import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {parse as parseYaml,stringify as yaml} from 'yaml';
import {AgentTemplateRegistry,computeAgentTemplateDigest,type AgentTemplateManifest} from './agent-template.js';
import {JobCatalog} from './job-catalog.js';
import {ActionRegistry,ArtifactStore,JobRuntime,ResourceLockManager,RunLedger,WorkerRegistry} from './job-runtime.js';
import {WorkParcelCoordinator,WorkParcelStore,type WorkParcelPlan} from './work-parcels.js';

function fixture(root:string,withAdaptation=false){const directory=path.join(root,'reviewer');fs.mkdirSync(directory,{recursive:true});const instructions='# Reviewer\n\nReport only evidence-backed findings. Zero findings is valid.\n';fs.writeFileSync(path.join(directory,'instructions.md'),instructions);const adaptation='Use the provider evidence-reference field without changing the portable review contract.\n';if(withAdaptation)fs.writeFileSync(path.join(directory,'provider.md'),adaptation);const adaptationDigest=createHash('sha256').update(adaptation).digest('hex'),manifest={spec_version:'1.0.0',id:'reviewer',version:'1.0.0',description:'Review bounded evidence.',intended_use:'Tests',role:'Reviewer',workflow:['Inspect','Report'],inputs:['Bound input'],output:{format:'JSON',requirements:['Evidence references']},requirements:{capabilities:['evidence.report'],permissions:[{kind:'read-only',scope:'bound-inputs'}],tools:[],context:['task'],memory:{mode:'none',requirements:[]}},compatible_jobs:['template-job'],limitations:['Static evidence is bounded.'],blocked_when:['Evidence is missing.'],provenance:{source:'fixture',url:'https://example.invalid/source',license:'MIT',upstream_revision:'a'.repeat(40),adapted_files:[]},qualification_refs:[],files:['instructions.md',...(withAdaptation?['provider.md']:[])],...(withAdaptation?{provider_adaptations:[{id:'provider-format',provider:'fixture',version:'1.0.0',file:'provider.md',content_digest:adaptationDigest}]}:{}),content_digest:'0'.repeat(64)} satisfies AgentTemplateManifest;const file=path.join(directory,'template.yaml'),source=yaml(manifest);fs.writeFileSync(file,source);const digest=computeAgentTemplateDigest(file,parseYaml(fs.readFileSync(file,'utf8')));fs.writeFileSync(file,fs.readFileSync(file,'utf8').replace(/^content_digest:\s*.*$/m,`content_digest: ${digest}`));return{directory,file,digest,adaptationDigest};}
function runtime(root:string){const actions=new ActionRegistry().register('template.action@1.0.0',async()=>({verification:['verified']})),catalog=new JobCatalog(actions.ids());catalog.addJob({apiVersion:'agent-control/v1',kind:'Job',metadata:{id:'template-job',name:'Template Job',version:'1.0.0'},spec:{priority:'normal',concurrency:'queue',steps:[{id:'execute',action:'template.action@1.0.0',requires:['evidence.report'],verification:['verified']}]}});const workers=new WorkerRegistry().register({id:'worker',capabilities:['evidence.report'],health:'healthy',capacity:1,active:0,observedAt:new Date().toISOString()});return new JobRuntime(catalog,actions,workers,new RunLedger(path.join(root,'runs.json')),new ArtifactStore(path.join(root,'artifacts')),new ResourceLockManager(path.join(root,'locks.json')));}

test('template registry validates immutable content and fails closed after tampering',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-template-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const value=fixture(root),registry=new AgentTemplateRegistry().loadDirectory(root);assert.equal(registry.get('reviewer@1.0.0').manifest.content_digest,value.digest);fs.appendFileSync(path.join(value.directory,'instructions.md'),'tampered');assert.throws(()=>new AgentTemplateRegistry().loadDirectory(root),/digest_mismatch/);});
test('readiness composes job capabilities, worker eligibility and scoped permissions',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-template-ready-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fixture(root);const registry=new AgentTemplateRegistry().loadDirectory(root),jobs=runtime(root),job=jobs.catalog.job('template-job@1.0.0')!;assert.deepEqual(registry.readiness('reviewer@1.0.0',job,jobs.workers.list(),[]).reasons,['permission:read-only:bound-inputs']);assert.equal(registry.readiness('reviewer@1.0.0',job,jobs.workers.list(),[{kind:'read-only',scope:'bound-inputs'}]).state,'READY');});
test('governed Work Parcel binds exact template, Job and input digests into the native run',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-template-run-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const value=fixture(path.join(root,'templates')),registry=new AgentTemplateRegistry().loadDirectory(path.join(root,'templates')),jobs=runtime(root),plan:WorkParcelPlan={objective:'Review the bounded fixture',planner:{kind:'deterministic',reason:'fixture'},stages:[{id:'execute',name:'Template Job',job:'template-job@1.0.0',template:{id:'reviewer',version:'1.0.0',digest:value.digest}}]},coordinator=new WorkParcelCoordinator(jobs,new WorkParcelStore(path.join(root,'parcels.json')),{plan:()=>plan},undefined,undefined,undefined,undefined,registry),parcel=await coordinator.submit('Review the bounded fixture','operator');await coordinator.tick();const run=jobs.ledger.get(coordinator.get(parcel.id).stages[0].runId!)!;assert.equal(run.templateBinding?.digest,value.digest);assert.match(run.trigger.parcelContext?.effectiveInstructions[0]??'',/Zero findings is valid/);assert.match(run.jobDigest??'',/^[a-f0-9]{64}$/);assert.match(run.inputsDigest??'',/^[a-f0-9]{64}$/);await jobs.tick();await coordinator.tick();assert.equal(coordinator.get(parcel.id).status,'SUCCEEDED');});
test('digest mismatch and unregistered provider adaptation are rejected before dispatch',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-template-reject-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const value=fixture(root),registry=new AgentTemplateRegistry().loadDirectory(root),jobs=runtime(root),job=jobs.catalog.job('template-job@1.0.0')!;assert.throws(()=>registry.binding({id:'reviewer',version:'1.0.0',digest:'f'.repeat(64)},job),/digest_mismatch/);assert.throws(()=>registry.binding({id:'reviewer',version:'1.0.0',digest:value.digest,providerAdaptation:{id:'x',version:'1',digest:'a'.repeat(64)}},job),/adaptation_unconfigured/);});
test('declared provider adaptation is independently digest-bound and appended after portable instructions',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-template-adaptation-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const value=fixture(root,true);assert.equal(computeAgentTemplateDigest(value.file,parseYaml(fs.readFileSync(value.file,'utf8'))),value.digest);const registry=new AgentTemplateRegistry().loadDirectory(root),job=runtime(root).catalog.job('template-job@1.0.0')!,binding=registry.binding({id:'reviewer',version:'1.0.0',digest:value.digest,providerAdaptation:{id:'provider-format',version:'1.0.0',digest:value.adaptationDigest}},job);assert.match(binding.portableInstructions,/Zero findings is valid/);assert.match(binding.providerAdaptation?.instructions??'',/provider evidence-reference field/);assert.throws(()=>registry.binding({id:'reviewer',version:'1.0.0',digest:value.digest,providerAdaptation:{id:'provider-format',version:'1.0.0',digest:'f'.repeat(64)}},job),/adaptation_digest_mismatch/);});

test('catalogue and readiness keep execution support separate from effectiveness',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-template-status-')),templates=path.join(root,'agent-templates');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fixture(templates);const statusDirectory=path.join(root,'qualifications','native-execution');fs.mkdirSync(statusDirectory,{recursive:true});fs.writeFileSync(path.join(statusDirectory,'status.json'),JSON.stringify({schema:'agent-control.agent-template-effectiveness/v1',records:[{template_id:'reviewer',template_version:'1.0.0',execution_support:'SUPPORTED',effectiveness:'FAILED_BOUNDED_QUALIFICATION',evidence:'report.json',limitations:['No accepted held-out run.']}]}));const registry=new AgentTemplateRegistry().loadDirectory(templates),record=registry.get('reviewer@1.0.0'),jobs=runtime(root),job=jobs.catalog.job('template-job@1.0.0')!;assert.equal(record.effectiveness.effectiveness,'FAILED_BOUNDED_QUALIFICATION');const readiness=registry.readiness('reviewer@1.0.0',job,jobs.workers.list(),[{kind:'read-only',scope:'bound-inputs'}]);assert.equal(readiness.state,'READY');assert.equal(readiness.effectiveness.effectiveness,'FAILED_BOUNDED_QUALIFICATION');});
