import assert from 'node:assert/strict';
import test from 'node:test';
import {defaultCapabilities, type LaneState, type WorkspaceState} from '../state.js';
import {AgentControlService} from './application-service.js';
import {PtyRegistry} from './pty.js';
import {chooseRoute, type RouteOption, type RouteRequest} from './routing.js';
import {TokenAwareBatonRuntime} from './token-aware-baton-routing.js';
import {SkillLearningRuntime} from './skill-learning.js';

const now = () => new Date().toISOString();
function lane(id: number, priority = 1): LaneState { return {id, name: `Lane ${id}`, status: 'waiting', model: 'qualified-model', reasoning: 'medium', context: '0', lines: [], contract: {version: 2, laneId: id, goal: `goal-${id}`, constraints: [], cwd: '/tmp', priority, mode: 'auto', capabilities: defaultCapabilities(), resourceLocks: {}, modelLock: null, sharedTaskIds: [], updatedAt: now()}, baton: {version: 1, laneId: id, revision: 1, status: 'waiting', progress: [], hypothesis: '', evidence: [], changes: [], nextAction: 'schedule', openQuestions: [], model: 'qualified-model', reasoning: 'medium', updatedAt: now()}, lease: {laneId: id, holder: null, acquiredAt: null, expiresAt: null}}; }
function setup() { const state: WorkspaceState = {version: 1, paused: false, lastRestorePoint: null, lanes: [lane(1, 5), lane(2, 1)]}; const ptys = new PtyRegistry(); ptys.upsert({id: 'pty-1', cwd: '/tmp', command: 'agent', recovery: 'reattachable'}, '1'); ptys.attach('pty-1', 'agent-a', 'own'); return {state, ptys, service: new AgentControlService(state, ptys, undefined, '3.1.0-test', () => {})}; }

test('TUI and web projections share the same authoritative lane object', () => { const {state, service} = setup(); service.submitTask(1, 'new objective', 'tui-operator'); assert.equal(state.lanes[0].contract.goal, 'new objective'); assert.equal(service.snapshot().lanes[0].task, 'new objective'); service.setPriority(1, 9, 'web-operator'); assert.equal(state.lanes[0].contract.priority, 9); });
test('status projection has a versioned authoritative command and dashboard contract', () => { const projection = setup().service.snapshot(); assert.equal(projection.schema, 'agent-control.system-status/v1'); assert.equal(projection.authority, 'AgentControlService'); });
test('status projection contains live token routing without conflating lifetime tokens and current context', () => { const {service} = setup(), routing = new TokenAwareBatonRuntime(); service.configureProjection({tokenBatonRouting: routing}); routing.observe({threadId: 'thread:one', parcelId: 'parcel:one', agentId: 'agent:one', providerId: 'openai', modelId: 'sol', elapsedMs: 1_000, cumulative: {inputTokens: 100_000, freshInputTokens: 75_000, cachedInputTokens: 25_000, outputTokens: 1_000, totalTokens: 101_000}, context: {tokens: 20_000, limitTokens: 128_000, authority: 'authoritative', source: 'provider'}, cost: {amount: .2, currency: 'USD', authority: 'estimated', source: 'pricing'}}); const thread = service.snapshot().tokenBatonRouting.threads[0]; assert.equal(thread.latest.cumulative.totalTokens, 101_000); assert.equal(thread.latest.cumulative.freshInputTokens, 75_000); assert.equal(thread.latest.cumulative.cachedInputTokens, 25_000); assert.equal(thread.latest.context.tokens, 20_000); assert.equal(thread.latest.contextPercent, 15.625); });
test('learned specialist projection is read-only durable runtime state and does not imply cache warmth',()=>{const {service}=setup(),skills=new SkillLearningRuntime(undefined,{routingEnabled:false});service.configureProjection({learnedSkills:skills});skills.observe({label:'Fixture specialist',taskClass:'fixture',capabilities:['fixture.classify'],sourceEvidence:['fixture:evidence'],reason:'Observed bounded failures',expectedBenefit:'Higher accuracy',actor:'operator'});const projection=service.learnedSpecialists();assert.equal(projection.candidates.length,1);assert.equal(projection.specialists.length,0);assert.equal(projection.policy?.routingEnabled,false);assert.doesNotMatch(JSON.stringify(projection),/warm|cache/i);});
test('dashboard controls do not mutate leases or acquire scheduling authority', () => { const {state, service} = setup(); service.plane.acquireLease(state.lanes[0], 'agent-a'); const lease = structuredClone(state.lanes[0].lease); service.pauseLane(1, 'web-operator'); service.setPriority(1, 99, 'web-operator'); assert.deepEqual(state.lanes[0].lease, lease); assert.equal(service.snapshot().scheduler.nextLaneId, 2); });
test('human takeover is unconditional and blocks resume until ownership is deliberately returned', () => { const {ptys, service} = setup(); service.humanTakeover(1, 'operator'); assert.equal(ptys.attached('pty-1').find(item => item.access === 'own')?.actorId, 'human:operator'); assert.throws(() => service.resumeLane(1, 'web-operator'), /human_owns_pty/); service.returnOwnership(1, 'operator', 'agent-b'); assert.equal(ptys.attached('pty-1').find(item => item.access === 'own')?.actorId, 'agent-b'); assert.equal(service.resumeLane(1, 'web-operator').status, 'waiting'); });
test('reroute is a request and cannot directly substitute the lane model', () => { const {state, service} = setup(); const before = state.lanes[0].model; const request = service.requestReroute(1, 'web-operator', 'latency changed'); assert.equal(request.requiresApproval, true); assert.equal(state.lanes[0].model, before); });
test('routing rationale is persisted with lane state and restored into projections', () => { const {state, ptys, service} = setup(); const option: RouteOption = {id: 'local', providerId: 'local', model: 'm', location: 'local', health: 'healthy', qualifiedCapabilities: ['coding'], tools: [], contextCapacity: 32000, capabilityScore: .9, reliability: .9, estimatedLatencyMs: 100, estimatedDurationMs: 1000, estimatedCost: 0, available: true}; const request: RouteRequest = {capabilities: ['coding'], urgency: 'normal', priority: 1, costSensitivity: 1, latencySensitivity: .5, reliabilitySensitivity: .5, privacy: 'standard', localComputeAvailable: true, gpuAvailable: true}; service.recordRoute(1, chooseRoute(request, [option])); const restored = new AgentControlService(structuredClone(state), ptys, undefined, '3.1.0-test', () => {}); assert.equal(restored.latestRoute(1)?.selected.id, 'local'); assert.match(restored.lane(1).routeReason ?? '', /qualified for coding/); });
test('verification changes are exposed as typed events without changing lease or ownership', () => { const {state, ptys, service} = setup(); const lease = structuredClone(state.lanes[0].lease), owner = ptys.attached('pty-1').find(item => item.access === 'own')?.actorId; const events: string[] = []; service.events.subscribe(event => events.push(event.type)); service.setVerificationPolicy(1, {required: ['test_result']}, 'agent-a'); service.recordClaim(1, 'done', 'agent-a'); service.addVerificationEvidence(1, {type: 'test_result', description: 'suite', status: 'passed'}, 'agent-a'); assert.equal(service.verifyClaim(1, 'judge').ok, true); assert.ok(events.every(type => type === 'verification.changed')); assert.deepEqual(state.lanes[0].lease, lease); assert.equal(ptys.attached('pty-1').find(item => item.access === 'own')?.actorId, owner); });

test('global pause and resume preserves meaningful lane state and human ownership fences', () => {
  const {state, ptys, service} = setup();
  state.lanes = [
    {...lane(1), status: 'working'}, {...lane(2), status: 'waiting'}, {...lane(3), status: 'cancelled'},
    {...lane(4), status: 'error'}, {...lane(5), status: 'paused'}, {...lane(6), status: 'working'},
  ];
  ptys.upsert({id: 'pty-human', cwd: '/tmp', command: 'agent', recovery: 'reattachable'}, '6');
  ptys.attach('pty-human', 'human:operator', 'own');
  service.setSystemPaused(true, 'operator');
  assert.ok(state.lanes.every(value => value.status === 'paused'));
  state.lanes[2].status = 'cancelled';
  state.lanes[3].status = 'error';
  service.setSystemPaused(false, 'operator');
  assert.deepEqual(state.lanes.map(value => value.status), ['working', 'waiting', 'cancelled', 'error', 'paused', 'paused']);
});

test('ownership return without PTY takeover preserves lane state and emits no transfer',()=>{const {state,service}=setup();service.pauseLane(2,'operator');const before=structuredClone(state),events:string[]=[];service.events.subscribe(e=>events.push(e.type));assert.throws(()=>service.returnOwnership(2,'operator','agent-b'),/human_takeover_not_active/);assert.deepEqual(state,before);assert.deepEqual(events,[]);});
test('ownership return validates every session before transferring any control',()=>{const {state,service,ptys}=setup();service.humanTakeover(1,'operator');ptys.upsert({id:'pty-second',cwd:'/tmp',command:'agent',recovery:'reattachable'},'1');ptys.attach('pty-second','agent-a','own');const before=structuredClone(state);assert.throws(()=>service.returnOwnership(1,'operator','agent-b'),/human_takeover_not_active/);assert.equal(ptys.attached('pty-1').find(a=>a.access==='own')?.actorId,'human:operator');assert.deepEqual(state,before);});
