import {annotateDiagnosticHistory,DIAGNOSTIC_CLASSIFIER_VERSION} from './diagnostic-classification.js';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {randomBytes,randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {EnvironmentDiscoveryRuntime} from './environment-discovery.js';
import type {JobRuntime} from './job-runtime.js';
import type {OwnedExecution} from './owned-process.js';
import {DiagnosticSanitizer,DIAGNOSTIC_SANITIZER_VERSION} from './diagnostic-sanitization.js';
import {diagnosticHash,normalizeDiagnostic,correlateDiagnostics,diagnosticReport} from './diagnostic-analysis.js';
import {DEFAULT_DIAGNOSTIC_PRIVACY,type DiagnosticAssessment,type DiagnosticInventory,type DiagnosticPermission,type DiagnosticSourceAdapter,type DiagnosticSourceRecord} from './diagnostic-types.js';

export const DIAGNOSTIC_JOB='architecture-health';
export const DIAGNOSTIC_CAPABILITY='agent-control.architecture-diagnostics.read';
const id=()=>randomUUID(),now=()=>new Date().toISOString();
const policy=z.enum(['KEEP','REDACT','PSEUDONYMIZE']);
const grantSchema=z.object({inventoryId:z.string(),inventorySha256:z.string(),scope:z.enum(['NONE','ERRORS_ONLY','RECENT_SAMPLE','FULL_DIAGNOSTIC_SCAN']),sourceIds:z.array(z.string()).max(32),bounds:z.object({since:z.iso.datetime(),until:z.iso.datetime(),maxSources:z.number().int().min(1).max(32),maxBytesPerSource:z.number().int().min(256).max(1048576),maxTotalBytes:z.number().int().min(256).max(8388608),maxLinesPerSource:z.number().int().min(1).max(10000),maxEvents:z.number().int().min(1).max(2000),timeoutMs:z.number().int().min(100).max(30000)}).strict(),privacy:z.object({usernames:policy,hostnames:policy,ipAddresses:policy,macAddresses:policy,paths:policy,emails:policy,identifiers:policy}).strict().optional(),externalModelProcessing:z.boolean().default(false),model:z.object({modelId:z.string().min(1).max(200),nodeId:z.string().min(1).max(200)}).strict().nullable().default(null),reason:z.string().min(1).max(1000)}).strict();
export interface DiagnosticModelPort {analyze(p:DiagnosticPermission,events:DiagnosticAssessment['events'],sanitizer:DiagnosticSanitizer,signal:AbortSignal,context:{runId:string;jobId:string;check:()=>void}):Promise<{analysis:DiagnosticAssessment['modelAnalysis'];hypotheses:Array<{text:string;eventIds:string[]}>}>;}
type Audit={sequence:number;at:string;kind:string;payload:any;previous:string|null;sha256:string};
/** Append-only local evidence. Hash linkage detects accidental edits, not a malicious host administrator. */
export class DiagnosticStore {
 readonly audit:Audit[]=[];
 constructor(readonly root:string){fs.mkdirSync(root,{recursive:true,mode:0o700});const file=path.join(root,'audit.jsonl');if(fs.existsSync(file)){for(const line of fs.readFileSync(file,'utf8').split('\n').filter(Boolean)){const item=JSON.parse(line) as Audit,{sha256,...rest}=item;if(item.sequence!==this.audit.length||item.previous!==(this.audit.at(-1)?.sha256??null)||diagnosticHash(rest)!==sha256)throw Error('diagnostic_audit_integrity_failed');this.audit.push(item);}}}
 append(kind:string,payload:unknown){const entry={sequence:this.audit.length,at:now(),kind,payload:structuredClone(payload),previous:this.audit.at(-1)?.sha256??null},record={...entry,sha256:diagnosticHash(entry)};fs.appendFileSync(path.join(this.root,'audit.jsonl'),JSON.stringify(record)+'\n',{mode:0o600,flush:true});this.audit.push(record);}
 salt(){const f=path.join(this.root,'privacy.key');if(!fs.existsSync(f))fs.writeFileSync(f,randomBytes(32).toString('hex'),{mode:0o600,flag:'wx'});return fs.readFileSync(f,'utf8');}
 save(a:DiagnosticAssessment){fs.writeFileSync(path.join(this.root,a.id+'.json'),JSON.stringify(a,null,2)+'\n',{mode:0o600,flag:'wx',flush:true});fs.writeFileSync(path.join(this.root,a.id+'.md'),diagnosticReport(a),{mode:0o600,flag:'wx',flush:true});this.append('ASSESSMENT',{id:a.id,permissionId:a.permissionId,sha256:a.sha256,createdAt:a.createdAt,findingCount:a.findings.length});}
 read(id:string){if(!/^assessment-[a-f0-9-]+$/.test(id))throw Error('diagnostic_assessment_missing');const registered=this.audit.find(e=>e.kind==='ASSESSMENT'&&e.payload.id===id);if(!registered)throw Error('diagnostic_assessment_missing');const value=JSON.parse(fs.readFileSync(path.join(this.root,id+'.json'),'utf8')) as DiagnosticAssessment,{sha256,...rest}=value;if(diagnosticHash(rest)!==sha256||registered.payload.sha256!==sha256)throw Error('diagnostic_assessment_integrity_failed');return value;}
}
export class ArchitectureDiagnostics {
 private inventories=new Map<string,{public:DiagnosticInventory;records:Map<string,DiagnosticSourceRecord>}>();
 private permissions=new Map<string,DiagnosticPermission>();private active=new Map<string,AbortController>();
 readonly sanitizer:DiagnosticSanitizer;
 constructor(readonly store:DiagnosticStore,readonly adapters:DiagnosticSourceAdapter[],private discovery:()=>ReturnType<EnvironmentDiscoveryRuntime['projection']>['latest'],private model?:DiagnosticModelPort){
  this.sanitizer=new DiagnosticSanitizer(store.salt(),DEFAULT_DIAGNOSTIC_PRIVACY,{hostnames:[os.hostname()],usernames:[os.userInfo().username]});
  if(new Set(adapters.map(a=>a.id)).size!==adapters.length)throw Error('diagnostic_adapter_duplicate');
  for(const e of store.audit){if(e.kind==='PERMISSION')this.permissions.set(e.payload.id,structuredClone(e.payload));if(e.kind==='REVOKED'){const p=this.permissions.get(e.payload.id);if(p)p.revokedAt=e.at;}}
 }
 projection(){return{inventory:[...this.inventories.values()].at(-1)?.public??null,permissions:[...this.permissions.values()].map(p=>({...p,active:!p.revokedAt&&Date.parse(p.expiresAt)>Date.now()&&p.scope!=='NONE'})),history:this.store.audit.filter(e=>e.kind==='ASSESSMENT').map(e=>e.payload),active:[...this.active.keys()],readOnly:true,defaultScope:'NONE',remediationAuthority:'PROPOSAL_ONLY'};}
 async enumerate(){
  const scan=this.discovery(),items=scan?.items??[],architecture:DiagnosticInventory['architecture']={discoveryScanId:scan?.id??null,observedAt:now(),components:items.map(i=>({id:i.id,label:i.label,kind:i.kind,nodeId:i.nodeId,attributes:i.attributes,provenance:i.provenance})),edges:items.flatMap(i=>(i.relatedIds??[]).map(to=>({from:i.id,to,kind:'RELATED' as const,authority:'OBSERVED' as const,evidence:'environment discovery relatedIds; dependency not established'})))};
  for(const c of [{id:'host:controller',label:'Controller host',kind:'MACHINE'},{id:'resource:kernel',label:'Host kernel',kind:'KERNEL'}])if(!architecture.components.some(e=>e.id===c.id))architecture.components.push({...c,nodeId:'controller',attributes:{},provenance:[{method:'local diagnostic adapter metadata'}]});
  const sources:DiagnosticSourceRecord[]=[],failures:DiagnosticInventory['failures']=[];
  for(const adapter of this.adapters){try{const result=await adapter.enumerate({items,signal:AbortSignal.timeout(15000)});sources.push(...result.sources);architecture.components.push(...(result.components??[]));architecture.edges.push(...(result.edges??[]));}catch{failures.push({adapterId:adapter.id,reason:'metadata enumeration unavailable or timed out'});}}
  architecture.components=[...new Map(architecture.components.map(c=>[c.id,c])).values()];const componentIds=new Set(architecture.components.map(c=>c.id));architecture.edges=architecture.edges.filter(e=>componentIds.has(e.from)&&componentIds.has(e.to));
  const publicSources=[...new Map(sources.map(s=>[s.id,s])).values()].map(({locator,...s})=>s),inventory:DiagnosticInventory={id:`inventory-${id()}`,at:now(),sha256:diagnosticHash({sources:publicSources,architecture}),sources:publicSources,architecture,failures,contentsRead:false};this.inventories.set(inventory.id,{public:inventory,records:new Map(sources.map(s=>[s.id,s]))});this.store.append('ENUMERATION',{id:inventory.id,sha256:inventory.sha256,sourceCount:sources.length,contentsRead:false});return structuredClone(inventory);
 }
 grant(input:unknown,actor:string){
  const parsed=grantSchema.safeParse(input);if(!parsed.success)throw Error('diagnostic_permission_invalid');const v=parsed.data,inventory=this.inventories.get(v.inventoryId)?.public;
  if(!inventory||inventory.sha256!==v.inventorySha256)throw Error('diagnostic_inventory_stale');const span=Date.parse(v.bounds.until)-Date.parse(v.bounds.since);if(span<=0||span>7*86400000||Date.parse(v.bounds.until)>Date.now()+60000||v.scope==='RECENT_SAMPLE'&&span>86400000)throw Error('diagnostic_window_invalid');
  if(new Set(v.sourceIds).size!==v.sourceIds.length||v.sourceIds.length>v.bounds.maxSources||v.sourceIds.some(i=>!inventory.sources.some(s=>s.id===i))||v.scope!=='NONE'&&!v.sourceIds.length)throw Error('diagnostic_sources_invalid');
  const sources=v.scope==='NONE'?[]:v.sourceIds;const p:DiagnosticPermission={...v,id:`permission-${id()}`,actor:this.sanitizer.text(actor).text,requestedByJob:DIAGNOSTIC_JOB,grantedAt:now(),expiresAt:new Date(Date.now()+3600000).toISOString(),revokedAt:null,sourceIds:sources,excludedSourceIds:inventory.sources.filter(s=>!sources.includes(s.id)).map(s=>s.id),sourceIdentities:Object.fromEntries(inventory.sources.filter(s=>sources.includes(s.id)).map(s=>[s.id,s.identity])),privacy:v.privacy??{...DEFAULT_DIAGNOSTIC_PRIVACY},reason:this.sanitizer.text(v.reason).text};this.store.append('PERMISSION',p);this.permissions.set(p.id,p);return structuredClone(p);
 }
 revoke(id:string,actor:string){const p=this.permissions.get(id);if(!p)throw Error('diagnostic_permission_missing');if(!p.revokedAt){this.store.append('REVOKED',{id,actor:this.sanitizer.text(actor).text});p.revokedAt=now();this.active.get(id)?.abort();}return structuredClone(p);}
 assertPermission(id:string){const p=this.permissions.get(id);if(!p||p.scope==='NONE'||p.revokedAt||Date.parse(p.expiresAt)<=Date.now())throw Error('diagnostic_permission_denied');return p;}
 assessment(id:string){const a=this.store.read(id);this.assertPermission(a.permissionId);return a;}
 report(id:string){return diagnosticReport(this.assessment(id));}
 async observe(permissionId:string,runId:string,jobId:string,signal:AbortSignal,owned?:OwnedExecution,assertExecution?:()=>void){
  const permission=this.assertPermission(permissionId),inventory=this.inventories.get(permission.inventoryId);if(!inventory||jobId!==DIAGNOSTIC_JOB)throw Error('diagnostic_permission_context_invalid');if(this.active.has(permissionId))throw Error('diagnostic_already_running');
  const controller=new AbortController(),combined=AbortSignal.any([signal,controller.signal,AbortSignal.timeout(Math.min(120000,permission.bounds.timeoutMs*permission.sourceIds.length+30000))]);this.active.set(permissionId,controller);
  const check=()=>{assertExecution?.();combined.throwIfAborted();this.assertPermission(permissionId);};const safe=new DiagnosticSanitizer(this.store.salt(),permission.privacy,{hostnames:[os.hostname()],usernames:[os.userInfo().username]});
  try{
   this.store.append('COLLECTION_STARTED',{permissionId,runId,jobId});const events:DiagnosticAssessment['events']=[],evidence:DiagnosticAssessment['evidence']=[],coverage:DiagnosticAssessment['coverage']=[];let bytes=0,redactions=0;
   for(const [sourceIndex,sourceId] of permission.sourceIds.entries()){check();const source=inventory.records.get(sourceId)!;if(bytes>=permission.bounds.maxTotalBytes||events.length>=permission.bounds.maxEvents){coverage.push({sourceId,status:'BUDGET_EXHAUSTED',bytesRead:0,linesExamined:0,events:0,malformed:0,outsideWindow:0,unknownTime:0,truncated:true,sampling:'source not read'});continue;}
    // Reserve event capacity for every remaining source; unused shares roll forward.
    const scoped={...permission,bounds:{...permission.bounds,maxBytesPerSource:Math.min(permission.bounds.maxBytesPerSource,permission.bounds.maxTotalBytes-bytes),maxEvents:Math.ceil((permission.bounds.maxEvents-events.length)/(permission.sourceIds.length-sourceIndex))}};
    const adapter=this.adapters.find(a=>a.id===source.adapterId)!;let collection;
    try{collection=await adapter.collect(source,scoped,combined,owned);}catch{check();collection={sourceId,status:'UNAVAILABLE' as const,text:'',bytesRead:0,truncated:false,sampling:'collection unavailable',locator:{}};}check();
    // Adapter outputs are bounded again at the engine boundary.
    const limited=Buffer.from(collection.text).subarray(0,scoped.bounds.maxBytesPerSource).toString('utf8');collection.truncated ||= limited.length<collection.text.length;collection.text=limited;collection.bytesRead=Math.min(Math.max(collection.bytesRead,Buffer.byteLength(limited)),scoped.bounds.maxBytesPerSource);bytes+=collection.bytesRead;
    const result=normalizeDiagnostic(collection,source,scoped,safe,inventory.public.architecture,now());events.push(...result.events);evidence.push(...result.evidence);coverage.push(result.coverage);redactions+=result.redactions;collection.text='';
   }
   check();events.sort((a,b)=>(a.timestamp??'').localeCompare(b.timestamp??''));const incomplete=coverage.some(c=>c.truncated||c.status!=='COLLECTED'||c.malformed>0||c.unknownTime>0)||permission.excludedSourceIds.length>0;
   annotateDiagnosticHistory(events);
   const findings=correlateDiagnostics(events,inventory.public.architecture,incomplete);let modelAnalysis:DiagnosticAssessment['modelAnalysis']={status:'NOT_REQUESTED',modelId:null,providerId:null,invocationId:null,reason:'Deterministic local analysis; no model request made.'};
   if(permission.model){if(!this.model)modelAnalysis={...modelAnalysis,status:'UNAVAILABLE',reason:'Normal model abstraction is unavailable.'};else{check();try{const result=await this.model.analyze(permission,events,safe,combined,{runId,jobId,check});check();modelAnalysis=result.analysis;for(const hypothesis of result.hypotheses){const refs=events.filter(e=>hypothesis.eventIds.includes(e.id));if(!refs.length)continue;const base=findings.find(f=>f.eventIds.some(i=>hypothesis.eventIds.includes(i)));if(!base)continue;findings.push({...structuredClone(base),id:`finding-${id()}`,key:`model:${modelAnalysis.invocationId}`,title:'Model hypothesis requiring verification',status:'INFERRED',inference:safe.text(hypothesis.text).text,producer:{kind:'MODEL',id:modelAnalysis.modelId??'unknown',version:'qualified route',invocationId:modelAnalysis.invocationId??undefined},analysisPath:[...base.analysisPath,'optional governed model hypothesis'],eventIds:refs.map(e=>e.id),evidenceRefs:refs.map(e=>e.evidenceRef)});}}catch{check();modelAnalysis={...modelAnalysis,status:'UNAVAILABLE',reason:'Model analysis failed; deterministic findings preserved.'};}}}
   const architecture=structuredClone(inventory.public.architecture);const idMap=new Map(architecture.components.map(c=>[c.id,safe.identifier('identifiers',c.id)!]));const safeId=(value:string)=>idMap.get(value)??safe.identifier('identifiers',value)!;for(const e of events)if(e.componentId)e.componentId=safeId(e.componentId);for(const f of findings){f.componentIds=f.componentIds.map(safeId);f.key=diagnosticHash(f.key);}for(const e of architecture.edges){e.from=safeId(e.from);e.to=safeId(e.to);e.evidence=safe.text(e.evidence).text;}for(const c of architecture.components){c.id=safeId(c.id);}for(const c of architecture.components){c.label=safe.text(c.label).text;c.nodeId=safe.identifier('identifiers',c.nodeId)!;c.attributes=safe.value(c.attributes) as typeof c.attributes;c.provenance=safe.value(c.provenance) as unknown[];}
   const history=this.store.audit.filter(e=>e.kind==='ASSESSMENT'),previous=history.length?this.store.read(history.at(-1)!.payload.id):null;
   const a:Omit<DiagnosticAssessment,'sha256'>={collectionStatus:coverage.some(c=>c.truncated||c.status!=='COLLECTED'||c.malformed>0||c.unknownTime>0)?'PARTIAL':'COMPLETE',classifierVersion:DIAGNOSTIC_CLASSIFIER_VERSION,schema:'agent-control.architecture-diagnostics/v1',id:`assessment-${id()}`,createdAt:now(),permissionId,runId,jobId,inventoryId:inventory.public.id,permission:structuredClone(permission),architecture,events,evidence,findings,health:architecture.components.map(c=>{const relevant=events.filter(e=>e.componentId===c.id),fs=findings.filter(f=>f.componentIds.includes(c.id)),errors=relevant.filter(e=>e.severity==='ERROR');return{componentId:c.id,state:'UNKNOWN',historicalState:errors.reduce((n,e)=>n+e.count,0)>=3?'RECURRING_FAILURE':errors.length?'DEGRADED':relevant.some(e=>e.severity==='WARNING')?'WARNING':'UNKNOWN',eventIds:relevant.map(e=>e.id),findingIds:fs.map(f=>f.id),basis:errors.length?'Historical errors were recorded; current incident status is UNKNOWN. Expected test effects and production impact require review.':'Bounded passive evidence does not establish current health.'};}),coverage,sanitization:{version:DIAGNOSTIC_SANITIZER_VERSION,status:'PASS',rawRetained:false,redactions,policy:permission.privacy},modelAnalysis,limitations:['Historical sample; health overlays do not establish current availability.','Counts are lower bounds within accessible selected sources. Mirrored journal/file records are not independent witnesses.','Missing timezone or timestamp excludes an event from time-bounded analysis.','Heuristic sanitization cannot detect every possible secret. Keep external processing off for sensitive estates.','Local SHA256 and append-only records are not an independent signed external anchor.','No remediation is executed. All proposals require a separate governed job.',...(incomplete?['Coverage is incomplete due to exclusions, bounds, inaccessible or malformed records.']:[])],previousAssessmentId:previous?.id??null,comparison:{state:'NOT_COMPARABLE',reason:'Coverage, source identities and event-window overlap must match; sample counts alone cannot prove reliability change.',previousFindings:previous?.findings.length??null,currentFindings:findings.length}};
   if(previous&&diagnosticHash(previous.permission.sourceIdentities)===diagnosticHash(permission.sourceIdentities)&&diagnosticHash(previous.permission.bounds)===diagnosticHash(permission.bounds)&&previous.permission.scope===permission.scope&&!incomplete&&!previous.coverage.some(c=>c.truncated||c.status!=='COLLECTED'))a.comparison={...a.comparison,state:'COMPARABLE',reason:'Same source identities, scope and exact window; compare repeated assessment results, not a reliability trend.'};
   check();const result={...a,sha256:diagnosticHash(a)};this.store.save(result);return result;
  }catch{this.store.append('COLLECTION_STOPPED',{permissionId,runId,reason:controller.signal.aborted?'PERMISSION_REVOKED':signal.aborted?'JOB_CANCELLED':'FAILED_OR_TIMED_OUT'});throw Error(controller.signal.aborted?'diagnostic_permission_denied':signal.aborted?'diagnostic_cancelled':'diagnostic_collection_failed');}finally{this.active.delete(permissionId);}
 }
}
export function registerArchitectureDiagnostics(runtime:JobRuntime,diagnostics:ArchitectureDiagnostics){
 runtime.workers.registerControllerInternal({id:'agent-control:diagnostic-observer',capabilities:[DIAGNOSTIC_CAPABILITY],health:'healthy',capacity:1,active:0,labels:{origin:'agent-control-built-in',scope:'permission-governed-controller-local-read-only'},observedAt:now()});
 const action='discovery.architecture-health@1.0.0';runtime.actions.registerReadOnly(action,async context=>{const permission=diagnostics.assertPermission(String(context.parameters.permissionId??''));if(permission.actor!==diagnostics.sanitizer.text(context.run.trigger.actor).text)throw Error('diagnostic_permission_actor_mismatch');const a=await diagnostics.observe(String(context.parameters.permissionId??''),context.run.id,context.run.jobId,context.signal,context.ownedExecution,()=>context.execution?.assertActive());return{artifacts:[{name:'architecture-health',value:{assessmentId:a.id,sha256:a.sha256,permissionId:a.permissionId,collectionStatus:a.collectionStatus,currentIncidentStatus:'UNKNOWN',findings:a.findings.length,report:'Governed Diagnostics evidence endpoint; permission required.'},type:'application/json',schema:'agent-control.architecture-diagnostics-receipt/v1',version:'1.0.0'}],evidence:[`assessment:${a.id}:${a.sha256}`],verification:['diagnostic-assessment-recorded']};});runtime.catalog.knownActions?.add(action);
 runtime.catalog.addJob({apiVersion:'agent-control/v1',kind:'Job',metadata:{id:DIAGNOSTIC_JOB,name:'Architecture health discovery',version:'1.0.0',description:'Observe explicitly permitted diagnostic sources, sanitize, correlate and propose investigations. Read-only.'},spec:{priority:'low',concurrency:'queue',parameters:{permissionId:{type:'string',required:true}},steps:[{id:'observe-correlate',action,requires:[DIAGNOSTIC_CAPABILITY],verification:['diagnostic-assessment-recorded'],outputs:[{name:'architecture-health',type:'application/json',schema:'agent-control.architecture-diagnostics-receipt/v1',version:'1.0.0'}]}]}});
}
