import assert from 'node:assert/strict'; import test from 'node:test';
import {browserCapability, pixelChatGptState, selectBrowserRoute, type BrowserRoute} from './browser-capabilities.js';
const routes: BrowserRoute[] = [
  {id:'headless',nodeId:'linux',capabilities:[browserCapability.headless,browserCapability.screenshot],state:'AVAILABLE',engine:'Chromium/Playwright',transport:'local',authenticated:false,expectedCost:0,expectedLatencyMs:100,locality:'local',reason:'qualified'},
  {id:'web',nodeId:'desktop',capabilities:[browserCapability.chatGptWeb,browserCapability.authenticated],state:'AUTH_REQUIRED',engine:'Edge',transport:'interactive',authenticated:true,locality:'remote',reason:'no approved session bridge'},
  {id:'pixel',nodeId:'android',capabilities:[browserCapability.chatGptAndroid,browserCapability.androidUi],state:'DEVICE_OFFLINE',engine:'Android UI',transport:'adb',authenticated:true,locality:'remote',reason:'device offline'},
];
test('router distinguishes headless, web and Android without explicit-route substitution',()=>{assert.equal(selectBrowserRoute({capability:browserCapability.headless},routes).selected.id,'headless');assert.throws(()=>selectBrowserRoute({capability:browserCapability.chatGptWeb,explicitRouteId:'web'},routes),/AUTH_REQUIRED/);assert.throws(()=>selectBrowserRoute({capability:browserCapability.chatGptAndroid,explicitRouteId:'pixel'},routes),/DEVICE_OFFLINE/);assert.throws(()=>selectBrowserRoute({capability:browserCapability.chatGptAndroid,explicitRouteId:'headless'},routes),/capability_missing/);});
test('Pixel state is fail-closed and distinguishes offline, unavailable, auth and available',()=>{assert.equal(pixelChatGptState({online:false,authorisedTransport:false,uiAutomation:false,authenticatedSession:false}),'DEVICE_OFFLINE');assert.equal(pixelChatGptState({online:true,authorisedTransport:false,uiAutomation:false,authenticatedSession:false}),'UNAVAILABLE');assert.equal(pixelChatGptState({online:true,authorisedTransport:true,uiAutomation:true,authenticatedSession:false}),'AUTH_REQUIRED');assert.equal(pixelChatGptState({online:true,authorisedTransport:true,uiAutomation:true,authenticatedSession:true}),'AVAILABLE');});
