import {createHash,randomUUID} from 'node:crypto';
import fs from 'node:fs';import path from 'node:path';
import type {ExecutionCleanupReport,OwnedExecution} from './owned-process.js';
import {assertNoSensitiveMaterial,redactSensitiveText,redactSensitiveValue} from './security-redaction.js';

export type KillScopeKind='JOB'|'LANE'|'WORKER'|'MODEL'|'NODE'|'WORKSPACE'|'ESTATE';
export type ContainmentResponse='WARN'|'BLOCK_ACTION'|'PAUSE_JOB'|'KILL_JOB'|'KILL_WORKER'|'ISOLATE_NODE'|'ESTATE_EMERGENCY_STOP';
export type StopState='STOP_REQUESTED'|'STOP_CONFIRMED'|'STOP_UNCONFIRMED'|'WORKER_QUARANTINED';
export type RecoveryState='KILLED'|'QUARANTINED'|'INSPECTED'|'RESET'|'REQUALIFIED'|'AVAILABLE';
export interface KillScope{kind:KillScopeKind;id:string;}
export interface ExecutionScopeEnvelope{schema:'agent-control.execution-scope-envelope/v1';id:string;workspace:string;repository:string|null;filesystem:{readable:string[];writable:string[]};network:{destinations:string[];ports:number[]};devices:string[];runtimes:string[];credentialReferences:string[];tools:string[];apis:string[];models:string[];subprocesses:string[];maximum:{runtimeMs:number;cpuPercent:number;ramBytes:number;gpuPercent:number;vramBytes:number;diskBytes:number;networkBytes:number;externalEffects:number};createdAt:string;sha256:string;}
export interface ScopeAction{filesystemPath?:string;networkDestination?:string;port?:number;device?:string;runtime?:string;credentialReference?:string;tool?:string;api?:string;model?:string;subprocess?:string;elapsedMs?:number;cpuPercent?:number;ramBytes?:number;gpuPercent?:number;vramBytes?:number;diskBytes?:number;networkBytes?:number;externalEffects?:number;}
export interface ScopeAssessment{allowed:boolean;response:ContainmentResponse;violations:string[];envelopeId:string;evidence:string[];}
export interface ExecutionOwnership{id:string;scopes:KillScope[];execution:OwnedExecution;exclusive:boolean;leaseRevoker?:()=>Promise<void>;isolate?:()=>Promise<boolean>;}
export interface KillRecord{id:string;requestedAt:string;completedAt:string|null;actor:string;reason:string;scope:KillScope;state:StopState;affected:string[];sharedSkipped:string[];cleanup:ExecutionCleanupReport[];leaseRevocation:'NOT_APPLICABLE'|'CONFIRMED'|'UNCONFIRMED';evidence:string[];recovery:RecoveryState;recoveryEvents?:{state:RecoveryState;at:string;actor:string;evidence:string}[];}
export interface ContainmentSchedulingEligibility{eligible:boolean;state:'AVAILABLE'|'QUARANTINED';reason:string|null;scopes:KillScope[];killIds:string[];}
export interface ContainmentTimelineEvent{id:string;killId:string;at:string;type:'STOP_REQUESTED'|'STOP_COMPLETED'|'RECOVERY';state:StopState|RecoveryState;actor:string;scope:KillScope;reason:string;evidence:string[];affected:string[];sharedSkipped:string[];}
interface Snapshot{schema:'agent-control.containment/v1';kills:KillRecord[];quarantined:string[];}

export function sealExecutionScope(input:Omit<ExecutionScopeEnvelope,'schema'|'id'|'sha256'>):ExecutionScopeEnvelope{const base={schema:'agent-control.execution-scope-envelope/v1' as const,id:`scope-${randomUUID()}`,...structuredClone(input)};validateEnvelope(base);return{...base,sha256:createHash('sha256').update(JSON.stringify(base)).digest('hex')};}
export function assessScope(envelope:ExecutionScopeEnvelope,action:ScopeAction):ScopeAssessment{validateSealed(envelope);const violations:string[]=[];const included=(value:string|undefined,allowed:string[],name:string)=>{if(value!==undefined&&!allowed.includes(value))violations.push(`${name}:${value}`);};included(action.filesystemPath,envelope.filesystem.writable,'filesystem');included(action.networkDestination,envelope.network.destinations,'network');if(action.port!==undefined&&!envelope.network.ports.includes(action.port))violations.push(`port:${action.port}`);included(action.device,envelope.devices,'device');included(action.runtime,envelope.runtimes,'runtime');included(action.credentialReference,envelope.credentialReferences,'credential-reference');included(action.tool,envelope.tools,'tool');included(action.api,envelope.apis,'api');included(action.model,envelope.models,'model');included(action.subprocess,envelope.subprocesses,'subprocess');for(const [field,limit] of Object.entries(envelope.maximum)){const observed=action[field as keyof ScopeAction];if(typeof observed==='number'&&observed>limit)violations.push(`${field}:${observed}>${limit}`);}const severe=violations.some(value=>/credential|subprocess|network|externalEffects/.test(value));return{allowed:violations.length===0,response:violations.length===0?'WARN':severe?'KILL_JOB':'BLOCK_ACTION',violations,envelopeId:envelope.id,evidence:violations.map(value=>`scope-violation:${value}`)};}

export class ContainmentSupervisor{private owners=new Map<string,ExecutionOwnership>();private snapshot:Snapshot={schema:'agent-control.containment/v1',kills:[],quarantined:[]};constructor(readonly file:string,private readonly clock=()=>new Date().toISOString()){if(fs.existsSync(file)){const value=JSON.parse(fs.readFileSync(file,'utf8')) as Snapshot;if(value.schema!==this.snapshot.schema)throw Error('containment_snapshot_invalid');this.snapshot=value;}}register(owner:ExecutionOwnership){if(this.owners.has(owner.id))throw Error('containment_owner_duplicate');this.owners.set(owner.id,owner);return()=>this.owners.delete(owner.id);}preview(scope:KillScope){const selected=this.select(scope),affected=selected.filter(value=>value.exclusive||scope.kind==='ESTATE').map(value=>value.id),sharedSkipped=selected.filter(value=>!value.exclusive&&scope.kind!=='ESTATE').map(value=>value.id);return{scope,affected,sharedSkipped,processes:selected.reduce((total,value)=>total+value.execution.activePids().length,0)};}async kill(scope:KillScope,actor:string,reason:string){if(!actor.trim()||!reason.trim())throw Error('containment_kill_reason_required');const preview=this.preview(scope),record:KillRecord={id:`kill-${randomUUID()}`,requestedAt:this.clock(),completedAt:null,actor,reason,scope:structuredClone(scope),state:'STOP_REQUESTED',affected:preview.affected,sharedSkipped:preview.sharedSkipped,cleanup:[],leaseRevocation:'NOT_APPLICABLE',evidence:[`kill-request:${scope.kind}:${scope.id}`],recovery:'KILLED'};this.snapshot.kills.push(record);this.persist();let leaseFailed=false,isolationFailed=false;for(const id of record.affected){const owner=this.owners.get(id)!;if(owner.leaseRevoker)try{await owner.leaseRevoker();record.leaseRevocation='CONFIRMED';}catch{leaseFailed=true;record.leaseRevocation='UNCONFIRMED';}try{record.cleanup.push(await owner.execution.terminateAll(`containment:${reason}`));}catch{record.evidence.push(`cleanup-threw:${id}`);}if((scope.kind==='NODE'||scope.kind==='ESTATE')&&owner.isolate)try{if(!await owner.isolate())isolationFailed=true;}catch{isolationFailed=true;}}
    const uncertain=leaseFailed||isolationFailed||record.cleanup.some(value=>value.outcome!=='confirmed');record.state=uncertain?'STOP_UNCONFIRMED':'STOP_CONFIRMED';if(uncertain){record.state='WORKER_QUARANTINED';for(const id of record.affected)if(!this.snapshot.quarantined.includes(id))this.snapshot.quarantined.push(id);record.recovery='QUARANTINED';}record.completedAt=this.clock();record.evidence.push(uncertain?'containment-unconfirmed':'containment-confirmed');this.persist();return structuredClone(record);}
  recovery(id:string,next:RecoveryState,evidence:string,actor='system'){const record=this.snapshot.kills.find(value=>value.id===id);if(!record)throw Error('containment_kill_missing');const order:RecoveryState[]=['KILLED','QUARANTINED','INSPECTED','RESET','REQUALIFIED','AVAILABLE'];if(order.indexOf(next)!==order.indexOf(record.recovery)+1)throw Error('containment_recovery_transition_invalid');if(!evidence.trim())throw Error('containment_recovery_evidence_required');if(!actor.trim())throw Error('containment_recovery_actor_required');record.recovery=next;record.evidence.push(evidence);record.recoveryEvents=[...(record.recoveryEvents??[]),{state:next,at:this.clock(),actor,evidence}];if(next==='QUARANTINED')for(const owner of record.affected)if(!this.snapshot.quarantined.includes(owner))this.snapshot.quarantined.push(owner);if(next==='AVAILABLE')this.snapshot.quarantined=this.snapshot.quarantined.filter(value=>!record.affected.includes(value));this.persist();return structuredClone(record);}
  schedulingEligibility(scopes:KillScope[]):ContainmentSchedulingEligibility{const uniqueScopes=scopes.filter((scope,index)=>scope.id.trim()&&scopes.findIndex(value=>value.kind===scope.kind&&value.id===scope.id)===index),active=this.snapshot.kills.filter(record=>record.recovery!=='KILLED'&&record.recovery!=='AVAILABLE'&&record.affected.some(owner=>this.snapshot.quarantined.includes(owner))&&uniqueScopes.some(scope=>scope.kind===record.scope.kind&&scope.id===record.scope.id));return active.length?{eligible:false,state:'QUARANTINED',reason:`QUALIFIED WORKER QUARANTINED: ${active.map(record=>`${record.scope.kind}:${record.scope.id}`).join(', ')}`,scopes:uniqueScopes,killIds:active.map(record=>record.id)}:{eligible:true,state:'AVAILABLE',reason:null,scopes:uniqueScopes,killIds:[]};}
  timeline():{schema:'agent-control.containment-timeline/v1';authority:'DERIVED_FROM_DURABLE_CONTAINMENT_RECORDS';events:ContainmentTimelineEvent[];quarantined:string[]}{const events=this.snapshot.kills.flatMap(record=>{const reason=redactSensitiveText(record.reason),values:ContainmentTimelineEvent[]=[{id:`${record.id}:requested`,killId:record.id,at:record.requestedAt,type:'STOP_REQUESTED',state:'STOP_REQUESTED',actor:record.actor,scope:structuredClone(record.scope),reason,evidence:record.evidence.filter(value=>value.startsWith('kill-request:')),affected:[...record.affected],sharedSkipped:[...record.sharedSkipped]}];if(record.completedAt)values.push({id:`${record.id}:completed`,killId:record.id,at:record.completedAt,type:'STOP_COMPLETED',state:record.state,actor:record.actor,scope:structuredClone(record.scope),reason,evidence:record.evidence.filter(value=>!value.startsWith('kill-request:')&&!record.recoveryEvents?.some(event=>event.evidence===value)),affected:[...record.affected],sharedSkipped:[...record.sharedSkipped]});for(const [index,event] of(record.recoveryEvents??[]).entries())values.push({id:`${record.id}:recovery:${index}`,killId:record.id,at:event.at,type:'RECOVERY',state:event.state,actor:event.actor,scope:structuredClone(record.scope),reason,evidence:[redactSensitiveText(event.evidence)],affected:[...record.affected],sharedSkipped:[...record.sharedSkipped]});return values;}).sort((a,b)=>a.at.localeCompare(b.at)||a.id.localeCompare(b.id));return redactSensitiveValue({schema:'agent-control.containment-timeline/v1' as const,authority:'DERIVED_FROM_DURABLE_CONTAINMENT_RECORDS' as const,events,quarantined:[...this.snapshot.quarantined]}) as {schema:'agent-control.containment-timeline/v1';authority:'DERIVED_FROM_DURABLE_CONTAINMENT_RECORDS';events:ContainmentTimelineEvent[];quarantined:string[]};}
  list(){return structuredClone(this.snapshot);}private select(scope:KillScope){return[...this.owners.values()].filter(owner=>scope.kind==='ESTATE'||owner.scopes.some(value=>value.kind===scope.kind&&value.id===scope.id));}private persist(){const safe=redactSensitiveValue(this.snapshot);assertNoSensitiveMaterial(JSON.stringify(safe),'containment_secret_forbidden');fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=`${this.file}.${process.pid}.tmp`;fs.writeFileSync(tmp,JSON.stringify(safe,null,2)+'\n',{mode:0o600});fs.renameSync(tmp,this.file);}}

function validateEnvelope(value:Omit<ExecutionScopeEnvelope,'sha256'>){if(value.schema!=='agent-control.execution-scope-envelope/v1'||!value.workspace.trim()||value.maximum.runtimeMs<1)throw Error('execution_scope_invalid');for(const port of value.network.ports)if(!Number.isSafeInteger(port)||port<1||port>65535)throw Error('execution_scope_port_invalid');}
function validateSealed(value:ExecutionScopeEnvelope){const{sha256,...base}=value;validateEnvelope(base);if(createHash('sha256').update(JSON.stringify(base)).digest('hex')!==sha256)throw Error('execution_scope_hash_mismatch');}
