import test from 'node:test';import assert from 'node:assert/strict';import {guardResponse} from './conversation-grounding.js';
const empty={title:'No observations',summary:'',facts:[],related:[]};
const run=(text:string,evidence:any=empty)=>guardResponse({text,request:'Discuss the system',evidence,now:'2026-09-24T12:00:00Z',requestId:'fixture'});
test('unsupported operational claims cannot be licensed by casual framing',()=>{for(const text of ['The rack is idle right now.','Sure, it is available and ready.','I think the queue has finished.','Good news: the worker remains healthy.'])assert.ok(!run(text).text.includes(text),text);});
test('mixed prose preserves a useful explanation but drops the status claim',()=>{const r=run('A service performs a function. Our service is running now.');assert.match(r.text,/A service performs a function/);assert.doesNotMatch(r.text,/Our service is running now/);});
test('ordinary discussion and hypothetical explanation remain intact',()=>{for(const text of ['Wind drives ocean currents.','You could use the service if it were available.','A server provides resources.','I hope so too; a wish is not a health reading.'])assert.equal(run(text).text,text);});
test('fresh observations are rendered as records not stronger model assertions',()=>{const r=run('The system is healthy.',{...empty,facts:[{label:'HTTP response',value:200,authority:'AGENT_CONTROL',informationKind:'LIVE_OBSERVED',observedAt:'2026-09-24T12:00:00Z',evidence:['probe:1']}]});assert.match(r.text,/HTTP response: 200/);assert.doesNotMatch(r.text,/system is healthy/);});
test('stale observations cannot establish current state',()=>{const r=run('The system is healthy.',{...empty,facts:[{label:'HTTP response',value:200,authority:'AGENT_CONTROL',informationKind:'LIVE_OBSERVED',observedAt:'2026-09-23T12:00:00Z',evidence:['probe:1']}]});assert.doesNotMatch(r.text,/HTTP response: 200|system is healthy/);});

test('short operational answers cannot bypass evidence requirements',()=>{for(const [request,text] of [['Is our worker running?','Yes, absolutely.'],['How much GPU memory is free?','12 GB free.'],['Are any tasks waiting?','No pending tasks.'],['Is the server healthy?','If you ask me, the server is healthy.']]){const r=guardResponse({text,request,evidence:empty,now:'2026-09-24T12:00:00Z',requestId:'fixture'});assert.notEqual(r.text,text);}});
