import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {CostRoutingLedger,explainRouting,normalizePolicy,preflightCost,reconcileCost,resolveRoutingPolicy,routingPreset,type CostPerformanceRoutingPolicy,type RoutingCandidate} from './cost-performance-routing.js';
import {openRouterUnsupportedCapabilities,translateOpenRouterPolicy} from './openrouter-cost-routing.js';

const candidate=(id:string,input:number,output:number,throughput:number,latency=100):RoutingCandidate=>({id,provider:id,model:'model',available:true,inputUsdPerMillionTokens:input,outputUsdPerMillionTokens:output,throughputTps:{p90:throughput},latencyMs:{p90:latency}});
const custom=(changes:Partial<CostPerformanceRoutingPolicy>={}):CostPerformanceRoutingPolicy=>normalizePolicy({schema:'agent-control.cost-performance-routing-policy/v1',id:'custom',strategy:'custom',optimization:'throughput',rateCeilingUsdPerMillionTokens:{input:1,output:2},budget:{invocationUsd:1,jobUsd:2},tokenCeiling:{input:10_000,output:2_000},fallback:{enabled:true,onNoEligibleRoute:'block',crossModel:false},...changes});

test('fastest eligible provider is selected and faster overpriced route is excluded',()=>{const value=explainRouting({policy:custom(),candidates:[candidate('eligible',.9,1.9,80),candidate('overpriced',1.1,1.9,200)],inputTokensEstimated:100,outputTokensRequested:100});assert.equal(value.selected?.id,'eligible');assert.deepEqual(value.excluded[0].reasons,['input_rate_above_ceiling_or_unknown']);});
test('balanced chooses cheapest provider meeting preferred throughput',()=>{const policy=custom({optimization:'price',preferredMinThroughputTps:{percentile:90,value:50,onMiss:'degrade'}}),value=explainRouting({policy,candidates:[candidate('slow-cheap',.1,.1,40),candidate('qualified-cheap',.3,.4,60),candidate('qualified-costly',.8,1,100)],inputTokensEstimated:100,outputTokensRequested:100});assert.equal(value.selected?.id,'qualified-cheap');});
test('no qualifying route is blocked with canonical reason and hard ceiling survives fallback',()=>{const policy=custom({fallback:{enabled:true,onNoEligibleRoute:'block',crossModel:true}}),value=explainRouting({policy,candidates:[candidate('costly',9,9,200)],inputTokensEstimated:100,outputTokensRequested:100});assert.equal(value.decision,'BLOCKED');assert.equal(value.reason,'NO_ROUTE_WITHIN_PRICE_CEILING');assert.equal(value.policy.rateCeilingUsdPerMillionTokens?.input,1);});
test('preferred throughput degrades only when explicitly permitted',()=>{const routes=[candidate('slow',.2,.2,10)],blocked=explainRouting({policy:custom({preferredMinThroughputTps:{percentile:90,value:50,onMiss:'block'}}),candidates:routes,inputTokensEstimated:1,outputTokensRequested:1}),degraded=explainRouting({policy:custom({preferredMinThroughputTps:{percentile:90,value:50,onMiss:'degrade'}}),candidates:routes,inputTokensEstimated:1,outputTokensRequested:1});assert.equal(blocked.reason,'PREFERRED_PERFORMANCE_UNAVAILABLE');assert.equal(degraded.selected?.id,'slow');});
test('invocation and remaining job budgets block independently',()=>{const route=[candidate('route',1,2,10)],invocation=explainRouting({policy:custom({budget:{invocationUsd:.001,jobUsd:10}}),candidates:route,inputTokensEstimated:1000,outputTokensRequested:1000}),job=explainRouting({policy:custom({budget:{invocationUsd:10,jobUsd:.003}}),candidates:route,inputTokensEstimated:1000,outputTokensRequested:1000,jobSpentUsd:.001});assert.equal(invocation.reason,'INVOCATION_BUDGET_EXCEEDED');assert.equal(job.reason,'JOB_BUDGET_EXCEEDED');});
test('job budget is enforced across calls using actual spent balance',()=>{const policy=custom({budget:{jobUsd:.01,invocationUsd:.01}}),first=preflightCost(policy,1000,1000,0),second=explainRouting({policy,candidates:[candidate('route',1,2,10)],inputTokensEstimated:1000,outputTokensRequested:1000,jobSpentUsd:.008});assert.equal(first.maximumInvocationCostUsd,.003);assert.equal(second.reason,'JOB_BUDGET_EXCEEDED');});
test('estimated and actual costs reconcile while cached and fresh tokens remain separate',()=>{const estimate=preflightCost(custom(),1000,1000),value=reconcileCost(estimate,{promptTokens:1000,cachedInputTokens:600,freshInputTokens:400,reasoningTokens:50,outputTokens:200,providerReportedCostUsd:.0009,advertisedInputUsdPerMillionTokens:1,advertisedOutputUsdPerMillionTokens:2});assert.equal(value.cachedInputTokens,600);assert.equal(value.freshInputTokens,400);assert.equal(value.actualCostAuthority,'PROVIDER_REPORTED');assert.equal(value.actualCostUsd,.0009);assert.throws(()=>reconcileCost(estimate,{promptTokens:1000,cachedInputTokens:600,freshInputTokens:500,reasoningTokens:0,outputTokens:1,providerReportedCostUsd:null,advertisedInputUsdPerMillionTokens:1,advertisedOutputUsdPerMillionTokens:2}),/partition/);});
test('provider translation is isolated from provider-neutral policy contract and matches OpenRouter schema',()=>{const policy=custom({optimization:'price',preferredMinThroughputTps:{percentile:90,value:50,onMiss:'degrade'},providers:{allowed:['A'],ignored:['B']},quantizations:['int8']}),translated=translateOpenRouterPolicy(policy);assert.equal('provider' in policy,false);assert.deepEqual(translated.body.provider.sort,'price');assert.deepEqual(translated.body.provider.max_price,{prompt:1,completion:2});assert.deepEqual(translated.body.provider.preferred_min_throughput,{p90:50});assert.deepEqual(translated.body.provider.only,['A']);assert.deepEqual(translated.body.provider.ignore,['B']);});
test('unsupported provider adapter capabilities are explicit',()=>assert.deepEqual(openRouterUnsupportedCapabilities(custom({fallback:{enabled:true,onNoEligibleRoute:'block',crossModel:true}})),['cross_model_fallback_requires_explicit_model_list']));
test('raising inherited authority requires approval and leaves approval evidence available',()=>{const estate={scope:'estate' as const,scopeId:'default',policy:custom(),recordedAt:'2026-09-20T00:00:00Z'},job={scope:'job' as const,scopeId:'job',policy:custom({rateCeilingUsdPerMillionTokens:{input:2,output:3}}),recordedAt:'2026-09-20T00:01:00Z'};assert.throws(()=>resolveRoutingPolicy([estate,job]),/requires_approval/);const approval={approved:true as const,approvalId:'approval-1',approver:'operator',approvedAt:'2026-09-20T00:02:00Z',reason:'one run'},value=resolveRoutingPolicy([estate,job],approval);assert.equal(value.approval?.approvalId,'approval-1');assert.equal(value.policy.rateCeilingUsdPerMillionTokens?.input,2);});
test('more specific policy may lower ceilings without approval and records source',()=>{const value=resolveRoutingPolicy([{scope:'estate',scopeId:'default',policy:custom(),recordedAt:'x'},{scope:'invocation',scopeId:'one',policy:custom({rateCeilingUsdPerMillionTokens:{input:.5,output:1}}),recordedAt:'y'}]);assert.equal(value.policy.rateCeilingUsdPerMillionTokens?.input,.5);assert.ok(value.sources.some(item=>item.scope==='invocation'));});
test('secrets cannot enter policy fields or rendered explanation',()=>{const secret='sk-or-v1-'+('x'.repeat(64));assert.throws(()=>normalizePolicy(custom({id:secret})),/invalid/);const value=explainRouting({policy:custom(),candidates:[candidate('route',.1,.2,10)],inputTokensEstimated:1,outputTokensRequested:1});assert.equal(JSON.stringify(value).includes('authorization'),false);});
test('existing unrouted behavior is opt-in because absence is rejected instead of silently enabling a preset',()=>assert.throws(()=>resolveRoutingPolicy([]),/routing_policy_missing/));
test('all presets and custom policy survive JSON configuration round trips',()=>{for(const policy of [routingPreset('economy'),routingPreset('balanced'),routingPreset('fast-capped'),custom()])assert.deepEqual(normalizePolicy(JSON.parse(JSON.stringify(policy))),policy);});
test('append-only historical evidence remains immutable after settings change',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'cost-routing-')),file=path.join(root,'routing.jsonl'),ledger=new CostRoutingLedger(file,()=> '2026-09-20T12:00:00Z');ledger.append('DECISION',{policy:custom()});const before=fs.readFileSync(file,'utf8');ledger.append('DECISION',{policy:custom({rateCeilingUsdPerMillionTokens:{input:.5,output:1}})});assert.equal(fs.readFileSync(file,'utf8').startsWith(before),true);assert.equal(ledger.list()[1].previousHash,ledger.list()[0].sha256);fs.rmSync(root,{recursive:true,force:true});});
test('dry-run explanation never invokes an external provider',()=>{let calls=0;const value=explainRouting({policy:custom(),candidates:[candidate('route',.1,.2,10)],inputTokensEstimated:1,outputTokensRequested:1});assert.equal(calls,0);assert.equal(value.externalRequestMade,false);});
test('token ceiling blocks before route selection',()=>{const value=explainRouting({policy:custom({tokenCeiling:{input:10,output:20}}),candidates:[candidate('route',.1,.2,10)],inputTokensEstimated:11,outputTokensRequested:20});assert.equal(value.reason,'INPUT_TOKEN_CEILING_EXCEEDED');assert.equal(value.selected,null);});
test('missing advertised price is not treated as zero under a hard ceiling',()=>{const value=explainRouting({policy:custom(),candidates:[{...candidate('unknown',0,0,100),inputUsdPerMillionTokens:null}],inputTokensEstimated:1,outputTokensRequested:1});assert.equal(value.reason,'NO_ROUTE_WITHIN_PRICE_CEILING');});
