import {createHash,randomUUID} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import type {ProjectMemoryPort} from './project-memory.js';

export type DeterministicSkillState='OBSERVED'|'CANDIDATE'|'VALIDATED'|'PROMOTED'|'INVALIDATED'|'RETIRED';
export interface DeterministicSkillPolicyConfig{enabled?:boolean;routingEnabled?:boolean;minimumDistinctParcels?:number;maximumValidationAgeDays?:number;}
export interface DeterministicSkillPolicy{enabled:boolean;routingEnabled:boolean;minimumDistinctParcels:number;maximumValidationAgeDays:number;}
export interface DeterministicContract{schema:string;required:string[];allowed:string[];}
export interface DeterministicSkillRecord{schema:'agent-control.deterministic-skill/v1';id:string;version:string;label:string;taskClass:string;handlerId:string;handlerSha256:string;state:DeterministicSkillState;sourceParcels:string[];originatingReasoning:Array<{parcelId:string;providerId:string;modelId:string;nodeId:string;evidence:string[]}>;assumptions:string[];inputContract:DeterministicContract;outputContract:DeterministicContract;verificationMethod:string;scope:string[];createdAt:string;validatedAt:string|null;promotedAt:string|null;lastUsedAt:string|null;expiresAt:string|null;invalidationConditions:string[];validationEvidence:string[];reason:string;}
export interface DeterministicSkillDecision{schema:'agent-control.deterministic-skill-decision/v1';id:string;parcelId:string;stageId:string;taskClass:string;at:string;selected:{id:string;version:string;handlerId:string}|null;candidates:Array<{id:string;version:string;eligible:boolean;reasons:string[]}>;route:'DETERMINISTIC_SKILL'|'ESCALATE_MODEL';reason:string;}
export interface DeterministicSkillExecution{schema:'agent-control.deterministic-skill-execution/v1';id:string;decisionId:string;skillId:string;skillVersion:string;parcelId:string;stageId:string;startedAt:string;completedAt:string;verified:boolean;output:unknown;energyJoules:number|null;verification:string[];}
interface Snapshot{schema:'agent-control.deterministic-skills/v1';skills:DeterministicSkillRecord[];decisions:DeterministicSkillDecision[];executions:DeterministicSkillExecution[];}
export interface DeterministicSkillHandler{identity:string;execute(input:unknown):unknown;verify(input:unknown,output:unknown):{passed:boolean;evidence:string[]};applicable(input:unknown):{applicable:boolean;reasons:string[]};}

const defaults:DeterministicSkillPolicy={enabled:true,routingEnabled:false,minimumDistinctParcels:3,maximumValidationAgeDays:90};
const stable=(value:unknown):string=>JSON.stringify(sort(value));
const sort=(value:unknown):unknown=>Array.isArray(value)?value.map(sort):value&&typeof value==='object'?Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,sort(v)])):value;
export const deterministicSkillSha256=(value:unknown)=>createHash('sha256').update(typeof value==='string'?value:stable(value)).digest('hex');

export class FileDeterministicSkillStore{private value:Snapshot={schema:'agent-control.deterministic-skills/v1',skills:[],decisions:[],executions:[]};constructor(readonly file?:string){if(file&&fs.existsSync(file)){const value=JSON.parse(fs.readFileSync(file,'utf8')) as Snapshot;if(value.schema!=='agent-control.deterministic-skills/v1')throw new Error('deterministic_skill_state_invalid');this.value=value;}}load(){return structuredClone(this.value);}save(value:Snapshot){this.value=structuredClone(value);if(!this.file)return;fs.mkdirSync(path.dirname(this.file),{recursive:true});const temporary=`${this.file}.${process.pid}.${randomUUID()}.tmp`;fs.writeFileSync(temporary,`${JSON.stringify(value,null,2)}\n`,{mode:0o600,flag:'wx'});fs.renameSync(temporary,this.file);}}

export class DeterministicSkillRuntime{
  readonly policy:DeterministicSkillPolicy;private state:Snapshot;private handlers=new Map<string,DeterministicSkillHandler>();
  constructor(private readonly store=new FileDeterministicSkillStore(),config:DeterministicSkillPolicyConfig={},private readonly clock=()=>new Date().toISOString()){this.policy={...defaults,...config};this.state=store.load();}
  registerHandler(id:string,handler:DeterministicSkillHandler){if(this.handlers.has(id))throw new Error('deterministic_skill_handler_exists');this.handlers.set(id,handler);return this;}
  observe(input:{id:string;version:string;label:string;taskClass:string;handlerId:string;sourceParcel:string;originatingReasoning:{providerId:string;modelId:string;nodeId:string;evidence:string[]};assumptions:string[];inputContract:DeterministicContract;outputContract:DeterministicContract;verificationMethod:string;scope:string[];invalidationConditions:string[];reason:string}){
    if(!this.policy.enabled)throw new Error('deterministic_skills_disabled');const now=this.clock(),existing=this.state.skills.find(item=>item.id===input.id&&item.version===input.version);
    if(existing){if(existing.taskClass!==input.taskClass||existing.handlerId!==input.handlerId)throw new Error('deterministic_skill_observation_conflict');if(!existing.sourceParcels.includes(input.sourceParcel)){existing.sourceParcels.push(input.sourceParcel);existing.originatingReasoning.push({parcelId:input.sourceParcel,...structuredClone(input.originatingReasoning)});}existing.reason=input.reason;this.persist();return structuredClone(existing);}
    const handler=this.handlers.get(input.handlerId);if(!handler)throw new Error('deterministic_skill_handler_missing');const record:DeterministicSkillRecord={schema:'agent-control.deterministic-skill/v1',id:required(input.id),version:required(input.version),label:required(input.label),taskClass:required(input.taskClass),handlerId:input.handlerId,handlerSha256:deterministicSkillSha256(handler.identity),state:'OBSERVED',sourceParcels:[required(input.sourceParcel)],originatingReasoning:[{parcelId:input.sourceParcel,...structuredClone(input.originatingReasoning)}],assumptions:unique(input.assumptions),inputContract:contract(input.inputContract),outputContract:contract(input.outputContract),verificationMethod:required(input.verificationMethod),scope:unique(input.scope),createdAt:now,validatedAt:null,promotedAt:null,lastUsedAt:null,expiresAt:null,invalidationConditions:unique(input.invalidationConditions),validationEvidence:[],reason:required(input.reason)};this.state.skills.push(record);this.persist();return structuredClone(record);
  }
  nominate(id:string,version:string,actor:string,reason:string){const value=this.must(id,version);if(value.state!=='OBSERVED'||new Set(value.sourceParcels).size<this.policy.minimumDistinctParcels)throw new Error('deterministic_skill_repeated_evidence_required');value.state='CANDIDATE';value.reason=`${actor}: ${required(reason)}`;this.persist();return structuredClone(value);}
  validate(id:string,version:string,input:{actor:string;evidence:string[];expiresAt?:string|null;passed:boolean;reason:string}){const value=this.must(id,version);if(value.state!=='CANDIDATE')throw new Error('deterministic_skill_lifecycle_invalid');if(!input.evidence.length)throw new Error('deterministic_skill_validation_evidence_required');value.validationEvidence=unique(input.evidence);value.validatedAt=this.clock();value.expiresAt=input.expiresAt??null;value.reason=`${input.actor}: ${required(input.reason)}`;value.state=input.passed?'VALIDATED':'INVALIDATED';this.persist();return structuredClone(value);}
  promote(id:string,version:string,input:{actor:string;reason:string;evidence:string[]}){const value=this.must(id,version);if(value.state!=='VALIDATED')throw new Error('deterministic_skill_lifecycle_invalid');value.state='PROMOTED';value.promotedAt=this.clock();value.reason=`${input.actor}: ${required(input.reason)}`;value.validationEvidence=unique([...value.validationEvidence,...input.evidence]);this.persist();return structuredClone(value);}
  invalidate(id:string,version:string,reason:string){const value=this.must(id,version);value.state='INVALIDATED';value.reason=required(reason);this.persist();return structuredClone(value);}
  assess(input:{parcelId:string;stageId:string;taskClass:string;payload:unknown;now?:string}){const at=input.now??this.clock(),candidates=this.state.skills.filter(item=>item.taskClass===input.taskClass).map(item=>{const reasons:string[]=[];if(!this.policy.routingEnabled)reasons.push('routing_disabled');if(item.state!=='PROMOTED')reasons.push(`state:${item.state}`);if(item.expiresAt&&Date.parse(item.expiresAt)<=Date.parse(at))reasons.push('evidence_expired');if(item.validatedAt&&(Date.parse(at)-Date.parse(item.validatedAt))/86_400_000>this.policy.maximumValidationAgeDays)reasons.push('validation_stale');const handler=this.handlers.get(item.handlerId);if(!handler||deterministicSkillSha256(handler.identity)!==item.handlerSha256)reasons.push('handler_identity_mismatch');else reasons.push(...handler.applicable(input.payload).reasons);return{id:item.id,version:item.version,eligible:reasons.length===0,reasons};});const chosen=candidates.find(item=>item.eligible)??null,decision:DeterministicSkillDecision={schema:'agent-control.deterministic-skill-decision/v1',id:`det-skill-route-${randomUUID()}`,parcelId:input.parcelId,stageId:input.stageId,taskClass:input.taskClass,at,selected:chosen?{id:chosen.id,version:chosen.version,handlerId:this.must(chosen.id,chosen.version).handlerId}:null,candidates,route:chosen?'DETERMINISTIC_SKILL':'ESCALATE_MODEL',reason:chosen?`Selected promoted deterministic skill ${chosen.id}@${chosen.version}: input contract, freshness, handler identity and applicability passed.`:`Deterministic skill rejected; escalate to governed model (${unique(candidates.flatMap(item=>item.reasons)).join(', ')||'no matching skill'}).`};this.state.decisions.push(decision);this.persist();return structuredClone(decision);}
  execute(decisionId:string,payload:unknown,energyJoules:number|null=null){const decision=this.state.decisions.find(item=>item.id===decisionId);if(!decision?.selected)throw new Error('deterministic_skill_not_selected');const skill=this.must(decision.selected.id,decision.selected.version),handler=this.handlers.get(skill.handlerId);if(!handler||deterministicSkillSha256(handler.identity)!==skill.handlerSha256)throw new Error('deterministic_skill_handler_identity_mismatch');const applicability=handler.applicable(payload);if(!applicability.applicable)throw new Error('deterministic_skill_applicability_changed');const startedAt=this.clock(),output=handler.execute(structuredClone(payload)),verification=handler.verify(payload,output);if(!verification.passed)throw new Error('deterministic_skill_independent_verification_failed');const record:DeterministicSkillExecution={schema:'agent-control.deterministic-skill-execution/v1',id:`det-skill-exec-${randomUUID()}`,decisionId,skillId:skill.id,skillVersion:skill.version,parcelId:decision.parcelId,stageId:decision.stageId,startedAt,completedAt:this.clock(),verified:true,output:structuredClone(output),energyJoules,verification:unique(verification.evidence)};skill.lastUsedAt=record.completedAt;this.state.executions.push(record);this.persist();return structuredClone(record);}
  async recallAndAssess(memory:ProjectMemoryPort,input:{projectId:string;repositoryId?:string;parcelId:string;stageId:string;taskClass:string;payload:unknown}){const recalled=await memory.recall({projectId:input.projectId,repositoryId:input.repositoryId,query:`deterministic skill ${input.taskClass}`,limit:8});const ids=recalled.accepted.map(item=>item.memory.factKey).filter((value):value is string=>Boolean(value));const decision=this.assess(input);return{memoryIds:recalled.accepted.map(item=>item.memory.id),rememberedSkillIds:ids,modelInvoked:false,decision};}
  projection(){return{...structuredClone(this.state),policy:structuredClone(this.policy),observedAt:this.clock()};}records(){return structuredClone(this.state.skills);}decisions(){return structuredClone(this.state.decisions);}executions(){return structuredClone(this.state.executions);}
  humanReadable(decisionId:string){const decision=this.state.decisions.find(item=>item.id===decisionId);if(!decision)throw new Error('deterministic_skill_decision_missing');const execution=this.state.executions.find(item=>item.decisionId===decision.id);return[`Task: ${decision.taskClass}`,`Route: ${decision.selected?`deterministic skill ${decision.selected.id}@${decision.selected.version}`:'governed model escalation'}`,`Reason: ${decision.reason}`,`Verification: ${execution?.verified?'PASS':decision.selected?'PENDING':'NOT RUN'}`,`Energy: ${execution?.energyJoules===null||execution?.energyJoules===undefined?'UNAVAILABLE':`${execution.energyJoules.toFixed(3)} J`}`,`LLM invocation avoided: ${decision.selected?'yes':'no'}`].join('\n');}
  private must(id:string,version:string){const value=this.state.skills.find(item=>item.id===id&&item.version===version);if(!value)throw new Error('deterministic_skill_missing');return value;}private persist(){this.store.save(this.state);}
}

export function deterministicBreakEven(reasoningJoules:number,deterministicJoules:number,modelPerRunJoules:number){if(![reasoningJoules,deterministicJoules,modelPerRunJoules].every(Number.isFinite)||reasoningJoules<0||deterministicJoules<0||modelPerRunJoules<=deterministicJoules)return{repetitions:null,reason:'positive_saving_unavailable'};return{repetitions:Math.ceil(reasoningJoules/(modelPerRunJoules-deterministicJoules)),reason:'reasoning_energy_divided_by_per_repetition_saving'};}
function required(value:string){if(typeof value!=='string'||!value.trim())throw new Error('deterministic_skill_field_required');return value.trim();}function unique(values:string[]){return[...new Set(values.map(required))].sort();}function contract(value:DeterministicContract){if(!value?.schema)return(()=>{throw new Error('deterministic_skill_contract_invalid')})();return{schema:required(value.schema),required:unique(value.required),allowed:unique(value.allowed)};}

export function registerCoreDeterministicHandlers(runtime:DeterministicSkillRuntime){
  runtime.registerHandler('repository-state-v1',{identity:'repository-state-v1:branch-head-porcelain',applicable:input=>objectWith(input,['branch','head','porcelain']),execute:input=>{const value=input as {branch:string;head:string;porcelain:string};return{clean:value.porcelain.trim()==='',branch:value.branch,head:value.head,status:value.porcelain.trim()===''?'CLEAN':'DIRTY'};},verify:(input,output)=>({passed:(output as {clean?:boolean}).clean===((input as {porcelain:string}).porcelain.trim()===''),evidence:['deterministic:repository-state-invariant']})});
  runtime.registerHandler('test-result-v1',{identity:'test-result-v1:exit-passed-failed-skipped',applicable:input=>objectWith(input,['exitCode','passed','failed','skipped']),execute:input=>{const value=input as {exitCode:number;passed:number;failed:number;skipped:number};return{verdict:value.exitCode===0&&value.failed===0?'PASS':'FAIL',total:value.passed+value.failed+value.skipped};},verify:(input,output)=>({passed:(output as {verdict?:string}).verdict===(((input as {exitCode:number;failed:number}).exitCode===0&&(input as {failed:number}).failed===0)?'PASS':'FAIL'),evidence:['deterministic:test-result-invariant']})});
  runtime.registerHandler('baton-integrity-v1',{identity:'baton-integrity-v1:stable-sha256',applicable:input=>objectWith(input,['baton','expectedSha256']),execute:input=>{const value=input as {baton:unknown;expectedSha256:string};const actualSha256=deterministicSkillSha256(value.baton);return{valid:actualSha256===value.expectedSha256,actualSha256};},verify:(input,output)=>({passed:(output as {actualSha256?:string}).actualSha256===deterministicSkillSha256((input as {baton:unknown}).baton),evidence:['deterministic:baton-hash-recomputed']})});return runtime;
}
function objectWith(input:unknown,keys:string[]){if(!input||typeof input!=='object'||Array.isArray(input))return{applicable:false,reasons:['input_contract_mismatch']};const value=input as Record<string,unknown>,missing=keys.filter(key=>!(key in value)),unknown=Object.keys(value).filter(key=>!keys.includes(key));return{applicable:missing.length===0&&unknown.length===0,reasons:[...missing.map(key=>`missing:${key}`),...unknown.map(key=>`unexpected:${key}`)]};}
