import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {DeterministicSkillRuntime,FileDeterministicSkillStore,deterministicBreakEven,deterministicSkillSha256,registerCoreDeterministicHandlers} from './deterministic-skill.js';
import {MarkdownProjectMemoryPort} from './project-memory.js';

const clock=()=> '2026-09-11T12:00:00Z',contract=(required:string[])=>({schema:'fixture/v1',required,allowed:required});
function setup(routingEnabled=true){const root=fs.mkdtempSync(path.join(os.tmpdir(),'det-skills-')),runtime=registerCoreDeterministicHandlers(new DeterministicSkillRuntime(new FileDeterministicSkillStore(path.join(root,'state.json')),{routingEnabled,minimumDistinctParcels:3},clock));return{root,runtime};}
function observe(runtime:DeterministicSkillRuntime,id:string,handlerId:string,taskClass:string,parcel:string,fields:string[]){return runtime.observe({id,version:'1',label:id,taskClass,handlerId,sourceParcel:parcel,originatingReasoning:{providerId:'local-qwen',modelId:'qwen-2.5-3b',nodeId:'qualification-node',evidence:[`verified:${parcel}`]},assumptions:['typed input'],inputContract:contract(fields),outputContract:contract(['result']),verificationMethod:'independent invariant',scope:['agent-control'],invalidationConditions:['input contract changes','verification fails'],reason:'Verified reasoning repeated'});}
function promote(runtime:DeterministicSkillRuntime,id:string,handler:string,taskClass:string,fields:string[]){for(let i=1;i<=3;i++)observe(runtime,id,handler,taskClass,`parcel-${id}-${i}`,fields);runtime.nominate(id,'1','operator','Three distinct verified parcels');runtime.validate(id,'1',{actor:'independent-verifier',evidence:['suite:frozen','review:approved'],passed:true,expiresAt:'2027-01-01T00:00:00Z',reason:'Held-out cases passed'});return runtime.promote(id,'1',{actor:'operator',reason:'Explicit promotion approved',evidence:['approval:operator']});}

test('promotion requires repeated distinct Work Parcel evidence and survives restart',()=>{const s=setup();try{observe(s.runtime,'repo-state','repository-state-v1','repository-state','parcel-1',['branch','head','porcelain']);assert.throws(()=>s.runtime.nominate('repo-state','1','operator','too early'),/repeated_evidence/);observe(s.runtime,'repo-state','repository-state-v1','repository-state','parcel-2',['branch','head','porcelain']);observe(s.runtime,'repo-state','repository-state-v1','repository-state','parcel-3',['branch','head','porcelain']);s.runtime.nominate('repo-state','1','operator','repeated');s.runtime.validate('repo-state','1',{actor:'verifier',evidence:['held-out'],passed:true,reason:'pass'});s.runtime.promote('repo-state','1',{actor:'operator',reason:'approved',evidence:['approval']});const restored=registerCoreDeterministicHandlers(new DeterministicSkillRuntime(new FileDeterministicSkillStore(path.join(s.root,'state.json')),{routingEnabled:true},clock));assert.equal(restored.records()[0]?.state,'PROMOTED');assert.equal(restored.records()[0]?.sourceParcels.length,3);}finally{fs.rmSync(s.root,{recursive:true,force:true});}});

test('three genuine recurring control operations execute deterministically and verify',()=>{const s=setup();try{promote(s.runtime,'repo-state','repository-state-v1','repository-state',['branch','head','porcelain']);promote(s.runtime,'test-result','test-result-v1','test-result',['exitCode','passed','failed','skipped']);promote(s.runtime,'baton-check','baton-integrity-v1','baton-integrity',['baton','expectedSha256']);const cases=[{taskClass:'repository-state',payload:{branch:'main',head:'abc',porcelain:''},expected:'CLEAN'},{taskClass:'test-result',payload:{exitCode:0,passed:1144,failed:0,skipped:0},expected:'PASS'},{taskClass:'baton-integrity',payload:{baton:{next:'verify'},expectedSha256:deterministicSkillSha256({next:'verify'})},expected:true}];for(const [index,item] of cases.entries()){const decision=s.runtime.assess({parcelId:`parcel-exec-${index}`,stageId:'execute',taskClass:item.taskClass,payload:item.payload});assert.equal(decision.route,'DETERMINISTIC_SKILL');const result=s.runtime.execute(decision.id,item.payload,.1);assert.equal(result.verified,true);assert.ok(Object.values(result.output as object).includes(item.expected));}assert.equal(s.runtime.executions().length,3);}finally{fs.rmSync(s.root,{recursive:true,force:true});}});

test('novel input, expired evidence and disabled routing fail closed to model escalation',()=>{const s=setup();try{promote(s.runtime,'repo-state','repository-state-v1','repository-state',['branch','head','porcelain']);const novel=s.runtime.assess({parcelId:'novel',stageId:'execute',taskClass:'repository-state',payload:{branch:'main',head:'abc',porcelain:'',submodules:true}});assert.equal(novel.route,'ESCALATE_MODEL');assert.match(novel.reason,/unexpected:submodules/);const expired=s.runtime.assess({parcelId:'expired',stageId:'execute',taskClass:'repository-state',payload:{branch:'main',head:'abc',porcelain:''},now:'2027-02-01T00:00:00Z'});assert.equal(expired.route,'ESCALATE_MODEL');assert.match(expired.reason,/expired/);}finally{fs.rmSync(s.root,{recursive:true,force:true});}});

test('Your Memories can identify a governed skill without invoking a model',async()=>{const s=setup();try{promote(s.runtime,'repo-state','repository-state-v1','repository-state',['branch','head','porcelain']);const memory=new MarkdownProjectMemoryPort(path.join(s.root,'memory'),'test',clock);await memory.remember({id:'memory-repo-state',kind:'LESSON',title:'Deterministic skill repo-state',content:'Use the promoted repository-state skill for exact branch head porcelain inputs.',factKey:'repo-state',projectId:'agent-control',repositoryId:'agent-control',originatingNodeId:'qualification-node',source:'AGENT_CONTROL',confidence:1,verification:'VERIFIED',provenance:[{id:'promotion',sha256:deterministicSkillSha256('promotion'),authority:'AUTHORITATIVE'}],supersedes:[]});const result=await s.runtime.recallAndAssess(memory,{projectId:'agent-control',repositoryId:'agent-control',parcelId:'parcel-memory',stageId:'execute',taskClass:'repository-state',payload:{branch:'main',head:'abc',porcelain:''}});assert.equal(result.modelInvoked,false);assert.deepEqual(result.rememberedSkillIds,['repo-state']);assert.equal(result.decision.route,'DETERMINISTIC_SKILL');}finally{fs.rmSync(s.root,{recursive:true,force:true});}});

test('break-even includes initial reasoning cost',()=>{assert.deepEqual(deterministicBreakEven(20.426,.121,20.426),{repetitions:2,reason:'reasoning_energy_divided_by_per_repetition_saving'});assert.equal(deterministicBreakEven(5,.2,.1).repetitions,null);});
