import {classifyDiagnosticEvent,diagnosticMessage} from './diagnostic-classification.js';
import {createHash} from 'node:crypto';
import {DiagnosticSanitizer,DIAGNOSTIC_SANITIZER_VERSION} from './diagnostic-sanitization.js';
import type {DiagnosticArchitecture,DiagnosticAssessment,DiagnosticCollection,DiagnosticEvent,DiagnosticEventType,DiagnosticEvidence,DiagnosticFinding,DiagnosticPermission,DiagnosticSource} from './diagnostic-types.js';

export const diagnosticHash=(v:unknown)=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
export {classifyDiagnosticEvent,annotateDiagnosticHistory} from './diagnostic-classification.js';
export function classifyDiagnostic(message:string,row:Record<string,unknown>):DiagnosticEventType{return classifyDiagnosticEvent(message,row).type;}
function timeOf(row:Record<string,unknown>,line:string,p:DiagnosticPermission):{time:string|null;authority:DiagnosticEvent['timeAuthority']}{
 const raw=row.__REALTIME_TIMESTAMP?Number(row.__REALTIME_TIMESTAMP)/1000:row.timestamp??row.time??row.Time??row.datetime;
 if(raw!==undefined){const v=typeof raw==='number'?new Date(raw<1e12?raw*1000:raw):new Date(String(raw));if(Number.isFinite(v.getTime()))return{time:v.toISOString(),authority:'SOURCE'};}
 const iso=line.match(/\b\d{4}[-/]\d{2}[-/]\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?/);if(iso){const explicit=/Z$|[+-]\d{2}:?\d{2}$/.test(iso[0]);if(explicit){const d=new Date(iso[0]);if(Number.isFinite(d.getTime()))return{time:d.toISOString(),authority:'SOURCE'};}}
 // Do not invent timezone/year for local syslog/nginx timestamps. Unknown times are excluded from bounded scans.
 const apache=line.match(/\[(\d{2})\/([A-Za-z]{3})\/(\d{4}):(\d{2}:\d{2}:\d{2}) ([+-]\d{4})\]/);if(apache){const d=new Date(`${apache[1]} ${apache[2]} ${apache[3]} ${apache[4]} ${apache[5]}`);if(Number.isFinite(d.getTime()))return{time:d.toISOString(),authority:'SOURCE'};}
 return{time:null,authority:'UNKNOWN'};
}
const field=(r:Record<string,unknown>,...keys:string[])=>{for(const k of keys)if(typeof r[k]==='string'||typeof r[k]==='number')return String(r[k]);return null;};
export function normalizeDiagnostic(collection:DiagnosticCollection,source:DiagnosticSource,p:DiagnosticPermission,sanitizer:DiagnosticSanitizer,architecture:DiagnosticArchitecture,collectedAt:string){
 const events:DiagnosticEvent[]=[],evidence:DiagnosticEvidence[]=[],dedupe=new Map<string,DiagnosticEvent>();let malformed=0,outsideWindow=0,unknownTime=0,redactions=0,examined=0,filteredSeverity=0,limitReached=false;
 const lines=collection.text.split(/\r?\n/),selected=lines.slice(0,p.bounds.maxLinesPerSource);
 for(const [index,raw] of selected.entries()){
  if(!raw.trim())continue;examined++;if(raw.length>16384){malformed++;continue;}let row:Record<string,unknown>={};
  if(source.format!=='TEXT'){try{const parsed=JSON.parse(raw);if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw Error();row=parsed;}catch{malformed++;continue;}}
  const t=timeOf(row,raw,p);if(!t.time){unknownTime++;continue;}if(t.time<p.bounds.since||t.time>p.bounds.until){outsideWindow++;continue;}
  const message=field(row,'MESSAGE','message','msg')??raw,classified=classifyDiagnosticEvent(message,row,t.time),{type,severity}=classified;
  if(p.scope==='ERRORS_ONLY'&&severity!=='ERROR'){filteredSeverity++;continue;}
  const sanitized=sanitizer.text(message===raw&&source.format!=='TEXT'?JSON.stringify(sanitizer.value(row)):message);redactions+=sanitized.redactions;
  const serviceRaw=field(row,'_SYSTEMD_UNIT','service','unit')??(source.componentIds.find(x=>x.startsWith('service:'))?.slice(8)??null),containerRaw=field(row,'CONTAINER_ID_FULL','container','id');
  const known=architecture.components.find(c=>c.id===`service:${serviceRaw}`||Boolean(serviceRaw&&c.label===serviceRaw)||Boolean(containerRaw&&c.id===`container:${containerRaw}`));
  const componentId=known?.id??source.componentIds[0]??null;
  const normalized=sanitized.text.replace(/\b\d+\b/g,'#'),bucket=Math.floor(Date.parse(t.time)/300000),fingerprint=diagnosticHash([source.id,componentId,serviceRaw,containerRaw,type,normalized,bucket]);
  const previous=dedupe.get(fingerprint);if(previous){previous.count++;previous.firstSeen=previous.firstSeen!<t.time?previous.firstSeen:t.time;previous.lastSeen=previous.lastSeen!>t.time?previous.lastSeen:t.time;continue;}
  if(events.length>=p.bounds.maxEvents){limitReached=true;continue;}
  const id=`event-${fingerprint.slice(0,20)}`,ref=`evidence-${diagnosticHash([collection.sourceId,index,sanitized.text]).slice(0,20)}`;
  evidence.push({id:ref,sourceId:source.id,sanitizedText:sanitized.text,sha256:diagnosticHash(sanitized.text),sourceIdentity:source.identity,collectedAt,location:{...collection.locator,sampledLine:index+1},untrusted:true,rawRetained:false});
  if(classified.classification.recoveryKey)classified.classification.recoveryKey=sanitizer.identifier('identifiers',classified.classification.recoveryKey)!;
  const ev:DiagnosticEvent={classification:classified.classification,id,timestamp:t.time,timeAuthority:t.authority,firstSeen:t.time,lastSeen:t.time,count:1,sourceId:source.id,componentId,host:sanitizer.identifier('hostnames',field(row,'_HOSTNAME','host','hostname')),service:sanitizer.identifier('identifiers',serviceRaw),process:sanitizer.identifier('identifiers',field(row,'_COMM','process','SYSLOG_IDENTIFIER')),pid:/^\d+$/.test(field(row,'_PID','pid')??'')?Number(field(row,'_PID','pid')):null,container:sanitizer.identifier('identifiers',containerRaw),severity,type,resource:['GPU_PRESSURE','MEMORY_PRESSURE','DISK_PRESSURE'].includes(type)?type.split('_')[0]:null,job:sanitizer.identifier('identifiers',field(row,'jobId','runId','job')),worker:sanitizer.identifier('identifiers',field(row,'workerId','worker')),lane:sanitizer.identifier('identifiers',field(row,'laneId','lane')),relatedService:sanitizer.identifier('identifiers',field(row,'relatedService','upstream')),message:sanitized.text,fingerprint,evidenceRef:ref,sanitization:{version:DIAGNOSTIC_SANITIZER_VERSION,redactions:sanitized.redactions,untrusted:true}};
  events.push(ev);dedupe.set(fingerprint,ev);
 }
 return{events,evidence,redactions,coverage:{sourceId:source.id,status:collection.status,bytesRead:collection.bytesRead,linesExamined:examined,events:events.reduce((a,e)=>a+e.count,0),malformed,outsideWindow,unknownTime,truncated:collection.truncated||lines.length>selected.length||limitReached,sampling:`${collection.sampling}; ${events.length} event groups retained (source allocation ${p.bounds.maxEvents}); ${filteredSeverity} excluded by severity; unknown-time records withheld`}};
}
function dependencies(graph:DiagnosticArchitecture){
 const adjacency=new Map<string,Set<string>>(),reachable=new Map<string,Set<string>>();for(const edge of graph.edges){if(edge.kind!=='DEPENDS_ON')continue;for(const [a,b]of [[edge.from,edge.to],[edge.to,edge.from]]){const links=adjacency.get(a!)??new Set<string>();links.add(b!);adjacency.set(a!,links);}}
 return(a:string|null,b:string|null)=>{if(!a||!b||a===b)return false;let seen=reachable.get(a);if(!seen){seen=new Set([a]);let front=[a];for(let depth=0;depth<4&&front.length;depth++){const next:string[]=[];for(const id of front)for(const other of adjacency.get(id)??[]){if(!seen.has(other)){seen.add(other);next.push(other);}}front=next;}reachable.set(a,seen);}return seen.has(b);};
}
export function diagnosticConfidence(f:DiagnosticFinding['factors']):DiagnosticFinding['confidence']{if(!f.directErrorEvidence)return'INSUFFICIENT_EVIDENCE';if(f.independentSources>=2&&f.knownDependency&&f.temporalRelationship&&f.occurrences>=3&&!f.coverageIncomplete)return'HIGH';if(f.knownDependency&&f.independentSources>=2&&f.temporalRelationship||f.occurrences>=3)return'MEDIUM';return'LOW';}
export function correlateDiagnostics(inputEvents:DiagnosticEvent[],graph:DiagnosticArchitecture,incomplete:boolean):DiagnosticFinding[]{
 const events=inputEvents.filter(e=>!e.classification?.duplicateOf);
 const findings:DiagnosticFinding[]=[],dependency=dependencies(graph);
 const add=(key:string,title:string,group:DiagnosticEvent[],explanation:string|null,temporal:boolean)=>{
  const components=[...new Set(group.map(e=>e.componentId).filter((v):v is string=>!!v))],known=components.some(a=>components.some(b=>dependency(a,b))),sources=new Set(group.map(e=>e.sourceId)),count=group.reduce((n,e)=>n+e.count,0);
  const factors={occurrences:count,independentSources:Math.min(sources.size,components.length),temporalRelationship:temporal,knownDependency:known,directErrorEvidence:group.some(e=>e.severity==='ERROR'),coverageIncomplete:incomplete};
  const status:DiagnosticFinding['status']=sources.size>1&&temporal?'CORRELATED':'OBSERVED';const times=group.flatMap(e=>[e.firstSeen,e.lastSeen]).filter((x):x is string=>!!x).sort();
  findings.push({temporal:group.every(e=>Boolean(e.timestamp))?'HISTORICAL':'UNKNOWN',incidentStatus:group.every(e=>e.classification?.incidentStatus==='RESOLVED')?'RESOLVED':'UNKNOWN',classificationReasons:[...new Set(group.flatMap(e=>e.classification?.rationale??['Legacy event classification; inspect original evidence.']))],recoveryEvidenceRefs:[...new Set(group.flatMap(e=>e.classification?.recoveryEvidenceRefs??[]))],id:`finding-${diagnosticHash(key).slice(0,20)}`,key,title,status,confidence:diagnosticConfidence(factors),componentIds:components,eventIds:group.map(e=>e.id),evidenceRefs:group.map(e=>e.evidenceRef),window:{start:times[0]??null,end:times.at(-1)??null},observations:group.map(e=>`${e.count} × ${e.type} (${e.id})`),correlation:status==='CORRELATED'?`Events form linked windows of up to five minutes across ${sources.size} sources. ${known?'A configured dependency connects affected components.':'No confirmed dependency connects these sources.'}`:null,inference:explanation,causation:'NOT_PROVEN',competingExplanations:explanation?['A shared upstream condition or an unrelated concurrent workload could explain this association.','Sampling and missing sources can omit contrary evidence.']:[],factors,analysisPath:['bounded collection','deterministic normalization','sanitization','pattern aggregation','temporal and topology correlation'],producer:{kind:'RULE',id:key.split(':')[0],version:'2.0.0'},investigations:['Inspect the linked evidence and the missing coverage before changing the system.','Compare resource consumers and dependency health in the same time window.'],remediation:{authority:'PROPOSAL_ONLY',summary:explanation?'Create a separately approved investigation job to test resource admission and dependency readiness.':'Create a separately approved investigation job to reproduce this pattern safely.',requiresSeparateApproval:true,autoExecutable:false}});
 };
 const groups=new Map<string,DiagnosticEvent[]>();for(const e of events){if(['UNKNOWN','INFO','JOB_START','JOB_SUCCESS','BOOT','SHUTDOWN','MODEL_CHANGE'].includes(e.type))continue;const key=`pattern:${e.componentId??e.sourceId}:${e.type}`;groups.set(key,[...(groups.get(key)??[]),e]);}
 for(const [key,group]of groups){const count=group.reduce((n,e)=>n+e.count,0);if(count>=3)add(key,`Recurring ${group[0]!.type.toLowerCase().replaceAll('_',' ')} (${count} observations)`,group,null,false);else if(group.some(e=>e.severity==='ERROR'))add(key,`${group[0]!.type.replaceAll('_',' ')} observed`,group,null,false);}
 const covered=new Set<string>(),chains=new Map<string,{group:DiagnosticEvent[];windows:number;label:string;linked:boolean}>();for(const anchor of events.filter(e=>['GPU_PRESSURE','MEMORY_PRESSURE','ALLOCATION_FAILURE','SERVICE_EXIT','RESTART','MODEL_CHANGE','BOOT','JOB_START'].includes(e.type))){
  if(covered.has(anchor.id))continue;const start=Date.parse(anchor.firstSeen!),end=Date.parse(anchor.lastSeen!)+300000,group=events.filter(e=>Date.parse(e.firstSeen!)>=start&&Date.parse(e.firstSeen!)<=end&&e.type!=='INFO');
  const kinds=new Set(group.map(e=>e.type)),sources=new Set(group.map(e=>e.sourceId));if(sources.size<2||kinds.size<2||!group.some(e=>e.severity==='ERROR'))continue;
  if(group.every(e=>covered.has(e.id)))continue;for(const e of group)covered.add(e.id);
  const signature=diagnosticHash([...new Set(group.map(e=>`${e.componentId}:${e.type}`))].sort()),linked=group.some(a=>group.some(b=>dependency(a.componentId,b.componentId))),label=kinds.has('JOB_FAILURE')?'Agent Control outcome and system events':kinds.has('PROXY_FAILURE')?'Service and proxy availability pattern':'Cross-source resource and lifecycle pattern';
  const previous=chains.get(signature);if(previous){previous.group.push(...group.filter(e=>!previous.group.some(x=>x.id===e.id)));previous.windows++;}else chains.set(signature,{group,windows:1,label,linked});
 }
 for(const [signature,chain]of chains)add(`cross-source:${signature.slice(0,20)}`,`${chain.windows>1?'Recurring ':''}${chain.label} (${chain.windows} window${chain.windows===1?'':'s'})`,chain.group,chain.linked?'Resource pressure or dependency instability may contribute to the observed availability failures. This is an inference, not established causation.':'The temporal association warrants investigation; architecture evidence is insufficient to explain a causal path.',true);
 return findings.sort((a,b)=>Number(b.status==='CORRELATED')-Number(a.status==='CORRELATED')||b.eventIds.length-a.eventIds.length).slice(0,100);
}
export function diagnosticReport(a:DiagnosticAssessment){return`# Historical architecture diagnostic assessment\n\n${a.id}\n\nCurrent incident status: UNKNOWN unless a finding links explicit same-operation recovery evidence. Collection: ${a.collectionStatus??'LEGACY_UNSPECIFIED'}; classifier: ${a.classifierVersion??'LEGACY_UNREVIEWED'}.\n\nRead-only • ${a.createdAt} • Job ${a.jobId} / ${a.runId}\n\n## Diagnostic permission scope\n\n${a.permission.scope}; ${a.permission.bounds.since} to ${a.permission.bounds.until}. External processing: ${a.permission.externalModelProcessing}.\nSources selected: ${a.permission.sourceIds.join(', ')}. Excluded: ${a.permission.excludedSourceIds.join(', ')}.\n\n## System architecture\n\n${a.architecture.components.map(c=>`- ${c.id}: ${c.label} (${c.kind})`).join('\n')}\n\n## Evidence sources and coverage\n\n${a.coverage.map(c=>`- ${c.sourceId}: ${c.status}, ${c.events} observations, ${c.bytesRead} bytes; truncated=${c.truncated}; unknown time=${c.unknownTime}; malformed=${c.malformed}. ${c.sampling}`).join('\n')}\n\n## Sanitisation\n\n${a.sanitization.status} — ${a.sanitization.version}, ${a.sanitization.redactions} transformations. Raw logs not retained; heuristic redaction cannot guarantee detection of every secret.\n\n## Historical patterns; current health unknown\n\n${a.health.map(h=>`- ${h.componentId}: current UNKNOWN; historical ${h.historicalState??h.state}. ${h.basis}`).join('\n')}\n\n## Architectural findings and recurring patterns\n\n${a.findings.map(f=>`### ${f.title}\n\n${f.status} / ${f.confidence}. Time: ${f.temporal??'HISTORICAL'}. Incident status: ${f.incidentStatus??'UNKNOWN'}. Classification: ${(f.classificationReasons??['Legacy classification; not current incident evidence.']).join(' ')}. Recovery evidence: ${(f.recoveryEvidenceRefs??[]).join(', ')||'None'}. Causation: ${f.causation}.\nObserved: ${f.observations.join('; ')}\n\nCorrelation: ${f.correlation??'None established'}\n\nInferred: ${f.inference??'None'}\n\nFactors: ${JSON.stringify(f.factors)}\n\nCompeting explanations: ${f.competingExplanations.join(' ')}\n\nEvidence: ${f.evidenceRefs.join(', ')}\n\nWindow: ${f.window.start} — ${f.window.end}\n\nProducer: ${f.producer.id}@${f.producer.version}. Path: ${f.analysisPath.join(' → ')}\n\nRecommended investigations: ${f.investigations.join(' ')}\n\nPotential remediation job (PROPOSAL ONLY, separate approval): ${f.remediation.summary}`).join('\n\n')||'No findings in the bounded sample. This does not establish health.'}\n\n## History comparison\n\n${a.comparison.state}: ${a.comparison.reason}\n\n## Unknowns and missing evidence\n\n${a.limitations.map(l=>`- ${l}`).join('\n')}\n\n## Evidence provenance\n\n${a.evidence.map(e=>`- ${e.id}: source ${e.sourceId}, source identity ${e.sourceIdentity}, sanitized SHA256 ${e.sha256}, locator ${JSON.stringify(e.location)}`).join('\n')}\n\nAssessment SHA256: ${a.sha256}\n`;}
