import {createHash,randomUUID} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import type {ModelRegistry,ModelRouteDecision} from './model-registry.js';
import {OpenAICompatibleProviderClient,type ModelInvocationResult} from './openai-compatible-provider.js';
import {resolveProviderAccountCredential} from './provider-credential-store.js';
import {createInvocationObservation,createInvocationStart,type HarnessEfficiencyLedgerPort} from './harness-efficiency.js';
import {redactSensitiveValue} from './security-redaction.js';
import type {AgentControlConfig} from './config.js';
import {CostRoutingLedger} from './cost-performance-routing.js';
import {configuredCostRoutingInvocation} from './cost-routing-projection.js';

export type InferenceRouteKind='RAW_INFERENCE'|'AGENT_WORKFLOW';
export interface DirectInferenceRequest{prompt:string;model?:string;modelRole?:string;nodeId:string;requiredCapabilities?:string[];maximumOutputTokens?:number;timeoutMs?:number;signal?:AbortSignal;jobId?:string;runId?:string;stepId?:string;}
export interface DirectInferenceReceipt{schema:'agent-control.direct-inference/v1';routeKind:'RAW_INFERENCE';invocationId:string;requestedModel:string|null;requestedRole:string|null;resolved:{model:string;provider:string;providerModel:string;responseModel:string|null;node:string;qualificationVersion:string;fallback:boolean};output:string;latencyMs:number;usage:ModelInvocationResult['usage']&{reasoningTokens:number|null};accounting:{execution:'LOCAL'|'API';billing:'FREE'|'INCLUDED'|'METERED'|'UNKNOWN';source:'PROVIDER_REPORTED'|'UNAVAILABLE'};finishReason:string|null;evidence:string[];}
export interface DirectInferenceEvidencePort{record(value:unknown):string;read(reference:string):unknown;}

export class FileDirectInferenceEvidenceStore implements DirectInferenceEvidencePort{
 constructor(readonly root:string){}
 record(value:unknown){const safe=redactSensitiveValue(value),bytes=Buffer.from(`${JSON.stringify(safe,null,2)}\n`),sha256=sha(bytes),file=path.join(this.root,`${sha256}.json`);fs.mkdirSync(this.root,{recursive:true,mode:0o700});if(!fs.existsSync(file))fs.writeFileSync(file,bytes,{mode:0o600,flag:'wx',flush:true});return`direct-inference:${sha256}`;}
 read(reference:string){const match=reference.match(/^direct-inference:([a-f0-9]{64})$/);if(!match)throw Error('direct_inference_evidence_reference_invalid');const file=path.join(this.root,`${match[1]}.json`),bytes=fs.readFileSync(file);if(sha(bytes)!==match[1])throw Error('direct_inference_evidence_integrity_failed');return JSON.parse(bytes.toString('utf8'));}
}

export class DirectInferenceRuntime{
 constructor(readonly models:ModelRegistry,readonly ledger:HarnessEfficiencyLedgerPort,readonly clientFactory=(route:ModelRouteDecision)=>providerClient(models,route),readonly evidenceStore?:DirectInferenceEvidencePort,readonly costRouting?:{config:AgentControlConfig;ledger:CostRoutingLedger}){}
 evidence(reference:string){if(!this.evidenceStore)throw Error('direct_inference_evidence_unconfigured');return this.evidenceStore.read(reference);}
 async invoke(request:DirectInferenceRequest):Promise<DirectInferenceReceipt>{
  if(!request.prompt.trim()||request.prompt.length>1_000_000)throw Error('direct_inference_prompt_invalid');
  if(Boolean(request.model)===Boolean(request.modelRole))throw Error('direct_inference_route_selector_invalid');
  if(request.maximumOutputTokens!==undefined&&(!Number.isSafeInteger(request.maximumOutputTokens)||request.maximumOutputTokens<1||request.maximumOutputTokens>65_536))throw Error('direct_inference_output_limit_invalid');
  const route=this.models.route({...(request.model?{model:request.model}:{modelRole:request.modelRole}),nodeId:request.nodeId,requiredCapabilities:request.requiredCapabilities??[],allowFallback:false,purpose:'EXECUTION'}),provider=this.models.provider(route.providerId)!;
  if(!['responses','openai-compatible','local'].includes(provider.kind))throw Error('direct_inference_adapter_unsupported');
  const startedAt=new Date().toISOString(),id=`inv-raw-${randomUUID()}`,jobId=request.jobId??`direct-inference-${randomUUID()}`,fingerprint=sha(JSON.stringify({route,prompt:sha(request.prompt)}));
  this.ledger.record(createInvocationStart({id,jobId,runId:request.runId,stepId:request.stepId,taskId:`${jobId}:raw`,laneId:`job:${jobId}`,model:route.modelId,provider:route.providerId,harnessProfile:'THIN',executionStrategy:'RAW_INFERENCE',startedAt,recipeFingerprint:fingerprint}));
  try{
   const result=await this.clientFactory(route).invoke(this.models.model(route.modelId)!,request.prompt,{maximumOutputTokens:request.maximumOutputTokens??256,timeoutMs:request.timeoutMs??60_000,signal:request.signal,costRouting:this.costRouting?configuredCostRoutingInvocation(this.costRouting.config,{providerId:route.providerId,modelId:route.modelId,jobId,runId:request.runId,invocationId:id,inputTokensEstimated:Math.max(1,Math.ceil(request.prompt.length/4)),outputTokensRequested:request.maximumOutputTokens??256},this.costRouting.ledger):undefined});
   if(result.toolCall)throw Object.assign(new Error('direct_inference_tool_output_forbidden'),{result});
   const completedAt=new Date().toISOString(),evidence=[`request_sha256:${sha(request.prompt)}`,`response_sha256:${sha(result.output)}`,`qualification:${route.qualificationVersion}`],rawUsage={input_tokens:result.usage.inputTokens,input_tokens_details:{cached_tokens:result.usage.cachedInputTokens,cache_write_tokens:result.usage.cacheWriteTokens},output_tokens:result.usage.outputTokens,output_tokens_details:{reasoning_tokens:result.usage.reasoningTokens??null},total_tokens:result.usage.totalTokens};
   const retained=this.evidenceStore?.record({schema:'agent-control.direct-inference-evidence/v1',invocationId:id,jobId,runId:request.runId??null,stepId:request.stepId??null,startedAt,completedAt,routeKind:'RAW_INFERENCE',request:{prompt:request.prompt,model:request.model??null,modelRole:request.modelRole??null,nodeId:request.nodeId,requiredCapabilities:request.requiredCapabilities??[],maximumOutputTokens:request.maximumOutputTokens??256,timeoutMs:request.timeoutMs??60000},resolved:{model:route.modelId,provider:route.providerId,providerModel:route.providerModel,responseModel:result.responseModel,node:route.providerExecutionNodeId??route.nodeId,qualificationVersion:route.qualificationVersion,fallback:route.fallback},response:{output:result.output,finishReason:result.finishReason,latencyMs:result.elapsedMs,usage:{...result.usage,reasoningTokens:result.usage.reasoningTokens??null}},hashes:{request:sha(request.prompt),response:sha(result.output)}});if(retained)evidence.push(retained);
   const accounting={schema:'agent-control.usage-accounting/v1' as const,revision:0,parentInvocationId:null,retryOfInvocationId:null,parcelId:null,batonId:null,providerRequestId:null,modelRevision:route.qualificationVersion,runtime:provider.kind,runtimeVersion:null,machine:route.providerExecutionNodeId??route.nodeId,hardware:null,jobType:'direct-inference',executionKind:provider.kind==='local'?'LOCAL' as const:'API' as const,provenance:{kind:'NATIVE' as const,source:'direct-inference',sourceVersion:'1',migrationVersion:null,at:startedAt},semantics:{id:'provider-normalized-direct-inference/v1',input:'UNKNOWN' as const,reasoning:'UNKNOWN' as const,total:'PROVIDER_ONLY' as const,billing:'UNKNOWN' as const},evidence:{input:result.usage.inputTokens,cached:result.usage.cachedInputTokens,cacheWrite:result.usage.cacheWriteTokens??null,output:result.usage.outputTokens,reasoning:result.usage.reasoningTokens??null,total:result.usage.totalTokens},pricing:null,reportedCost:null,localApiChargeKnownZero:provider.kind==='local'};
   this.ledger.complete(id,createInvocationObservation({id,jobId,runId:request.runId,stepId:request.stepId,taskId:`${jobId}:raw`,laneId:`job:${jobId}`,model:route.modelId,provider:route.providerId,...(route.accountProfileId?{accountProfileId:route.accountProfileId}:{}),harnessProfile:'THIN',executionStrategy:'RAW_INFERENCE',startedAt,completedAt,rawUsage,accounting,finishReason:result.finishReason??undefined,recipeFingerprint:fingerprint,evidenceIds:evidence,outcome:'COMPLETE'}));
   return{schema:'agent-control.direct-inference/v1',routeKind:'RAW_INFERENCE',invocationId:id,requestedModel:route.requestedModel,requestedRole:route.requestedRole,resolved:{model:route.modelId,provider:route.providerId,providerModel:route.providerModel,responseModel:result.responseModel,node:route.providerExecutionNodeId??route.nodeId,qualificationVersion:route.qualificationVersion,fallback:route.fallback},output:result.output,latencyMs:result.elapsedMs,usage:{...result.usage,reasoningTokens:result.usage.reasoningTokens??null},accounting:{execution:provider.kind==='local'?'LOCAL':'API',billing:provider.costClass==='free'?'FREE':provider.costClass==='included'?'INCLUDED':provider.costClass==='metered'?'METERED':'UNKNOWN',source:[result.usage.inputTokens,result.usage.cachedInputTokens,result.usage.outputTokens].some(value=>value!==null)?'PROVIDER_REPORTED':'UNAVAILABLE'},finishReason:result.finishReason,evidence};
  }catch(error){this.ledger.finalizePending([id],request.signal?.aborted?'CANCELLED':'FAILED',classifyDirectInferenceFailure(error),request.signal?.aborted?'cancelled':'failed');throw error;}
 }
}

function providerClient(models:ModelRegistry,route:ModelRouteDecision){const provider=models.provider(route.providerId)!,account=route.accountProfileId?models.accountProfile(route.providerId,route.accountProfileId):undefined,credential=account?()=>resolveProviderAccountCredential(provider,account,process.env,undefined,route.providerExecutionNodeId??route.nodeId):undefined;return new OpenAICompatibleProviderClient(provider,fetch,credential,{accountProfileId:account?.id,nodeId:route.providerExecutionNodeId??route.nodeId});}
export function classifyDirectInferenceFailure(error:unknown){const message=error instanceof Error?error.message:String(error);if(/tool.*(?:argument|output)|malformed.*tool/i.test(message))return'malformed_tool_output';if(/cancel/i.test(message))return'cancelled';if(/timeout/i.test(message))return'timeout';if(/auth/i.test(message))return'authentication';if(/policy|route_unavailable|forbidden/i.test(message))return'policy';if(/transport|fetch|http/i.test(message))return'transport';return'execution';}
function sha(value:string|Buffer){return createHash('sha256').update(value).digest('hex');}
