import {integratePower,type EnergyMeasurementInput,type EnergyAccounting} from './usage-energy.js';
import {createHash, randomUUID} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

export type EnergyAuthority='MEASURED'|'DERIVED'|'ESTIMATED'|'UNAVAILABLE';
export type EnergyScope='WHOLE_NODE'|'MEASURED_COMPONENTS'|'GPU_ONLY'|'CPU_PACKAGE'|'DEVICE_BATTERY'|'PROVIDER_UNKNOWN';
export interface PowerSample {at:string;nodeId:string;scope:EnergyScope;watts:number|null;cpuWatts?:number|null;gpuWatts?:number|null;cpuUtilizationPercent?:number|null;gpuUtilizationPercent?:number|null;vramUsedBytes?:number|null;vramTotalBytes?:number|null;authority:EnergyAuthority;source:string;limitations:string[];}
export interface EnergyBaseline {nodeId:string;scope:EnergyScope;averageWatts:number;sampleCount:number;startedAt:string;completedAt:string;authority:EnergyAuthority;source:string;limitations:string[];}
export interface EnergyExecutionInput {parcelId:string;stageId:string;route:{providerId:string;modelId:string;nodeId:string;accountProfileId?:string|null};samples:PowerSample[];idleBaseline?:EnergyBaseline|null;tokens?:number|null;verified:boolean;successful:boolean;kind?:'INFERENCE'|'TRAINING'|'MODEL_LOAD'|'MODEL_IDLE';evidence?:string[];}
export interface EnergyExecutionRecord {accounting?:EnergyAccounting;schema:'agent-control.energy-execution/v1';id:string;parcelId:string;stageId:string;route:EnergyExecutionInput['route'];kind:NonNullable<EnergyExecutionInput['kind']>;startedAt:string;completedAt:string;elapsedMs:number;scope:EnergyScope;authority:EnergyAuthority;measurementMethod:string;sampleCount:number;averageWatts:number|null;peakWatts:number|null;grossWh:number|null;incrementalWh:number|null;joules:number|null;idleBaselineWatts:number|null;tokens:number|null;whPerToken:number|null;whPerSuccessfulParcel:number|null;verified:boolean;successful:boolean;limitations:string[];evidence:string[];sha256:string;}
export interface EnergyRouteCandidate {id:string;capable:boolean;qualified:boolean;quality:number;confidence:number;latencyMs:number|null;monetaryCost:number|null;expectedEnergyWh:number|null;energyAuthority:EnergyAuthority;successProbability:number|null;fallbackEnergyWh?:number|null;locality?:number;privacy?:number;memoryAffinity?:number;declaredOrder?:number;}
export interface EnergyRoutingPolicy {minimumQuality:number;minimumConfidence:number;qualityWeight:number;confidenceWeight:number;latencyWeight:number;costWeight:number;energyWeight:number;localityWeight:number;privacyWeight:number;memoryAffinityWeight:number;latencyReferenceMs:number;costReference:number;energyReferenceWh:number;}
export interface EnergyRouteDecision {schema:'agent-control.energy-route-decision/v1';id:string;parcelId:string;stageId:string;at:string;candidates:Array<EnergyRouteCandidate&{eligible:boolean;expectedTotalEnergyWh:number|null;score:number;reasons:string[]}>;selectedId:string|null;reason:string;}
interface Snapshot {schema:'agent-control.energy-telemetry/v1';baselines:EnergyBaseline[];executions:EnergyExecutionRecord[];decisions:EnergyRouteDecision[];}
const defaults:EnergyRoutingPolicy={minimumQuality:.7,minimumConfidence:.5,qualityWeight:.35,confidenceWeight:.1,latencyWeight:.1,costWeight:.1,energyWeight:.2,localityWeight:.05,privacyWeight:.05,memoryAffinityWeight:.05,latencyReferenceMs:1000,costReference:1,energyReferenceWh:1};
const stable=(v:unknown):string=>JSON.stringify(sort(v));const sort=(v:unknown):unknown=>Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.entries(v as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,sort(x)])):v;
const hash=(v:unknown)=>createHash('sha256').update(stable(v)).digest('hex');
export class FileEnergyTelemetryStore {private value:Snapshot={schema:'agent-control.energy-telemetry/v1',baselines:[],executions:[],decisions:[]};constructor(readonly file?:string){if(file&&fs.existsSync(file)){const v=JSON.parse(fs.readFileSync(file,'utf8')) as Snapshot;if(v.schema!=='agent-control.energy-telemetry/v1')throw new Error('energy_state_invalid');this.value=v;}}load(){return structuredClone(this.value);}save(v:Snapshot){this.value=structuredClone(v);if(!this.file)return;fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=`${this.file}.${process.pid}.tmp`;fs.writeFileSync(tmp,`${JSON.stringify(v,null,2)}\n`,{mode:0o600});fs.renameSync(tmp,this.file);}}
export class EnergyTelemetryRuntime {private state:Snapshot;constructor(private readonly store=new FileEnergyTelemetryStore(),private readonly clock=()=>new Date().toISOString()){this.state=store.load();}
  establishBaseline(samples:PowerSample[]){const valid=validatedSamples(samples);if(valid.some(x=>x.scope!==valid[0]!.scope||x.nodeId!==valid[0]!.nodeId))throw new Error('energy_baseline_scope_mismatch');const values=valid.map(x=>x.watts).filter((x):x is number=>x!==null),first=valid[0]!;if(values.length<2)throw new Error('energy_baseline_samples_insufficient');const value:EnergyBaseline={nodeId:first.nodeId,scope:first.scope,averageWatts:mean(values),sampleCount:values.length,startedAt:first.at,completedAt:valid.at(-1)!.at,authority:combineAuthority(valid),source:[...new Set(valid.map(x=>x.source))].join('+'),limitations:[...new Set(valid.flatMap(x=>x.limitations))]};this.state.baselines=this.state.baselines.filter(x=>!(x.nodeId===value.nodeId&&x.scope===value.scope));this.state.baselines.push(value);this.persist();return structuredClone(value);}
  recordExecution(input:EnergyExecutionInput){const samples=validatedSamples(input.samples);if(samples.some(x=>x.nodeId!==input.route.nodeId||x.scope!==samples[0]!.scope))throw new Error('energy_execution_scope_mismatch');const measured=samples.filter(x=>x.watts!==null),scope=samples[0]!.scope,authority=combineAuthority(samples),grossWh=integrate(measured),elapsedMs=Date.parse(samples.at(-1)!.at)-Date.parse(samples[0]!.at),averageWatts=grossWh===null||elapsedMs<=0?null:grossWh*3_600_000/elapsedMs,peakWatts=measured.length?Math.max(...measured.map(x=>x.watts!)):null,baseline=input.idleBaseline??this.state.baselines.find(x=>x.nodeId===input.route.nodeId&&x.scope===scope)??null,incrementalWh=grossWh===null||!baseline?null:Math.max(0,grossWh-baseline.averageWatts*elapsedMs/3_600_000),energy=incrementalWh??grossWh,tokens=finite(input.tokens),base={schema:'agent-control.energy-execution/v1' as const,id:`energy-${randomUUID()}`,parcelId:input.parcelId,stageId:input.stageId,route:{...input.route,accountProfileId:input.route.accountProfileId??null},kind:input.kind??'INFERENCE',startedAt:samples[0]!.at,completedAt:samples.at(-1)!.at,elapsedMs,scope,authority,measurementMethod:[...new Set(samples.map(x=>x.source))].join('+'),sampleCount:measured.length,averageWatts,peakWatts,grossWh,incrementalWh,joules:energy===null?null:energy*3600,idleBaselineWatts:baseline?.averageWatts??null,tokens,whPerToken:energy!==null&&tokens&&tokens>0?energy/tokens:null,whPerSuccessfulParcel:input.verified&&input.successful?energy:null,verified:input.verified,successful:input.successful,limitations:[...new Set([...samples.flatMap(x=>x.limitations),...(scope!=='WHOLE_NODE'?['measurement_not_whole_node']:[]),...(!baseline?['idle_baseline_unavailable']:[])])],evidence:[...new Set(input.evidence??[])]};const record:EnergyExecutionRecord={...base,sha256:hash(base)};this.state.executions.push(record);this.persist();return structuredClone(record);}
  recordMeasurement(input:EnergyMeasurementInput){const v=integratePower(input),a=v.accounting,base={schema:'agent-control.energy-execution/v1' as const,id:`energy-${randomUUID()}`,parcelId:input.parcelId,stageId:input.stageId,route:{providerId:input.providerId,modelId:input.modelId,nodeId:input.nodeId},kind:'INFERENCE' as const,...v,scope:input.scope,authority:a.measurementClass==='UNAVAILABLE'?'UNAVAILABLE' as const:a.measurementClass==='ESTIMATED'?'ESTIMATED' as const:'DERIVED' as const,measurementMethod:input.methodology,joules:a.attributedWh===null?null:a.attributedWh*3600,idleBaselineWatts:a.baselineStatus==='VALID'?input.baseline!.averageWatts:null,tokens:input.tokens,whPerToken:a.attributedWh!==null&&input.tokens&&input.tokens>0?a.attributedWh/input.tokens:null,whPerSuccessfulParcel:input.verified&&input.successful?a.attributedWh:null,verified:input.verified,successful:input.successful,limitations:[...(input.scope!=='WHOLE_NODE'?['measurement_not_whole_node']:[]),...(a.coverage<1?['partial_coverage']:[]),...(a.attribution==='NOT_ATTRIBUTABLE'?['workload_attribution_unavailable']:[])],evidence:[...input.concurrencyEvidence]};const record:EnergyExecutionRecord={...base,sha256:hash(base)};if(this.state.executions.some(r=>r.accounting?.invocationId===input.invocationId&&r.accounting.sensorId===input.sensorId&&r.startedAt===v.startedAt&&r.completedAt===v.completedAt))throw Error('energy_measurement_duplicate');this.state.executions.push(record);this.persist();return structuredClone(record);}
  route(parcelId:string,stageId:string,candidates:EnergyRouteCandidate[],policy:Partial<EnergyRoutingPolicy>={}){const p={...defaults,...policy};const assessed=candidates.map((c,i)=>{const reasons:string[]=[];if(!c.capable)reasons.push('capability_unproven');if(!c.qualified)reasons.push('route_unqualified');if(c.quality<p.minimumQuality)reasons.push('quality_below_policy');if(c.confidence<p.minimumConfidence)reasons.push('confidence_below_policy');const total=expectedTotal(c),energy=total===null?.5:low(total,p.energyReferenceWh),score=c.quality*p.qualityWeight+c.confidence*p.confidenceWeight+low(c.latencyMs,p.latencyReferenceMs)*p.latencyWeight+low(c.monetaryCost,p.costReference)*p.costWeight+energy*p.energyWeight+(c.locality??.5)*p.localityWeight+(c.privacy??.5)*p.privacyWeight+(c.memoryAffinity??.5)*p.memoryAffinityWeight;return{...c,declaredOrder:c.declaredOrder??i,eligible:reasons.length===0,expectedTotalEnergyWh:total,score,reasons:[...reasons,...(total===null?['energy_unavailable_not_preferred']:[])]};});const eligible=assessed.filter(x=>x.eligible),withMeasured=eligible.filter(x=>x.expectedTotalEnergyWh!==null&&x.energyAuthority!=='UNAVAILABLE'),pool=withMeasured.length?withMeasured:eligible,selected=[...pool].sort((a,b)=>b.score-a.score||(a.declaredOrder??0)-(b.declaredOrder??0))[0]??null,decision:EnergyRouteDecision={schema:'agent-control.energy-route-decision/v1',id:`energy-route-${randomUUID()}`,parcelId,stageId,at:this.clock(),candidates:assessed,selectedId:selected?.id??null,reason:selected?`Selected ${selected.id} by governed capability, quality, confidence, expected total energy, latency, monetary cost, locality, privacy and memory affinity. Failed-attempt energy is included when evidence exists.`:'No candidate passed capability, qualification, quality and confidence gates.'};this.state.decisions.push(decision);this.persist();return structuredClone(decision);}
  breakEven(trainingWh:number|null,baselineWh:number|null,specialistWh:number|null){if([trainingWh,baselineWh,specialistWh].some(x=>x===null)||baselineWh!<=specialistWh!)return{parcels:null,reason:'positive_measured_energy_saving_unavailable'};return{parcels:Math.ceil(trainingWh!/(baselineWh!-specialistWh!)),reason:'training_wh_divided_by_measured_wh_saved_per_success'};}
  projection(){return structuredClone({...this.state,observedAt:this.clock(),totals:{measuredExecutions:this.state.executions.filter(x=>x.authority==='MEASURED').length,verifiedSuccessful:this.state.executions.filter(x=>x.verified&&x.successful).length,wholeNodeMeasurements:this.state.executions.filter(x=>x.scope==='WHOLE_NODE').length}});}private persist(){this.store.save(this.state);}}
export function mallowEnergyDigest(input:{taskPassed:boolean;route:string;energy:EnergyExecutionRecord;generalBaseline:{joules:number;authority:EnergyAuthority;scope:EnergyScope}|null;memoryReused:boolean;escalated:boolean}){const measured=input.energy.authority==='MEASURED'&&input.energy.joules!==null,baseline=input.generalBaseline,comparable=measured&&baseline?.authority==='MEASURED'&&baseline.scope===input.energy.scope&&baseline.joules>0,reduction=comparable?(baseline.joules-input.energy.joules!)/baseline.joules*100:null;return[`Task completed: ${input.taskPassed?'PASS':'FAIL'}`,`Route: ${input.route}`,`Energy measured: ${measured?`${input.energy.joules!.toFixed(3)} J / ${(input.energy.joules!/3600).toFixed(6)} Wh (${input.energy.scope})`:'UNAVAILABLE'}`,`General-model baseline: ${baseline===null?'UNAVAILABLE':`${baseline.joules.toFixed(3)} J (${baseline.authority}, ${baseline.scope})`}`,`Energy reduction: ${reduction===null?'UNAVAILABLE':`${reduction.toFixed(1)}%`}`,`Memory reused: ${input.memoryReused?'yes':'no'}`,`Escalation: ${input.escalated?'yes':'no'}`].join('\n');}
function validatedSamples(samples:PowerSample[]){if(samples.length<2)throw new Error('energy_samples_insufficient');const v=[...samples].sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));for(const x of v)if(!Number.isFinite(Date.parse(x.at))||x.watts!==null&&(!Number.isFinite(x.watts)||x.watts<0)||!x.nodeId||!x.source)throw new Error('energy_sample_invalid');return v;}
function integrate(samples:PowerSample[]){if(samples.length<2)return null;let ws=0;for(let i=1;i<samples.length;i++){const dt=(Date.parse(samples[i]!.at)-Date.parse(samples[i-1]!.at))/1000;if(dt<=0)return null;ws+=(samples[i-1]!.watts!+samples[i]!.watts!)/2*dt;}return ws/3600;}
function combineAuthority(s:PowerSample[]):EnergyAuthority{if(!s.some(x=>x.watts!==null))return'UNAVAILABLE';if(s.every(x=>x.authority==='MEASURED'))return'MEASURED';if(s.some(x=>x.authority==='ESTIMATED'))return'ESTIMATED';return'DERIVED';}function finite(x:number|null|undefined){return x!==null&&x!==undefined&&Number.isFinite(x)?x:null;}function mean(v:number[]){return v.reduce((a,b)=>a+b,0)/v.length;}function expectedTotal(c:EnergyRouteCandidate){if(c.expectedEnergyWh===null)return null;const success=c.successProbability??1,fallback=c.fallbackEnergyWh??0;return c.expectedEnergyWh+(1-Math.max(0,Math.min(1,success)))*fallback;}function low(v:number|null,reference:number){if(v===null)return.5;if(!Number.isFinite(v)||v<0||!Number.isFinite(reference)||reference<=0)return 0;return 1/(1+v/reference);}
/** @deprecated Use mallowEnergyDigest. */
export const poeEnergyDigest=mallowEnergyDigest;
