import {EnvironmentDiscoveryRuntime} from './environment-discovery.js';
import {Ajv2020} from 'ajv/dist/2020.js';
import {FactoryJournal} from './factory-view.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';import {once} from 'node:events';import type {AddressInfo} from 'node:net';
import {EstateDiscovery,registerEstateDiscovery,ESTATE_WORKER} from './estate-discovery.js';import {estateDiff,estateHash,assertEstateEvidence,estateProjection,type EstateSnapshot,type EstateEntity,type EstateEvidence,type EstateState} from './estate-model.js';import {emptyConfig} from './config.js';import {ActionRegistry,WorkerRegistry,createJobRuntime} from './job-runtime.js';import {JobCatalog} from './job-catalog.js';import {AgentControlService} from './application-service.js';import {PtyRegistry} from './pty.js';import {startWebDashboard} from './web-server.js';
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'estate-test-'));const ev=(override:Partial<EstateEvidence>={}):EstateEvidence=>({id:'e',source:'SYNTHETIC test evidence',method:'fixture',type:'OS_INVENTORY',at:new Date().toISOString(),permissionId:'p',category:'PASSIVE_INVENTORY',probe:null,result:'OBSERVATION',digest:estateHash('fixture'),runId:'r',activityRef:'run:r',ledgerRef:'run:r',...override});
const entity=(state:EstateState='OBSERVED'):EstateEntity=>({id:'host:test',kind:'host',label:'SYNTHETIC host',state,hostId:null,attributes:{},capabilities:{},factoryId:null,firstSeen:'2026-09-21T10:00:00Z',lastSeen:'2026-09-21T10:00:00Z',evidence:[ev()]});const snapshot=(entities:EstateEntity[]):EstateSnapshot=>({schema:'agent-control.estate/v1',id:'s',runId:'r',permissionId:'p',scopeDigest:'same',startedAt:'2026-09-21T10:00:00Z',completedAt:'2026-09-21T10:00:01Z',status:'COMPLETED',entities,relationships:[],events:[],diff:[],coverage:[],scanId:null});
function fixture(targets:ConstructorParameters<typeof EstateDiscovery>[0]['targets']=[]){const root=temp(),estate=new EstateDiscovery({root:path.join(root,'estate'),config:emptyConfig,targets}),runtime=createJobRuntime(path.join(root,'jobs'),new JobCatalog(),new ActionRegistry(),new WorkerRegistry());registerEstateDiscovery(runtime,estate);return{root,estate,runtime};}
async function run(f:ReturnType<typeof fixture>,categories:string[]=[],targetIds:string[]=[]){const p=f.estate.grant({categories,targetIds},'test');const run=f.runtime.createRun('discover-estate@1.0.0',{permissionId:p.id},{type:'manual',actor:'test'});await f.runtime.tick();return{permission:p,run:f.runtime.ledger.get(run.id)!,snapshot:f.estate.latest()!};}
test('Estate starts empty and registration does not invent inventory',()=>{const f=fixture();assert.equal(f.estate.latest(),null);assert.deepEqual(f.estate.projection().entities,[]);assert.equal(f.runtime.workers.list().length,1);});
test('Unsupported target, arbitrary fields and log scope fail closed',()=>{const f=fixture();assert.throws(()=>f.estate.grant({categories:[],targetIds:['outside']},'test'),/allowlisted/);assert.throws(()=>f.estate.grant({categories:[],targetIds:[],command:'cat secret'},'test'));assert.throws(()=>f.estate.grant({categories:[],targetIds:[],diagnosticAssessmentIds:['assessment-abcd']},'test'),/log_permission/);});
test('Remote, credential, DNS, query and redirect-capable endpoint seeds are not accepted',()=>{for(const locator of ['https://remote.invalid','http://localhost:8080','http://127.0.0.1.evil.invalid','http://secret@127.0.0.1','http://127.0.0.1/?secret=abc','file:///tmp/x'])assert.throws(()=>fixture([{id:'x',kind:'ENDPOINT',label:'fixture',locator}]),/loopback/);});
test('No permission yields BLOCKED and performs no scoped probes',async()=>{const f=fixture([{id:'no-read',kind:'ENDPOINT',label:'SYNTHETIC endpoint',locator:'http://127.0.0.1:1'}]);const r=await run(f,[],['no-read']);assert.equal(r.run.status,'SUCCEEDED');assert.ok(r.snapshot.entities.every(e=>e.state==='BLOCKED'));assert.equal(r.snapshot.entities.some(e=>e.state==='UNREACHABLE'),false);assert.ok(r.snapshot.events.filter(e=>e.type==='PERMISSION_BLOCKED').length===10);});
test('Only configuration permission yields EXPECTED before denied observation, never VERIFIED',async()=>{const f=fixture([{id:'configured',kind:'ENDPOINT',label:'Configured fixture',locator:'http://127.0.0.1:1'}]);const r=await run(f,['CONFIGURATION_READ'],['configured']);const events=r.snapshot.events.filter(e=>e.entity?.id==='endpoint:configured');assert.deepEqual(events.map(e=>e.entity!.state),['EXPECTED','BLOCKED']);});
test('Permission actor, expiry and revocation are enforced independently of UI',()=>{const f=fixture(),p=f.estate.grant({categories:[],targetIds:[]},'alice');assert.throws(()=>f.estate.assertPermission(p.id,'bob'),/denied/);f.estate.permissions.get(p.id)!.expiresAt='2000-01-01T00:00:00Z';assert.throws(()=>f.estate.assertPermission(p.id),/denied/);});
test('Revocation removes snapshot and replay access and empties stream projection',async()=>{const f=fixture(),r=await run(f);f.estate.revoke(r.permission.id,'test');assert.throws(()=>f.estate.snapshot(r.snapshot.id),/denied/);assert.throws(()=>f.estate.replay(r.snapshot.id),/denied/);assert.deepEqual(f.estate.projection().entities,[]);assert.deepEqual(f.estate.history(),[]);});
test('Historical logs and configuration cannot establish verified or capability states',()=>{for(const type of ['CONFIGURATION','HISTORICAL_LOG','INFERENCE'] as const)for(const state of ['VERIFIED','CAPABILITY_VERIFIED'] as const)assert.throws(()=>assertEstateEvidence(state,ev({type,result:'PASS',probe:'fixture'})));assert.throws(()=>assertEstateEvidence('OBSERVED',ev({type:'HISTORICAL_LOG'})));assert.doesNotThrow(()=>assertEstateEvidence('HISTORICALLY_OBSERVED',ev({type:'HISTORICAL_LOG'})));});
test('Capability requires actual scoped capability probe, not a successful service GET',()=>{assert.throws(()=>assertEstateEvidence('CAPABILITY_VERIFIED',ev({type:'SERVICE_RESPONSE',result:'PASS',probe:'GET health'})));assert.throws(()=>assertEstateEvidence('CAPABILITY_VERIFIED',ev({type:'CAPABILITY_PROBE',result:'PASS',probe:'literal'})));assert.doesNotThrow(()=>assertEstateEvidence('CAPABILITY_VERIFIED',ev({category:'CAPABILITY_PROBES',type:'CAPABILITY_PROBE',result:'PASS',probe:'literal'})));});
test('Probe failure and absent verification evidence never pass verification',()=>{for(const evidence of [ev(),ev({result:'FAIL',probe:'x'}),ev({result:'PASS'})])assert.throws(()=>assertEstateEvidence('VERIFIED',evidence));});
test('Unreachable does not mean removed and recovered resources preserve identity',()=>{assert.deepEqual(estateDiff(snapshot([entity('VERIFIED')]),snapshot([entity('UNREACHABLE')])).map(d=>d.change),['UNREACHABLE']);assert.deepEqual(estateDiff(snapshot([entity('UNREACHABLE')]),snapshot([entity('VERIFIED')])).map(d=>d.change),['RECOVERED']);assert.equal(estateDiff(snapshot([entity()]),snapshot([]))[0]!.change,'NOT_REOBSERVED');});
test('Snapshot diff distinguishes capability addition, regression and absent probes',()=>{const a=entity(),b={...entity(),capabilities:{text:'PASS' as const}},c={...entity(),capabilities:{text:'FAIL' as const}};assert.equal(estateDiff(snapshot([a]),snapshot([b]))[0]!.change,'CAPABILITY_ADDED');assert.equal(estateDiff(snapshot([b]),snapshot([c]))[0]!.change,'CAPABILITY_LOST');assert.deepEqual(estateDiff(snapshot([b]),snapshot([a])),[]);});
test('Scope changes cannot establish removal',()=>{const n=snapshot([]);n.scopeDigest='different';assert.match(estateDiff(snapshot([entity()]),n)[0]!.basis,/not comparable/);});
test('Relationship state is independent of endpoint verification',()=>{const s=snapshot([entity('VERIFIED')]);s.relationships=[{id:'link',from:'host:test',to:'host:test',kind:'inferred dependency',layer:'LOGICAL',state:'OBSERVED',basis:'INFERRED',firstSeen:s.startedAt,lastSeen:s.startedAt,evidence:[ev({type:'INFERENCE'})]}];const p=estateProjection(s);assert.equal(p.entities[0]!.state,'VERIFIED');assert.equal(p.relations[0]!.state,'OBSERVED');assert.equal(p.relations[0]!.basis,'INFERRED');});
test('Durable progressive events carry a contiguous hash chain and native receipt',async()=>{const f=fixture(),r=await run(f);let previous=null;for(const e of r.snapshot.events){const {sha256,...body}=e;assert.equal(e.previousHash,previous);assert.equal(sha256,estateHash(body));previous=sha256;}assert.ok(r.snapshot.scanId);const receipt=f.runtime.artifacts.read(r.run.artifacts[0]!);assert.ok(JSON.stringify(receipt).includes(r.snapshot.id));const restored=new EstateDiscovery(f.estate.options);assert.equal(restored.replay(r.snapshot.id).events.length,r.snapshot.events.length);});
test('Renderer observer crash does not affect discovery Job',async()=>{const f=fixture();f.estate.subscribe(()=>{throw Error('renderer unavailable');});assert.equal((await run(f)).run.status,'SUCCEEDED');});
test('Redaction happens before journal, persistence, UI and replay',async()=>{const f=fixture([{id:'target',kind:'ENDPOINT',label:'SYNTHETIC password=must-not-leak',locator:'http://127.0.0.1:1'}]);const r=await run(f,['CONFIGURATION_READ'],['target']);assert.ok(!JSON.stringify(r.snapshot).includes('must-not-leak'));assert.ok(!fs.readFileSync(path.join(f.estate.options.root,`${r.snapshot.id}.jsonl`),'utf8').includes('must-not-leak'));});
test('Real local passive inventory progresses from observed to identified and verified without granting model admission',async()=>{const f=fixture(),r=await run(f,['PASSIVE_INVENTORY','CAPABILITY_PROBES']);assert.equal(r.run.status,'SUCCEEDED');const stages=r.snapshot.events.filter(e=>e.entity?.id==='host:controller-local').map(e=>e.entity!.state);assert.deepEqual(stages.slice(0,2),['OBSERVED','IDENTIFIED']);if(process.platform==='linux')assert.equal(stages[2],'VERIFIED');assert.equal(r.snapshot.entities.find(e=>e.id===`worker:${ESTATE_WORKER}`)?.factoryId,`worker:${ESTATE_WORKER}`);});
test('Authorised failed contact is UNREACHABLE without raw transport errors',async()=>{const f=fixture([{id:'refused',kind:'ENDPOINT',label:'SYNTHETIC unavailable endpoint',locator:'http://127.0.0.1:1'}]);const r=await run(f,['SERVICE_ENUMERATION'],['refused']);assert.equal(r.snapshot.entities.find(e=>e.id==='endpoint:refused')?.state,'UNREACHABLE');assert.ok(!JSON.stringify(r.snapshot).includes('ECONNREFUSED'));});
test('HTTP endpoints authenticate reads, reject cross-origin mutation and support disabled renderer independently',async()=>{const f=fixture(),service=new AgentControlService({lanes:[]} as never,new PtyRegistry()),server=startWebDashboard(service,{host:'127.0.0.1',port:0,operatorToken:'estate-test',estate:f.estate,estateEnabled:false});await once(server,'listening');const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}/api/estate`;try{assert.equal((await fetch(base+'/catalog')).status,401);assert.equal((await fetch(base+'/snapshot',{headers:{Authorization:'Bearer estate-test'}})).status,404);assert.equal((await fetch(base+'/permissions',{method:'POST',headers:{Authorization:'Bearer estate-test',Origin:'https://untrusted.invalid','Content-Type':'application/json'},body:'{}'})).status,403);assert.equal((await run(f)).run.status,'SUCCEEDED');}finally{server.close();}});
test('An endpoint redirect cannot widen the approved scope',async()=>{let otherReads=0;const other=http.createServer((_q,r)=>{otherReads++;r.end('{}');});await once(other.listen(0,'127.0.0.1'),'listening');const redirected=http.createServer((_q,r)=>{r.writeHead(302,{Location:`http://127.0.0.1:${(other.address() as AddressInfo).port}/secret`});r.end();});await once(redirected.listen(0,'127.0.0.1'),'listening');try{const f=fixture([{id:'redirect',kind:'ENDPOINT',label:'SYNTHETIC redirect',locator:`http://127.0.0.1:${(redirected.address() as AddressInfo).port}`}]);const r=await run(f,['SERVICE_ENUMERATION'],['redirect']);assert.equal(otherReads,0);assert.equal(r.snapshot.entities.find(e=>e.id==='endpoint:redirect')?.state,'UNREACHABLE');}finally{other.close();redirected.close();}});
test('Native consumption binds the discovered worker identity and produces independently verified evidence',async()=>{if(process.platform!=='linux')return;const f=fixture(),r=await run(f,['PASSIVE_INVENTORY','CAPABILITY_PROBES']);const use=f.runtime.createRun('estate-system-observation@1.0.0',{snapshotId:r.snapshot.id},{type:'manual',actor:'test'});for(let i=0;i<4&&!['SUCCEEDED','FAILED'].includes(f.runtime.ledger.get(use.id)!.status);i++)await f.runtime.tick();const result=f.runtime.ledger.get(use.id)!;assert.equal(result.status,'SUCCEEDED');assert.deepEqual(result.selectedWorkers,[ESTATE_WORKER]);assert.ok(result.artifacts.map(id=>f.runtime.artifacts.read(id)).some(v=>(v as any).status==='PASS'));});
test('Discovery alone cannot run a capability-dependent consumer',async()=>{const f=fixture(),r=await run(f,['PASSIVE_INVENTORY']);const use=f.runtime.createRun('estate-system-observation@1.0.0',{snapshotId:r.snapshot.id},{type:'manual',actor:'test'});await f.runtime.tick();assert.equal(f.runtime.ledger.get(use.id)!.status,'FAILED');});
test('Identity disagreement becomes sticky CONFLICTED within a scan',async()=>{const f=fixture();let injected=false;f.estate.subscribe(()=>{const h=f.estate.latest()?.entities.find(e=>e.id==='host:controller-local');if(h?.state==='VERIFIED'&&!injected){injected=true;f.estate.observe({id:h.id,kind:'host',label:'SYNTHETIC conflict injected by unit test',state:'VERIFIED',attributes:{identityDigest:'different'}},ev({result:'PASS',probe:'fixture identity'}));}});const r=await run(f,['PASSIVE_INVENTORY']);if(injected){assert.equal(r.snapshot.entities.find(e=>e.id==='host:controller-local')?.state,'CONFLICTED');assert.equal(r.snapshot.status,'PARTIAL');}});
test('Tampered persisted event chain is rejected on restore',async()=>{const f=fixture();await run(f);const file=path.join(f.estate.options.root,'state.json'),v=JSON.parse(fs.readFileSync(file,'utf8'));v.snapshots[0].events[0].caption='modified';fs.writeFileSync(file,JSON.stringify(v));assert.throws(()=>new EstateDiscovery(f.estate.options),/integrity/);});
test('Restart marks old current observations STALE without rewriting recorded replay',async()=>{const f=fixture(),r=await run(f,['PASSIVE_INVENTORY']);const restored=new EstateDiscovery(f.estate.options);assert.equal(restored.projection().entities.find(e=>e.id==='host:controller-local')?.state,'STALE');assert.equal(restored.replay(r.snapshot.id).events.at(-1)?.sha256,r.snapshot.events.at(-1)?.sha256);});
test('Bounded streaming keeps 500 hosts inspectable and server search reaches omitted objects',()=>{const entities=Array.from({length:5500},(_,i)=>({...entity(),id:i<500?`host:${i}`:`service:${i}`,kind:i<500?'host' as const:'service' as const,label:`SYNTHETIC object ${i}`})),s=snapshot(entities),p=estateProjection(s);assert.equal(p.entities.length,600);assert.equal(p.entities.filter(e=>e.kind==='host').length,500);assert.equal(p.coverage.omittedEntities,4900);assert.equal(estateProjection(s,false,'object 5499').entities[0]?.id,'service:5499');assert.ok(Buffer.byteLength(JSON.stringify(p))<8*1024*1024);});
test('Estate reconnect restores a complete snapshot while discovery survives disconnected observers',async()=>{const f=fixture(),service=new AgentControlService({lanes:[]} as never,new PtyRegistry()),server=startWebDashboard(service,{host:'127.0.0.1',port:0,operatorToken:'estate-stream',estate:f.estate});await once(server,'listening');const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}/api/estate`;try{const request=await fetch(base+'/events',{headers:{Authorization:'Bearer estate-stream'}}),reader=request.body!.getReader();await reader.read();await reader.cancel();const r=await run(f);assert.equal(r.run.status,'SUCCEEDED');const next=await fetch(base+'/events',{headers:{Authorization:'Bearer estate-stream','Last-Event-ID':'expired:1'}}),nextReader=next.body!.getReader();const chunk=new TextDecoder().decode((await nextReader.read()).value);assert.match(chunk,/"gap":true/);assert.match(chunk,/estate-frame|factory-frame/);assert.match(chunk,/'blocked'|BLOCKED/);await nextReader.cancel();}finally{server.close();}});
test('Revocation during an in-flight endpoint probe cancels the Job and withholds evidence access',async()=>{let arrived!:()=>void;const pending=new Promise<void>(r=>arrived=r);const endpoint=http.createServer((_q,_r)=>arrived());await once(endpoint.listen(0,'127.0.0.1'),'listening');const f=fixture([{id:'pending',kind:'ENDPOINT',label:'SYNTHETIC pending probe',locator:`http://127.0.0.1:${(endpoint.address() as AddressInfo).port}`}]);const p=f.estate.grant({categories:['SERVICE_ENUMERATION'],targetIds:['pending']},'test');const native=f.runtime.createRun('discover-estate@1.0.0',{permissionId:p.id},{type:'manual',actor:'test'});try{const tick=f.runtime.tick();await pending;f.estate.revoke(p.id,'test');await tick;assert.equal(f.runtime.ledger.get(native.id)!.status,'FAILED');assert.throws(()=>f.estate.latest(),/denied/);}finally{endpoint.closeAllConnections();endpoint.close();}});

test('Existing Discovery projection preserves scope gating without reading general configuration',async()=>{const f=fixture();let configReads=0;const discovery=new EnvironmentDiscoveryRuntime({file:path.join(f.root,'shared-inventory.json'),config:()=>{configReads++;return emptyConfig();},configurationRevision:()=> 'test'});f.estate.options.environmentDiscovery=discovery;const r=await run(f);assert.equal(configReads,0);assert.equal(discovery.projection().latest?.id,r.snapshot.scanId);f.estate.revoke(r.permission.id,'test');assert.equal(discovery.projection().latest,null);assert.throws(()=>discovery.scan(r.snapshot.scanId!),/permission_denied/);const restored=new EnvironmentDiscoveryRuntime({file:path.join(f.root,'shared-inventory.json'),config:emptyConfig,configurationRevision:()=> 'test'});assert.equal(restored.projection().latest,null);});
test('Historical integration requires selected timestamped log evidence and preserves upstream revocation',async()=>{const f=fixture();let revoked=false;f.estate.options.diagnostics={assessment(){if(revoked)throw Error('diagnostic_permission_denied');return{id:'assessment-abcd',sha256:'fixture',architecture:{components:[{id:'a',label:'SYNTHETIC historical A'},{id:'b',label:'SYNTHETIC configuration only'},{id:'c',label:'SYNTHETIC historical C'}]},events:[{id:'event-a',componentId:'a',timestamp:'2026-09-20T10:00:00Z'},{id:'event-c',componentId:'c',timestamp:'2026-09-20T10:00:01Z'}],findings:[{id:'finding',status:'CORRELATED',componentIds:['a','c'],evidenceRefs:['event-a','event-c']}]};}} as never;const p=f.estate.grant({categories:['LOG_INSPECTION'],targetIds:[],diagnosticAssessmentIds:['assessment-abcd']},'test'),run=f.runtime.createRun('discover-estate@1.0.0',{permissionId:p.id},{type:'manual',actor:'test'});await f.runtime.tick();assert.equal(f.runtime.ledger.get(run.id)!.status,'SUCCEEDED');const s=f.estate.latest()!;assert.ok(s.entities.some(e=>e.id==='historical:a'&&e.state==='HISTORICALLY_OBSERVED'));assert.ok(!s.entities.some(e=>e.id==='historical:b'));assert.equal(s.relationships[0]?.state,'HISTORICALLY_OBSERVED');revoked=true;assert.throws(()=>f.estate.replay(s.id),/denied/);assert.equal(f.estate.projection().entities.length,0);});
test('Estate frames validate against the shared Factory envelope schema',async()=>{const f=fixture(),r=await run(f,['PASSIVE_INVENTORY']),frame=new FactoryJournal().append(estateProjection(r.snapshot));const validate=new Ajv2020({strict:false}).compile(JSON.parse(fs.readFileSync(new URL('../../docs/factory-event.schema.json',import.meta.url),'utf8')));assert.equal(validate(frame),true,JSON.stringify(validate.errors));});

test('Comparable rescans retain absent models as STALE and preserve first seen instead of implying removal',async()=>{let available=true;const endpoint=http.createServer((q,r)=>{r.setHeader('Content-Type','application/json');r.end(JSON.stringify(q.url==='/v1/models'?{data:available?[{id:'SYNTHETIC-model'}]:[]}:q.url==='/health'?{status:'ok'}:{}));});await once(endpoint.listen(0,'127.0.0.1'),'listening');try{const f=fixture([{id:'rescan',kind:'ENDPOINT',label:'SYNTHETIC rescan',locator:`http://127.0.0.1:${(endpoint.address() as AddressInfo).port}`}]);const a=await run(f,['SERVICE_ENUMERATION'],['rescan']);available=false;const b=await run(f,['SERVICE_ENUMERATION'],['rescan']);const old=a.snapshot.entities.find(e=>e.kind==='model')!,stale=b.snapshot.entities.find(e=>e.id===old.id)!;assert.equal(stale.state,'STALE');assert.equal(stale.firstSeen,old.firstSeen);assert.equal(stale.lastSeen,old.lastSeen);assert.ok(b.snapshot.diff.some(d=>d.id===old.id&&d.change==='NOT_REOBSERVED'));assert.ok(!b.snapshot.diff.some(d=>d.change==='REMOVED'||d.change==='MODEL_REMOVED'));}finally{endpoint.close();}});

// An accepted permission does not mean that an observation adapter exists.
test('Selected unsupported discovery scopes yield PARTIAL even when all observed local resources succeeded',async()=>{
 for(const category of ['REMOTE_HOST_DISCOVERY','NETWORK_RELATIONSHIP_DISCOVERY','PROCESS_INSPECTION'] as const){
  const f=fixture(),r=await run(f,['PASSIVE_INVENTORY',category]);
  assert.equal(r.run.status,'SUCCEEDED');
  assert.equal(r.snapshot.status,'PARTIAL');
  assert.ok(r.snapshot.events.some(e=>e.type==='ADAPTER_UNAVAILABLE'&&e.caption.includes(category)));
  assert.equal(r.snapshot.entities.filter(e=>e.kind==='host').length,1);
  assert.ok(!r.snapshot.entities.some(e=>e.hostId&&e.hostId!=='host:controller-local'));
  assert.equal(f.estate.projection().estate?.status,'PARTIAL');
  assert.equal(f.estate.replay(r.snapshot.id).snapshot.status,'PARTIAL');
 }
});
