import {EstateRemoteAdapter,estateControllerIdentity,estateResourceAlias,type RemoteEstateState} from './estate-remote.js';
import type {SshExecutor} from './managed-node-ssh.js';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {emptyConfig,type AgentControlConfig} from './config.js';
import type {JobRuntime} from './job-runtime.js';
import type {OwnedExecution} from './owned-process.js';
import {EnvironmentDiscoveryRuntime,type DiscoveryObservation} from './environment-discovery.js';
import type {ArchitectureDiagnostics} from './architecture-diagnostics.js';
import {ESTATE_CATEGORIES,estateHash,estateSafe,estateDiff,estateComparison,estateProjection,assertEstateEvidence,type EstateCategory,type EstateEntity,type EstateRelationship,type EstateEvidence,type EstateSnapshot,type EstateState,type EstateKind,type EstateEvent} from './estate-model.js';

export const ESTATE_WORKER='agent-control:estate-observer';
export const ESTATE_CAPABILITY='agent-control.estate.read';
const now=()=>new Date().toISOString();
const inputSchema=z.object({categories:z.array(z.enum(ESTATE_CATEGORIES)).max(10),targetIds:z.array(z.string().min(1).max(160)).max(50),diagnosticAssessmentIds:z.array(z.string().regex(/^assessment-[a-f0-9-]+$/)).max(10).default([])}).strict();
export interface EstateTarget {id:string;kind:'ENDPOINT'|'REPOSITORY'|'STORAGE'|'REMOTE_RESOURCE';label:string;locator:string;resourceId?:string;providerId?:string;modelIds?:Record<string,string>;}
export interface EstatePermission {id:string;actor:string;createdAt:string;expiresAt:string;revokedAt:string|null;categories:EstateCategory[];targetIds:string[];diagnosticAssessmentIds:string[];scopeDigest:string;remoteBindings?:Record<string,string>;}
export interface EstateOptions {root:string;config:()=>AgentControlConfig;targets?:EstateTarget[];remoteExecutor?:SshExecutor;controllerIdentity?:typeof estateControllerIdentity;diagnostics?:ArchitectureDiagnostics;environmentDiscovery?:EnvironmentDiscoveryRuntime;onEvent?:(type:string,payload:Record<string,unknown>)=>void;}

/** Authoritative evidence observer. No renderer, scheduling admission, or inference-provider coupling. */
export class EstateDiscovery {
 readonly permissions=new Map<string,EstatePermission>();
 private snapshots:EstateSnapshot[]=[];private active:EstateSnapshot|null=null;private controller:AbortController|null=null;
 private listeners=new Set<()=>void>();private restarted=true;private eventBytes=0;
 readonly targets:EstateTarget[];
 constructor(readonly options:EstateOptions){
  options.environmentDiscovery?.setScopedScanAuthorizer(id=>{try{this.assertPermission(id);return true;}catch{return false;}});
  fs.mkdirSync(options.root,{recursive:true,mode:0o700});this.targets=structuredClone(options.targets??[]);for(const resource of this.configuration().resources.filter(r=>r.transport.type==='ssh')){const id=estateResourceAlias(resource.id);this.targets.push({id,kind:'REMOTE_RESOURCE',label:`Remote host ${id.slice(-8)}`,locator:'',resourceId:resource.id});}if(new Set(this.targets.map(t=>t.id)).size!==this.targets.length)throw Error('estate_duplicate_target');
  for(const t of this.targets){if(t.kind==='REMOTE_RESOURCE'){if(t.locator!==''||!t.resourceId||t.id!==estateResourceAlias(t.resourceId))throw Error('estate_remote_target_requires_resource_binding');continue;}if(t.kind==='ENDPOINT'){const u=new URL(t.locator);if(!['http:','https:'].includes(u.protocol)||!['127.0.0.1','[::1]'].includes(u.hostname)||u.username||u.password||u.search||u.hash)throw Error('estate_endpoint_must_be_explicit_numeric_loopback');}else if(!path.isAbsolute(t.locator))throw Error('estate_target_requires_absolute_admin_path');}
  const file=path.join(options.root,'state.json');if(fs.existsSync(file)){const stored=JSON.parse(fs.readFileSync(file,'utf8'));for(const p of stored.permissions??[])this.permissions.set(p.id,p);this.snapshots=stored.snapshots??[];for(const snapshot of this.snapshots)this.verifyChain(snapshot.events);}
 }
 private configuration(){try{const config=this.options.config();if(!Array.isArray(config.resources))throw Error('invalid');return config;}catch{throw Error('estate_configuration_unavailable');}}
 private verifyChain(events:EstateEvent[]){let previous:string|null=null;for(const [index,event] of events.entries()){const {sha256,...body}=event;if(event.sequence!==index+1||event.previousHash!==previous||estateHash(body)!==sha256)throw Error('estate_event_integrity_failure');previous=sha256;}}
 catalog(){return{categories:ESTATE_CATEGORIES,targets:this.targets.map(({id,kind,label})=>({id,kind,label:estateSafe(label)})),localHost:'controller-local',boundaries:['Local endpoints require numeric loopback. Remote metadata requires a selected, authorised and identity-pinned SSH resource; no network scan.','No process arguments, environment variables, credentials, file contents, or repository history.','Logs require an existing explicit Diagnostics source grant and selected assessment.','Discovery does not register models or grant execution authority.']};}
 grant(input:unknown,actor:string){const v=inputSchema.parse(input);if(v.targetIds.some(id=>!this.targets.some(t=>t.id===id)))throw Error('estate_target_not_allowlisted');if(v.diagnosticAssessmentIds.length&&!v.categories.includes('LOG_INSPECTION'))throw Error('estate_log_permission_required');for(const id of v.diagnosticAssessmentIds)this.options.diagnostics?.assessment(id)??(()=>{throw Error('estate_diagnostics_unavailable');})();
  const remoteBindings=Object.fromEntries(this.targets.filter(t=>t.kind==='REMOTE_RESOURCE'&&v.targetIds.includes(t.id)).map(t=>[t.id,estateHash(this.configuration().resources.find(r=>r.id===t.resourceId)??null)]));
  const p:EstatePermission={...v,remoteBindings,id:`estate-permission-${randomUUID()}`,actor,createdAt:now(),expiresAt:new Date(Date.now()+3600000).toISOString(),revokedAt:null,scopeDigest:estateHash({remoteBindings,categories:[...v.categories].sort(),targets:this.targets.filter(t=>v.targetIds.includes(t.id)),assessments:v.diagnosticAssessmentIds})};this.permissions.set(p.id,p);this.audit('PERMISSION_GRANTED',{permission:p});this.persist();return structuredClone(p);}
 assertPermission(id:string,actor?:string){const p=this.permissions.get(id);if(!p||p.revokedAt||Date.parse(p.expiresAt)<=Date.now()||actor&&actor!==p.actor)throw Error('estate_permission_denied');for(const assessment of p.diagnosticAssessmentIds)this.options.diagnostics?.assessment(assessment)??(()=>{throw Error('estate_permission_denied');})();for(const [targetId,digest] of Object.entries(p.remoteBindings??{})){const target=this.targets.find(t=>t.id===targetId);if(!target||estateHash(this.configuration().resources.find(r=>r.id===target.resourceId)??null)!==digest)throw Error('estate_resource_binding_changed');}return p;}
 revoke(id:string,actor:string){const p=this.assertPermission(id,actor);p.revokedAt=now();if(this.active?.permissionId===id)this.controller?.abort();this.audit('PERMISSION_REVOKED',{permissionId:id,actor});this.persist();this.notify();return structuredClone(p);}
 subscribe(listener:()=>void){this.listeners.add(listener);return()=>this.listeners.delete(listener);}
 private notify(){for(const listener of this.listeners){try{listener();}catch{/* UI failure cannot stop evidence collection. */}}}
 private audit(type:string,payload:unknown){fs.appendFileSync(path.join(this.options.root,'audit.jsonl'),JSON.stringify(estateSafe({at:now(),type,payload}))+'\n',{mode:0o600});}
 private persist(){const file=path.join(this.options.root,'state.json');fs.writeFileSync(file+'.tmp',JSON.stringify({permissions:[...this.permissions.values()],snapshots:this.snapshots.slice(-20)}),{mode:0o600});fs.renameSync(file+'.tmp',file);}
 latest(){const s=this.active??this.snapshots.at(-1)??null;if(s)this.assertPermission(s.permissionId);return s?structuredClone(s):null;}
 history(){return this.snapshots.filter(s=>{try{this.assertPermission(s.permissionId);return true;}catch{return false;}}).map(({id,runId,startedAt,completedAt,status,diff})=>({id,runId,startedAt,completedAt,status,diff}));}
 snapshot(id:string){const s=[...this.snapshots,...(this.active?[this.active]:[])].find(s=>s.id===id);if(!s)throw Error('estate_snapshot_missing');this.assertPermission(s.permissionId);return structuredClone(s);}
 projection(query=''){try{const s=this.latest();return estateProjection(s,this.restarted||Boolean(s?.completedAt&&Date.now()-Date.parse(s.completedAt)>300000),query.slice(0,200));}catch{return estateProjection(null);}}
 replay(id:string){const s=this.snapshot(id);this.verifyChain(s.events);return{schema:'agent-control.estate-replay/v1',snapshot:{...s,events:[]},events:s.events,authority:'RECORDED_EVIDENCE_NO_PROBES',externalAnchor:'UNAVAILABLE'};}
 private event(type:string,caption:string,entity?:EstateEntity,relationship?:EstateRelationship){const s=this.active!;if(s.events.length>=50000)throw Error('estate_event_budget_exceeded');const prior=s.events.at(-1),value=estateSafe({schema:'agent-control.estate-event/v1' as const,sequence:s.events.length+1,id:`estate-event-${randomUUID()}`,at:now(),runId:s.runId,type,caption:caption.slice(0,240),...(entity?{entity}:{}),...(relationship?{relationship}:{}),previousHash:prior?.sha256??null});const event={...value,sha256:estateHash(value)};this.eventBytes+=Buffer.byteLength(JSON.stringify(event));if(this.eventBytes>32*1024*1024)throw Error('estate_event_byte_budget_exceeded');s.events.push(event);fs.appendFileSync(path.join(this.options.root,`${s.id}.jsonl`),JSON.stringify(event)+'\n',{mode:0o600});try{this.options.onEvent?.('estate.discovery_evidence',{runId:s.runId,eventId:event.id,type,caption:event.caption});}catch{/* Optional activity projection cannot abort evidence collection. */}this.notify();return event;}
 evidence(category:EstateCategory,source:string,method:string,type:EstateEvidence['type'],result:EstateEvidence['result'],facts:unknown,probe:string|null=null):EstateEvidence {const s=this.active!;return{id:`estate-evidence-${randomUUID()}`,source,method,type,at:now(),permissionId:s.permissionId,category,probe,result,digest:estateHash(estateSafe(facts)),runId:s.runId,activityRef:`run:${s.runId}`,ledgerRef:`run:${s.runId}`};}
 observe(input:{id:string;kind:EstateKind;label:string;state:EstateState;hostId?:string|null;attributes?:EstateEntity['attributes'];capabilities?:EstateEntity['capabilities'];factoryId?:string|null;lastSeen?:string;lastSuccessfulDiscovery?:string|null},e:EstateEvidence){
  assertEstateEvidence(input.state,e);const s=this.active!;if(s.entities.length>=10000&&!s.entities.some(v=>v.id===input.id))throw Error('estate_entity_budget_exceeded');const p=s.entities.find(v=>v.id===input.id);let state=p?.state==='CONFLICTED'?'CONFLICTED' as EstateState:input.state;
  if(p&&['VERIFIED','CAPABILITY_VERIFIED'].includes(p.state)&&['VERIFIED','CAPABILITY_VERIFIED'].includes(state)&&p.attributes.identityDigest&&input.attributes?.identityDigest&&p.attributes.identityDigest!==input.attributes.identityDigest)state='CONFLICTED';
  const value=estateSafe({...input,state,hostId:input.hostId??p?.hostId??null,attributes:{...p?.attributes,...input.attributes},capabilities:{...p?.capabilities,...input.capabilities},factoryId:input.factoryId??p?.factoryId??null,firstSeen:p?.firstSeen??(this.snapshots.at(-1)?.scopeDigest===s.scopeDigest?this.snapshots.at(-1)?.entities.find(v=>v.id===input.id)?.firstSeen:undefined)??e.at,lastSeen:input.lastSeen??e.at,evidence:[...(p?.evidence??[]),e]});if(p)s.entities[s.entities.indexOf(p)]=value;else s.entities.push(value);this.event(`${input.kind.toUpperCase()}_${state}`,`${input.label} · ${state.replaceAll('_',' ')}`,value);return value;
 }
 relate(from:string,to:string,kind:string,layer:EstateRelationship['layer'],state:EstateState,basis:EstateRelationship['basis'],e:EstateEvidence){assertEstateEvidence(state,e);const s=this.active!;if(!s.entities.some(v=>v.id===from)||!s.entities.some(v=>v.id===to))throw Error('estate_relationship_endpoint_missing');const id=`relationship:${estateHash([from,to,kind]).slice(0,24)}`,p=s.relationships.find(v=>v.id===id);const value:EstateRelationship=estateSafe({id,from,to,kind,layer,state,basis,firstSeen:p?.firstSeen??(this.snapshots.at(-1)?.scopeDigest===s.scopeDigest?this.snapshots.at(-1)?.relationships.find(r=>r.id===id)?.firstSeen:undefined)??e.at,lastSeen:e.at,evidence:[...(p?.evidence??[]),e]});if(p)s.relationships[s.relationships.indexOf(p)]=value;else s.relationships.push(value);this.event('RELATIONSHIP_EVIDENCED',`${kind} · ${state} · ${basis}`,undefined,value);return value;}
 async discover(permissionId:string,runId:string,actor:string,signal:AbortSignal,owned:OwnedExecution|undefined,workers:()=>Array<{id:string;health:string;capabilities:string[]}>,assertActive:()=>void){
  const permission=this.assertPermission(permissionId,actor);if(this.active)throw Error('estate_discovery_already_running');this.restarted=false;this.eventBytes=0;this.controller=new AbortController();const combined=AbortSignal.any([signal,this.controller.signal,AbortSignal.timeout(120000)]);const check=()=>{combined.throwIfAborted();assertActive();this.assertPermission(permissionId,actor);};const previous=this.snapshots.at(-1)??null;
  this.active={schema:'agent-control.estate/v1',id:`estate-${randomUUID()}`,runId,permissionId,scopeDigest:permission.scopeDigest,startedAt:now(),completedAt:null,status:'RUNNING',entities:[],relationships:[],events:[],diff:[],coverage:['Unknown and unselected resources remain unknown. No network-range or process enumeration is performed. Remote coverage is bounded host/CPU/memory and optional GPU metadata. Android identity is SSH-installation scoped; physical identity is unavailable. No service or log discovery.','Filesystem metadata and registry records do not prove running services or model capabilities.','Capability passes apply only to the named probe. Execution admission remains governed by the existing registry.'],scanId:null};
  this.event('DISCOVERY_STARTED','Discovery started · no assumed topology');
  const ev=(category:EstateCategory,source:string,method:string,type:EstateEvidence['type'],facts:unknown,result:EstateEvidence['result']='OBSERVATION',probe:string|null=null)=>this.evidence(category,source,method,type,result,facts,probe);
  const allowed=(category:EstateCategory)=>permission.categories.includes(category);
  const host='host:controller-local';
  const command=async(executable:string,args:string[])=>{check();if(!owned)return null;try{const r=await owned.runProcess({command:executable,args,maxOutputBytes:64*1024},AbortSignal.any([combined,AbortSignal.timeout(8000)]));check();return r.exitCode===0?r.stdout:null;}catch{check();return null;}};
  try{
   const adapter={id:'permission-governed-estate/v1',discover:async():Promise<DiscoveryObservation[]>=>{
    if(allowed('REMOTE_HOST_DISCOVERY')&&!this.targets.some(t=>t.kind==='REMOTE_RESOURCE'&&permission.targetIds.includes(t.id)))this.event('ADAPTER_UNAVAILABLE','REMOTE_HOST_DISCOVERY · no selected governed resource binding');
    for(const category of ['PROCESS_INSPECTION','NETWORK_RELATIONSHIP_DISCOVERY'] as const)if(allowed(category))this.event('ADAPTER_UNAVAILABLE',`${category} · UNKNOWN, no enabled adapter`);
    for(const category of ESTATE_CATEGORIES)if(!allowed(category))this.event('PERMISSION_BLOCKED',`${category.replaceAll('_',' ')} · BLOCKED by scope`);
    if(allowed('PASSIVE_INVENTORY')){
     check();this.observe({id:host,kind:'host',label:'Controller host',state:'OBSERVED'},ev('PASSIVE_INVENTORY','local OS','Node os API','OS_INVENTORY',{platform:os.platform()}));
     const facts={platform:os.platform(),release:os.release(),arch:os.arch(),identityDigest:estateHash([os.hostname(),os.platform(),os.arch()])};this.observe({id:host,kind:'host',label:`Controller · ${os.platform()}`,state:'IDENTIFIED',attributes:facts},ev('PASSIVE_INVENTORY','local OS','OS identity metadata','OS_INVENTORY',facts));
     const kernel=await command('uname',['-s','-m']);const pass=Boolean(kernel&&kernel.toLowerCase().includes(os.platform()==='linux'?'linux':os.platform())&&kernel.includes(os.arch()==='x64'?'x86_64':os.arch()==='arm64'?'aarch64':os.arch()));this.observe({id:host,kind:'host',label:`Controller · ${os.platform()}`,state:pass?'VERIFIED':'IDENTIFIED',attributes:facts,lastSuccessfulDiscovery:pass?now():null},ev('PASSIVE_INVENTORY','local kernel','Compare independent uname response with OS API','OS_INVENTORY',facts,pass?'PASS':'UNKNOWN',pass?'uname identity consistency':null));
     const cpu={architecture:os.arch(),logicalCpus:os.cpus().length,model:os.cpus()[0]?.model??'UNKNOWN',memoryBytes:os.totalmem()};this.observe({id:'cpu:controller-local',kind:'cpu',label:cpu.model,state:'IDENTIFIED',hostId:host,attributes:cpu},ev('PASSIVE_INVENTORY','local OS','CPU and memory inventory','OS_INVENTORY',cpu));this.relate(host,'cpu:controller-local','reports CPU','PHYSICAL','OBSERVED','OBSERVED',ev('PASSIVE_INVENTORY','local OS','OS CPU inventory','OS_INVENTORY',cpu));
     const gpu=await command('nvidia-smi',['--query-gpu=index,name,memory.total,driver_version','--format=csv,noheader,nounits']);if(gpu){for(const row of gpu.trim().split('\n').slice(0,32)){const [index,name,memory,driver]=row.split(',').map(v=>v.trim());const id=`gpu:controller-local:${index}`,facts={index:index??'',model:name??'UNKNOWN',memoryMiB:Number(memory)||null,driver:driver??'UNKNOWN'};this.observe({id,kind:'gpu',label:name??'GPU',state:'IDENTIFIED',hostId:host,attributes:facts},ev('PASSIVE_INVENTORY','GPU driver','nvidia-smi bounded inventory','OS_INVENTORY',facts));this.relate(host,id,'reports accelerator','PHYSICAL','OBSERVED','OBSERVED',ev('PASSIVE_INVENTORY','GPU driver','nvidia-smi inventory','OS_INVENTORY',facts));}}else this.event('INVENTORY_UNKNOWN','GPU inventory unavailable · UNKNOWN, not zero GPUs');
     for(const w of workers().slice(0,500)){const id=`worker:${w.id}`,facts={health:w.health,capabilities:w.capabilities.join(', ')};this.observe({id,kind:'worker',label:w.id,state:'OBSERVED',hostId:w.id===ESTATE_WORKER?host:null,attributes:facts,factoryId:id},ev('PASSIVE_INVENTORY','Agent Control worker registry','Registered worker metadata','REGISTRY',facts));if(w.id===ESTATE_WORKER)this.relate(id,host,'executes controller-local discovery','LOGICAL','VERIFIED','VERIFIED',ev('PASSIVE_INVENTORY','native Job execution','Current controller action executing on local OS','REGISTRY',{runId,workerId:w.id},'PASS','native controller execution receipt'));}
     if(allowed('CAPABILITY_PROBES')){check();const good=os.cpus().length>0&&os.totalmem()>0;this.observe({id:`worker:${ESTATE_WORKER}`,kind:'worker',label:ESTATE_WORKER,state:good?'CAPABILITY_VERIFIED':'OBSERVED',capabilities:{'local-system-observation':good?'PASS':'FAIL'},factoryId:`worker:${ESTATE_WORKER}`},ev('CAPABILITY_PROBES','native local worker','Bounded OS observation schema probe','CAPABILITY_PROBE',{cpuCount:os.cpus().length,memory:os.totalmem()},good?'PASS':'FAIL','local-system-observation/v1'));}
    }else{this.observe({id:host,kind:'host',label:'Controller inventory',state:'BLOCKED'},ev('PASSIVE_INVENTORY','permission scope','Passive inventory not granted','PERMISSION',{},'DENIED'));}
    if(allowed('SERVICE_ENUMERATION')){const services=await command('systemctl',['list-units','--type=service','--state=running','--no-pager','--no-legend','--plain']);if(services){for(const line of services.split('\n').filter(Boolean).slice(0,100)){const name=line.trim().split(/\s+/)[0]!;if(!/^[a-zA-Z0-9_.@-]+\.service$/.test(name))continue;const id=`service:${estateHash(name).slice(0,20)}`;this.observe({id,kind:'service',label:name,state:'OBSERVED',hostId:host},ev('SERVICE_ENUMERATION','systemd','Running unit name only; no arguments or environment','OS_INVENTORY',{name}));this.relate(host,id,'reports service','LOGICAL','OBSERVED','OBSERVED',ev('SERVICE_ENUMERATION','systemd','Unit inventory','OS_INVENTORY',{name}));}}else this.event('SERVICE_UNKNOWN','Service inventory unavailable · UNKNOWN');}
    await this.discoverRemote(permission,combined,owned,previous,check);
    for(const target of this.targets.filter(t=>t.kind!=='REMOTE_RESOURCE'&&permission.targetIds.includes(t.id))){check();const category:EstateCategory=target.kind==='ENDPOINT'?'SERVICE_ENUMERATION':target.kind==='REPOSITORY'?'REPOSITORY_INSPECTION':'STORAGE_INSPECTION';const entityId=`${target.kind.toLowerCase()}:${target.id}`,kind:EstateKind=target.kind==='ENDPOINT'?'endpoint':target.kind==='REPOSITORY'?'repository':'storage';
     if(allowed('CONFIGURATION_READ'))this.observe({id:entityId,kind,label:target.label,state:'EXPECTED'},ev('CONFIGURATION_READ','selected target configuration','Admin allowlist; not an observation','CONFIGURATION',{targetId:target.id}));
     if(!allowed(category)){this.observe({id:entityId,kind,label:target.label,state:'BLOCKED'},ev(category,'permission scope','Selected target category not granted','PERMISSION',{targetId:target.id},'DENIED'));continue;}
     if(target.kind==='ENDPOINT'){
      let models:any;try{models=await this.endpoint(target,'/v1/models',combined);check();}catch{check();this.observe({id:entityId,kind,label:target.label,state:'UNREACHABLE'},ev(category,'selected loopback endpoint','Bounded HTTP model inventory failed','SERVICE_RESPONSE',{targetId:target.id},'FAIL','GET /v1/models'));continue;}
      const rows=Array.isArray(models?.data)?models.data.slice(0,100):[];const valid=rows.length>0&&rows.every((v:any)=>typeof v.id==='string'&&v.id.length<=512);this.observe({id:entityId,kind,label:target.label,state:valid?'IDENTIFIED':'UNKNOWN',hostId:host,attributes:{modelCount:rows.length}},ev(category,'selected loopback endpoint','GET /v1/models schema inspection','SERVICE_RESPONSE',{modelCount:rows.length}));
      try{const health=await this.endpoint(target,'/health',combined);check();const good=health?.status==='ok';this.observe({id:entityId,kind,label:target.label,state:good?'VERIFIED':'IDENTIFIED'},ev(category,'selected loopback endpoint','Independent health response','SERVICE_RESPONSE',{status:good?'ok':'UNKNOWN'},good?'PASS':'UNKNOWN',good?'GET /health + model inventory':null));}catch{check();this.event('HEALTH_UNKNOWN',`${target.label} · health probe unavailable`);}
      try{const props=await this.endpoint(target,'/props',combined);check();if(props&&typeof props.default_generation_settings==='object'&&typeof props.model_path==='string'){const id=`runtime:${target.id}`,facts={apiProfile:'llama.cpp-compatible',version:'UNKNOWN',modelIdentityDigest:estateHash(props.model_path)};this.observe({id,kind:'runtime',label:'Model runtime · metadata identified',state:'IDENTIFIED',hostId:host,attributes:facts},ev(category,'selected runtime metadata','GET /props profile; executable version not established','SERVICE_RESPONSE',facts));this.relate(id,entityId,'exposes model API','LOGICAL','OBSERVED','OBSERVED',ev(category,'runtime metadata response','Shared explicitly selected endpoint','SERVICE_RESPONSE',facts));}}catch{check();this.event('RUNTIME_IDENTITY_UNKNOWN','Runtime-specific identity metadata unavailable · UNKNOWN');}
      this.relate(host,entityId,'local loopback endpoint','LOGICAL','OBSERVED','OBSERVED',ev(category,'numeric loopback transport','Response received from selected local endpoint','SERVICE_RESPONSE',{targetId:target.id}));
      if(valid)for(const row of rows){const configured=target.modelIds?.[row.id];const modelId=configured&&target.providerId?`model:${encodeURIComponent(target.providerId)}:${encodeURIComponent(configured)}`:`model:observed:${estateHash([target.id,row.id]).slice(0,24)}`;const label=path.basename(row.id.replaceAll('\\','/'));this.observe({id:modelId,kind:'model',label,state:'IDENTIFIED',hostId:host,attributes:{modelId:configured??label,identityDigest:estateHash(row.id),admission:'UNCHANGED'},factoryId:configured?modelId:null},ev(category,'model inventory response','Provider-reported identifier; weights not independently hashed','SERVICE_RESPONSE',{identityDigest:estateHash(row.id)}));this.relate(entityId,modelId,'lists model','LOGICAL','OBSERVED','OBSERVED',ev(category,'model inventory response','GET /v1/models membership','SERVICE_RESPONSE',{modelIdentity:estateHash(row.id)}));
       if(allowed('CAPABILITY_PROBES')){let pass=false;try{const output=await this.endpoint(target,'/v1/chat/completions',combined,{model:row.id,messages:[{role:'user',content:'Reply with exactly ESTATE_OK and no other text.'}],temperature:0,max_tokens:16,stream:false});check();pass=output?.choices?.[0]?.message?.content?.trim()==='ESTATE_OK';}catch{check();}this.observe({id:modelId,kind:'model',label,state:pass?'CAPABILITY_VERIFIED':'IDENTIFIED',capabilities:{'literal-text-response':pass?'PASS':'FAIL'}},ev('CAPABILITY_PROBES','selected local model','Exact literal response; no tools, no qualification promotion','CAPABILITY_PROBE',{pass},pass?'PASS':'FAIL','literal-text-response/v1'));}
      }
     }else{try{const stat=await fs.promises.lstat(target.locator);check();if(stat.isSymbolicLink())throw Error('symlink');const facts:EstateEntity['attributes']={directory:stat.isDirectory(),identityDigest:estateHash([stat.dev,stat.ino])};if(target.kind==='REPOSITORY'){const rev=await command('git',['-C',target.locator,'rev-parse','--verify','HEAD']);facts.revision=rev?.trim().match(/^[a-f0-9]{40,64}$/)?.[0]??null;}else{const space=await fs.promises.statfs(target.locator);check();facts.capacityBytes=space.blocks*space.bsize;facts.availableBytes=space.bavail*space.bsize;}this.observe({id:entityId,kind,label:target.label,state:'IDENTIFIED',hostId:host,attributes:facts},ev(category,'selected local metadata',target.kind==='REPOSITORY'?'Directory identity and git revision only':'Filesystem capacity metadata only',target.kind==='REPOSITORY'?'REPOSITORY_METADATA':'FILESYSTEM_METADATA',facts));this.relate(host,entityId,'local metadata source','PHYSICAL','OBSERVED','OBSERVED',ev(category,'local filesystem','Selected metadata accessible', 'FILESYSTEM_METADATA',facts));}catch{check();this.observe({id:entityId,kind,label:target.label,state:'UNKNOWN'},ev(category,'selected local metadata','Unavailable or symlink refused','FILESYSTEM_METADATA',{},'UNKNOWN'));}}
    }
    if(allowed('LOG_INSPECTION'))for(const id of permission.diagnosticAssessmentIds){check();const assessment=this.options.diagnostics!.assessment(id);const observed=new Set(assessment.events.filter(e=>e.timestamp&&e.componentId).map(e=>e.componentId));for(const component of assessment.architecture.components.filter(c=>observed.has(c.id)).slice(0,100)){const events=assessment.events.filter(e=>e.componentId===component.id&&e.timestamp);const evidence=ev('LOG_INSPECTION',`diagnostics:${id}`,'Explicitly granted timestamped historical log events; not current verification','HISTORICAL_LOG',{assessmentId:id,sha256:assessment.sha256,eventIds:events.map(e=>e.id)});this.observe({id:`historical:${component.id}`,kind:'unknown',label:component.label,state:'HISTORICALLY_OBSERVED',attributes:{assessmentId:id,historicalLastSeen:events.at(-1)?.timestamp??null}},evidence);}for(const finding of assessment.findings.filter(f=>f.status==='CORRELATED')){const ids=finding.componentIds.filter(id=>this.active!.entities.some(e=>e.id===`historical:${id}`));if(ids.length>1)this.relate(`historical:${ids[0]}`,`historical:${ids[1]}`,'historical correlated events','LOGICAL','HISTORICALLY_OBSERVED','HISTORICAL',ev('LOG_INSPECTION',`diagnostics:${id}`,'Historical correlation only; no current dependency or causation established','HISTORICAL_LOG',{findingId:finding.id,evidenceRefs:finding.evidenceRefs}));}}
    check();return this.active!.entities.map(e=>({id:e.id,kind:({host:'MACHINE',cpu:'MACHINE',gpu:'GPU',runtime:'RUNTIME',endpoint:'ENDPOINT',model:'MODEL',worker:'AGENT',skill:'SKILL'} as Record<string,string>)[e.kind]??'TOOL',label:e.label,nodeId:e.hostId??'controller-local',computeClass:'SERVER_LOCAL',health:e.state==='UNREACHABLE'?'OFFLINE':'NEEDS_QUALIFICATION',lifecycle:'DISCOVERED',attributes:{...e.attributes,estateState:e.state},provenance:e.evidence.map(v=>({adapter:'permission-governed-estate/v1',method:v.method,observedAt:v.at,authority:v.type==='CONFIGURATION'?'CONFIGURED':v.type==='INFERENCE'?'DERIVED':'AUTHORITATIVE'}))} as DiscoveryObservation));
   }};
   const discovery=this.options.environmentDiscovery??new EnvironmentDiscoveryRuntime({file:path.join(this.options.root,'inventory.json'),config:emptyConfig,configurationRevision:()=>permission.scopeDigest,adapters:[adapter],environment:{}});discovery.setScopedScanAuthorizer(id=>{try{this.assertPermission(id);return true;}catch{return false;}});const scan=await discovery.discoverScoped({scopePermissionId:permission.id,mode:'FULL_DISCOVERY',testing:'SKIP_TESTING',includeRemote:false},[adapter]);check();this.active.scanId=scan.id;if(scan.failures.length)throw Error('estate_adapter_failed');
   this.retainStale(previous);
   this.active.status=this.active.events.some(e=>e.type==='ADAPTER_UNAVAILABLE')||this.active.entities.some(e=>['UNKNOWN','UNREACHABLE','CONFLICTED','BLOCKED','STALE','UNAUTHORISED','TIMED_OUT','INVALID_RESPONSE','CANCELLED','DEGRADED'].includes(e.state))?'PARTIAL':'COMPLETED';this.active.completedAt=now();this.active.diff=estateDiff(previous,this.active);this.active.comparison=estateComparison(previous,this.active);this.event('DISCOVERY_COMPLETED',`Discovery ${this.active.status} · ${this.active.entities.length} entities · ${this.active.relationships.length} evidenced relationships`);const result=structuredClone(this.active);this.snapshots.push(result);this.persist();return result;
  }catch(error){this.active.status='FAILED';this.active.completedAt=now();try{this.retainStale(previous);this.active.diff=estateDiff(previous,this.active);this.active.comparison=estateComparison(previous,this.active);this.event('DISCOVERY_STOPPED','Discovery stopped · permission, cancellation or probe failure');}catch{/* Budget remains a hard limit. */}this.snapshots.push(structuredClone(this.active));this.persist();throw error;}finally{this.active=null;this.controller=null;this.notify();}
 }
 private retainStale(previous:EstateSnapshot|null){
  const active=this.active;if(!active)return;
   if(previous?.scopeDigest===active.scopeDigest){for(const old of previous.entities){if(active.entities.some(e=>e.id===old.id))continue;if(active.entities.length>=10000){active.coverage.push('Stale resource retention reached the entity limit; consult prior snapshots.');break;}const stale:EstateEntity={...structuredClone(old),state:'STALE',capabilities:Object.fromEntries(Object.keys(old.capabilities).map(k=>[k,'UNKNOWN' as const]))};active.entities.push(stale);this.event('NOT_REOBSERVED',`${old.label} · not reobserved in this scan; retained STALE, removal unproven`,stale);}}
   if(previous?.scopeDigest===active.scopeDigest)for(const old of previous.relationships){if(active.relationships.some(r=>r.id===old.id)||!active.entities.some(e=>e.id===old.from)||!active.entities.some(e=>e.id===old.to))continue;const stale:EstateRelationship={...structuredClone(old),state:'STALE',basis:'STALE'};active.relationships.push(stale);this.event('RELATIONSHIP_NOT_REOBSERVED','Relationship retained STALE; removal unproven',undefined,stale);}
 }
 private async discoverRemote(permission:EstatePermission,signal:AbortSignal,owned:OwnedExecution|undefined,previous:EstateSnapshot|null,check:()=>void){
  const selected=this.targets.filter(t=>t.kind==='REMOTE_RESOURCE'&&permission.targetIds.includes(t.id));
  if(!selected.length)return;
  const comparable=previous?.scopeDigest===permission.scopeDigest?previous:null;
  const adapter=new EstateRemoteAdapter(()=>this.configuration(),this.options.remoteExecutor);
  const controllerIdentity=owned&&permission.categories.includes('REMOTE_HOST_DISCOVERY')?await(this.options.controllerIdentity??estateControllerIdentity)(owned,signal):null;
  const controller=this.active!.entities.find(e=>e.id==='host:controller-local');
  if(controllerIdentity&&controller&&permission.categories.includes('PASSIVE_INVENTORY')&&controller.state==='VERIFIED')this.observe({id:controller.id,kind:'host',label:controller.label,state:'VERIFIED',attributes:{physicalIdentityDigest:controllerIdentity},lastSuccessfulDiscovery:controller.lastSuccessfulDiscovery},this.evidence('PASSIVE_INVENTORY','local native collector','Physical machine identity digest from metadata utility','OS_INVENTORY','PASS',{physicalIdentityDigest:controllerIdentity},'native-controller-machine-identity/v1'));
  for(const target of selected){
   check();const alias=target.id,hostId=`host:${alias}`,old=comparable?.entities.find(e=>e.id===hostId);
   const evidence=(method:string,result:EstateEvidence['result'],facts:unknown,probe:string|null=null,type:EstateEvidence['type']='REGISTRY')=>this.evidence('REMOTE_HOST_DISCOVERY',alias,method,type,result,facts,probe);
   const failed=(state:EstateState,reason:string)=>this.observe({id:hostId,kind:'host',label:target.label,state,attributes:{...old?.attributes,execution:'REMOTE',resourceAlias:alias,reason,retryPolicy:'ONE_ATTEMPT_NO_AUTOMATIC_RETRY'},lastSeen:old?.lastSeen,lastSuccessfulDiscovery:old?.lastSuccessfulDiscovery??null},evidence(reason,state==='BLOCKED'?'DENIED':'FAIL',{resourceAlias:alias,reason}));
   if(!permission.categories.includes('REMOTE_HOST_DISCOVERY')){failed('BLOCKED','REMOTE_HOST_DISCOVERY_NOT_GRANTED');continue;}
   if(!owned){failed('UNAUTHORISED','NATIVE_EXECUTION_AUTHORITY_REQUIRED');continue;}
   const result=await adapter.discover(target.resourceId!,{signal,ownedExecution:owned,controllerIdentitySha256:controllerIdentity,onState:(state:RemoteEstateState,reason:string)=>{
    if(state==='DISCOVERED'||state==='CONNECTING')this.observe({id:hostId,kind:'host',label:target.label,state,attributes:{execution:'REMOTE',resourceAlias:alias,retryPolicy:'ONE_ATTEMPT_NO_AUTOMATIC_RETRY'},lastSeen:old?.lastSeen,lastSuccessfulDiscovery:old?.lastSuccessfulDiscovery??null},evidence(reason,'OBSERVATION',{resourceAlias:alias}));
    this.event(`REMOTE_${state}`,`${target.label} · ${state} · ${reason}`);
   }});
   if(!('envelope' in result)){failed(result.state,result.reason);check();continue;}
   check();const envelope=result.envelope;
   const facts={execution:'REMOTE',resourceAlias:alias,identityDigest:envelope.host.identitySha256,platform:envelope.host.platform,identityScope:envelope.host.identityScope??'SYSTEMD_MACHINE_ID',deviceModel:envelope.deviceModel??null,osVersion:envelope.osVersion??null,architecture:envelope.host.architecture,cpuCount:envelope.cpuCount,memoryBytes:envelope.memoryBytes,cpuModel:envelope.cpuModel??null,gpuInventoryStatus:envelope.gpuInventory?.status??'UNAVAILABLE',gpuInventorySource:envelope.host.platform==='android'?'UNAVAILABLE':envelope.gpuInventory?.source??'NVIDIA',coverage:'HOST_CPU_MEMORY_OPTIONAL_GPU_METADATA',retryPolicy:'ONE_ATTEMPT_NO_AUTOMATIC_RETRY'};
   const proof=()=>evidence('Pinned physical identity, request nonce, resource binding and schema validated','PASS',envelope,'native-ssh-estate-metadata/v1','OS_INVENTORY');
   if(old&&['UNREACHABLE','TIMED_OUT','INVALID_RESPONSE','UNAUTHORISED','STALE','CANCELLED'].includes(old.state))this.observe({id:hostId,kind:'host',label:target.label,state:'RECOVERED',attributes:facts,lastSuccessfulDiscovery:envelope.observedAt},proof());
   this.observe({id:hostId,kind:'host',label:target.label,state:result.state,attributes:facts,lastSuccessfulDiscovery:envelope.observedAt},proof());
   if(envelope.cpuCount!==null){const cpuId=`cpu:${alias}`;this.observe({id:cpuId,kind:'cpu',label:envelope.cpuModel??`Remote CPU · ${envelope.host.architecture}`,state:'VERIFIED',hostId,attributes:{logicalCpus:envelope.cpuCount,architecture:envelope.host.architecture,model:envelope.cpuModel??'UNKNOWN',memoryBytes:envelope.memoryBytes},lastSuccessfulDiscovery:envelope.observedAt},proof());this.relate(hostId,cpuId,'reports CPU','PHYSICAL','VERIFIED','VERIFIED',proof());}
   if(envelope.gpuInventory?.status==='OBSERVED')for(const gpu of envelope.gpuInventory.devices){const gpuId=`gpu:${alias}:${gpu.index}`;this.observe({id:gpuId,kind:'gpu',label:gpu.model,state:'IDENTIFIED',hostId,attributes:{...gpu,inventorySource:envelope.gpuInventory?.source??'NVIDIA'},lastSuccessfulDiscovery:envelope.observedAt},proof());this.relate(hostId,gpuId,'reports accelerator','PHYSICAL','VERIFIED','VERIFIED',proof());}
   else this.event('INVENTORY_UNKNOWN',`${target.label} · GPU inventory unavailable · UNKNOWN, not zero GPUs`);
   const workerId=`worker:estate:${alias}`;this.observe({id:workerId,kind:'worker',label:'Native SSH metadata collector',state:'VERIFIED',hostId,attributes:{execution:'REMOTE',lifetime:'PER_DISCOVERY_JOB',admission:'NO_GENERAL_EXECUTION_AUTHORITY'},lastSuccessfulDiscovery:envelope.observedAt},proof());this.relate(workerId,hostId,'executes read-only metadata collector','LOGICAL','VERIFIED','VERIFIED',proof());
   const local=this.active!.entities.find(e=>e.id==='host:controller-local');
   if(local&&['VERIFIED','CAPABILITY_VERIFIED'].includes(local.state)){
    this.relate(local.id,hostId,'declared governed discovery resource','LOGICAL','OBSERVED','DECLARED',evidence('Approved resource membership','OBSERVATION',{resourceAlias:alias},null,'CONFIGURATION'));
    this.relate(local.id,hostId,'executes remote metadata discovery','LOGICAL','VERIFIED','VERIFIED',proof());
   }
  }
 }
 private async endpoint(target:EstateTarget,suffix:string,signal:AbortSignal,body?:unknown){const response=await fetch(new URL(suffix,target.locator),{method:body?'POST':'GET',redirect:'error',signal:AbortSignal.any([signal,AbortSignal.timeout(20000)]),headers:{accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok||!response.body){await response.body?.cancel();throw Error('estate_endpoint_unavailable');}const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;try{while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>128*1024)throw Error('estate_response_too_large');chunks.push(r.value);}}finally{await reader.cancel();}return JSON.parse(Buffer.concat(chunks).toString('utf8'));}
}

export function registerEstateDiscovery(runtime:JobRuntime,estate:EstateDiscovery){
 runtime.workers.registerControllerInternal({id:ESTATE_WORKER,capabilities:[ESTATE_CAPABILITY],health:'healthy',capacity:1,active:0,labels:{origin:'agent-control-built-in',scope:'permission-governed-controller-local-read-only'},observedAt:now()});
 const action='discovery.estate@1.0.0';runtime.actions.registerReadOnly(action,async c=>{const s=await estate.discover(String(c.parameters.permissionId??''),c.run.id,c.run.trigger.actor,c.signal,c.ownedExecution,()=>runtime.workers.list(),()=>c.execution?.assertActive());return{artifacts:[{name:'estate-receipt',value:{snapshotId:s.id,permissionId:s.permissionId,eventChainHead:s.events.at(-1)?.sha256,entities:s.entities.length,relationships:s.relationships.length,scanId:s.scanId},type:'application/json',schema:'agent-control.estate-receipt/v1',version:'1'}],verification:['estate-evidence-recorded'],evidence:[`estate:${s.id}`]};});runtime.catalog.knownActions?.add(action);
 runtime.catalog.addJob({apiVersion:'agent-control/v1',kind:'Job',metadata:{id:'discover-estate',name:'Discover estate',version:'1.0.0',description:'Observe explicitly scoped resources and preserve progressive evidence. No admission changes.'},spec:{priority:'low',concurrency:'queue',parameters:{permissionId:{type:'string',required:true}},steps:[{id:'discover',action,requires:[ESTATE_CAPABILITY],verification:['estate-evidence-recorded'],outputs:[{name:'estate-receipt',type:'application/json',schema:'agent-control.estate-receipt/v1',version:'1'}]}]}});
 const consume='estate.system-observation@1.0.0',verify='estate.verify-observation@1.0.0';
 runtime.actions.registerReadOnly(consume,async c=>{const s=estate.snapshot(String(c.parameters.snapshotId??''));estate.assertPermission(s.permissionId,c.run.trigger.actor);const host=s.entities.find(e=>e.id==='host:controller-local'),worker=s.entities.find(e=>e.id===`worker:${ESTATE_WORKER}`);if(!host||!['VERIFIED','CAPABILITY_VERIFIED'].includes(host.state)||worker?.capabilities['local-system-observation']!=='PASS')throw Error('estate_resource_not_verified');if(host.attributes.identityDigest!==estateHash([os.hostname(),os.platform(),os.arch()]))throw Error('estate_host_identity_changed');const facts={hostId:host.id,workerId:worker.id,snapshotId:s.id,cpuCount:os.cpus().length,memoryBytes:os.totalmem(),platform:os.platform(),observedAt:now()};return{artifacts:[{name:'estate-system-observation',value:facts,type:'application/json',schema:'agent-control.estate-system-observation/v1',version:'1'}],verification:['estate-resource-observed'],evidence:[`estate:${s.id}:${host.id}`]};});
 runtime.actions.registerReadOnly(verify,async c=>{const input=c.inputArtifacts.find(a=>a.name==='estate-system-observation');if(!input)throw Error('estate_artifact_missing');const v=c.readArtifact(input.id) as any;if(!v||v.hostId!=='host:controller-local'||v.workerId!==`worker:${ESTATE_WORKER}`||!Number.isFinite(Date.parse(v.observedAt))||v.cpuCount<=0||v.memoryBytes<=0)throw Error('estate_observation_invalid');return{artifacts:[{name:'estate-verification',value:{status:'PASS',inputArtifactId:input.id,inputSha256:input.sha256,checks:['artifact integrity','same discovered resource IDs','OS observation schema'],authority:'DETERMINISTIC_ARTIFACT_VERIFICATION'},type:'application/json',schema:'agent-control.estate-verification/v1',version:'1'}],verification:['estate-observation-verified'],evidence:[`artifact:${input.id}:${input.sha256}`]};});runtime.catalog.knownActions?.add(consume);runtime.catalog.knownActions?.add(verify);
 runtime.catalog.addJob({apiVersion:'agent-control/v1',kind:'Job',metadata:{id:'estate-system-observation',name:'Observe discovered host',version:'1.0.0',description:'Use the observed controller worker and independently validate a real system observation artifact.'},spec:{priority:'normal',concurrency:'queue',parameters:{snapshotId:{type:'string',required:true}},steps:[{id:'observe',action:consume,requires:[ESTATE_CAPABILITY],verification:['estate-resource-observed'],outputs:[{name:'estate-system-observation',type:'application/json',schema:'agent-control.estate-system-observation/v1',version:'1'}]},{id:'verify',action:verify,requires:[ESTATE_CAPABILITY],dependsOn:['observe'],inputs:{observation:'observe.estate-system-observation'},verification:['estate-observation-verified'],outputs:[{name:'estate-verification',type:'application/json',schema:'agent-control.estate-verification/v1',version:'1'}]}]}});
}
