import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Ajv2020} from 'ajv/dist/2020.js';
import {once,EventEmitter} from 'node:events';
import type {IncomingMessage,ServerResponse} from 'node:http';
import type {AddressInfo} from 'node:net';
import {projectFactory,FactoryJournal,type FactorySource} from './factory-view.js';
import {FactoryStream} from './factory-stream.js';
import {createInvocationObservation} from './harness-efficiency.js';
import {createParcelContext} from './parcel-context.js';
import type {RunRecord} from './job-types.js';
import type {WorkParcel} from './work-parcels.js';
import {AgentControlService} from './application-service.js';
import {PtyRegistry} from './pty.js';
import {startWebDashboard} from './web-server.js';

const at='2026-09-21T10:00:00.000Z';
const source=(changes:Partial<FactorySource>={}):FactorySource=>({observedAt:at,lanes:[],boards:[],runs:[],workers:[],models:[],invocations:[],artifacts:[],parcels:[],kills:[],skills:[],skillRouting:[],events:[],...changes});
const run=(changes:Partial<RunRecord>={}):RunRecord=>({id:'run-1',jobId:'review',jobVersion:'1',trigger:{type:'manual',actor:'test'},requestedAt:at,status:'RUNNING',priority:'normal',concurrency:'allow',parameters:{},steps:[{id:'execute',action:'read@1',status:'RUNNING',dependsOn:[],capabilityRequest:{requires:[]} as never,resources:[],attempts:[{attempt:1,startedAt:at,workerId:'worker-a'}],artifactIds:[],verification:{required:['content'],passed:[],failed:[]}}],artifacts:[],errors:[],effectiveJob:{apiVersion:'agent-control/v1',kind:'Job',metadata:{id:'review',name:'Review documentation',version:'1'},spec:{priority:'normal',concurrency:'allow',steps:[]}},selectedWorkers:['worker-a'],approvals:[],provenance:[],...changes});
const invocation=(changes={})=>({...createInvocationObservation({jobId:'review',runId:'run-1',stepId:'execute',taskId:'t',laneId:'7',model:'model-x',provider:'provider-a',harnessProfile:'STANDARD',executionStrategy:'test-only',startedAt:at,completedAt:'2026-09-21T10:00:01.000Z',rawUsage:{prompt_tokens:100,completion_tokens:10,prompt_tokens_details:{cached_tokens:80}},recipeFingerprint:'digest'}),...changes});
const job=(s:FactorySource)=>projectFactory(s).entities.find(e=>e.kind==='job')!;

test('factory lifecycle preserves runtime VERIFYING until the run actually succeeds',()=>{const r=run();assert.equal(job(source({runs:[r]})).state,'RUNNING');r.status='VERIFYING';r.steps[0].status='VERIFYING';assert.equal(job(source({runs:[r],invocations:[invocation()]})).state,'VERIFYING');r.status='SUCCEEDED';r.steps[0].verification!.passed=['content'];const e=job(source({runs:[r]}));assert.equal(e.state,'SUCCEEDED');assert.equal(e.detail.verification,'PASS');assert.equal(e.links[0].id,r.id);});
test('factory verification failure and retry are not shown as success',()=>{const r=run({status:'FAILED'});r.steps[0].verification!.failed=['content'];r.steps[0].attempts.push({attempt:2,startedAt:at,workerId:'worker-b'});const e=job(source({runs:[r]}));assert.equal(e.detail.verification,'FAIL');assert.equal(e.detail.retries,1);assert.equal(e.state,'FAILED');assert.equal(e.workerId,'worker-b');});
test('factory observed worker reassignment and model/provider changes preserve exact IDs',()=>{const r=run();let p=projectFactory(source({runs:[r],invocations:[invocation()]}));assert.equal(p.entities.find(e=>e.kind==='job')!.providerId,'provider-a');r.steps[0].attempts[0].workerId='worker-b';const next=invocation({model:'alternative',provider:'provider-b'});p=projectFactory(source({runs:[r],invocations:[next]}));assert.equal(p.entities.find(e=>e.kind==='job')!.modelId,'alternative');assert.equal(p.entities.find(e=>e.kind==='job')!.workerId,'worker-b');assert.ok(p.entities.some(e=>e.kind==='model'&&e.sourceId==='alternative'));});
test('shared worker preserves both Run assignments without falsely inheriting the first colour',()=>{const worker={id:'worker-a',capabilities:[],health:'healthy' as const,capacity:2,active:2,observedAt:at},first=run(),second=run({id:'run-2'});let projected=projectFactory(source({runs:[first,second],workers:[worker]})).entities.find(e=>e.kind==='worker')!;assert.equal(projected.runId,null);assert.deepEqual(projected.detail.currentRuns,['run-1','run-2']);second.steps[0].status='SUCCEEDED';projected=projectFactory(source({runs:[first,second],workers:[worker]})).entities.find(e=>e.kind==='worker')!;assert.equal(projected.runId,'run-1');});
test('factory unknown telemetry is null and cache ratios do not fabricate measurements',()=>{const empty=job(source({runs:[run()]}));assert.equal(empty.metrics.inputTokens.value,null);assert.equal(empty.metrics.cacheReusePercent.value,null);const e=job(source({runs:[run()],invocations:[invocation()]}));assert.equal(e.metrics.cachedInputTokens.value,80);assert.equal(e.metrics.cacheReusePercent.value,null);assert.match(e.metrics.inputTokens.authority,/UNKNOWN/);assert.equal(e.metrics.ttftMs.value,null);assert.equal(e.metrics.tokensPerSecond.value,null);assert.equal(e.metrics.peakVramBytes.value,null);});
test('factory estimates remain labelled and partial usage stays unavailable',()=>{const known=invocation({usageSource:'estimated' as const}),unknown=invocation();unknown.accounting!.evidence.cached=null;const e=job(source({runs:[run()],invocations:[known,unknown]}));assert.match(e.metrics.inputTokens.authority,/ESTIMATED/);assert.equal(e.metrics.cachedInputTokens.value,null);assert.equal(e.metrics.cacheReusePercent.value,null);});
test('factory zero input never reports a fabricated cache percentage',()=>{const i=invocation();i.accounting!.evidence.input=0;i.accounting!.evidence.cached=0;assert.equal(job(source({runs:[run()],invocations:[i]})).metrics.cacheReusePercent.value,null);});
test('factory dynamic board lanes are namespaced and linked plans do not duplicate executions',()=>{const board={id:'board',title:'Review',updatedAt:at,lanes:[{id:'arbitrary',label:'User-created lane',parallelism:2}],items:[{id:'work',title:'Plan',state:'ACTIVE',updatedAt:at,laneId:'arbitrary',priority:'HIGH',assignment:{agent:null,model:null,provider:null},runs:[{runId:'run-1'}]}]} as FactorySource['boards'][number];let p=projectFactory(source({runs:[run()],boards:[board]}));assert.equal(p.entities.filter(e=>e.kind==='planned-work').length,0);assert.equal(p.entities.find(e=>e.kind==='job')!.laneId,'lane:board:board:arbitrary');board.lanes.push({id:'next',label:'Next',parallelism:1});board.items[0].laneId='next';p=projectFactory(source({runs:[run()],boards:[board]}));assert.equal(p.entities.find(e=>e.kind==='job')!.laneId,'lane:board:board:next');});
test('factory quarantined worker is isolated until recorded recovery returns AVAILABLE',()=>{const worker={id:'worker-a',capabilities:[],health:'healthy' as const,capacity:1,active:0,observedAt:at};const kill={id:'kill-1',requestedAt:at,completedAt:at,actor:'operator',reason:'cleanup uncertain',scope:{kind:'WORKER' as const,id:'worker-a'},state:'WORKER_QUARANTINED' as const,affected:['owner'],sharedSkipped:[],cleanup:[],leaseRevocation:'UNCONFIRMED' as const,evidence:[],recovery:'QUARANTINED' as const};const s=source({workers:[worker],kills:[kill]});assert.equal(projectFactory(s).entities.find(e=>e.kind==='worker')!.state,'QUARANTINED');s.kills[0].recovery='AVAILABLE';assert.equal(projectFactory(s).entities.find(e=>e.kind==='worker')!.state,'IDLE');});
test('factory stop request, confirmed stop and cleanup signal evidence remain distinct',()=>{const kill={id:'kill',requestedAt:at,completedAt:null,actor:'operator',reason:'cancel requested',scope:{kind:'WORKER' as const,id:'worker-a'},state:'STOP_REQUESTED' as const,affected:['owner'],sharedSkipped:['shared-service'],cleanup:[],leaseRevocation:'NOT_APPLICABLE' as const,evidence:['SIGTERM requested'],recovery:'KILLED' as const};const s=source({kills:[kill]});assert.equal(projectFactory(s).entities[0].state,'STOP_REQUESTED');s.kills[0].state='STOP_CONFIRMED';s.kills[0].completedAt=at;const e=projectFactory(s).entities[0];assert.equal(e.state,'STOP_CONFIRMED');assert.deepEqual(e.detail.sharedSkipped,['shared-service']);});
test('factory evidence retains real hash and opens existing protected content reader',()=>{const s=source({runs:[run()],artifacts:[{id:'artifact-1',runId:'run-1',stepId:'execute',name:'report',type:'application/json',schema:'report/v1',version:'1',createdAt:at,size:40,sha256:'a'.repeat(64),retention:'run-history',provenance:{jobId:'review',jobVersion:'1',action:'read',workerId:'worker-a'}}]});const p=projectFactory(s),e=p.entities.find(e=>e.kind==='evidence')!;assert.equal(e.detail.sha256,'a'.repeat(64));assert.equal(e.detail.externalAnchor,'UNAVAILABLE');assert.deepEqual(e.links,[{kind:'artifact',id:'artifact-1',label:'Open protected evidence'}]);assert.equal(p.relations[0].kind,'evidence');});
test('factory baton consumes actual parcel digest and source/destination stage references',()=>{const context=createParcelContext({goal:'review',actor:'test',at});context.batonViews.push({schema:'agent-control.work-parcel-baton/v2',id:'baton-1',createdAt:at,sourceStageIds:['first'],targetStageId:'second',objective:'review',currentInterpretation:'review',effectiveInstructions:[],constraints:[],successCriteria:[],completedStages:[],nextAction:'Independent review',artifactIds:[],outputTypes:[],eventRefs:[],unresolvedQuestions:[],approvals:[],previousBatonIds:[],sizeBytes:20,estimatedTokens:5,sha256:'b'.repeat(64)});const parcel={id:'parcel',context,stages:[{id:'first',runId:'run-1'},{id:'second',runId:'run-2'}],audit:{timeline:[]}} as unknown as WorkParcel;const p=projectFactory(source({runs:[run(),run({id:'run-2'})],parcels:[parcel]})),e=p.entities.find(e=>e.kind==='baton')!;assert.equal(e.detail.stateDigest,'b'.repeat(64));assert.deepEqual(e.detail.source,['first']);assert.equal(e.detail.destination,'second');assert.ok(p.relations.some(r=>r.kind==='handoff'&&r.from==='job:run-1'&&r.to==='job:run-2'));});
test('factory source credentials are redacted and run parameters are absent',()=>{const r=run({parameters:{secret:'must-not-appear'}});r.provenance=[{type:'test',at,detail:'Bearer sensitive-material-12345'}];const p=JSON.stringify(projectFactory(source({runs:[r]})));assert.ok(!p.includes('must-not-appear'));assert.ok(!p.includes('sensitive-material-12345'));});
test('factory journal reconnect cursor, bounded eviction and epoch restart are explicit',()=>{const journal=new FactoryJournal(2,100000),p=projectFactory(source()),a=journal.append(p),b=journal.append(p);assert.equal(journal.replay(a.id).frames[0].id,b.id);journal.append(p);assert.equal(journal.replay(a.id).coverage.gap,true);assert.equal(journal.replay().frames.length,2);assert.equal(new FactoryJournal().replay(b.id).coverage.gap,true);assert.throws(()=>new FactoryJournal(2,1).append(p),/exceeds/);});
test('factory replacement frame replay preserves earlier states without rerunning work',()=>{const r=run({status:'QUEUED'}),journal=new FactoryJournal();journal.append(projectFactory(source({runs:[r]})));r.status='SUCCEEDED';journal.append(projectFactory(source({runs:[r]})));assert.deepEqual(journal.replay().frames.map(f=>f.projection.entities[0].state),['QUEUED','SUCCEEDED']);});
test('factory stream is dormant without viewers and reports source failures without changing execution',async()=>{let calls=0;const stream=new FactoryStream(()=>{calls++;return source();},10);await new Promise(r=>setTimeout(r,25));assert.equal(calls,0);stream.close();});
test('factory SSE requires operator read authority, provides live frames and resets expired cursors',async t=>{const service=new AgentControlService({version:1,paused:false,lastRestorePoint:null,lanes:[]},new PtyRegistry()),server=startWebDashboard(service,{port:0,operatorToken:'test-only'});await once(server,'listening');const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;t.after(()=>{server.closeAllConnections();server.close();});assert.equal((await fetch(base+'/api/factory/events')).status,401);const headers={Authorization:'Bearer test-only'};const snapshot=await(await fetch(base+'/api/factory/snapshot',{headers})).json() as {id:string};assert.ok(snapshot.id);const abort=new AbortController();const res=await fetch(base+'/api/factory/events',{headers:{...headers,'Last-Event-ID':'expired:1'},signal:abort.signal});const reader=res.body!.getReader();let content='';for(let i=0;i<5&&!content.includes('factory.frame');i++){const chunk=await reader.read();content+=new TextDecoder().decode(chunk.value);}abort.abort();assert.match(content,/factory.coverage/);assert.match(content,/"gap":true/);assert.match(content,/factory.frame/);assert.equal((await fetch(base+'/api/factory/snapshot',{method:'POST',headers})).status,405);});
test('factory disabled mode does not project runtime state and returns explicit unavailable',async t=>{const service=new AgentControlService({version:1,paused:false,lastRestorePoint:null,lanes:[]},new PtyRegistry());service.factorySource=()=>{throw Error('must not run');};const server=startWebDashboard(service,{port:0,operatorToken:'test-only',factoryEnabled:false});await once(server,'listening');t.after(()=>{server.closeAllConnections();server.close();});const res=await fetch(`http://127.0.0.1:${(server.address() as AddressInfo).port}/api/factory/snapshot`,{headers:{Authorization:'Bearer test-only'}});assert.equal(res.status,404);assert.deepEqual(await res.json(),{error:'factory_view_disabled'});});

test('factory published schema validates actual renderer-independent frames',()=>{const validate=new Ajv2020({strict:false}).compile(JSON.parse(fs.readFileSync(new URL('../../docs/factory-event.schema.json',import.meta.url),'utf8')));const frame=new FactoryJournal().append(projectFactory(source({runs:[run()],invocations:[invocation()]})));assert.ok(validate(frame),JSON.stringify(validate.errors));const invalid=structuredClone(frame);invalid.projection.entities[0].metrics.inputTokens.value=-1;assert.equal(validate(invalid),false);});
test('factory known attested cache partitions report reuse and real cache links',()=>{const i=invocation();i.accounting!.semantics.input='INCLUDES_CACHE';i.accounting!.evidence.cacheWrite=0;const p=projectFactory(source({runs:[run()],invocations:[i]})),e=p.entities.find(e=>e.kind==='job')!;assert.equal(e.metrics.cacheReusePercent.value,80);assert.equal(e.metrics.freshInputTokens.value,20);assert.ok(p.entities.some(e=>e.kind==='cache'&&e.state==='REUSE_REPORTED'));assert.ok(p.relations.some(r=>r.kind==='cache'&&r.to==='job:run-1'));});
test('factory node quarantine uses established worker identity rather than worker labels',()=>{const worker={id:'worker-a',capabilities:[],health:'healthy' as const,capacity:1,active:0,observedAt:at,labels:{nodeId:'wrong-node'}};const kill={id:'kill-1',requestedAt:at,completedAt:at,actor:'operator',reason:'uncertain node cleanup',scope:{kind:'NODE' as const,id:'node-a'},state:'WORKER_QUARANTINED' as const,affected:['owner'],sharedSkipped:[],cleanup:[],leaseRevocation:'UNCONFIRMED' as const,evidence:[],recovery:'QUARANTINED' as const};const p=projectFactory(source({workers:[worker],kills:[kill],workerIdentities:[{workerId:'worker-a',nodeId:'node-a',locality:'REMOTE_WORKER',authority:'CONFIGURED_RESOURCE',controllerRelationship:'REMOTE_RESOURCE'}]}));assert.equal(p.entities.find(e=>e.kind==='worker')!.state,'QUARANTINED');});
test('factory no active model is assigned to a deterministic verifier from historical invocation data',()=>{const r=run();r.steps[0].attempts[0].workerId='verifier';const p=projectFactory(source({runs:[r],invocations:[invocation()],workers:[{id:'verifier',capabilities:[],health:'healthy',capacity:1,active:1,observedAt:at}]}));assert.equal(p.entities.find(e=>e.kind==='worker')!.modelId,null);assert.equal(p.entities.find(e=>e.kind==='job')!.detail.modelAssignment,'MOST_RECENT_INVOCATION');});
test('factory captions retain recorded event identity instead of generating invented success',()=>{const p=projectFactory(source({events:[{id:3,at,type:'job.run_changed',payload:{runId:'run-1',status:'VERIFYING'}}]}));assert.equal(p.events[0].sourceId,'3');assert.match(p.events[0].caption,/VERIFYING/);assert.ok(!p.events[0].caption.includes('PASS'));});
test('factory bounded population reports omissions instead of pretending all jobs are visible',()=>{const runs=Array.from({length:110},(_,i)=>run({id:`run-${i}`,status:'SUCCEEDED'}));const p=projectFactory(source({runs}));assert.equal(p.entities.filter(e=>e.kind==='job').length,100);assert.equal(p.coverage.omittedEntities,10);});

test('factory slow SSE reader coalesces frames until drain, then resumes with current state',async()=>{
  const request=Object.assign(new EventEmitter(),{headers:{}}),writes:string[]=[];
  const response=Object.assign(new EventEmitter(),{destroyed:false,writableEnded:false,writableLength:0,writeHead(){},write(value:string){writes.push(value);return !value.includes('factory.frame');},end():void{response.writableEnded=true;response.emit('close');},destroy():void{response.destroyed=true;response.emit('close');}});
  const stream=new FactoryStream(()=>source(),10);try{stream.connect(request as IncomingMessage,response as unknown as ServerResponse);await new Promise(r=>setTimeout(r,70));assert.equal(writes.filter(w=>w.includes('factory.frame')).length,1);response.emit('drain');await new Promise(r=>setTimeout(r,35));assert.equal(writes.filter(w=>w.includes('factory.frame')).length,2);response.writableLength=1024*1024+1;await new Promise(r=>setTimeout(r,35));assert.equal(response.destroyed,true);}finally{stream.close();}
});

test('factory source failure closes observer without throwing into runtime execution',async()=>{
  const request=Object.assign(new EventEmitter(),{headers:{}}),writes:string[]=[];
  const response=Object.assign(new EventEmitter(),{destroyed:false,writableEnded:false,writableLength:0,writeHead(){},write(value:string){writes.push(value);return true;},end():void{response.writableEnded=true;response.emit('close');}});
  const stream=new FactoryStream(()=>{throw Error('source failure');},10);try{stream.connect(request as IncomingMessage,response as unknown as ServerResponse);await new Promise(r=>setTimeout(r,35));assert.equal(response.writableEnded,true);assert.ok(writes.some(w=>w.includes('factory_projection_unavailable')));}finally{stream.close();}
});

test('factory skill selection is version-exact and never asserts an adapter loaded or permanent learning',()=>{
  const skill={id:'adapter',version:'1',label:'Audit adapter',base:{modelId:'base'},adapter:{format:'lora',artefactSha256:'a'.repeat(64)},training:{method:'LoRA'},qualification:{state:'QUALIFIED'},lifecycle:{lastUsedAt:null,registeredAt:at}} as FactorySource['skills'][number];
  const route={schema:'agent-control.skill-routing-decision/v1' as const,id:'route',parcelId:'parcel',stageId:'stage',at,taskClass:'audit',baseModelId:'base',candidates:[],selected:{adapterId:'adapter',version:'1',artefactSha256:'a'.repeat(64)},reason:'Qualified exact adapter'};
  const parcel={id:'parcel',stages:[{id:'stage',runId:'run-1'}],audit:{timeline:[]}} as unknown as WorkParcel;
  const p=projectFactory(source({skills:[skill],skillRouting:[route],parcels:[parcel],runs:[run()]})),e=p.entities.find(e=>e.kind==='skill')!;
  assert.equal(e.detail.trainingTokenCount,null);assert.equal(e.detail.loadReceipt,'UNAVAILABLE');assert.equal(e.detail.semantics,'LOADABLE_ADAPTER_NOT_PERMANENT_LEARNING');assert.ok(p.relations.some(r=>r.kind==='skill'&&r.to==='job:run-1'));assert.match(p.events[0].caption,/SELECTED.*load receipt unavailable/);
  route.selected.version='2';assert.equal(projectFactory(source({skills:[skill],skillRouting:[route]})).relations.length,0);
});
