import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import test from 'node:test';
import {unknownInteractionProfile,observeInteraction,qualifiedInteraction,reprioritisationDisposition} from './harness-interaction.js';
import {GovernedEffectStore} from './governed-effects.js';import {TypedWorkerTransport} from './outbound-worker-transport.js';import {createTraceCorrelation,exportTraceSafely} from './trace-correlation.js';
import {assessScope,ContainmentSupervisor,sealExecutionScope,type ExecutionOwnership} from './containment.js';import type {ExecutionCleanupReport,OwnedExecution} from './owned-process.js';
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'ac-governance-'));
function execution(outcome:ExecutionCleanupReport['outcome']='confirmed'):OwnedExecution{return{activePids:()=>[100],runProcess:async()=>({pid:100,exitCode:0,signal:null,stdout:'',stderr:''}),terminateAll:async reason=>({outcome,reason:reason??'',requestedAt:'2026-01-01T00:00:00Z',completedAt:'2026-01-01T00:00:01Z',processes:[]})};}
function envelope(){return sealExecutionScope({workspace:'ws',repository:null,filesystem:{readable:['/r'],writable:['/w']},network:{destinations:['private.example'],ports:[443]},devices:['gpu0'],runtimes:['podman'],credentialReferences:['ref:provider'],tools:['git'],apis:['status'],models:['model-a'],subprocesses:['git'],maximum:{runtimeMs:1000,cpuPercent:100,ramBytes:1024,gpuPercent:100,vramBytes:1024,diskBytes:1024,networkBytes:1024,externalEffects:1},createdAt:'2026-01-01T00:00:00Z'});}

test('interaction defaults unknown and observed drift degrades only the observed trait',()=>{const p=unknownInteractionProfile('worker-a','1');assert.equal(p.traits.resume,'UNKNOWN');p.traits.resume='SUPPORTED';p.traits.interrupt='SUPPORTED';const o=observeInteraction({id:'o1',adapterId:'worker-a',trait:'interrupt',expectedObservation:'SUPPORTED',observedObservation:'UNSUPPORTED',probeVersion:'1',observedAt:'2026-01-01T00:00:00Z',evidence:['e1']});const q=qualifiedInteraction(p,[o]);assert.deepEqual(q.drift,['interrupt']);assert.equal(q.profile.traits.interrupt,'UNSUPPORTED');assert.equal(q.profile.traits.resume,'SUPPORTED');assert.equal(reprioritisationDisposition(p,[o]).action,'CONTINUE_ATOMIC_STEP');});
test('three worker interruption profiles produce distinct safe dispositions',()=>{const a=unknownInteractionProfile('a','1'),b=unknownInteractionProfile('b','1'),c=unknownInteractionProfile('c','1');a.traits.interrupt=a.traits.resume='SUPPORTED';b.traits.cancellation='SUPPORTED';c.traits.interrupt='UNSUPPORTED';assert.equal(reprioritisationDisposition(a,[]).action,'CHECKPOINT_THEN_PAUSE');assert.equal(reprioritisationDisposition(b,[]).action,'DEFER_PHYSICAL_CHANGE');assert.equal(reprioritisationDisposition(c,[]).action,'CONTINUE_ATOMIC_STEP');});
test('governed effects bind exact approval, reject replay, persist and mark uncertain commits',async()=>{const file=path.join(tmp(),'effects.json'),store=new GovernedEffectStore(file,()=> '2026-01-01T00:00:00Z'),p=store.propose([{kind:'MOVE_ITEM',target:'a',value:'top'}],'2026-01-02T00:00:00Z');assert.throws(()=>store.decide(p.id,'bad',{approved:true,actor:'op',decisionId:'d1',evidence:['e']}),/hash/);store.decide(p.id,p.proposalHash,{approved:true,actor:'op',decisionId:'d1',evidence:['e']});await assert.rejects(()=>store.commit(p.id,p.proposalHash,async()=>{throw Error('lost response');}));assert.equal(new GovernedEffectStore(file).list()[0]!.state,'COMMIT_STATE_UNCERTAIN');});
test('typed transport authenticates generations and rejects replay, stale and revoked lease results',()=>{let now=new Date('2026-01-01T00:00:00Z');const t=new TypedWorkerTransport(undefined,()=>now);t.connect('w','identity',1);const l=t.issueLease('w',1000),base={schema:'agent-control.worker-frame/v1' as const,id:'f',workerId:'w',sessionGeneration:1,sequence:1,type:'RESULT' as const,leaseId:l.id,sentAt:now.toISOString(),payload:{status:'ok'}};assert.equal(t.receive(base).type,'RESULT');assert.throws(()=>t.receive(base),/replay/);t.revokeLease(l.id);assert.throws(()=>t.receive({...base,id:'f2',sequence:2}),/stale/);t.connect('w','identity',2);assert.throws(()=>t.receive({...base,id:'f3',sequence:3}),/generation/);});
test('trace correlation captures identifiers only and exporter failure never controls execution',async()=>{const trace=createTraceCorrelation({'run.id':'r','prompt':'secret','worker.id':'w'});assert.deepEqual(trace.attributes,{'run.id':'r','worker.id':'w'});assert.deepEqual(await exportTraceSafely(trace,{export:async()=>{throw Error('down');}}),{exported:false,reason:'exporter_failed_execution_continued'});});
test('scope envelope allows declared action and blocks filesystem escape',()=>{const e=envelope();assert.equal(assessScope(e,{filesystemPath:'/w'}).allowed,true);const denied=assessScope(e,{filesystemPath:'/etc'});assert.equal(denied.allowed,false);assert.equal(denied.response,'BLOCK_ACTION');});
test('scope envelope distinguishes hard network/subprocess violations with kill response',()=>{const denied=assessScope(envelope(),{networkDestination:'public.example',subprocess:'bash'});assert.equal(denied.response,'KILL_JOB');assert.equal(denied.violations.length,2);});
test('scope envelope integrity rejects tampering',()=>{const e=envelope();e.maximum.runtimeMs=2;assert.throws(()=>assessScope(e,{}),/hash/);});
test('job kill affects owned exclusive execution and persists confirmation',async()=>{const file=path.join(tmp(),'contain.json'),s=new ContainmentSupervisor(file),owner:ExecutionOwnership={id:'o1',scopes:[{kind:'JOB',id:'j1'}],execution:execution(),exclusive:true};s.register(owner);assert.deepEqual(s.preview({kind:'JOB',id:'j1'}).affected,['o1']);const r=await s.kill({kind:'JOB',id:'j1'},'operator','stop');assert.equal(r.state,'STOP_CONFIRMED');assert.equal(new ContainmentSupervisor(file).list().kills.length,1);});
test('shared infrastructure is skipped for narrow kill',async()=>{const s=new ContainmentSupervisor(path.join(tmp(),'c.json'));s.register({id:'shared',scopes:[{kind:'JOB',id:'j'}],execution:execution(),exclusive:false});const r=await s.kill({kind:'JOB',id:'j'},'operator','stop');assert.deepEqual(r.affected,[]);assert.deepEqual(r.sharedSkipped,['shared']);});
test('estate emergency stop includes shared infrastructure',async()=>{const s=new ContainmentSupervisor(path.join(tmp(),'c.json'));s.register({id:'shared',scopes:[{kind:'JOB',id:'j'}],execution:execution(),exclusive:false});assert.deepEqual((await s.kill({kind:'ESTATE',id:'estate'},'operator','emergency')).affected,['shared']);});
test('ignored or uncertain cancellation quarantines owner',async()=>{const s=new ContainmentSupervisor(path.join(tmp(),'c.json'));s.register({id:'w',scopes:[{kind:'WORKER',id:'w'}],execution:execution('uncertain'),exclusive:true});const r=await s.kill({kind:'WORKER',id:'w'},'watchdog','ignored cancellation');assert.equal(r.state,'WORKER_QUARANTINED');assert.deepEqual(s.list().quarantined,['w']);});
test('lost lease revocation quarantines remote worker',async()=>{const s=new ContainmentSupervisor(path.join(tmp(),'c.json'));s.register({id:'remote',scopes:[{kind:'WORKER',id:'remote'}],execution:execution(),exclusive:true,leaseRevoker:async()=>{throw Error('offline');}});const r=await s.kill({kind:'WORKER',id:'remote'},'watchdog','lost connectivity');assert.equal(r.leaseRevocation,'UNCONFIRMED');assert.equal(r.state,'WORKER_QUARANTINED');});
test('node isolation failure remains unconfirmed and quarantined',async()=>{const s=new ContainmentSupervisor(path.join(tmp(),'c.json'));s.register({id:'node-work',scopes:[{kind:'NODE',id:'n'}],execution:execution(),exclusive:true,isolate:async()=>false});assert.equal((await s.kill({kind:'NODE',id:'n'},'operator','contain')).state,'WORKER_QUARANTINED');});
test('recovery lifecycle requires ordered evidenced transitions',async()=>{const s=new ContainmentSupervisor(path.join(tmp(),'c.json'));s.register({id:'w',scopes:[{kind:'WORKER',id:'w'}],execution:execution('uncertain'),exclusive:true});const r=await s.kill({kind:'WORKER',id:'w'},'watchdog','stop');assert.throws(()=>s.recovery(r.id,'AVAILABLE','skip'),/transition/);for(const state of ['INSPECTED','RESET','REQUALIFIED','AVAILABLE'] as const)s.recovery(r.id,state,`evidence:${state}`);assert.deepEqual(s.list().quarantined,[]);});
test('confirmed kill enters durable quarantine only through explicit recovery',async()=>{const file=path.join(tmp(),'c.json'),s=new ContainmentSupervisor(file);s.register({id:'w',scopes:[{kind:'WORKER',id:'w'}],execution:execution(),exclusive:true});const r=await s.kill({kind:'WORKER',id:'w'},'watchdog','stop');assert.deepEqual(s.list().quarantined,[]);s.recovery(r.id,'QUARANTINED','inspection required');assert.deepEqual(new ContainmentSupervisor(file).list().quarantined,['w']);});
test('durable containment authority fences stable worker identity until authorised availability',async()=>{const file=path.join(tmp(),'c.json'),s=new ContainmentSupervisor(file);s.register({id:'owner-w',scopes:[{kind:'WORKER',id:'worker-a'}],execution:execution('uncertain'),exclusive:true});const killed=await s.kill({kind:'WORKER',id:'worker-a'},'watchdog','uncertain stop'),scope=[{kind:'WORKER' as const,id:'worker-a'}];assert.equal(s.schedulingEligibility(scope).eligible,false);const restarted=new ContainmentSupervisor(file);assert.match(restarted.schedulingEligibility(scope).reason!,/QUARANTINED/);for(const state of ['INSPECTED','RESET','REQUALIFIED'] as const){restarted.recovery(killed.id,state,`evidence:${state}`,'recovery-operator');assert.equal(restarted.schedulingEligibility(scope).eligible,false);}const available=restarted.recovery(killed.id,'AVAILABLE','qualification:passed','recovery-operator');assert.equal(restarted.schedulingEligibility(scope).eligible,true);assert.deepEqual(available.recoveryEvents?.map(value=>value.actor),['recovery-operator','recovery-operator','recovery-operator','recovery-operator']);});
test('kill supervisor operates without scheduler or model dependency',async()=>{const s=new ContainmentSupervisor(path.join(tmp(),'c.json'));s.register({id:'x',scopes:[{kind:'LANE',id:'lane'}],execution:execution(),exclusive:true});assert.equal((await s.kill({kind:'LANE',id:'lane'},'watchdog','scheduler unavailable')).state,'STOP_CONFIRMED');});
test('unmatched scope is a confirmed no-op with durable request evidence',async()=>{const s=new ContainmentSupervisor(path.join(tmp(),'c.json'));const r=await s.kill({kind:'MODEL',id:'missing'},'operator','stop model');assert.equal(r.state,'STOP_CONFIRMED');assert.deepEqual(r.affected,[]);assert.ok(r.evidence.includes('containment-confirmed'));});
test('containment timeline projects recorded stop and recovery events in chronological order',async()=>{let tick=0;const s=new ContainmentSupervisor(path.join(tmp(),'c.json'),()=>`2026-01-01T00:00:0${tick++}.000Z`);s.register({id:'w',scopes:[{kind:'WORKER',id:'w'}],execution:execution('uncertain'),exclusive:true});const killed=await s.kill({kind:'WORKER',id:'w'},'operator','uncertain worker stop');s.recovery(killed.id,'INSPECTED','inspection:passed','reviewer');const timeline=s.timeline();assert.deepEqual(timeline.events.map(event=>event.type),['STOP_REQUESTED','STOP_COMPLETED','RECOVERY']);assert.equal(timeline.events[2]?.actor,'reviewer');assert.equal(timeline.events[0]?.reason,'uncertain worker stop');assert.equal(timeline.authority,'DERIVED_FROM_DURABLE_CONTAINMENT_RECORDS');});
