import {createHash} from 'node:crypto';

export const interactionValues=['SUPPORTED','UNSUPPORTED','UNKNOWN'] as const;
export type InteractionSupport=typeof interactionValues[number];
export type InteractionTrait='elicitation'|'resume'|'cancellation'|'interrupt'|'streaming'|'steering'|'liveQueue'|'forkHistoryTransfer';
export interface HarnessInteractionProfile{schema:'agent-control.harness-interaction-profile/v1';adapterId:string;adapterVersion:string;integrationMode:'LOCAL_PROCESS'|'REMOTE_PROCESS'|'API'|'MANAGED_SERVICE'|'UNKNOWN';traits:Record<InteractionTrait,InteractionSupport>;authOwnership:'AGENT_CONTROL'|'ADAPTER'|'EXTERNAL'|'UNKNOWN';instructionDelivery:'ARGUMENT'|'STDIN'|'API_MESSAGE'|'FILE_REFERENCE'|'UNKNOWN';observedAt:string|null;evidence:string[];}
export interface InteractionObservation{schema:'agent-control.harness-interaction-observation/v1';id:string;adapterId:string;trait:InteractionTrait;expectedObservation:InteractionSupport;observedObservation:InteractionSupport;drift:boolean;probeVersion:string;observedAt:string;evidence:string[];sha256:string;}

const traits:InteractionTrait[]=['elicitation','resume','cancellation','interrupt','streaming','steering','liveQueue','forkHistoryTransfer'];
export function unknownInteractionProfile(adapterId:string,adapterVersion:string):HarnessInteractionProfile{return{schema:'agent-control.harness-interaction-profile/v1',adapterId,adapterVersion,integrationMode:'UNKNOWN',traits:Object.fromEntries(traits.map(value=>[value,'UNKNOWN'])) as Record<InteractionTrait,InteractionSupport>,authOwnership:'UNKNOWN',instructionDelivery:'UNKNOWN',observedAt:null,evidence:[]};}
export function validateInteractionProfile(value:HarnessInteractionProfile){if(value.schema!=='agent-control.harness-interaction-profile/v1'||!value.adapterId.trim()||!value.adapterVersion.trim())throw Error('interaction_profile_invalid');for(const trait of traits)if(!interactionValues.includes(value.traits[trait]))throw Error(`interaction_profile_trait_invalid:${trait}`);return structuredClone(value);}
export function observeInteraction(input:Omit<InteractionObservation,'schema'|'drift'|'sha256'>):InteractionObservation{if(!input.probeVersion.trim()||!input.observedAt||!input.evidence.length)throw Error('interaction_observation_evidence_required');const base={schema:'agent-control.harness-interaction-observation/v1' as const,...structuredClone(input),drift:input.expectedObservation!==input.observedObservation};return{...base,sha256:createHash('sha256').update(JSON.stringify(base)).digest('hex')};}
export function qualifiedInteraction(profile:HarnessInteractionProfile,observations:InteractionObservation[]){validateInteractionProfile(profile);const effective=structuredClone(profile),drift:InteractionTrait[]=[];for(const observation of observations.filter(value=>value.adapterId===profile.adapterId)){if(observation.drift)drift.push(observation.trait);effective.traits[observation.trait]=observation.observedObservation;}return{profile:effective,drift:[...new Set(drift)],qualified:observations.some(value=>value.adapterId===profile.adapterId)};}
export function reprioritisationDisposition(profile:HarnessInteractionProfile,observations:InteractionObservation[]){const value=qualifiedInteraction(profile,observations).profile.traits;if(value.interrupt==='SUPPORTED'&&value.resume==='SUPPORTED')return{action:'CHECKPOINT_THEN_PAUSE' as const,reason:'Qualified interrupt and durable resume are supported.'};if(value.interrupt==='UNSUPPORTED')return{action:'CONTINUE_ATOMIC_STEP' as const,reason:'Observed worker is non-interruptible; board order changes now and execution changes at the next safe boundary.'};return{action:'DEFER_PHYSICAL_CHANGE' as const,reason:'Interrupt semantics are unknown; no destructive inference is permitted.'};}
