import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {JobCatalog} from './job-catalog.js';
import {ActionFailure, ActionRegistry, ArtifactStore, JobRuntime, ResourceLockManager, RunLedger, WorkerRegistry} from './job-runtime.js';
import type {JobDefinition, ScheduleDefinition, WorkerRegistration} from './job-types.js';
import {registerBrowserActions} from './browser-actions.js';
import {registerReferenceActions} from './reference-actions.js';
import {registerProtectedResourceModelActions} from './protected-resource-model-actions.js';
import type {AgentControlConfig} from './config.js';
import {createInvocationStart, MemoryHarnessEfficiencyLedger, type HarnessEfficiencyLedgerPort} from './harness-efficiency.js';
import {RuntimeSafetySupervisor} from './runtime-safety-supervisor.js';
import type {ExecutionCleanupReport, OwnedExecution} from './owned-process.js';
import {ExecutionSessionRuntime} from './execution-session.js';

const worker = (id: string, capabilities: string[], health: WorkerRegistration['health'] = 'healthy', extra: Partial<WorkerRegistration> = {}): WorkerRegistration => ({id, capabilities, health, capacity: 1, active: 0, observedAt: new Date().toISOString(), ...extra});

test('GPU-required Job cannot silently execute on a CPU-only worker', async t => {
  let dispatched=0;
  const setup=runtime(job([{id:'gpu',action:'gpu@1.0.0',requires:['gpu.nvidia']}]),actions=>actions.register('gpu@1.0.0',async()=>{dispatched++;return{};}),[worker('cpu',['cpu'])]);
  t.after(()=>fs.rmSync(setup.root,{recursive:true,force:true}));
  const run=setup.runtime.createRun('job@1.0.0',{}, {type:'manual',actor:'test'});
  await setup.runtime.tick();
  assert.equal(dispatched,0);
  assert.notEqual(setup.runtime.ledger.get(run.id)?.status,'SUCCEEDED');
  assert.equal(setup.workers.resolve(['gpu.nvidia']).worker,undefined);
  assert.match(JSON.stringify(setup.workers.resolve(['gpu.nvidia']).rationale),/gpu.nvidia/);
});
const job = (steps: JobDefinition['spec']['steps'], extra: Partial<JobDefinition['spec']> = {}): JobDefinition => ({apiVersion: 'agent-control/v1', kind: 'Job', metadata: {id: 'job', name: 'Job', version: '1.0.0'}, spec: {priority: 'normal', concurrency: 'no-overlap', steps, ...extra}});
function runtime(definition: JobDefinition, handlers: (actions: ActionRegistry) => void, workers: WorkerRegistration[], schedule?: ScheduleDefinition, clock?: () => Date, efficiency?: HarnessEfficiencyLedgerPort) { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-control-runtime-')), actions = new ActionRegistry(); handlers(actions); const catalog = new JobCatalog(actions.ids()); catalog.addJob(definition); if (schedule) catalog.addSchedule(schedule); const registry = new WorkerRegistry(); workers.forEach(item => registry.register(item)); return {root, actions, catalog, workers: registry, runtime: new JobRuntime(catalog, actions, registry, new RunLedger(path.join(root, 'ledger.json')), new ArtifactStore(path.join(root, 'artifacts')), new ResourceLockManager(path.join(root, 'locks.json')), {now: clock, approval: () => true, efficiency})}; }

test('concurrent dispatch calls cannot select the same run step twice',async()=>{let release:()=>void=()=>{},calls=0;const setup=runtime(job([{id:'one',action:'one@1.0.0',requires:['run']}]),actions=>actions.register('one@1.0.0',async()=>{calls++;await new Promise<void>(resolve=>{release=resolve});return{};}),[worker('worker',['run'])]);const run=setup.runtime.createRun('job@1.0.0',{}, {type:'manual',actor:'test'}),first=setup.runtime.dispatch();assert.ok(first);assert.equal(setup.runtime.dispatch(),undefined);await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,1);release();await first!.completion;assert.equal(setup.runtime.ledger.get(run.id)?.status,'SUCCEEDED');});

test('manual Run uses capability placement, typed artifact handoff and verified completion', async () => { let consumed = 0; const setup = runtime(job([{id: 'produce', action: 'produce@1.0.0', requires: ['source'], outputs: [{name: 'data', type: 'application/json', schema: 'data/v1', version: '1.0.0'}], verification: ['schema']}, {id: 'consume', action: 'consume@1.0.0', requires: ['sink'], dependsOn: ['produce'], inputs: {data: 'produce.data'}, verification: ['tests']}]), actions => { actions.register('produce@1.0.0', async () => ({artifacts: [{name: 'data', value: {count: 3}}], verification: ['schema']})); actions.register('consume@1.0.0', async context => { consumed = (context.readArtifact(context.inputArtifacts[0].id) as {count: number}).count; return {verification: ['tests']}; }); }, [worker('source-worker', ['source']), worker('sink-worker', ['sink'])]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); assert.equal(setup.runtime.ledger.get(run.id)?.steps[0].status, 'SUCCEEDED'); await setup.runtime.tick(); const complete = setup.runtime.ledger.get(run.id)!; assert.equal(complete.status, 'SUCCEEDED'); assert.equal(consumed, 3); assert.deepEqual(complete.selectedWorkers, ['source-worker', 'sink-worker']); assert.equal(setup.runtime.artifacts.list(run.id).length, 1); });
test('incapable, offline and expired workers are rejected with visible rationale', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['required']}]), actions => { actions.register('one@1.0.0', async () => ({})); }, [worker('incapable', []), worker('offline', ['required'], 'offline'), worker('expired', ['required'], 'healthy', {capabilityExpiresAt: {required: '2020-01-01T00:00:00Z'}})]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const step = setup.runtime.ledger.get(run.id)!.steps[0]; assert.equal(step.status, 'WAITING_FOR_WORKER'); assert.deepEqual(step.placement?.rejected.map(item => item.workerId), ['incapable', 'offline', 'expired']); assert.match(step.waitingReason ?? '', /No worker/); });
test('identical worker waits do not churn and resume when capacity is available', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['required']}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', ['required'], 'offline')]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const eventsFile = path.join(setup.root, 'run-events.jsonl'), firstCount = fs.readFileSync(eventsFile, 'utf8').trim().split('\n').length; assert.equal(setup.runtime.ledger.get(run.id)?.status, 'WAITING'); await setup.runtime.tick(); await setup.runtime.tick(); assert.equal(fs.readFileSync(eventsFile, 'utf8').trim().split('\n').length, firstCount); setup.workers.setHealth('worker', 'healthy'); await setup.runtime.tick(); assert.equal(setup.runtime.ledger.get(run.id)?.status, 'SUCCEEDED'); });
test('resource contention is durable, visible and released after failure', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], resources: ['exclusive']}], {concurrency: 'allow'}), actions => { actions.register('one@1.0.0', async () => { throw new ActionFailure('permanent', 'configuration'); }); }, [worker('worker', ['run'])]); setup.runtime.locks.acquire(['exclusive'], 'other-run', 'step'); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); assert.equal(setup.runtime.ledger.get(run.id)!.steps[0].status, 'WAITING_FOR_RESOURCE'); assert.match(setup.runtime.queueProjection()[0].reason ?? '', /other-run/); setup.runtime.locks.release('other-run'); await setup.runtime.tick(); assert.equal(setup.runtime.ledger.get(run.id)!.status, 'FAILED'); assert.equal(setup.runtime.locks.list().length, 0); });
test('identical resource waits are transition-driven and resume without ledger churn', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], resources: ['exclusive']}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', ['run'])]); setup.runtime.locks.acquire(['exclusive'], 'other-run', 'step'); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const eventsFile = path.join(setup.root, 'run-events.jsonl'), firstCount = fs.readFileSync(eventsFile, 'utf8').trim().split('\n').length; assert.equal(setup.runtime.ledger.get(run.id)?.status, 'WAITING'); await setup.runtime.tick(); await setup.runtime.tick(); assert.equal(fs.readFileSync(eventsFile, 'utf8').trim().split('\n').length, firstCount); setup.runtime.locks.release('other-run'); await setup.runtime.tick(); assert.equal(setup.runtime.ledger.get(run.id)?.status, 'SUCCEEDED'); });
test('retry policy is bounded and every attempt is recorded', async () => { let calls = 0, instant = new Date('2026-01-01T00:00:00Z'); const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], verification: ['ok']}], {retry: {attempts: 1, backoffSeconds: 5}}), actions => { actions.register('one@1.0.0', async () => { calls++; if (calls === 1) throw new ActionFailure('temporary', 'execution', true); return {verification: ['ok']}; }); }, [worker('worker', ['run'])], undefined, () => instant); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); assert.equal(setup.runtime.ledger.get(run.id)!.steps[0].status, 'RETRY_PENDING'); instant = new Date(instant.getTime() + 5000); await setup.runtime.tick(); const result = setup.runtime.ledger.get(run.id)!; assert.equal(result.status, 'SUCCEEDED'); assert.equal(result.steps[0].attempts.length, 2); });
test('verification failure is distinct from process completion', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], verification: ['required-check']}]), actions => { actions.register('one@1.0.0', async () => ({detail: 'process exited zero'})); }, [worker('worker', ['run'])]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const result = setup.runtime.ledger.get(run.id)!; assert.equal(result.status, 'DEGRADED'); assert.equal(result.steps[0].attempts[0].errorClass, 'verification'); });
test('upstream failure cancels dependent steps without dispatching them', async () => { let dependentCalls = 0; const setup = runtime(job([{id: 'first', action: 'first@1.0.0', requires: ['run']}, {id: 'second', action: 'second@1.0.0', requires: ['run'], dependsOn: ['first']}]), actions => { actions.register('first@1.0.0', async () => { throw new ActionFailure('bad configuration', 'configuration'); }); actions.register('second@1.0.0', async () => { dependentCalls++; return {}; }); }, [worker('worker', ['run'])]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const result = setup.runtime.ledger.get(run.id)!; assert.equal(result.steps[1].status, 'CANCELLED'); assert.equal(result.steps[1].error, 'upstream_failed'); assert.equal(dependentCalls, 0); });
test('approval requirement remains a visible wait until explicitly granted', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], approval: 'release'}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', ['run'])]); const deniedRuntime = new JobRuntime(setup.catalog, setup.actions, setup.workers, setup.runtime.ledger, setup.runtime.artifacts, setup.runtime.locks, {approval: () => false}), run = deniedRuntime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await deniedRuntime.tick(); assert.equal(deniedRuntime.ledger.get(run.id)!.steps[0].status, 'WAITING_FOR_APPROVAL'); deniedRuntime.approve(run.id, 'release'); await deniedRuntime.tick(); assert.equal(deniedRuntime.ledger.get(run.id)!.status, 'SUCCEEDED'); });
test('approval waits are reported as WAITING and repeated ticks do not duplicate events', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], approval: 'release'}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', ['run'])]); const deniedRuntime = new JobRuntime(setup.catalog, setup.actions, setup.workers, setup.runtime.ledger, setup.runtime.artifacts, setup.runtime.locks, {approval: () => false}), run = deniedRuntime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await deniedRuntime.tick(); const eventsFile = path.join(setup.root, 'run-events.jsonl'), firstCount = fs.readFileSync(eventsFile, 'utf8').trim().split('\n').length; assert.equal(deniedRuntime.ledger.get(run.id)?.status, 'WAITING'); await deniedRuntime.tick(); await deniedRuntime.tick(); assert.equal(fs.readFileSync(eventsFile, 'utf8').trim().split('\n').length, firstCount); });
test('cancellation aborts execution and retains the exclusive lock until the handler returns', async () => { let release!: () => void; const waiting = new Promise<void>(resolve => { release = resolve; }); const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], resources: ['exclusive']}]), actions => { actions.register('one@1.0.0', async () => { await waiting; return {}; }); }, [worker('worker', ['run'])]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}), executing = setup.runtime.tick(); await new Promise(resolve => setImmediate(resolve)); setup.runtime.cancel(run.id); assert.equal(setup.runtime.locks.list()[0].runId, run.id); release(); await executing; assert.equal(setup.runtime.ledger.get(run.id)?.status, 'CANCELLED'); assert.equal(setup.runtime.locks.list().length, 0); });
test('cancellation fence is durable before the live abort signal is dispatched',async()=>{let observed:string|undefined;const setup=runtime(job([{id:'one',action:'one@1.0.0',requires:['run']}]),actions=>actions.register('one@1.0.0',async context=>new Promise((_resolve,reject)=>context.signal.addEventListener('abort',()=>{observed=setup.runtime.ledger.get(context.run.id)?.status;reject(new Error('cancelled'));},{once:true}))),[worker('worker',['run'])]);const run=setup.runtime.createRun('job@1.0.0',{}, {type:'manual',actor:'test'}),executing=setup.runtime.tick();await new Promise(resolve=>setImmediate(resolve));setup.runtime.cancel(run.id);await executing;assert.equal(observed,'CANCELLING');assert.equal(setup.runtime.ledger.get(run.id)?.status,'CANCELLED');});
test('production cancellation retains worker and resource protection when owned cleanup cannot be proven', async () => {
  const at = new Date().toISOString(), cleanup: ExecutionCleanupReport = {outcome: 'uncertain', reason: 'execution_cancelled', requestedAt: at, completedAt: at, processes: [{identity: {pid: 101, platform: process.platform, startedAtToken: 'captured-start', capturedAt: at}, outcome: 'uncertain', reason: 'execution_cancelled', signals: ['test-termination'], requestedAt: at, verifiedAt: at, detail: 'termination_completed_but_verification_unavailable'}]};
  const ownedExecution: OwnedExecution = {activePids: () => [101], terminateAll: async () => cleanup, runProcess: async (_request, signal) => new Promise((_resolve, reject) => signal?.addEventListener('abort', () => reject(new Error('execution_cancelled')), {once: true}))};
  const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], resources: ['exclusive']}]), actions => actions.register('one@1.0.0', async context => { await context.ownedExecution.runProcess({command: process.execPath}, context.signal); return {}; }), [worker('worker', ['run'])]);
  const governed = new JobRuntime(setup.catalog, setup.actions, setup.workers, setup.runtime.ledger, setup.runtime.artifacts, setup.runtime.locks, {approval: () => true, ownedExecutionFactory: () => ownedExecution});
  const run = governed.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}), executing = governed.tick(); await new Promise(resolve => setImmediate(resolve)); governed.cancel(run.id); await executing;
  const retained = governed.ledger.get(run.id)!; assert.equal(retained.status, 'CLEANUP_UNCERTAIN'); assert.equal(retained.steps[0].status, 'CLEANUP_UNCERTAIN'); assert.equal(retained.steps[0].cleanup?.outcome, 'uncertain'); assert.equal(setup.workers.list()[0].active, 1); assert.equal(setup.runtime.locks.list()[0].runId, run.id);
});
test('late cancellation cannot overwrite a successful terminal run', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run']}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', ['run'])]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const endedAt = setup.runtime.ledger.get(run.id)?.endedAt; assert.equal(setup.runtime.cancel(run.id).status, 'SUCCEEDED'); assert.equal(setup.runtime.ledger.get(run.id)?.endedAt, endedAt); assert.equal(setup.runtime.ledger.get(run.id)?.errors.length, 0); });

test('normal production Job execution creates and links a genuine execution session', async () => {
  const setup = runtime(job([{id: 'inspect', action: 'repository.inspect@1.0.0', requires: ['run'], verification: ['process-output']}]), actions => actions.register('repository.inspect@1.0.0', async context => { const result = await context.ownedExecution.runProcess({command: process.execPath, args: ['-e', "process.stdout.write('REAL_JOB_OUTPUT\\n')"]}, context.signal); return {verification: result.exitCode === 0 ? ['process-output'] : [], detail: 'real process completed'}; }), [worker('worker', ['run'])]);
  const sessions = new ExecutionSessionRuntime(path.join(setup.root, 'execution-sessions'));
  const governed = new JobRuntime(setup.catalog, setup.actions, setup.workers, setup.runtime.ledger, setup.runtime.artifacts, setup.runtime.locks, {approval: () => true, executionSessions: sessions});
  const run = governed.createRun('job@1.0.0', {}, {type: 'manual', actor: 'operator', parcelContext: {schema: 'agent-control.run-parcel-context/v1', parcelId: 'parcel:production', stageId: 'stage:inspect', originalGoal: 'Inspect the repository', currentInterpretation: 'Run the bounded inspection', effectiveInstructions: [], constraints: [], successCriteria: [], baton: null}});
  await governed.tick(); const complete = governed.ledger.get(run.id)!, sessionId = complete.steps[0].attempts[0].executionSessionIds?.[0];
  assert.equal(complete.status, 'SUCCEEDED'); assert.ok(sessionId); assert.ok(complete.provenance.some(item => item.type === 'execution-session' && item.detail === sessionId));
  const session = sessions.get(sessionId!); assert.equal(session.scope.runId, run.id); assert.equal(session.scope.parcelId, 'parcel:production'); assert.equal(session.scope.jobId, 'job'); assert.equal(session.scope.stepId, 'inspect'); assert.equal(session.scope.workerId, 'worker'); assert.equal(session.scope.crewRole, 'parcel-coordinator'); assert.equal(session.capabilities.terminal, 'pipe'); assert.equal(session.capabilities.modes.watch, true); assert.equal(session.capabilities.modes.intervene, false); assert.equal(session.state, 'EXITED'); assert.match(sessions.transcript(session.id), /REAL_JOB_OUTPUT/);
});
test('replace-running links both attempts and keeps the cancelled attempt visible until cleanup is confirmed', async () => { let release!: () => void; const waiting = new Promise<void>(resolve => { release = resolve; }); const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run']}], {concurrency: 'replace-running'}), actions => actions.register('one@1.0.0', async () => { await waiting; return {}; }), [worker('worker', ['run'])]); const first = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}), executing = setup.runtime.tick(); await new Promise(resolve => setImmediate(resolve)); const replacement = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); assert.equal(setup.runtime.ledger.get(first.id)?.lineage?.replacedByRunId, replacement.id); assert.equal(replacement.lineage?.replacesRunId, first.id); assert.equal(setup.runtime.ledger.get(first.id)?.status, 'CANCELLING'); release(); await executing; assert.equal(setup.runtime.ledger.get(first.id)?.status, 'CANCELLED'); assert.equal(setup.runtime.ledger.list('job').some(item => item.id === first.id), true); });
test('timeout finalizes a retained running efficiency invocation', async () => { const efficiency = new MemoryHarnessEfficiencyLedger(); const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], timeoutSeconds: 1}]), actions => actions.register('one@1.0.0', async context => { efficiency.record(createInvocationStart({jobId: context.run.jobId, runId: context.run.id, stepId: context.step.id, taskId: `${context.run.id}:${context.step.id}`, laneId: `job:${context.run.id}`, model: 'configured-model', provider: 'configured-provider', harnessProfile: 'STANDARD', executionStrategy: 'fixture', startedAt: new Date().toISOString(), recipeFingerprint: 'fixture-timeout'})); return new Promise((_resolve, reject) => context.signal.addEventListener('abort', () => reject(new Error('step_timeout')), {once: true})); }), [worker('worker', ['run'])], undefined, undefined, efficiency); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const invocation = efficiency.list()[0]; assert.equal(setup.runtime.ledger.get(run.id)?.status, 'FAILED'); assert.equal(invocation.state, 'TIMED_OUT'); assert.equal(invocation.verifierResult, 'FAIL'); assert.equal(invocation.finalJobResult, 'FAILED'); assert.equal(invocation.finishReason, 'step_timeout'); });
test('executor error after partial telemetry finalizes rather than leaving UNKNOWN', async () => { const efficiency = new MemoryHarnessEfficiencyLedger(); const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run']}]), actions => actions.register('one@1.0.0', async context => { const id = efficiency.record(createInvocationStart({jobId: context.run.jobId, runId: context.run.id, stepId: context.step.id, taskId: `${context.run.id}:${context.step.id}`, laneId: `job:${context.run.id}`, model: 'configured-model', provider: 'configured-provider', harnessProfile: 'STANDARD', executionStrategy: 'fixture', startedAt: new Date().toISOString(), recipeFingerprint: 'fixture-error'})); const error = new Error('executor_broke_after_response'); Object.assign(error, {efficiencyInvocationIds: [id]}); throw error; }), [worker('worker', ['run'])], undefined, undefined, efficiency); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const invocation = efficiency.list()[0]; assert.equal(invocation.state, 'FAILED'); assert.equal(invocation.verifierResult, 'FAIL'); assert.equal(invocation.finalJobResult, 'FAILED'); assert.match(invocation.error ?? '', /executor_broke_after_response/); });
test('scheduled and manual triggers share createRun and missed skip is visible without backfill', async () => { let instant = new Date('2026-08-24T06:00:00Z'); const schedule: ScheduleDefinition = {apiVersion: 'agent-control/v1', kind: 'Schedule', metadata: {id: 'daily', name: 'Daily'}, spec: {enabled: true, job: 'job@1.0.0', cron: '0 7 * * *', timezone: 'Europe/London', missedRunPolicy: 'skip'}}; const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: []}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', [])], schedule, () => instant); setup.runtime.setScheduleEnabled('daily', true); instant = new Date('2026-08-25T08:00:00Z'); const created = await setup.runtime.tickSchedules(instant); assert.equal(created.length, 0); assert.equal(setup.runtime.ledger.schedule('daily')?.missedCount, 1); assert.equal(setup.runtime.ledger.list()[0].status, 'MISSED'); const manual = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); assert.equal(manual.steps.length, 1); });
test('a due schedule creates exactly one Run and its next time survives ledger restart', async () => { const instant = new Date('2026-08-24T06:00:00Z'), schedule: ScheduleDefinition = {apiVersion: 'agent-control/v1', kind: 'Schedule', metadata: {id: 'daily', name: 'Daily'}, spec: {enabled: true, job: 'job@1.0.0', cron: '0 7 * * *', timezone: 'Europe/London', missedRunPolicy: 'run-once-immediately'}}; const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: []}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', [])], schedule, () => instant); const state = setup.runtime.ledger.saveSchedule({scheduleId: 'daily', enabled: true, nextScheduledAt: instant.toISOString(), missedCount: 0, updatedAt: instant.toISOString()}); assert.equal(state.enabled, true); assert.equal((await setup.runtime.tickSchedules(instant)).length, 1); assert.equal((await setup.runtime.tickSchedules(instant)).length, 0); const restored = new RunLedger(path.join(setup.root, 'ledger.json')); assert.notEqual(restored.schedule('daily')?.nextScheduledAt, instant.toISOString()); });

test('provider credential echoes cannot survive artifact, run, event or exception persistence', async t => {
  const credential = ['nvapi', 'fixture', 'J'.repeat(24)].join('-');
  const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], outputs: [{name: 'result', type: 'application/json', schema: 'result/v1', version: '1.0.0'}]}]), actions => actions.register('one@1.0.0', async () => {
    const error = new ActionFailure(`upstream echoed ${credential}`, 'execution');
    Object.assign(error, {partialActionOutput: {artifacts: [{name: 'result', value: {providerError: `echo ${credential}`}}]}});
    throw error;
  }), [worker('worker', ['run'])]);
  t.after(() => fs.rmSync(setup.root, {recursive: true, force: true}));
  const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'});
  await setup.runtime.tick();
  const record = setup.runtime.ledger.get(run.id)!;
  assert.equal(JSON.stringify(record).includes(credential), false);
  assert.match(JSON.stringify(record), /REDACTED/);
  const artifact = setup.runtime.artifacts.list(run.id)[0];
  assert.equal(JSON.stringify(setup.runtime.artifacts.read(artifact.id)).includes(credential), false);
  for (const file of [path.join(setup.root, 'ledger.json'), path.join(setup.root, 'run-events.jsonl'), path.join(setup.root, 'artifacts', 'artifacts.json'), artifact.storageRef]) {
    assert.equal(fs.readFileSync(file, 'utf8').includes(credential), false, file);
  }
});
test('one invalid due schedule is contained and does not block another due schedule', async () => { const instant = new Date('2026-08-24T07:00:00Z'), first: ScheduleDefinition = {apiVersion: 'agent-control/v1', kind: 'Schedule', metadata: {id: 'invalid', name: 'Invalid'}, spec: {enabled: true, job: 'job@1.0.0', cron: '0 7 * * *', timezone: 'Europe/London', missedRunPolicy: 'run-once-immediately'}}, second: ScheduleDefinition = {...first, metadata: {id: 'valid', name: 'Valid'}}; const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: []}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', [])], first, () => instant); setup.catalog.addSchedule(second); setup.catalog.job('job@1.0.0')!.spec.enabled = false; for (const id of ['invalid', 'valid']) setup.runtime.ledger.saveSchedule({scheduleId: id, enabled: true, nextScheduledAt: instant.toISOString(), missedCount: 0, updatedAt: instant.toISOString()}); const originalCreate = setup.runtime.createRun.bind(setup.runtime); let calls = 0; setup.runtime.createRun = ((...args: Parameters<JobRuntime['createRun']>) => { calls++; if (calls === 1) throw new Error('malformed_scheduled_operation'); setup.catalog.job('job@1.0.0')!.spec.enabled = true; return originalCreate(...args); }) as JobRuntime['createRun']; const created = await setup.runtime.tickSchedules(instant); assert.equal(created.length, 1); assert.equal(setup.runtime.ledger.schedule('invalid')?.lastError, 'malformed_scheduled_operation'); assert.equal(created[0].trigger.id, 'valid'); });
test('a disabled scheduled job records failure and advances instead of rejecting', async () => { const instant = new Date('2026-08-24T07:00:00Z'), schedule: ScheduleDefinition = {apiVersion: 'agent-control/v1', kind: 'Schedule', metadata: {id: 'disabled', name: 'Disabled'}, spec: {enabled: true, job: 'job@1.0.0', cron: '0 7 * * *', timezone: 'Europe/London', missedRunPolicy: 'run-once-immediately'}}, setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: []}], {enabled: false}), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', [])], schedule, () => instant); setup.runtime.ledger.saveSchedule({scheduleId: 'disabled', enabled: true, nextScheduledAt: instant.toISOString(), missedCount: 0, updatedAt: instant.toISOString()}); assert.deepEqual(await setup.runtime.tickSchedules(instant), []); const state = setup.runtime.ledger.schedule('disabled')!; assert.equal(state.lastError, 'job_disabled'); assert.notEqual(state.nextScheduledAt, instant.toISOString()); });
test('artifact store detects post-write corruption before downstream consumption', () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: []}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', [])]), run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}), artifact = setup.runtime.artifacts.create(run, 'one', 'worker', {name: 'data', type: 'application/json', schema: 'data/v1', version: '1.0.0'}, {safe: true}); fs.writeFileSync(artifact.storageRef, '{}'); assert.throws(() => setup.runtime.artifacts.read(artifact.id), /artifact_checksum_mismatch/); });
test('restart recovery fails closed and retains Git-independent ledger identity and locks', () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], resources: ['repo']}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', ['run'])]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}), changed = setup.runtime.ledger.get(run.id)!; changed.status = 'RUNNING'; changed.steps[0].status = 'RUNNING'; setup.runtime.ledger.update(changed); setup.runtime.locks.acquire(['repo'], run.id, 'one'); const restored = new RunLedger(path.join(setup.root, 'ledger.json')); assert.deepEqual(restored.recoverFailClosed(), [run.id]); assert.equal(restored.get(run.id)?.status, 'DISCONNECTED'); assert.equal(new ResourceLockManager(path.join(setup.root, 'locks.json')).list()[0].runId, run.id); });

function processAlive(pid: number) { try { process.kill(pid, 0); return true; } catch { return false; } }
async function waitForProcessExit(pid: number, timeoutMs = 2500) { const deadline = Date.now() + timeoutMs; while (Date.now() < deadline && processAlive(pid)) await new Promise(resolve => setTimeout(resolve, 25)); return !processAlive(pid); }

test('step timeout permits fast success without erroneous termination', async () => {
  const setup = runtime(job([{id: 'fast', action: 'fast@1.0.0', requires: ['run'], timeoutSeconds: 1}]), actions => actions.register('fast@1.0.0', async () => ({detail: 'fast-success'})), [worker('worker', ['run'])]);
  const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick();
  const result = setup.runtime.ledger.get(run.id)!; assert.equal(result.status, 'SUCCEEDED'); assert.equal(result.steps[0].status, 'SUCCEEDED'); assert.equal(result.steps[0].attempts[0].terminalReason, undefined); assert.equal(setup.workers.list()[0].active, 0);
});

test('step timeout terminates its direct child, records evidence, releases resources and permits lane reuse', async () => {
  const pidFile = path.join(os.tmpdir(), `agent-control-owned-child-${process.pid}.txt`); let calls = 0;
  const setup = runtime(job([{id: 'owned', action: 'owned@1.0.0', requires: ['run'], resources: ['exclusive'], timeoutSeconds: 1}], {concurrency: 'allow'}), actions => actions.register('owned@1.0.0', async context => {
    calls++; if (calls > 1) return {detail: 'lane-reused'};
    await context.ownedExecution.runProcess({command: process.execPath, args: ['-e', `require('node:fs').writeFileSync(${JSON.stringify(pidFile)},String(process.pid));setInterval(()=>{},1000)`]}, context.signal);
    return {};
  }), [worker('worker', ['run'])]);
  try {
    const started = Date.now(), run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const elapsed = Date.now() - started;
    const result = setup.runtime.ledger.get(run.id)!, attempt = result.steps[0].attempts[0], childPid = Number(fs.readFileSync(pidFile, 'utf8'));
    assert.equal(result.status, 'FAILED'); assert.equal(result.steps[0].status, 'TIMED_OUT'); assert.equal(attempt.timeoutSeconds, 1); assert.equal(attempt.terminalReason, 'step_timeout'); assert.ok((attempt.elapsedMs ?? 0) >= 900); assert.ok(elapsed < 4000); assert.equal(await waitForProcessExit(childPid), true);
    assert.equal(setup.workers.list()[0].active, 0); assert.equal(setup.runtime.locks.list().length, 0);
    const events = fs.readFileSync(path.join(setup.root, 'run-events.jsonl'), 'utf8').trim().split('\n').map(line => JSON.parse(line));
    const timeout = events.find(event => event.type === 'step.timed_out'); assert.deepEqual({jobId: timeout.evidence.jobId, stepId: timeout.evidence.stepId, timeoutSeconds: timeout.evidence.timeoutSeconds, terminalReason: timeout.evidence.terminalReason}, {jobId: 'job', stepId: 'owned', timeoutSeconds: 1, terminalReason: 'step_timeout'}); assert.ok(timeout.evidence.elapsedMs >= 900);
    const retry = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); assert.equal(setup.runtime.ledger.get(retry.id)?.status, 'SUCCEEDED'); assert.equal(setup.workers.list()[0].active, 0); assert.equal(setup.runtime.locks.list().length, 0);
  } finally { fs.rmSync(pidFile, {force: true}); }
});

test('step timeout terminates the owned process group including descendants', {skip: process.platform === 'win32'}, async () => {
  const pidFile = path.join(os.tmpdir(), `agent-control-owned-tree-${process.pid}.txt`);
  const setup = runtime(job([{id: 'tree', action: 'tree@1.0.0', requires: ['run'], timeoutSeconds: 1}]), actions => actions.register('tree@1.0.0', async context => {
    const script = '(sleep 30) & grandchild=$!; printf "%s %s" "$$" "$grandchild" > "$1"; wait "$grandchild"';
    await context.ownedExecution.runProcess({command: 'bash', args: ['-c', script, 'owned-tree', pidFile]}, context.signal); return {};
  }), [worker('worker', ['run'])]);
  try {
    const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick();
    const [parentPid, grandchildPid] = fs.readFileSync(pidFile, 'utf8').split(' ').map(Number); assert.equal(setup.runtime.ledger.get(run.id)?.steps[0].status, 'TIMED_OUT'); assert.equal(await waitForProcessExit(parentPid), true); assert.equal(await waitForProcessExit(grandchildPid), true);
  } finally { fs.rmSync(pidFile, {force: true}); }
});
test('worker registry explains protected-workload capability fencing without hiding safe inspection', () => { const registry = new WorkerRegistry(); registry.register(worker('managed', ['compute.intensive', 'managed-node.inspect'], 'healthy', {blockedCapabilities: ['compute.intensive']})); assert.match(registry.resolve(['compute.intensive']).rationale.rejected[0].reasons.join(','), /workload_blocked:compute\.intensive/); assert.equal(registry.resolve(['managed-node.inspect']).worker?.id, 'managed'); });

test('production Job dispatch consults runtime safety, waits for approval, then resumes the same governed action', async () => {
  let calls = 0; const setup = runtime(job([{id: 'remove', action: 'repository.delete@1.0.0', requires: ['repository.write']}], {parameters: {repoPath: {type: 'string', required: true}}}), actions => actions.registerConsequentialControl('repository.delete@1.0.0', async () => { calls++; return {}; }, ['REPOSITORY_WRITE', 'DESTRUCTIVE']), [worker('worker', ['repository.write'])]), repository = path.join(setup.root, 'project'); fs.mkdirSync(repository);
  const safety = new RuntimeSafetySupervisor({id: 'job-safety', approvedRepositoryRoots: [repository]}, path.join(setup.root, 'safety.json'));
  const trustedWorkers = WorkerRegistry.fromConfig([{id: 'worker', platform: 'linux', transport: {type: 'local'}, capabilities: ['repository.write']}]); trustedWorkers.setHealth('worker', 'healthy');
  const governed = new JobRuntime(setup.catalog, setup.actions, trustedWorkers, setup.runtime.ledger, setup.runtime.artifacts, setup.runtime.locks, {approval: () => false, safety}), run = governed.createRun('job@1.0.0', {repoPath: repository}, {type: 'manual', actor: 'operator'});
  await governed.tick(); const waiting = governed.ledger.get(run.id)!; assert.equal(waiting.status, 'WAITING'); assert.equal(waiting.steps[0].status, 'WAITING_FOR_APPROVAL'); assert.equal(calls, 0);
  const approval = waiting.steps[0].approval!; governed.approve(run.id, approval, 'operator'); await governed.tick();
  assert.equal(governed.ledger.get(run.id)?.status, 'SUCCEEDED'); assert.equal(calls, 1); assert.equal(safety.list()[0].outcome, 'ALLOW_WITH_AUDIT'); assert.ok(governed.ledger.get(run.id)?.provenance.some(item => item.type === 'runtime-safety'));
});

test('production Job dispatch fails closed before an out-of-scope action handler runs', async () => {
  let calls = 0; const setup = runtime(job([{id: 'write', action: 'repository.write@1.0.0', requires: ['repository.write']}], {parameters: {repoPath: {type: 'string', required: true}}}), actions => actions.registerConsequentialControl('repository.write@1.0.0', async () => { calls++; return {}; }, ['REPOSITORY_WRITE']), [worker('worker', ['repository.write'])]), approved = path.join(setup.root, 'approved'); fs.mkdirSync(approved); fs.mkdirSync(path.join(setup.root, 'forbidden'));
  const safety = new RuntimeSafetySupervisor({id: 'job-safety', approvedRepositoryRoots: [approved]}, path.join(setup.root, 'safety.json'));
  const governed = new JobRuntime(setup.catalog, setup.actions, setup.workers, setup.runtime.ledger, setup.runtime.artifacts, setup.runtime.locks, {safety}), run = governed.createRun('job@1.0.0', {repoPath: path.join(approved, '..', 'forbidden')}, {type: 'manual', actor: 'operator'});
  await governed.tick(); const failed = governed.ledger.get(run.id)!;
  assert.equal(failed.status, 'FAILED'); assert.equal(failed.steps[0].status, 'FAILED'); assert.match(failed.steps[0].error ?? '', /runtime_safety_denied/); assert.equal(calls, 0); assert.equal(safety.list()[0].outcome, 'DENY');
});

test('managed-node disruptive maintenance has a bounded step timeout',()=>{const source=fs.readFileSync(path.resolve('config/jobs/managed-node-maintenance.job.yaml'),'utf8');assert.match(source,/approval: managed-node\.protected-workload-override\s+timeoutSeconds: 300/);});

test('reference workflow retains discovery artifact while publisher is unavailable then resumes across workers', async () => {
  const actions = registerReferenceActions(); registerBrowserActions(actions); registerProtectedResourceModelActions({} as AgentControlConfig, undefined, undefined, actions);
  actions.register('managed-node.inspect@1.0.0', async () => ({})); actions.register('managed-node.maintain@1.0.0', async () => ({}));
  const catalog = new JobCatalog(actions.ids()).loadDirectory(path.resolve('config/jobs')), root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-control-events-')), workers = new WorkerRegistry(); workers.register(worker('mobile', ['browser.mobile', 'facebook.authenticated'])); workers.register(worker('publisher', ['localwalks.publisher', 'node', 'git', 'production-access'], 'offline')); workers.register(worker('observer', ['network.read']));
  const runtime = new JobRuntime(catalog, actions, workers, new RunLedger(path.join(root, 'ledger.json')), new ArtifactStore(path.join(root, 'artifacts')), new ResourceLockManager(path.join(root, 'locks.json')), {approval: () => true}); const run = runtime.createRun('events-refresh-qualification@1.0.0', {}, {type: 'manual', actor: 'qualification'});
  await runtime.tick(); await runtime.tick(); let state = runtime.ledger.get(run.id)!; assert.equal(state.steps[0].status, 'SUCCEEDED'); assert.equal(state.steps[1].status, 'WAITING_FOR_WORKER'); const artifactId = state.steps[0].artifactIds[0]; workers.setHealth('publisher', 'healthy'); for (let count = 0; count < 5; count++) await runtime.tick(); state = runtime.ledger.get(run.id)!; assert.equal(state.status, 'SUCCEEDED'); assert.equal(state.steps[0].artifactIds[0], artifactId); assert.equal(state.artifacts.length, 5); assert.deepEqual(state.selectedWorkers, ['mobile', 'publisher', 'observer']); assert.match(JSON.stringify(state.provenance), /preserved 3 existing/);
});

for (const mode of ['success','failure','cancel'] as const) for (const throwAt of [1,2]) test('runtime cleanup rejection retains UNKNOWN and durable evidence: '+mode+' sweep '+throwAt, async t => {
 let sweep=0;
 const setup=runtime(job([{id:'one',action:'one@1.0.0',requires:['run'],resources:['exclusive']}]), actions=>actions.register('one@1.0.0',async context=>{context.recordEvidence!('raw-action-attempt',{mode});if(mode==='failure')throw new Error('action-failed');if(mode==='cancel')await new Promise((_resolve,reject)=>context.signal.addEventListener('abort',()=>reject(new Error('cancelled')),{once:true}));return {};}),[worker('worker',['run'])]); t.after(()=>fs.rmSync(setup.root,{recursive:true,force:true}));
 const owned:OwnedExecution={activePids:()=>[],runProcess:async()=>{throw new Error('not used');},terminateAll:async reason=>{if(++sweep===throwAt)throw new Error('cleanup-adapter-rejected');const at=new Date().toISOString();return {outcome:'confirmed',reason:reason??'cleanup',requestedAt:at,completedAt:at,processes:[]};}};
 const governed=new JobRuntime(setup.catalog,setup.actions,setup.workers,setup.runtime.ledger,setup.runtime.artifacts,setup.runtime.locks,{approval:()=>true,ownedExecutionFactory:()=>owned});const run=governed.createRun('job@1.0.0',{}, {type:'manual',actor:'human:test'}),executing=governed.tick();if(mode==='cancel'){await new Promise(resolve=>setImmediate(resolve));governed.cancel(run.id);}await executing;
 const retained=governed.ledger.get(run.id)!;assert.equal(retained.status,'CLEANUP_UNCERTAIN');assert.equal(retained.steps[0].cleanup?.outcome,'uncertain');assert.match(retained.steps[0].cleanup?.reason??'',/cleanup-adapter-rejected/);assert.equal(setup.workers.list()[0].active,1);assert.equal(governed.locks.list()[0].runId,run.id);assert.equal(governed.contracts.get(retained.steps[0].attempts[0].contractId!).process.state,'UNKNOWN');
 const restored=new RunLedger(path.join(setup.root,'ledger.json'));assert.equal(restored.get(run.id)?.status,'CLEANUP_UNCERTAIN');const artifacts=new ArtifactStore(path.join(setup.root,'artifacts'));const names=artifacts.list(run.id).map(a=>a.name);assert.ok(names.includes('raw-action-attempt'));assert.ok(names.includes('runtime-cleanup-error'));
});

test('reacquiring an UNKNOWN retained resource cannot erase its durable hold',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'retained-lock-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'locks.json'),locks=new ResourceLockManager(file);locks.acquire(['resource'],'run','step',true);const restored=new ResourceLockManager(file);restored.acquire(['resource'],'run','step');assert.equal(restored.list()[0].retained,true);restored.release('run');assert.equal(restored.list().length,1);restored.release('run','step');assert.equal(restored.list().length,0);});

test('retained cleanup recovery is evidence-bound and requires an explicit cancel request',async()=>{
 const setup=runtime(job([{id:'one',action:'one@1.0.0',requires:['run']}]),a=>a.register('one@1.0.0',async c=>{c.retainCleanup!({kind:'test-recovery',target:'fixture'},async()=>({outcome:'uncertain',reason:'fixture',requestedAt:new Date().toISOString(),completedAt:new Date().toISOString(),processes:[]}));throw Error('fixture failure');}),[worker('worker',['run'])]);
 const run=setup.runtime.createRun('job@1.0.0',{}, {type:'manual',actor:'test'});await setup.runtime.tick();for(let i=0;i<100&&setup.runtime.ledger.get(run.id)?.status!=='CLEANUP_UNCERTAIN';i++)await new Promise(r=>setTimeout(r,5));assert.equal(setup.runtime.ledger.get(run.id)?.status,'CLEANUP_UNCERTAIN');
 const registry=new WorkerRegistry();registry.register(worker('worker',['run']));const resumed=new JobRuntime(setup.catalog,setup.actions,registry,setup.runtime.ledger,setup.runtime.artifacts,setup.runtime.locks,{contracts:setup.runtime.contracts});let calls=0;
 resumed.restoreRetainedCleanup('wrong-kind',()=>{throw Error('wrong kind must not bind');});
 resumed.restoreRetainedCleanup('test-recovery',(identity,record,stepId,workerId)=>{assert.equal(identity.target,'fixture');assert.equal(record.id,run.id);assert.equal(stepId,'one');assert.equal(workerId,'worker');return async()=>{calls++;return {outcome:'confirmed',reason:'fixture-proof',requestedAt:new Date().toISOString(),completedAt:new Date().toISOString(),processes:[]};};});assert.equal(calls,0);assert.ok(resumed.locks.list().length);
 resumed.locks.acquire(['fixture-quarantine'],run.id,'one',true);resumed.cancel(run.id);for(let i=0;i<100&&resumed.ledger.get(run.id)?.status!=='CANCELLED';i++)await new Promise(r=>setTimeout(r,5));assert.equal(calls,1);assert.equal(resumed.ledger.get(run.id)?.status,'CANCELLED');assert.equal(resumed.locks.list().length,0);assert.equal(registry.list()[0].active,0);assert.ok(resumed.artifacts.list(run.id).some(a=>a.name==='retained-cleanup-outcome'));
});
