import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {JobCatalog, JobManifestError, effectiveParameters, nextCronOccurrence, validateJobManifest, validateScheduleManifest} from './job-catalog.js';

const action = 'test.action@1.0.0';
const validJob = () => ({apiVersion: 'agent-control/v1', kind: 'Job', metadata: {id: 'test-job', name: 'Test Job', version: '1.0.0'}, spec: {priority: 'normal', concurrency: 'no-overlap', parameters: {count: {type: 'integer', default: 2, minimum: 1}}, steps: [{id: 'first', action, requires: ['node']}, {id: 'second', action, requires: ['git'], dependsOn: ['first']} ]}});

test('valid versioned Job manifest passes JSON Schema and action validation', () => { const job = validateJobManifest(validJob(), new Set([action])); assert.equal(job.metadata.id, 'test-job'); assert.deepEqual(effectiveParameters(job, {count: 4}), {count: 4}); });
test('invalid API version and unknown Action fail closed', () => { const version = validJob(); version.apiVersion = 'agent-control/v2'; assert.throws(() => validateJobManifest(version, new Set([action])), JobManifestError); assert.throws(() => validateJobManifest(validJob(), new Set()), /invalid_action/); });
test('duplicate step IDs, missing dependencies and circular graphs are rejected by canonical manifest validation', () => { const duplicate=validJob();duplicate.spec.steps[1].id='first';assert.throws(()=>validateJobManifest(duplicate,new Set([action])),/duplicate_step_id/);const missing = validJob(); missing.spec.steps[1].dependsOn = ['absent']; assert.throws(() => validateJobManifest(missing, new Set([action])), /invalid_dependency/); const circular = validJob(); circular.spec.steps[0].dependsOn = ['second']; assert.throws(() => validateJobManifest(circular, new Set([action])), /circular_dependency/); const schema=JSON.parse(fs.readFileSync(path.resolve('config/schemas/job-v1.schema.json'),'utf8'));assert.match(schema.properties.spec.properties.steps.$comment,/validateJobManifest enforces unique step IDs/); });
test('typed parameters reject unknown, wrong-type and out-of-range values', () => { const job = validateJobManifest(validJob(), new Set([action])); assert.throws(() => effectiveParameters(job, {extra: true}), /unknown_parameter/); assert.throws(() => effectiveParameters(job, {count: '2'}), /invalid_parameter_type/); assert.throws(() => effectiveParameters(job, {count: 0}), /parameter_out_of_range/); });
test('manifest secret material and unsafe secret values are rejected', () => { const raw = {...validJob(), apiKey: 'forbidden'}; assert.throws(() => validateJobManifest(raw, new Set([action])), /secret_material_forbidden/); const secret: any = validJob(); secret.spec.parameters = {credential: {type: 'string', secretRef: true}}; const job = validateJobManifest(secret, new Set([action])); assert.throws(() => effectiveParameters(job, {credential: 'plaintext-value'}), /invalid_secret_reference/); assert.deepEqual(effectiveParameters(job, {credential: 'APPROVED_SECRET_REF'}), {credential: 'APPROVED_SECRET_REF'}); });
test('catalog loads YAML Jobs before separate Schedule manifests', () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-control-catalog-')); fs.writeFileSync(path.join(dir, 'job.yaml'), `apiVersion: agent-control/v1\nkind: Job\nmetadata:\n  id: yaml-job\n  name: YAML Job\n  version: 1.0.0\nspec:\n  priority: normal\n  concurrency: queue\n  steps:\n    - id: run\n      action: test.action@1.0.0\n      requires: []\n`); fs.writeFileSync(path.join(dir, 'schedule.yaml'), `apiVersion: agent-control/v1\nkind: Schedule\nmetadata:\n  id: daily\n  name: Daily\nspec:\n  job: yaml-job@1.0.0\n  cron: "0 7 * * *"\n  timezone: Europe/London\n  missedRunPolicy: skip\n`); const catalog = new JobCatalog(new Set([action])).loadDirectory(dir); assert.equal(catalog.listJobs().length, 1); assert.equal(catalog.listSchedules()[0].spec.job, 'yaml-job@1.0.0'); fs.rmSync(dir, {recursive: true}); });
test('timezone-aware schedule handles London summer and winter offsets', () => { const schedule = validateScheduleManifest({apiVersion: 'agent-control/v1', kind: 'Schedule', metadata: {id: 'twice', name: 'Twice'}, spec: {job: 'x@1.0.0', cron: '0 7,19 * * *', timezone: 'Europe/London', missedRunPolicy: 'skip'}}); assert.equal(schedule.spec.timezone, 'Europe/London'); assert.equal(nextCronOccurrence(schedule.spec.cron, schedule.spec.timezone, new Date('2026-08-24T05:59:00Z')).toISOString(), '2026-08-24T06:00:00.000Z'); assert.equal(nextCronOccurrence(schedule.spec.cron, schedule.spec.timezone, new Date('2026-12-24T06:59:00Z')).toISOString(), '2026-12-24T07:00:00.000Z'); });
