import type {DigitalWorker,WorkOrder,LabourAttempt,LabourOutcome,LabourEvent} from './labour-types.js';
import {labourHash} from './labour-ledger.js';
/** Pure projection from retained evidence. Retry attribution is a subset, never an extra charge. */
export function labourEconomics(workers:DigitalWorker[],orders:WorkOrder[],attempts:LabourAttempt[],outcomes:LabourOutcome[],events:LabourEvent[]){

  const market=attempts.filter(a=>!a.calibration),marketOrders=orders.filter(o=>!attempts.some(a=>a.workOrderId===o.id&&a.calibration));
  const tenders=events.filter(e=>e.kind==='tender.opened').map(e=>e.data as {workOrderId:string;bids:Array<{workerId:string}>;rejected:Array<{workerId:string}>});
  const summarize=(rows:LabourAttempt[],selected:LabourOutcome[])=>{
    const known=rows.filter(a=>a.execution.resources?.cpuMs!=null),verified=selected.filter(o=>o.state==='COMPLETED');
    return {workOrders:selected.length,verifiedOutcomes:verified.length,attempts:rows.length,firstPassVerified:selected.filter(o=>o.state==='COMPLETED'&&o.attempts.length===1).length,retries:rows.filter(a=>outcomes.some(o=>o.attempts.indexOf(a.id)>0)).length,failedOutcomes:selected.filter(o=>o.state==='FAILED').length,blockedOutcomes:selected.filter(o=>o.state==='BLOCKED').length,rawExecutionCharges:rows.reduce((s,a)=>s+a.rawExecutionCost,0),verificationCharges:rows.reduce((s,a)=>s+a.verificationCost,0),failedAttemptCharges:rows.filter(a=>a.outcome!=='SUCCEEDED').reduce((s,a)=>s+a.totalCost,0),retryAttributableCharges:rows.filter(a=>outcomes.some(o=>o.attempts.slice(0,-1).includes(a.id))).reduce((s,a)=>s+a.totalCost,0),escalationCharges:rows.reduce((s,a)=>s+a.escalationCost,0),totalInternalCharges:rows.reduce((s,a)=>s+a.totalCost,0),meanRawExecutionCharge:rows.length?rows.reduce((s,a)=>s+a.rawExecutionCost,0)/rows.length:null,meanChargesPerVerifiedOutcome:verified.length?rows.reduce((s,a)=>s+a.totalCost,0)/verified.length:null,knownCpuMs:known.reduce((s,a)=>s+a.execution.resources!.cpuMs!,0),measuredCpuIncludingVerifierMs:known.reduce((s,a)=>s+a.execution.resources!.cpuMs!,0)+rows.reduce((s,a)=>s+a.verificationCost,0),unknownCpuAttempts:rows.length-known.length,wallMs:rows.reduce((s,a)=>s+a.latencyMs,0),meanLatencyMs:rows.length?rows.reduce((s,a)=>s+a.latencyMs,0)/rows.length:null,inputTokens:rows.reduce((s,a)=>s+(a.execution.tokens?.input??0),0),outputTokens:rows.reduce((s,a)=>s+(a.execution.tokens?.output??0),0),unknownTokenAttempts:rows.filter(a=>a.execution.tokens==null).length,externalMoney:null,energyJoules:null};
  };
  const payroll=workers.map(w=>{
    const rows=market.filter(a=>a.workerId===w.id),completed=outcomes.filter(o=>rows.some(a=>a.id===o.attempts.at(-1)));
    return {workerId:w.id,organisationId:w.organisationId,backendId:w.backendId,modelConfiguration:w.modelConfiguration,unit:w.rateCard.metering==='cpu-ms'?'CPU_MILLISECONDS':'INTERNAL_CURRENCY_MICROUNITS',workOffered:new Set(tenders.filter(t=>t.bids.some(b=>b.workerId===w.id)||t.rejected.some(b=>b.workerId===w.id)).map(t=>t.workOrderId)).size,eligibleJobs:new Set(tenders.filter(t=>t.bids.some(b=>b.workerId===w.id)).map(t=>t.workOrderId)).size,bidsSubmitted:tenders.reduce((s,t)=>s+t.bids.filter(b=>b.workerId===w.id).length,0),jobsAwarded:rows.length,successfullyCompleted:rows.filter(a=>a.outcome==='SUCCEEDED').length,...summarize(rows,completed)};
  });
  const keys=[...new Set(marketOrders.filter(o=>o.comparison).map(o=>o.organisationId+'|'+o.comparison!.benchmarkHash))];
  const comparisons=keys.map(key=>{
    const selectedOrders=marketOrders.filter(o=>o.comparison&&o.organisationId+'|'+o.comparison.benchmarkHash===key);
    const strategies=['fixed','cheapest','broker'].map(strategy=>{const os=selectedOrders.filter(o=>o.comparison!.strategy===strategy),ids=new Set(os.map(o=>o.id));return {strategy,cases:os.map(o=>o.comparison!.caseId).sort(),...summarize(market.filter(a=>ids.has(a.workOrderId)),outcomes.filter(o=>ids.has(o.workOrderId)))};});
    const contract=(o:WorkOrder)=>labourHash({jobType:o.jobType,input:o.input,verification:o.verification,requiredCapabilities:o.requiredCapabilities,requiredPermissions:o.requiredPermissions,maximumCost:o.maximumCost,maximumAttempts:o.maximumAttempts,scope:o.scope});
    const sameContracts=[...new Set(selectedOrders.map(o=>o.comparison!.caseId))].every(id=>new Set(selectedOrders.filter(o=>o.comparison!.caseId===id).map(contract)).size===1);
    const broker=strategies[2],comparable=sameContracts&&strategies.every(s=>JSON.stringify(s.cases)===JSON.stringify(broker.cases)&&new Set(s.cases).size===s.cases.length&&s.cases.length>0&&s.workOrders===s.cases.length&&s.verifiedOutcomes===s.cases.length&&s.unknownCpuAttempts===0);
    return {key,strategies,classification:comparable?'MEASURED_RESOURCE_COMPARISON':'INCONCLUSIVE_INCOMPLETE_OR_UNMATCHED',monetarySavings:null,resourceDifferences:comparable?strategies.slice(0,2).map(s=>({baseline:s.strategy,cpuMsSaved:s.measuredCpuIncludingVerifierMs-broker.measuredCpuIncludingVerifierMs,percentage:s.measuredCpuIncludingVerifierMs?(s.measuredCpuIncludingVerifierMs-broker.measuredCpuIncludingVerifierMs)/s.measuredCpuIncludingVerifierMs*100:null,wallMsSaved:s.wallMs-broker.wallMs})):[]};
  });
  return {accounting:'INTERNAL_ACCOUNTING_NOT_PAYMENT',payroll,comparisons,totalsByOrganisation:[...new Set(workers.map(w=>w.organisationId))].map(organisationId=>({organisationId,...summarize(market.filter(a=>a.organisationId===organisationId),outcomes.filter(o=>o.organisationId===organisationId&&!attempts.some(a=>a.workOrderId===o.workOrderId&&a.calibration)))})),definitions:{costPerOutcome:'All retained attempt charges divided by verified outcomes; null with no verified outcomes.',retry:'Subset attribution; not added again to total.',resources:'CPU time includes child cold load and inference; no conversion to currency or energy.',calibration:'Excluded from payroll and comparison; retained in full ledger.',latency:'Sum of measured attempt wall time including cleanup; not elapsed batch makespan.'}};
}
