import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {WorkBoardRuntime} from './work-board.js';
import {ModelImprovementRuntime,createImprovementScope,freezeImprovementBaseline,improvementSha256,type ImprovementMetric,type TrainingExample} from './model-improvement.js';
import {FilePromptInterventionAdapter,createPromotionProposal,interventionSha256,type InterventionAdapter} from './model-intervention.js';

const h=(value:string)=>improvementSha256(value);
const clock=()=>{let n=0;return()=>new Date(Date.UTC(2026,8,19,12,0,n++)).toISOString();};
const baseline=()=>freezeImprovementBaseline({model:{id:'student',version:'1',sha256:h('model')},runtime:{id:'llama.cpp',version:'1',sha256:h('runtime')},parameters:{temperature:0,seed:7},contextSha256:h('context'),promptSha256:h('prompt'),benchmark:{id:'frozen',version:'1',sha256:h('benchmark')},evaluator:{id:'exact',version:'1',sha256:h('evaluator')},hardware:{nodeId:'node-a',deviceIds:['gpu-a'],resourceSnapshotSha256:h('resources')}},'2026-09-19T12:00:00.000Z');
const scope=()=>createImprovementScope({workspace:'/work/experiment',candidateRoot:'/work/experiment/candidate',datasetRoot:'/work/experiment/dataset',nodeIds:['node-a'],runtimeIds:['llama.cpp'],modelIds:['student','teacher'],maximum:{runtimeMs:60_000,cpuPercent:100,ramBytes:1_000_000,gpuPercent:100,vramBytes:1_000_000,diskBytes:1_000_000,networkBytes:0,externalEffects:0},createdAt:'2026-09-19T12:00:00.000Z'});
const available=(name:string,value:number):ImprovementMetric=>({name,value,unit:'score',direction:'HIGHER_IS_BETTER',authority:'MEASURED',evidence:[`metric:${name}`]});
const unavailable=(name:string):ImprovementMetric=>({name,value:null,unit:'unavailable',direction:'LOWER_IS_BETTER',authority:'UNAVAILABLE',evidence:[]});
function setup(file?:string){const runtime=new ModelImprovementRuntime(file,clock());runtime.setMode('REQUIRE_PROMOTION_APPROVAL');const opportunity=runtime.observe({model:{id:'student',version:'1',sha256:h('model'),runtimeId:'llama.cpp'},weakness:'Fails exact transform',evidenceReferences:['attempt:1','attempt:2'],frequency:2,baselineReferences:['batch:baseline'],options:[{level:'PROMPT',expectedBenefit:'Clarify format',estimatedCost:[unavailable('cost')]}],proposedExperiment:'Compare exact output'});return{runtime,opportunity};}
function proposed(file?:string,board?:WorkBoardRuntime){const{runtime,opportunity}=setup(file);const experiment=runtime.propose({opportunityId:opportunity.id,baseline:baseline(),selected:'PROMPT',considered:['DETERMINISTIC_REMOVAL','PROMPT'],reason:'Cheapest viable intervention after deterministic removal was inapplicable',teacherModelIds:['teacher'],scope:scope(),actor:'operator',workBoard:board,requirements:{nodes:['node-a'],minimumRamBytes:1024}});return{runtime,opportunity,experiment};}
function candidate(runtime:ModelImprovementRuntime,id:string){runtime.approve(id,{actor:'operator',reason:'Bounded experiment approved',evidence:['approval:1']});runtime.beginCandidate(id,{actor:'worker',reason:'Begin isolated candidate'});const example:TrainingExample={schema:'agent-control.training-example/v1',id:'example-1',inputSha256:h('in'),outputSha256:h('out'),source:{kind:'SYNTHETIC_TEACHER',reference:'invocation:teacher-1',sha256:h('source')},teacher:{modelId:'teacher',version:'1',invocationId:'teacher-1'},containsSensitiveData:false,decision:'ACCEPTED',reviewReason:'Exact validator passed',evidence:['validator:pass']};runtime.addTrainingExample(id,example);return runtime.createCandidate(id,{configurationSha256:h('config'),adapterSha256:null,resultSha256:h('result'),runtime:{id:'llama.cpp',version:'1'},tools:[{id:'prompt-compiler',version:'1'}],teachers:[{modelId:'teacher',version:'1',invocationIds:['teacher-1']}],actor:'worker',reason:'Prompt candidate materialized',evidence:['artifact:result']});}
function promotable(runtime:ModelImprovementRuntime,id:string){const created=candidate(runtime,id);runtime.beginBenchmark(id,{actor:'worker',reason:'Frozen benchmark',evidence:['batch:1']});runtime.recordSecurity(id,{passed:true,actor:'security-worker',reason:'No findings',evidence:['security:pass']});runtime.recordRegression(id,{baseline:[available('quality',.5)],candidate:[available('quality',.8)],protectedRegressions:[],actor:'independent-evaluator',reason:'Protected suite passed',evidence:['regression:pass']});runtime.completeComparison(id,{decision:'PROMOTE',reason:'Measured improvement with no protected regression',oneTimeCost:[unavailable('cost')],perJobSaving:unavailable('saving'),evidence:['comparison:1'],actor:'independent-evaluator'});return created;}
function promptFixture(runtime:ModelImprovementRuntime,id:string,candidateSha256:string,root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-prompt-')),quarantined=()=>false){const stateFile=path.join(root,'prompt-state.json'),protectedFile=path.join(root,'protected.txt');fs.writeFileSync(stateFile,JSON.stringify({schema:'agent-control.prompt-interventions/v1',routes:{qualification:{prompt:'Return compact output',candidateSha256:null,experimentId:null,updatedAt:'2026-09-19T12:00:00.000Z'}}},null,2));fs.writeFileSync(protectedFile,'protected service identity');const previous={prompt:'Return compact output',candidateSha256:null,experimentId:null},proposed={prompt:'Return the exact value with a vertical bar separator',candidateSha256,experimentId:id};const proposal=createPromotionProposal({experimentId:id,baselineSha256:runtime.projection().experiments.find(item=>item.id===id)!.baseline.sha256,candidateSha256,interventionKind:'PROMPT',target:{id:'qualification',workload:'frozen-two-case',route:'qwen-qualification'},intendedEffect:'Apply the candidate prompt only to the disposable qualification route',previousState:previous,proposedState:proposed,affectedConfigurationReference:`file:${path.resolve(stateFile)}#qualification`,rollbackPlan:'Restore the exact sealed previous prompt state',candidateEvidence:['candidate:pass'],securityEvidence:['security:pass'],regressionEvidence:['regression:pass'],approvalRequirement:'model-improvement-promotion'},'2026-09-19T12:30:00.000Z');const adapter=new FilePromptInterventionAdapter(stateFile,['qualification'],()=>({protectedSha256:interventionSha256(fs.readFileSync(protectedFile))}),quarantined,clock());return{proposal,adapter,stateFile,protectedFile,previous,proposed,root};}

test('opportunity requires repeated evidence and analysis mode cannot create candidates',()=>{const runtime=new ModelImprovementRuntime(undefined,clock());runtime.setMode('ANALYSE_ONLY');assert.throws(()=>runtime.observe({model:{id:'m',version:'1',sha256:h('m'),runtimeId:'r'},weakness:'x',evidenceReferences:['one'],frequency:1,baselineReferences:['b'],options:[],proposedExperiment:'x'}),/evidence_threshold/);const opportunity=runtime.observe({model:{id:'m',version:'1',sha256:h('m'),runtimeId:'r'},weakness:'x',evidenceReferences:['one','two'],frequency:2,baselineReferences:['b'],options:[],proposedExperiment:'x'});assert.throws(()=>runtime.propose({opportunityId:opportunity.id,baseline:baseline(),selected:'PROMPT',considered:['PROMPT'],reason:'x',scope:scope(),actor:'a'}),/analysis_only/);});

test('baseline and candidate identities reject mutation on restart',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-improve-')),file=path.join(root,'state.json');const{runtime,experiment}=proposed(file);candidate(runtime,experiment.id);const raw=JSON.parse(fs.readFileSync(file,'utf8'));raw.experiments[0].baseline.parameters.temperature=1;fs.writeFileSync(file,JSON.stringify(raw));assert.throws(()=>new ModelImprovementRuntime(file),/baseline_identity_mismatch/);});

test('teacher evidence cannot become authority and sensitive examples are excluded',()=>{const{runtime,experiment}=proposed();runtime.approve(experiment.id,{actor:'operator',reason:'approve',evidence:['approval']});runtime.beginCandidate(experiment.id,{actor:'worker',reason:'begin'});const common={schema:'agent-control.training-example/v1' as const,id:'example',inputSha256:h('i'),outputSha256:h('o'),source:{kind:'SYNTHETIC_TEACHER' as const,reference:'teacher:1',sha256:h('s')},containsSensitiveData:false,decision:'ACCEPTED' as const,reviewReason:'validated',evidence:['validator']};assert.throws(()=>runtime.addTrainingExample(experiment.id,common),/teacher_provenance_required/);assert.throws(()=>runtime.addTrainingExample(experiment.id,{...common,teacher:{modelId:'teacher',version:'1',invocationId:'i'},containsSensitiveData:true}),/sensitive_training_data_forbidden/);});

test('work board stages use existing lanes and gate promotion and rollback',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-board-')),boards=new WorkBoardRuntime(path.join(root,'boards.json'),clock());const{experiment}=proposed(undefined,boards),board=boards.get(experiment.workBoardId!);assert.equal(board.items.length,12);assert.equal(board.items.find(item=>item.title==='Security validation')?.parallelismPolicy,'ALLOW_SAFE');assert.deepEqual(board.items.find(item=>item.title==='Prepare and approve promotion')?.requiredApprovals,['model-improvement-promotion']);assert.deepEqual(board.items.find(item=>item.title==='Approve and apply rollback')?.requiredApprovals,['model-improvement-rollback']);assert.equal(board.items.find(item=>item.title==='Apply intervention')?.dependencies.length,1);});

test('candidate requires sealed approval applied effect and verified rollback receipts',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-promote-')),file=path.join(root,'state.json'),{runtime,experiment}=proposed(file),created=promotable(runtime,experiment.id),fixture=promptFixture(runtime,experiment.id,created.candidate!.sha256,root);runtime.requestPromotion(experiment.id,{actor:'operator',reason:'Review requested',evidence:['comparison:1'],proposal:fixture.proposal});assert.equal(runtime.projection().experiments[0]?.state,'AWAITING_PROMOTION_APPROVAL');const approved=runtime.decidePromotion(experiment.id,{approved:true,actor:'human-approver',reason:'Exact sealed effect approved',evidence:['decision:1'],candidateSha256:created.candidate!.sha256,proposalSha256:fixture.proposal.sha256});assert.equal(approved.state,'PROMOTION_APPROVED');assert.equal(approved.promotion.appliedEffectReceipt,null);const promoted=runtime.applyPromotion(experiment.id,fixture.adapter,{actor:'intervention-worker',reason:'Apply exact approved prompt'});assert.equal(promoted.state,'PROMOTED');assert.equal(promoted.promotion.appliedEffectReceipt?.result,'VERIFIED');const restarted=new ModelImprovementRuntime(file,clock());assert.equal(restarted.projection().experiments[0]?.state,'PROMOTED');assert.ok(restarted.projection().experiments[0]?.promotion.appliedEffectReceipt);restarted.proposeRollback(experiment.id,{actor:'operator',reason:'Qualification rollback',approvalRequirement:'model-improvement-rollback'});const rolled=restarted.applyRollback(experiment.id,fixture.adapter,{actor:'intervention-worker',reason:'Restore exact prior state',approvalEvidence:['rollback-approval:1']});assert.equal(rolled.state,'ROLLED_BACK');assert.equal(rolled.promotion.rollbackReceipt?.result,'VERIFIED');assert.deepEqual(JSON.parse(fs.readFileSync(fixture.stateFile,'utf8')).routes.qualification.prompt,'Return compact output');});

test('regression, security failure and unavailable economics cannot be hidden',()=>{const first=proposed(),firstCandidate=candidate(first.runtime,first.experiment.id);first.runtime.beginBenchmark(first.experiment.id,{actor:'w',reason:'run',evidence:['b']});const quarantined=first.runtime.recordSecurity(first.experiment.id,{passed:false,actor:'s',reason:'Prompt injection finding',evidence:['security:fail'],findings:['prompt-injection']});assert.equal(quarantined.state,'QUARANTINED');assert.throws(()=>first.runtime.decidePromotion(first.experiment.id,{approved:true,actor:'a',reason:'x',evidence:['x'],candidateSha256:firstCandidate.candidate!.sha256,proposalSha256:h('missing')}),/promotion_identity/);
  const second=proposed();candidate(second.runtime,second.experiment.id);second.runtime.beginBenchmark(second.experiment.id,{actor:'w',reason:'run',evidence:['b']});second.runtime.recordSecurity(second.experiment.id,{passed:true,actor:'s',reason:'pass',evidence:['s']});const rejected=second.runtime.recordRegression(second.experiment.id,{baseline:[available('quality',.8)],candidate:[available('quality',.7)],protectedRegressions:['quality:-0.1'],actor:'e',reason:'regression',evidence:['r']});assert.equal(rejected.state,'REJECTED');
  const third=proposed();candidate(third.runtime,third.experiment.id);third.runtime.beginBenchmark(third.experiment.id,{actor:'w',reason:'run',evidence:['b']});third.runtime.recordSecurity(third.experiment.id,{passed:true,actor:'s',reason:'pass',evidence:['s']});third.runtime.recordRegression(third.experiment.id,{baseline:[available('quality',.5)],candidate:[available('quality',.6)],protectedRegressions:[],actor:'e',reason:'pass',evidence:['r']});const inconclusive=third.runtime.completeComparison(third.experiment.id,{decision:'INCONCLUSIVE',reason:'Costs unavailable',oneTimeCost:[unavailable('training-cost')],perJobSaving:unavailable('per-job-saving'),evidence:['cost:unavailable'],actor:'e'});assert.equal(inconclusive.state,'INCONCLUSIVE');assert.equal(inconclusive.comparison?.economics.breakEvenJobs,null);});

test('scope prevents writes outside isolated candidate and defaults to no external effects',()=>{const value=scope();assert.equal(value.maximum.externalEffects,0);assert.equal(value.network.destinations.length,0);assert.throws(()=>createImprovementScope({workspace:'/w',candidateRoot:'/w/baseline',datasetRoot:'/w/data',nodeIds:['n'],runtimeIds:['r'],modelIds:['m'],maximum:value.maximum,createdAt:value.createdAt}),/scope_unsafe/);});

test('restart reconstructs nonterminal experiment without changing history',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-restart-')),file=path.join(root,'state.json');const{runtime,experiment}=proposed(file);candidate(runtime,experiment.id);const before=runtime.projection(),after=new ModelImprovementRuntime(file,clock()).projection();assert.equal(after.experiments[0]?.state,'CANDIDATE_CREATED');assert.deepEqual(after.experiments[0]?.transitions,before.experiments[0]?.transitions);});

test('changed candidate or effect invalidates sealed approval',()=>{const{runtime,experiment}=proposed(),created=promotable(runtime,experiment.id),fixture=promptFixture(runtime,experiment.id,created.candidate!.sha256);assert.throws(()=>runtime.requestPromotion(experiment.id,{actor:'operator',reason:'changed effect',evidence:['comparison'],proposal:{...fixture.proposal,intendedEffect:'different effect'}}),/proposal_identity/);runtime.requestPromotion(experiment.id,{actor:'operator',reason:'sealed',evidence:['comparison'],proposal:fixture.proposal});assert.throws(()=>runtime.decidePromotion(experiment.id,{approved:true,actor:'approver',reason:'wrong candidate',evidence:['approval'],candidateSha256:h('other'),proposalSha256:fixture.proposal.sha256}),/promotion_identity/);assert.throws(()=>runtime.decidePromotion(experiment.id,{approved:true,actor:'approver',reason:'wrong effect',evidence:['approval'],candidateSha256:created.candidate!.sha256,proposalSha256:h('other proposal')}),/promotion_identity/);});

test('stale target and quarantine stop before application',()=>{for(const quarantine of [false,true]){const{runtime,experiment}=proposed(),created=promotable(runtime,experiment.id),fixture=promptFixture(runtime,experiment.id,created.candidate!.sha256,undefined,()=>quarantine);runtime.requestPromotion(experiment.id,{actor:'operator',reason:'sealed',evidence:['comparison'],proposal:fixture.proposal});runtime.decidePromotion(experiment.id,{approved:true,actor:'approver',reason:'approved',evidence:['approval'],candidateSha256:created.candidate!.sha256,proposalSha256:fixture.proposal.sha256});if(!quarantine){const value=JSON.parse(fs.readFileSync(fixture.stateFile,'utf8'));value.routes.qualification.prompt='drifted';fs.writeFileSync(fixture.stateFile,JSON.stringify(value));}assert.throws(()=>runtime.applyPromotion(experiment.id,fixture.adapter,{actor:'worker',reason:'apply'}),quarantine?/quarantined/:/state_drifted/);const state=runtime.projection().experiments[0]!;assert.equal(state.state,'PROMOTION_APPROVED');assert.equal(state.promotion.lastFailure?.state,'APPLY_NOT_STARTED');}});

test('apply and independent verification failures never promote',()=>{for(const mode of ['apply','uncertain','verify'] as const){const{runtime,experiment}=proposed(),created=promotable(runtime,experiment.id),fixture=promptFixture(runtime,experiment.id,created.candidate!.sha256);runtime.requestPromotion(experiment.id,{actor:'operator',reason:'sealed',evidence:['comparison'],proposal:fixture.proposal});runtime.decidePromotion(experiment.id,{approved:true,actor:'approver',reason:'approved',evidence:['approval'],candidateSha256:created.candidate!.sha256,proposalSha256:fixture.proposal.sha256});const adapter:InterventionAdapter={...fixture.adapter,id:`failure-${mode}`,version:'1',kinds:['PROMPT'],prepare:(p,a)=>fixture.adapter.prepare(p,a),apply:(p,prepared)=>{if(mode==='apply')throw Error('apply_failed');if(mode==='uncertain')throw Error('state_uncertain_after_write');return fixture.adapter.apply(p,prepared);},observe:(p)=>{const observed=fixture.adapter.observe(p);return mode==='verify'?{...observed,observedStateSha256:h('wrong')}:observed;},rollback:(p,r)=>fixture.adapter.rollback(p,r)};const result=runtime.applyPromotion(experiment.id,adapter,{actor:'worker',reason:'apply'});assert.equal(result.state,mode==='apply'?'APPLY_FAILED':mode==='uncertain'?'APPLY_STATE_UNCERTAIN':'APPLY_SUCCEEDED_VERIFICATION_FAILED');assert.equal(result.promotion.appliedEffectReceipt,null);}});

test('PROMOTED and ROLLED_BACK cannot survive restart without verified receipts',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-forged-')),file=path.join(root,'state.json'),{runtime,experiment}=proposed(file);candidate(runtime,experiment.id);const raw=JSON.parse(fs.readFileSync(file,'utf8'));raw.experiments[0].state='PROMOTED';fs.writeFileSync(file,JSON.stringify(raw));assert.throws(()=>new ModelImprovementRuntime(file),/promoted_without_receipt/);raw.experiments[0].state='ROLLED_BACK';fs.writeFileSync(file,JSON.stringify(raw));assert.throws(()=>new ModelImprovementRuntime(file),/rolled_back_without_receipt/);});


test('an inherited awaiting candidate can bind one sealed proposal without rewriting its history',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-awaiting-upgrade-')),file=path.join(root,'state.json'),{runtime,experiment}=proposed(file),created=promotable(runtime,experiment.id),fixture=promptFixture(runtime,experiment.id,created.candidate!.sha256,root);runtime.requestPromotion(experiment.id,{actor:'operator',reason:'initial proposal',evidence:['comparison'],proposal:fixture.proposal});const raw=JSON.parse(fs.readFileSync(file,'utf8'));raw.experiments[0].promotion.proposal=null;raw.experiments[0].promotion.previousRouteReference='legacy:previous';raw.experiments[0].promotion.candidateRouteReference='legacy:candidate';fs.writeFileSync(file,JSON.stringify(raw));const inherited=new ModelImprovementRuntime(file,clock()),before=inherited.projection().experiments[0]!.transitions.slice();const reconciled=inherited.requestPromotion(experiment.id,{actor:'reconciliation-worker',reason:'Bind sealed operational proposal to inherited awaiting candidate',evidence:['legacy:qualification'],proposal:fixture.proposal});assert.equal(reconciled.state,'AWAITING_PROMOTION_APPROVAL');assert.equal(reconciled.promotion.proposal?.sha256,fixture.proposal.sha256);assert.deepEqual(reconciled.transitions.slice(0,-1),before);assert.equal(reconciled.transitions.at(-1)?.from,'AWAITING_PROMOTION_APPROVAL');assert.equal(reconciled.transitions.at(-1)?.to,'AWAITING_PROMOTION_APPROVAL');assert.throws(()=>inherited.requestPromotion(experiment.id,{actor:'reconciliation-worker',reason:'replace',evidence:['legacy'],proposal:fixture.proposal}),/already_sealed/);});
