import {morningIntelligence} from './morning-intelligence.js';
import {PYTHON_REPAIR_CASES} from './local-llm-benchmark.js';
import {IntelligenceJournal,ModelLandscape,candidateFunnel,intelligenceHash,type IntelligenceSource,type EstateCandidateTarget,type IntelligenceObservation,type ModelWatch} from './model-landscape.js';
import {ModelWatchPolicies,type BenchmarkReservation} from './model-watch-policies.js';
import {PersonalBenchmarkLeague} from './personal-benchmark-league.js';
import type {JobCatalog} from './job-catalog.js';
import type {ActionRegistry} from './job-runtime.js';
import type {WorkParcelPlan} from './work-parcels.js';
export interface WatchBenchmarkPort {
  plan(watch:ModelWatch,candidates:IntelligenceObservation[],targets:EstateCandidateTarget[],runKey:string):Promise<{reservation:Omit<BenchmarkReservation,'watchDigest'>;planSha256:string;details:unknown}>;
  submit(planSha256:string,reservation:BenchmarkReservation,reservationSha256:string):Promise<{parcelId:string}>;
  interrupt?(parcelId:string,reason:string):Promise<void>;
  observe(parcelId:string):Promise<{state:'RUNNING'|'COMPLETE'|'FAILED'|'INTERRUPTED';resultHashes:string[]}>;
}
export interface WatchNotificationPort {emit(event:{kind:string;watchId:string;briefSha256:string}):Promise<void>;}
export class ModelWatchRuntime {
  readonly policies:ModelWatchPolicies;readonly league:PersonalBenchmarkLeague;
  constructor(readonly options:{journal:IntelligenceJournal;landscape:ModelLandscape;sources:()=>IntelligenceSource[];estate:()=>EstateCandidateTarget[];benchmark?:WatchBenchmarkPort;notifications?:WatchNotificationPort}){this.policies=new ModelWatchPolicies(options.journal);this.league=new PersonalBenchmarkLeague(options.journal);}
  private recorded(kind:string,runKey:string){return this.options.journal.records(kind).filter(r=>r.value.runKey===runKey).at(-1)?.value;}
  async gather(watchDigest:string,runKey:string,signal:AbortSignal){const watch=this.policies.approved(watchDigest);if(!this.options.journal.records('watch-run-started').some(r=>r.value.runKey===runKey))this.policies.start(watchDigest,runKey);const prior=this.recorded('watch-intelligence',runKey);if(prior)return prior;const results=[];for(const id of watch.sourceIds){const source=this.options.sources().find(s=>s.id===id);if(!source?.approved){results.push({sourceId:id,state:'SOURCE_APPROVAL_REQUIRED',items:[],changes:[]});continue;}try{results.push({sourceId:id,state:'COMPLETE',...await this.options.landscape.poll(source,signal)});}catch{results.push({sourceId:id,state:'SOURCE_UNAVAILABLE',items:[],changes:[]});}}
    const value={watchDigest,runKey,results};this.options.journal.append('watch-intelligence',value);return value;}
  shortlist(watchDigest:string,runKey:string){const watch=this.policies.approved(watchDigest),gathered=this.recorded('watch-intelligence',runKey);if(!gathered)throw Error('watch_intelligence_required');const targets=this.options.estate(),unique=new Map<string,IntelligenceObservation>(),conflicts=new Set<string>(),changed=new Set<string>();
    const trust={OFFICIAL:5,PRIMARY:4,COMMUNITY:3,INFERRED:2,UNVERIFIED:1};
    for(const r of gathered.results)for(const item of r.items as IntelligenceObservation[]){const key=intelligenceHash(item.identity),prior=unique.get(key);if(r.changes.some((c:any)=>c.after===item.payloadSha256))changed.add(key);if(prior&&intelligenceHash({facts:prior.facts,artifactSha256:prior.artifactSha256})!==intelligenceHash({facts:item.facts,artifactSha256:item.artifactSha256}))conflicts.add(key);if(!prior||trust[item.trust]>trust[prior.trust])unique.set(key,item);}
    const candidates=[...unique.values()].filter(item=>changed.has(intelligenceHash(item.identity))).map(item=>{const assessment=candidateFunnel(item,watch,targets);return {item,...assessment,...(conflicts.has(intelligenceHash(item.identity))?{state:'REVIEW_REQUIRED',reasons:[...assessment.reasons,'CONFLICTING_SOURCE_EVIDENCE']}:{} )};});const value={watchDigest,runKey,candidates,counts:{changes:gathered.results.reduce((n:number,r:any)=>n+r.changes.length,0),unique:unique.size,rejected:candidates.filter(c=>c.reasons.length).length,shortlisted:candidates.filter(c=>!c.reasons.length).length}};this.options.journal.append('watch-shortlist',value);return value;}
  async propose(watchDigest:string,runKey:string){const watch=this.policies.approved(watchDigest),shortlist=this.recorded('watch-shortlist',runKey);if(!shortlist)throw Error('watch_shortlist_required');const candidates=shortlist.candidates.filter((c:any)=>!c.reasons.length).map((c:any)=>c.item as IntelligenceObservation);let value:any={watchDigest,runKey,state:'NO_CANDIDATES'};
    if(candidates.length){if(!this.options.benchmark)value={...value,state:'CONNECTOR_REQUIRED'};else{const planned=await this.options.benchmark.plan(watch,candidates,this.options.estate(),runKey);if(planned.reservation.runKey!==runKey||planned.reservation.specSha256!==watch.benchmarkSha256)throw Error('watch_benchmark_identity_mismatch');value={...value,state:watch.policy.automaticBenchmark?'POLICY_REVIEW':'APPROVAL_REQUIRED',...planned};}}
    this.options.journal.append('watch-benchmark-proposed',value);return value;}
  async dispatch(watchDigest:string,runKey:string){const watch=this.policies.approved(watchDigest),plan=this.recorded('watch-benchmark-proposed',runKey);if(!plan)throw Error('watch_proposal_required');if(!['POLICY_REVIEW','APPROVAL_REQUIRED'].includes(plan.state))return plan;if(!watch.policy.automaticBenchmark)return {state:'APPROVAL_REQUIRED',runKey};if(!this.options.benchmark)throw Error('watch_benchmark_connector_required');
    if(watch.policy.pauseOnPriorityWork&&!this.options.benchmark.interrupt)return {state:'RESOURCE_PROTECTION_CONNECTOR_REQUIRED',runKey};
    const shortlist=this.recorded('watch-shortlist',runKey),estate=this.options.estate();if(shortlist.candidates.filter((c:any)=>!c.reasons.length).some((c:any)=>candidateFunnel(c.item,watch,estate).reasons.length))return {state:'ESTATE_UNAVAILABLE',runKey};
    const reservation={...plan.reservation,watchDigest},reservationSha256=this.policies.reserve(reservation);try{const submitted=await this.options.benchmark.submit(plan.planSha256,reservation,reservationSha256),value={watchDigest,runKey,reservationSha256,parcelId:submitted.parcelId};this.options.journal.append('watch-dispatched',value);return value;}catch{this.options.journal.append('watch-dispatch-uncertain',{runKey,reservationSha256});throw Error('watch_dispatch_requires_reconciliation');}}
  async observe(runKey:string){const dispatched=this.recorded('watch-dispatched',runKey);if(!dispatched)return {state:'NOT_DISPATCHED',resultHashes:[]};if(!this.options.benchmark)throw Error('watch_benchmark_connector_required');const result=await this.options.benchmark.observe(dispatched.parcelId);if(result.state!=='RUNNING'){this.policies.reconcile(dispatched.reservationSha256,{state:result.state as 'COMPLETE'|'FAILED'|'INTERRUPTED',resultHashes:result.resultHashes,parcelId:dispatched.parcelId});this.options.journal.append('watch-results',{runKey,...result});}return result;}
  brief(watchDigest:string,runKey:string){const watch=this.policies.definition(watchDigest);const brief=morningIntelligence(this.options.journal,this.league,watch,watchDigest,runKey);const stored=this.options.journal.append('morning-brief',brief);return {sha256:stored.sha256,...brief};}
  async reconcileActive(){for(const row of this.options.journal.records('watch-dispatched')){if(this.recorded('watch-results',row.value.runKey))continue;let watch:ModelWatch;try{watch=this.policies.approved(row.value.watchDigest);}catch{await this.options.benchmark?.interrupt?.(row.value.parcelId,'watch_policy_expired_or_revoked');const ended=await this.observe(row.value.runKey);if(ended.state!=='RUNNING')this.brief(row.value.watchDigest,row.value.runKey);continue;}const targets=this.options.estate().filter(e=>watch.policy.machines.includes(e.id));if(watch.policy.pauseOnPriorityWork&&targets.some(e=>e.busy)||targets.some(e=>!e.fresh||!e.authenticated))await this.options.benchmark?.interrupt?.(row.value.parcelId,'higher_priority_work_or_estate_unavailable');const outcome=await this.observe(row.value.runKey);if(outcome.state!=='RUNNING')await this.notifyBrief(this.brief(row.value.watchDigest,row.value.runKey));}}
  async notifyBrief(brief:ReturnType<ModelWatchRuntime['brief']>){let definition:ModelWatch;try{definition=this.policies.approved(brief.watchDigest);}catch{return {state:'APPROVAL_EXPIRED_OR_REVOKED'};}const kind=brief.comparisons.some((c:any)=>c.delta?.quality>0)?'NEW_LEADER':brief.status==='FAILED'?'FAILED':brief.status==='APPROVAL_REQUIRED'?'APPROVAL_REQUIRED':'COMPLETE';if(!definition.notifications.includes(kind))return {state:'DISABLED'};const key=intelligenceHash({brief:brief.sha256,kind});if(this.options.journal.records('notification-outbox').some(r=>r.value.key===key))return {state:'ALREADY_QUEUED'};this.options.journal.append('notification-outbox',{key,kind,watchId:brief.watchId,briefSha256:brief.sha256});if(!this.options.notifications)return {state:'CONNECTOR_REQUIRED'};try{await this.options.notifications.emit({kind,watchId:brief.watchId,briefSha256:brief.sha256});this.options.journal.append('notification-delivered',{key});return {state:'DELIVERED'};}catch{this.options.journal.append('notification-uncertain',{key});return {state:'RECONCILIATION_REQUIRED'};}}
  projection(){return {targets:this.options.estate(),benchmarkExample:{schema:'agent-control.personal-benchmark/v1',id:'python-function-repair',version:'1.0.0',objective:'Repair Python functions using independent tests',cases:PYTHON_REPAIR_CASES,attempts:2,settings:{context:2048,temperature:0,seed:7,maxOutputTokens:256,timeoutMs:90000,tools:[]},weights:{quality:.95,speed:.05,cost:0,memory:0},judge:null},benchmarks:this.options.journal.records('personal-benchmark').map(r=>r.value),watches:this.options.journal.records('watch-proposed').filter((r,i,rows)=>!rows.slice(i+1).some(n=>n.value.watch.id===r.value.watch.id)).map(r=>({...r.value,approved:Date.parse(r.value.watch.expiresAt)>Date.now()&&this.options.journal.records('watch-approved').some(a=>a.value.digest===r.value.digest)&&!this.options.journal.records('watch-revoked').some(a=>a.value.digest===r.value.digest)})),briefs:this.options.journal.records('morning-brief').map(r=>({sha256:r.sha256,...r.value})),results:this.options.journal.records('personal-result').map(r=>r.value),interrupted:this.policies.interrupted(),sources:this.options.sources().map(s=>({id:s.id,adapter:s.adapter,trust:s.trust,approved:s.approved})),routing:'NEVER_AUTOMATIC'};}
}
export function modelWatchPlan(watchDigest:string,runKey:string):WorkParcelPlan {const phases=['intelligence','shortlist','proposal','dispatch','observe','brief'];return {objective:'Find relevant model changes and compare approved benchmark evidence',planner:{kind:'deterministic',reason:'Approved Model Watch translated into reusable typed jobs'},stages:phases.map((phase,i)=>({id:phase,name:`Model Watch ${phase}`,job:`model-watch-${phase}@1.0.0`,parameters:{watchDigest,runKey},...(i?{dependsOn:[phases[i-1]!]}:{})}))};}
export function registerModelWatchJobs(catalog:JobCatalog,actions:ActionRegistry,runtime:ModelWatchRuntime){for(const phase of ['intelligence','shortlist','proposal','dispatch','observe','brief']){const action=`model-watch.${phase}@1.0.0`;catalog.knownActions?.add(action);actions.registerConsequentialControl(action,async context=>{const digest=String(context.parameters.watchDigest),runKey=String(context.parameters.runKey);let result:unknown;if(phase==='intelligence')result=await runtime.gather(digest,runKey,context.signal);else if(phase==='shortlist')result=runtime.shortlist(digest,runKey);else if(phase==='proposal')result=await runtime.propose(digest,runKey);else if(phase==='dispatch')result=await runtime.dispatch(digest,runKey);else if(phase==='observe'){result=await runtime.observe(runKey);}else {const brief=runtime.brief(digest,runKey);await runtime.notifyBrief(brief);result=brief;}return {artifacts:[{name:phase,value:result}],verification:[`${phase}-recorded`]};},['FILESYSTEM_WRITE']);catalog.addJob({apiVersion:'agent-control/v1',kind:'Job',metadata:{id:`model-watch-${phase}`,name:`Model Watch ${phase}`,version:'1.0.0'},spec:{priority:'low',concurrency:'no-overlap',parameters:{watchDigest:{type:'string',required:true},runKey:{type:'string',required:true}},steps:[{id:phase,action,requires:['model.intelligence.control'],timeoutSeconds:120,outputs:[{name:phase,type:'application/json',schema:'agent-control.model-watch-stage/v1',version:'1.0.0'}],verification:[`${phase}-recorded`]}]}});}}
