import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {IntelligenceJournal,ModelLandscape,intelligenceHash,type IntelligenceObservation} from './model-landscape.js';
import {ModelWatchRuntime} from './model-watch-runtime.js';
import {LocalWatchBenchmarkPort} from './local-watch-benchmark-port.js';
import {PersonalBenchmarkLeague} from './personal-benchmark-league.js';
import {ModelWatchPolicies} from './model-watch-policies.js';
const hash='a'.repeat(64);
function context(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'watch-boundary-'));return {root,journal:new IntelligenceJournal(path.join(root,'journal.jsonl'))};}
const watch=()=>({schema:'agent-control.model-watch/v1',id:'watch',name:'Watch',sourceIds:['a','b'],benchmarkSha256:hash,incumbentResultSha256:null,filters:{mode:'LOCAL',capability:'coding',allowedLicences:['mit'],minimumContext:2048,maximumArtifactBytes:2000,minimumTrust:'PRIMARY'},policy:{machines:['machine'],maxDownloadBytesPerRun:2000,maxDownloadBytesPerDay:2500,maxApiSpendPerRun:0,maxApiSpendPerDay:0,currency:'USD',maxDurationMs:60000,allowRuntimeInstall:false,onlyWhenIdle:true,pauseOnPriorityWork:true,maxGpuUtilisation:0,maxDiskBytes:2000,automaticBenchmark:true},schedule:{kind:'MANUAL',utcHour:0,utcWeekday:0},notifications:[],routing:'NEVER_AUTOMATIC',retention:'KEEP_ALL',expiresAt:new Date(Date.now()+3600000).toISOString()});
test('conflicting changed and unchanged sources require review instead of source-order selection',()=>{const {root,journal}=context();try{const runtime=new ModelWatchRuntime({journal,landscape:new ModelLandscape(journal),sources:()=>[],estate:()=>[]}),draft=runtime.policies.propose(watch());runtime.policies.approve(draft.digest,'contract-test');const item={identity:{provider:'p',family:'f',model:'m',revision:'r',artifact:'file',quantisation:'q4',runtime:'r',runtimeVersion:'1',kind:'LOCAL'},facts:{licence:'mit',capabilities:['coding'],contextTokens:2048,bytes:1000,ramBytes:1000,vramBytes:0,architecture:'x64',format:'gguf',runtimeSupport:['r'],price:null,deprecated:false},artifactSha256:hash,sourceUrl:'https://example.org/model',sourceId:'a',trust:'OFFICIAL',observedAt:new Date().toISOString(),payloadSha256:hash} as IntelligenceObservation;
journal.append('watch-intelligence',{runKey:'test',results:[{items:[item],changes:[{after:hash}]},{items:[{...item,sourceId:'b',facts:{...item.facts,bytes:2000}}],changes:[]}]});const result=runtime.shortlist(draft.digest,'test');assert.equal(result.candidates.length,1);assert.ok(result.candidates[0]!.reasons.includes('CONFLICTING_SOURCE_EVIDENCE'));assert.equal(result.counts.shortlisted,0);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('new watch version does not reset daily charged budget or retain old approval',()=>{const {root,journal}=context();try{const p=new ModelWatchPolicies(journal),one=p.propose(watch());p.approve(one.digest,'contract-test');const quote={watchDigest:one.digest,runKey:'one',specSha256:hash,candidateHashes:[hash],targetIds:['machine'],downloadBytes:1500,apiSpendCeiling:0,currency:'USD',durationMs:1000,runtimeInstallation:false,expiresAt:new Date(Date.now()+30000).toISOString()};p.reserve(quote);const two=p.propose({...watch(),name:'Revised watch'});p.approve(two.digest,'contract-test');assert.throws(()=>p.approved(one.digest));assert.throws(()=>p.reserve({...quote,watchDigest:two.digest,runKey:'two'}),/daily_policy/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('local benchmark bridge rejects forged receipts before any grant or parcel submission',async()=>{const {root,journal}=context();try{let sideEffects=0;const port=new LocalWatchBenchmarkPort({journal,league:new PersonalBenchmarkLeague(journal),controller:{admit:()=>sideEffects++,grants:new Map()} as any,parcels:{submitApprovedPlan:()=>sideEffects++} as any,resolve:()=>null});const reservation={watchDigest:hash,runKey:'one',specSha256:hash,candidateHashes:[hash],targetIds:['machine'],downloadBytes:1000,apiSpendCeiling:0,currency:'USD',durationMs:1000,runtimeInstallation:false,expiresAt:new Date(Date.now()+30000).toISOString()};await assert.rejects(()=>port.submit(hash,reservation,hash),/receipt_invalid/);assert.equal(sideEffects,0);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('local bridge cancels only the requested parcel and refuses to invent running results',async()=>{const {root,journal}=context();try{const calls:unknown[]=[];const port=new LocalWatchBenchmarkPort({journal,league:new PersonalBenchmarkLeague(journal),controller:{} as any,parcels:{cancel:(...args:unknown[])=>calls.push(args),get:()=>({status:'RUNNING',endedAt:null})} as any,resolve:()=>null});await port.interrupt('native-parcel','estate disappeared');assert.deepEqual(calls,[['native-parcel','estate disappeared']]);assert.deepEqual(await port.observe('native-parcel'),{state:'RUNNING',resultHashes:[]});assert.equal(journal.records('personal-result').length,0);}finally{fs.rmSync(root,{recursive:true,force:true});}});
