import type {BenchmarkCandidate} from './local-llm-benchmark.js';
import type {IntelligenceSource,IntelligenceSourceAdapter,LandscapeItem} from './model-landscape.js';

/** Bounded, origin-locked metadata transport. Source responses are data, never commands. */
export async function approvedJson(url:string,source:Pick<IntelligenceSource,'allowedOrigins'>,signal:AbortSignal,fetcher:typeof fetch=fetch){const parsed=new URL(url);if(parsed.protocol!=='https:'||parsed.username||parsed.password||!source.allowedOrigins.includes(parsed.origin))throw Error('metadata_origin_denied');const response=await fetcher(url,{signal,redirect:'error',headers:{Accept:'application/json'}});if(!response.ok||!response.body)throw Error('metadata_source_unavailable');let size=0;const chunks:Uint8Array[]=[];for await(const chunk of response.body as unknown as AsyncIterable<Uint8Array>){size+=chunk.length;if(size>8*1024*1024){await response.body.cancel().catch(()=>{});throw Error('metadata_size_limit');}chunks.push(chunk);}return JSON.parse(Buffer.concat(chunks).toString('utf8'));}
export class JsonModelCatalogueAdapter implements IntelligenceSourceAdapter {
  id='json-model-catalogue';constructor(readonly fetcher:typeof fetch=fetch){}
  async collect(source:IntelligenceSource,signal:AbortSignal){const body=await approvedJson(source.endpoint,source,signal,this.fetcher);if(!Array.isArray(body.items)||typeof body.complete!=='boolean')throw Error('catalogue_envelope_invalid');return {items:body.items,complete:body.complete};}
}
export class HuggingFaceMetadataAdapter implements IntelligenceSourceAdapter {
  id='huggingface-metadata';constructor(readonly fetcher:typeof fetch=fetch,readonly reviewedCandidates:()=>BenchmarkCandidate[]=()=>[]){}
  async collect(source:IntelligenceSource,signal:AbortSignal){const body=await approvedJson(source.endpoint,source,signal,this.fetcher);if(typeof body.id!=='string'||typeof body.sha!=='string'||!Array.isArray(body.siblings))throw Error('repository_metadata_invalid');const items:LandscapeItem[]=[];
    for(const artifact of body.siblings.filter((s:any)=>typeof s.rfilename==='string'&&s.rfilename.endsWith('.gguf'))){const quantisation=artifact.rfilename.match(/(q\d_[a-z0-9_]+|f16|bf16|f32)\.gguf$/i)?.[1]??'unknown';const base:LandscapeItem={identity:{provider:'huggingface',family:body.id.split('/')[1]?.split('-')[0]??body.id,model:body.id,revision:body.sha,artifact:artifact.rfilename,quantisation,runtime:'',runtimeVersion:'',kind:'LOCAL'},facts:{licence:typeof body.cardData?.license==='string'?body.cardData.license:null,capabilities:Array.isArray(body.tags)&&body.tags.some((t:string)=>/code|coding/i.test(t))?['coding']:[],contextTokens:typeof body.config?.max_position_embeddings==='number'?body.config.max_position_embeddings:null,bytes:artifact.lfs?.size??artifact.size??null,ramBytes:null,vramBytes:null,architecture:body.config?.model_type??null,format:'GGUF',runtimeSupport:[],price:null,deprecated:false},artifactSha256:artifact.lfs?.sha256??null,sourceUrl:`https://huggingface.co/${body.id}/blob/${body.sha}/${artifact.rfilename}`};const reviewed=this.reviewedCandidates().find(c=>c.id===body.id&&c.revision===body.sha&&c.filename===artifact.rfilename&&c.sha256===base.artifactSha256&&c.bytes===base.facts.bytes);if(reviewed){base.facts.contextTokens=reviewed.contextLimit;base.facts.architecture=reviewed.architecture;base.facts.ramBytes=reviewed.estimatedRamBytes;base.facts.vramBytes=0;base.facts.runtimeSupport=['llama.cpp'];base.facts.estimates=['RAM is a reviewed planning estimate, not measured usage','Context and architecture are reviewed pinned-artifact metadata; target workload qualification is still required'];}items.push(base);}
    return {items,complete:true};
  }
}
export class GitHubRuntimeReleasesAdapter implements IntelligenceSourceAdapter {
  id='github-runtime-releases';constructor(readonly fetcher:typeof fetch=fetch){}
  async collect(source:IntelligenceSource,signal:AbortSignal){const releases=await approvedJson(source.endpoint,source,signal,this.fetcher);if(!Array.isArray(releases))throw Error('release_feed_invalid');const runtimeId=String(source.settings.runtimeId??'');if(!runtimeId)throw Error('runtime_identity_required');return {complete:false,items:releases.filter(r=>!r.draft&&!r.prerelease).map(r=>({identity:{provider:'github',family:runtimeId,model:runtimeId,revision:String(r.tag_name),artifact:String(r.id),quantisation:'',runtime:runtimeId,runtimeVersion:String(r.tag_name),kind:'RUNTIME'},facts:{licence:null,capabilities:[],contextTokens:null,bytes:null,ramBytes:null,vramBytes:null,architecture:null,format:null,runtimeSupport:[runtimeId],price:null,deprecated:false},artifactSha256:null,sourceUrl:r.html_url}))};}
}

export type HomeAssistantPermission='DISCOVER'|'OBSERVE'|'CONTROL'|'AUTOMATE';
export interface HomeAssistantPolicy {baseUrl:string;permissions:HomeAssistantPermission[];entities:string[];services:string[];expiresAt:string;}
/** Optional external-estate adapter. Observation never calls services or mutates state. */
export class HomeAssistantEstateAdapter {
  constructor(readonly policy:HomeAssistantPolicy,readonly credential:()=>string|undefined,readonly fetcher:typeof fetch=fetch){}
  private permitted(permission:HomeAssistantPermission){if(Date.parse(this.policy.expiresAt)<=Date.now()||!Number.isFinite(Date.parse(this.policy.expiresAt))||!this.policy.permissions.includes(permission))throw Error('home_assistant_permission_required');if(!this.credential())throw Error('home_assistant_authentication_required');}
  private async request(route:string,method='GET',body?:unknown){const base=new URL(this.policy.baseUrl);if(base.username||base.password||base.search||base.hash||!['http:','https:'].includes(base.protocol))throw Error('home_assistant_endpoint_invalid');const response=await this.fetcher(new URL(route,base),{method,redirect:'error',signal:AbortSignal.timeout(10000),headers:{Authorization:`Bearer ${this.credential()}`,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});if(!response.ok)throw Error(`home_assistant_http_${response.status}`);const text=await response.text();if(text.length>2*1024*1024)throw Error('home_assistant_response_limit');return JSON.parse(text);}
  async discover(){this.permitted('DISCOVER');const states=await this.request('/api/states');if(!Array.isArray(states))throw Error('home_assistant_states_invalid');return states.filter(s=>this.policy.entities.includes(s.entity_id)).map(s=>({id:s.entity_id,kind:'EXTERNAL_ENTITY',permissions:[...this.policy.permissions],state:'DISCOVERED'}));}
  async observe(entity:string){this.permitted('OBSERVE');if(!this.policy.entities.includes(entity))throw Error('home_assistant_entity_denied');const state=await this.request('/api/states/'+encodeURIComponent(entity));return {id:entity,state:String(state.state),unit:typeof state.attributes?.unit_of_measurement==='string'?state.attributes.unit_of_measurement:null,observedAt:new Date().toISOString(),lastChanged:state.last_changed,authority:'HOME_ASSISTANT_REPORTED',physicalVerification:false};}
  async control(entity:string,service:string,automation=false){this.permitted('CONTROL');if(automation)this.permitted('AUTOMATE');if(!this.policy.entities.includes(entity)||!this.policy.services.includes(service)||!/^\w+\.\w+$/.test(service))throw Error('home_assistant_action_denied');const [domain,action]=service.split('.');await this.request(`/api/services/${domain}/${action}`,'POST',{entity_id:entity});return {state:'REQUEST_ACCEPTED_VERIFICATION_REQUIRED',entity,service};}
}
