import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {IntelligenceJournal,ModelLandscape,intelligenceHash,candidateFunnel,type IntelligenceSource,type LandscapeItem,type ModelWatch,type EstateCandidateTarget} from './model-landscape.js';
import {ModelWatchPolicies,GovernedRules} from './model-watch-policies.js';
import {PersonalBenchmarkLeague,type PersonalBenchmark,type PersonalResult} from './personal-benchmark-league.js';
import {HomeAssistantEstateAdapter,JsonModelCatalogueAdapter} from './model-intelligence-adapters.js';
import {ModelWatchRuntime} from './model-watch-runtime.js';
const hash='a'.repeat(64),future=()=>new Date(Date.now()+86400000).toISOString();
function setup(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'showcase-contract-'));return {root,journal:new IntelligenceJournal(path.join(root,'journal.jsonl'))};}
const source:IntelligenceSource={id:'official',adapter:'contract',approved:true,trust:'OFFICIAL',endpoint:'https://example.org/catalogue',allowedOrigins:['https://example.org'],settings:{}};
function item():LandscapeItem{return {identity:{provider:'provider',family:'family',model:'model',revision:'1',artifact:'weights',quantisation:'q4',runtime:'runtime',runtimeVersion:'1',kind:'LOCAL'},facts:{licence:'apache-2.0',capabilities:['coding'],contextTokens:4096,bytes:1000,ramBytes:1000,vramBytes:0,architecture:'arch',format:'format',runtimeSupport:['runtime'],price:null,deprecated:false},artifactSha256:hash,sourceUrl:'https://example.org/model'};}
function watch():ModelWatch{return {schema:'agent-control.model-watch/v1',id:'coding',name:'Coding watch',sourceIds:['official'],benchmarkSha256:hash,incumbentResultSha256:null,filters:{mode:'LOCAL',capability:'coding',allowedLicences:['apache-2.0'],minimumContext:2048,maximumArtifactBytes:2000,minimumTrust:'PRIMARY'},policy:{machines:['machine'],maxDownloadBytesPerRun:2000,maxDownloadBytesPerDay:2500,maxApiSpendPerRun:2,maxApiSpendPerDay:3,currency:'USD',maxDurationMs:60000,allowRuntimeInstall:false,onlyWhenIdle:true,pauseOnPriorityWork:true,maxGpuUtilisation:50,maxDiskBytes:2000,automaticBenchmark:true},schedule:{kind:'DAILY',utcHour:0,utcWeekday:0},notifications:['COMPLETE'],routing:'NEVER_AUTOMATIC',retention:'KEEP_ALL',expiresAt:future()};}
const estate=():EstateCandidateTarget[]=>[{id:'machine',fresh:true,authenticated:true,controlQualified:true,ramAvailable:10000,vramAvailable:0,diskAvailable:10000,busy:false,gpuUtilisation:null,architectures:['arch'],runtimes:['runtime'],existingArtifactHashes:[],provisioners:[]}];
function benchmark():PersonalBenchmark{return {schema:'agent-control.personal-benchmark/v1',id:'repair',version:'1',objective:'Repair a function',cases:[{id:'case',prompt:'Repair',input:[],expected:0,validator:'exact-text'}],attempts:1,settings:{context:2048,temperature:0,seed:7,maxOutputTokens:256,timeoutMs:1000,tools:[]},weights:{quality:.95,speed:.05,cost:0,memory:0},judge:null};}
function result(benchmarkSha256:string,revision='1'):PersonalResult{return {schema:'agent-control.personal-result/v1',benchmarkSha256,comparisonSha256:hash,identity:{provider:'provider',model:'model',revision,quantisation:'q4',runtime:'runtime',runtimeVersion:'1',hardwareFingerprint:hash,execution:'LOCAL'},observedAt:new Date().toISOString(),status:'COMPLETE',plannedAttempts:1,attempts:[{caseId:'case',attempt:1,passed:true,elapsedMs:10,responseSha256:hash,validatorSha256:hash,subjectiveScore:null,judgementSha256:null}],metrics:{ramBytes:100,vramBytes:null,generationTokensPerSecond:null,promptTokens:null,outputTokens:null,apiCost:0,localOperatingCost:null,energyJoules:null,currency:'USD',hardwareClass:'private-fixture-machine'},nativeRunIds:['private-fixture-native-run'],provenance:'NATIVE_EXECUTION',limitations:['CONTRACT FIXTURE ONLY - NOT PHYSICAL EVIDENCE']};}
test('journal preserves history and detects tampering after restart',()=>{const {root,journal}=setup();try{journal.append('one',{a:1});journal.append('two',{b:2});assert.equal(new IntelligenceJournal(journal.file).records().length,2);fs.writeFileSync(journal.file,fs.readFileSync(journal.file,'utf8').replace('"a":1','"a":3'));assert.throws(()=>journal.records(),/integrity/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('journal recovers a lock whose process owner is proven dead and refuses a live owner',()=>{const {root,journal}=setup(),lock=journal.file+'.lock';try{fs.writeFileSync(lock,JSON.stringify({pid:2147483647,processStartToken:null,acquiredAt:'2026-09-01T00:00:00Z'}),{mode:0o600});assert.equal(journal.append('recovered',{ok:true}).sequence,1);fs.writeFileSync(lock,JSON.stringify({pid:process.pid,processStartToken:null,acquiredAt:new Date().toISOString()}),{mode:0o600});assert.throws(()=>journal.append('blocked',{ok:false}),/intelligence_journal_locked/);assert.equal(journal.records().length,1);}finally{fs.rmSync(root,{recursive:true,force:true});}});

test('ingestion deduplicates and retains revisions, prices, licence and context changes',async()=>{const {root,journal}=setup();try{let next=[item(),item()];const landscape=new ModelLandscape(journal).register({id:'contract',collect:async()=>({items:next,complete:true})});const first=await landscape.poll(source,new AbortController().signal);assert.equal(first.items.length,1);assert.deepEqual(first.changes.map(c=>c.kind),['NEW MODEL']);assert.equal((await landscape.poll(source,new AbortController().signal)).changes.length,0);next=[{...item(),identity:{...item().identity,revision:'2'},facts:{...item().facts,contextTokens:8192,licence:'mit',price:{currency:'USD',inputPerMillion:1,outputPerMillion:2}}}];const updated=await landscape.poll(source,new AbortController().signal);for(const change of ['NEW REVISION','PRICE CHANGE','CONTEXT CHANGE','LICENCE CHANGE'])assert.ok(updated.changes.some(c=>c.kind===change));assert.equal(journal.records('source-snapshot').length,3);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('partial and failed source cannot claim removals; complete source can',async()=>{const {root,journal}=setup();try{let next=[item()],complete=true,fail=false;const landscape=new ModelLandscape(journal).register({id:'contract',collect:async()=>{if(fail)throw Error('offline');return {items:next,complete};}});await landscape.poll(source,new AbortController().signal);next=[];complete=false;assert.equal((await landscape.poll(source,new AbortController().signal)).changes.length,0);fail=true;await assert.rejects(()=>landscape.poll(source,new AbortController().signal));assert.equal(landscape.latest(source.id).length,1);fail=false;complete=true;assert.equal((await landscape.poll(source,new AbortController().signal)).changes[0]?.kind,'REMOVED');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('malicious source fields, conflicting identities and unapproved source fail before execution',async()=>{const {root,journal}=setup();try{let next:any[]=[{...item(),command:'execute arbitrary source command'}];const landscape=new ModelLandscape(journal).register({id:'contract',collect:async()=>({items:next,complete:true})});await assert.rejects(()=>landscape.poll(source,new AbortController().signal));next=[item(),{...item(),facts:{...item().facts,bytes:999}}];await assert.rejects(()=>landscape.poll(source,new AbortController().signal),/conflicting/);await assert.rejects(()=>landscape.poll({...source,approved:false},new AbortController().signal),/approval/);assert.equal(journal.records('source-snapshot').length,0);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('zero local models is provisionable; stale estate, community and missing evidence are explicit rejections',()=>{const observed={...item(),sourceId:source.id,trust:source.trust,observedAt:new Date().toISOString(),payloadSha256:hash};assert.equal(candidateFunnel(observed,watch(),estate()).state,'PROVISIONABLE');const stale=estate();stale[0]!.fresh=false;assert.ok(candidateFunnel(observed,watch(),stale).reasons.includes('NO_ADMITTED_TARGET'));assert.ok(candidateFunnel({...observed,trust:'COMMUNITY'},watch(),estate()).reasons.includes('SOURCE_UNVERIFIED'));assert.ok(candidateFunnel({...observed,facts:{...observed.facts,ramBytes:null}},watch(),estate()).reasons.includes('NO_ADMITTED_TARGET'));});
test('watch policy binds approval and durably charges daily download and cost ceilings across restart',()=>{const {root,journal}=setup();try{const policies=new ModelWatchPolicies(journal),proposal=policies.propose(watch());assert.throws(()=>policies.approved(proposal.digest));policies.approve(proposal.digest,'operator');const reservation={watchDigest:proposal.digest,runKey:'one',specSha256:hash,candidateHashes:[hash],targetIds:['machine'],downloadBytes:1500,apiSpendCeiling:2,currency:'USD',durationMs:1000,runtimeInstallation:false,expiresAt:new Date(Date.now()+60000).toISOString()};policies.reserve(reservation);const restored=new ModelWatchPolicies(new IntelligenceJournal(journal.file));assert.throws(()=>restored.reserve({...reservation,runKey:'two'}),/daily_policy/);assert.throws(()=>restored.reserve(reservation),/already_consumed/);assert.equal(restored.interrupted().length,1);policies.revoke(proposal.digest,'operator');assert.throws(()=>restored.approved(proposal.digest),/approval/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('schedule is deduplicated; natural language policy cannot imply approval',()=>{const {root,journal}=setup();try{const p=new ModelWatchPolicies(journal),draft=p.propose(watch());assert.throws(()=>p.due(draft.digest));p.approve(draft.digest,'operator');const due=p.due(draft.digest)!;p.start(draft.digest,due.runKey);assert.equal(p.due(draft.digest),null);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('rules reject untrusted events and escalate failed remediation without repeating uncertain effects',async()=>{const {root,journal}=setup();try{let effects=0;const rules=new GovernedRules(journal).register('restart-runtime',{check:async()=>({running:false}),execute:async()=>{effects++;return {evidence:hash};},verify:async()=>false});const rule={id:'desired-runtime',version:1,trigger:'runtime-offline',resourceId:'isolated-runtime',checkId:'runtime-status',condition:{field:'running',operator:'EQ' as const,value:false},action:{id:'restart-runtime',parameters:{}},verifyId:'runtime-status',maxAttempts:3,expiresAt:future()};const digest=intelligenceHash(rule);rules.propose(rule);rules.approve(digest,'operator');const event={id:'event',type:'runtime-offline',resourceId:'isolated-runtime',trusted:false};await assert.rejects(()=>rules.event(digest,event,new AbortController().signal));assert.equal(effects,0);assert.equal((await rules.event(digest,{...event,trusted:true},new AbortController().signal)).state,'ESCALATE');assert.equal((await rules.event(digest,{...event,trusted:true},new AbortController().signal)).state,'REVIEW_REQUIRED');assert.equal(effects,1);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('personal league preserves revisions, rejects incomplete or unverified winners and separates operating cost',()=>{const {root,journal}=setup();try{const league=new PersonalBenchmarkLeague(journal),definition=league.define(benchmark()),one=league.record(result(definition.digest));const newer=result(definition.digest,'2');newer.attempts[0]!.passed=false;newer.attempts[0]!.elapsedMs=20;const two=league.record(newer),comparison=league.compare(one,two);assert.ok('regressions' in comparison&&comparison.regressions?.includes('QUALITY REGRESSION'));const table=league.table(definition.digest,hash);assert.equal(table.rows.length,2);assert.deepEqual(table.rankings.bestForWorkload,[one]);assert.deepEqual(table.rankings.lowestCost,[]);const incomplete=result(definition.digest);incomplete.attempts=[];assert.throws(()=>league.record(incomplete),/incomplete/);const imported=result(definition.digest,'3');imported.provenance='IMPORTED_UNVERIFIED';const unverified=league.record(imported);assert.ok(!league.table(definition.digest,hash).rankings.bestForWorkload.includes(unverified));}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('imported definitions are quarantined and result sharing has no private payload by default',()=>{const {root,journal}=setup();try{const league=new PersonalBenchmarkLeague(journal),draft=league.importDefinition(benchmark());assert.throws(()=>league.definition(draft.digest));assert.throws(()=>league.importDefinition({...benchmark(),permissions:['production.write']}));const defined=league.approveImport(draft.digest,'operator'),recorded=league.record(result(defined.digest));assert.throws(()=>league.exportResult(recorded,false),/approval/);const exported=JSON.stringify(league.exportResult(recorded,true));for(const forbidden of ['Repair a function','private-fixture','nativeRunIds','hardwareFingerprint','responseSha256','validatorSha256','prompt'])assert.ok(!exported.includes(forbidden),forbidden);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('subjective results require a named judge and separate judgment evidence',()=>{const {root,journal}=setup();try{const league=new PersonalBenchmarkLeague(journal),b=benchmark();b.cases[0]!.validator='subjective';assert.throws(()=>league.define(b));const defined=league.define(benchmark()),r=result(defined.digest);r.attempts[0]!.subjectiveScore=.9;r.attempts[0]!.judgementSha256=hash;assert.throws(()=>league.record(r),/subjective/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('Home Assistant observation cannot control or automate household devices',async()=>{const calls:any[]=[];const fetcher=(async(url:any,init:any)=>{calls.push({url:String(url),method:init.method});return new Response(JSON.stringify({entity_id:'sensor.ups',state:'battery',attributes:{unit_of_measurement:null},last_changed:new Date().toISOString()}));}) as typeof fetch;const adapter=new HomeAssistantEstateAdapter({baseUrl:'https://example.org',permissions:['OBSERVE'],entities:['sensor.ups'],services:[],expiresAt:future()},()=> 'contract-credential',fetcher);assert.equal((await adapter.observe('sensor.ups')).state,'battery');await assert.rejects(()=>adapter.control('switch.test','switch.turn_off'),/permission/);assert.equal(calls.length,1);assert.equal(calls[0].method,'GET');});
test('watch source failure produces an evidence-backed brief without fabricating benchmark results',async()=>{const {root,journal}=setup();try{const landscape=new ModelLandscape(journal).register({id:'contract',collect:async()=>{throw Error('offline');}}),runtime=new ModelWatchRuntime({journal,landscape,sources:()=>[source],estate});const draft=runtime.policies.propose(watch());runtime.policies.approve(draft.digest,'operator');await runtime.gather(draft.digest,'run',new AbortController().signal);runtime.shortlist(draft.digest,'run');await runtime.propose(draft.digest,'run');const brief=runtime.brief(draft.digest,'run');assert.equal(brief.benchmarked,0);assert.deepEqual(brief.sourceFailures,['official']);assert.equal(brief.routingChanged,false);}finally{fs.rmSync(root,{recursive:true,force:true});}});

test('morning brief separates baseline, partial coverage and an unavailable source from no change',async()=>{
 const {root,journal}=setup();try{
  let complete=false,offline=false;
  const landscape=new ModelLandscape(journal).register({id:'contract',collect:async()=>{if(offline)throw Error('offline');return {items:[item()],complete};}});
  const runtime=new ModelWatchRuntime({journal,landscape,sources:()=>[source],estate}),draft=runtime.policies.propose(watch());runtime.policies.approve(draft.digest,'operator');
  await runtime.gather(draft.digest,'baseline',new AbortController().signal);runtime.shortlist(draft.digest,'baseline');
  const first=runtime.brief(draft.digest,'baseline');assert.equal(first.observationScope,'BASELINE_OR_MIXED');assert.equal(first.sourceCoverage.allComplete,false);assert.equal(first.sourceCoverage.sources[0]?.state,'PARTIAL');assert.match(first.changeSummary,/not proof/);
  complete=true;await runtime.gather(draft.digest,'followup',new AbortController().signal);runtime.shortlist(draft.digest,'followup');const second=runtime.brief(draft.digest,'followup');assert.equal(second.observationScope,'FOLLOW_UP');assert.equal(second.sourceCoverage.allComplete,true);assert.equal(second.changesDetected,0);assert.match(second.changeSummary,/No changes observed/);
  offline=true;await runtime.gather(draft.digest,'offline',new AbortController().signal);runtime.shortlist(draft.digest,'offline');await runtime.propose(draft.digest,'offline');const third=runtime.brief(draft.digest,'offline');assert.equal(third.status,'SOURCE_UNAVAILABLE');assert.match(third.changeSummary,/incomplete/);assert.equal(third.benchmarked,0);
 }finally{fs.rmSync(root,{recursive:true,force:true});}
});
test('morning brief counts only distinct complete native results for its benchmark',()=>{
 const {root,journal}=setup();try{
  const runtime=new ModelWatchRuntime({journal,landscape:new ModelLandscape(journal),sources:()=>[source],estate});const b=runtime.league.define(benchmark());const w={...watch(),benchmarkSha256:b.digest};const draft=runtime.policies.propose(w);
  const good=runtime.league.record(result(b.digest));const failed=runtime.league.record({...result(b.digest,'failed'),status:'FAILED'});const interrupted=runtime.league.record({...result(b.digest,'interrupted'),status:'INTERRUPTED'});const imported=runtime.league.record({...result(b.digest,'imported'),provenance:'IMPORTED_UNVERIFIED'});
  journal.append('watch-results',{watchDigest:draft.digest,runKey:'results',state:'FAILED',resultHashes:[good,good,failed,interrupted,imported,hash]});const brief=runtime.brief(draft.digest,'results');assert.equal(brief.benchmarked,1);assert.deepEqual(brief.benchmarkOutcomes,{complete:1,failed:1,interrupted:1,unverified:1,missing:1});assert.equal(brief.routingChanged,false);assert.equal(brief.comparisons[0]?.state,'NO_INCUMBENT');
  assert.throws(()=>runtime.brief('f'.repeat(64),'results'));
 }finally{fs.rmSync(root,{recursive:true,force:true});}
});
test('morning brief retains quality and resource regressions without granting routing authority',()=>{
 const {root,journal}=setup();try{
  const runtime=new ModelWatchRuntime({journal,landscape:new ModelLandscape(journal),sources:()=>[source],estate}),b=runtime.league.define(benchmark());const before=result(b.digest);before.attempts[0]!.passed=false;const incumbent=runtime.league.record(before),after=result(b.digest,'2');after.attempts[0]!.elapsedMs=20;after.metrics.ramBytes=200;const candidate=runtime.league.record(after),draft=runtime.policies.propose({...watch(),benchmarkSha256:b.digest,incumbentResultSha256:incumbent});journal.append('watch-results',{watchDigest:draft.digest,runKey:'compare',state:'COMPLETE',resultHashes:[candidate]});const brief=runtime.brief(draft.digest,'compare');assert.match(brief.recommendation,/quality improved/);assert.ok(brief.comparisons[0].regressions.includes('MEMORY REGRESSION'));assert.ok(brief.comparisons[0].regressions.includes('PERFORMANCE REGRESSION'));assert.equal(brief.routingChanged,false);
 }finally{fs.rmSync(root,{recursive:true,force:true});}
});
