import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const context=vm.createContext({});vm.runInContext(fs.readFileSync('assets/dashboard/dashboard-observability-model.js','utf8'),context);
const model=context.AgentControlObservabilityModel;
test('opening unrelated work cannot keep a previously viewed node as its parent',()=>{assert.equal(model.boundNode('old-node',[]),null);assert.equal(model.boundNode('old-node',[{id:'actual-node'}]),'actual-node');assert.equal(model.boundNode('old-node',[{id:'a'},{id:'b'}]),null);assert.equal(model.boundNode('b',[{id:'a'},{id:'b'}]),'b');});
test('end-to-end throughput uses canonical accounting even without legacy counters',()=>{assert.equal(model.outputRate({accounting:{usage:{outputTokens:24}},elapsedMs:2000}),12);assert.equal(model.outputRate({accounting:{usage:{outputTokens:24}},outputTokens:999,elapsedMs:2000}),12);assert.equal(model.outputRate({accounting:{usage:{outputTokens:null}},outputTokens:999,elapsedMs:2000}),null);assert.equal(model.outputRate({outputTokens:0,elapsedMs:2000}),0);assert.equal(model.outputRate({outputTokens:10,elapsedMs:0}),null);});

test('an explicit node origin is retained only if the multi-node run proves that binding',()=>{assert.equal(model.boundNode('b',[{id:'a'},{id:'b'}]),'b');assert.equal(model.boundNode('unrelated',[{id:'a'},{id:'b'}]),null);});
test('production dashboard renders nested hierarchy, route evidence and honest missing token telemetry',()=>{const script=fs.readFileSync('assets/dashboard/dashboard-observability.js','utf8'),css=fs.readFileSync('assets/dashboard/dashboard-observability.css','utf8');for(const marker of ['Execution environments','Resource accounting','Where and how this ran','Recorded route decision','Token telemetry: unavailable / not applicable','Invocation output evidence'])assert.match(script,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(css,/Nested values are views|obs-accounting/);assert.match(css,/@media\(max-width:640px\).*obs-hierarchy/s);});
test('Estate defaults evidenced nested branches to progressive disclosure',()=>{const script=fs.readFileSync('assets/dashboard/dashboard-runtime-map.js','utf8');assert.match(script,/nestedEnvironmentCount>0/);assert.match(script,/nestedEnvironmentSummary/);});
test('existing Node and Run inspectors expose qualified acceleration without a parallel dashboard',()=>{const script=fs.readFileSync('assets/dashboard/dashboard-observability.js','utf8');for(const marker of ['Qualified execution capabilities','Qualified accelerated decoding','Speculative decoding qualification','Throughput and latency are separate objectives','Standard decoding. No qualified speculative relationship is attached to this run.'])assert.match(script,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(script,/speculative-dashboard|speculativeDashboard/);});
