import assert from 'node:assert/strict';
import {once} from 'node:events';
import fs from 'node:fs';
import {createServer} from 'node:http';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {normalizeModelUsage, OpenAICompatibleProviderClient, PROMPT_CACHE_EXPLICIT_CAPABILITY, PROMPT_CACHE_KEY_CAPABILITY, type FetchLike} from './openai-compatible-provider.js';
import type {ProviderPrompt} from './provider-prompt.js';
import {routingPreset} from './cost-performance-routing.js';

const provider = {id: 'external', kind: 'openai-compatible' as const, baseUrl: 'https://models.example/v1', wireApi: 'responses' as const, auth: {type: 'bearer-env' as const, env: 'MODEL_TEST_KEY'}};
const model = {id: 'fast', provider: 'external', providerModel: 'vendor/fast', enabled: true, capabilities: ['coding'], pricing: {currency: 'USD', inputPerMillionTokens: 1, outputPerMillionTokens: 2, cachedInputPerMillionTokens: .5, effectiveFrom: '2026-09-01', source: 'test'}};
const envKey = process.env.MODEL_TEST_KEY;
test.afterEach(() => { if (envKey === undefined) delete process.env.MODEL_TEST_KEY; else process.env.MODEL_TEST_KEY = envKey; });

test('successful OpenAI-compatible response normalizes usage and calculated cost', async () => { process.env.MODEL_TEST_KEY = 'test-secret-not-for-output'; let authorization = ''; const fetcher: FetchLike = async (_url, init) => { authorization = new Headers(init?.headers).get('authorization') ?? ''; return new Response(JSON.stringify({model: 'vendor/fast', status:'completed', output_text: 'ok', usage: {input_tokens: 100, output_tokens: 20, input_tokens_details: {cached_tokens: 40}, total_tokens: 120}}), {status: 200}); }; const result = await new OpenAICompatibleProviderClient(provider, fetcher).invoke(model, 'hello'); assert.equal(result.output, 'ok'); assert.equal(result.finishReason,'completed'); assert.equal(result.usage.cachedInputTokens, 40); assert.equal(result.usage.calculatedCost, .00012); assert.equal(authorization, 'Bearer test-secret-not-for-output'); assert.equal(JSON.stringify(result).includes('test-secret-not-for-output'), false); });
test('default provider transport is governed by the invocation deadline', async t => { const server=createServer((_request,response)=>setTimeout(()=>{response.writeHead(200,{'content-type':'application/json'});response.end(JSON.stringify({model:'vendor/fast',status:'completed',output_text:'ok',usage:{input_tokens:1,output_tokens:1,total_tokens:2}}));},25)); server.listen(0,'127.0.0.1'); await once(server,'listening'); t.after(()=>server.close()); const address=server.address(); assert.ok(address && typeof address==='object'); const localProvider={...provider,baseUrl:`http://127.0.0.1:${address.port}/v1`,auth:{type:'none' as const}}; const result=await new OpenAICompatibleProviderClient(localProvider).invoke(model,'hello',{timeoutMs:1_000}); assert.equal(result.output,'ok'); assert.equal(result.usage.totalTokens,2); });
test('Codex JSONL top-level cached input is normalized without changing total input', () => { const usage = normalizeModelUsage({input_tokens: 100, cached_input_tokens: 40, output_tokens: 20, total_tokens: 120}, model); assert.deepEqual(usage, {inputTokens: 100, outputTokens: 20, cachedInputTokens: 40, cacheWriteTokens: null, totalTokens: 120, providerReportedCost: null, calculatedCost: .00012, currency: 'USD', cacheEvidence: {reusedTokens: 40, processedPromptTokens: null, cacheWriteTokens: null, promptProcessingMs: null, generationMs: null, authority: 'authoritative', source: 'provider.usage.cached_tokens'}}); const camel = normalizeModelUsage({input_tokens: 100, cachedInputTokens: 40, output_tokens: 20, total_tokens: 120}, model); assert.equal(camel.cachedInputTokens, 40); });
test('provider-reported reasoning tokens remain distinct from visible output',()=>{const usage=normalizeModelUsage({input_tokens:10,output_tokens:4,total_tokens:14,output_tokens_details:{reasoning_tokens:3}},model);assert.equal(usage.reasoningTokens,3);assert.equal(usage.outputTokens,4);assert.equal(usage.totalTokens,14);});
test('cache writes remain distinct and use their configured price without double-counting fresh input', () => { const priced = {...model, pricing: {...model.pricing, cacheWritePerMillionTokens: 1.25}}; const usage = normalizeModelUsage({input_tokens: 100, input_tokens_details: {cached_tokens: 40, cache_write_tokens: 20}, output_tokens: 20, total_tokens: 120}, priced); assert.equal(usage.cacheWriteTokens, 20); assert.equal(usage.calculatedCost, .000125); const missing = normalizeModelUsage({input_tokens: 100, input_tokens_details: {cached_tokens: 40}, output_tokens: 20, total_tokens: 120}, priced); assert.equal(missing.calculatedCost, null); });
test('discounted cached-input pricing remains unknown when the provider omits the cache split', () => { const usage = normalizeModelUsage({input_tokens: 100, output_tokens: 20, total_tokens: 120}, model); assert.equal(usage.inputTokens, 100); assert.equal(usage.cachedInputTokens, null); assert.equal(usage.calculatedCost, null); const equalRates = normalizeModelUsage({input_tokens: 100, output_tokens: 20, total_tokens: 120}, {...model, pricing: {...model.pricing, cachedInputPerMillionTokens: 1}}); assert.equal(equalRates.calculatedCost, .00014); });
test('Responses-compatible adapters publish start and completion telemetry without inventing current context', async () => { process.env.MODEL_TEST_KEY = 'hidden'; const telemetry: Array<{phase:string; context:string; total:number|null}> = []; await new OpenAICompatibleProviderClient(provider, async () => new Response(JSON.stringify({model: 'vendor/fast', status:'completed', output_text: 'ok', usage: {input_tokens: 10, output_tokens: 2, total_tokens: 12}}), {status: 200})).invoke(model, 'hello', {onTelemetry: event => telemetry.push({phase: event.phase, context: event.context.authority, total: event.usage?.totalTokens ?? null})}); assert.deepEqual(telemetry, [{phase: 'started', context: 'unavailable', total: null}, {phase: 'completed', context: 'unavailable', total: 12}]); });
test('one-shot compatible-provider usage supplies estimated context when a window is configured', async () => { process.env.MODEL_TEST_KEY = 'hidden'; const contexts: unknown[] = [], configured = {...model, limits: {contextTokens: 100}}; await new OpenAICompatibleProviderClient(provider, async () => new Response(JSON.stringify({model: 'vendor/fast', status:'completed', output_text: 'ok', usage: {input_tokens: 40, output_tokens: 10, total_tokens: 50}}), {status: 200})).invoke(configured, 'hello', {onTelemetry: event => contexts.push(event.context)}); assert.deepEqual(contexts.at(-1), {tokens: 50, limitTokens: 100, authority: 'estimated', source: 'ephemeral_single_turn_usage_estimate'}); });
test('llama.cpp timings preserve authoritative prompt/KV reuse evidence', async () => { process.env.MODEL_TEST_KEY = 'hidden'; const result = await new OpenAICompatibleProviderClient({...provider, auth: {type: 'none' as const}}, async () => new Response(JSON.stringify({model: 'qwen', status: 'completed', output_text: 'ok', usage: {input_tokens: 240, output_tokens: 4, total_tokens: 244, input_tokens_details: {cached_tokens: 236}}, timings: {cache_n: 236, prompt_n: 4, prompt_ms: 12.5, predicted_n: 4, predicted_ms: 80}}), {status: 200})).invoke({...model, provider: 'external', providerModel: 'qwen'}, 'stable prefix'); assert.deepEqual(result.usage.cacheEvidence, {reusedTokens: 236, processedPromptTokens: 4, cacheWriteTokens: null, promptProcessingMs: 12.5, generationMs: 80, authority: 'authoritative', source: 'llama.cpp.response.timings'}); assert.equal(result.usage.cachedInputTokens, 236); });
test('governed streaming invocation retains output, timings and meaningful progress',async()=>{process.env.MODEL_TEST_KEY='hidden';const chat={...provider,wireApi:'chat-completions' as const},events=[{id:'stream-1',model:'vendor/fast',choices:[{delta:{reasoning_content:'checking'},finish_reason:null}]},{choices:[{delta:{content:'{"marker":"ok"}'},finish_reason:null}]},{choices:[{delta:{},finish_reason:'stop'}],usage:{prompt_tokens:12,completion_tokens:4,total_tokens:16},timings:{prompt_n:12,prompt_ms:24,prompt_per_second:500,predicted_n:4,predicted_ms:80,predicted_per_second:50}}],stream=events.map(value=>`data: ${JSON.stringify(value)}\n\n`).join('')+'data: [DONE]\n\n',progress:string[]=[];const result=await new OpenAICompatibleProviderClient(chat,async(_url,init)=>{const body=JSON.parse(String(init?.body));assert.equal(body.stream,true);return new Response(stream,{status:200,headers:{'content-type':'text/event-stream'}})}).invoke(model,'x',{streaming:true,noProgressMs:1000,onProgress:event=>progress.push(event.kind),structured:true});assert.equal(result.output,'{"marker":"ok"}');assert.equal(result.finishReason,'stop');assert.equal(result.usage.totalTokens,16);assert.equal(result.providerTimings?.predicted_per_second,50);assert.deepEqual(progress,['HEADERS','STREAM_EVENT','GENERATED_CONTENT']);});
test('governed streaming invocation terminates harmless no-progress independently',async()=>{process.env.MODEL_TEST_KEY='hidden';const chat={...provider,wireApi:'chat-completions' as const},stream=new ReadableStream({start(){}});await assert.rejects(()=>new OpenAICompatibleProviderClient(chat,async()=>new Response(stream,{status:200,headers:{'content-type':'text/event-stream'}})).invoke(model,'x',{streaming:true,noProgressMs:20,timeoutMs:1000}),/MODEL_NO_PROGRESS/);});

test('structured schema is sent as a strict JSON Schema on chat completions',async()=>{process.env.MODEL_TEST_KEY='hidden';let request:Record<string,unknown>|undefined;const chat={...provider,wireApi:'chat-completions' as const};const result=await new OpenAICompatibleProviderClient(chat,async(_url,init)=>{request=JSON.parse(String(init?.body));return new Response(JSON.stringify({model:'vendor/fast',choices:[{finish_reason:'stop',message:{content:'{"marker":"ok"}'}}]}),{status:200})}).invoke(model,'x',{structured:true,outputSchema:{type:'object',properties:{marker:{type:'string'}},required:['marker'],additionalProperties:false}});assert.equal(result.finishReason,'stop');assert.equal((request?.response_format as {type?:string}).type,'json_schema');assert.equal((request?.response_format as {json_schema?:{strict?:boolean}}).json_schema?.strict,true);assert.equal(request?.temperature,0)});
test('audited provider request extensions add adapter fields but cannot replace governed request fields',async()=>{process.env.MODEL_TEST_KEY='hidden';let request:Record<string,unknown>|undefined,calls=0;const chat={...provider,wireApi:'chat-completions' as const},client=new OpenAICompatibleProviderClient(chat,async(_url,init)=>{calls++;request=JSON.parse(String(init?.body));return new Response(JSON.stringify({model:'vendor/fast',choices:[{finish_reason:'stop',message:{content:'ok'}}]}),{status:200})});await client.invoke(model,'x',{requestExtension:{profile:'fixture-nonreasoning-v1',body:{chat_template_kwargs:{enable_thinking:false}}}});assert.deepEqual(request?.chat_template_kwargs,{enable_thinking:false});assert.equal(request?.model,'vendor/fast');await assert.rejects(()=>client.invoke(model,'x',{requestExtension:{profile:'fixture-v1',body:{model:'replacement'}}}),/provider_request_extension_reserved_field/);assert.equal(calls,1)});
test('OpenRouter cost routing blocks before credential resolution or inference and applies exact provider schema when eligible',async()=>{let credentials=0,calls=0,body:Record<string,unknown>|undefined;const openrouter={...provider,baseUrl:'https://openrouter.ai/api/v1',wireApi:'chat-completions' as const},client=new OpenAICompatibleProviderClient(openrouter,async(_url,init)=>{calls++;body=JSON.parse(String(init?.body));return new Response(JSON.stringify({model:'vendor/fast',choices:[{finish_reason:'stop',message:{content:'ok'}}],usage:{prompt_tokens:10,prompt_tokens_details:{cached_tokens:4},completion_tokens:2,total_tokens:12,cost:.00001}}),{status:200})},()=>{credentials++;return 'opaque-fixture-credential'}),route=(input:number,output:number)=>({id:'route',provider:'vendor',model:'vendor/fast',available:true,inputUsdPerMillionTokens:input,outputUsdPerMillionTokens:output,throughputTps:{p90:80}});await assert.rejects(()=>client.invoke(model,'x',{costRouting:{policy:routingPreset('fast-capped'),candidates:[route(9,9)]}}),/NO_ROUTE_WITHIN_PRICE_CEILING/);assert.equal(credentials,0);assert.equal(calls,0);const result=await client.invoke(model,'x',{maximumOutputTokens:32,costRouting:{policy:routingPreset('fast-capped'),candidates:[route(.5,1)]}});assert.equal(calls,1);assert.equal(credentials,1);assert.deepEqual((body?.provider as Record<string,unknown>).max_price,{prompt:1,completion:2});assert.equal((body?.provider as Record<string,unknown>).sort,'throughput');assert.equal(result.costRouting?.reconciliation.cachedInputTokens,4);assert.equal(result.costRouting?.reconciliation.freshInputTokens,6);assert.equal(result.costRouting?.reconciliation.actualCostAuthority,'PROVIDER_REPORTED');});
test('unsupported Responses routes retain the rendered legacy prompt and omit cache controls',async()=>{process.env.MODEL_TEST_KEY='hidden';let request:Record<string,unknown>|undefined;const structured:ProviderPrompt={schema:'agent-control.provider-prompt/v1',cacheScope:'private-repository-scope',blocks:[{type:'text',stability:'stable',text:'stable'},{type:'text',stability:'volatile',text:'-volatile'}]};await new OpenAICompatibleProviderClient(provider,async(_url,init)=>{request=JSON.parse(String(init?.body));return new Response(JSON.stringify({model:'vendor/fast',status:'completed',output_text:'ok'}),{status:200})}).invoke(model,structured);assert.equal(request?.input,'stable-volatile');assert.equal('prompt_cache_key' in (request??{}),false);assert.equal('prompt_cache_options' in (request??{}),false)});
test('Responses explicit cache controls require verified provider and model capabilities',async()=>{process.env.MODEL_TEST_KEY='hidden';let request:Record<string,unknown>|undefined;const capabilities=[PROMPT_CACHE_KEY_CAPABILITY,PROMPT_CACHE_EXPLICIT_CAPABILITY],qualifiedProvider={...provider,capabilities},qualifiedModel={...model,capabilities:['coding',...capabilities]},structured:ProviderPrompt={schema:'agent-control.provider-prompt/v1',cacheScope:'private-repository-scope',blocks:[{type:'text',stability:'stable',text:'stable evidence'},{type:'text',stability:'volatile',text:'\nrun-id'}]};await new OpenAICompatibleProviderClient(qualifiedProvider,async(_url,init)=>{request=JSON.parse(String(init?.body));return new Response(JSON.stringify({model:'vendor/fast',status:'completed',output_text:'ok',usage:{input_tokens:10,input_tokens_details:{cached_tokens:0,cache_write_tokens:10},output_tokens:1,total_tokens:11}}),{status:200})}).invoke(qualifiedModel,structured);const messages=request?.input as Array<{content:Array<Record<string,unknown>>}>;assert.equal(messages[0].content[0].text,'stable evidence');assert.deepEqual(messages[0].content[0].prompt_cache_breakpoint,{mode:'explicit'});assert.equal(messages[0].content[1].text,'\nrun-id');assert.equal(messages[0].content[1].prompt_cache_breakpoint,undefined);assert.deepEqual(request?.prompt_cache_options,{mode:'explicit'});assert.match(String(request?.prompt_cache_key),/^[a-f0-9]{64}$/);assert.equal(JSON.stringify(request).includes('private-repository-scope'),false)});
test('one-sided cache declarations do not send provider-specific fields',async()=>{process.env.MODEL_TEST_KEY='hidden';let request:Record<string,unknown>|undefined;const structured:ProviderPrompt={schema:'agent-control.provider-prompt/v1',cacheScope:'scope',blocks:[{type:'text',stability:'stable',text:'stable'}]};await new OpenAICompatibleProviderClient({...provider,capabilities:[PROMPT_CACHE_EXPLICIT_CAPABILITY]},async(_url,init)=>{request=JSON.parse(String(init?.body));return new Response(JSON.stringify({model:'vendor/fast',status:'completed',output_text:'ok'}),{status:200})}).invoke(model,structured);assert.equal(request?.input,'stable');assert.equal(request?.prompt_cache_options,undefined)});
test('absent secret fails without making a request', async () => { delete process.env.MODEL_TEST_KEY; let called = false; await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => { called = true; return new Response(); }).invoke(model, 'x'), /provider_authentication_required/); assert.equal(called, false); });
test('credential resolution is deferred until invocation', async () => { let resolutions=0,called=0;const client=new OpenAICompatibleProviderClient(provider,async(_url,init)=>{called++;assert.equal(new Headers(init?.headers).get('authorization'),'Bearer late-fixture-credential');return new Response(JSON.stringify({model:'vendor/fast',status:'completed',output_text:'ok'}),{status:200})},()=>{resolutions++;return 'late-fixture-credential'});assert.equal(resolutions,0);await client.invoke(model,'x');assert.equal(resolutions,1);assert.equal(called,1); });
test('account-bound API invocation seals account and node identity and rejects mismatched models before credential use',async()=>{let resolutions=0,calls=0;const accountModel={...model,accountProfile:'account-b'},client=new OpenAICompatibleProviderClient(provider,async(_url,init)=>{calls++;assert.equal(new Headers(init?.headers).get('authorization'),'Bearer account-b-credential');return new Response(JSON.stringify({model:'vendor/fast',status:'completed',output_text:'ok'}),{status:200})},()=>{resolutions++;return 'account-b-credential'},{accountProfileId:'account-b',nodeId:'controller'});const result=await client.invoke(accountModel,'x');assert.equal(result.accountProfileId,'account-b');assert.equal(result.nodeId,'controller');assert.equal(resolutions,1);assert.equal(calls,1);await assert.rejects(()=>client.invoke({...accountModel,accountProfile:'account-a'},'x'),/model_account_profile_mismatch/);assert.equal(resolutions,1);assert.equal(calls,1)});
test('declared file-backed compatibility reference is used when the primary environment reference is absent', async t => { delete process.env.MODEL_TEST_KEY; const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-provider-key-')),file=path.join(root,'credential'); t.after(()=>{delete process.env.MODEL_TEST_KEY_FILE;fs.rmSync(root,{recursive:true,force:true})}); fs.writeFileSync(file,'file-secret',{mode:0o600}); process.env.MODEL_TEST_KEY_FILE=file; let authorization=''; const configured={...provider,credentialEnv:'MODEL_TEST_KEY',credentialFileEnv:'MODEL_TEST_KEY_FILE'}; const result=await new OpenAICompatibleProviderClient(configured,async(_url,init)=>{authorization=new Headers(init?.headers).get('authorization')??'';return new Response(JSON.stringify({model:'vendor/fast',status:'completed',output_text:'ok'}),{status:200})}).invoke(model,'x'); assert.equal(authorization,'Bearer file-secret'); assert.equal(result.output,'ok'); assert.equal(JSON.stringify(result).includes('file-secret'),false); });
test('authentication and rate-limit responses are classified', async () => { process.env.MODEL_TEST_KEY = 'hidden'; await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('', {status: 401})).invoke(model, 'x'), /provider_authentication_failed/); await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('', {status: 429})).invoke(model, 'x'), /provider_rate_limited/); });
test('non-success provider bodies that echo an exact credential never enter the thrown error', async () => { const secret='opaque.future.provider.credential.8642',client=new OpenAICompatibleProviderClient(provider,async()=>new Response(JSON.stringify({error:{message:`rejected ${secret}`}}),{status:429}),()=>secret);await assert.rejects(()=>client.invoke(model,'x'),error=>{assert.equal((error as Error).message.includes(secret),false);assert.equal((error as Error).message,'provider_rate_limited');assert.equal(JSON.stringify(error).includes(secret),false);return true})});
test('malformed and streaming-only responses fail safely', async () => { process.env.MODEL_TEST_KEY = 'hidden'; await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('not-json', {status: 200})).invoke(model, 'x'), /provider_malformed_response/); await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('data: partial\n\n', {status: 200, headers: {'content-type':'text/event-stream'}})).invoke(model, 'x'), /provider_malformed_response/); });
test('bounded streaming probe records accepted endpoint TTFT usage and output without retaining raw events', async () => {
  process.env.MODEL_TEST_KEY='hidden'; const chat={...provider,wireApi:'chat-completions' as const}; let request:Record<string,unknown>|undefined;
  const stream = [
    'data: {"model":"vendor/fast","choices":[{"delta":{"role":"assistant"},"finish_reason":null}]}',
    'data: {"choices":[{"delta":{"content":"AC_CALLABILITY_OK"},"finish_reason":null}]}',
    'data: {"choices":[{"delta":{},"finish_reason":"stop"}],"usage":{"prompt_tokens":7,"completion_tokens":2,"total_tokens":9}}',
    'data: [DONE]',
  ].join('\n\n');
  const result=await new OpenAICompatibleProviderClient(chat,async(_url,init)=>{request=JSON.parse(String(init?.body));return new Response(stream,{status:200,headers:{'content-type':'text/event-stream'}})}).probeStreaming(model,'probe',{maximumOutputTokens:64});
  assert.equal(request?.stream,true); assert.equal(request?.max_tokens,64); assert.equal(result.outcome,'COMPLETED'); assert.equal(result.httpAccepted,true); assert.equal(result.streamStarted,true); assert.equal(result.tokenObserved,true); assert.equal(result.output,'AC_CALLABILITY_OK'); assert.equal(result.finishReason,'stop'); assert.equal(result.usage.totalTokens,9); assert.equal(typeof result.firstEventMs,'number'); assert.equal(typeof result.firstTokenMs,'number'); assert.match(result.responseHash??'',/^sha256:[a-f0-9]{64}$/); assert.equal(JSON.stringify(result).includes('"choices"'),false);
});
test('streaming probe separates timeout before first token from timeout during generation', async () => {
  process.env.MODEL_TEST_KEY='hidden'; const chat={...provider,wireApi:'chat-completions' as const};
  const hanging = (content: string) => async (_url: string|URL|Request, init?: RequestInit) => new Response(new ReadableStream({start(controller){if(content)controller.enqueue(new TextEncoder().encode(`data: {"choices":[{"delta":{"content":"${content}"},"finish_reason":null}]}\n\n`));init?.signal?.addEventListener('abort',()=>controller.error(Object.assign(new Error('aborted'),{name:'AbortError'})),{once:true});}}),{status:200,headers:{'content-type':'text/event-stream'}});
  const before=await new OpenAICompatibleProviderClient(chat,hanging('')).probeStreaming(model,'probe',{timeoutMs:5}); assert.equal(before.outcome,'TIMEOUT'); assert.equal(before.httpAccepted,true); assert.equal(before.tokenObserved,false); assert.equal(before.firstTokenMs,null);
  const during=await new OpenAICompatibleProviderClient(chat,hanging('partial')).probeStreaming(model,'probe',{timeoutMs:5}); assert.equal(during.outcome,'TIMEOUT'); assert.equal(during.httpAccepted,true); assert.equal(during.tokenObserved,true); assert.equal(during.output,'partial'); assert.equal(typeof during.firstTokenMs,'number');
});
test('streaming probe classifies HTTP status without retaining an upstream body',async()=>{const secret='opaque.future.provider.credential.stream.2468',chat={...provider,wireApi:'chat-completions' as const},result=await new OpenAICompatibleProviderClient(chat,async()=>new Response(`echo ${secret}`,{status:404}),()=>secret).probeStreaming(model,'probe');assert.equal(result.outcome,'HTTP_ERROR');assert.equal(result.httpStatus,404);assert.equal(result.httpAccepted,false);assert.equal(result.responseHash,null);assert.equal(JSON.stringify(result).includes(secret),false)});
test('streaming probe accepts standard multi-line SSE data fields',async()=>{process.env.MODEL_TEST_KEY='hidden';const chat={...provider,wireApi:'chat-completions' as const},stream='data: {"choices":[{"delta":\ndata: {"content":"AC_CALLABILITY_OK"},"finish_reason":"stop"}]}\n\ndata: [DONE]\n\n',result=await new OpenAICompatibleProviderClient(chat,async()=>new Response(stream,{status:200,headers:{'content-type':'text/event-stream'}})).probeStreaming(model,'probe');assert.equal(result.outcome,'COMPLETED');assert.equal(result.output,'AC_CALLABILITY_OK');assert.equal(result.finishReason,'stop')});
test('streaming probe returns a sanitized transport classification for durable diagnosis',async()=>{const secret='opaque.future.provider.credential.stream.9753',chat={...provider,wireApi:'chat-completions' as const},result=await new OpenAICompatibleProviderClient(chat,async()=>{throw new Error(`socket failed ${secret}`)},()=>secret).probeStreaming(model,'probe');assert.equal(result.outcome,'TRANSPORT_ERROR');assert.equal(result.failure,'socket failed [REDACTED CREDENTIAL]');assert.equal(result.httpStatus,null);assert.equal(JSON.stringify(result).includes(secret),false)});
test('empty provider output retains sanitized partial usage finish and response-hash evidence',async()=>{process.env.MODEL_TEST_KEY='hidden';const chat={...provider,wireApi:'chat-completions' as const};await assert.rejects(async()=>new OpenAICompatibleProviderClient(chat,async()=>new Response(JSON.stringify({model:'vendor/fast',choices:[{finish_reason:'length',message:{content:null}}],usage:{prompt_tokens:10,completion_tokens:20,total_tokens:30}}),{status:200})).invoke(model,'x'),error=>{const partial=(error as {partialInvocation?:{finishReason?:string;usage?:{totalTokens?:number};responseHash?:string}}).partialInvocation;assert.equal(partial?.finishReason,'length');assert.equal(partial?.usage?.totalTokens,30);assert.match(partial?.responseHash??'',/^sha256:[a-f0-9]{64}$/);assert.equal(JSON.stringify(error).includes('choices'),false);return true})});
test('timeout is bounded', async () => { process.env.MODEL_TEST_KEY = 'hidden'; const fetcher: FetchLike = (_url, init) => new Promise((_resolve, reject) => init?.signal?.addEventListener('abort', () => reject(Object.assign(new Error('aborted'), {name: 'AbortError'})))); await assert.rejects(() => new OpenAICompatibleProviderClient(provider, fetcher).invoke(model, 'x', {timeoutMs: 5}), /provider_timeout/); });
test('native fetch header deadlines are normalized as governed provider timeouts', async () => { process.env.MODEL_TEST_KEY = 'hidden'; const fetcher: FetchLike = async () => { throw Object.assign(new TypeError('fetch failed'), {cause: Object.assign(new Error('Headers Timeout Error'), {code: 'UND_ERR_HEADERS_TIMEOUT'})}); }; await assert.rejects(() => new OpenAICompatibleProviderClient(provider, fetcher).invoke(model, 'x'), error => { assert.equal((error as Error).message, 'provider_timeout'); assert.deepEqual((error as {providerFailureObservation?:unknown}).providerFailureObservation, {requestDispatched:true,usage:null,usageAuthority:'unavailable',elapsedMs:(error as {providerFailureObservation:{elapsedMs:number}}).providerFailureObservation.elapsedMs,invocationProfile:null}); assert.equal(JSON.stringify(error).includes('Headers Timeout Error'), false); return true; }); });
test('opaque native fetch failures are normalized as retryable transport failures', async () => { process.env.MODEL_TEST_KEY = 'hidden'; const fetcher: FetchLike = async () => { throw new TypeError('fetch failed'); }; await assert.rejects(() => new OpenAICompatibleProviderClient(provider, fetcher).invoke(model, 'x'), error => { assert.equal((error as Error).message, 'provider_transport_failed'); assert.equal(JSON.stringify(error).includes('fetch failed'), false); return true; }); });
test('caller cancellation remains distinct from provider timeout', async () => { process.env.MODEL_TEST_KEY = 'hidden'; const fetcher: FetchLike = (_url, init) => new Promise((_resolve, reject) => init?.signal?.addEventListener('abort', () => reject(Object.assign(new Error('aborted'), {name: 'AbortError'})))); const controller = new AbortController(), invocation = new OpenAICompatibleProviderClient(provider, fetcher).invoke(model, 'x', {timeoutMs: 30_000, signal: controller.signal}); controller.abort('operator_cancelled'); await assert.rejects(invocation, /provider_cancelled/); });
test('Responses function call is normalized without executing it', async () => { process.env.MODEL_TEST_KEY='hidden'; let requested=false; const result=await new OpenAICompatibleProviderClient(provider,async (_url,init)=>{const body=JSON.parse(String(init?.body));requested=body.tool_choice?.name==='qualification_marker';return new Response(JSON.stringify({model:'vendor/fast',output:[{type:'function_call',name:'qualification_marker',arguments:'{"marker":"ok"}'}]}),{status:200})}).invoke(model,'call it',{toolProbe:'qualification_marker'});assert.equal(requested,true);assert.deepEqual(result.toolCall,{name:'qualification_marker',arguments:'{"marker":"ok"}'});assert.equal(result.output,''); });
test('Responses extraction excludes reasoning text and returns only assistant output_text',async()=>{process.env.MODEL_TEST_KEY='hidden';const result=await new OpenAICompatibleProviderClient(provider,async()=>new Response(JSON.stringify({model:'vendor/fast',output:[{type:'reasoning',content:[{type:'reasoning_text',text:'private reasoning'}]},{type:'message',content:[{type:'output_text',text:'{"marker":"ok"}'}]}]}),{status:200})).invoke(model,'x',{structured:true});assert.equal(result.output,'{"marker":"ok"}');assert.equal(result.output.includes('private reasoning'),false)});
test('provider output and thrown transport errors cannot echo a credential',async()=>{const secret=['nvapi','fixture','D'.repeat(24)].join('-'),client=new OpenAICompatibleProviderClient(provider,async()=>new Response(JSON.stringify({model:secret,status:secret,output_text:`echo ${secret}`}),{status:200}),()=>secret),result=await client.invoke(model,'x');assert.equal(JSON.stringify(result).includes(secret),false);assert.match(result.output,/REDACTED/);const failed=new OpenAICompatibleProviderClient(provider,async()=>{throw new Error(`transport ${secret}`)},()=>secret);await assert.rejects(()=>failed.invoke(model,'x'),error=>{assert.equal((error as Error).message.includes(secret),false);assert.match((error as Error).message,/REDACTED/);return true})});
test('provider adapter redacts an exact unknown-format credential from output and errors',async()=>{const secret='opaque.future.provider.credential.1357',client=new OpenAICompatibleProviderClient(provider,async()=>new Response(JSON.stringify({model:secret,status:secret,output_text:`echo ${secret}`}),{status:200}),()=>secret),result=await client.invoke(model,'x');assert.equal(JSON.stringify(result).includes(secret),false);assert.match(result.output,/REDACTED CREDENTIAL/);const failed=new OpenAICompatibleProviderClient(provider,async()=>{throw new Error(`transport ${secret}`)},()=>secret);await assert.rejects(()=>failed.invoke(model,'x'),error=>{assert.equal((error as Error).message.includes(secret),false);assert.match((error as Error).message,/REDACTED CREDENTIAL/);return true})});
