import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import test from 'node:test';
import {ModelRegistry} from './model-registry.js';
import {ParameterizedJobEngine} from './parameterized-job-engine.js';
import {ParameterizedJobError, ParameterizedJobRegistry, ParameterizedRunStore, resolveParameters, SavedJobStore} from './parameterized-job-registry.js';
import {repositoryCodeReviewDefinition} from './repository-review-definition.js';
import {savedMessagingTemplateHash,validateSavedMessagingRun} from './messaging-saved-jobs.js';
import type {MessagingTemplate} from './messaging-commands.js';
import {buildRepositoryContext, LocalRepositoryResolver, ReviewBaselineStore} from './repository-review-runtime.js';
import type {ParameterizedExecutionIdentity, RepositoryReviewExecutor, ReviewExecutionRequest, ReviewExecutionResponse, SavedJob} from './parameterized-job-types.js';

function command(cwd: string, ...args: string[]) { return execFileSync(args[0], args.slice(1), {cwd, encoding: 'utf8'}).trim(); }
function repository(root: string) { const repo = path.join(root, 'repo'); fs.mkdirSync(repo); command(repo, 'git', 'init', '-q', '-b', 'main'); command(repo, 'git', 'config', 'user.email', 'test@example.invalid'); command(repo, 'git', 'config', 'user.name', 'Agent Control Test'); fs.writeFileSync(path.join(repo, 'index.ts'), 'export const answer = 41;\n'); command(repo, 'git', 'add', 'index.ts'); command(repo, 'git', 'commit', '-qm', 'initial'); return repo; }
function models(primaryQualified = true) { return new ModelRegistry([{id: 'provider', kind: 'openai-compatible', baseUrl: 'https://provider.invalid', wireApi: 'chat-completions', enabled: true}], [{id: 'fast', provider: 'provider', providerModel: 'glm-5.3-flash', capabilities: ['repository-review'], qualification: {state: primaryQualified ? 'QUALIFIED' : 'FAILED', version: 'q1', qualifiedAt: '2026-09-01T00:00:00Z', evidence: ['fixture'], capabilities: ['repository-review'], nodes: ['controller']}}, {id: 'deep', provider: 'provider', providerModel: 'glm-5.3', capabilities: ['repository-review'], qualification: {state: 'QUALIFIED', version: 'q2', qualifiedAt: '2026-09-01T00:00:00Z', evidence: ['fixture'], capabilities: ['repository-review'], nodes: ['controller']}}], {roles: {'review.default': {primary: 'fast', fallback: ['deep'], requires: ['repository-review']}}}); }
function accountModels() { const profile = {id: 'account-a', providerExecutionNodeId: 'provider-node', label: 'Account A', credentialResidency: {nodeId: 'provider-node', store: {type: 'codex-home-env' as const, env: 'CODEX_HOME_ACCOUNT_A'}}, qualification: {state: 'QUALIFIED' as const, version: 'account-q1', checkedAt: '2026-08-31T23:59:00Z', qualifiedAt: '2026-08-31T23:59:00Z', capabilities: ['codex-chatgpt'], evidence: ['fixture-account-status']}}; return new ModelRegistry([{id: 'codex', kind: 'cli', accountProfiles: [profile]}], [{id: 'sol-account-a', provider: 'codex', accountProfile: 'account-a', providerModel: 'gpt-5.6-sol', capabilities: ['repository-review'], qualification: {state: 'QUALIFIED', version: 'model-q1', qualifiedAt: '2026-08-31T23:59:00Z', capabilities: ['repository-review'], nodes: ['provider-node']}}], {roles: {'review.default': {primary: 'sol-account-a', requires: ['repository-review']}}}); }
class FixtureExecutor implements RepositoryReviewExecutor {
  requests: ReviewExecutionRequest[] = [];
  verification: Array<{workParcelIds: string[]; verdict: string}> = [];
  beforeReturn?: (request: ReviewExecutionRequest) => void;
  recordVerification(workParcelIds: string[], verdict: 'PASS' | 'PASS_WITH_FINDINGS' | 'REVIEW_REQUIRED' | 'FAILED') { this.verification.push({workParcelIds: [...workParcelIds], verdict}); }
  async execute(request: ReviewExecutionRequest): Promise<ReviewExecutionResponse> { this.requests.push(request); this.beforeReturn?.(request); return fixtureResponse(); }
}
function fixtureResponse(): ReviewExecutionResponse { return {result: {schema: 'agent-control.repository-review/v1', executiveSummary: 'One validated finding.', findings: [{id: 'f1', severity: 'medium', title: 'Incorrect constant', category: 'correctness', file: 'index.ts', startLine: 1, endLine: 1, evidence: 'answer is fixed at 41', reasoning: 'fixture', impact: 'fixture', suggestedRemediation: 'review value', confidence: .9, validation: {state: 'UNVERIFIED', reasons: []}}, {id: 'bad', severity: 'high', title: 'Invented path', category: 'correctness', file: 'missing.ts', startLine: 1, evidence: 'not real', reasoning: 'fixture', impact: 'none', suggestedRemediation: 'none', confidence: .9, validation: {state: 'UNVERIFIED', reasons: []}}], positiveObservations: [], areasReviewed: ['index.ts'], areasNotReviewed: [], verdict: 'PASS_WITH_FINDINGS'}, usage: {inputTokens: 100, outputTokens: 20, totalTokens: 120, cost: .01, currency: 'USD', source: 'provider'}, evidence: ['provider-response:fixture'], providerResponseIds: ['response-1'], workParcelIds: ['parcel-1']}; }
function setup<T extends RepositoryReviewExecutor = FixtureExecutor>(root: string, repo: string, executor: T = new FixtureExecutor() as unknown as T, instant = new Date('2026-09-01T00:00:00Z'), registryModels = models()) { const definitions = new ParameterizedJobRegistry(); definitions.register(repositoryCodeReviewDefinition); const clock = () => instant, saved = new SavedJobStore(path.join(root, 'saved.json'), definitions, clock), runs = new ParameterizedRunStore(path.join(root, 'runs.json')), baselines = new ReviewBaselineStore(path.join(root, 'baselines.json')), engine = new ParameterizedJobEngine(definitions, saved, runs, baselines, registryModels, executor, {allowedRepositoryRoots: [root], snapshotsRoot: path.join(root, 'snapshots'), nodeHealthy: id => id === 'controller', clock, wait: async () => {}}); const job = saved.create({id: 'review', name: 'Review', definition: {id: 'repository-code-review', version: 1, follow: 'latest-compatible'}, parameters: {node: 'controller', repository: repo, ref: 'main', scope: 'changes'}, contextProfile: 'STANDARD', concurrency: 'forbid-overlap', enabled: true}); return {definitions, saved, runs, baselines, engine, executor, job, setTime: (value: Date) => { instant = value; }}; }
test('messaging saved review pins approval and persists one request across store restart',t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-messaging-review-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
  const s=setup(root,repository(root));
  const service={exportSavedJob:(id:string)=>s.saved.export(id),jobDefinition:(id:string,version?:number)=>s.definitions.get(id,version),parameterizedRuns:(id?:string)=>s.runs.list(id)};
  assert.throws(()=>savedMessagingTemplateHash(service,'review'),/must_be_pinned/);
  s.saved.update('review',s.job.revision,{definition:{...s.job.definition,follow:'pinned'}});
  const template:MessagingTemplate={kind:'saved',name:'review',jobId:'review',definitionHash:savedMessagingTemplateHash(service,'review'),parameters:{},arguments:{},maxActive:1,maxRunsPerHour:2};
  validateSavedMessagingRun(service,template,{},Date.parse('2026-09-01T00:00:01Z'));
  assert.throws(()=>validateSavedMessagingRun(service,template,{repository:'/unapproved'},Date.now()),/argument_not_approved/);
  let observed=0;s.runs.subscribe(()=>{observed++;throw new Error('optional observer failure');});
  const first=s.engine.runNow('review','messaging:test','stable-event');assert.equal(observed,1);
  assert.throws(()=>validateSavedMessagingRun(service,template,{},Date.now()),/active_job_budget/);
  const reloaded=new ParameterizedRunStore(s.runs.file),engine=new ParameterizedJobEngine(s.definitions,s.saved,reloaded,s.baselines,s.engine.models,s.executor,s.engine.options);
  assert.equal(engine.runNow('review','messaging:test','stable-event').id,first.id);assert.equal(reloaded.list().length,1);
  s.saved.update('review',s.saved.get('review').revision,{contextProfile:'THIN'});
  assert.throws(()=>validateSavedMessagingRun(service,template,{},Date.now()),/definition_changed/);
  engine.cancel(first.id,'messaging:test');assert.equal(reloaded.get(first.id)?.status,'CANCELLED');
});

function interruptedExecution(setupResult: ReturnType<typeof setup>, repo: string, state: 'RUNNING' | 'CANCELLING' = 'RUNNING') {
  const created=setupResult.engine.runNow('review','operator'),run=setupResult.runs.get(created.id)!,repository=new LocalRepositoryResolver().resolve({nodeId:'controller',repository:repo,requestedRef:'main',allowedRoots:[path.dirname(repo)],snapshotsRoot:path.join(path.dirname(repo),'recovery-snapshots')}),route=setupResult.engine.models.route({modelRole:'review.default',nodeId:'controller',workloadNodeId:'controller',requiredCapabilities:['repository-review'],allowFallback:true}),at='2026-09-01T00:00:00.000Z';
  const identity:ParameterizedExecutionIdentity={id:`repository-review:${run.id}:1`,sequence:1,providerId:route.providerId,accountProfileId:route.accountProfileId??null,modelId:route.modelId,nodeId:route.nodeId,workloadNodeId:route.workloadNodeId,providerExecutionNodeId:route.providerExecutionNodeId,credentialNodeId:route.credentialNodeId??null,startedAt:at,state:'RUNNING',observedAt:at};
  run.repository=repository;run.modelRoute=route;run.context=buildRepositoryContext(repository,'STANDARD').summary;run.status=state;run.executionSequence=1;run.activeExecution=identity;run.providerExecutions=[structuredClone(identity)];run.transitions.push({status:state,at});setupResult.runs.update(run);return {run,identity};
}

test('definition parameters are typed, defaulted, versioned and reject unknown or incompatible updates', () => { const registry = new ParameterizedJobRegistry(), definition = registry.register(repositoryCodeReviewDefinition); assert.deepEqual(resolveParameters(definition, {node: 'controller', repository: '/srv/repositories/example'}), {node: 'controller', repository: '/srv/repositories/example', ref: 'main', scope: 'changes'}); assert.equal(resolveParameters(definition,{node:'controller',repository:'https://git.example/team/repo.git'}).repository,'https://git.example/team/repo.git'); assert.throws(() => resolveParameters(definition, {node: 'controller'}), /required_parameter_missing:repository/); assert.throws(() => resolveParameters(definition, {node: 'controller', repository: 'relative'}), /invalid_repository_reference/); assert.throws(() => resolveParameters(definition, {node: 'controller', repository: '/repo', arbitrary: true}), /unknown_parameter/); assert.throws(() => registry.register({...definition,parameters:{...definition.parameters,apiKey:{type:'string',description:'must not persist'}}}),/job_parameter_schema_invalid/); assert.throws(() => registry.register({...definition, displayName: 'Changed'}), /incompatible_definition_update/); assert.throws(() => registry.get('missing'), /unknown_definition/); });

test('saved jobs persist, validate schedules, use optimistic revisions and export no credentials', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-saved-')), repo = repository(root), setupResult = setup(root, repo), restored = new SavedJobStore(path.join(root, 'saved.json'), setupResult.definitions); assert.equal(restored.get('review').revision, 1); assert.throws(() => restored.update('review', 2, {name: 'wrong'}), /revision_conflict/); const scheduled = restored.update('review', 1, {schedule: {kind: 'cron', cron: '0 2 * * *', timezone: 'Europe\/London', enabled: true, missedRunPolicy: 'skip'}}); assert.equal(scheduled.revision, 2); assert.doesNotMatch(JSON.stringify(restored.export('review')), /token|credential|password/i); });

test('repository resolver freezes exact SHA in an isolated read-only snapshot and records dirty source state', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-repo-')), repo = repository(root), allowedElsewhere = path.join(root, 'allowed-elsewhere'), sha = command(repo, 'git', 'rev-parse', 'HEAD'); fs.mkdirSync(allowedElsewhere); fs.writeFileSync(path.join(repo, 'dirty.txt'), 'not reviewed\n'); const resolved = new LocalRepositoryResolver().resolve({nodeId: 'controller', repository: repo, requestedRef: 'main', allowedRoots: [root], snapshotsRoot: path.join(root, 'snapshots')}); assert.equal(resolved.reviewedSha, sha); assert.equal(resolved.dirty, true); assert.equal(command(resolved.snapshotPath, 'git', 'rev-parse', 'HEAD'), sha); assert.equal(fs.existsSync(path.join(resolved.snapshotPath, 'dirty.txt')), false); assert.equal(fs.statSync(path.join(resolved.snapshotPath, 'index.ts')).mode & 0o222, 0); assert.throws(() => new LocalRepositoryResolver().resolve({nodeId: 'controller', repository: repo, requestedRef: 'main', allowedRoots: [allowedElsewhere], snapshotsRoot: path.join(root, 'other')}), /outside_policy/); });

test('repository context excludes secret files and reports every unrepresented tracked file',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-context-')),repo=repository(root);fs.writeFileSync(path.join(repo,'secrets.json'),'{"value":"never-send"}\n');fs.writeFileSync(path.join(repo,'notes.txt'),'not selected by THIN\n');command(repo,'git','add','secrets.json','notes.txt');command(repo,'git','commit','-qm','context inputs');const resolved=new LocalRepositoryResolver().resolve({nodeId:'controller',repository:repo,requestedRef:'main',allowedRoots:[root],snapshotsRoot:path.join(root,'snapshots')}),context=buildRepositoryContext(resolved,'THIN',10_000),wire=context.chunks.map(chunk=>chunk.content).join('\n');assert.equal(wire.includes('never-send'),false);assert.equal(wire.includes('secrets.json'),false);assert.equal(context.summary?.omittedFiles.includes('notes.txt'),true);assert.equal(context.summary?.omittedFiles.includes('secrets.json'),true)});

test('repository resolution fails closed for missing, non-Git, unresolved ref and unapproved remote inputs',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-repo-errors-')),plain=path.join(root,'plain');fs.mkdirSync(plain);const resolver=new LocalRepositoryResolver();assert.throws(()=>resolver.resolve({nodeId:'controller',repository:path.join(root,'missing'),requestedRef:'main',allowedRoots:[root]}),/repository_missing/);assert.throws(()=>resolver.resolve({nodeId:'controller',repository:plain,requestedRef:'main',allowedRoots:[root]}),/repository_not_git/);const repo=repository(root);assert.throws(()=>resolver.resolve({nodeId:'controller',repository:repo,requestedRef:'missing-branch',allowedRoots:[root]}),/repository_ref_unresolved/);assert.throws(()=>resolver.resolve({nodeId:'controller',repository:'https://git.example/team/repo.git',requestedRef:'main',allowedRoots:[root],allowedRemotes:[]}),/repository_remote_outside_policy/);});

test('manual execution routes qualified model, links work parcels, validates findings and advances only successful baseline', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-run-')), repo = repository(root), setupResult = setup(root, repo), created = setupResult.engine.runNow('review', 'operator'), completed = await setupResult.engine.execute(created.id); assert.equal(completed.status, 'SUCCEEDED_WITH_FINDINGS'); assert.equal(completed.repository?.reviewedSha, command(repo, 'git', 'rev-parse', 'HEAD')); assert.equal(completed.modelRoute?.modelId, 'fast'); assert.deepEqual(completed.workParcelIds, ['parcel-1']); assert.equal(completed.result?.findings.length, 1); assert.equal(completed.result?.findings[0].validation.state, 'VALID'); assert.deepEqual(setupResult.executor.verification, [{workParcelIds: ['parcel-1'], verdict: 'PASS_WITH_FINDINGS'}]); assert.equal(completed.immutable, true); assert.throws(() => setupResult.runs.update(completed), /historical_run_immutable/); assert.equal(setupResult.baselines.get('review', completed.repository!.identity, 'main')?.sha, completed.repository!.reviewedSha); });

test('branch movement during review cannot change frozen SHA and next success reviews the delta', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-delta-')), repo = repository(root), setupResult = setup(root, repo), first = await setupResult.engine.execute(setupResult.engine.runNow('review', 'operator').id), firstSha = first.repository!.reviewedSha; fs.writeFileSync(path.join(repo, 'index.ts'), 'export const answer = 42;\n'); command(repo, 'git', 'add', 'index.ts'); command(repo, 'git', 'commit', '-qm', 'change'); const secondSha = command(repo, 'git', 'rev-parse', 'HEAD'); setupResult.setTime(new Date('2026-09-01T01:00:00Z')); setupResult.executor.beforeReturn = () => { fs.writeFileSync(path.join(repo, 'later.ts'), 'export const later = true;\n'); command(repo, 'git', 'add', 'later.ts'); command(repo, 'git', 'commit', '-qm', 'later'); }; const second = await setupResult.engine.execute(setupResult.engine.runNow('review', 'operator').id); assert.equal(second.repository?.reviewedSha, secondSha); assert.equal(second.repository?.comparisonSha, firstSha); assert.deepEqual(second.context?.changedFiles, ['index.ts']); assert.equal(setupResult.baselines.get('review', second.repository!.identity, 'main')?.sha, secondSha); });

test('failed review does not advance baseline and missing work parcel fails closed', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-fail-')), repo = repository(root), executor: RepositoryReviewExecutor = {execute: async () => ({result: {schema: 'agent-control.repository-review/v1', executiveSummary: 'none', findings: [], positiveObservations: [], areasReviewed: [], areasNotReviewed: [], verdict: 'PASS'}, usage: {source: 'unavailable'}, evidence: [], providerResponseIds: [], workParcelIds: []})}, setupResult = setup(root, repo, executor); const failed = await setupResult.engine.execute(setupResult.engine.runNow('review', 'operator').id); assert.equal(failed.status, 'FAILED'); assert.match(failed.errors[0], /work_parcel_missing/); assert.equal(setupResult.baselines.get('review', failed.repository!.identity, 'main'), undefined); });

test('logical route records explicit fallback and fallback can be disabled', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-route-')), repo = repository(root), setupResult = setup(root, repo, new FixtureExecutor(), new Date('2026-09-01T00:00:00Z'), models(false)); const completed = await setupResult.engine.execute(setupResult.engine.runNow('review', 'operator').id); assert.equal(completed.status, 'SUCCEEDED_WITH_FINDINGS'); assert.equal(completed.modelRoute?.modelId, 'deep'); assert.equal(completed.modelRoute?.fallback, true); assert.match(completed.fallbackHistory[0].reason, /fast/); const current = setupResult.saved.get('review'), changed = setupResult.saved.update('review', current.revision, {routing: {modelRole: 'review.default', allowFallback: false}}); setupResult.setTime(new Date('2026-09-01T01:00:00Z')); const failed = await setupResult.engine.execute(setupResult.engine.runNow(changed.id, 'operator').id); assert.equal(failed.status, 'FAILED'); assert.match(failed.errors[0], /model_fallback_disabled/); });

test('Saved Job account policy reaches the exact account-bound production route', async () => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-account-route-')),repo=repository(root),profile={id:'lawrence-pro',nodeId:'msi',label:'Lawrence Pro',credentialStore:{type:'codex-home-env' as const,env:'CODEX_HOME_LAWRENCE_PRO'},qualification:{state:'QUALIFIED' as const,version:'account-q1',checkedAt:'2026-09-02T00:00:00Z',qualifiedAt:'2026-09-02T00:00:00Z',capabilities:['codex-chatgpt'],evidence:['interactive-login']}},registry=new ModelRegistry([{id:'codex',kind:'cli',accountProfiles:[profile]}],[{id:'sol-pro',provider:'codex',accountProfile:'lawrence-pro',providerModel:'gpt-5.6-sol',capabilities:['repository-review'],qualification:{state:'QUALIFIED',version:'model-q1',capabilities:['repository-review'],nodes:['msi']}}],{roles:{'review.default':{primary:'sol-pro',requires:['repository-review']}}}),fixture=new FixtureExecutor(),setupResult=setup(root,repo,fixture,new Date('2026-09-02T00:00:00Z'),registry),current=setupResult.saved.get('review');
  setupResult.saved.update('review',current.revision,{routing:{model:'sol-pro',accountProfile:'lawrence-pro',allowFallback:false},budgets:{timeoutMinutes:3}});
  const completed=await setupResult.engine.execute(setupResult.engine.runNow('review','operator').id);
  assert.equal(completed.modelRoute?.providerId,'codex');assert.equal(completed.modelRoute?.accountProfileId,'lawrence-pro');assert.equal(completed.modelRoute?.modelId,'sol-pro');assert.equal(completed.modelRoute?.nodeId,'msi');assert.equal(completed.repository?.nodeId,'controller');assert.equal(fixture.requests[0].route.accountProfileId,'lawrence-pro');assert.equal(fixture.requests[0].run.definition.budgets.timeoutMinutes,3);
  const latest=setupResult.saved.get('review');assert.throws(()=>setupResult.saved.update('review',latest.revision,{routing:{model:'sol-pro',accountProfile:'invalid profile',allowFallback:false}}),/saved_job_account_profile_invalid/);
});

test('scheduler persists occurrence identity, prevents duplicate delivery, honours disable and uses manual run path', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-schedule-')), repo = repository(root), setupResult = setup(root, repo), scheduled = setupResult.saved.update('review', 1, {schedule: {kind: 'cron', cron: '0 2 * * *', timezone: 'Europe/London', enabled: true, missedRunPolicy: 'run-once-immediately'}}); setupResult.setTime(new Date('2026-09-01T01:00:00Z')); assert.equal((await setupResult.engine.tickSchedules()).length, 1); assert.equal((await setupResult.engine.tickSchedules()).length, 0); assert.equal(setupResult.runs.list().length, 1); await setupResult.engine.executeNext(); assert.equal(setupResult.runs.list()[0].status, 'SUCCEEDED_WITH_FINDINGS'); setupResult.saved.setEnabled('review', false, scheduled.revision); setupResult.setTime(new Date('2026-09-02T01:00:00Z')); assert.equal((await setupResult.engine.tickSchedules()).length, 0); const restored = new ParameterizedRunStore(path.join(root, 'runs.json')); assert.equal(restored.list().length, 1); });

test('run-once-immediately retains the deterministic due occurrence while advancing past missed backlog',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-run-once-')),repo=repository(root),setupResult=setup(root,repo);setupResult.saved.update('review',1,{schedule:{kind:'cron',cron:'0 2 * * *',timezone:'Europe/London',enabled:true,missedRunPolicy:'run-once-immediately'}});setupResult.setTime(new Date('2026-09-03T12:00:00Z'));const [run]=await setupResult.engine.tickSchedules();assert.equal(run.trigger.scheduledFor,'2026-09-01T01:00:00.000Z');assert.equal(run.trigger.scheduleCursor,'2026-09-03T12:00:00.000Z');assert.equal((await setupResult.engine.tickSchedules()).length,0);const restored=new ParameterizedRunStore(path.join(root,'runs.json'));assert.equal(restored.get(run.id)?.occurrenceId,run.occurrenceId)});

test('missed skip occurrences are durably consumed and an interrupted external run is not duplicated', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-restart-')), repo = repository(root), setupResult = setup(root, repo); setupResult.saved.update('review', 1, {schedule: {kind: 'cron', cron: '0 2 * * *', timezone: 'Europe/London', enabled: true, missedRunPolicy: 'skip'}}); setupResult.setTime(new Date('2026-09-03T12:00:00Z')); const skipped = await setupResult.engine.tickSchedules(); assert.equal(skipped[0].status, 'CANCELLED'); assert.match(skipped[0].errors[0], /missed-schedule-skip/); const second = await setupResult.engine.tickSchedules(); assert.equal(second[0].status, 'CANCELLED'); assert.notEqual(second[0].occurrenceId, skipped[0].occurrenceId); const manual = setupResult.engine.runNow('review', 'operator'), mutable = setupResult.runs.get(manual.id)!; mutable.status = 'RUNNING'; mutable.executionSequence = 3; mutable.transitions.push({status: 'RUNNING', at: '2026-09-03T12:00:00Z'}); setupResult.runs.update(mutable); const recovered = new ParameterizedJobEngine(setupResult.definitions, setupResult.saved, setupResult.runs, setupResult.baselines, setupResult.engine.models, setupResult.executor, setupResult.engine.options); assert.equal(recovered.runs.get(manual.id)?.status, 'DISCONNECTED'); assert.equal(recovered.runs.get(manual.id)?.recovery?.reason, 'controller_restart_execution_identity_missing'); assert.equal(await recovered.executeNext(), undefined); assert.equal(setupResult.executor.requests.length, 0); });

test('restart before an external execution identity exists safely requeues the same Run', async () => { const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-resolve-restart-')),repo=repository(root),setupResult=setup(root,repo),manual=setupResult.engine.runNow('review','operator'),mutable=setupResult.runs.get(manual.id)!; mutable.status='RESOLVING';mutable.executionSequence=3;mutable.transitions.push({status:'RESOLVING',at:'2026-09-03T12:00:00Z'});setupResult.runs.update(mutable);const recovered=new ParameterizedJobEngine(setupResult.definitions,setupResult.saved,setupResult.runs,setupResult.baselines,setupResult.engine.models,setupResult.executor,setupResult.engine.options);assert.equal(recovered.runs.get(manual.id)?.status,'QUEUED');const completed=await recovered.execute(manual.id);assert.equal(completed.executionSequence,4);assert.equal(setupResult.executor.requests.at(-1)?.executionAttempt,4);});

test('authoritative reconnect follows a changed turn id then finalizes one missed completion event', async () => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-reconcile-')),repo=repository(root);let phase=0;const executor:RepositoryReviewExecutor={execute:async()=>{throw new Error('duplicate_execution_forbidden')},reconcile:async(_run,execution)=>phase++===0?{executionId:execution.id,state:'RUNNING',continuityProven:true,activeTurnId:'turn:continued',observedAt:'2026-09-01T00:01:00.000Z'}:{executionId:execution.id,state:'COMPLETED',continuityProven:true,activeTurnId:'turn:continued',observedAt:'2026-09-01T00:02:00.000Z',response:fixtureResponse()},recordVerification:()=>{}};const setupResult=setup(root,repo,executor),{run}=interruptedExecution(setupResult,repo),recovered=new ParameterizedJobEngine(setupResult.definitions,setupResult.saved,setupResult.runs,setupResult.baselines,setupResult.engine.models,executor,setupResult.engine.options);
  assert.equal(recovered.runs.get(run.id)?.status,'DISCONNECTED');const active=await recovered.reconcile(run.id);assert.equal(active.status,'RECONNECTING');assert.equal(active.activeExecution?.activeTurnId,'turn:continued');const complete=await recovered.reconcile(run.id);assert.equal(complete.status,'SUCCEEDED_WITH_FINDINGS');assert.equal(complete.transitions.filter(item=>['SUCCEEDED','SUCCEEDED_WITH_FINDINGS','FAILED','CANCELLED','DEGRADED'].includes(item.status)).length,1);assert.equal(await recovered.executeNext(),undefined);
});

test('reconciliation fails closed on execution identity mismatch and preserves the selected route', async () => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-reconcile-mismatch-')),repo=repository(root),executor:RepositoryReviewExecutor={execute:async()=>{throw new Error('not_expected')},reconcile:async()=>({executionId:'different-execution',state:'COMPLETED',continuityProven:true,observedAt:'2026-09-01T00:01:00.000Z',response:fixtureResponse()})},setupResult=setup(root,repo,executor),{run,identity}=interruptedExecution(setupResult,repo),recovered=new ParameterizedJobEngine(setupResult.definitions,setupResult.saved,setupResult.runs,setupResult.baselines,setupResult.engine.models,executor,setupResult.engine.options),result=await recovered.reconcile(run.id);
  assert.equal(result.status,'DISCONNECTED');assert.equal(result.recovery?.reason,'execution_identity_changed');assert.equal(result.modelRoute?.modelId,identity.modelId);assert.equal(result.activeExecution?.accountProfileId,identity.accountProfileId);
});

test('cancellation becomes terminal only after an identity-matched cleanup receipt', async () => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-reconcile-cancel-')),repo=repository(root),executor:RepositoryReviewExecutor={execute:async()=>{throw new Error('not_expected')},cancel:async(_run,execution)=>({executionId:execution.id,state:'CANCELLED',cleanupConfirmed:true,observedAt:'2026-09-01T00:01:00.000Z'})},setupResult=setup(root,repo,executor),{run}=interruptedExecution(setupResult,repo,'CANCELLING'),recovered=new ParameterizedJobEngine(setupResult.definitions,setupResult.saved,setupResult.runs,setupResult.baselines,setupResult.engine.models,executor,setupResult.engine.options),result=await recovered.reconcile(run.id);
  assert.equal(result.status,'CANCELLED');assert.equal(result.activeExecution?.state,'CANCELLED');assert.equal(result.immutable,true);assert.equal(result.recovery?.reason,'cancellation_confirmed');
});

test('human authentication blocks the selected account route without fallback or retry', async () => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-auth-blocked-')),repo=repository(root),executor:RepositoryReviewExecutor={execute:async()=>{throw new Error('codex_chatgpt_auth_required')}},setupResult=setup(root,repo,executor),result=await setupResult.engine.execute(setupResult.engine.runNow('review','operator').id);
  assert.equal(result.status,'AUTHENTICATION_BLOCKED');assert.equal(result.recovery?.state,'AUTHENTICATION_REQUIRED');assert.equal(result.retryHistory.length,0);assert.equal(result.activeExecution?.providerId,result.modelRoute?.providerId);assert.equal(result.activeExecution?.accountProfileId,result.modelRoute?.accountProfileId??null);
});

test('authentication recovery requires newer qualification and resumes the same sealed account route', async () => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-auth-resume-')),repo=repository(root),registry=accountModels(),fixture=new FixtureExecutor(),original=fixture.execute.bind(fixture);let calls=0;
  fixture.execute=async request=>{calls++;if(calls===1){fixture.requests.push(request);throw new Error('codex_chatgpt_auth_required')}return original(request)};
  const setupResult=setup(root,repo,fixture,new Date('2026-09-01T00:00:00Z'),registry),saved=setupResult.saved.get('review');setupResult.saved.update('review',saved.revision,{routing:{model:'sol-account-a',accountProfile:'account-a',allowFallback:false}});
  const blocked=await setupResult.engine.execute(setupResult.engine.runNow('review','operator').id),sealed=structuredClone(blocked.modelRoute!);
  assert.equal(blocked.status,'AUTHENTICATION_BLOCKED');assert.throws(()=>setupResult.engine.resumeAuthentication(blocked.id,'operator'),/account_profile_requalification_required/);
  setupResult.setTime(new Date('2026-09-01T00:01:00Z'));registry.setAccountQualification({providerId:'codex',accountProfileId:'account-a',providerExecutionNodeId:'provider-node',credentialNodeId:'provider-node',state:'QUALIFIED',version:'account-q2',checkedAt:'2026-09-01T00:00:30Z',qualifiedAt:'2026-09-01T00:00:30Z',capabilities:['codex-chatgpt'],evidence:['fixture-reauthenticated']});
  const queued=setupResult.engine.resumeAuthentication(blocked.id,'operator');assert.equal(queued.status,'QUEUED');assert.equal(queued.recovery?.reason,'authentication_requalified_same_route');
  const completed=await setupResult.engine.execute(blocked.id);assert.equal(completed.status,'SUCCEEDED_WITH_FINDINGS');assert.equal(completed.executionSequence,2);assert.equal(calls,2);assert.equal(completed.fallbackHistory.length,0);
  const routeIdentity=(value:typeof sealed)=>[value.providerId,value.accountProfileId,value.modelId,value.providerModel,value.workloadNodeId,value.providerExecutionNodeId,value.credentialNodeId];assert.deepEqual(routeIdentity(completed.modelRoute!),routeIdentity(sealed));
  assert.deepEqual(completed.providerExecutions?.map(value=>[value.sequence,value.providerId,value.accountProfileId,value.modelId,value.workloadNodeId,value.providerExecutionNodeId,value.credentialNodeId]),[[1,'codex','account-a','sol-account-a','controller','provider-node','provider-node'],[2,'codex','account-a','sol-account-a','controller','provider-node','provider-node']]);
  assert.match(completed.transitions.find(value=>value.detail?.startsWith('authentication_requalified_same_route'))?.detail??'',/operator/);
});

test('retry remains within one Run and cost budget failure preserves evidence without baseline advancement',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-budget-')),repo=repository(root),fixture=new FixtureExecutor(),original=fixture.execute.bind(fixture);let attempts=0;fixture.execute=async request=>{attempts++;if(attempts===1)throw Object.assign(new Error('provider_unavailable'),{workParcelIds:['failed-parcel']});return original(request)};const setupResult=setup(root,repo,fixture),current=setupResult.saved.get('review');setupResult.saved.update('review',current.revision,{budgets:{maximumRetries:1,maxCost:.001}});const completed=await setupResult.engine.execute(setupResult.engine.runNow('review','operator').id);assert.equal(attempts,2);assert.equal(completed.retryHistory.length,1);assert.deepEqual(completed.workParcelIds,['failed-parcel','parcel-1']);assert.deepEqual(fixture.verification,[]);assert.equal(completed.status,'FAILED');assert.match(completed.errors[0],/cost_budget_exceeded/);assert.equal(setupResult.baselines.get('review',completed.repository!.identity,'main'),undefined)});

test('configured cost budget fails closed when authoritative and calculated cost are unavailable',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-budget-unknown-')),repo=repository(root),fixture=new FixtureExecutor(),original=fixture.execute.bind(fixture);fixture.execute=async request=>{const response=await original(request);response.usage={inputTokens:100,outputTokens:20,totalTokens:120,source:'unavailable'};return response};const setupResult=setup(root,repo,fixture),current=setupResult.saved.get('review');setupResult.saved.update('review',current.revision,{budgets:{maximumRetries:0,maxCost:1}});const completed=await setupResult.engine.execute(setupResult.engine.runNow('review','operator').id);assert.equal(completed.status,'FAILED');assert.match(completed.errors[0],/cost_budget_unenforceable/);assert.deepEqual(fixture.verification,[])});

test('timeout and operator cancellation remain distinct while external cleanup is unproven',async()=>{const waitExecutor:RepositoryReviewExecutor={execute:request=>new Promise((_resolve,reject)=>request.signal.addEventListener('abort',()=>reject(new Error('aborted')),{once:true}))};const timeoutRoot=fs.mkdtempSync(path.join(os.tmpdir(),'ac-timeout-')),timeoutRepo=repository(timeoutRoot),timed=setup(timeoutRoot,timeoutRepo,waitExecutor),timedJob=timed.saved.get('review');timed.saved.update('review',timedJob.revision,{budgets:{timeoutMinutes:.0002,maximumRetries:0}});const timeoutRun=await timed.engine.execute(timed.engine.runNow('review','operator').id);assert.equal(timeoutRun.status,'DISCONNECTED');assert.equal(timeoutRun.recovery?.reason,'timeout_cleanup_unproven');assert.match(timeoutRun.errors[0],/job_timeout_budget_exceeded/);const cancelRoot=fs.mkdtempSync(path.join(os.tmpdir(),'ac-cancel-')),cancelRepo=repository(cancelRoot),cancelled=setup(cancelRoot,cancelRepo,waitExecutor),created=cancelled.engine.runNow('review','operator'),pending=cancelled.engine.execute(created.id);while(cancelled.runs.get(created.id)?.status!=='RUNNING')await new Promise(resolve=>setTimeout(resolve,1));cancelled.engine.cancel(created.id,'operator');const cancelRun=await pending;assert.equal(cancelRun.status,'DISCONNECTED');assert.equal(cancelRun.recovery?.state,'CANCELLING');assert.match(cancelRun.errors[0],/cancelled_by:operator/)});

test('cancellation during retry backoff preserves intent and reconciles the exact execution once',async()=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-retry-cancel-')),repo=repository(root);let calls=0,cancelledExecution='';const executor:RepositoryReviewExecutor={execute:async()=>{calls++;throw new Error('provider_unavailable')},cancel:async(_run,execution)=>{cancelledExecution=execution.id;return{executionId:execution.id,state:'CANCELLED',cleanupConfirmed:true,observedAt:'2026-09-01T00:00:10.000Z'}}},setupResult=setup(root,repo,executor),saved=setupResult.saved.get('review');setupResult.saved.update('review',saved.revision,{budgets:{maximumRetries:2,retryBackoffSeconds:30,retryMaximumBackoffSeconds:30}});
  const retryEngine=new ParameterizedJobEngine(setupResult.definitions,setupResult.saved,setupResult.runs,setupResult.baselines,setupResult.engine.models,executor,{...setupResult.engine.options,wait:(_milliseconds,signal)=>new Promise<void>((_resolve,reject)=>{if(signal?.aborted)return reject(signal.reason);signal?.addEventListener('abort',()=>reject(signal.reason),{once:true})})}),created=retryEngine.runNow('review','operator'),pending=retryEngine.execute(created.id);
  while(setupResult.runs.get(created.id)?.status!=='RECONNECTING')await new Promise(resolve=>setTimeout(resolve,1));const executionId=setupResult.runs.get(created.id)?.activeExecution?.id;retryEngine.cancel(created.id,'operator');const disconnected=await pending;
  assert.equal(disconnected.status,'DISCONNECTED');assert.equal(disconnected.recovery?.state,'CANCELLING');assert.equal(disconnected.errors.filter(value=>value==='cancelled_by:operator').length,1);assert.equal(calls,1);assert.equal(executionId,disconnected.activeExecution?.id);
  const terminal=await retryEngine.reconcile(created.id);assert.equal(terminal.status,'CANCELLED');assert.equal(cancelledExecution,executionId);assert.equal(terminal.transitions.filter(value=>value.status==='CANCELLED').length,1);assert.equal(terminal.recovery?.reason,'cancellation_confirmed');
});

test('forbid-overlap rejects a second active Run and rewritten history never uses a non-ancestor baseline',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-rewrite-')),repo=repository(root),setupResult=setup(root,repo),queued=setupResult.engine.runNow('review','operator');assert.throws(()=>setupResult.engine.runNow('review','operator'),/overlap_forbidden/);await setupResult.engine.execute(queued.id);const first=setupResult.runs.get(queued.id)!.repository!.reviewedSha;command(repo,'git','checkout','--orphan','rewritten');for(const file of fs.readdirSync(repo))if(file!=='.git')fs.rmSync(path.join(repo,file),{recursive:true,force:true});fs.writeFileSync(path.join(repo,'new.ts'),'export const rewritten = true;\n');command(repo,'git','add','-A');command(repo,'git','commit','-qm','rewrite');command(repo,'git','branch','-M','main');setupResult.setTime(new Date('2026-09-02T00:00:00Z'));const second=await setupResult.engine.execute(setupResult.engine.runNow('review','operator').id);assert.notEqual(second.repository?.reviewedSha,first);assert.equal(second.repository?.comparisonSha,undefined);assert.ok(['SUCCEEDED','SUCCEEDED_WITH_FINDINGS'].includes(second.status))});

test('saved-job ingress rejects credentials and parameterized run state redacts provider echoes', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-parameterized-secret-')), repo = repository(root), setupResult = setup(root, repo), credential = ['nvapi', 'fixture', 'K'.repeat(24)].join('-');
  try {
    const saved = setupResult.saved.get('review');
    assert.throws(() => setupResult.saved.update('review', saved.revision, {name: `unsafe ${credential}`}), /saved_job_credential_material_forbidden/);
    const run = setupResult.engine.runNow('review', 'operator'), mutable = setupResult.runs.get(run.id)!;
    mutable.errors.push(`provider echoed ${credential}`);
    const updated = setupResult.runs.update(mutable);
    assert.equal(JSON.stringify(updated).includes(credential), false);
    assert.match(JSON.stringify(updated), /REDACTED/);
    assert.equal(fs.readFileSync(path.join(root, 'runs.json'), 'utf8').includes(credential), false);
  } finally {
    fs.rmSync(root, {recursive: true, force: true});
  }
});
