import {spawn} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import type {SkillTrainingInvocation,SkillTrainingPort,SkillTrainingResult} from './skill-learning.js';
import {hashDirectory} from './peft-specialist-execution.js';

export class LocalPeftSkillTrainingPort implements SkillTrainingPort {
  constructor(private readonly options:{python:string;runner:string;datasetRoot:string;outputRoot:string;bases:Array<{modelId:string;modelVersion:string;modelSha256:string;localPath:string}>;epochs:number;seed:number}){}
  async train(input:SkillTrainingInvocation):Promise<SkillTrainingResult>{if(input.resourceLimits.device!=='cpu')throw new Error('skill_training_device_unsupported');const base=this.options.bases.find(item=>item.modelId===input.base.modelId&&item.modelVersion===input.base.modelVersion&&item.modelSha256===input.base.modelSha256);if(!base)throw new Error('skill_training_base_binding_missing');for(const value of [this.options.python,this.options.runner,base.localPath])if(!fs.existsSync(value))throw new Error('skill_training_asset_missing');if(hashDirectory(base.localPath)!==input.base.modelSha256)throw new Error('skill_training_base_checksum_mismatch');const train=managed(input.dataset.trainingStorageRef,'managed://skill-datasets/',this.options.datasetRoot),evaluation=managed(input.dataset.evaluationStorageRef,'managed://skill-datasets/',this.options.datasetRoot),output=managed(input.outputStorageRef,'managed://skill-training/',this.options.outputRoot);if(!fs.existsSync(train)||!fs.existsSync(evaluation))throw new Error('skill_training_dataset_missing');const result=await run(this.options.python,[this.options.runner,'--mode','train','--model',base.localPath,'--model-identity',input.base.modelId,'--revision',input.base.modelVersion,'--train',train,'--eval',evaluation,'--output',output,'--epochs',String(this.options.epochs),'--seed',String(this.options.seed)],input.resourceLimits.maximumSeconds*1000),parsed=JSON.parse(result) as {status?:string;artefactSha256?:string;sizeBytes?:number;configSha256?:string;environmentSha256?:string;elapsedSeconds?:number};if(parsed.status!=='COMPLETE'||typeof parsed.artefactSha256!=='string'||typeof parsed.sizeBytes!=='number'||typeof parsed.configSha256!=='string'||typeof parsed.environmentSha256!=='string'||typeof parsed.elapsedSeconds!=='number')throw new Error('skill_training_result_invalid');const adapterPath=path.join(output,'adapter');if(hashDirectory(adapterPath)!==parsed.artefactSha256)throw new Error('skill_training_adapter_checksum_mismatch');return{status:'COMPLETE',adapter:{format:'peft-lora',artefactSha256:parsed.artefactSha256,sizeBytes:parsed.sizeBytes,storageRef:`${input.outputStorageRef}/adapter`},configurationSha256:parsed.configSha256,environmentSha256:parsed.environmentSha256,elapsedSeconds:parsed.elapsedSeconds};}
}
function managed(reference:string,prefix:string,root:string){if(!reference.startsWith(prefix))throw new Error('skill_training_storage_reference_invalid');const relative=reference.slice(prefix.length);if(!relative||relative.includes('..')||path.isAbsolute(relative))throw new Error('skill_training_storage_reference_invalid');const resolvedRoot=path.resolve(root),resolved=path.resolve(resolvedRoot,relative);if(resolved!==resolvedRoot&&!resolved.startsWith(resolvedRoot+path.sep))throw new Error('skill_training_storage_boundary_violation');return resolved;}
function run(command:string,args:string[],timeoutMs:number){return new Promise<string>((resolve,reject)=>{const child=spawn(command,args,{stdio:['ignore','pipe','pipe'],env:{PATH:process.env.PATH??'',HOME:process.env.HOME??'',CUDA_VISIBLE_DEVICES:'',TOKENIZERS_PARALLELISM:'false'},windowsHide:true}),stdout:Buffer[]=[],timer=setTimeout(()=>{child.kill('SIGKILL');reject(new Error('skill_training_timeout'));},timeoutMs);child.stdout.on('data',value=>stdout.push(Buffer.from(value)));child.on('error',error=>{clearTimeout(timer);reject(error)});child.on('close',code=>{clearTimeout(timer);if(code!==0)return reject(new Error(`skill_training_process_failed:${code}`));const lines=Buffer.concat(stdout).toString('utf8').trim().split('\n'),last=lines.at(-1)?.trim();if(!last||last.length>65536)return reject(new Error('skill_training_output_invalid'));resolve(last)});});}
