import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {InMemoryTransport} from '@modelcontextprotocol/sdk/inMemory.js';
import {ChatGptComputerMcpAdapter,chatGptComputerTools,createChatGptComputerMcpServer} from './chatgpt-computer-mcp.js';
import {PhoneComputerTaskRuntime,type ComputerUseDispatch,type ComputerUsePort,type PhonePlan} from './phone-computer-task.js';

const phoneToken='phone-worker-test-token-00000001';
const worker={deviceId:'android:test-phone',workerId:'phone-worker',modelId:'local/structured-small',modelSha256:'a'.repeat(64),runtime:'llama.cpp',runtimeVersion:'test',bootId:'boot-1',sessionId:'session-1',endpoint:'http://127.0.0.1:8080/v1',authReference:'env:AGENT_CONTROL_PHONE_WORKER_TOKEN',authDigest:'d45710f549e6ffbb157cfc71b9bc0ab7c5dadd988200222a73f185b8c915ee4f',capabilities:['model.infer.structured'],health:'healthy' as const,thermalState:'nominal' as const,memoryAvailableBytes:null,batteryPercent:null,charging:null,observedAt:'2026-09-19T00:00:00.000Z'};
const usage={inputTokens:12,cachedInputTokens:null,freshInputTokens:null,outputTokens:5,reasoningTokens:null};
const safePlan:PhonePlan={summary:'Open the test page and capture it',steps:[{action:'navigate',url:'https://test.example/status'},{action:'screenshot',name:'result'}],usage,latencyMs:25};

function fixture(t:test.TestContext,custom?:ComputerUsePort){const root=fs.mkdtempSync(path.join(os.tmpdir(),'phone-computer-task-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));let resolve:(value:any)=>void=()=>{},cancelled=false;const completion=new Promise<any>(r=>resolve=r);const computer=custom??{dispatch:async()=>({runId:'computer-run-1',completion,cancel:async()=>{cancelled=true;return{descendantsTerminated:true,evidence:['cleanup:confirmed']};}})};const runtime=new PhoneComputerTaskRuntime(path.join(root,'tasks.json'),computer,{allowedTargetWorkers:['pc-worker'],allowedHosts:['test.example'],now:(()=>{let n=0;return()=>`2026-09-19T00:00:${String(n++).padStart(2,'0')}.000Z`;})()});runtime.registerPhoneWorker(worker);return{root,runtime,resolve,cancelled:()=>cancelled};}

test('authenticated outbound worker proposes a bounded plan and Agent Control dispatches it',async t=>{const f=fixture(t),adapter=new ChatGptComputerMcpAdapter(f.runtime,'chatgpt-user:ed','pc-worker'),created=await adapter.call('start_computer_task',{request:'Open the harmless status page'} as any) as any,lease=f.runtime.claim('phone-worker',phoneToken)!;assert.equal(lease.taskId,created.id);assert.equal(lease.modelId,'local/structured-small');const submitted=await f.runtime.submitPlan('phone-worker',phoneToken,created.id,safePlan);assert.equal(submitted.state,'COMPUTER_RUNNING');f.resolve({engine:'fixture',finalUrl:'https://test.example/status',title:'Test',interactions:2,startedAt:'2026-09-19T00:00:05.000Z',completedAt:'2026-09-19T00:00:06.000Z',values:{text:'ok'},screenshots:[{name:'result',mediaType:'image/png',base64:'private-image',sha256:'b'.repeat(64)}],downloads:[],usage:{inputTokens:null,outputTokens:null,monetaryCost:null}});await new Promise(r=>setImmediate(r));const status=await adapter.call('get_task_status',{taskId:created.id}) as any;assert.equal(status.state,'SUCCEEDED');assert.equal(status.request,'[protected request retained in authorised evidence]');assert.equal(status.latestScreenshot.base64,'[protected]');const evidence=await adapter.call('get_task_evidence',{taskId:created.id}) as any;assert.equal(evidence.request,'Open the harmless status page');assert.equal(evidence.model.modelId,'local/structured-small');assert.equal(evidence.plan.usage.cachedInputTokens,null);});

test('consequential proposal waits for the exact approval and rejection is durable',async t=>{const f=fixture(t),task=f.runtime.create({actorId:'chatgpt-user:ed',request:'Enter test text then submit',targetWorkerId:'pc-worker'}),lease=f.runtime.claim('phone-worker',phoneToken)!,plan:PhonePlan={...safePlan,steps:[{action:'navigate',url:'https://test.example/form'},{action:'enterText',selector:'#test-text',text:'harmless'},{action:'submit',selector:'#test-form'}]};assert.equal(lease.taskId,task.id);const waiting=await f.runtime.submitPlan('phone-worker',phoneToken,task.id,plan);assert.equal(waiting.state,'WAITING_FOR_APPROVAL');await assert.rejects(()=>f.runtime.approve(task.id,'wrong','operator'),/approval_not_waiting/);const rejected=f.runtime.reject(task.id,waiting.pendingApproval!.id,'operator');assert.equal(rejected.state,'REJECTED');const restored=new PhoneComputerTaskRuntime(path.join(f.root,'tasks.json'),{dispatch:async()=>{throw Error('must not dispatch')}} as any,{allowedTargetWorkers:['pc-worker'],allowedHosts:['test.example']});assert.equal(restored.status(task.id).state,'REJECTED');});

test('cancellation fence is persisted before descendant abort and cleanup is required',async t=>{let runtime!:PhoneComputerTaskRuntime,taskId='';const root=fs.mkdtempSync(path.join(os.tmpdir(),'phone-cancel-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const computer:ComputerUsePort={dispatch:async()=>({runId:'run',completion:new Promise(()=>{}),cancel:async()=>{const snapshot=JSON.parse(fs.readFileSync(path.join(root,'tasks.json'),'utf8'));assert.equal(snapshot.tasks.find((x:any)=>x.id===taskId).state,'CANCELLING');return{descendantsTerminated:true,evidence:['cleanup:confirmed']};}})};runtime=new PhoneComputerTaskRuntime(path.join(root,'tasks.json'),computer,{allowedTargetWorkers:['pc-worker'],allowedHosts:['test.example']});runtime.registerPhoneWorker(worker);const task=runtime.create({actorId:'actor',request:'View test',targetWorkerId:'pc-worker'});taskId=task.id;runtime.claim('phone-worker',phoneToken);await runtime.submitPlan('phone-worker',phoneToken,task.id,safePlan);const cancelled=await runtime.cancel(task.id,'actor');assert.equal(cancelled.state,'CANCELLED');assert.ok(runtime.evidence(task.id).evidence.includes('cleanup:confirmed'));});

test('phone identity is loopback-bound and credentials are references, never raw secrets',async t=>{const f=fixture(t);assert.throws(()=>f.runtime.registerPhoneWorker({...worker,workerId:'bad-public',endpoint:'https://public.example/v1'}),/must_be_loopback/);assert.throws(()=>f.runtime.registerPhoneWorker({...worker,workerId:'bad-secret',authReference:'sk-abcdefghijklmnopqrstuvwxyz012345'}),/auth_reference/);const task=f.runtime.create({actorId:'actor',request:'View test',targetWorkerId:'pc-worker'});assert.throws(()=>f.runtime.claim('phone-worker','wrong-reference'),/authentication_failed/);assert.equal(f.runtime.status(task.id).state,'QUEUED_FOR_PHONE');});

test('plans reject private destinations sensitive fields and unsupported direct-control actions',async t=>{const f=fixture(t),task=f.runtime.create({actorId:'actor',request:'test',targetWorkerId:'pc-worker'});f.runtime.claim('phone-worker',phoneToken);await assert.rejects(()=>f.runtime.submitPlan('phone-worker',phoneToken,task.id,{...safePlan,steps:[{action:'navigate',url:'http://127.0.0.1/admin'}]}),/destination_not_allowed/);await assert.rejects(()=>f.runtime.submitPlan('phone-worker',phoneToken,task.id,{...safePlan,steps:[{action:'enterText',selector:'#password',text:'secret'}]}),/sensitive_input_forbidden/);await assert.rejects(()=>f.runtime.submitPlan('phone-worker',phoneToken,task.id,{...safePlan,steps:[{action:'javascript',expression:'fetch(\"/\")',name:'x'}]} as any),/action_not_allowed/);});

test('restart reconstructs in-flight phone work without pretending it completed',t=>{const f=fixture(t),task=f.runtime.create({actorId:'actor',request:'test',targetWorkerId:'pc-worker'});f.runtime.claim('phone-worker',phoneToken);const restored=new PhoneComputerTaskRuntime(path.join(f.root,'tasks.json'),{dispatch:async()=>{throw Error('unused')}} as any,{allowedTargetWorkers:['pc-worker'],allowedHosts:['test.example']});assert.equal(restored.status(task.id).state,'PHONE_DISCONNECTED');assert.match(restored.evidence(task.id).error??'',/restart_requires_reconciliation/);});

test('MCP tool annotations distinguish reads and consequential mutations',()=>{const byName=Object.fromEntries(chatGptComputerTools.map(item=>[item.name,item]));assert.equal(byName.get_task_status.annotations.readOnlyHint,true);assert.equal(byName.get_task_evidence.annotations.readOnlyHint,true);assert.equal(byName.approve_action.annotations.destructiveHint,true);assert.equal(byName.cancel_task.annotations.destructiveHint,true);assert.equal(byName.start_computer_task.annotations.openWorldHint,false);});

test('official MCP client lists and invokes only the narrow governed tools',async t=>{const f=fixture(t),server=createChatGptComputerMcpServer(new ChatGptComputerMcpAdapter(f.runtime,'chatgpt-user:ed','pc-worker')),client=new Client({name:'qualification-client',version:'1'}),[clientTransport,serverTransport]=InMemoryTransport.createLinkedPair();t.after(async()=>{await client.close();await server.close();});await Promise.all([server.connect(serverTransport),client.connect(clientTransport)]);const listed=await client.listTools();assert.deepEqual(listed.tools.map(item=>item.name).sort(),chatGptComputerTools.map(item=>item.name).sort());const called=await client.callTool({name:'start_computer_task',arguments:{request:'Open the harmless status page'}});assert.equal(called.isError,undefined);const structured=called.structuredContent as any;assert.equal(structured.state,'QUEUED_FOR_PHONE');assert.equal(f.runtime.evidence(structured.id).actorId,'chatgpt-user:ed');});
