import assert from 'node:assert/strict';
import test from 'node:test';
import {once} from 'node:events';
import type {AddressInfo} from 'node:net';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {AgentControlService} from './application-service.js';
import {PtyRegistry} from './pty.js';
import {ActionRegistry, ArtifactStore, JobRuntime, ResourceLockManager, RunLedger, WorkerRegistry} from './job-runtime.js';
import {JobCatalog} from './job-catalog.js';
import {WorkParcelCoordinator, WorkParcelStore, type WorkParcelPlanner} from './work-parcels.js';
import {PoeRuntime, type PoeBenchmarkProposalInput} from './poe.js';
import {governedRequestOrigin} from './request-origin.js';
import {startWebDashboard} from './web-server.js';
import {defaultCapabilities, type LaneState, type WorkspaceState} from '../state.js';

const now=()=>new Date().toISOString();
function fixture(root:string){const lane:LaneState={id:1,name:'Primary',status:'waiting',model:'unassigned',reasoning:'medium',context:'0',lines:[],contract:{version:2,laneId:1,goal:'Await task',constraints:[],cwd:root,priority:1,mode:'auto',capabilities:defaultCapabilities(),resourceLocks:{},modelLock:null,sharedTaskIds:[],updatedAt:now()},baton:{version:1,laneId:1,revision:1,status:'waiting',progress:[],hypothesis:'',evidence:[],changes:[],nextAction:'wait',openQuestions:[],model:'unassigned',reasoning:'medium',updatedAt:now()},lease:{laneId:1,holder:null,acquiredAt:null,expiresAt:null}},state:WorkspaceState={version:1,paused:false,lastRestorePoint:null,lanes:[lane]},actions=new ActionRegistry();actions.register('benchmark.fixture@1.0.0',async()=>({evidence:['fixture-verified'],verification:['fixture-verified']}));const catalog=new JobCatalog(actions.ids());catalog.addJob({apiVersion:'agent-control/v1',kind:'Job',metadata:{id:'benchmark-job',name:'Benchmark Job',version:'1.0.0'},spec:{priority:'normal',concurrency:'queue',parameters:{},steps:[{id:'execute',action:'benchmark.fixture@1.0.0',requires:['benchmark'],verification:['fixture-verified']}]}});const workers=new WorkerRegistry();workers.register({id:'controller',capabilities:['benchmark'],health:'healthy',capacity:1,active:0,observedAt:now()});const runtime=new JobRuntime(catalog,actions,workers,new RunLedger(path.join(root,'runs.json')),new ArtifactStore(path.join(root,'artifacts')),new ResourceLockManager(path.join(root,'locks.json'))),planner:WorkParcelPlanner={plan:()=>{throw new Error('not used')}},parcels=new WorkParcelCoordinator(runtime,new WorkParcelStore(path.join(root,'parcels.json')),planner),service=new AgentControlService(state,new PtyRegistry(),undefined,'4.0.0-test',()=>{});service.configureProjection({jobRuntime:runtime,workParcels:parcels,resources:[{id:'controller',name:'Controller',platform:'linux',transport:'local',capabilities:['benchmark']}]});const poe=new PoeRuntime({file:path.join(root,'poe.json'),evidence:{overview:()=>service.poeEvidence(),resolve:reference=>service.poeEvidence(reference)},benchmark:{submit:({proposal,actor,requestKey,plan})=>{const origin=governedRequestOrigin({channel:'poe/dashboard',modality:'dashboard',receivedAt:now(),authentication:'dashboard-bearer',actorId:actor,authority:[`proposal:${proposal.id}`],messageReference:requestKey,identityReference:createHash('sha256').update(actor).digest('hex'),request:proposal.objective});const parcel=parcels.submitApprovedPlan(origin.request,actor,requestKey,plan,origin);return{parcelId:parcel.id}}},onEvent:event=>service.events.emit(event.type==='proposal.changed'?'poe.proposal_changed':'poe.conversation_changed',{conversationId:event.conversationId,state:event.state})});service.configureProjection({poe});return{service,poe,parcels,runtime};}
function proposal():PoeBenchmarkProposalInput{const common={tools:['benchmark'],contextPolicy:'same',fixtureSha256:'f'.repeat(64),softwareVersion:'1',hardwareClass:'controller',quantization:null,cacheState:'COLD' as const,authority:'QUALIFICATION',timeLimitMs:10000};return{decision:'Select route A or B',objective:'Run the smallest fair comparison',whyNewEvidenceIsNeeded:'No matched evidence exists',conditions:[{...common,route:{providerId:'a',modelId:'a',nodeId:'controller'},providerEndpoint:'a'},{...common,route:{providerId:'b',modelId:'b',nodeId:'controller'},providerEndpoint:'b'}],stages:[{id:'compare',name:'Compare',job:'benchmark-job@1.0.0'}],metrics:[{id:'verified',label:'Verified',kind:'OBJECTIVE',successCriterion:'Job verification passes',stageId:'compare'}],repetitions:1};}

test('authenticated POE API preserves causal lineage and submits a normal Work Parcel only after sealed approval',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'poe-api-')),value=fixture(root),server=startWebDashboard(value.service,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');t.after(()=>{server.close();fs.rmSync(root,{recursive:true,force:true})});const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`,headers={'Content-Type':'application/json',Authorization:'Bearer test-token'};assert.equal((await fetch(`${base}/api/poe`)).status,401);const conversation=await(await fetch(`${base}/api/poe/conversations`,{method:'POST',headers,body:'{"channel":"dashboard"}'})).json();const turn=await(await fetch(`${base}/api/poe/conversations/${encodeURIComponent(conversation.id)}/turns`,{method:'POST',headers,body:JSON.stringify({text:'What is Agent Control doing?'})})).json();assert.match(turn.turn.text,/Agent Control status/);const draft=await(await fetch(`${base}/api/poe/conversations/${encodeURIComponent(conversation.id)}/proposals`,{method:'POST',headers,body:JSON.stringify(proposal())})).json();assert.equal(value.parcels.list().length,0);const frozen=await(await fetch(`${base}/api/poe/proposals/${encodeURIComponent(draft.id)}/freeze`,{method:'POST',headers,body:JSON.stringify({revision:draft.revision})})).json();assert.equal(value.parcels.list().length,0);const response=await fetch(`${base}/api/poe/proposals/${encodeURIComponent(draft.id)}/approve`,{method:'POST',headers,body:JSON.stringify({revision:frozen.revision,frozenSha256:frozen.frozenSha256})});assert.equal(response.status,202);const submitted=await response.json(),parcel=value.parcels.get(submitted.execution.parcelId);assert.equal(parcel.status,'QUEUED');assert.equal(parcel.origin?.channel,'poe/dashboard');assert.equal(parcel.origin?.actorId,'web-operator');assert.equal(parcel.audit.planner.kind,'deterministic');assert.match(parcel.audit.planningRationale,/frozen, fairness-checked and explicitly approved/);assert.equal(value.service.snapshot().poe?.state,'OBSERVING_CREW');assert.equal('conversations' in value.service.snapshot().poe!,false);assert.ok(value.service.events.history().some(event=>event.type==='poe.proposal_changed'));});

test('POE approved parcel executes through the ordinary Job runtime and verifier boundary',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'poe-parcel-'));try{const value=fixture(root),conversation=value.poe.createConversation({actorId:'web-operator',channel:'dashboard'}),draft=value.poe.proposeBenchmark(conversation.id,proposal()),frozen=value.poe.freezeBenchmark(draft.id,draft.revision),submitted=value.poe.approveBenchmark(frozen.id,{revision:frozen.revision,frozenSha256:frozen.frozenSha256!,actor:'web-operator'});await value.parcels.tick();for(let count=0;count<30&&value.parcels.get(submitted.execution!.parcelId).status!=='SUCCEEDED';count++){await value.runtime.tick();await new Promise(resolve=>setImmediate(resolve));await value.parcels.tick();}const parcel=value.parcels.get(submitted.execution!.parcelId);assert.equal(parcel.status,'SUCCEEDED',JSON.stringify({parcel,runs:value.runtime.ledger.list()},null,2));assert.equal(parcel.decision?.outcome,'COMPLETE');assert.ok(parcel.audit.timeline.some(event=>event.type==='verification.completed'));assert.ok(parcel.context?.events.some(event=>event.type==='stage.completed'));}finally{fs.rmSync(root,{recursive:true,force:true});}});
