import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {MemoryRouteQualificationStore,type MemoryPairQualificationRecord,type MemoryRoleQualification,type MemoryRouteQualificationRecord} from './project-memory-route-qualification.js';
import {PROJECT_MEMORY_EXCHANGE_VERSION,type MemoryRouteIdentity} from './project-memory.js';

const route=(modelId:string):MemoryRouteIdentity=>({providerId:'provider',modelId,nodeId:'node'});
const qualified=(reason='Repeated physical success'):MemoryRoleQualification=>({eligibility:'QUALIFIED',maximumProvenMemoryBytes:2400,permittedRepairCount:1,reason});
const record=(modelId:string,overrides:Partial<MemoryRouteQualificationRecord>={}):MemoryRouteQualificationRecord=>({schema:'agent-control.memory-route-qualification/v1',route:route(modelId),runtimeVersion:'runtime-v1',contractVersion:PROJECT_MEMORY_EXCHANGE_VERSION,writer:qualified(),reader:qualified(),terminalClassification:'PASS',qualifiedAt:'2026-09-12T00:00:00.000Z',expiresAt:'2026-12-12T00:00:00.000Z',evidence:[`physical:${modelId}`],...overrides});
const pairing=(writer:string,reader:string,overrides:Partial<MemoryPairQualificationRecord>={}):MemoryPairQualificationRecord=>({schema:'agent-control.memory-pair-qualification/v1',writer:route(writer),reader:route(reader),contractVersion:PROJECT_MEMORY_EXCHANGE_VERSION,eligibility:'QUALIFIED',terminalClassification:'PASS',maximumProvenMemoryBytes:2400,permittedRepairCount:1,qualifiedAt:'2026-09-12T00:00:00.000Z',expiresAt:'2026-12-12T00:00:00.000Z',reason:'Repeated physical success',evidence:[`physical:${writer}-to-${reader}`],...overrides});

test('qualified writer and reader are admitted only within the physically proven size',()=>{const store=new MemoryRouteQualificationStore();store.set(record('writer'));store.set(record('reader'));store.setPair(pairing('writer','reader'));const allowed=store.assess({writer:route('writer'),reader:route('reader'),contractVersion:PROJECT_MEMORY_EXCHANGE_VERSION,memoryBytes:1800,now:'2026-09-13T00:00:00.000Z'});assert.equal(allowed.decision,'ALLOW');assert.equal(allowed.permittedRepairCount,1);const oversized=store.assess({writer:route('writer'),reader:route('reader'),contractVersion:PROJECT_MEMORY_EXCHANGE_VERSION,memoryBytes:2401,now:'2026-09-13T00:00:00.000Z'});assert.equal(oversized.decision,'DENY');assert.deepEqual(oversized.reasons,['writer-memory-size-unproven','reader-memory-size-unproven','pair-memory-size-unproven']);});

test('unsupported reader fails before execution and selects only its qualified governed escalation',()=>{const store=new MemoryRouteQualificationStore(),fallback=route('strong-reader');store.set(record('writer'));store.set(record('edge-reader',{reader:{eligibility:'UNSUPPORTED',maximumProvenMemoryBytes:2100,permittedRepairCount:1,reason:'Repeated semantic reconstruction failure'},terminalClassification:'UNSUPPORTED',requiredEscalationRoute:fallback,evidence:['physical:attempt-1','physical:attempt-2','physical:attempt-3']}));store.set(record('strong-reader'));store.setPair(pairing('writer','edge-reader',{eligibility:'UNSUPPORTED',terminalClassification:'UNSUPPORTED',reason:'Repeated semantic failure',requiredEscalationPair:{writer:route('writer'),reader:fallback}}));store.setPair(pairing('writer','strong-reader'));const result=store.assess({writer:route('writer'),reader:route('edge-reader'),contractVersion:PROJECT_MEMORY_EXCHANGE_VERSION,memoryBytes:1800,now:'2026-09-13T00:00:00.000Z'});assert.equal(result.decision,'ESCALATE');assert.deepEqual(result.selected,{writer:route('writer'),reader:fallback});assert.ok(result.reasons.includes('reader-unsupported'));assert.ok(result.reasons.includes('pair-unsupported'));assert.equal(result.records.some(item=>item.terminalClassification==='UNSUPPORTED'),true);});

test('missing, blocked, stale and wrong-contract qualifications fail closed',()=>{const store=new MemoryRouteQualificationStore();store.set(record('writer',{writer:{eligibility:'BLOCKED_EXTERNAL',maximumProvenMemoryBytes:null,permittedRepairCount:0,reason:'Credential unavailable'},terminalClassification:'BLOCKED_EXTERNAL'}));store.set(record('reader',{expiresAt:'2026-09-12T12:00:00.000Z'}));store.setPair(pairing('writer','reader'));const blocked=store.assess({writer:route('writer'),reader:route('reader'),contractVersion:PROJECT_MEMORY_EXCHANGE_VERSION,memoryBytes:1,now:'2026-09-13T00:00:00.000Z'});assert.equal(blocked.decision,'DENY');assert.deepEqual(blocked.reasons,['writer-blocked-external','reader-qualification-stale']);const missing=store.assess({writer:route('writer'),reader:route('reader'),contractVersion:'future-contract',memoryBytes:1});assert.equal(missing.decision,'DENY');assert.deepEqual(missing.reasons,['writer-qualification-missing','reader-qualification-missing','pair-qualification-missing']);});

test('qualification records persist owner-only without credential material',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'memory-route-'));try{const file=path.join(root,'qualifications.json'),store=new MemoryRouteQualificationStore(file),profileRoute={providerId:'provider',accountProfileId:'opaque-profile',modelId:'reader',nodeId:'remote-node'};store.set(record('reader',{route:profileRoute}));store.setPair({...pairing('reader','reader'),writer:profileRoute,reader:profileRoute});assert.equal(fs.statSync(file).mode&0o777,0o600);const text=fs.readFileSync(file,'utf8');assert.doesNotMatch(text,/token|password|secret|oauth/i);const reloaded=new MemoryRouteQualificationStore(file);assert.equal(reloaded.list().length,1);assert.equal(reloaded.listPairings().length,1);assert.equal(reloaded.list()[0].route.accountProfileId,'opaque-profile');}finally{fs.rmSync(root,{recursive:true,force:true});}});
