import {createHash,randomUUID} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

export const PROJECT_MEMORY_SCHEMA='agent-control.project-memory/v1' as const;
export const PROJECT_MEMORY_EXCHANGE_VERSION='agent-control.project-memory-exchange/v1' as const;
export type MemoryKind='PROJECT_FACT'|'DECISION'|'EXPERIMENT'|'MACHINE_CAPABILITY'|'MODEL_QUALIFICATION'|'UNRESOLVED_QUESTION'|'WORK_PARCEL_OUTCOME'|'BATON_SUMMARY'|'LESSON'|'REJECTED_APPROACH';
export type MemoryVerification='CANDIDATE'|'VERIFIED'|'SUPERSEDED'|'INVALID';
export interface MemoryRouteIdentity{providerId:string;accountProfileId?:string;modelId:string;nodeId:string}
export interface MemoryEvidenceBinding{id:string;sha256:string;authority:'AUTHORITATIVE'|'CORROBORATING'}
export interface ProjectMemoryRecord{schema:typeof PROJECT_MEMORY_SCHEMA;id:string;kind:MemoryKind;title:string;content:string;contentSha256:string;factKey?:string;projectId:string;repositoryId?:string;sessionId?:string;originatingNodeId:string;originatingRoute?:MemoryRouteIdentity;source:'AGENT_CONTROL'|'ASSISTANT_MEMORY'|'OPERATOR'|'REPOSITORY'|'EXPERIMENT';confidence:number;verification:MemoryVerification;createdAt:string;lastVerifiedAt:string;expiresAt?:string;revalidation?:string;provenance:MemoryEvidenceBinding[];supersedes:string[]}
export interface MemoryCandidate extends Omit<ProjectMemoryRecord,'schema'|'id'|'contentSha256'|'createdAt'|'lastVerifiedAt'|'verification'>{id?:string;createdAt?:string;lastVerifiedAt?:string;verification?:MemoryVerification}
export interface MemoryRecallIntent{projectId:string;query:string;repositoryId?:string;sessionId?:string;limit?:number;now?:string;maximumBytes?:number}
export interface MemoryRecallRejection{id:string;reason:'WRONG_SCOPE'|'UNVERIFIED'|'STALE'|'SUPERSEDED'|'CONFLICT'|'INVALID_PROVENANCE'|'LOW_RELEVANCE'}
export interface MemoryRecallResult{candidates:number;accepted:Array<{memory:ProjectMemoryRecord;score:number;method:'METADATA'|'LEXICAL'}>;rejected:MemoryRecallRejection[];conflicts:Array<{factKey:string;memoryIds:string[]}>;bytesInjected:number;estimatedTokens:number;latencyMs:number}
export interface ProjectMemoryPort{remember(candidate:MemoryCandidate):Promise<ProjectMemoryRecord>;recall(intent:MemoryRecallIntent):Promise<MemoryRecallResult>;invalidate(id:string,reason:string):Promise<void>;health():Promise<{backendId:string;available:boolean}>}

/** Canonical bounded interchange shape for model-produced project memories. */
export interface ProjectMemoryExchange{objective:string;completedWork:string;decisions:string;rejectedApproaches:string;currentState:string;outstandingWork:string;supportingEvidence:string;nextAction:string;authority:string}
export const PROJECT_MEMORY_EXCHANGE_SCHEMA={type:'object',properties:{objective:{type:'string'},completedWork:{type:'string'},decisions:{type:'string'},rejectedApproaches:{type:'string'},currentState:{type:'string'},outstandingWork:{type:'string'},supportingEvidence:{type:'string'},nextAction:{type:'string'},authority:{type:'string'}},required:['objective','completedWork','decisions','rejectedApproaches','currentState','outstandingWork','supportingEvidence','nextAction','authority'],additionalProperties:false} as const;
export function projectMemoryExchangeFailures(value:unknown){if(!record(value))return['application_schema:root:not_object'];const required=PROJECT_MEMORY_EXCHANGE_SCHEMA.required,failures=required.filter(key=>!(key in value)).map(key=>`application_schema:${key}:required`);for(const key of required)if(key in value&&(typeof value[key]!=='string'||!(value[key] as string).trim()))failures.push(`application_schema:${key}:non_empty_string`);for(const key of Object.keys(value))if(!required.includes(key as typeof required[number]))failures.push(`application_schema:${key}:additional_property`);return failures;}
export function renderProjectMemoryExchange(value:ProjectMemoryExchange){const failures=projectMemoryExchangeFailures(value);if(failures.length)throw new Error(`project_memory_exchange_invalid:${failures.join('|')}`);return`Objective\n${value.objective.trim()}\n\nCompleted work\n${value.completedWork.trim()}\n\nDecisions\n${value.decisions.trim()}\n\nRejected approaches\n${value.rejectedApproaches.trim()}\n\nCurrent state\n${value.currentState.trim()}\n\nOutstanding work\n${value.outstandingWork.trim()}\n\nSupporting evidence\n${value.supportingEvidence.trim()}\n\nExact next action\n${value.nextAction.trim()}\n\nAuthority\n${value.authority.trim()}`;}

/** Generic Markdown-directory backend. Obsidian can view it but is not a dependency. */
export class MarkdownProjectMemoryPort implements ProjectMemoryPort{
  constructor(private readonly root:string,private readonly backendId='markdown-directory',private readonly clock=()=>new Date().toISOString()){}
  async remember(candidate:MemoryCandidate){validateCandidate(candidate);return this.withLock(async()=>{const now=this.clock(),id=candidate.id??`memory-${randomUUID()}`,record:ProjectMemoryRecord={...candidate,schema:PROJECT_MEMORY_SCHEMA,id,contentSha256:hash(candidate.content),verification:candidate.verification??'CANDIDATE',createdAt:candidate.createdAt??now,lastVerifiedAt:candidate.lastVerifiedAt??now,supersedes:[...new Set(candidate.supersedes)]};validateRecord(record);fs.mkdirSync(this.root,{recursive:true,mode:0o700});const target=this.file(id),temporary=`${target}.${process.pid}.${randomUUID()}.tmp`;fs.writeFileSync(temporary,render(record),{mode:0o600,flag:'wx'});fs.renameSync(temporary,target);return structuredClone(record);});}
  async recall(intent:MemoryRecallIntent){const started=Date.now(),all=this.readAll(),now=Date.parse(intent.now??this.clock()),rejected:MemoryRecallRejection[]=[],eligible:ProjectMemoryRecord[]=[];for(const memory of all){if(memory.projectId!==intent.projectId||(intent.repositoryId&&memory.repositoryId!==intent.repositoryId)||(memory.sessionId&&intent.sessionId&&memory.sessionId!==intent.sessionId)){rejected.push({id:memory.id,reason:'WRONG_SCOPE'});continue;}if(memory.verification==='INVALID'||!memory.provenance.length){rejected.push({id:memory.id,reason:'INVALID_PROVENANCE'});continue;}if(memory.verification!=='VERIFIED'){rejected.push({id:memory.id,reason:memory.verification==='SUPERSEDED'?'SUPERSEDED':'UNVERIFIED'});continue;}if(memory.expiresAt&&Date.parse(memory.expiresAt)<=now){rejected.push({id:memory.id,reason:'STALE'});continue;}eligible.push(memory);}const superseded=new Set(eligible.flatMap(item=>item.supersedes));for(const memory of eligible.filter(item=>superseded.has(item.id)))rejected.push({id:memory.id,reason:'SUPERSEDED'});const current=eligible.filter(item=>!superseded.has(item.id)),groups=new Map<string,ProjectMemoryRecord[]>();for(const memory of current)if(memory.factKey)groups.set(memory.factKey,[...(groups.get(memory.factKey)??[]),memory]);const conflicts=[...groups].filter(([,items])=>new Set(items.map(item=>item.contentSha256)).size>1).map(([factKey,items])=>({factKey,memoryIds:items.map(item=>item.id).sort()})),conflicting=new Set(conflicts.flatMap(item=>item.memoryIds));for(const id of conflicting)rejected.push({id,reason:'CONFLICT'});const terms=tokens(intent.query),ranked=current.filter(item=>!conflicting.has(item.id)).map(memory=>({memory,score:score(memory,terms),method:(memory.projectId===intent.projectId&&(!intent.repositoryId||memory.repositoryId===intent.repositoryId)?'METADATA':'LEXICAL') as 'METADATA'|'LEXICAL'})).sort((a,b)=>b.score-a.score||b.memory.lastVerifiedAt.localeCompare(a.memory.lastVerifiedAt)||a.memory.id.localeCompare(b.memory.id));for(const item of ranked.filter(item=>item.score<=0))rejected.push({id:item.memory.id,reason:'LOW_RELEVANCE'});const limit=Math.min(Math.max(intent.limit??8,1),50),max=Math.min(Math.max(intent.maximumBytes??32768,256),262144),accepted:Array<{memory:ProjectMemoryRecord;score:number;method:'METADATA'|'LEXICAL'}>=[];let bytes=0;for(const item of ranked.filter(item=>item.score>0)){const size=Buffer.byteLength(item.memory.content);if(accepted.length>=limit||bytes+size>max)break;accepted.push(item);bytes+=size;}return{candidates:all.length,accepted:structuredClone(accepted),rejected,conflicts,bytesInjected:bytes,estimatedTokens:Math.ceil(bytes/4),latencyMs:Date.now()-started};}
  async invalidate(id:string,reason:string){if(!reason.trim())throw new Error('memory_invalidation_reason_required');await this.withLock(async()=>{const record=this.read(id);record.verification='INVALID';record.revalidation=reason;record.lastVerifiedAt=this.clock();const target=this.file(id),temporary=`${target}.${process.pid}.tmp`;fs.writeFileSync(temporary,render(record),{mode:0o600});fs.renameSync(temporary,target);});}
  async health(){try{fs.mkdirSync(this.root,{recursive:true,mode:0o700});fs.accessSync(this.root,fs.constants.R_OK|fs.constants.W_OK);return{backendId:this.backendId,available:true};}catch{return{backendId:this.backendId,available:false};}}
  read(id:string){const record=parse(fs.readFileSync(this.file(id),'utf8'));validateRecord(record);return record;}
  private readAll(){if(!fs.existsSync(this.root))return[];return fs.readdirSync(this.root).filter(name=>name.endsWith('.md')).sort().map(name=>parse(fs.readFileSync(path.join(this.root,name),'utf8')));}
  private file(id:string){if(!/^[A-Za-z0-9._-]{1,160}$/.test(id))throw new Error('memory_id_invalid');return path.join(this.root,`${id}.md`);}
  private async withLock<T>(fn:()=>Promise<T>){fs.mkdirSync(this.root,{recursive:true,mode:0o700});const lock=path.join(this.root,'.agent-control-write.lock');let descriptor:number;try{descriptor=fs.openSync(lock,'wx',0o600);}catch{throw new Error('memory_store_write_conflict');}try{return await fn();}finally{fs.closeSync(descriptor);fs.unlinkSync(lock);}}
}

function validateCandidate(value:MemoryCandidate){if(!value.projectId?.trim()||!value.title?.trim()||!value.content?.trim()||!value.originatingNodeId?.trim())throw new Error('memory_candidate_invalid');if(!Number.isFinite(value.confidence)||value.confidence<0||value.confidence>1)throw new Error('memory_confidence_invalid');if(!value.provenance?.length||value.provenance.some(item=>!item.id.trim()||!/^[a-f0-9]{64}$/.test(item.sha256)))throw new Error('memory_provenance_invalid');}
function validateRecord(value:ProjectMemoryRecord){validateCandidate(value);if(value.schema!==PROJECT_MEMORY_SCHEMA||hash(value.content)!==value.contentSha256)throw new Error('memory_integrity_invalid');}
function render(record:ProjectMemoryRecord){return`<!-- agent-control-memory\n${JSON.stringify(record)}\n-->\n\n# ${record.title.replace(/[\r\n]+/g,' ')}\n\n${record.content.trim()}\n`;}
function parse(text:string){const match=/^<!-- agent-control-memory\n([^\n]+)\n-->/.exec(text);if(!match)throw new Error('memory_document_invalid');return JSON.parse(match[1]) as ProjectMemoryRecord;}
function hash(value:string){return createHash('sha256').update(value).digest('hex');}
function record(value:unknown):value is Record<string,unknown>{return Boolean(value&&typeof value==='object'&&!Array.isArray(value));}
function tokens(value:string){return [...new Set(value.toLowerCase().split(/[^a-z0-9._-]+/).filter(item=>item.length>1))];}
function score(memory:ProjectMemoryRecord,terms:string[]){if(!terms.length)return memory.confidence;const haystack=`${memory.title} ${memory.content} ${memory.kind} ${memory.factKey??''}`.toLowerCase(),matches=terms.filter(term=>haystack.includes(term)).length;return matches/terms.length+.1*memory.confidence;}
