import type {RuntimeMapProjection} from './runtime-map.js';
/** Public presentation is an allowlisted projection, never a mask over recoverable private fields. */
export function publicRuntimeMap(source:RuntimeMapProjection):RuntimeMapProjection {
  const ids=new Map(source.nodes.map((node,index)=>[node.id,`resource-${index+1}`]));
  const counters=new Map<string,number>();
  const counts=(source as RuntimeMapProjection&{estateCounts?:Record<string,unknown>}).estateCounts;
  const numericCounts=Object.fromEntries(Object.entries(counts??{}).map(([key,value])=>[key,typeof value==='number'&&Number.isFinite(value)?value:value&&typeof value==='object'?Object.fromEntries(Object.entries(value).filter(([,n])=>typeof n==='number'&&Number.isFinite(n))):null]));
  return {schema:source.schema,authority:source.authority,mapKind:source.mapKind,mode:source.mode,parcelId:source.parcelId?'public-capture':null,observedAt:source.observedAt,replayAt:source.replayAt,range:source.range,freshness:source.freshness,summary:source.summary,
    nodes:source.nodes.map(node=>{const index=(counters.get(node.type)??0)+1;counters.set(node.type,index);return {id:ids.get(node.id)!,type:node.type,label:node.type==='estate'?'Agent Control Estate':`${node.type.replaceAll('-',' ')} ${index}`,state:node.state,...(node.parentId&&ids.has(node.parentId)?{parentId:ids.get(node.parentId)}:{}),...(node.groupId&&ids.has(node.groupId)?{groupId:ids.get(node.groupId)}:{}),expandable:node.expandable,detail:{presentation:'PUBLIC',status:node.state,note:'Private names, addresses, paths, prompts and connection details are excluded from this view.'},evidence:[]};}),
    edges:source.edges.filter(edge=>ids.has(edge.from)&&ids.has(edge.to)).map((edge,index)=>({id:`connection-${index+1}`,from:ids.get(edge.from)!,to:ids.get(edge.to)!,kind:edge.kind,state:edge.state,label:edge.kind,evidence:[]})),events:[],controlRoom:[],limitations:['Public presentation: authentic topology and state with private identities and drill-down details excluded.'],...{estateCounts:numericCounts}};
}

export function publicDiscoveryProjection(source:{schema:string;latest:any;progress?:any}) {
  const sanitise=(items:any[])=>{const ids=new Map(items.map((item,index)=>[item.id,`resource-${index+1}`]));const nodes=new Map([...new Set(items.map(item=>item.nodeId))].map((id,index)=>[id,`machine-${index+1}`]));return items.map((item,index)=>({id:ids.get(item.id),kind:item.kind,label:`${String(item.kind).toLowerCase().replaceAll('_',' ')} ${index+1}`,nodeId:nodes.get(item.nodeId),health:item.health,lifecycle:item.lifecycle,resourceClasses:item.resourceClasses,operationalState:item.operationalState,change:item.change,fingerprint:'EXCLUDED_PUBLIC_PRESENTATION',attributes:{presentation:'PUBLIC'},provenance:(item.provenance??[]).map((p:any)=>({adapter:'discovery-adapter',method:'Details excluded from public presentation',observedAt:p.observedAt,authority:p.authority})),...(item.attention?{attention:'Needs attention; inspect privately for details.'}:{}),relatedIds:(item.relatedIds??[]).filter((id:string)=>ids.has(id)).map((id:string)=>ids.get(id))}));};
  const raw=source.latest,latest=raw?{schema:raw.schema,id:raw.id,mode:raw.mode,testing:raw.testing,startedAt:raw.startedAt,completedAt:raw.completedAt,includeRemote:raw.includeRemote,includeMemory:raw.includeMemory,status:raw.status,items:sanitise(raw.items),failures:raw.failures.map(()=>({adapter:'discovery-adapter',classification:'FAILED',detail:'Private details excluded'})),summary:raw.summary,recommendations:[]}:null;
  return {schema:source.schema,latest,scans:latest?[latest]:[],proposals:[],progress:source.progress?{scanId:source.progress.scanId,state:source.progress.state,startedAt:source.progress.startedAt,updatedAt:source.progress.updatedAt,adapters:source.progress.adapters.map((stage:any,index:number)=>({id:`adapter-${index+1}`,state:stage.state,found:stage.found})),items:sanitise(source.progress.items)}:null,presentation:'PUBLIC'};
}
