import test from 'node:test';import assert from 'node:assert/strict';
import {assessRelease,coreChecks,limitationsSchema,type CoreReceipt} from './release-readiness.js';
const item={id:'ENERGY-1',capability:'Whole-node energy',status:'BLOCKED_EXTERNAL',why:'No bound sensor',userImpact:'No measured whole-node comparison',workaround:'Use labelled component measurements',closure:'Qualified actual-watts sensor and machine binding',releaseBlocking:false,evidence:['sensor-discovery.json'],helpWanted:true,impact:'OPTIONAL_CAPABILITY'};
const register=()=>({schema:'agent-control.known-limitations/v1',version:'4.6.0-rc.1',items:[item]});
const receipt=():CoreReceipt=>({version:'4.6.0-rc.1',sourceDigest:'verified-source',checks:Object.fromEntries(coreChecks.map(c=>[c,{status:'PASS',evidence:[c+'.json']}]))});
test('externally blocked optional measurements preserve their status without failing a verified core',()=>{const report=assessRelease(register(),receipt(),{version:'4.6.0-rc.1',sourceDigest:'verified-source'},'PASS_WITH_LIMITATIONS');assert.equal(report.coreRelease,'PASS');assert.equal(report.knownLimitations.BLOCKED_EXTERNAL,1);assert.deepEqual(report.nonBlocking,['ENERGY-1']);assert.equal(report.publication,'REQUIRES_OPERATOR_REVIEW');});
test('missing, failed or unevidenced core checks block independently of showcase and optional limitations',()=>{for(const change of ['missing','failed','empty']){const r=receipt();if(change==='missing')delete r.checks.governanceSecurity;else r.checks.governanceSecurity={status:change==='failed'?'FAIL':'PASS',evidence:[]};assert.equal(assessRelease(register(),r,{version:r.version,sourceDigest:r.sourceDigest},'PASS').coreRelease,'FAIL');}});
test('core risks cannot be relabelled optional and source/version drift invalidates the receipt',()=>{assert.throws(()=>limitationsSchema.parse({...register(),items:[{...item,impact:'GOVERNANCE_SECURITY'}]}));assert.throws(()=>limitationsSchema.parse({...register(),items:[item,item]}));const r=receipt();assert.deepEqual(assessRelease(register(),r,{version:'changed',sourceDigest:'changed'},'PASS').releaseBlockers,['VERSION_MISMATCH','SOURCE_CHANGED_SINCE_VALIDATION']);});
test('a true classified blocker fails the core even when every execution check passed',()=>{const report=assessRelease({...register(),items:[{...item,id:'CORE-1',impact:'DATA_INTEGRITY',releaseBlocking:true}]},receipt(),{version:'4.6.0-rc.1',sourceDigest:'verified-source'},'PASS');assert.equal(report.coreRelease,'FAIL');assert.deepEqual(report.releaseBlockers,['CORE-1']);});
