import assert from 'node:assert/strict';
import test from 'node:test';
import {compareRuntimeMaps,projectRuntimeMap} from './runtime-map.js';

const start='2026-09-12T12:00:00.000Z',mid='2026-09-12T12:00:02.000Z',end='2026-09-12T12:00:04.000Z';
function fixture(count=6){
 const stages:any[]=Array.from({length:count},(_,i)=>({id:`branch-${i}`,name:`Review ${i}`,job:'review@1.0.0',dependsOn:[],parameters:{},requiredCapabilities:[],outputs:[],status:'SUCCEEDED',runId:`run-${i}`,startedAt:mid,endedAt:end,...(i===0?{baton:{schema:'agent-control.work-parcel-baton/v1',artifactIds:[],outputTypes:[]}}:{})}));
 stages.push({id:'aggregate',name:'Aggregate',job:'aggregate@1.0.0',dependsOn:Array.from({length:count},(_,i)=>`branch-${i}`),parameters:{},requiredCapabilities:[],outputs:[],status:'SUCCEEDED',runId:'run-aggregate',startedAt:end,endedAt:end});
 const parcel:any={id:'parcel-one',prompt:'Review safely',objective:'Parallel review',actor:'operator',origin:{channel:'dashboard',authentication:{state:'authenticated'}},status:'SUCCEEDED',planner:{kind:'deterministic',reason:'registered jobs'},stages,createdAt:start,updatedAt:end,endedAt:end,telemetry:{freshInputTokens:60,cachedInputTokens:20,outputTokens:10,reasoningTokens:null,totalTokens:90,cost:null,currency:null,elapsedMs:4000},decision:{outcome:'COMPLETE',title:'Verified result',summary:'All branches passed',evidence:['verification'],blockedStages:[],authority:'Agent Control'},audit:{schema:'agent-control.work-parcel-audit/v1',recordedAt:end,classification:'parallel',selectedExecution:'Work Parcel',planningRationale:'bounded fanout',planner:{kind:'deterministic',provider:null,model:null},alternatives:[],timeline:[{id:'a',at:start,type:'plan.selected',summary:'Plan selected',detail:'six branches'},{id:'b',at:mid,type:'baton.created',stageId:'branch-0',summary:'Baton sealed',detail:'integrity=abc'},{id:'c',at:mid,type:'cache.expert_selected',stageId:'branch-1',summary:'Warm route selected',detail:'reused=20'},{id:'d',at:end,type:'verification.completed',stageId:'aggregate',summary:'Verified',detail:'pass'}],invocations:[{id:'invoke-0',stageId:'branch-0',runId:'run-0',route:'provider/account/model@node',provider:'provider',model:'model',node:'node',profile:'STANDARD',startedAt:mid,completedAt:end,elapsedMs:2000,requestDispatched:true,usageAuthority:'authoritative',inputTokens:30,freshInputTokens:10,cachedInputTokens:20,outputTokens:5,reasoningTokens:null,totalTokens:35,providerReportedCost:null,calculatedCost:null,costBasis:'unavailable',currency:null,verifierResult:'PASS',outcome:'SUCCEEDED'}],totals:{models:['model'],invocations:1,inputTokens:30,freshInputTokens:10,cachedInputTokens:20,outputTokens:5,reasoningTokens:null,totalTokens:35,providerReportedCost:null,calculatedCost:null,cost:null,costBasis:'unavailable',currency:null,modelExecutionMs:2000,wallClockMs:4000}},provenance:[]};
 const runs:any[]=stages.map((stage:any,i)=>({id:stage.runId,jobId:stage.job.split('@')[0],jobVersion:'1.0.0',trigger:{type:'manual',actor:'operator',parcelContext:{parcelId:parcel.id,stageId:stage.id}},requestedAt:mid,status:'SUCCEEDED',priority:'normal',concurrency:'allow',parameters:{},steps:[{id:'execute',action:i===count?'verify.aggregate':'tool.review',status:'SUCCEEDED',dependsOn:[],capabilityRequest:{requires:[]},resources:[],attempts:[{workerId:`worker-${i}`}],artifactIds:[],verification:{required:['independent'],passed:['independent'],failed:[]},placement:{selected:`worker-${i}`,eligible:[],rejected:[]},startedAt:mid,endedAt:end}],artifacts:[],errors:[],effectiveJob:{},selectedWorkers:[`worker-${i}`],approvals:[],provenance:[],endedAt:end}));
 const sessions:any[]=[{id:'session-real',incarnation:'one',adapterId:'local-process',scope:{runId:'run-0',jobId:'review',jobVersion:'1.0.0',stepId:'execute',workerId:'worker-0',nodeId:'node',parcelId:parcel.id},state:'SUCCEEDED',command:'node verify.mjs',cwd:'/safe',capabilities:{terminal:'pipes',modes:{watch:true,intervene:false,takeControl:false},signals:[],interactiveInput:false,resize:false,reconnectable:false},control:{owner:'agent',actorId:'agent:worker-0',generation:1,reconciliationRequired:false},attachments:[],createdAt:mid,startedAt:mid,updatedAt:end,endedAt:end,eventSequence:3,outputBytes:15,outputTruncated:false}];
 const sessionEvents:any[]=[{schema:'agent-control.execution-session-event/v1',sessionId:'session-real',sequence:1,at:mid,type:'session.started',actorId:'agent',detail:'started'},{schema:'agent-control.execution-session-event/v1',sessionId:'session-real',sequence:2,at:end,type:'output',actorId:'process',detail:'stream=stdout',stream:'stdout',text:'47 tests passed\n'}];
 return{parcel,runs,sessions,sessionEvents:(id:string)=>id==='session-real'?sessionEvents:[],now:end};
}

test('authoritative parcel, fan-out, aggregation, model, cache, baton and terminal records map to linked nodes',()=>{const map=projectRuntimeMap(fixture());for(const type of ['request','poe','planner','work-parcel','parallel-lane','job','worker','model-call','cache','baton','terminal','validation','aggregation','result'])assert.ok(map.nodes.some(n=>n.type===type),type);assert.ok(map.edges.some(e=>e.kind==='dependency'));assert.equal(map.controlRoom.length,7);assert.match(String(map.nodes.find(n=>n.type==='terminal')?.detail.latestSafeOutput),/47 tests passed/)});
test('replay restores waiting, running and completed states from authoritative timestamps',()=>{const source=fixture(),before=projectRuntimeMap({...source,replayAt:'2026-09-12T11:59:59Z'}),during=projectRuntimeMap({...source,replayAt:'2026-09-12T12:00:03Z'}),after=projectRuntimeMap({...source,replayAt:end});assert.equal(before.nodes.find(n=>n.type==='job')?.state,'WAITING');assert.equal(during.nodes.find(n=>n.type==='job')?.state,'RUNNING');assert.equal(after.nodes.find(n=>n.type==='job')?.state,'SUCCEEDED');assert.equal(during.mode,'REPLAY')});
test('aggregation remains waiting while independent roots are still running',()=>{const source=fixture();source.parcel.status='RUNNING';source.parcel.endedAt=undefined;source.parcel.decision={...source.parcel.decision,outcome:'IN_PROGRESS'};for(const stage of source.parcel.stages){stage.status='RUNNING';stage.endedAt=undefined;}for(const run of source.runs){run.status='RUNNING';run.endedAt=undefined;for(const step of run.steps){step.status='RUNNING';step.endedAt=undefined;}}const map=projectRuntimeMap(source);const aggregate=map.nodes.find(node=>node.type==='aggregation')!;assert.equal(aggregate.state,'WAITING');assert.equal(aggregate.detail.branches,6);assert.equal(aggregate.detail.stages,7)});
test('failed, blocked, degraded and retry states remain visually distinct',()=>{const source=fixture(1);source.runs[0].status='DEGRADED';source.runs[0].steps[0].status='RETRY_PENDING';source.runs[0].steps[0].attempts.push({workerId:'worker-0'});source.parcel.stages[0].status='FAILED';const map=projectRuntimeMap(source);assert.ok(map.nodes.some(n=>n.type==='retry'&&n.state==='DEGRADED'));assert.ok(map.nodes.some(n=>n.state==='FAILED'))});
test('redaction occurs before graph evidence and drill-down metadata are returned',()=>{const source=fixture(1);source.parcel.stages[0].error='Bearer abcdefghijklmnopqrstuvwxyz123456';const text=JSON.stringify(projectRuntimeMap(source));assert.doesNotMatch(text,/abcdefghijklmnopqrstuvwxyz123456/);assert.match(text,/REDACTED/)});
test('large and nested 50-job topologies remain bounded deterministic projections',()=>{const source=fixture(55),started=performance.now(),first=projectRuntimeMap(source),elapsed=performance.now()-started,second=projectRuntimeMap(source);assert.ok(first.nodes.length>200);assert.ok(first.summary.groups>=56);assert.equal(first.edges.length,second.edges.length);assert.ok(elapsed<250,`projection ${elapsed}ms`)});
test('compare reports structural and operational deltas without changing either execution',()=>{const small=projectRuntimeMap(fixture(1)),large=projectRuntimeMap(fixture(6)),comparison=compareRuntimeMaps(small,large);assert.ok(comparison.deltas.nodes>0);assert.equal(comparison.deltas.modelCalls,0);assert.equal(comparison.identity.labelMatching,false);assert.equal(small.parcelId,'parcel-one')});
test('compare uses explicit route and evidence identities rather than matching display labels',()=>{const left=projectRuntimeMap(fixture(1)),source=fixture(1);source.parcel.id='parcel-two';source.parcel.audit.invocations[0].route='provider-b/account-b/model-b@node-b';source.parcel.audit.invocations[0].provider='provider-b';source.parcel.audit.invocations[0].node='node-b';source.parcel.audit.invocations[0].model='model-b';const leftModel=left.nodes.find(node=>node.type==='model-call')!;leftModel.label='same-display-label';const right=projectRuntimeMap(source),rightModel=right.nodes.find(node=>node.type==='model-call')!;rightModel.label='same-display-label';const comparison=compareRuntimeMaps(left,right);assert.deepEqual(comparison.facets.models.added,['model-b']);assert.deepEqual(comparison.facets.models.removed,['model']);assert.ok(comparison.facets.routes.added.includes('provider-b/account-b/model-b@node-b'));assert.ok(comparison.facets.routes.removed.includes('provider/account/model@node'));assert.equal(comparison.identity.strategy,'independent-authoritative-facets')});
test('missing telemetry remains unavailable rather than fabricated',()=>{const map=projectRuntimeMap({...fixture(1),sessions:[],sessionEvents:()=>[]});const invocation=map.nodes.find(n=>n.type==='model-call')!;assert.equal(invocation.detail.cost,null);assert.equal(invocation.detail.costBasis,'unavailable')});
test('governor, decision, approval, escalation, verification and retrieval records retain their authoritative reasons',()=>{const source:any=fixture(1);source.parcel.audit.timeline.push(
 {id:'route',at:mid,type:'route.resolved',stageId:'branch-0',summary:'Selected qualified route',detail:'capability and policy matched'},
 {id:'approval',at:mid,type:'question.created',stageId:'branch-0',summary:'Approval required',detail:'mutation exceeds lane authority'},
 {id:'exhausted',at:end,type:'retry.exhausted',stageId:'branch-0',summary:'Retries exhausted',detail:'validation remained red'},
 {id:'criterion',at:end,type:'criterion.evaluated',stageId:'branch-0',summary:'Independent criterion passed',detail:'evidence hash matched'});
 source.tokenRouting={decisions:[{id:'governed-route',at:mid,threadId:'thread-1',parcelId:'parcel-one',state:'PREPARE_BATON',action:'BATON_AND_HANDOFF',reason:'bounded mechanical continuation',trigger:{kind:'QUALITY_GATE',code:'verification_retry',reason:'quality gate requested escalation',evidence:['gate:1']},contextPercent:88,target:{providerId:'provider-b',modelId:'model-b',nodeId:'node-b'},batonId:'token-baton:1',outcome:'SUCCEEDED'}]};
 source.retrieval={attempts:[{id:'memory-1',at:mid,intentId:'intent-1',parcelId:'parcel-one',providerId:'your-memories',strategy:'HYBRID',outcome:'SUCCEEDED',reason:'validated durable memory matched',evidenceCount:2,evidenceTokens:140,freshness:'CURRENT',evidenceStatus:'SUFFICIENT',indexState:'CURRENT',latencyMs:4}]};
 const map=projectRuntimeMap(source);for(const type of ['decision','approval','escalation','validation','memory'])assert.ok(map.nodes.some(node=>node.type===type),type);const governor=map.nodes.find(node=>node.id==='governor:governed-route')!;assert.equal(governor.type,'baton');assert.equal(governor.detail.contextPercent,88);assert.match(JSON.stringify(governor.detail),/verification_retry/);assert.ok(map.events.some(item=>item.kind==='governor.decision'))});
test('replay excludes future governor and memory records',()=>{const source:any=fixture(1);source.tokenRouting={decisions:[{id:'future',at:end,threadId:'thread',parcelId:'parcel-one',state:'CONTINUE',action:'CONTINUE',reason:'within policy',contextPercent:12,outcome:'RECORDED'}]};source.retrieval={attempts:[{id:'future-memory',at:end,intentId:'intent',parcelId:'parcel-one',providerId:'local',strategy:'EXACT',outcome:'SUCCEEDED',reason:'found',evidenceCount:1,evidenceTokens:20,freshness:'CURRENT',evidenceStatus:'SUFFICIENT',indexState:'CURRENT',latencyMs:1}]};const map=projectRuntimeMap({...source,replayAt:mid});assert.equal(map.nodes.some(node=>node.id==='governor:future'),false);assert.equal(map.nodes.some(node=>node.id==='retrieval:future-memory'),false)});

test('direct provider sessions connect to their explicit parcel when no job-step record exists',()=>{
 const source=fixture(1);source.runs=[];source.sessions[0].scope.runId='direct-review-run';source.sessions[0].scope.stepId='repository-review:chunk-one';
 const map=projectRuntimeMap(source),terminal=map.nodes.find(n=>n.type==='terminal')!;
 assert.equal(terminal.parentId,`parcel:${source.parcel.id}`);
 assert.ok(map.edges.some(e=>e.from===terminal.parentId&&e.to===terminal.id&&e.kind==='contains'));
});

test('a recorded CONTINUE decision does not imply an active process',()=>{
 const source:any=fixture(1);source.tokenRouting={decisions:[{id:'recorded',at:mid,threadId:'thread',parcelId:'parcel-one',state:'CONTINUE',action:'CONTINUE',reason:'within policy',contextPercent:12,outcome:'RECORDED'}]};
 const node=projectRuntimeMap(source).nodes.find(n=>n.id==='governor:recorded')!;
 assert.equal(node.state,'RECORDED');assert.equal(node.endedAt,mid);assert.equal(node.detail.outcome,'RECORDED');
});

test('current and compatibility Mallow channels appear as governed ingress in the normal process map',()=>{
 for(const channel of ['mallow/dashboard','poe/dashboard']){
  const source=fixture(1);source.parcel.origin={channel,modality:'voice-confirmed-by-text',authentication:'dashboard-bearer',authority:['voice-session:voice-test']};
  const map=projectRuntimeMap(source),mallow=map.nodes.find(n=>n.type==='poe');assert.equal(mallow?.label,'Mallow');assert.equal(mallow?.detail.modality,'voice-confirmed-by-text');assert.deepEqual(mallow?.detail.voiceEvidence,['voice-session:voice-test']);assert.ok(map.edges.some(e=>e.from===mallow?.id));
 }
});
