import fs from 'node:fs';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import type {SandboxQualification} from './execution-sandbox.js';

export const SECURITY_AUDIT_PHASES=['RECONNAISSANCE','COVERAGE_HUNTING','CANDIDATE_VALIDATION','STRUCTURED_FINDINGS','RECORD_VERIFICATION','REPORTING'] as const;
export type SecurityAuditPhase=typeof SECURITY_AUDIT_PHASES[number];
export type SecurityAuditVerdict='confirmed'|'needs_validation'|'rejected';
export type SecurityAuditProvenance='AGENT_CONTROL_NATIVE'|'EXTERNAL_HARNESS'|'STATIC_ONLY'|'EXECUTION_BLOCKED_BY_SANDBOX'|'OPERATOR_SUPPLIED_EVIDENCE';
export type CoverageStatus='covered'|'partial'|'blocked'|'unreviewed';
export type SandboxStatus='PASS'|'PARTIAL'|'FAIL';
export type IndependenceGrade='FULL'|'MODEL_INDEPENDENT'|'CONTEXT_INDEPENDENT'|'IDENTITY_SEPARATED'|'PARTIAL';

export interface SandboxAssurance{status:SandboxStatus;network:'DENIED'|'UNPROVEN';environment:'ALLOWLISTED'|'UNPROVEN';resources:'BOUNDED'|'UNPROVEN';writes:'SCRATCH_ONLY'|'UNPROVEN';processes:'TRACKED_AND_CLEANED'|'UNPROVEN';evidence:string[];reason:string;qualification?:{id:string;adapter:string;controls:Array<{id:string;status:'PASS'|'FAIL';evidenceSha256:string}>};}
export interface CoverageUnit{id:string;category:string;scope:string;sourceFiles:string[];status:CoverageStatus;methods:string[];evidence:string[];sourceRevision:string;updatedAt:string;}
export interface Candidate{id:string;title:string;description:string;category:string;sourceTrace:string[];preconditions:string[];trustBoundary:string;evidence:string[];finder:{invocationId:string;workerId:string;model?:string;provider?:string};createdAt:string;}
export interface Verification{candidateId:string;verifier:{invocationId:string;workerId:string;model?:string;provider?:string};independence:IndependenceGrade;verdict:SecurityAuditVerdict;reason:string;evidence:string[];verifiedAt:string;}
export interface Finding{schema:'agent-control.security-finding/v1';id:string;candidateId:string;verdict:SecurityAuditVerdict;title:string;category:string;sourceRevision:string;sourceTrace:string[];preconditions:string[];trustBoundary:string;reproduction:string[];impact:string;finder:Candidate['finder'];verification:Verification;confidence:'high'|'medium'|'low';severity?:'critical'|'high'|'medium'|'low'|'informational';severityRationale?:string;scope:string;limitations:string[];evidence:string[];}
export interface SecurityAuditEvent{sequence:number;at:string;type:string;actor:string;detail:Record<string,unknown>;previousHash:string|null;hash:string;}
export interface SecurityAuditRecord{schema:'agent-control.security-audit/v1';id:string;repositoryRoot:string;scope:string[];sourceRevision:string;baselineAuditId?:string;jobRunIds:string[];status:'CREATED'|'RUNNING'|'COMPLETE'|'FAILED';phase:SecurityAuditPhase;provenance:SecurityAuditProvenance[];sandbox:SandboxAssurance;coverage:CoverageUnit[];candidates:Candidate[];verifications:Verification[];findings:Finding[];findingHistory?:Finding[];artifacts:Record<string,{path:string;sha256:string}>;createdAt:string;updatedAt:string;events:SecurityAuditEvent[];}
interface Snapshot{version:1;audits:SecurityAuditRecord[];}

const iso=()=>new Date().toISOString();
const hash=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex');
const assertText=(value:unknown,name:string)=>{if(typeof value!=='string'||!value.trim())throw new Error(`security_audit_${name}_required`);};
function atomic(file:string,value:unknown){fs.mkdirSync(path.dirname(file),{recursive:true});const temporary=`${file}.tmp-${process.pid}`;fs.writeFileSync(temporary,`${JSON.stringify(value,null,2)}\n`,{mode:0o600});fs.renameSync(temporary,file);}
function within(root:string,target:string){const base=path.resolve(root),resolved=path.resolve(target);return resolved===base||resolved.startsWith(`${base}${path.sep}`);}
function artifact(file:string){const bytes=fs.readFileSync(file);return{path:file,sha256:hash(bytes)};}

export function assessSandbox(input:Partial<SandboxAssurance>):SandboxAssurance{
 const complete=input.network==='DENIED'&&input.environment==='ALLOWLISTED'&&input.resources==='BOUNDED'&&input.writes==='SCRATCH_ONLY'&&input.processes==='TRACKED_AND_CLEANED';
 const any=Object.values(input).some(value=>value&&value!=='UNPROVEN'&&value!==input.status);
 return{status:complete?'PASS':any?'PARTIAL':'FAIL',network:input.network??'UNPROVEN',environment:input.environment??'UNPROVEN',resources:input.resources??'UNPROVEN',writes:input.writes??'UNPROVEN',processes:input.processes??'UNPROVEN',evidence:[...(input.evidence??[])],reason:complete?'All target-execution guarantees are evidenced.':input.reason??'Target execution is blocked because one or more sandbox guarantees are unproven.',...(input.qualification?{qualification:structuredClone(input.qualification)}:{})};
}
export function canExecuteTarget(assurance:SandboxAssurance){return assurance.status==='PASS'&&assurance.network==='DENIED'&&assurance.environment==='ALLOWLISTED'&&assurance.resources==='BOUNDED'&&assurance.writes==='SCRATCH_ONLY'&&assurance.processes==='TRACKED_AND_CLEANED';}

export function validateFinding(value:Finding){
 if(value?.schema!=='agent-control.security-finding/v1')throw Error('security_finding_schema_invalid');
 for(const [name,item] of Object.entries({id:value.id,candidateId:value.candidateId,title:value.title,category:value.category,sourceRevision:value.sourceRevision,trustBoundary:value.trustBoundary,impact:value.impact,scope:value.scope}))assertText(item,name);
 if(!['confirmed','needs_validation','rejected'].includes(value.verdict))throw Error('security_finding_verdict_invalid');
 if(!value.finder?.invocationId||!value.verification?.verifier?.invocationId)throw Error('security_finding_identity_missing');
 if(value.finder.invocationId===value.verification.verifier.invocationId)throw Error('security_finding_self_verification');
 if(value.verification.candidateId!==value.candidateId||value.verification.verdict!==value.verdict)throw Error('security_finding_verification_binding_invalid');
 if(!value.sourceTrace.length||!value.evidence.length)throw Error('security_finding_evidence_missing');
 if(value.verdict==='confirmed'&&(!value.severity||!value.severityRationale?.trim()||!value.reproduction.length))throw Error('security_finding_confirmation_incomplete');
 if(value.verdict==='needs_validation'&&(value.severity!==undefined||value.severityRationale!==undefined))throw Error('security_finding_unresolved_severity_forbidden');
 if(value.verdict==='rejected'&&!value.verification.reason.trim())throw Error('security_finding_rejection_reason_missing');
 return structuredClone(value);
}

export class SecurityAuditStore{
 private readonly file:string;private readonly audits=new Map<string,SecurityAuditRecord>();
 constructor(readonly root:string){this.file=path.join(root,'audits.json');if(fs.existsSync(this.file)){const value=JSON.parse(fs.readFileSync(this.file,'utf8')) as Snapshot;if(value.version!==1)throw Error('security_audit_store_version_unsupported');for(const audit of value.audits){audit.jobRunIds??=[];audit.findingHistory??=[];if(!Array.isArray(audit.provenance))audit.provenance=[audit.provenance as unknown as SecurityAuditProvenance];let previous:string|null=null;for(const event of audit.events){const {hash:recorded,...body}=event;if(event.previousHash!==previous||hash(JSON.stringify(body))!==recorded)throw Error('security_audit_event_chain_invalid');previous=recorded;}this.audits.set(audit.id,audit);}}}
 list(){return[...this.audits.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(value=>structuredClone(value));}
 get(id:string){const value=this.audits.get(id);if(!value)throw Error('security_audit_missing');return structuredClone(value);}
 create(input:{repositoryRoot:string;scope?:string[];sourceRevision:string;baselineAuditId?:string;sandbox?:Partial<SandboxAssurance>;actor:string}){
  const root=path.resolve(input.repositoryRoot);if(!fs.statSync(root).isDirectory())throw Error('security_audit_repository_invalid');assertText(input.sourceRevision,'source_revision');
  const assurance=assessSandbox(input.sandbox??{}),at=iso(),record:SecurityAuditRecord={schema:'agent-control.security-audit/v1',id:`audit-${randomUUID()}`,repositoryRoot:root,scope:(input.scope?.length?input.scope:['.']).map(String),sourceRevision:input.sourceRevision,...(input.baselineAuditId?{baselineAuditId:input.baselineAuditId}:{}),jobRunIds:[],status:'CREATED',phase:'RECONNAISSANCE',provenance:['AGENT_CONTROL_NATIVE',...(canExecuteTarget(assurance)?[]:['STATIC_ONLY' as const,'EXECUTION_BLOCKED_BY_SANDBOX' as const])],sandbox:assurance,coverage:[],candidates:[],verifications:[],findings:[],findingHistory:[],artifacts:{},createdAt:at,updatedAt:at,events:[]};
  this.event(record,'audit.created',input.actor,{sourceRevision:input.sourceRevision});this.audits.set(record.id,record);this.save();return this.get(record.id);
 }
 update(record:SecurityAuditRecord,type:string,actor:string,detail:Record<string,unknown>={}){if(!this.audits.has(record.id))throw Error('security_audit_missing');record.updatedAt=iso();this.event(record,type,actor,detail);this.audits.set(record.id,structuredClone(record));this.save();return this.get(record.id);}
 private event(record:SecurityAuditRecord,type:string,actor:string,detail:Record<string,unknown>){const previous=record.events.at(-1)?.hash??null,body={sequence:record.events.length+1,at:iso(),type,actor,detail,previousHash:previous},event={...body,hash:hash(JSON.stringify(body))};record.events.push(event);}
 private save(){atomic(this.file,{version:1,audits:this.list()} satisfies Snapshot);}
}

export class SecurityAuditRuntime{
 constructor(readonly store:SecurityAuditStore,readonly allowedRepositoryRoots:string[]){this.allowedRepositoryRoots=allowedRepositoryRoots.map(root=>path.resolve(root));}
 private assertRoot(root:string){if(!this.allowedRepositoryRoots.some(allowed=>within(allowed,root)))throw Error('security_audit_repository_not_allowed');}
 sourceSnapshot(id:string,root:string,revision:string){const audit=this.store.get(id),resolved=path.resolve(root);this.assertRoot(resolved);if(audit.sourceRevision!==revision)throw Error('security_audit_source_revision_mismatch');return resolved;}
 start(input:{repositoryRoot:string;scope?:string[];sourceRevision:string;baselineAuditId?:string;sandbox?:Partial<SandboxAssurance>;actor:string}){this.assertRoot(input.repositoryRoot);return this.store.create(input);}
 list(){return this.store.list();}get(id:string){return this.store.get(id);}
 linkRun(id:string,runId:string,actor:string){const audit=this.store.get(id);if(!audit.jobRunIds.includes(runId))audit.jobRunIds.push(runId);return this.store.update(audit,'audit.run_linked',actor,{runId});}
 recordCoverage(id:string,units:CoverageUnit[],actor:string){const audit=this.store.get(id),seen=new Set<string>();for(const unit of units){for(const [name,value] of Object.entries({id:unit.id,category:unit.category,scope:unit.scope,sourceRevision:unit.sourceRevision,updatedAt:unit.updatedAt}))assertText(value,`coverage_${name}`);if(seen.has(unit.id))throw Error('security_audit_coverage_duplicate');seen.add(unit.id);if(!['covered','partial','blocked','unreviewed'].includes(unit.status)||!Array.isArray(unit.sourceFiles)||!Array.isArray(unit.methods)||!Array.isArray(unit.evidence))throw Error('security_audit_coverage_invalid');}audit.coverage=units.map(unit=>structuredClone(unit));audit.status='RUNNING';audit.phase='COVERAGE_HUNTING';return this.store.update(audit,'coverage.recorded',actor,{units:units.length});}
 addCandidate(id:string,candidate:Candidate,actor:string){const audit=this.store.get(id);for(const [name,value] of Object.entries({id:candidate.id,title:candidate.title,description:candidate.description,category:candidate.category,trustBoundary:candidate.trustBoundary,createdAt:candidate.createdAt}))assertText(value,`candidate_${name}`);if(!candidate.sourceTrace.length||!candidate.evidence.length||!candidate.finder?.invocationId)throw Error('security_audit_candidate_invalid');const existing=audit.candidates.find(item=>item.id===candidate.id);if(existing){existing.evidence=[...new Set([...existing.evidence,...candidate.evidence])];existing.sourceTrace=[...new Set([...existing.sourceTrace,...candidate.sourceTrace])];return this.store.update(audit,'candidate.deduplicated',actor,{candidateId:candidate.id,evidence:existing.evidence.length});}audit.candidates.push(structuredClone(candidate));audit.phase='CANDIDATE_VALIDATION';return this.store.update(audit,'candidate.recorded',actor,{candidateId:candidate.id});}
 verify(id:string,verification:Verification,actor:string){const audit=this.store.get(id),candidate=audit.candidates.find(item=>item.id===verification.candidateId);if(!candidate)throw Error('security_audit_candidate_missing');if(candidate.finder.invocationId===verification.verifier.invocationId)throw Error('security_audit_self_verification');audit.verifications.push(structuredClone(verification));audit.phase='RECORD_VERIFICATION';return this.store.update(audit,'candidate.verified',actor,{candidateId:candidate.id,verdict:verification.verdict,independence:verification.independence});}
 addFinding(id:string,finding:Finding,actor:string){const audit=this.store.get(id),candidate=audit.candidates.find(item=>item.id===finding.candidateId),verification=audit.verifications.find(item=>item.candidateId===finding.candidateId&&item.verifier.invocationId===finding.verification.verifier.invocationId);if(!candidate||!verification)throw Error('security_finding_chain_incomplete');validateFinding(finding);if(audit.findings.some(item=>item.id===finding.id))throw Error('security_finding_exists');audit.findings.push(structuredClone(finding));audit.phase='STRUCTURED_FINDINGS';return this.store.update(audit,'finding.recorded',actor,{findingId:finding.id,verdict:finding.verdict});}
 qualifySandbox(id:string,qualification:SandboxQualification,actor:string){const audit=this.store.get(id);if(qualification.status!=='PASS'||!qualification.cleanupVerified||qualification.controls.some(control=>control.status!=='PASS'))throw Error('security_audit_sandbox_qualification_failed');audit.sandbox=assessSandbox({network:'DENIED',environment:'ALLOWLISTED',resources:'BOUNDED',writes:'SCRATCH_ONLY',processes:'TRACKED_AND_CLEANED',evidence:qualification.controls.map(control=>`${control.id}:${control.evidenceSha256}`),reason:'Host-enforced qualification passed every mandatory containment control.',qualification:{id:qualification.id,adapter:qualification.adapter,controls:qualification.controls.map(control=>({id:control.id,status:control.status,evidenceSha256:control.evidenceSha256}))}});return this.store.update(audit,'sandbox.qualified',actor,{qualificationId:qualification.id,adapter:qualification.adapter,controls:qualification.controls.length});}
 supersedeFinding(id:string,finding:Finding,actor:string){const audit=this.store.get(id),index=audit.findings.findIndex(item=>item.candidateId===finding.candidateId);if(index<0)throw Error('security_finding_missing');validateFinding(finding);audit.findingHistory??=[];audit.findingHistory.push(structuredClone(audit.findings[index]));audit.findings[index]=structuredClone(finding);audit.phase='STRUCTURED_FINDINGS';return this.store.update(audit,'finding.superseded',actor,{findingId:finding.id,verdict:finding.verdict,previousVerdict:audit.findingHistory.at(-1)?.verdict});}
 resume(id:string,actor:string){const audit=this.store.get(id);audit.status='RUNNING';return this.store.update(audit,'audit.resumed',actor,{phase:audit.phase,previouslyComplete:audit.events.some(event=>event.type==='audit.completed')});}
 compare(leftId:string,rightId:string){const left=this.store.get(leftId),right=this.store.get(rightId),leftMap=new Map(left.findings.map(item=>[item.id,item])),rightMap=new Map(right.findings.map(item=>[item.id,item]));return{schema:'agent-control.security-audit-comparison/v1',left:{id:left.id,revision:left.sourceRevision},right:{id:right.id,revision:right.sourceRevision},introduced:[...rightMap.keys()].filter(id=>!leftMap.has(id)),resolved:[...leftMap.keys()].filter(id=>!rightMap.has(id)),retained:[...rightMap.keys()].filter(id=>leftMap.has(id)),coverage:{left:left.coverage.length,right:right.coverage.length}};}
 revalidate(id:string,currentRevision:string,changedFiles:string[],actor:string){const audit=this.store.get(id),changed=new Set(changedFiles.map(file=>file.replaceAll('\\','/')));for(const unit of audit.coverage)if(unit.sourceFiles.some(file=>changed.has(file.replaceAll('\\','/')))){unit.status='unreviewed';unit.evidence=[...unit.evidence,`stale_after:${currentRevision}`];unit.updatedAt=iso();}audit.sourceRevision=currentRevision;return this.store.update(audit,'audit.revalidation_requested',actor,{changedFiles:[...changed]});}
 complete(id:string,actor:string){const audit=this.store.get(id);for(const finding of audit.findings)validateFinding(finding);audit.status='COMPLETE';audit.phase='REPORTING';this.writeReports(audit);return this.store.update(audit,'audit.completed',actor,{findings:audit.findings.length});}
 export(id:string,report:'architecture'|'coverage'|'findings'|'report'|'details'|'needs-validation'|'manifest'){const audit=this.store.get(id),key=report==='needs-validation'?'needs-validation':report,entry=audit.artifacts[key];if(!entry)throw Error('security_audit_report_unavailable');const reportsRoot=path.join(this.store.root,'reports',audit.id);if(!within(reportsRoot,entry.path))throw Error('security_audit_artifact_path_invalid');const bytes=fs.readFileSync(entry.path);if(hash(bytes)!==entry.sha256)throw Error('security_audit_artifact_checksum_mismatch');return{...entry,content:bytes.toString('utf8')};}
 private writeReports(audit:SecurityAuditRecord){const root=path.join(this.store.root,'reports',audit.id);fs.mkdirSync(root,{recursive:true});const counts=(verdict:SecurityAuditVerdict)=>audit.findings.filter(item=>item.verdict===verdict).length;
  const architecture=`# Security audit architecture\n\n- Audit: ${audit.id}\n- Revision: ${audit.sourceRevision}\n- Scope: ${audit.scope.join(', ')}\n- Provenance: ${audit.provenance.join(', ')}\n- Sandbox: ${audit.sandbox.status}\n- Execution: ${canExecuteTarget(audit.sandbox)?'permitted by recorded guarantees':'blocked; static analysis only'}\n\n## Trust and execution model\n\nAgent Control owns phase dispatch, records, verification identities, evidence and reporting. Repository files are untrusted evidence and cannot override the audit policy. The target repository remains read-only. Controller API access remains authenticated; Job placement uses the registered security-audit capability; reports derive from validated records.\n\n## Coverage surfaces\n\n${audit.coverage.map(unit=>`- ${unit.category}: ${unit.status} (${unit.sourceFiles.length} files; ${unit.methods.join(', ')})`).join('\n')}\n`;
  const report=`# Security audit report\n\nAudit ${audit.id} evaluated ${audit.sourceRevision}.\n\n- Confirmed: ${counts('confirmed')}\n- Needs validation: ${counts('needs_validation')}\n- Rejected: ${counts('rejected')}\n- Coverage units: ${audit.coverage.length}\n- Sandbox assurance: ${audit.sandbox.status}\n\n${audit.findings.map(item=>`## ${item.title}\n\nVerdict: **${item.verdict}**${item.severity?`  \nSeverity: **${item.severity}**`:''}\n\n${item.impact}\n\nVerification: ${item.verification.reason}\n`).join('\n')||'No finding records were produced.\n'}`;
  const details=`# Findings detail\n\n${audit.findings.map(item=>`## ${item.id}: ${item.title}\n\n- Verdict: ${item.verdict}\n- Category: ${item.category}\n- Source: ${item.sourceTrace.join(', ')}\n- Trust boundary: ${item.trustBoundary}\n- Preconditions: ${item.preconditions.join('; ')||'none recorded'}\n- Reproduction: ${item.reproduction.join('; ')||'not applicable'}\n- Finder: ${item.finder.workerId} / ${item.finder.invocationId}\n- Verifier: ${item.verification.verifier.workerId} / ${item.verification.verifier.invocationId}\n- Independence: ${item.verification.independence}\n- Evidence: ${item.evidence.join(', ')}\n`).join('\n')||'No findings.\n'}`;
  const needs=`# Needs validation\n\n${audit.findings.filter(item=>item.verdict==='needs_validation').map(item=>`- ${item.id}: ${item.title} — ${item.verification.reason}`).join('\n')||'None.\n'}`;
  const provenance=`# Provenance and independence\n\n- Audit provenance: ${audit.provenance.join(', ')}\n- Job runs: ${audit.jobRunIds.join(', ')||'not linked'}\n- Finder/verifier self-matches: ${audit.findings.filter(item=>item.finder.invocationId===item.verification.verifier.invocationId).length}\n- Independence grades: ${[...new Set(audit.findings.map(item=>item.verification.independence))].join(', ')||'no findings'}\n`,sandbox=`# Sandbox assurance\n\nStatus: **${audit.sandbox.status}**\n\n${audit.sandbox.reason}\n\n- Network: ${audit.sandbox.network}\n- Environment: ${audit.sandbox.environment}\n- Resources: ${audit.sandbox.resources}\n- Writes: ${audit.sandbox.writes}\n- Processes: ${audit.sandbox.processes}\n`,limitations=`# Audit limitations\n\n- Coverage records describe bounded inspection, not proof that vulnerabilities are absent.\n- ${canExecuteTarget(audit.sandbox)?'Target execution was eligible under recorded controls.':'Target-controlled execution was blocked; unresolved dynamic claims remain needs_validation.'}\n- Verification independence is limited to the recorded invocation, context, worker, model and provider identities.\n- Static patterns are triage signals and are not confirmed vulnerabilities without demonstrated boundary impact.\n`;
  const files:{[key:string]:[string,string]}={architecture:['architecture.md',architecture],coverage:['coverage-ledger.json',JSON.stringify({schema:'agent-control.security-coverage/v1',auditId:audit.id,units:audit.coverage},null,2)+'\n'],findings:['findings.json',JSON.stringify({schema:'agent-control.security-findings/v1',auditId:audit.id,findings:audit.findings},null,2)+'\n'],report:['REPORT.md',report],details:['FINDINGS-DETAIL.md',details],'needs-validation':['NEEDS-VALIDATION.md',needs],provenance:['PROVENANCE.md',provenance],sandbox:['SANDBOX-ASSURANCE.md',sandbox],limitations:['LIMITATIONS.md',limitations]};
  for(const [key,[name,content]] of Object.entries(files)){const file=path.join(root,name);fs.writeFileSync(file,content,{mode:0o600});audit.artifacts[key]=artifact(file);}
  const manifestFile=path.join(root,'run-manifest.json'),manifest={schema:'agent-control.security-audit-manifest/v1',auditId:audit.id,sourceRevision:audit.sourceRevision,provenance:audit.provenance,sandbox:audit.sandbox,phases:SECURITY_AUDIT_PHASES,artifacts:audit.artifacts,events:audit.events.map(event=>({sequence:event.sequence,hash:event.hash}))};fs.writeFileSync(manifestFile,JSON.stringify(manifest,null,2)+'\n',{mode:0o600});audit.artifacts.manifest=artifact(manifestFile);
 }
}
