import test from 'node:test';import assert from 'node:assert/strict';
import {SharedSpeechClient} from '../vendor/shared-speech/client.mjs';import {SharedSpeechAdapter} from './shared-speech-adapter.js';import {PoeRuntime} from './poe.js';
const now='2026-09-24T12:00:00.000Z';const wav=Buffer.alloc(44);wav.write('RIFF');wav.write('WAVE',8);
function setup(){let serial=0,stt='What date is it?',failed=false,fallback=false;const calls:any[]=[];
 const request:typeof fetch=async(url,init)=>{const path=new URL(String(url)).pathname,body=typeof init?.body==='string'?JSON.parse(init.body):null;calls.push({path,body,method:init?.method});if(failed)return new Response('{}',{status:503});
  if(path==='/v2/sessions')return Response.json({speech_session_id:'session-'+(++serial)});
  const id=path.split('/')[3];if(path.endsWith('/transcribe'))return Response.json({type:'stt.final',text:stt,speech_session_id:id,generation_id:1,client_id:'agent-control',provider:'fixture-stt'});
  if(path.endsWith('/speak')){const events=[{type:'speech.started'},...(fallback?[{type:'provider.unavailable',provider:'requested',fallback:'standard'}]:[]),{type:'speech.block',provider:fallback?'standard':'qualified-voice',mime:'audio/wav',audio:wav.toString('base64')},{type:'speech.finished',provider:fallback?'standard':'qualified-voice'}];return new Response(events.map(e=>'data: '+JSON.stringify({...e,speech_session_id:id,generation_id:1})+'\n\n').join(''),{headers:{'content-type':'text/event-stream'}});}
  return Response.json({service:'ready',stt:'ready',tts:'ready'});
 };
 const adapter=new SharedSpeechAdapter(new SharedSpeechClient({url:'http://127.0.0.1:9999',token:'test-only',request}),'standard');const packet={title:'Recorded job state',summary:'Current observation',facts:[{label:'Job state',value:'RUNNING',authority:'AGENT_CONTROL' as const,informationKind:'LIVE_OBSERVED' as const,observedAt:now,evidence:['job:test']}],related:[]};
 const poe=new PoeRuntime({clock:()=>now,sharedSpeech:adapter,evidence:{overview:()=>packet,resolve:()=>packet}});const conversation=poe.createConversation({actorId:'web-operator',channel:'dashboard'});
 return {adapter,poe,conversation,calls,setStt:(s:string)=>stt=s,fail:()=>failed=true,recover:()=>failed=false,fallback:()=>fallback=true};
}
test('actual SDK voice transcript follows same governed response as text',async()=>{const f=setup();f.setStt('What is running?');const textConversation=f.poe.createConversation({actorId:'web-operator',channel:'dashboard'});const text=await f.poe.ask({conversationId:textConversation.id,text:'What is running?',contentTrust:'UNTRUSTED_DATA'});const voice=await f.poe.transcribeTurn(f.conversation.id,wav,'audio/wav','web-operator');assert.equal(voice.turn.text,text.turn.text);assert.deepEqual(voice.turn.evidence,text.turn.evidence);assert.equal(voice.turn.authority,text.turn.authority);assert.equal(voice.turn.responseMode,text.turn.responseMode);assert.equal((voice.operatorTurn.sharedSpeech as any).rawStt,'What is running?');assert.ok((voice.operatorTurn.sharedSpeech as any).sessionId);});
test('raw STT stays exact, correlation and source retained',async()=>{const f=setup();f.setStt('  What date is it?  ');const r=await f.poe.transcribeTurn(f.conversation.id,wav,'audio/wav','web-operator');assert.equal(r.operatorTurn.text,'  What date is it?  ');assert.equal((r.operatorTurn.sharedSpeech as any).rawStt,r.operatorTurn.text);assert.equal(f.calls[0].body.conversation_id,f.conversation.id);});
test('runtime date is deterministic for text and voice',async()=>{const f=setup();const r=await f.poe.transcribeTurn(f.conversation.id,wav,'audio/wav','web-operator');assert.match(r.turn.text,/24 September 2026/);assert.equal(r.turn.evidence[0]?.value,now);assert.equal(r.turn.responseMode,'DETERMINISTIC');});
test('repeat uses latest valid response in active conversation',async()=>{const f=setup();const r=await f.poe.ask({conversationId:f.conversation.id,text:'What date is it?'});for(const phrase of ['repeat','repeat that','repeat your previous answer']){const repeat=await f.poe.ask({conversationId:f.conversation.id,text:phrase});assert.equal(repeat.turn.text,r.turn.text);}const other=f.poe.createConversation({actorId:'web-operator',channel:'dashboard'});assert.match((await f.poe.ask({conversationId:other.id,text:'repeat'})).turn.text,/no valid previous/);});
test('cancelled latest answer is not revived or replaced with an older answer',async()=>{const f=setup();await f.poe.ask({conversationId:f.conversation.id,text:'What is running?'});const r=await f.poe.ask({conversationId:f.conversation.id,text:'What date is it?'});f.poe.bargeIn(f.conversation.id,'web-operator',r.turn.id);assert.match((await f.poe.ask({conversationId:f.conversation.id,text:'repeat that'})).turn.text,/no valid previous/);});
test('final governed text, not a new voice job/model prompt, reaches SDK',async()=>{const f=setup();const r=await f.poe.ask({conversationId:f.conversation.id,text:'What is running?'});const events=[];for await(const e of f.poe.sharedSpeechForTurn(f.conversation.id,r.turn.id,'web-operator'))events.push(e);const submissions=f.calls.filter(x=>x.path.endsWith('/speak'));assert.equal(submissions.map(x=>x.body.text).join(''),r.turn.text);assert.ok(submissions.every(x=>x.body.voice==='mallow'));assert.ok(events.some(e=>e.type==='speech.block'));assert.equal(f.poe.conversation(f.conversation.id).turns.length,2);});
test('fallback event identifies actual provider without claiming Mallow',async()=>{const f=setup();f.fallback();const events=[];for await(const e of f.adapter.speak('c','r','Hello.'))events.push(e);assert.ok(events.some(e=>e.type==='provider.unavailable'));assert.equal(events.find(e=>e.type==='speech.block')?.provider,'standard');});
test('Shared Speech unavailable does not disable normal governed text',async()=>{const f=setup();f.fail();await assert.rejects(f.adapter.transcribe('c',wav,'audio/wav'),/503/);assert.match((await f.poe.ask({conversationId:f.conversation.id,text:'What date is it?'})).turn.text,/24 September/);f.recover();assert.equal((await f.adapter.transcribe('c',wav,'audio/wav')).text,'What date is it?');});
test('cross-conversation ownership enforced before STT or speech',async()=>{const f=setup();await assert.rejects(f.poe.transcribeTurn(f.conversation.id,wav,'audio/wav','stranger'),/actor_mismatch/);const iterator=f.poe.sharedSpeechForTurn(f.conversation.id,'unknown','stranger');await assert.rejects(iterator.next(),/actor_mismatch/);assert.equal(f.calls.length,0);});
test('long text preserves every character across SDK request limits',async()=>{const f=setup(),text='An unchanged governed sentence. '.repeat(90);for await(const e of f.adapter.speak('c','r',text)){}const sent=f.calls.filter(c=>c.path.endsWith('/speak')).map(c=>c.body.text);assert.equal(sent.join(''),text);assert.ok(sent.every(s=>s.length<=1200));});
test('SDK rejects stale generation frames rather than adapter recreating protocol fencing',async()=>{const request:typeof fetch=async(url)=>{const p=new URL(String(url)).pathname;if(p==='/v2/sessions')return Response.json({speech_session_id:'s'});if(p.endsWith('/speak'))return new Response([{type:'speech.started',generation_id:2},{type:'speech.block',generation_id:1,audio:'stale'},{type:'speech.finished',generation_id:2}].map(e=>'data: '+JSON.stringify({...e,speech_session_id:'s'})+'\n\n').join(''));return Response.json({});};const adapter=new SharedSpeechAdapter(new SharedSpeechClient({url:'http://127.0.0.1:9999',token:'fixture',request}));const events=[];for await(const e of adapter.speak('c','r','Hello.'))events.push(e);assert.ok(!events.some(e=>e.audio==='stale'));});
test('cancel prevents late normal response emission',async()=>{let resolve!:Function;const pending=new Promise<any>(r=>resolve=r),packet={title:'Knowledge unavailable',summary:'No facts',facts:[],related:[]};const p=new PoeRuntime({evidence:{overview:()=>packet,resolve:()=>packet},responseModel:{respond:()=>pending}});const c=p.createConversation({actorId:'web-operator',channel:'dashboard'});const answer=p.ask({conversationId:c.id,text:'Explain this idea'});await new Promise(r=>setTimeout(r,10));p.bargeIn(c.id,'web-operator');resolve({text:'Hello',informationKind:'CONVERSATION',speechAct:'GREETING',citations:[],route:{providerId:'f',modelId:'f',nodeId:'f'},usage:{inputTokens:null,outputTokens:null,totalTokens:null,cost:null,currency:null,authority:'UNAVAILABLE'}});await assert.rejects(answer,/generation_cancelled/);assert.equal(p.conversation(c.id).turns.filter(t=>t.actor==='poe').length,0);});

test('failed session creation releases active state for recovery',async()=>{const f=setup();f.fail();await assert.rejects(f.adapter.transcribe('c',wav,'audio/wav'));assert.equal(f.adapter.isActive('c'),false);f.recover();assert.equal((await f.adapter.transcribe('c',wav,'audio/wav')).text,'What date is it?');});
test('cancellation before session creation completes closes the late session',async()=>{let release!:Function;const pending=new Promise<Response>(r=>release=r),calls:string[]=[];const request:typeof fetch=async(url)=>{const p=new URL(String(url)).pathname;calls.push(p);if(p==='/v2/sessions')return pending;return Response.json({});};const a=new SharedSpeechAdapter(new SharedSpeechClient({url:'http://127.0.0.1:9999',token:'fixture',request}));const result=a.transcribe('c',wav,'audio/wav');await new Promise(r=>setImmediate(r));await a.cancel('c');release(Response.json({speech_session_id:'late'}));await assert.rejects(result,/interrupted/);assert.ok(calls.includes('/v2/sessions/late'));assert.ok(!calls.some(p=>p.endsWith('/transcribe')));assert.equal(a.isActive('c'),false);});
test('cancel discards a late STT response even if upstream ignores abort',async()=>{let release!:Function,started!:Function;const pending=new Promise<Response>(r=>release=r),ready=new Promise<void>(r=>started=r);const request:typeof fetch=async(url)=>{const p=new URL(String(url)).pathname;if(p==='/v2/sessions')return Response.json({speech_session_id:'s'});if(p.endsWith('/transcribe')){started();return pending;}return Response.json({});};const a=new SharedSpeechAdapter(new SharedSpeechClient({url:'http://127.0.0.1:9999',token:'fixture',request}));const result=a.transcribe('c',wav,'audio/wav');await ready;await a.cancel('c');release(Response.json({type:'stt.final',speech_session_id:'s',text:'stale'}));await assert.rejects(result);assert.equal(a.isActive('c'),false);});

test('all requested date forms use authoritative clock without a model call',async()=>{const f=setup();for(const text of ['What date is it?', 'What day is it?', "What's today's date?", "What’s today’s date?"]){const result=await f.poe.ask({conversationId:f.conversation.id,text});assert.match(result.turn.text,/Thursday, 24 September 2026/);assert.equal(result.turn.responseMode,'DETERMINISTIC');}});
test('critical stop is only cancellation and does not wait for model execution',async()=>{const f=setup();let calls=0;const events:any[]=[];const p=new PoeRuntime({onEvent:e=>events.push(e),sharedSpeech:f.adapter,evidence:{overview:()=>{throw Error('must not retrieve');},resolve:()=>{throw Error('must not retrieve');}},responseModel:{respond:async()=>{calls++;throw Error('must not model');}}});const c=p.createConversation({actorId:'web-operator',channel:'dashboard'});const result=await p.ask({conversationId:c.id,text:'Mallow, stop.',modality:'voice',contentTrust:'UNTRUSTED_DATA'});assert.equal(calls,0);assert.equal(result.turn.responseMode,'DETERMINISTIC');assert.match(result.turn.text,/Stopped/);assert.equal(events.filter(e=>e.type==='interrupted').length,1);});
test('speech text control does not permit arbitrary model instructions to cancel',async()=>{const f=setup();await f.poe.ask({conversationId:f.conversation.id,text:'Explain why a stop command is useful.'});assert.notEqual(f.poe.conversation(f.conversation.id).state,'LISTENING');});

test('cancelled pending answer does not resurrect an older response through repeat',async()=>{let release!:Function;const pending=new Promise<any>(r=>release=r),packet={title:'Knowledge unavailable',summary:'No facts',facts:[],related:[]};const p=new PoeRuntime({clock:()=>now,evidence:{overview:()=>packet,resolve:()=>packet},responseModel:{respond:()=>pending}});const c=p.createConversation({actorId:'web-operator',channel:'dashboard'});await p.ask({conversationId:c.id,text:'What date is it?'});const answer=p.ask({conversationId:c.id,text:'Tell me something'});await new Promise(r=>setTimeout(r,10));p.bargeIn(c.id,'web-operator');release({text:'Discarded',citations:[],route:{providerId:'f',modelId:'f',nodeId:'f'},usage:{inputTokens:null,outputTokens:null,totalTokens:null,cost:null,currency:null,authority:'UNAVAILABLE'}});await assert.rejects(answer,/generation_cancelled/);const repeated=await p.ask({conversationId:c.id,text:'repeat that'});assert.match(repeated.turn.text,/no valid previous/);});
test('Mallow busy without fallback is explicit and never emits replacement audio',async()=>{const request:typeof fetch=async(url)=>{const p=new URL(String(url)).pathname;if(p==='/v2/sessions')return Response.json({speech_session_id:'s'});if(p.endsWith('/speak'))return new Response([{type:'speech.started'},{type:'provider.unavailable',reason:'BUSY',fallback:null},{type:'speech.failed',error:'MALLOW_BUSY'}].map(e=>'data: '+JSON.stringify({...e,speech_session_id:'s',generation_id:'g'})+'\n\n').join(''));return Response.json({});};const a=new SharedSpeechAdapter(new SharedSpeechClient({url:'http://127.0.0.1:9999',token:'fixture',request}));const events:any[]=[];await assert.rejects(async()=>{for await(const e of a.speak('c','t','Test'))events.push(e);},/generation_failed/);assert.ok(events.some(e=>e.reason==='BUSY'));assert.ok(!events.some(e=>e.type==='speech.block'));});
