import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {FileSkillLearningStore,SkillLearningRuntime,skillSha256,type SkillDatasetManifest,type SkillMetric,type SpecialistExecutionPort} from './skill-learning.js';

const hash=(value:string)=>skillSha256(value),metric=(value:number):SkillMetric=>({name:'frozen_accuracy',value,unit:'ratio',authority:'MEASURED',direction:'HIGHER_IS_BETTER'});
const dataset=(approval:'APPROVED'|'PENDING'='APPROVED'):SkillDatasetManifest=>({schema:'agent-control.skill-dataset/v1',id:'route-intent-v1',version:'1',taskClass:'route-intent-json',trainingExampleIds:['train-1','train-2'],evaluationExampleIds:['eval-1'],trainingSha256:hash('train'),evaluationSha256:hash('eval'),schemaSha256:hash('schema'),provenance:[{sourceId:'parcel-history-1',sourceSha256:hash('source'),authority:'operator-approved'}],duplicateCount:0,malformedCount:0,disagreementCount:0,contaminationCount:0,humanReview:{state:approval,actor:approval==='APPROVED'?'operator':undefined,at:approval==='APPROVED'?'2026-09-11T10:00:00Z':undefined},createdAt:'2026-09-11T10:00:00Z'});
const training={method:'lora',framework:'peft',frameworkVersion:'0.test',runtimeId:'transformers-cpu',runtimeVersion:'1.0.0',precision:'fp32',quantization:null,rank:8,gradientAccumulationSteps:4,gradientCheckpointing:false,seed:42,configurationSha256:hash('config'),environmentSha256:hash('environment')};
function setup(routingEnabled=true){const root=fs.mkdtempSync(path.join(os.tmpdir(),'skill-learning-')),file=path.join(root,'skills.json'),runtime=new SkillLearningRuntime(new FileSkillLearningStore(file),{routingEnabled,minimumImprovement:.1},()=> '2026-09-11T12:00:00Z');return{root,file,runtime};}
function qualified(runtime:SkillLearningRuntime,improvement=.3){let candidate=runtime.observe({label:'Route intent specialist',taskClass:'route-intent-json',capabilities:['route.intent.classify'],sourceEvidence:['parcel:one'],reason:'Repeated bounded task',expectedBenefit:'Higher schema-valid accuracy',actor:'operator'});runtime.identify(candidate.id,{actor:'operator',reason:'Approved candidate'});runtime.attachDataset(candidate.id,dataset(),{actor:'operator',reason:'Dataset reviewed'});runtime.recordBaseline(candidate.id,{metrics:[metric(.4)],actor:'verifier',reason:'Frozen baseline',evidence:['eval:baseline']});runtime.beginTraining(candidate.id,{identity:training,actor:'operator',reason:'Approved bounded CPU LoRA'});runtime.completeTraining(candidate.id,{resultRef:'managed://skills/route-intent/1',resultSha256:hash('adapter'),actor:'trainer',reason:'Training complete'});const adapter=runtime.qualify(candidate.id,{adapter:{id:'route-intent-lora',version:'1',format:'peft-lora',artefactSha256:hash('adapter'),sizeBytes:1024,storageRef:'managed://skills/route-intent/1'},base:{modelId:'tiny-base',modelVersion:'rev-1',modelSha256:hash('base')},specialistMetrics:[metric(.4+improvement)],evaluatorId:'independent-verifier',evidence:['eval:specialist'],protectedRegressions:[],runtimeIds:['transformers-cpu'],actor:'verifier',reason:'Frozen evaluation completed'});if(adapter.qualification.state==='QUALIFIED')runtime.enableRouting(adapter.id,adapter.version,{actor:'operator',reason:'Explicitly admitted after qualification'});return{candidate,adapter};}

test('governed lifecycle requires reviewed disjoint dataset and frozen baseline before training',()=>{const s=setup();try{const candidate=s.runtime.observe({label:'Specialist',taskClass:'route-intent-json',capabilities:['route.intent.classify'],sourceEvidence:['history:1'],reason:'Observed misses',expectedBenefit:'accuracy',actor:'operator'});assert.throws(()=>s.runtime.attachDataset(candidate.id,dataset(),{actor:'operator',reason:'too early'}),/transition/);s.runtime.identify(candidate.id,{actor:'operator',reason:'review'});assert.throws(()=>s.runtime.attachDataset(candidate.id,dataset('PENDING'),{actor:'operator',reason:'pending'}),/approval_required/);const contaminated={...dataset(),evaluationExampleIds:['train-1']};assert.throws(()=>s.runtime.attachDataset(candidate.id,contaminated,{actor:'operator',reason:'bad'}),/contaminated/);s.runtime.attachDataset(candidate.id,dataset(),{actor:'operator',reason:'approved'});assert.throws(()=>s.runtime.beginTraining(candidate.id,{identity:training,actor:'operator',reason:'no baseline'}),/transition/);}finally{fs.rmSync(s.root,{recursive:true,force:true});}});

test('material improvement qualifies and exact composed route executes with fail-closed identity',async()=>{const s=setup();try{const {adapter}=qualified(s.runtime),request={parcelId:'parcel-1',stageId:'classify',taskClass:'route-intent-json',requiredCapabilities:['route.intent.classify'],baseModelId:'tiny-base',baseModelVersion:'rev-1',baseModelSha256:hash('base'),runtimeId:'transformers-cpu',runtimeVersion:'1.2.0'},decision=s.runtime.assess(request);assert.equal(decision.selected?.adapterId,adapter.id);const good:SpecialistExecutionPort={execute:async input=>({actual:{baseModelId:input.baseModelId,baseModelSha256:input.baseModelSha256,runtimeId:input.runtimeId,adapterId:input.adapterId,adapterVersion:input.adapterVersion,adapterSha256:input.adapterSha256},output:{lane:'review'},usage:{inputTokens:7,outputTokens:3,totalTokens:10},elapsedMs:4})};const result=await s.runtime.execute(decision.id,{...request,input:{text:'review this'}},good);assert.deepEqual(result.output,{lane:'review'});const bad:SpecialistExecutionPort={execute:async input=>({actual:{baseModelId:input.baseModelId,baseModelSha256:input.baseModelSha256,runtimeId:input.runtimeId,adapterId:'wrong',adapterVersion:input.adapterVersion,adapterSha256:input.adapterSha256},output:{},elapsedMs:1})};await assert.rejects(()=>s.runtime.execute(decision.id,{...request,input:{}},bad),/execution_identity_mismatch/);}finally{fs.rmSync(s.root,{recursive:true,force:true});}});

test('wrong base, stale qualification, inappropriate task and disabled policy use ordinary route',()=>{const s=setup();try{qualified(s.runtime);for(const request of [{taskClass:'unrelated-task',baseModelSha256:hash('base')},{taskClass:'route-intent-json',baseModelSha256:hash('wrong')}]){const decision=s.runtime.assess({parcelId:random(),stageId:'stage',requiredCapabilities:['route.intent.classify'],baseModelId:'tiny-base',baseModelVersion:'rev-1',runtimeId:'transformers-cpu',runtimeVersion:'1.0.0',...request});assert.equal(decision.selected,null);}const disabled=setup(false);try{qualified(disabled.runtime);assert.equal(disabled.runtime.assess({parcelId:'p',stageId:'s',taskClass:'route-intent-json',requiredCapabilities:['route.intent.classify'],baseModelId:'tiny-base',baseModelVersion:'rev-1',baseModelSha256:hash('base'),runtimeId:'transformers-cpu',runtimeVersion:'1.0.0'}).selected,null);}finally{fs.rmSync(disabled.root,{recursive:true,force:true});}}finally{fs.rmSync(s.root,{recursive:true,force:true});}});

test('failed qualification never enters routing and durable restart preserves evidence',()=>{const s=setup();try{const {adapter}=qualified(s.runtime,.01);assert.equal(adapter.qualification.state,'REJECTED');const restored=new SkillLearningRuntime(new FileSkillLearningStore(s.file),{routingEnabled:true,minimumImprovement:.1},()=> '2026-09-11T12:00:00Z');assert.equal(restored.adapters()[0]?.qualification.state,'REJECTED');assert.equal(restored.candidates()[0]?.events.some(event=>event.to==='REJECTED'),true);}finally{fs.rmSync(s.root,{recursive:true,force:true});}});

function random(){return `p-${Math.random().toString(16).slice(2)}`;}
