import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {SocialVoiceCoordinator, prepareSpokenText, spokenJobSummary, type PoeSocialPort, type SocialExecutionPort} from './social-voice.js';
import {validateAudio,validateVoice,type SocialChannelProvider,type SocialMessage,type VoiceIdentity,type SpeechProvider,type SpeechRecognitionProvider} from './social-voice-providers.js';
const voice:VoiceIdentity={id:'test',kind:'designed',provider:'test',modelRevision:'immutable',instruction:'synthetic voice',seed:1};
function setup(t:test.TestContext){
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'social-voice-'));const file=path.join(root,'state.sqlite');let clock=1000000,allowed=true,failSend=false,failSpeech=false,failSpeechValidation=false,transcription='status',snapshot='fixed-action',synthesizedText:string|undefined;
  const messages:string[]=[],audio:string[]=[],spokenTexts:string[]=[],poeCalls:Array<{actor:string;identityReference:string;text:string;modality:'text'|'voice'}>=[],poeInterrupts:Array<{actor:string;identityReference:string;conversationId:string;turnId:string}>=[],parcels=new Map<string,{id:string;status:string}>();let decisions=0;
  const identity={channel:'fixture',account:'account',sender:'alice',conversation:'alice'};
  const wav=Buffer.alloc(44);wav.write('RIFF');wav.write('WAVE',8);
  const provider:SocialChannelProvider={id:'fixture',capabilities:()=>({text:true,audio:true,artifacts:false,approvals:true}),health:async()=>({state:'ready',checkedAt:new Date().toISOString()}),receive:x=>x as SocialMessage,
    send:async(_i,text,key)=>{if(failSend)throw new Error('offline');if(!messages.includes(key+'|'+text))messages.push(key+'|'+text);return {state:'queued',id:key};},
    sendStatus:async(i,text,key)=>provider.send(i,text,key),sendApprovalRequest:async(i,text,key)=>provider.send(i,text,key),sendArtifact:async(_i,_a,_m,key)=>{audio.push(key);return {state:'submitted',id:key};},downloadAudio:async()=>({bytes:wav,mime:'audio/wav'})};
  const origins:{prompt:string;origin:import('./request-origin.js').GovernedRequestOrigin}[]=[];
  const port:SocialExecutionPort={principal:i=>allowed&&i.sender==='alice'?{actor:'operator',templates:['test'],approve:true}:undefined,start:(_t,_a,key,request)=>{origins.push(structuredClone(request));if(!parcels.has(key))parcels.set(key,{id:'parcel-'+key,status:'QUEUED'});return parcels.get(key)!;},observe:id=>{const p=[...parcels.values()].find(p=>p.id===id)!;return {status:p.status,text:'Bounded test '+p.status};},stop:id=>{[...parcels.values()].find(p=>p.id===id)!.status='CANCELLED';},overview:()=> 'No active jobs.',approvalSnapshot:()=>snapshot,decide:()=>{decisions++;}};
  const metrics={provider:'fixture',host:'test',model:'fixture',elapsedMs:1,audioSeconds:1,rtf:0.001,firstAudioMs:1,memoryBytes:null};
  const speech:SpeechProvider={id:'fixture',capabilities:()=>({synthesize:true,design:true,clone:false,streaming:false}),health:provider.health,voices:async()=>[voice],synthesize:async input=>{if(failSpeech)throw new Error('GPU unavailable');synthesizedText=input.text;spokenTexts.push(input.text);return {bytes:wav,mime:'audio/wav',metrics};}};
  const recognition:SpeechRecognitionProvider={id:'fixture',capabilities:()=>({transcribe:true,languages:['en']}),health:provider.health,transcribe:async()=>{if(synthesizedText!==undefined){const text=failSpeechValidation?'unrelated audio content':synthesizedText;synthesizedText=undefined;return{text,confidence:null,metrics};}return{text:transcription,confidence:null,metrics};}};
  const poe:PoeSocialPort={ask:input=>{poeCalls.push(structuredClone(input));return{conversationId:'poe-whatsapp:fixture',turnId:`poe-turn:${poeCalls.length}`,text:`Grounded POE response: ${input.text}`};},interrupt:input=>{poeInterrupts.push(structuredClone(input));return{interrupted:true};}};
  let coordinator=new SocialVoiceCoordinator(file,provider,port,speech,recognition,voice,()=>clock,undefined,poe);
  t.after(()=>{coordinator.close();fs.rmSync(root,{recursive:true,force:true});});
  const receive=(text:string,id=text,kind:'text'|'audio'='text')=>coordinator.accept({identity,id,kind,text,mediaId:kind==='audio'?id:undefined,receivedAt:clock});
  return {get c(){return coordinator;},receive,identity,messages,audio,spokenTexts,poeCalls,poeInterrupts,parcels,origins,get decisions(){return decisions;},reopen(){coordinator.close();coordinator=new SocialVoiceCoordinator(file,provider,port,speech,recognition,voice,()=>clock,undefined,poe);},advance(ms:number){clock+=ms;},revoke(){allowed=false;},failSend(v:boolean){failSend=v;},failSpeech(){failSpeech=true;},failSpeechValidation(){failSpeechValidation=true;},transcribe(s:string){transcription=s;},changeAction(){snapshot='changed';}};
}
test('durable intake and restart create exactly one parcel and completion is retained',async t=>{const s=setup(t);s.receive('start test voice','one');s.reopen();await s.c.tick();assert.equal(s.parcels.size,1);assert.equal(s.receive('start test voice','one').duplicate,true);for(const p of s.parcels.values())p.status='SUCCEEDED';await s.c.tick();assert.equal(s.audio.length,1);s.reopen();await s.c.tick();assert.equal(s.audio.length,1);assert.match(s.c.transcript(),/policy.allowed/);assert.match(s.c.transcript(),/speech.synthesized/);});
test('unauthorized identities, stale input and ambiguous commands never create parcels',async t=>{const s=setup(t);assert.throws(()=>s.c.accept({identity:{...s.identity,sender:'other'},id:'bad',receivedAt:1000000,kind:'text',text:'start test'}));assert.throws(()=>s.c.accept({identity:s.identity,id:'stale',receivedAt:0,kind:'text',text:'start test'}));s.receive('start test; delete files');await s.c.tick();assert.equal(s.parcels.size,0);assert.match(s.c.transcript(),/policy.denied/);});
test('voice transcription cannot stop or launch work; read-only status is permitted',async t=>{const s=setup(t);s.transcribe('start test');s.receive('audio','a','audio');await s.c.tick();assert.equal(s.parcels.size,0);assert.match(s.messages.join('\n'),/No action was executed/);s.transcribe('status');s.receive('audio','b','audio');await s.c.tick();assert.match(s.messages.join('\n'),/No active jobs/);});
test('confirmed voice request retains exact transcription and safe channel provenance',async t=>{const s=setup(t);s.transcribe('start test');s.receive('audio','voice-origin','audio');await s.c.tick();s.receive('start test voice','text-confirmation');await s.c.tick();assert.equal(s.origins.length,1);assert.equal(s.origins[0].prompt,'start test');assert.equal(s.origins[0].origin.modality,'voice-confirmed-by-text');assert.equal(s.origins[0].origin.channel,'fixture');assert.equal(s.origins[0].origin.authentication,'enrolled-direct-sender');assert.equal(s.origins[0].origin.identityReference.length,64);assert.equal(s.origins[0].origin.messageReference.length,64);assert.equal(s.origins[0].origin.confirmationReference?.length,64);assert.doesNotMatch(JSON.stringify(s.origins[0]),/alice|account/);});
test('revocation after durable intake is checked again before execution',async t=>{const s=setup(t);s.receive('start test');s.revoke();await s.c.tick();assert.equal(s.parcels.size,0);assert.equal(s.messages.length,0);});
test('speech failure retains text and never retries an uncertain voice send',async t=>{const s=setup(t);s.receive('start test voice');await s.c.tick();s.failSpeech();for(const p of s.parcels.values())p.status='SUCCEEDED';await s.c.tick();assert.match(s.messages.join('\n'),/SUCCEEDED/);assert.equal(s.audio.length,0);assert.match(s.c.transcript(),/speech.text_fallback/);});
test('spoken evidence is speech-friendly and mismatched generated content fails closed to text',async t=>{assert.equal(prepareSpokenText('Agent Control status\n\nThe current waiting work is 0.\n\nWaiting work: 0 (agent control)'),'Agent Control status. The current waiting work is zero. Waiting work, zero.');const s=setup(t);s.failSpeechValidation();s.transcribe('POE: status');s.receive('audio','mismatched-speech','audio');await s.c.tick();assert.equal(s.audio.length,0);assert.match(s.messages.join('\n'),/Grounded POE response/);assert.match(s.c.transcript(),/synthesis_content_mismatch/);assert.doesNotMatch(s.c.transcript(),/speech.synthesized/);});
test('messaging failure does not duplicate execution and resumes from durable state',async t=>{const s=setup(t);s.receive('start test');s.failSend(true);await assert.rejects(()=>s.c.tick());assert.equal(s.parcels.size,1);s.failSend(false);await s.c.tick();assert.equal(s.parcels.size,1);});
test('approvals bind identity action parcel timestamp and are one-shot',async t=>{const s=setup(t);s.receive('start test');await s.c.tick();const p=[...s.parcels.values()][0]!;const a=await s.c.requestApproval(s.identity,p.id,'run','approved-action');s.receive('APPROVE '+a.number,'approval');await s.c.tick();assert.equal(s.decisions,1);s.receive('APPROVE '+a.number,'second-message');await s.c.tick();assert.equal(s.decisions,1);assert.match(s.c.transcript(),/approval.transition/);});
test('changed and expired approval snapshots fail closed',async t=>{const s=setup(t);s.receive('start test');await s.c.tick();const p=[...s.parcels.values()][0]!;const a=await s.c.requestApproval(s.identity,p.id,'run','action');s.changeAction();s.receive('approve '+a.number,'a');await s.c.tick();assert.equal(s.decisions,0);const b=await s.c.requestApproval(s.identity,p.id,'run','action',1);s.advance(2);s.receive('approve '+b.number,'b');await s.c.tick();assert.equal(s.decisions,0);});
test('audio signature and voice provenance reject arbitrary attachments and silent cloning',()=>{assert.throws(()=>validateAudio(Buffer.from('<html>not audio</html>'),'audio/wav'));assert.throws(()=>validateVoice({...voice,kind:'cloned'}));assert.doesNotThrow(()=>validateVoice(voice));});
test('channel identity cannot be confused with a group or another account operator',t=>{const s=setup(t);assert.throws(()=>s.c.accept({identity:{...s.identity,conversation:'group'},id:'group',receivedAt:1000000,kind:'text',text:'start test'}));assert.throws(()=>s.c.accept({identity:{...s.identity,channel:'wrong'},id:'wrong',receivedAt:1000000,kind:'text',text:'start test'}));});

test('authenticated WhatsApp and voice questions reach the same spoken POE persona with distinct channel provenance and cannot create work',async t=>{const s=setup(t);assert.equal(s.c.accepts('POE: what is running?'),true);s.receive('POE: what is running?','poe-text');await s.c.tick();assert.equal(s.audio.length,0);s.transcribe('POE: explain parcel parcel-one');s.receive('audio','poe-voice','audio');await s.c.tick();assert.equal(s.poeCalls.length,2);assert.deepEqual(s.poeCalls.map(item=>item.modality),['text','voice']);assert.equal(s.poeCalls[0]!.actor,'operator');assert.equal(s.poeCalls[0]!.identityReference.length,64);assert.doesNotMatch(JSON.stringify(s.poeCalls),/alice|account/);assert.equal(s.parcels.size,0);assert.equal(s.audio.length,1);assert.match(s.messages.join('\n'),/Grounded POE response/);assert.match(s.c.transcript(),/poe.response/);assert.match(s.c.transcript(),/speech.synthesized/);});

test('audited voice-name normalization admits only explicit POE homophones while retaining the provider transcription',async t=>{const s=setup(t);s.transcribe('Ask Pose status');s.receive('audio','poe-pose','audio');await s.c.tick();s.transcribe('Po current systems');s.receive('audio','poe-po','audio');await s.c.tick();assert.deepEqual(s.poeCalls.map(call=>call.text),['status','current systems']);assert.equal(s.parcels.size,0);const transcript=s.c.transcript();assert.match(transcript,/"text":"Ask Pose status"/);assert.match(transcript,/"sourceText":"Ask Pose status"/);assert.match(transcript,/"normalizedText":"Ask POE status"/);assert.match(transcript,/"sourceText":"Po current systems"/);assert.match(transcript,/speech.intent_normalized/);assert.match(transcript,/poe-invocation-homophone-v1/);});

test('an explicit natural WhatsApp voice interruption closes the latest POE playback boundary and preserves work',async t=>{const s=setup(t);s.transcribe('POE: explain parcel parcel-one');s.receive('audio','poe-first','audio');await s.c.tick();s.transcribe('Sorry, interrupt Pose. Explain its verification');s.receive('audio','poe-interrupt','audio');await s.c.tick();assert.equal(s.poeInterrupts.length,1);assert.equal(s.poeInterrupts[0]?.conversationId,'poe-whatsapp:fixture');assert.equal(s.poeInterrupts[0]?.turnId,'poe-turn:1');assert.equal(s.poeCalls[1]?.text,'Explain its verification');assert.equal(s.parcels.size,0);assert.equal(s.audio.length,2);assert.match(s.c.transcript(),/"text":"Sorry, interrupt Pose\. Explain its verification"/);assert.match(s.c.transcript(),/"normalizedText":"Sorry, interrupt POE\. Explain its verification"/);assert.match(s.c.transcript(),/poe.interrupted/);assert.match(s.c.transcript(),/client-playback/);assert.match(s.c.transcript(),/"workParcelCancellation":false/);});

test('spoken summaries use number words and the outcome only',()=>{
 const result={status:'FAILED',durationMs:22000,text:'secret internal diagnostics https://private.invalid',runId:'run-hex',model:'internal-model'};
 assert.equal(spokenJobSummary(1,result),'Agent Control job one failed.');
 assert.equal(spokenJobSummary(2,{status:'SUCCEEDED'}),'Agent Control job two completed successfully.');assert.doesNotMatch(spokenJobSummary(123,{status:'CANCELLED'}),/[0-9]/);
 assert.doesNotMatch(spokenJobSummary(1,result),/secret|https|hex|internal-model/);
});

test('authenticated summary recovery is owner-scoped, terminal-only and audio-idempotent',async t=>{const s=setup(t);s.receive('start test');await s.c.tick();await assert.rejects(()=>s.c.requestSummary(s.identity,'AC-1','summary-1'),/not_terminal/);for(const p of s.parcels.values())p.status='FAILED';await s.c.requestSummary(s.identity,'AC-1','summary-1');await s.c.requestSummary(s.identity,'AC-1','summary-1');assert.equal(s.audio.length,1);s.revoke();await assert.rejects(()=>s.c.requestSummary(s.identity,'AC-1','summary-2'),/denied/);});

test('Morrow and legacy POE names share authenticated text and voice routing without starting work',async t=>{
  const s=setup(t);
  for(const command of ['Mallow: what is running?','ask Mallow status','Morrow: what is running?','ask Morrow status','POE: status'])assert.equal(s.c.accepts(command),true);
  for(const command of ['Tomorrow: status','Morrowish: status','Ask Morrowish status'])assert.equal(s.c.accepts(command),false);
  s.receive('Morrow: what is running?','morrow-text');await s.c.tick();
  s.transcribe('Ask Morrow status');s.receive('audio','morrow-voice','audio');await s.c.tick();
  s.receive('POE: status','legacy-poe-text');await s.c.tick();
  assert.deepEqual(s.poeCalls.map(call=>call.text),['what is running?','status','status']);
  assert.deepEqual(s.poeCalls.map(call=>call.modality),['text','voice','text']);
  assert.equal(s.audio.length,1);assert.equal(s.parcels.size,0);
  assert.match(s.c.transcript(),/"text":"Ask Morrow status"/);
});

test('Morrow voice interruption targets the existing playback record and preserves governed work',async t=>{
  const s=setup(t);
  s.transcribe('Morrow: explain parcel parcel-one');s.receive('audio','morrow-first','audio');await s.c.tick();
  s.transcribe('Sorry, interrupt Morrow. Explain its verification');s.receive('audio','morrow-interrupt','audio');await s.c.tick();
  assert.equal(s.poeInterrupts.length,1);
  assert.equal(s.poeInterrupts[0]?.conversationId,'poe-whatsapp:fixture');
  assert.equal(s.poeCalls[1]?.text,'Explain its verification');
  assert.equal(s.parcels.size,0);assert.equal(s.audio.length,2);
  assert.match(s.c.transcript(),/"workParcelCancellation":false/);
});
