import fs from 'node:fs';
import net from 'node:net';
import {createHash} from 'node:crypto';
import type {JobRuntime} from './job-runtime.js';
import type {ActionContext} from './job-types.js';

export type SpeculativeVerdict='BENEFICIAL'|'NEUTRAL'|'REGRESSION'|'INCOMPATIBLE'|'RESOURCE_BLOCKED'|'UNSUPPORTED';
export type SpeculativeExecutionObjective='LATENCY_SENSITIVE'|'THROUGHPUT_SENSITIVE'|'BALANCED';
export interface SpeculativeModelRef{id:string;path:string;sha256:string;quantisation:string;tokenizerFingerprint:string;bytes:number;}
export interface SpeculativeTrial{mode:'ORDINARY'|'SPECULATIVE';draftTokens:number|null;promptId:string;repetition:number;promptTokens:number|null;outputTokens:number|null;ttftMs:number;totalMs:number;tokensPerSecond:number|null;draftProposed:number|null;draftAccepted:number|null;acceptanceRatio:number|null;peakVramBytes:number|null;peakGpuUtilisationPct?:number|null;peakGpuTemperatureCelsius?:number|null;peakGpuPowerWatts?:number|null;systemAvailableBytes:number|null;output:string;error?:string;}
export interface SpeculativeBenchmarkConfig{
 schema:'agent-control.speculative-decoding-benchmark/v1';node:{id:string;gpu:string};runtime:{implementation:string;path:string;sha256:string;version:string};main:SpeculativeModelRef;draft:SpeculativeModelRef;
 settings:{context:number;threads:number;batch:number;microBatch:number;gpuLayers:number;draftGpuLayers:number;maxTokens:number;temperature:number;seed:number;warmups:number;repetitions:number;draftTokenSettings:number[];prompts:Array<{id:string;text:string}>;timeoutMs:number};
 admission:{minimumFreeVramBytes:number;workspaceReserveBytes:number;benefitThresholdPct:number;maximumTemperatureCelsius:number};authority:{actor:string;expiresAt:string};
}
export interface SpeculativeReport{schema:'agent-control.speculative-decoding-report/v1';node:string;gpu:string;runtime:SpeculativeBenchmarkConfig['runtime'];main:Omit<SpeculativeModelRef,'path'>;draft:Omit<SpeculativeModelRef,'path'>;compatibility:{tokenizerCompatible:boolean;runtimeValidated:boolean};admission:unknown;trials:SpeculativeTrial[];summary:{baselineTokensPerSecond:number|null;bestSpeculativeTokensPerSecond:number|null;changePct:number|null;baselineTtftMs:number|null;bestSpeculativeTtftMs:number|null;ttftChangePct:number|null;bestDraftTokens:number|null;draftAcceptance:number|null;vramBaselineBytes:number|null;vramSpeculativeBytes:number|null;vramOverheadBytes:number|null;qualityEquivalent:boolean;energyPerToken:null;energyReason:string;thresholdPct:number;thresholdPolicy:'EXPERIMENTAL_CONFIGURED';};verdict:SpeculativeVerdict;recommendation:string;}
export interface SpeculativeQualifiedRelationship{node:string;gpu:string;runtimeSha256:string;mainSha256:string;draftSha256:string;draftTokens:number;}
export interface SpeculativeRouteRequest{objective:SpeculativeExecutionObjective;relationship:SpeculativeQualifiedRelationship;currentFreeVramBytes:number;expectedOutputTokens?:number|null;}
export interface SpeculativeRouteDecision{decodeMode:'ORDINARY'|'SPECULATIVE';objective:SpeculativeExecutionObjective;reason:string;qualified:boolean;admissionSatisfied:boolean;throughputThresholdPct:number|null;measuredThroughputChangePct:number|null;measuredTtftChangePct:number|null;estimatedCompletionMs:{ordinary:number;speculative:number}|null;}
export interface SpeculativeQualificationProjection{schema:'agent-control.speculative-qualification-projection/v1';node:string;gpu:string;status:SpeculativeVerdict;main:{id:string;sha256:string;quantisation:string};draft:{id:string;sha256:string;quantisation:string};runtime:{implementation:string;version:string;sha256:string};bestDraftTokens:number|null;throughput:{baseline:number|null;speculative:number|null;changePct:number|null;thresholdPct:number};latency:{baselineTtftMs:number|null;speculativeTtftMs:number|null;changePct:number|null};acceptance:number|null;vram:{baselineBytes:number|null;speculativeBytes:number|null;overheadBytes:number|null};qualityEquivalent:boolean;recommendation:string;evidence:{artifactId:string|null;sha256:string|null};}

const sha=async(file:string)=>{const h=createHash('sha256');for await(const chunk of fs.createReadStream(file))h.update(chunk);return h.digest('hex');};
const mean=(values:number[])=>values.length?values.reduce((a,b)=>a+b,0)/values.length:null;
const finite=(value:unknown)=>typeof value==='number'&&Number.isFinite(value)?value:null;
const pause=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const freePort=()=>new Promise<number>((resolve,reject)=>{const s=net.createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const address=s.address() as net.AddressInfo;s.close(error=>error?reject(error):resolve(address.port));});});
function publicModel(model:SpeculativeModelRef){const {path:_path,...value}=model;return value;}

function admissionRequired(report:SpeculativeReport){const value=report.admission as {decision?:unknown;requiredFreeVramBytes?:unknown}|null;return value?.decision==='ADMIT'&&typeof value.requiredFreeVramBytes==='number'&&Number.isFinite(value.requiredFreeVramBytes)?value.requiredFreeVramBytes:null;}
function exactRelationship(report:SpeculativeReport,value:SpeculativeQualifiedRelationship){return report.node===value.node&&report.gpu===value.gpu&&report.runtime.sha256===value.runtimeSha256&&report.main.sha256===value.mainSha256&&report.draft.sha256===value.draftSha256&&report.summary.bestDraftTokens===value.draftTokens;}
export function selectSpeculativeRoute(report:SpeculativeReport,request:SpeculativeRouteRequest):SpeculativeRouteDecision{
 const threshold=finite(report.summary.thresholdPct),gain=finite(report.summary.changePct),ttftChange=finite(report.summary.ttftChangePct),required=admissionRequired(report),qualified=report.verdict==='BENEFICIAL'&&report.compatibility.tokenizerCompatible&&report.compatibility.runtimeValidated&&report.summary.qualityEquivalent&&threshold!==null&&gain!==null&&gain>=threshold&&exactRelationship(report,request.relationship),admissionSatisfied=required!==null&&Number.isFinite(request.currentFreeVramBytes)&&request.currentFreeVramBytes>=required;
 const base={objective:request.objective,qualified,admissionSatisfied,throughputThresholdPct:threshold,measuredThroughputChangePct:gain,measuredTtftChangePct:ttftChange,estimatedCompletionMs:null} satisfies Omit<SpeculativeRouteDecision,'decodeMode'|'reason'>;
 if(!qualified)return{...base,decodeMode:'ORDINARY',reason:'Ordinary decoding retained because this exact model, draft, runtime, hardware and draft-token relationship is not beneficially qualified.'};
 if(!admissionSatisfied)return{...base,decodeMode:'ORDINARY',reason:'Ordinary decoding retained because the current free-VRAM admission floor is not satisfied.'};
 if(request.objective==='LATENCY_SENSITIVE')return{...base,decodeMode:ttftChange!==null&&ttftChange<0?'SPECULATIVE':'ORDINARY',reason:ttftChange!==null&&ttftChange<0?'Speculative decoding has the lower measured time to first token.':'Ordinary decoding has the lower measured time to first token for this qualified relationship.'};
 if(request.objective==='THROUGHPUT_SENSITIVE')return{...base,decodeMode:'SPECULATIVE',reason:`Speculative decoding exceeds the explicit ${threshold}% generation-throughput threshold for this exact relationship.`};
 const tokens=finite(request.expectedOutputTokens),ordinaryTtft=finite(report.summary.baselineTtftMs),speculativeTtft=finite(report.summary.bestSpeculativeTtftMs),ordinaryTps=finite(report.summary.baselineTokensPerSecond),speculativeTps=finite(report.summary.bestSpeculativeTokensPerSecond);
 if(tokens===null||tokens<0||ordinaryTtft===null||speculativeTtft===null||ordinaryTps===null||speculativeTps===null||ordinaryTps<=0||speculativeTps<=0)return{...base,decodeMode:'ORDINARY',reason:'Ordinary decoding retained because balanced routing lacks a defensible expected-output or timing measurement.'};
 const estimatedCompletionMs={ordinary:ordinaryTtft+tokens/ordinaryTps*1000,speculative:speculativeTtft+tokens/speculativeTps*1000},useSpeculative=estimatedCompletionMs.speculative<estimatedCompletionMs.ordinary;
 return{...base,estimatedCompletionMs,decodeMode:useSpeculative?'SPECULATIVE':'ORDINARY',reason:useSpeculative?'Speculative decoding has the lower estimated completion time at the requested output length.':'Ordinary decoding has the lower estimated completion time at the requested output length.'};
}

export function projectSpeculativeQualification(value:unknown,evidence:{artifactId?:string|null;sha256?:string|null}={}):SpeculativeQualificationProjection|null{
 const report=value as Partial<SpeculativeReport>|null;if(report?.schema!=='agent-control.speculative-decoding-report/v1'||typeof report.node!=='string'||typeof report.gpu!=='string'||!report.runtime||!report.main||!report.draft||!report.summary||typeof report.verdict!=='string')return null;const summary=report.summary;
 return{schema:'agent-control.speculative-qualification-projection/v1',node:report.node,gpu:report.gpu,status:report.verdict as SpeculativeVerdict,main:{id:String(report.main.id),sha256:String(report.main.sha256),quantisation:String(report.main.quantisation)},draft:{id:String(report.draft.id),sha256:String(report.draft.sha256),quantisation:String(report.draft.quantisation)},runtime:{implementation:String(report.runtime.implementation),version:String(report.runtime.version),sha256:String(report.runtime.sha256)},bestDraftTokens:finite(summary.bestDraftTokens),throughput:{baseline:finite(summary.baselineTokensPerSecond),speculative:finite(summary.bestSpeculativeTokensPerSecond),changePct:finite(summary.changePct),thresholdPct:finite(summary.thresholdPct)??0},latency:{baselineTtftMs:finite(summary.baselineTtftMs),speculativeTtftMs:finite(summary.bestSpeculativeTtftMs),changePct:finite(summary.ttftChangePct)},acceptance:finite(summary.draftAcceptance),vram:{baselineBytes:finite(summary.vramBaselineBytes),speculativeBytes:finite(summary.vramSpeculativeBytes),overheadBytes:finite(summary.vramOverheadBytes)},qualityEquivalent:summary.qualityEquivalent===true,recommendation:String(report.recommendation??''),evidence:{artifactId:evidence.artifactId??null,sha256:evidence.sha256??null}};
}

export function validateSpeculativeConfig(raw:SpeculativeBenchmarkConfig){const c=structuredClone(raw);if(c?.schema!=='agent-control.speculative-decoding-benchmark/v1'||!c.node?.id||!c.runtime?.implementation||!c.runtime.path?.startsWith('/')||!c.main?.path?.startsWith('/')||!c.draft?.path?.startsWith('/')||!c.authority?.actor||Date.parse(c.authority.expiresAt)<=Date.now())throw Error('speculative_configuration_invalid');for(const model of [c.main,c.draft])if(!/^[a-f0-9]{64}$/.test(model.sha256)||!/^[a-f0-9]{64}$/.test(model.tokenizerFingerprint)||!Number.isSafeInteger(model.bytes)||model.bytes<1)throw Error('speculative_model_identity_invalid');const s=c.settings,a=c.admission;if(!Number.isInteger(s.context)||s.context<256||!Number.isInteger(s.maxTokens)||s.maxTokens<8||s.repetitions<2||s.warmups<1||!s.prompts.length||!s.draftTokenSettings.length||s.draftTokenSettings.some(n=>!Number.isInteger(n)||n<1||n>32)||!Number.isSafeInteger(a.minimumFreeVramBytes)||a.minimumFreeVramBytes<c.main.bytes+c.draft.bytes||a.benefitThresholdPct<0||a.benefitThresholdPct>100||a.maximumTemperatureCelsius<20||a.maximumTemperatureCelsius>100)throw Error('speculative_policy_invalid');return c;}

export function summarizeSpeculative(config:SpeculativeBenchmarkConfig,trials:SpeculativeTrial[],compatibility={tokenizerCompatible:true,runtimeValidated:true},admission:unknown={}):SpeculativeReport{
 const good=trials.filter(t=>!t.error&&t.tokensPerSecond!==null),baseline=good.filter(t=>t.mode==='ORDINARY'),groups=new Map<number,SpeculativeTrial[]>();for(const trial of good.filter(t=>t.mode==='SPECULATIVE')){const n=trial.draftTokens!;groups.set(n,[...(groups.get(n)??[]),trial]);}
 const baseTps=mean(baseline.map(t=>t.tokensPerSecond!)),baseTtft=mean(baseline.map(t=>t.ttftMs));let bestN:number|null=null,best:SpeculativeTrial[]=[];for(const [n,rows] of groups){const value=mean(rows.map(r=>r.tokensPerSecond!));if(value!==null&&(bestN===null||value>(mean(best.map(r=>r.tokensPerSecond!))??-Infinity))){bestN=n;best=rows;}}
 const specTps=mean(best.map(t=>t.tokensPerSecond!)),specTtft=mean(best.map(t=>t.ttftMs)),change=baseTps&&specTps?(specTps/baseTps-1)*100:null,ttftChange=baseTtft&&specTtft?(specTtft/baseTtft-1)*100:null,accepted=best.reduce((n,t)=>n+(t.draftAccepted??0),0),proposed=best.reduce((n,t)=>n+(t.draftProposed??0),0),quality=best.length>0&&best.every(row=>baseline.some(base=>base.promptId===row.promptId&&base.output===row.output));
 const baselineVram=Math.max(0,...baseline.map(t=>t.peakVramBytes??0))||null,specVram=Math.max(0,...best.map(t=>t.peakVramBytes??0))||null;
 const resourceFailure=trials.some(t=>/out of memory|cuda.*alloc|alloc.*cuda|insufficient.*memory/i.test(t.error??''));
 let verdict:SpeculativeVerdict;if(resourceFailure)verdict='RESOURCE_BLOCKED';else if(!compatibility.tokenizerCompatible||!compatibility.runtimeValidated)verdict='INCOMPATIBLE';else if(!baseline.length||!best.length)verdict='UNSUPPORTED';else if(!quality||change===null||change<=-config.admission.benefitThresholdPct)verdict='REGRESSION';else if(change>=config.admission.benefitThresholdPct)verdict='BENEFICIAL';else verdict='NEUTRAL';
 return{schema:'agent-control.speculative-decoding-report/v1',node:config.node.id,gpu:config.node.gpu,runtime:config.runtime,main:publicModel(config.main),draft:publicModel(config.draft),compatibility,admission,trials,summary:{baselineTokensPerSecond:baseTps,bestSpeculativeTokensPerSecond:specTps,changePct:change,baselineTtftMs:baseTtft,bestSpeculativeTtftMs:specTtft,ttftChangePct:ttftChange,bestDraftTokens:bestN,draftAcceptance:proposed?accepted/proposed:null,vramBaselineBytes:baselineVram,vramSpeculativeBytes:specVram,vramOverheadBytes:baselineVram!==null&&specVram!==null?specVram-baselineVram:null,qualityEquivalent:quality,energyPerToken:null,energyReason:'No approved whole-node energy sensor is bound to this invocation.',thresholdPct:config.admission.benefitThresholdPct,thresholdPolicy:'EXPERIMENTAL_CONFIGURED'},verdict,recommendation:verdict==='BENEFICIAL'?'Qualified for throughput-sensitive routing on this exact relationship while admission remains satisfied; latency and balanced requests must evaluate their own objective.':'Retain ordinary decoding for this relationship.'};
}

async function command(c:ActionContext,command:string,args:string[],timeoutMs=10000){return c.ownedExecution.runProcess({command,args,maxOutputBytes:262144},AbortSignal.any([c.signal,AbortSignal.timeout(timeoutMs)]));}
async function gpu(c:ActionContext){const r=await command(c,'/usr/bin/nvidia-smi',['--query-gpu=memory.total,memory.used,memory.free,utilization.gpu,temperature.gpu,power.draw','--format=csv,noheader,nounits']);if(r.exitCode!==0)throw Error('speculative_gpu_telemetry_unavailable');const values=r.stdout.trim().split(',').map(x=>Number(x.trim()));if(values.length<6||values.some(x=>!Number.isFinite(x)))throw Error('speculative_gpu_telemetry_invalid');return{totalBytes:values[0]!*1024*1024,usedBytes:values[1]!*1024*1024,freeBytes:values[2]!*1024*1024,utilisation:values[3],temperatureCelsius:values[4],powerWatts:values[5]};}
async function observedCompletion(c:ActionContext,run:Promise<Awaited<ReturnType<typeof streamCompletion>>>){let active=true,peakVramBytes=0,peakGpuUtilisationPct=0,peakGpuTemperatureCelsius=0,peakGpuPowerWatts=0;const monitor=(async()=>{while(active){try{const state=await gpu(c);peakVramBytes=Math.max(peakVramBytes,state.usedBytes);peakGpuUtilisationPct=Math.max(peakGpuUtilisationPct,state.utilisation);peakGpuTemperatureCelsius=Math.max(peakGpuTemperatureCelsius,state.temperatureCelsius);peakGpuPowerWatts=Math.max(peakGpuPowerWatts,state.powerWatts);}catch{}await pause(200);}})();try{return{result:await run,telemetry:{peakVramBytes:peakVramBytes||null,peakGpuUtilisationPct:peakGpuUtilisationPct||null,peakGpuTemperatureCelsius:peakGpuTemperatureCelsius||null,peakGpuPowerWatts:peakGpuPowerWatts||null}};}finally{active=false;await monitor;}}
function systemAvailable(){const match=fs.readFileSync('/proc/meminfo','utf8').match(/^MemAvailable:\s+(\d+) kB/m);return match?Number(match[1])*1024:null;}
async function streamCompletion(base:string,prompt:string,config:SpeculativeBenchmarkConfig,signal:AbortSignal){const started=performance.now(),response=await fetch(base+'/completion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,n_predict:config.settings.maxTokens,temperature:config.settings.temperature,seed:config.settings.seed,cache_prompt:false,stream:true}),signal});if(!response.ok||!response.body)throw Error('speculative_inference_http_'+response.status);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',output='',first:number|null=null,final:any={};for(;;){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});for(;;){const split=buffer.indexOf('\n\n');if(split<0)break;const event=buffer.slice(0,split);buffer=buffer.slice(split+2);for(const line of event.split(/\r?\n/)){if(!line.startsWith('data:'))continue;const text=line.slice(5).trim();if(!text||text==='[DONE]')continue;const row=JSON.parse(text);if(typeof row.content==='string'&&row.content){if(first===null)first=performance.now();output+=row.content;}if(row.stop===true||row.timings)final=row;}}}const ended=performance.now(),tokens=finite(final.tokens_predicted??final.timings?.predicted_n),tps=finite(final.timings?.predicted_per_second);return{output,ttftMs:(first??ended)-started,totalMs:ended-started,promptTokens:finite(final.tokens_evaluated??final.timings?.prompt_n),outputTokens:tokens,tokensPerSecond:tps,draftProposed:finite(final.timings?.draft_n),draftAccepted:finite(final.timings?.draft_n_accepted)};}

export function registerSpeculativeDecoding(runtime:JobRuntime,raw:SpeculativeBenchmarkConfig){const config=validateSpeculativeConfig(raw),workerId='speculative-decoding:'+config.node.id;runtime.workers.registerControllerInternal({id:workerId,capabilities:['model.speculative.qualify'],health:'healthy',capacity:1,active:0,observedAt:new Date().toISOString()});runtime.actions.registerConsequentialControl('speculative-decoding.qualify@1.0.0',async c=>{
 if(c.worker.id!==workerId||Date.parse(config.authority.expiresAt)<=Date.now())throw Error('speculative_authority_invalid');const evidence=(name:string,value:unknown)=>c.recordEvidence?.(name,{schema:'agent-control.speculative-evidence/v1',at:new Date().toISOString(),node:config.node.id,...(value as object)});
 const identities=[];for(const [role,model] of [['main',config.main],['draft',config.draft]] as const){const stat=fs.statSync(model.path);if(stat.size!==model.bytes||await sha(model.path)!==model.sha256)throw Error('speculative_'+role+'_identity_mismatch');identities.push({role,id:model.id,sha256:model.sha256,bytes:model.bytes,quantisation:model.quantisation,tokenizerFingerprint:model.tokenizerFingerprint});}if(await sha(config.runtime.path)!==config.runtime.sha256)throw Error('speculative_runtime_identity_mismatch');const tokenizerCompatible=config.main.tokenizerFingerprint===config.draft.tokenizerFingerprint;evidence('speculative-capability-discovery',{runtime:config.runtime,identities,tokenizerCompatible});if(!tokenizerCompatible){const report=summarizeSpeculative(config,[],{tokenizerCompatible:false,runtimeValidated:false},{});return{artifacts:[{name:'speculative-decoding-report',value:report}],verification:['speculative-incompatibility-evidenced']};}
 const before=await gpu(c),required=Math.max(config.admission.minimumFreeVramBytes,config.main.bytes+config.draft.bytes+config.admission.workspaceReserveBytes),admission={decision:before.freeBytes>=required&&before.temperatureCelsius!<config.admission.maximumTemperatureCelsius?'ADMIT':'REFUSE',requiredFreeVramBytes:required,observation:before,protectedProcessesUntouched:true};evidence('speculative-resource-admission',admission);if(admission.decision==='REFUSE'){const report=summarizeSpeculative(config,[],undefined,admission);report.verdict='RESOURCE_BLOCKED';report.recommendation='Ordinary decoding remains selected; protected workloads were not changed.';return{artifacts:[{name:'speculative-decoding-report',value:report}],verification:['speculative-resource-block-recorded']};}
 const trials:SpeculativeTrial[]=[],ordinary=new Map<string,string>();const modes:Array<{mode:'ORDINARY'|'SPECULATIVE';draftTokens:number|null}>=[{mode:'ORDINARY',draftTokens:null},...config.settings.draftTokenSettings.map(draftTokens=>({mode:'SPECULATIVE' as const,draftTokens}))];let speculativeRuntimeValidated=false;
 for(const mode of modes){const port=await freePort(),base='http://127.0.0.1:'+port,stop=new AbortController(),serverSignal=AbortSignal.any([c.signal,stop.signal]),args=['--model',config.main.path,'--host','127.0.0.1','--port',String(port),'--ctx-size',String(config.settings.context),'--threads',String(config.settings.threads),'--batch-size',String(config.settings.batch),'--ubatch-size',String(config.settings.microBatch),'--n-gpu-layers',String(config.settings.gpuLayers),'--parallel','1','--no-warmup'];if(mode.mode==='SPECULATIVE')args.push('--spec-type','draft-simple','--spec-draft-model',config.draft.path,'--spec-draft-n-max',String(mode.draftTokens),'--spec-draft-ngl',String(config.settings.draftGpuLayers));const server=c.ownedExecution.runProcess({command:config.runtime.path,args,maxOutputBytes:2*1024*1024,env:{PATH:process.env.PATH,HOME:process.env.HOME,LANG:'C.UTF-8',CUDA_VISIBLE_DEVICES:process.env.CUDA_VISIBLE_DEVICES}},serverSignal).then(value=>({value}),error=>({error:String(error)}));let peak=before.usedBytes,ready=false;
  try{for(let i=0;i<240;i++){const state=await gpu(c);peak=Math.max(peak,state.usedBytes);if(state.temperatureCelsius>=config.admission.maximumTemperatureCelsius)throw Error('speculative_temperature_limit');try{const response=await fetch(base+'/health',{signal:AbortSignal.timeout(500)});if(response.ok){ready=true;break;}}catch{}await pause(250);}if(!ready){stop.abort('speculative_runtime_start_timeout');const ended=await server;const detail='value' in ended?(ended.value.stderr||ended.value.stdout):ended.error;throw Error('speculative_runtime_start_failed: '+detail.slice(-4000));}if(mode.mode==='SPECULATIVE')speculativeRuntimeValidated=true;evidence('speculative-runtime-ready',{mode:mode.mode,draftTokens:mode.draftTokens,portRef:createHash('sha256').update(String(port)).digest('hex').slice(0,16),peakVramBytes:peak,configuration:{context:config.settings.context,threads:config.settings.threads,batch:config.settings.batch,microBatch:config.settings.microBatch,gpuLayers:config.settings.gpuLayers,draftGpuLayers:mode.mode==='SPECULATIVE'?config.settings.draftGpuLayers:null}});
   for(let warm=0;warm<config.settings.warmups;warm++)for(const prompt of config.settings.prompts)await streamCompletion(base,prompt.text,config,AbortSignal.any([c.signal,AbortSignal.timeout(config.settings.timeoutMs)]));
   for(const prompt of config.settings.prompts)for(let repetition=1;repetition<=config.settings.repetitions;repetition++){const observed=await observedCompletion(c,streamCompletion(base,prompt.text,config,AbortSignal.any([c.signal,AbortSignal.timeout(config.settings.timeoutMs)]))),result=observed.result;peak=Math.max(peak,observed.telemetry.peakVramBytes??0);const proposed=result.draftProposed,accepted=result.draftAccepted,trial:SpeculativeTrial={mode:mode.mode,draftTokens:mode.draftTokens,promptId:prompt.id,repetition,promptTokens:result.promptTokens,outputTokens:result.outputTokens,ttftMs:result.ttftMs,totalMs:result.totalMs,tokensPerSecond:result.tokensPerSecond,draftProposed:proposed,draftAccepted:accepted,acceptanceRatio:proposed?accepted!/proposed:null,peakVramBytes:observed.telemetry.peakVramBytes,peakGpuUtilisationPct:observed.telemetry.peakGpuUtilisationPct,peakGpuTemperatureCelsius:observed.telemetry.peakGpuTemperatureCelsius,peakGpuPowerWatts:observed.telemetry.peakGpuPowerWatts,systemAvailableBytes:systemAvailable(),output:result.output};if(mode.mode==='ORDINARY')ordinary.set(prompt.id+':'+repetition,result.output);trials.push(trial);evidence('speculative-trial',{...trial,outputSha256:createHash('sha256').update(trial.output).digest('hex')});}
  }catch(error){trials.push({mode:mode.mode,draftTokens:mode.draftTokens,promptId:'runtime',repetition:0,promptTokens:null,outputTokens:null,ttftMs:0,totalMs:0,tokensPerSecond:null,draftProposed:null,draftAccepted:null,acceptanceRatio:null,peakVramBytes:peak,peakGpuUtilisationPct:null,peakGpuTemperatureCelsius:null,peakGpuPowerWatts:null,systemAvailableBytes:systemAvailable(),output:'',error:error instanceof Error?error.message:String(error)});evidence('speculative-runtime-failure',{mode:mode.mode,draftTokens:mode.draftTokens,error:error instanceof Error?error.message:'unknown',peakVramBytes:peak});}
  finally{stop.abort('speculative_mode_complete');await server;const cleanup=await c.ownedExecution.terminateAll('speculative-mode-complete');if(cleanup.outcome!=='confirmed')throw Error('speculative_cleanup_unconfirmed');}
 }
 const report=summarizeSpeculative(config,trials,{tokenizerCompatible,runtimeValidated:speculativeRuntimeValidated},admission),artifact=evidence('speculative-final-report',report);return{artifacts:[{name:'speculative-decoding-report',value:{...report,evidenceRef:artifact?{id:artifact.id,sha256:artifact.sha256}:null}}],verification:['speculative-ab-complete','speculative-cleanup-confirmed']};
 },['FILESYSTEM_WRITE']);runtime.catalog.knownActions?.add('speculative-decoding.qualify@1.0.0');runtime.catalog.addJob({apiVersion:'agent-control/v1',kind:'Job',metadata:{id:'speculative-decoding-qualification',version:'1.0.0',name:'Qualify speculative decoding'},spec:{priority:'low',concurrency:'no-overlap',parameters:{},steps:[{id:'qualify',action:'speculative-decoding.qualify@1.0.0',requires:['model.speculative.qualify'],resources:['lab/qualification-window','gpu/'+config.node.id],timeoutSeconds:7200,verification:['speculative-ab-complete','speculative-cleanup-confirmed'],outputs:[{name:'speculative-decoding-report',type:'application/json',schema:'agent-control.speculative-decoding-report/v1',version:'1.0.0'}]}]}});return{workerId};}
