import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {TargetReset,type ResetObservation,type ResetAuthority} from './target-reset.js';
const before='11111111-1111-4111-8111-111111111111',after='22222222-2222-4222-8222-222222222222';
const observation=(bootId=before):ResetObservation=>({bootId,physicalIdentity:'physical-identity',environmentVerified:true,service:{identity:true,healthy:true,expected:true}});
function fixture(change:{pre?:Partial<ResetObservation>;post?:Partial<ResetObservation>;service?:Partial<ResetObservation['service']>;rebootError?:boolean;offline?:boolean;unchanged?:boolean;neverReturn?:boolean;restoreError?:boolean}={}){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'target-reset-'));let now=Date.now(),calls=0,reboots=0,restores=0;
 const reset=new TargetReset(dir,'configured-device','configured-environment','hash',{async observe(){calls++;if(calls===1)return {...observation(),...change.pre};if(change.neverReturn||calls===2&&change.offline!==false)throw Error('transport_offline');return {...observation(change.unchanged?before:after),...change.post};},async reboot(){reboots++;if(change.rebootError)throw Error('reset_request_failed');},async restore(boot){restores++;if(change.restoreError)throw Error('restoration_failed');return {...observation(boot),...change.post,service:{...observation().service,...change.service}};}},{now:()=>now,pause:async(ms)=>{now+=ms;},timeoutMs:6000});
 const authority:ResetAuthority={actor:'operator',reason:'explicit recovery',requestKey:'one',expiresAt:new Date(now+60000).toISOString(),approveReset:true};
 return {reset,authority,dir,calls:()=>({calls,reboots,restores}),dispose:()=>fs.rmSync(dir,{recursive:true,force:true})};
}
for(const bad of [{approveReset:false},{actor:''},{reason:''},{requestKey:'../bad'},{expiresAt:'invalid'},{expiresAt:'2000-01-01'}])test('reset rejects invalid authority '+JSON.stringify(bad),async()=>{const f=fixture();try{await assert.rejects(f.reset.reset({...f.authority,...bad}),/authority_required/);assert.equal(f.calls().reboots,0);}finally{f.dispose();}});
test('changed kernel boot, disappearance, same device and healthy service produce append-only proof; repeat does not reboot',async()=>{const f=fixture();try{const old=f.reset.generation(),r=await f.reset.reset(f.authority);assert.equal(r.status,'COMPLETE');assert.equal(r.pre?.bootId,before);assert.equal(r.post?.bootId,after);assert.equal(r.disappeared,true);assert.throws(()=>f.reset.assertGeneration(old),/fenced/);f.reset.assertGeneration(r.generation);const log=fs.readFileSync(path.join(f.dir,r.id+'.jsonl'),'utf8');assert.match(log,/BOOT_BOUNDARY_VERIFIED/);const repeat=await f.reset.reset(f.authority);assert.equal(repeat.replayed,true);assert.equal(f.calls().reboots,1);assert.equal(fs.readFileSync(path.join(f.dir,r.id+'.jsonl'),'utf8'),log);f.reset.abandon(['legacy']);assert.throws(()=>f.reset.assertAttempt('legacy'),/permanently_fenced/);f.reset.assertAttempt('fresh');}finally{f.dispose();}});
for(const [label,change] of Object.entries({missingBoot:{pre:{bootId:''}},wrongDevice:{post:{physicalIdentity:'other'}},environmentMissing:{post:{environmentVerified:false}},resetRejected:{rebootError:true},noDisappearance:{offline:false},sameBoot:{unchanged:true},neverReturns:{neverReturn:true},restoreFailure:{restoreError:true},serviceIdentity:{service:{identity:false}},serviceHealth:{service:{healthy:false}},protectedState:{service:{expected:false}}}))test('failed '+label+' cannot confirm boundary or release quarantine',async()=>{const f=fixture(change);try{const r=await f.reset.reset(f.authority);assert.equal(r.status,'FAILED');assert.throws(()=>f.reset.generation(),/quarantined/);assert.throws(()=>f.reset.abandon(['old']),/not_complete/);await assert.rejects(f.reset.reset({...f.authority,requestKey:'retry'}),/quarantined/);}finally{f.dispose();}});
test('receipt cannot be reused by another operator or run',async()=>{const f=fixture();try{await f.reset.reset(f.authority);await assert.rejects(f.reset.reset({...f.authority,actor:'other'}),/binding_mismatch/);await assert.rejects(f.reset.reset({...f.authority,runId:'other'}),/binding_mismatch/);}finally{f.dispose();}});
test('operation contains no model or benchmark execution port',async()=>{const f=fixture();try{await f.reset.reset(f.authority);assert.deepEqual(f.calls(),{calls:3,reboots:1,restores:1});}finally{f.dispose();}});


test('diagnostic aggregate preserves unknown, ignores optional failures, and requires mandatory evidence',async()=>{
 const {environmentResult}=await import('./target-reset.js');const c=(status:any,mandatory=true)=>({id:'x',status,mandatory,expected:'x',observed:null,reason:'test',timestamp:new Date().toISOString()});
 assert.equal(environmentResult([]),'UNKNOWN');assert.equal(environmentResult([c('UNKNOWN')]),'UNKNOWN');assert.equal(environmentResult([c('FAIL')]),'FAIL');assert.equal(environmentResult([c('PASS'),c('FAIL',false)]),'PASS');assert.equal(environmentResult([c('PASS'),c('UNKNOWN')]),'UNKNOWN');
});

test('read-only diagnostic persists component evidence without changing recovery state or calling operational ports',async()=>{
 const f=fixture();try{
  const failed=await f.reset.reset({...f.authority,requestKey:'failed'});const state=JSON.stringify(f.reset.state()),before=f.calls();
  f.reset.port.diagnose=async()=>({components:[{id:'environment',mandatory:true,expected:'supported environment',observed:'Android',status:'PASS',reason:'observed',timestamp:new Date().toISOString()}]});
  await assert.rejects(f.reset.diagnose(''),/authority_required/);const r=await f.reset.diagnose('operator');assert.equal(r.status,'PASS');assert.equal(r.targetMutations,0);assert.equal(r.modelCalls,0);assert.equal(r.benchmarkFixtures,0);assert.deepEqual(f.calls(),before);assert.equal(JSON.stringify(f.reset.state()),state);assert.ok(fs.existsSync(path.join(f.dir,r.id+'.json')));assert.equal(f.reset.state()?.id,failed.id);
 }finally{f.dispose();}
});
