import type {ModelInvocationObservation,HarnessEfficiencyLedgerPort} from './harness-efficiency.js';
import type {EnergyExecutionRecord} from './energy-telemetry.js';
import {accountingSchema,divideDecimal,addMoney,decimalScale,legacyDecimal,multiplyDecimal,normalizeAttestedUsage,priceUsage,usageHash} from './usage-accounting.js';
import {z} from 'zod';
const dimensions=['provider','model','modelRevision','agent','job','jobType','parcel','machine','runtime','runtimeVersion','executionKind','outcome'] as const;
type Dimension=typeof dimensions[number];
export const usageQuerySchema=z.object({period:z.enum(['today','7d','30d','90d','mtd','all','custom']).default('today'),start:z.string().datetime().optional(),end:z.string().datetime().optional(),groupBy:z.enum(dimensions).default('model'),filters:z.record(z.string(),z.string().max(240)).refine(v=>Object.keys(v).every(k=>(dimensions as readonly string[]).includes(k)),'unsupported filter').default({}),limit:z.number().int().min(1).max(1000).default(200)}).strict();
export type UsageQuery=z.input<typeof usageQuerySchema>;
const safe=(v:string|null|undefined)=>v&&!/^\/|[A-Za-z]:[\\/]|Bearer\s|sk-[a-zA-Z0-9]|password[=:]|token[=:]/i.test(v)?v.slice(0,240):null;
const known=(values:Array<number|null>)=>({value:values.length&&values.every(v=>v!==null)?values.reduce<number>((n,v)=>n+v!,0):null,knownTotal:values.reduce<number>((n,v)=>n+(v??0),0),reported:values.filter(v=>v!==null).length,total:values.length});
export function projectInvocation(r:ModelInvocationObservation,energy:EnergyExecutionRecord[]){const a=r.accounting?accountingSchema.parse(r.accounting):null,u=a?normalizeAttestedUsage(a.evidence,a.semantics):r.usage;
  let apiCost:{amount:string;currency:string;authority:string;basis:string}|null=null;
  if(a?.reportedCost)apiCost={...a.reportedCost,authority:'MEASURED',basis:safe(a.reportedCost.source)??'source identity withheld'};
  else if(a?.pricing){const amount=priceUsage(a.evidence,a.semantics,a.pricing,r.startedAt);if(amount!==null)apiCost={amount,currency:a.pricing.currency,authority:'DERIVED',basis:a.pricing.id+'@'+a.pricing.version};}
  else if((!a||a.provenance.kind==='MIGRATED')&&(r.providerReportedCost??r.calculatedCost)!==null&&r.currency)apiCost={amount:legacyDecimal((r.providerReportedCost??r.calculatedCost)!),currency:r.currency,authority:'LEGACY',basis:'historical numeric evidence, not repriced'};
  let saving:{amount:string;currency:string;authority:string}|null=null;
  if(a?.pricing&&a.semantics.billing==='TOKEN_PARTITIONS'&&a.semantics.input!=='UNKNOWN'&&u.cachedInputTokens!==null&&a.pricing.cached!==null){const difference=addMoney(a.pricing.input,'-'+a.pricing.cached);saving={amount:decimalScale(multiplyDecimal(String(u.cachedInputTokens),difference),6),currency:a.pricing.currency,authority:'DERIVED'};}
  const d:Record<Dimension,string|null>={provider:safe(r.provider),model:safe(r.model),modelRevision:safe(a?.modelRevision),agent:safe(r.agentId),job:safe(r.jobId),jobType:safe(a?.jobType),parcel:safe(a?.parcelId),machine:safe(a?.machine),runtime:safe(a?.runtime),runtimeVersion:safe(a?.runtimeVersion),executionKind:a?.executionKind??'UNKNOWN',outcome:r.finalJobResult};
  const overlapsUnattributable=(e:EnergyExecutionRecord)=>{const a=e.accounting!;const peers=energy.filter(o=>o.id!==e.id&&o.accounting?.sensorId===a.sensorId&&o.route.nodeId===e.route.nodeId&&Date.parse(o.startedAt)<Date.parse(e.completedAt)&&Date.parse(o.completedAt)>Date.parse(e.startedAt));if(!peers.length)return false;if(a.attribution!=='SHARED_ATTRIBUTED')return true;return peers.some(o=>o.accounting?.attribution!=='SHARED_ATTRIBUTED'||o.startedAt!==e.startedAt||o.completedAt!==e.completedAt||!a.concurrentInvocationIds.includes(o.accounting.invocationId))||peers.reduce((n,o)=>n+(o.accounting?.allocationFraction??1),a.allocationFraction??1)>1;};
  const measurements=energy.filter(e=>(e.accounting?.invocationId===r.id||a?.migrationIdentity?.invocationId===e.accounting?.invocationId&&e.route.providerId===r.provider&&e.route.modelId===r.model&&e.parcelId===a?.parcelId)).map(e=>({id:e.id,machine:safe(e.route.nodeId),sensor:safe(e.accounting!.sensorId),scope:e.scope,measurementClass:e.accounting!.measurementClass,sensorMeasurementClass:e.accounting!.sensorMeasurementClass,attribution:overlapsUnattributable(e)?'NOT_ATTRIBUTABLE':e.accounting!.attribution,coverage:e.accounting!.coverage,grossWh:e.grossWh,attributedWh:overlapsUnattributable(e)?null:e.accounting!.attributedWh,incrementalWh:overlapsUnattributable(e)?null:e.accounting!.incrementalAttributedWh,averageWatts:e.averageWatts,peakWatts:e.peakWatts,electricityCost:!overlapsUnattributable(e)&&e.accounting!.electricityCost?{amount:e.accounting!.electricityCost.amount,currency:e.accounting!.electricityCost.currency,authority:e.accounting!.electricityCost.authority,tariffs:e.accounting!.electricityCost.basis.map(t=>({id:safe(t.id),version:safe(t.version),pricePerKwh:t.pricePerKwh,effectiveStart:t.effectiveStart,effectiveEnd:t.effectiveEnd}))}:null,startedAt:e.startedAt,completedAt:e.completedAt}));
  return {id:safe(r.id),jobRun:safe(r.runId),...d,at:r.startedAt,completedAt:r.completedAt,durationMs:r.elapsedMs,usage:u,usageAuthority:a?(a.semantics.input==='UNKNOWN'?'PROVIDER_SEMANTICS_UNKNOWN':'ATTESTED'):'LEGACY_PROVIDER_SEMANTICS_UNATTESTED',semantics:a?.semantics??null,revision:a?.revision??null,provenance:a?.provenance.kind??'LEGACY',retryOf:safe(a?.retryOfInvocationId??a?.migrationIdentity?.retryOfInvocationId),parentInvocation:safe(a?.parentInvocationId),baton:safe(a?.batonId),apiCost,localApiChargeKnownZero:a?.executionKind==='LOCAL'&&a.localApiChargeKnownZero===true,cacheSaving:saving,verifiedSuccess:r.verifierResult==='PASS'&&r.finalJobResult==='SUCCEEDED',energy:measurements,links:{process:a?.parcelId?`?view=runtime-map&parcelId=${encodeURIComponent(a.parcelId)}`:null,estate:a?.machine?`?view=runtime-map&mode=estate&resource=${encodeURIComponent(a.machine)}`:null}};
}
type Row=ReturnType<typeof projectInvocation>;
function currencyTotals(rows:Array<{amount:string;currency:string;authority?:string}|null>){const currencies:Record<string,{amount:string;observations:number;authorities:string[]}>={};for(const r of rows){if(!r)continue;const c=currencies[r.currency]??{amount:'0',observations:0,authorities:[]};c.amount=addMoney(c.amount,r.amount);c.observations++;if(r.authority&&!c.authorities.includes(r.authority))c.authorities.push(r.authority);currencies[r.currency]=c;}return {currencies,reported:rows.filter(Boolean).length,total:rows.length};}
function aggregate(rows:Row[]){const jobs=new Set(rows.map(r=>r.jobRun).filter(Boolean)),successes=new Set(rows.filter(r=>r.verifiedSuccess&&r.jobRun!==null).map(r=>r.jobRun)),retry=rows.filter(r=>r.retryOf!==null);const energy=rows.flatMap(r=>r.energy);
  const energyGroups=new Map<string,typeof energy>();for(const e of energy){const k=JSON.stringify([e.machine,e.sensor,e.scope,e.measurementClass,e.attribution]);energyGroups.set(k,[...(energyGroups.get(k)??[]),e]);}
  const cacheRows=rows.filter(r=>r.semantics?.input!=='UNKNOWN'&&r.semantics!==null&&r.usage.inputTokens!==null&&r.usage.cachedInputTokens!==null),cacheInput=cacheRows.reduce((n,r)=>n+r.usage.inputTokens!,0),cacheRead=cacheRows.reduce((n,r)=>n+r.usage.cachedInputTokens!,0),comparable=rows.length>0&&rows.every(r=>r.jobType!==null)&&new Set(rows.map(r=>r.jobType)).size===1,api=currencyTotals(rows.map(r=>r.apiCost));
  const outcomeRatios={comparableJobType:comparable,successfulJobs:successes.size,tokensPerSuccessfulJob:comparable&&successes.size&&rows.every(r=>r.usage.totalProcessedTokens!==null)?rows.reduce((n,r)=>n+r.usage.totalProcessedTokens!,0)/successes.size:null,timeMsPerSuccessfulJob:comparable&&successes.size&&rows.every(r=>r.durationMs!==null)?rows.reduce((n,r)=>n+r.durationMs!,0)/successes.size:null,retriesPerSuccessfulJob:comparable&&successes.size?retry.length/successes.size:null,apiCostPerSuccessfulJob:comparable&&successes.size?Object.fromEntries(Object.entries(api.currencies).map(([currency,c])=>[currency,{amount:c.observations===rows.length?divideDecimal(c.amount,successes.size):null,coverage:c.observations+'/'+rows.length,rounding:'half-up 12 decimal places'}])):{}};
  return {outcomeRatios,cacheHit:{value:cacheRows.length===rows.length&&cacheInput>0?cacheRead/cacheInput:null,observedRatio:cacheInput>0?cacheRead/cacheInput:null,reported:cacheRows.length,total:rows.length,authority:cacheRows.length?'DERIVED':'UNKNOWN'},calls:rows.length,jobs:jobs.size,unknownJobRunInvocations:rows.filter(r=>r.jobRun===null).length,successfulJobs:successes.size,successAuthority:'VERIFIER_AND_FINAL_JOB_RESULT',knownZeroApiCalls:rows.filter(r=>r.localApiChargeKnownZero).length,localCalls:rows.filter(r=>r.executionKind==='LOCAL').length,input:known(rows.map(r=>r.usage.inputTokens)),cached:known(rows.map(r=>r.usage.cachedInputTokens)),fresh:known(rows.map(r=>r.usage.freshInputTokens)),output:known(rows.map(r=>r.usage.outputTokens)),reasoning:known(rows.map(r=>r.usage.reasoningTokens)),tokens:known(rows.map(r=>r.usage.totalProcessedTokens)),durationMs:known(rows.map(r=>r.durationMs)),apiCost:currencyTotals(rows.map(r=>r.apiCost)),cacheSaving:currencyTotals(rows.map(r=>r.cacheSaving)),retry:{count:retry.length,rate:rows.length?retry.length/rows.length:null,tokens:known(retry.map(r=>r.usage.totalProcessedTokens)),durationMs:known(retry.map(r=>r.durationMs)),cost:currencyTotals(retry.map(r=>r.apiCost))},energy: [...energyGroups.values()].map(es=>({machine:es[0]!.machine,sensor:es[0]!.sensor,scope:es[0]!.scope,measurementClass:es[0]!.measurementClass,attribution:es[0]!.attribution,observations:es.length,observedWh:es.some((a,i)=>es.some((b,j)=>i!==j&&Date.parse(a.startedAt)<Date.parse(b.completedAt)&&Date.parse(a.completedAt)>Date.parse(b.startedAt)))?{value:null,knownTotal:0,reported:0,total:es.length}:known(es.map(e=>e.grossWh)),attributedWh:known(es.map(e=>e.attributedWh)),incrementalWh:known(es.map(e=>e.incrementalWh)),minimumCoverage:Math.min(...es.map(e=>e.coverage)),electricityCost:currencyTotals(es.map(e=>e.electricityCost))})),energyCoverage:{observedInvocations:rows.filter(r=>r.energy.length).length,totalInvocations:rows.length,estimatedInvocations:rows.filter(r=>r.energy.some(e=>e.measurementClass==='ESTIMATED')).length,unavailableInvocations:rows.filter(r=>!r.energy.length||r.energy.every(e=>e.attributedWh===null)).length},comparability:{jobTypes:[...new Set(rows.map(r=>r.jobType??'UNKNOWN'))],modelRevisions:[...new Set(rows.map(r=>r.modelRevision??'UNKNOWN'))],runtimeVersions:[...new Set(rows.map(r=>r.runtimeVersion??'UNKNOWN'))],warning:'Outcome ratios require equivalent workload, model revision, runtime and hardware; no universal ranking is inferred.'}};
}
export function usageProjection(ledger:Pick<HarnessEfficiencyLedgerPort,'list'|'usageHistory'>|undefined,energy:EnergyExecutionRecord[],query:UsageQuery={},now=new Date()){
  const q=usageQuerySchema.parse(query),all=ledger?.list()??[],history=ledger?.usageHistory?.()??{excludedIds:[],events:[]};if(all.length>100000||energy.length>100000)throw Error('usage_projection_capacity_requires_index');
  const end=q.period==='custom'?Date.parse(q.end??''):now.getTime(),midnight=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate());let start=q.period==='today'?midnight:q.period==='mtd'?Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1):q.period==='all'?Math.min(end,...all.map(r=>Date.parse(r.startedAt))):q.period==='custom'?Date.parse(q.start??''):end-Number(q.period.slice(0,-1))*86400000;
  if(!Number.isFinite(start)||!Number.isFinite(end)||start>end||end>now.getTime())throw Error('usage_time_range_invalid');
  const excluded=new Set(history.excludedIds),visible=all.filter(r=>!excluded.has(r.id));
  const select=(from:number,to:number)=>visible.filter(r=>Date.parse(r.startedAt)>=from&&Date.parse(r.startedAt)<to).map(r=>projectInvocation(r,energy)).filter(r=>Object.entries(q.filters).every(([k,v])=>r[k as Dimension]===v));
  const rows=select(start,end),previous=select(start-(end-start),start),groups=new Map<string,Row[]>(),days=new Map<string,Row[]>();
  for(const r of rows){const key=r[q.groupBy]??'UNKNOWN';groups.set(key,[...(groups.get(key)??[]),r]);const day=r.at.slice(0,10);days.set(day,[...(days.get(day)??[]),r]);}
  const period={name:q.period,start:new Date(start).toISOString(),end:new Date(end).toISOString(),timezone:'UTC',allocation:'invocation start; entire invocation assigned to start period'};
  const totals=aggregate(rows),groupRows=[...groups].sort(([a],[b])=>a.localeCompare(b)).slice(0,1000).map(([key,rs])=>({key,...aggregate(rs)}));
  return {schema:'agent-control.usage-projection/v1',observedAt:now.toISOString(),period,groupBy:q.groupBy,filters:q.filters,totals,previousPeriod:previous.length?{...aggregate(previous),coverageWarning:'Observed rows only; continuous collection is not established.'}:null,comparisonStatus:'INSUFFICIENT_CONTINUOUS_COVERAGE',projectedMonth:{value:null,reason:'Continuous accounting coverage and a representative complete-day baseline are not yet established.'},groups:groupRows,groupsTruncated:groups.size>1000,trend:[...days].sort(([a],[b])=>a.localeCompare(b)).map(([day,rs])=>({day,...aggregate(rs)})),localVsApi:['LOCAL','API','UNKNOWN'].map(kind=>({kind,cloudEnergy:'UNKNOWN',...aggregate(rows.filter(r=>r.executionKind===kind))})),rows:rows.sort((a,b)=>b.at.localeCompare(a.at)).slice(0,q.limit),coverage:{matching:rows.length,returned:Math.min(rows.length,q.limit),native:rows.filter(r=>r.provenance==='NATIVE').length,migrated:rows.filter(r=>r.provenance==='MIGRATED').length,legacy:rows.filter(r=>r.provenance==='LEGACY').length,historyStart:visible.length?visible.map(r=>r.startedAt).sort()[0]:null,continuousCollectionEstablished:false},history:{policy:'Retained until explicit usage visibility reset. Original execution and qualification evidence are preserved.',resetCount:history.events.length,resetDigest:usageHash(all.map(r=>r.id).sort())},limitations:['No currencies converted. Amounts retain authority and reported coverage.','Energy groups must not be added across sensors or component/whole-node scopes.','Legacy rows retain historical numeric evidence and unattested provider semantics.']};
}
export function usageObservations(p:ReturnType<typeof usageProjection>){return {source:'CANONICAL_USAGE_PROJECTION',observedAt:p.observedAt,period:p.period,apiCost:p.totals.apiCost,retryRate:p.totals.retry.rate,cacheSaving:p.totals.cacheSaving,energy:p.totals.energy,coverage:p.coverage,routingAuthority:'NONE',qualityCapabilitySafetyApprovalRequired:true};}
export function usageAnswer(p:ReturnType<typeof usageProjection>){return {summary:`${p.totals.calls} observed calls; ${p.totals.successfulJobs} verified successful jobs. Values apply to ${p.period.start} through ${p.period.end}. Unknown metrics cannot establish savings or energy efficiency.`,evidence:usageObservations(p),accountedUsage:{calls:p.totals.calls,tokens:p.totals.tokens,input:p.totals.input,output:p.totals.output,localCalls:p.totals.localCalls,knownZeroApiCalls:p.totals.knownZeroApiCalls},executionKinds:p.localVsApi.map(g=>({kind:g.kind,calls:g.calls,tokens:g.tokens,durationMs:g.durationMs,successfulJobs:g.successfulJobs,apiCost:g.apiCost,energy:g.energy,cloudEnergy:g.cloudEnergy})),comparisonLimitation:'These observations do not establish equivalent workloads. A cheaper-local claim requires comparable successful work, attributable electricity and applicable tariffs as well as actual API billing evidence.',leadersByObservedTokens:p.groups.map(g=>({identity:g.key,tokens:g.tokens})).sort((a,b)=>b.tokens.knownTotal-a.tokens.knownTotal).slice(0,10),authority:'EVIDENCE_WITH_COVERAGE',limitations:p.limitations};}

export function usageQuestionQuery(question:string):UsageQuery{return {period:/month|monthly/i.test(question)?'mtd':/90 days/i.test(question)?'90d':/30 days/i.test(question)?'30d':/week|7 days/i.test(question)?'7d':/all time|historical/i.test(question)?'all':'today',groupBy:/machine|resource/i.test(question)?'machine':/provider/i.test(question)?'provider':'model'};}
