import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {addMoney,accountingSchema,normalizeAttestedUsage,priceUsage,type UsageAccounting,usageHash} from './usage-accounting.js';
import {MemoryHarnessEfficiencyLedger,FileHarnessEfficiencyLedger,createInvocationObservation} from './harness-efficiency.js';
import {integratePower,observeBoundEnergy,type EnergyMeasurementInput} from './usage-energy.js';
import {EnergyTelemetryRuntime} from './energy-telemetry.js';
import {usageProjection,usageAnswer,usageObservations,usageQuerySchema,usageQuestionQuery} from './usage-projection.js';
import {indexHistoricalUsage} from './usage-migration.js';
const at='2026-09-13T10:00:00.000Z',now=new Date('2026-09-13T12:00:00.000Z');
function accounting(overrides:Partial<UsageAccounting>={}):UsageAccounting{return accountingSchema.parse({schema:'agent-control.usage-accounting/v1',revision:0,parentInvocationId:null,retryOfInvocationId:null,parcelId:'parcel-test',batonId:'baton-test',providerRequestId:null,modelRevision:'sha-test',runtime:'runtime',runtimeVersion:'1',machine:'machine',hardware:'hardware',jobType:'arithmetic',executionKind:'API',provenance:{kind:'NATIVE',source:'test-adapter',sourceVersion:'1',migrationVersion:null,at},semantics:{id:'test-inclusive/v1',input:'INCLUDES_CACHE',reasoning:'IN_OUTPUT',total:'INPUT_PLUS_OUTPUT',billing:'TOKEN_PARTITIONS'},evidence:{input:100,cached:40,cacheWrite:0,output:20,reasoning:10,total:null},pricing:{id:'prices',version:'1',currency:'USD',effectiveStart:'2026-09-01T00:00:00.000Z',effectiveEnd:null,source:'test-contract',input:'1',cached:'0.1',cacheWrite:null,output:'2',reasoning:null,fixed:'0'},reportedCost:null,...overrides});}
function row(id='inv',a=accounting()){return createInvocationObservation({id,jobId:'job',runId:'run',stepId:'step',taskId:'task',laneId:'lane',model:'model',provider:'provider',harnessProfile:'STANDARD',executionStrategy:'test',startedAt:at,completedAt:'2026-09-13T10:00:01.000Z',recipeFingerprint:'test',accounting:a});}
function energy(overrides:Partial<EnergyMeasurementInput>={}):EnergyMeasurementInput{return {invocationId:'inv',parcelId:'parcel-test',stageId:'step',providerId:'provider',modelId:'model',modelRevision:'sha-test',runtime:'runtime',runtimeVersion:'1',nodeId:'machine',sensorId:'meter',scope:'WHOLE_NODE',samples:[0,10,20,30].map(s=>({at:`2026-09-13T10:00:${String(s).padStart(2,'0')}.000Z`,nodeId:'machine',scope:'WHOLE_NODE',watts:120,authority:'MEASURED',source:'meter',limitations:[]})),maxGapMs:11000,attribution:'DEDICATED_MEASUREMENT',concurrentInvocationIds:[],concurrencyEvidence:['exclusive-interval-proof'],methodology:'trapezoidal/v1',conditions:'stable',baselineMaxAgeMs:60000,tariffs:[{id:'tariff',version:'1',currency:'GBP',pricePerKwh:'0.3',effectiveStart:'2026-09-01T00:00:00.000Z',effectiveEnd:'2026-10-01T00:00:00.000Z'}],tokens:120,verified:true,successful:true,...overrides};}
test('decimal addition and billing partition arithmetic are exact',()=>{assert.equal(addMoney('0.1','0.2'),'0.3');let total='0';for(let n=0;n<10000;n++)total=addMoney(total,'0.000001');assert.equal(total,'0.01');const a=accounting();assert.equal(priceUsage(a.evidence,a.semantics,a.pricing!,at),'0.000104');assert.throws(()=>addMoney('NaN','0'));});
test('inclusive/exclusive cache and reasoning contracts do not share invalid derivations',()=>{const a=accounting();assert.equal(normalizeAttestedUsage(a.evidence,a.semantics).freshInputTokens,60);assert.equal(normalizeAttestedUsage(a.evidence,{...a.semantics,input:'EXCLUDES_CACHE'}).inputTokens,140);assert.equal(normalizeAttestedUsage(a.evidence,{...a.semantics,input:'UNKNOWN'}).freshInputTokens,null);assert.equal(priceUsage(a.evidence,{...a.semantics,reasoning:'UNKNOWN'},a.pricing!,at),null);assert.equal(priceUsage(a.evidence,{...a.semantics,reasoning:'ADDITIONAL'},a.pricing!,at),null);assert.equal(normalizeAttestedUsage({...a.evidence,cacheWrite:null},a.semantics).freshInputTokens,null);assert.throws(()=>normalizeAttestedUsage({...a.evidence,input:10},a.semantics));});
test('historical pricing effective periods and multiple currencies remain independent',()=>{const ledger=new MemoryHarnessEfficiencyLedger(),a=accounting();ledger.record(row('a',a));ledger.record(row('b',{...a,pricing:{...a.pricing!,currency:'GBP'}}));const p=usageProjection(ledger,[],{},now);assert.equal(p.totals.apiCost.currencies.USD?.amount,'0.000104');assert.equal(p.totals.apiCost.currencies.GBP?.amount,'0.000104');assert.throws(()=>priceUsage(a.evidence,a.semantics,{...a.pricing!,effectiveEnd:'2026-09-12T00:00:00.000Z'},at));});
test('delayed cumulative usage revises one identity; stale/conflicting/duplicate requests fail',()=>{const ledger=new MemoryHarnessEfficiencyLedger(),a=accounting({providerRequestId:'request'});ledger.record(row('a',a));const later={...a,revision:1,evidence:{...a.evidence,output:30}};ledger.reviseUsage('a',later);ledger.reviseUsage('a',later);assert.equal(ledger.list().length,1);assert.equal(ledger.list()[0]!.usage.outputTokens,30);assert.throws(()=>ledger.reviseUsage('a',a));assert.throws(()=>ledger.reviseUsage('a',{...later,evidence:{...later.evidence,output:31}}));assert.throws(()=>ledger.reviseUsage('a',{...later,revision:2,machine:'another'}));assert.throws(()=>ledger.record(row('b',a)));});
test('only explicit retries count, normal stages do not',()=>{const ledger=new MemoryHarnessEfficiencyLedger();ledger.record(row('a'));ledger.record(row('b',accounting({parentInvocationId:'a'})));ledger.record(row('c',accounting({retryOfInvocationId:'a'})));const p=usageProjection(ledger,[],{},now);assert.equal(p.totals.retry.count,1);assert.equal(p.totals.retry.tokens.value,120);assert.equal(p.totals.retry.cost.currencies.USD?.amount,'0.000104');});
test('missing samples and oversized gaps exclude intervals without interpolation',()=>{const i=energy();i.samples[1]!.watts=null;const v=integratePower(i);assert.equal(v.accounting.observedMs,10000);assert.equal(v.accounting.coverage,1/3);assert.equal(v.accounting.excludedIntervals.length,2);assert.equal(v.grossWh,1/3);assert.equal(integratePower(energy({maxGapMs:5000})).grossWh,null);});
test('baseline identity, freshness and conditions gate incremental energy',()=>{const i=energy(),baseline={nodeId:'machine',scope:'WHOLE_NODE' as const,averageWatts:40,sampleCount:3,startedAt:'2026-09-13T09:59:40.000Z',completedAt:'2026-09-13T09:59:50.000Z',authority:'MEASURED' as const,source:'meter',limitations:[],sensorId:'meter',workloadState:'IDLE' as const,methodology:i.methodology,conditions:i.conditions};assert.equal(integratePower({...i,baseline}).accounting.baselineStatus,'VALID');assert.equal(integratePower({...i,baseline:{...baseline,sensorId:'other'}}).incrementalWh,null);assert.equal(integratePower({...i,baseline:{...baseline,completedAt:'2026-09-12T10:00:00.000Z'}}).accounting.baselineStatus,'STALE');assert.equal(integratePower({...i,baseline:{...baseline,conditions:'busy'}}).incrementalWh,null);});
test('overlapping jobs cannot claim dedicated energy; source scopes remain distinct',()=>{assert.equal(integratePower(energy({concurrentInvocationIds:['other']})).accounting.attributedWh,null);assert.equal(integratePower(energy({concurrencyEvidence:[]})).accounting.attribution,'NOT_ATTRIBUTABLE');const shared=integratePower(energy({attribution:'SHARED_ATTRIBUTED',allocationFraction:.5,concurrentInvocationIds:['other']}));assert.equal(shared.accounting.attributedWh,.5);const gpu=energy({scope:'GPU_ONLY'});gpu.samples.forEach(s=>s.scope='GPU_ONLY');assert.equal(integratePower(gpu).accounting.sensorMeasurementClass,'COMPONENT_MEASURED');assert.equal(integratePower(gpu).accounting.electricityCost,null);});
test('tariff changes split observed energy; gaps or overlaps refuse unsupported cost',()=>{const i=energy(),t=i.tariffs[0]!;assert.equal(integratePower(i).accounting.electricityCost?.amount,'0.0003');const ts=[{...t,effectiveEnd:'2026-09-13T10:00:10.000Z'},{...t,version:'2',pricePerKwh:'0.6',effectiveStart:'2026-09-13T10:00:10.000Z'}];assert.equal(integratePower({...i,tariffs:ts}).accounting.electricityCost?.basis.length,2);assert.equal(integratePower({...i,tariffs:[t,t]}).accounting.electricityCost,null);assert.equal(integratePower({...i,tariffs:[{...t,effectiveEnd:at}]}).accounting.electricityCost,null);});
test('Home Assistant port requires approved binding and supports units without device control',async()=>{let calls=0;const adapter={observe:async(id:string)=>{calls++;return {id,state:'0.12',unit:'kW',observedAt:at,lastChanged:at,authority:'HOME_ASSISTANT_REPORTED',physicalVerification:false};}},binding={id:'binding',entityId:'sensor.power',nodeId:'machine',scope:'WHOLE_NODE' as const,approvedAt:'2026-09-13T09:00:00.000Z',expiresAt:'2026-09-13T13:00:00.000Z',measurement:'POWER' as const};const v=await observeBoundEnergy(adapter,binding,now);assert.equal(v.value,120);assert.equal(v.permission,'OBSERVE');assert.equal(calls,1);await assert.rejects(observeBoundEnergy(adapter,{...binding,expiresAt:at},now));await assert.rejects(observeBoundEnergy({observe:async(id)=>({...await adapter.observe(id),unit:'%'})},binding,now));});
test('reset is explicit, auditable, persisted and leaves execution/qualification untouched',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'usage-reset-'));try{const file=path.join(root,'ledger.json'),ledger=new FileHarnessEfficiencyLedger(file);ledger.record(row());ledger.markVerification(['inv'],'PASS','SUCCEEDED');const before=ledger.list(),digest=usageHash(['inv']);assert.throws(()=>ledger.resetUsage('yes',digest,'operator'));assert.throws(()=>ledger.resetUsage('RESET USAGE HISTORY','stale','operator'));ledger.resetUsage('RESET USAGE HISTORY',digest,'operator');const restored=new FileHarnessEfficiencyLedger(file);assert.deepEqual(restored.list(),before);assert.equal(restored.usageHistory().events.length,1);assert.equal(usageProjection(restored,[],{},now).totals.calls,0);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('migration is idempotent, preserves unknowns and does not invent qualification',()=>{const ledger=new MemoryHarnessEfficiencyLedger(),r=row();delete r.accounting;r.usage.inputTokens=null;const source={id:'canonical-archive',version:'4.5',at};assert.equal(indexHistoricalUsage(ledger,[r],source).indexed,1);assert.equal(indexHistoricalUsage(ledger,[r],source).existing,1);const p=usageProjection(ledger,[],{},now);assert.equal(p.coverage.migrated,1);assert.equal(p.rows[0]!.usage.inputTokens,null);assert.equal(p.totals.successfulJobs,0);});
test('projection privacy, Process/Estate links, POE and rules share exact evidence',()=>{const ledger=new MemoryHarnessEfficiencyLedger(),r=row();r.error='secret prompt response password=do-not-publish';r.contextSourceIds=['/private/prompt'];ledger.record(r);ledger.markVerification(['inv'],'PASS','SUCCEEDED');const runtime=new EnergyTelemetryRuntime();runtime.recordMeasurement(energy());const p=usageProjection(ledger,runtime.projection().executions,{},now);assert.ok(!JSON.stringify(p).includes('do-not-publish'));assert.ok(!JSON.stringify(p).includes('/private'));assert.match(p.rows[0]!.links.process!,/parcel-test/);assert.match(p.rows[0]!.links.estate!,/machine/);assert.deepEqual(usageAnswer(p).evidence.apiCost,p.totals.apiCost);assert.equal(usageObservations(p).routingAuthority,'NONE');assert.equal(p.totals.energy[0]!.attributedWh.value,1);});
test('time filters and query bounds reject unsupported dimensions and future periods',()=>{assert.equal(usageQuerySchema.safeParse({filters:{secret:'x'}}).success,false);assert.equal(usageQuerySchema.safeParse({limit:1001}).success,false);const l=new MemoryHarnessEfficiencyLedger();l.record(row());assert.equal(usageProjection(l,[],{filters:{machine:'absent'}},now).totals.calls,0);assert.throws(()=>usageProjection(l,[],{period:'custom',start:at,end:'2027-01-01T00:00:00.000Z'},now));assert.equal(usageProjection(l,[],{period:'all'},now).totals.calls,1);});

test('overlapping sensor records cannot double-attribute electricity in reporting',()=>{const ledger=new MemoryHarnessEfficiencyLedger();ledger.record(row('inv'));ledger.record(row('other'));const runtime=new EnergyTelemetryRuntime();runtime.recordMeasurement(energy());runtime.recordMeasurement(energy({invocationId:'other'}));const p=usageProjection(ledger,runtime.projection().executions,{},now);assert.ok(p.rows.every(r=>r.energy.every(e=>e.attributedWh===null&&e.attribution==='NOT_ATTRIBUTABLE')));});

test('migration preserves attested runtime/model identity and retains source request links',()=>{const l=new MemoryHarnessEfficiencyLedger(),r=row('original',accounting({providerRequestId:'native-request'}));indexHistoricalUsage(l,[r],{id:'snapshot',version:'1',at});const imported=l.list()[0]!;assert.equal(imported.accounting?.modelRevision,'sha-test');assert.equal(imported.accounting?.runtimeVersion,'1');assert.equal(imported.accounting?.migrationIdentity?.providerRequestId,'native-request');assert.equal(imported.accounting?.semantics.id,r.accounting?.semantics.id);});

test('POE period and resource requests select the canonical query',()=>{assert.deepEqual(usageQuestionQuery('Which machine consumed electricity this month?'),{period:'mtd',groupBy:'machine'});assert.deepEqual(usageQuestionQuery('What did providers cost this week?'),{period:'7d',groupBy:'provider'});});

test('successful jobs count executions rather than collapsing repeated job definitions',()=>{const l=new MemoryHarnessEfficiencyLedger();const a=row('a'),b={...row('b'),runId:'another-run'};l.record(a);l.record(b);l.markVerification(['a','b'],'PASS','SUCCEEDED');const p=usageProjection(l,[],{},now);assert.equal(p.totals.jobs,2);assert.equal(p.totals.successfulJobs,2);});

test('local no-charge declarations remain distinct from missing API prices and electricity',()=>{const l=new MemoryHarnessEfficiencyLedger();l.record(row('local',accounting({executionKind:'LOCAL',localApiChargeKnownZero:true,pricing:null})));const p=usageProjection(l,[],{},now);assert.equal(p.totals.knownZeroApiCalls,1);assert.deepEqual(p.totals.apiCost.currencies,{});assert.equal(p.totals.energyCoverage.unavailableInvocations,1);});

test('tiny numeric provider charges retain an exact decimal bridge without exponent rejection',()=>{const r=createInvocationObservation({jobId:'tiny',taskId:'task',laneId:'lane',model:'model',provider:'provider',harnessProfile:'STANDARD',executionStrategy:'test',startedAt:at,completedAt:at,recipeFingerprint:'test',providerReportedCost:1e-8,pricing:{currency:'USD',source:'provider',freshInputPerMillionTokens:1,outputPerMillionTokens:1}});assert.equal(r.accounting?.reportedCost?.amount,'0.00000001');assert.equal(r.providerReportedCost,1e-8);});

test('POE exposes exact token coverage and local API distinction without claiming cost equivalence',()=>{
 const ledger=new MemoryHarnessEfficiencyLedger();ledger.record(row('local',accounting({executionKind:'LOCAL',pricing:null,localApiChargeKnownZero:true})));
 const p=usageProjection(ledger,[],{},now),answer=usageAnswer(p);assert.deepEqual(answer.accountedUsage.tokens,p.totals.tokens);assert.equal(answer.accountedUsage.knownZeroApiCalls,1);assert.equal(answer.executionKinds.find(k=>k.kind==='API')!.calls,0);assert.match(answer.comparisonLimitation,/attributable electricity/);assert.equal(answer.evidence.routingAuthority,'NONE');
});
