import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {ParameterizedJobRegistry,ParameterizedRunStore,SavedJobStore} from './parameterized-job-registry.js';
import {repositoryCodeReviewDefinition} from './repository-review-definition.js';
import type {ParameterizedJobRun} from './parameterized-job-types.js';
import {WorkParcelStore} from './work-parcels.js';
import {projectUxSession,sealUxSession,UxSessionAnnotationStore,UxSessionCaptureRuntime,UxSessionShareStore,UxSessionStore} from './ux-session.js';

function session(){return sealUxSession({
  id:'session-1',title:'Parallel review',startedAt:'2026-09-10T21:15:40Z',completedAt:'2026-09-10T21:17:04Z',
  sources:[{kind:'qualification-evidence',reference:'qualification.json',sha256:'a'.repeat(64),authority:'Agent Control durable evidence'}],
  lanes:[{id:'luna',name:'Luna',provider:'codex-chatgpt',model:'luna',outcome:'FAILED',inputTokens:10,outputTokens:2,totalTokens:12,cost:null,currency:null}],
  events:[
    {id:'ux-1',at:'2026-09-10T21:15:41Z',layer:'UX',kind:'USER_INTERACTION',title:'Request entered',summary:'Run a governed review',parentIds:[],evidenceRefs:[],interaction:{actor:'operator',action:'submit'}},
    {id:'lane-1',at:'2026-09-10T21:16:00Z',layer:'AGENT_CONTROL',kind:'LANE',title:'Luna gate failed',summary:'Independent criterion missing',outcome:'FAILED',laneId:'luna',provider:'codex-chatgpt',model:'luna',parentIds:['ux-1'],evidenceRefs:['gate:1'],diagnostic:{sanitisedInput:'bounded review',sanitisedOutput:'criterion missing'},authorised:{content:'internal source excerpt',sourcePaths:['src/private.ts']}},
  ],outcome:{verdict:'PASS',summary:'Another lane passed',selectedLaneId:'glm',escalationInvoked:false},totals:{inputTokens:10,outputTokens:2,totalTokens:12,cost:null,currency:null,authority:'PARTIAL'},artifacts:[],
});}

test('immutable session survives restart and detects mutation',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ux-session-'));try{const store=new UxSessionStore(root),record=store.write(session());assert.equal(new UxSessionStore(root).read(record.id).sha256,record.sha256);const file=path.join(root,'session-1.json'),mutated=JSON.parse(fs.readFileSync(file,'utf8'));mutated.title='altered';fs.writeFileSync(file,JSON.stringify(mutated));assert.throws(()=>store.read(record.id),/integrity/);}finally{fs.rmSync(root,{recursive:true,force:true});}});

test('audience projections fail closed and never expose source or authorised content',()=>{const record=session(),external=projectUxSession(record,'EXECUTION_OVERVIEW'),diagnostic=projectUxSession(record,'SANITISED_DIAGNOSTIC'),full=projectUxSession(record,'AUTHORISED_FULL_EVIDENCE');assert.equal(external.capabilities.operationalAccess,false);assert.equal(external.capabilities.rerun,false);assert.equal(external.capabilities.sourceAccess,false);assert.doesNotMatch(JSON.stringify(external),/private\.ts|internal source excerpt|sanitisedInput/);assert.match(JSON.stringify(diagnostic),/bounded review/);assert.doesNotMatch(JSON.stringify(diagnostic),/private\.ts|internal source excerpt/);assert.match(JSON.stringify(full),/internal source excerpt/);assert.doesNotMatch(JSON.stringify(full),/private\.ts/);});

test('shares store only a token hash, enforce expiry and revocation',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ux-share-'));try{const file=path.join(root,'shares.json'),store=new UxSessionShareStore(file),record=session(),created=store.create(record,'EXECUTION_OVERVIEW',{expiresAt:'2026-09-12T00:00:00Z',now:'2026-09-11T00:00:00Z'});assert.ok(created.url.includes('#token='));assert.doesNotMatch(fs.readFileSync(file,'utf8'),new RegExp(created.token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.equal(store.resolve(created.share.id,created.token,'2026-09-11T12:00:00Z').sessionId,record.id);assert.throws(()=>store.resolve(created.share.id,'wrong','2026-09-11T12:00:00Z'),/denied/);assert.throws(()=>store.resolve(created.share.id,created.token,'2026-09-13T00:00:00Z'),/expired/);const active=store.create(record,'UX_ONLY');store.revoke(active.share.id);assert.throws(()=>store.resolve(active.share.id,active.token),/revoked/);}finally{fs.rmSync(root,{recursive:true,force:true});}});

test('reviewer annotations remain a separate redacted overlay',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ux-comment-'));try{const record=session(),store=new UxSessionAnnotationStore(path.join(root,'annotations.json')),annotation=store.add(record,{eventId:'lane-1',reviewerId:'reviewer',comment:'This transition needs context; api_key=abcdefghi'});assert.equal(record.events.length,2);assert.match(annotation.comment,/REDACTED/);assert.equal(store.list(record.id).length,1);assert.throws(()=>store.add(record,{eventId:'missing',reviewerId:'reviewer',comment:'No'}),/event_missing/);}finally{fs.rmSync(root,{recursive:true,force:true});}});

test('normal terminal Job Run automatically becomes a sealed UX session projection',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ux-capture-'));try{const definitions=new ParameterizedJobRegistry();definitions.register(repositoryCodeReviewDefinition);const runs=new ParameterizedRunStore(path.join(root,'runs.json')),saved=new SavedJobStore(path.join(root,'saved.json'),definitions),parcels=new WorkParcelStore(path.join(root,'parcels.json')),sessions=new UxSessionStore(path.join(root,'sessions')),capture=new UxSessionCaptureRuntime(sessions,runs,saved,parcels);const run:ParameterizedJobRun={schema:'agent-control.job-run/v1',id:'run-terminal',occurrenceId:'occurrence',definition:repositoryCodeReviewDefinition,resolvedParameters:{node:'controller',repository:'/fixture',ref:'main',scope:'full'},trigger:{type:'manual',actor:'operator'},status:'SUCCEEDED',transitions:[{status:'QUEUED',at:'2026-09-11T10:00:00Z'},{status:'SUCCEEDED',at:'2026-09-11T10:00:10Z'}],requestedAt:'2026-09-11T10:00:00Z',startedAt:'2026-09-11T10:00:01Z',completedAt:'2026-09-11T10:00:10Z',workParcelIds:[],evidence:[],providerResponseIds:[],usage:{source:'unavailable'},errors:[],fallbackHistory:[],retryHistory:[],immutable:true};runs.add(run);const record=sessions.read('ux-run-run-terminal');assert.equal(record.outcome.verdict,'RECORDED');assert.equal(record.sources[0].reference,'job-run:run-terminal');assert.equal(projectUxSession(record,'EXECUTION_OVERVIEW').capabilities.rerun,false);capture.dispose();}finally{fs.rmSync(root,{recursive:true,force:true});}});
