import assert from 'node:assert/strict';
import test from 'node:test';
import {defaultCapabilities, type LaneState, type WorkspaceState} from '../state.js';
import {VerificationService} from './verification.js';

const now = () => new Date().toISOString();
function workspace(): WorkspaceState { const lane: LaneState = {id: 1, name: 'Lane 1', status: 'working', model: 'model-a', reasoning: 'high', context: '0', lines: [], contract: {version: 2, laneId: 1, goal: 'ship safe change', constraints: [], cwd: '/tmp', priority: 5, mode: 'auto', capabilities: defaultCapabilities(), modelLock: null, sharedTaskIds: [], updatedAt: now()}, baton: {version: 1, laneId: 1, revision: 3, status: 'working', progress: [], hypothesis: '', evidence: [], changes: [], nextAction: 'test', openQuestions: [], model: 'model-a', reasoning: 'high', updatedAt: now()}, lease: {laneId: 1, holder: 'agent-a', acquiredAt: now(), expiresAt: new Date(Date.now() + 60_000).toISOString()}}; return {version: 1, paused: false, lastRestorePoint: null, lanes: [lane]}; }

test('claim alone cannot satisfy a verification-required task', () => { const state = workspace(), service = new VerificationService(state, () => {}); service.setPolicy(1, {required: ['test_result']}); service.claim(1, 'done'); const result = service.verify(1); assert.equal(result.ok, false); assert.deepEqual(result.reasons, ['evidence_missing:test_result']); assert.equal(state.lanes[0].verification?.phase, 'claimed'); });
test('failed required evidence prevents VERIFIED state', () => { const state = workspace(), service = new VerificationService(state, () => {}); service.setPolicy(1, {required: ['test_result']}); service.claim(1, 'done'); service.addEvidence(1, {type: 'test_result', description: 'suite', status: 'failed'}); const result = service.verify(1); assert.equal(result.ok, false); assert.ok(result.reasons.includes('evidence_not_passed:test_result')); assert.ok(result.reasons.includes('failed_evidence_present')); });
test('valid evidence verifies and explicit acceptance is separately recorded', () => { const state = workspace(); let persisted = ''; const service = new VerificationService(state, value => { persisted = JSON.stringify(value); }); service.setPolicy(1, {required: ['git_commit', 'test_result'], requireHumanAcceptance: true}); service.claim(1, 'change complete'); service.addEvidence(1, {type: 'git_commit', description: 'commit abc', status: 'passed', reference: 'abc'}); service.addEvidence(1, {type: 'test_result', description: '156 tests', status: 'passed'}); assert.equal(service.verify(1).ok, true); assert.equal(state.lanes[0].verification?.phase, 'verified'); service.accept(1, 'human:operator'); assert.equal(state.lanes[0].verification?.phase, 'accepted'); const restored = JSON.parse(persisted) as WorkspaceState; assert.equal(restored.lanes[0].verification?.acceptedBy, 'human:operator'); assert.equal(restored.lanes[0].verification?.evidence.length, 2); });
