import assert from 'node:assert/strict';
import test from 'node:test';
import {once} from 'node:events';
import http from 'node:http';
import type {AddressInfo} from 'node:net';
import path from 'node:path';
import {defaultCapabilities, type LaneState, type WorkspaceState} from '../state.js';
import {AgentControlService} from './application-service.js';
import {PtyRegistry} from './pty.js';
import {startWebDashboard} from './web-server.js';
import fs from 'node:fs';
import os from 'node:os';
import {JobCatalog} from './job-catalog.js';
import {ActionRegistry, ArtifactStore, JobRuntime, ResourceLockManager, RunLedger, WorkerRegistry} from './job-runtime.js';
import {COMMAND_RESULT_SCHEMA, MemoryCommandResultStore, TokenAwareOutputService, type OutputAuthorityScope} from './token-aware-output.js';
import {MemoryHarnessEfficiencyLedger, createInvocationObservation} from './harness-efficiency.js';
import {WorkParcelCoordinator, WorkParcelStore, type WorkParcelPlanner} from './work-parcels.js';
import {ProviderRegistry} from './providers.js';
import {ModelRegistry} from './model-registry.js';
import {ParameterizedJobRegistry, ParameterizedRunStore, SavedJobStore} from './parameterized-job-registry.js';
import {repositoryCodeReviewDefinition} from './repository-review-definition.js';
import {ParameterizedJobEngine} from './parameterized-job-engine.js';
import {ReviewBaselineStore} from './repository-review-runtime.js';
import type {RepositoryReviewExecutor} from './parameterized-job-types.js';
import {IdentityControlPlane} from './identity-control-plane.js';
import {TokenAwareBatonRuntime} from './token-aware-baton-routing.js';
import {GovernedRetrievalRuntime, type RetrievalProvider} from './governed-retrieval.js';
import {CapabilityIntelligenceStore, registerAgentControlCoreCapabilities} from './capability-intelligence.js';
import {loadFrozenQualificationSuite, ModelIntelligenceLedger} from './model-intelligence.js';
import {ProviderCatalogRuntime, ProviderCatalogStore} from './provider-catalog.js';
import {CostRoutingLedger} from './cost-performance-routing.js';
import {SecureProviderCredentialStore} from './provider-credential-store.js';
import {AdaptiveOrchestrationRuntime, MemoryAdaptiveOrchestrationStore} from './adaptive-orchestration.js';
import {ExecutionSessionRuntime} from './execution-session.js';
import {CacheAwareExpertRuntime, FileCacheExpertStore} from './cache-aware-expert.js';
import {EnergyTelemetryRuntime} from './energy-telemetry.js';
import {WorkspacePreferenceStore} from './workspace-preferences.js';

const unauthenticatedFetch = globalThis.fetch;
function fetch(input: Parameters<typeof globalThis.fetch>[0], init: Parameters<typeof globalThis.fetch>[1] = {}) {
  const target = new URL(input instanceof Request ? input.url : String(input));
  if (target.pathname.startsWith('/api/') && target.pathname !== '/api/operator-auth' && (init?.method ?? 'GET') === 'GET') {
    const headers = new Headers(input instanceof Request ? input.headers : undefined);
    new Headers(init?.headers).forEach((value, key) => headers.set(key, value));
    if (!headers.has('Authorization')) headers.set('Authorization', 'Bearer test-token');
    return unauthenticatedFetch(input, {...init, headers});
  }
  return unauthenticatedFetch(input, init);
}

const now = () => new Date().toISOString();
function service() { const lane: LaneState = {id: 1, name: 'Primary', status: 'waiting', model: 'model-a', reasoning: 'medium', context: '0', lines: [], contract: {version: 2, laneId: 1, goal: 'safe task', constraints: [], cwd: '/tmp', priority: 1, mode: 'auto', capabilities: defaultCapabilities(), resourceLocks: {}, modelLock: null, sharedTaskIds: [], updatedAt: now()}, baton: {version: 1, laneId: 1, revision: 1, status: 'waiting', progress: [], hypothesis: '', evidence: [], changes: [], nextAction: 'schedule', openQuestions: [], model: 'model-a', reasoning: 'medium', updatedAt: now()}, lease: {laneId: 1, holder: null, acquiredAt: null, expiresAt: null}}; return new AgentControlService({version: 1, paused: false, lastRestorePoint: null, lanes: [lane]}, new PtyRegistry(), undefined, '3.1.0-test', () => {}); }
async function running(operatorToken: string | null = 'test-token') { const control = service(); const server = startWebDashboard(control, {host: '127.0.0.1', port: 0, operatorToken: operatorToken ?? undefined, assetsDir: path.resolve('assets/dashboard')}); await once(server, 'listening'); const port = (server.address() as AddressInfo).port; return {control, server, base: `http://127.0.0.1:${port}`}; }
async function runningWithControl(control:AgentControlService){const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');return{control,server,base:`http://127.0.0.1:${(server.address() as AddressInfo).port}`};}
function serviceWithJobs() { const control = service(), root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-control-web-jobs-')), actions = new ActionRegistry(); actions.register('test.run@1.0.0', async () => ({verification: ['ok']})); const catalog = new JobCatalog(actions.ids()); catalog.addJob({apiVersion: 'agent-control/v1', kind: 'Job', metadata: {id: 'web-job', name: 'Web Job', version: '1.0.0'}, spec: {priority: 'normal', concurrency: 'queue', parameters: {count: {type: 'integer', default: 2}, ratio: {type: 'number', default: 1.5}, enabled: {type: 'boolean', default: false}, label: {type: 'string', default: 'fixture'}, maximumOutputTokens: {type: 'integer', default: 32768}}, steps: [{id: 'run', action: 'test.run@1.0.0', requires: ['test'], approval: 'release', verification: ['ok']}]}}); const workers = new WorkerRegistry(); workers.register({id: 'worker', capabilities: ['test'], health: 'healthy', capacity: 1, active: 0, observedAt: now()}); const runtime = new JobRuntime(catalog, actions, workers, new RunLedger(path.join(root, 'ledger.json')), new ArtifactStore(path.join(root, 'artifacts')), new ResourceLockManager(path.join(root, 'locks.json'))); control.configureProjection({jobRuntime: runtime, resources: [{id: 'worker', name: 'Worker', platform: 'linux', transport: 'ssh', capabilities: ['test']}]}); return {control, runtime}; }
async function runningJobs(operatorToken: string | null = 'test-token') { const value = serviceWithJobs(), server = startWebDashboard(value.control, {host: '127.0.0.1', port: 0, operatorToken: operatorToken ?? undefined, assetsDir: path.resolve('assets/dashboard')}); await once(server, 'listening'); return {...value, server, base: `http://127.0.0.1:${(server.address() as AddressInfo).port}`}; }
async function runningParcels(operatorToken?: string) { const value = await runningJobs(operatorToken), root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-control-web-parcels-')); const planner: WorkParcelPlanner = {plan: prompt => ({objective: `interpreted:${prompt}`, planner: {kind: 'deterministic', reason: 'web fixture'}, stages: [{id: 'inspect', name: 'Inspect', job: 'web-job@1.0.0'}]})}, workParcels = new WorkParcelCoordinator(value.runtime, new WorkParcelStore(path.join(root, 'parcels.json')), planner); value.control.configureProjection({workParcels}); return {...value, workParcels}; }
async function runningParameterizedJobs(operatorToken='test-token') { const control=service(),root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-web-parameterized-')),definitions=new ParameterizedJobRegistry();definitions.register(repositoryCodeReviewDefinition);const models=new ModelRegistry([],[],{roles:{}}),executor:RepositoryReviewExecutor={execute:async()=>{throw new Error('not_executed_by_api_test')}};const engine=new ParameterizedJobEngine(definitions,new SavedJobStore(path.join(root,'saved.json'),definitions),new ParameterizedRunStore(path.join(root,'runs.json')),new ReviewBaselineStore(path.join(root,'baselines.json')),models,executor,{allowedRepositoryRoots:[root],snapshotsRoot:path.join(root,'snapshots'),nodeHealthy:()=>true});control.configureProjection({parameterizedJobs:engine,modelRegistry:models});const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken,assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');return{control,engine,server,base:`http://127.0.0.1:${(server.address() as AddressInfo).port}`};}

test('observer and status command can read the same versioned projection as dashboard assets', async t => { const {server, base} = await running(); t.after(() => server.close()); const status = await fetch(`${base}/api/status`); assert.equal(status.status, 200); const projection = await status.json(); assert.equal(projection.schema, 'agent-control.system-status/v1'); assert.equal(projection.authority, 'AgentControlService'); assert.equal(projection.lanes[0].task, 'safe task'); assert.equal(projection.characterCrew.schema, 'agent-control.dashboard-character-crew/v2'); assert.deepEqual(projection.characterCrew.members.map((item:{id:string})=>item.id), ['lane-master','prompt-reviewer','parcel-coordinator','model-scout','resource-guardian','quality-inspector']); assert.match(projection.characterCrew.members[1].instrumentation.limitation,/no separately instrumented prompt-review worker/i); assert.ok(projection.characterCrew.members.every((item:{animationCue:{authority:string}})=>item.animationCue.authority==='presentation-only')); assert.equal(projection.characterCrew.activityPanel.schema,'agent-control.dashboard-activity-panel/v1'); assert.ok(projection.characterCrew.activityPanel.groups.flatMap((item:{indicators:unknown[]})=>item.indicators).length>=8); const html = await fetch(base); assert.equal(html.status, 200); assert.match(await html.text(), /Agent Control/); for(const [asset,marker] of [['dashboard-bots.css','bot-'],['dashboard-bots.js','bot-'],['dashboard-wopr.css','activity-matrix'],['dashboard-wopr.js','activityMatrixRuntime']]){const response=await fetch(`${base}/${asset}`);assert.equal(response.status,200);assert.match(await response.text(),new RegExp(marker));} });
test('all control-plane API reads require authentication and route authority while assets and signed share routes remain separately governed', async t => {
  const control=service(),server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',operatorAuthorizer:(request,authority)=>authority==='control.read'&&request.headers['x-test-authority']==='read',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  assert.equal((await unauthenticatedFetch(base+'/api/status')).status,401);
  assert.equal((await unauthenticatedFetch(base+'/api/status',{headers:{Authorization:'Bearer wrong'}})).status,401);
  assert.equal((await unauthenticatedFetch(base+'/api/status',{headers:{Authorization:'Bearer test-token'}})).status,403);
  assert.equal((await unauthenticatedFetch(base+'/api/status',{headers:{Authorization:'Bearer test-token','X-Test-Authority':'read'}})).status,200);
  assert.equal((await unauthenticatedFetch(base+'/api/events')).status,401);
  assert.equal((await unauthenticatedFetch(base)).status,200);
});
test('control-plane API reads fail closed when operator authentication is not configured',async t=>{const {server,base}=await running(null);t.after(()=>server.close());assert.equal((await unauthenticatedFetch(base+'/api/status')).status,503);});
test('navigable workspace API supports authenticated search and durable operator favourites',async t=>{const control=service(),expected={schema:'agent-control.navigable-workspace/v1',id:'acw1.ESTATE.WyJlc3RhdGUiXQ',kind:'ESTATE'},root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-web-workspaces-')),preferences=new WorkspacePreferenceStore(path.join(root,'preferences.json'));(control as unknown as {workspaces:()=>unknown;workspace:(id:string)=>unknown;searchWorkspaces:(input:unknown)=>unknown}).workspaces=()=>expected;(control as unknown as {workspaces:()=>unknown;workspace:(id:string)=>unknown}).workspace=id=>({...expected,id});(control as unknown as {searchWorkspaces:(input:unknown)=>unknown}).searchWorkspaces=input=>({schema:'agent-control.workspace-search/v1',input,items:[expected],nextCursor:null,total:1});const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard'),workspacePreferences:preferences});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`,headers={Authorization:'Bearer test-token'};assert.equal((await unauthenticatedFetch(base+'/api/workspaces')).status,401);assert.deepEqual(await(await fetch(base+'/api/workspaces',{headers})).json(),expected);assert.equal((await fetch(base+'/api/workspaces?query=estate&limit=10',{headers})).status,200);assert.equal((await fetch(base+'/api/workspaces/'+encodeURIComponent(expected.id),{headers})).status,200);assert.equal((await fetch(base+'/api/workspaces/'+encodeURIComponent('x'.repeat(1025)),{headers})).status,400);assert.equal((await fetch(base+'/api/workspaces',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:'{}'})).status,404);const saved=await fetch(base+'/api/workspace-preferences/favourite',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({workspaceId:expected.id,favourite:true})});assert.equal(saved.status,200);assert.equal((await saved.json()).favourites.length,1);assert.equal((await(await fetch(base+'/api/workspace-preferences',{headers})).json()).favourites[0].workspaceId,expected.id);});
test('mutations fail closed when operator authentication is not configured', async t => { const {server, base} = await running(null); t.after(() => server.close()); const response = await fetch(`${base}/api/lanes/1/pause`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: '{}'}); assert.equal(response.status, 503); assert.equal((await response.json()).error, 'operator_auth_not_configured'); });
test('authenticated mutation uses the control service and rejects invalid origin', async t => { const {server, base, control} = await running('test-token'); t.after(() => server.close()); const denied = await fetch(`${base}/api/lanes/1/pause`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token', Origin: 'https://evil.invalid'}, body: '{}'}); assert.equal(denied.status, 403); const response = await fetch(`${base}/api/lanes/1/pause`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({actor: 'test-operator'})}); assert.equal(response.status, 200); assert.equal(control.state.lanes[0].status, 'paused'); });
test('authenticated parameterized authentication resume reaches the typed control operation', async t => { const {server,base,control}=await running('test-token');t.after(()=>server.close());let invocation:{id:string;actor:string}|undefined;(control as unknown as {resumeParameterizedRunAuthentication:(id:string,actor:string)=>unknown}).resumeParameterizedRunAuthentication=(id,actor)=>{invocation={id,actor};return{id,status:'QUEUED'}};const denied=await fetch(`${base}/api/job-runs/run-auth/resume-authentication`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(denied.status,401);const response=await fetch(`${base}/api/job-runs/run-auth/resume-authentication`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer test-token'},body:'{}'});assert.equal(response.status,202);assert.deepEqual(await response.json(),{id:'run-auth',status:'QUEUED'});assert.deepEqual(invocation,{id:'run-auth',actor:'web-operator'});});
test('live execution-session API is authenticated, streams real redacted bytes and enforces WATCH/INTERVENE authority', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-control-web-execution-session-')); t.after(() => fs.rmSync(root, {recursive: true, force: true}));
  const control = service(), sessions = new ExecutionSessionRuntime(path.join(root, 'sessions')), writes: string[] = [], secret = `nvapi-web-${'s'.repeat(24)}`, id = 'session:web', incarnation = 'incarnation:web';
  sessions.create({id, incarnation, adapterId: 'fixture-pipe', scope: {runId: 'run:web', jobId: 'web-job', jobVersion: '1.0.0', stepId: 'run', actionId: 'test.run@1.0.0', workerId: 'worker', nodeId: 'controller', parcelId: 'parcel:web', crewRole: 'quality-inspector'}, command: 'bounded-test', cwd: '/workspace', pid: 201, capabilities: {observableOutput: true, interactiveInput: true, terminal: 'pipe', resize: false, signals: ['INTERRUPT'], suspendResume: false, persistent: false, reconnectable: false, remoteTransport: false, modes: {watch: true, intervene: true, takeControl: false}, limitations: ['fixture']}, runtimeCredentials: [secret], control: {prove: async () => ({sessionId: id, incarnation, state: 'RUNNING', pid: 201}), write: async value => { writes.push(value); }, signal: async () => {}}});
  control.configureProjection({executionSessions: sessions}); const server = startWebDashboard(control, {host: '127.0.0.1', port: 0, operatorToken: 'test-token', assetsDir: path.resolve('assets/dashboard')}); await once(server, 'listening'); t.after(() => server.close()); const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`, headers = {'Content-Type': 'application/json', Authorization: 'Bearer test-token'};
  assert.equal((await unauthenticatedFetch(`${base}/api/execution-sessions`)).status, 401); assert.equal((await unauthenticatedFetch(`${base}/api/execution-sessions/${encodeURIComponent(id)}/stream`)).status, 401);
  const listed = await (await fetch(`${base}/api/execution-sessions`, {headers: {Authorization: 'Bearer test-token'}})).json(); assert.equal(listed[0].id, id); assert.equal(listed[0].scope.parcelId, 'parcel:web'); assert.equal('text' in listed[0], false);
  const watch = await (await fetch(`${base}/api/execution-sessions/${encodeURIComponent(id)}/attach`, {method: 'POST', headers, body: JSON.stringify({mode: 'WATCH'})})).json();
  const watchWrite = await fetch(`${base}/api/execution-sessions/${encodeURIComponent(id)}/input`, {method: 'POST', headers, body: JSON.stringify({attachmentId: watch.id, value: 'forbidden'})}); assert.equal(watchWrite.status, 403); assert.equal((await watchWrite.json()).error, 'execution_session_watch_read_only');
  const intervention = await (await fetch(`${base}/api/execution-sessions/${encodeURIComponent(id)}/attach`, {method: 'POST', headers, body: JSON.stringify({mode: 'INTERVENE'})})).json();
  const input = await fetch(`${base}/api/execution-sessions/${encodeURIComponent(id)}/input`, {method: 'POST', headers, body: JSON.stringify({attachmentId: intervention.id, value: 'approved\n'})}); assert.equal(input.status, 200); assert.deepEqual(writes, ['approved\n']);
  sessions.appendOutput(id, 'stdout', `real-before ${secret.slice(0, 8)}`); sessions.appendOutput(id, 'stdout', `${secret.slice(8)} real-after\n`); sessions.flushOutput(id);
  const abort = new AbortController(), response = await fetch(`${base}/api/execution-sessions/${encodeURIComponent(id)}/stream?after=0`, {headers: {Authorization: 'Bearer test-token'}, signal: abort.signal}); assert.equal(response.status, 200);
  const reader = response.body!.getReader(); let streamed = ''; for (let index = 0; index < 10 && !streamed.includes('real-after'); index++) streamed += new TextDecoder().decode((await reader.read()).value); abort.abort();
  assert.match(streamed, /event: output/); assert.match(streamed, /real-before/); assert.match(streamed, /real-after/); assert.equal(streamed.includes(secret), false); assert.match(streamed, /REDACTED/);
  const transcript = await (await fetch(`${base}/api/execution-sessions/${encodeURIComponent(id)}/transcript`, {headers: {Authorization: 'Bearer test-token'}})).json(); assert.match(transcript.content, /real-before/); assert.equal(transcript.content.includes(secret), false); assert.doesNotMatch(transcript.content, /approved/);
  const status = JSON.stringify(await (await fetch(`${base}/api/status`)).json()); assert.equal(status.includes('real-before'), false); assert.equal(status.includes(secret), false);
  for (const asset of ['dashboard-live-shell.css', 'dashboard-live-shell.js']) assert.equal((await fetch(`${base}/${asset}`)).status, 200);
});
test('no API route permits direct lease, scheduler, or PTY writes', async t => { const {server, base} = await running('test-token'); t.after(() => server.close()); for (const route of ['lease', 'scheduler', 'pty-input']) { const response = await fetch(`${base}/api/lanes/1/${route}`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: '{}'}); assert.equal(response.status, 404); } });
test('typed SSE stream replays authoritative control events', async t => { const {server, base, control} = await running(); t.after(() => server.close()); control.pauseLane(1, 'test'); const abort = new AbortController(); const response = await fetch(`${base}/api/events`, {headers: {'Last-Event-ID': '0'}, signal: abort.signal}); const reader = response.body!.getReader(); const first = await reader.read(); const text = new TextDecoder().decode(first.value); abort.abort(); assert.match(text, /event: lane\.status_changed/); assert.match(text, /"type":"lane.status_changed"/); });
test('token routing projection is served and live telemetry is published through the SSE event stream', async t => { const {server, base, control} = await running(); t.after(() => server.close()); const routing = new TokenAwareBatonRuntime(); control.configureProjection({tokenBatonRouting: routing}); routing.subscribe(event => control.events.emit(event.type === 'telemetry' ? 'token.telemetry' : event.type === 'context.lifecycle' ? 'token.context_lifecycle' : 'token.governor_transition', {threadId: event.threadId, parcelId: event.parcelId}, undefined, 'test')); routing.observe({threadId: 'thread:one', parcelId: 'parcel:one', agentId: 'agent:one', providerId: 'openai', modelId: 'sol', elapsedMs: 1_000, cumulative: {inputTokens: 100, freshInputTokens: 70, cachedInputTokens: 30, outputTokens: 20, totalTokens: 120}, context: {tokens: 80, limitTokens: 100, authority: 'authoritative', source: 'provider'}}); routing.recordContextLifecycle('thread:one', {kind: 'COMPACTION', authority: 'authoritative', source: 'provider'}); const projection = await (await fetch(`${base}/api/token-routing`)).json(); assert.equal(projection.threads[0].latest.context.tokens, 80); assert.equal(projection.threads[0].latest.cumulative.freshInputTokens, 70); assert.equal(projection.threads[0].latest.cumulative.cachedInputTokens, 30); assert.equal(projection.threads[0].governor.state, 'PREPARE_BATON'); assert.equal(projection.contextLifecycle[0].kind, 'COMPACTION'); const abort = new AbortController(), response = await fetch(`${base}/api/events`, {headers: {'Last-Event-ID': '0'}, signal: abort.signal}), reader = response.body!.getReader(), first = await reader.read(), text = new TextDecoder().decode(first.value); abort.abort(); assert.match(text, /event: token\.telemetry/); assert.match(text, /event: token\.context_lifecycle/); assert.match(text, /"threadId":"thread:one"/); assert.match(text, /"tokens":80/); assert.match(text, /"cachedInputTokens":30/); });

test('energy projection preserves measured scope and unavailable cloud energy',async t=>{const control=service(),energy=new EnergyTelemetryRuntime(),at=(s:number)=>`2026-09-11T00:00:${String(s).padStart(2,'0')}.000Z`;energy.recordExecution({parcelId:'parcel:energy',stageId:'infer',route:{providerId:'local',modelId:'small',nodeId:'controller'},samples:[{at:at(0),nodeId:'controller',scope:'GPU_ONLY',watts:20,authority:'MEASURED',source:'qualified-gpu-sensor',limitations:[]},{at:at(10),nodeId:'controller',scope:'GPU_ONLY',watts:30,authority:'MEASURED',source:'qualified-gpu-sensor',limitations:[]}],verified:true,successful:true});control.configureProjection({energyTelemetry:energy});const{server,base}=await runningWithControl(control);t.after(()=>server.close());const value=await(await fetch(`${base}/api/energy`)).json();assert.equal(value.executions[0].scope,'GPU_ONLY');assert.equal(value.executions[0].authority,'MEASURED');assert.ok(value.executions[0].limitations.includes('measurement_not_whole_node'));});

test('execution-history context counters remain visible while credential-like token fields stay redacted', async t => {
  const control=service();
  (control as unknown as {parameterizedRuns:()=>unknown[]}).parameterizedRuns=()=>[{id:'run-history',executionHistory:{entries:[{telemetry:{contextTokens:80,contextLimitTokens:100,inputTokens:70,outputTokens:10,totalTokens:80,tokenEfficiency:441.11},credentialToken:'must-not-leak'}]}}];
  const {server,base}=await runningWithControl(control);t.after(()=>server.close());
  const [run]=await(await fetch(`${base}/api/job-runs`)).json();
  assert.equal(run.executionHistory.entries[0].telemetry.contextTokens,80);
  assert.equal(run.executionHistory.entries[0].telemetry.contextLimitTokens,100);
  assert.equal(run.executionHistory.entries[0].telemetry.tokenEfficiency,441.11);
  assert.equal(run.executionHistory.entries[0].credentialToken,'[REDACTED]');
});

test('opaque credential residency node identity remains visible while credential values stay redacted',async t=>{const control=service();(control as unknown as {parameterizedRuns:()=>unknown[]}).parameterizedRuns=()=>[{id:'run-locality',credentialNodeId:'provider-node',credentialToken:'must-not-leak',nested:{credentialNodeId:'controller-node',credentialValue:'must-not-leak'}}];const{server,base}=await runningWithControl(control);t.after(()=>server.close());const[run]=await(await fetch(`${base}/api/job-runs`)).json();assert.equal(run.credentialNodeId,'provider-node');assert.equal(run.nested.credentialNodeId,'controller-node');assert.equal(run.credentialToken,'[REDACTED]');assert.equal(run.nested.credentialValue,'[REDACTED]')});

test('governed retrieval projection is redacted and streams over the existing SSE transport',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-web-retrieval-'));fs.writeFileSync(path.join(root,'source.ts'),'export const Needle = true;\n');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const provider:RetrievalProvider={descriptor:()=>({id:'fixture',name:'fixture',locality:'LOCAL',strategies:['EXACT'],capabilities:['retrieval.search'],index:{required:false}}),retrieve:async()=>({providerId:'fixture',strategy:'EXACT',evidence:[{path:'source.ts',text:'export const Needle = true;',score:1}],latencyMs:2,cost:{amount:0,currency:'USD',authority:'authoritative'},index:{state:'NOT_REQUIRED'},rawBytesConsidered:100})};const retrieval=new GovernedRetrievalRuntime([provider],{enabled:true,progression:['EXACT'],minimumConfidence:0,requiredCoverage:0}),control=service();control.configureProjection({governedRetrieval:retrieval});retrieval.subscribe(event=>control.events.emit(event.type,{parcelId:event.parcelId,intentId:event.intentId},undefined,'test'));const {server,base}=await runningWithControl(control);t.after(()=>server.close());await retrieval.retrieve({id:'intent:web',parcelId:'parcel:web',taskType:'test',query:'Needle',repository:{repositoryId:'repo',root,gitSha:'abc',dirty:false}});const projection=await(await fetch(`${base}/api/retrieval`)).json();assert.equal(projection.totals.evidenceCount,1);assert.equal(JSON.stringify(projection).includes('export const Needle'),false);assert.match(fs.readFileSync(path.resolve('assets/dashboard/dashboard.js'),'utf8'),/retrieval\.evidence/);});

test('adaptive APIs expose the persisted leagues, decision tree and canonical human-readable report', async t => {
  const adaptive = new AdaptiveOrchestrationRuntime(new MemoryAdaptiveOrchestrationStore(), {}, () => '2026-09-07T00:00:00.000Z');
  const decision = adaptive.startDecision({parcelId: 'parcel-web-adaptive', objective: 'review a repository', taskClass: 'repository-review', requiredCapabilities: ['repository-review'], workflowId: 'repository-review'});
  const selectedRoute = {providerId: 'provider-web', modelId: 'review-model', accountProfileId: null, nodeId: 'controller', modelVersion: 'qualification-1'};
  adaptive.recordOutcome({decisionId: decision.id, parcelId: 'parcel-web-adaptive', stageId: 'review', observationId: 'invocation-web', route: selectedRoute, capabilities: ['repository-review'], workflow: {id: 'repository-review', version: '1'}, evidenceKind: 'PRODUCTION_WORK_PARCEL', outcome: 'SUCCEEDED', verified: true, qualityScore: .95, qualityGatePass: true, firstPass: true, usage: {inputTokens: 100, cachedInputTokens: 20, outputTokens: 30, totalTokens: 130}, cost: .01, costAuthority: 'authoritative'});
  adaptive.evaluateDecision(decision.id, {stageId: 'review', candidates: [{route: selectedRoute, eligible: true, reasons: [], capabilities: ['repository-review'], availability: 'available', estimatedCost: .01, costAuthority: 'authoritative'}], workflowCandidates: [{id: 'repository-review', version: '1', eligible: true, reasons: []}]});
  const control = service().configureProjection({adaptiveOrchestration: adaptive});
  const server = startWebDashboard(control, {host: '127.0.0.1', port: 0, operatorToken: 'test-token', assetsDir: path.resolve('assets/dashboard')}); await once(server, 'listening'); t.after(() => server.close()); const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const models = await (await fetch(`${base}/api/orchestration/models?taskClass=repository-review&evidenceKind=PRODUCTION_WORK_PARCEL&modelVersion=qualification-1&location=local&sort=quality`)).json();
  const workflows = await (await fetch(`${base}/api/orchestration/workflows?taskClass=repository-review&evidenceKind=PRODUCTION_WORK_PARCEL`)).json();
  const decisions = await (await fetch(`${base}/api/orchestration/decisions`)).json();
  const detail = await (await fetch(`${base}/api/orchestration/decisions/${encodeURIComponent(decision.id)}`)).json();
  const report = await (await fetch(`${base}/api/orchestration/decisions/${encodeURIComponent(decision.id)}/report`)).json();
  assert.equal(models[0].route.providerId, 'provider-web'); assert.equal(models[0].sampleSize, 1); assert.equal(models[0].cacheEfficiency, .2);
  assert.equal(workflows[0].workflow.id, 'repository-review'); assert.equal(decisions[0].id, decision.id); assert.equal(detail.id, decision.id); assert.equal(report.steps.length, detail.nodes.length); assert.ok(report.steps.some((step: {parentId?: string | null}) => step.parentId)); assert.equal(report.evidence[0].currency, null); assert.equal(report.evidence[0].cost, .01); assert.match(report.humanReadable, /Routing & Orchestration Decision Record/); assert.match(report.humanReadable, /input 100 \/ output 30 \/ total 130/);
  const html = await (await fetch(base)).text(), script = await (await fetch(`${base}/dashboard-adaptive-orchestration.js`)).text(); assert.match(html, /data-view="routing">Routing/); assert.match(html, /Model Capability League/); assert.match(html, /Workflow League/); assert.match(html, /orchestration-version-filter/); assert.match(html, /orchestration-location-filter/); assert.match(script, /parent \$\{esc\(step.parentId\|\|'root'\)\}/); assert.match(script, /modelVersion/); assert.match(script, /location/); assert.match(script, /api\/orchestration\/decisions/);
});
test('Warm Experts API and dashboard expose provider-neutral cache evidence and human-readable decisions', async t => {
  const experts=new CacheAwareExpertRuntime(new FileCacheExpertStore(),{maximumScoreBonus:.2},()=> '2026-09-09T10:01:00.000Z'),route={workerId:'controller',providerId:'local',modelId:'qwen',nodeId:'controller',sessionId:'session-1',cacheScopeId:'slot-0',backendInstanceId:'process-1'},context={repositoryRef:'agent-control@abc',repositoryIdentitySha256:'repo',immutableContextSha256:'bundle',promptPrefixSha256:'prefix',contextTags:['repository:agent-control']};
  experts.observe({invocationId:'inv-web-cache',route,context,cacheEvidence:{reusedTokens:900,processedPromptTokens:100,cacheWriteTokens:null,promptProcessingMs:10,generationMs:20,authority:'authoritative',source:'llama.cpp.timings'},observedAt:'2026-09-09T10:00:00.000Z',taskClass:'coding',capabilities:['coding'],outcome:'COMPLETE',verifierResult:'PASS',health:'healthy'});
  experts.assess({parcelId:'parcel-cache',stageId:'follow-on',context,candidates:[{route,eligible:true,capabilityQualified:true,integrityQualified:true,health:'healthy',baseScore:.8,reasons:[]}]});
  const control=service().configureProjection({cacheExperts:experts}),server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const projection=await(await fetch(`${base}/api/cache-experts`)).json(),html=await(await fetch(base)).text(),source=await(await fetch(`${base}/dashboard-cache-experts.js`)).text(),styles=await(await fetch(`${base}/dashboard-cache-runtime.css`)).text();assert.equal(projection.experts[0].state,'HOT');assert.equal(projection.decisions[0].verifier.status,'PASS');assert.match(projection.decisions[0].humanReadable,/Capability, integrity and governance always outrank cache warmth/);assert.match(html,/data-view="experts">Warm Cache Runtime/);assert.match(html,/Runtime Timeline/);assert.match(source,/Cache Heatmap/);assert.match(source,/Agent & Process Utilization/);assert.match(source,/Compatibility Matrix/);assert.match(html,/Candidate Routes/);assert.match(html,/Route Explanation/);assert.match(html,/Cross-lane Visibility/);assert.match(source,/estimated context delta/i);assert.match(html,/MONETARY SAVING UNAVAILABLE/);assert.match(source,/Agent Control will not fabricate cross-lane reuse relationships/);assert.match(styles,/cache-timeline-row/);assert.match(styles,/cache-heatmap/);
  assert.equal((await fetch(`${base}/api/cache-experts/invalidate`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,401);
  const invalidated=await fetch(`${base}/api/cache-experts/invalidate`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer test-token'},body:JSON.stringify({backendInstanceId:'process-1',reason:'backend-restarted'})});assert.equal(invalidated.status,200);assert.equal((await invalidated.json()).count,1);assert.equal((await(await fetch(`${base}/api/cache-experts`)).json()).experts[0].state,'INVALIDATED');assert.equal(control.events.history().at(-1)?.type,'cache.expert_invalidated');
});

test('safe retained prompt token accounting remains visible while secret-like fields stay redacted', async t => {
  const experts=new CacheAwareExpertRuntime(new FileCacheExpertStore(),{allowDerivedPreference:true},()=> '2026-09-09T10:01:00.000Z'),route={workerId:'controller',providerId:'local',modelId:'qwen',nodeId:'controller',sessionId:'session-1',cacheScopeId:'slot-0',backendInstanceId:'process-1'},context={repositoryRef:'agent-control@abc'};
  experts.observe({invocationId:'inv-retained',route,context,cacheEvidence:{reusedTokens:0,processedPromptTokens:100,cacheWriteTokens:null,promptProcessingMs:10,generationMs:20,authority:'authoritative',source:'llama.cpp.timings',retainedPromptTokens:100,retentionAuthority:'derived',retentionSource:'qualified'},observedAt:'2026-09-09T10:00:00.000Z',taskClass:'coding',capabilities:['coding'],outcome:'COMPLETE',verifierResult:'PASS',health:'healthy'});
  const control=service().configureProjection({cacheExperts:experts}),server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const body=await(await fetch(`${base}/api/cache-experts`)).json(); assert.equal(body.experts[0].cache.retainedPromptTokens,100); assert.equal(JSON.stringify(body).includes('[REDACTED]'),false);
});
test('Jobs, queue, workers, locks, artifacts and Run history share the authoritative runtime', async t => { const {server, base, runtime} = await runningJobs(); t.after(() => server.close()); assert.equal((await (await fetch(`${base}/api/jobs`)).json())[0].metadata.id, 'web-job'); assert.deepEqual(await (await fetch(`${base}/api/runs`)).json(), []); assert.deepEqual(await (await fetch(`${base}/api/queue`)).json(), []); assert.equal((await (await fetch(`${base}/api/workers`)).json())[0].id, 'worker'); const status = await (await fetch(`${base}/api/status`)).json(); assert.equal(status.resources[0].health, 'healthy'); assert.equal(status.resources[0].capacity, 1); runtime.workers.setHealth('worker', 'offline'); assert.equal((await (await fetch(`${base}/api/status`)).json()).health, 'degraded'); assert.deepEqual(await (await fetch(`${base}/api/resources`)).json(), []); assert.deepEqual(await (await fetch(`${base}/api/artifacts`)).json(), []); const css = await fetch(`${base}/dashboard-jobs.css`), javascript = await fetch(`${base}/dashboard-enhancements.js`), parameters = await fetch(`${base}/dashboard-parameters.js`), runningState = await fetch(`${base}/dashboard-running-state.js`); assert.equal(css.status, 200); assert.equal(parameters.status, 200); assert.equal(runningState.status, 200); const styles = await css.text(); assert.match(styles, /authority-note/); assert.match(styles, /agent-control-status-pulse/); assert.match(styles, /prefers-reduced-motion:reduce/); assert.match(styles, /running-summary:focus-visible/); assert.match(styles, /lane-live/); assert.match(styles, /workflow-preview/); const source = await javascript.text(), stateSource = await runningState.text(); assert.match(source, /renderWorkersAndLocks/); assert.match(source, /Last meaningful activity|Unavailable until provider reports/); assert.match(source, /running-inspector/); assert.match(stateSource, /Usage reported on completion/); assert.match(source, /Latest actual events/); assert.match(source, /Why this model \/ route/); assert.match(source, /Invocation → Job → Stage → Parcel accounting/); assert.match(source, /Planner selecting route/); assert.match(source, /renderWorkflowPreview/); assert.match(source, /Selected workflow details/); assert.match(source, /aria-expanded/); });
test('parameterised Job APIs create, export, run and expose first-class dashboard views',async t=>{const{server,base,engine}=await runningParameterizedJobs();t.after(()=>server.close());const headers={'Content-Type':'application/json',Authorization:'Bearer test-token'},definitions=await(await fetch(`${base}/api/job-definitions`)).json();assert.equal(definitions[0].id,'repository-code-review');const createdResponse=await fetch(`${base}/api/saved-jobs`,{method:'POST',headers,body:JSON.stringify({id:'repo-review',name:'Repo Review',definition:{id:'repository-code-review',version:1,follow:'latest-compatible'},parameters:{node:'controller',repository:'/tmp/repo',ref:'main',scope:'changes'},routing:{modelRole:'review.default',allowFallback:true},contextProfile:'STANDARD',concurrency:'forbid-overlap',enabled:true})});assert.equal(createdResponse.status,201);const created=await createdResponse.json();assert.equal(created.revision,1);const runResponse=await fetch(`${base}/api/saved-jobs/repo-review/run`,{method:'POST',headers,body:'{}'});assert.equal(runResponse.status,201);assert.equal(engine.runs.list()[0].trigger.type,'manual');const exported=await(await fetch(`${base}/api/saved-jobs/repo-review/export`)).json();assert.equal(exported.name,'Repo Review');assert.doesNotMatch(JSON.stringify(exported),/token|password|credential/i);const asset=await fetch(`${base}/dashboard-parameterized-jobs.js`),html=await(await fetch(base)).text();assert.equal(asset.status,200);assert.match(await asset.text(),/Job Definitions|job-platform-definitions/);assert.match(html,/Saved Jobs/);assert.match(html,/Schedules/);assert.match(html,/job-platform-runs/);});
test('authenticated Run Now uses createRun and Job failure cannot mutate lane authority', async t => { const {server, base, control, runtime} = await runningJobs('test-token'); t.after(() => server.close()); const before = structuredClone(control.state.lanes[0]), response = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({actor: 'operator'})}); assert.equal(response.status, 201); const created = await response.json(); assert.equal(runtime.ledger.get(created.id)?.trigger.type, 'manual'); assert.deepEqual(control.state.lanes[0].lease, before.lease); assert.equal(control.state.lanes[0].status, before.status); assert.deepEqual(control.state.lanes[0].baton, before.baton); });
test('Run Now preserves typed parameters and returns safe validation detail', async t => { const {server, base} = await runningJobs('test-token'); t.after(() => server.close()); const headers = {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}; const accepted = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers, body: JSON.stringify({parameters: {count: 3, ratio: .25, enabled: true, label: 'typed'}})}); assert.equal(accepted.status, 201); assert.deepEqual((await accepted.json()).parameters, {count: 3, ratio: .25, enabled: true, label: 'typed', maximumOutputTokens: 32768}); const rejected = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers, body: JSON.stringify({parameters: {count: '3'}})}); assert.equal(rejected.status, 400); const body = await rejected.json(); assert.equal(body.error, 'invalid_parameter_type:count'); assert.deepEqual(body.issues, ['invalid_parameter_type:count']); });
test('artifact collection exposes provenance and checksum but not managed storage paths', async t => { const {server, base, runtime} = await runningJobs('test-token'); t.after(() => server.close()); const response = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: '{}'}), created = await response.json(), run = runtime.ledger.get(created.id)!; runtime.artifacts.create(run, 'run', 'worker', {name: 'report', type: 'application/json', schema: 'report/v1', version: '1.0.0'}, {ok: true}); const artifacts = await (await fetch(`${base}/api/artifacts?runId=${encodeURIComponent(created.id)}`)).json(); assert.equal(artifacts.length, 1); assert.match(artifacts[0].sha256, /^[a-f0-9]{64}$/); assert.equal(artifacts[0].provenance.workerId, 'worker'); assert.equal(artifacts[0].storage, 'agent-control-managed'); assert.equal('storageRef' in artifacts[0], false); });
test('speculative token metrics remain visible while credential tokens remain redacted', async t => { const {server, base, runtime} = await runningJobs('test-token'); t.after(() => server.close()); const createdResponse=await fetch(`${base}/api/jobs/web-job/run`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer test-token'},body:'{}'}),run=runtime.ledger.get((await createdResponse.json()).id)!;const artifact=runtime.artifacts.create(run,'run','worker',{name:'speculative',type:'application/json',schema:'speculative/v1',version:'1'}, {draftTokens:3,bestDraftTokens:2,tokensPerSecond:27.1,baselineTokensPerSecond:27.1,bestSpeculativeTokensPerSecond:33.7,energyPerToken:null,accessToken:'secret-value'});const body=await(await fetch(`${base}/api/artifacts/${artifact.id}/content`,{headers:{Authorization:'Bearer test-token'}})).json();assert.equal(body.content.draftTokens,3);assert.equal(body.content.bestDraftTokens,2);assert.equal(body.content.tokensPerSecond,27.1);assert.equal(body.content.bestSpeculativeTokensPerSecond,33.7);assert.equal(body.content.accessToken,'[REDACTED]');});
test('managed artifact content is operator-authenticated and API-redacted', async t => {
  const {server,base,runtime}=await runningJobs('test-token'); t.after(()=>server.close());
  const run=runtime.createRun('web-job@1.0.0',{}, {type:'manual',actor:'test'}), artifact=runtime.artifacts.create(run,'run','worker',{name:'transcript',type:'application/json',schema:'test.transcript/v1',version:'1.0.0'},{transcript:[{type:'provider',reusedTokens:75,processedPromptTokens:25,prompt_tokens:100,prompt_tokens_details:{cached_tokens:75},prompt_per_token_ms:1.25,accessToken:'sk-test-secret-value-123456'}]});
  assert.equal((await unauthenticatedFetch(`${base}/api/artifacts/${artifact.id}/content`)).status,401);
  const response=await fetch(`${base}/api/artifacts/${artifact.id}/content`,{headers:{Authorization:'Bearer test-token'}}), body=await response.json(), serialized=JSON.stringify(body);
  assert.equal(response.status,200); assert.equal(body.content.transcript[0].reusedTokens,75); assert.equal(body.content.transcript[0].processedPromptTokens,25); assert.equal(body.content.transcript[0].prompt_tokens,100); assert.equal(body.content.transcript[0].prompt_tokens_details.cached_tokens,75); assert.equal(body.content.transcript[0].prompt_per_token_ms,1.25); assert.equal(body.content.transcript[0].accessToken,'[REDACTED]'); assert.equal(serialized.includes('sk-test-secret-value'),false); assert.equal(serialized.includes('storageRef'),false);
});
test('Job mutations fail closed without operator authentication and expose no PTY input route', async t => { const deniedServer = await runningJobs(null); t.after(() => deniedServer.server.close()); const denied = await fetch(`${deniedServer.base}/api/jobs/web-job/run`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: '{}'}); assert.equal(denied.status, 503); const authenticated = await runningJobs('test-token'); t.after(() => authenticated.server.close()); const pty = await fetch(`${authenticated.base}/api/jobs/web-job/pty-input`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: '{}'}); assert.equal(pty.status, 404); });
test('operator authentication projection distinguishes disabled required and authenticated', async t => { const disabled = await running(null); t.after(() => disabled.server.close()); assert.equal((await (await fetch(`${disabled.base}/api/operator-auth`)).json()).state, 'disabled'); const configured = await running('test-token'); t.after(() => configured.server.close()); assert.equal((await (await fetch(`${configured.base}/api/operator-auth`)).json()).state, 'authentication_required'); assert.equal((await (await fetch(`${configured.base}/api/operator-auth`, {headers:{Authorization:'Bearer test-token'}})).json()).state, 'authenticated'); });
test('operator configuration API safely adds systems and retains credential references without exposing key values', async t => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-web-config-')),configFile=path.join(root,'config.json');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
  fs.writeFileSync(configFile,JSON.stringify({schemaVersion:1,resources:[],providers:[{id:'external',kind:'responses',baseUrl:'https://provider.example/v1',requiresAuth:true,credentialEnv:'EXTERNAL_API_KEY'}],services:[],lanes:[]}));
  const control=service(),server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard'),configFile});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  assert.equal((await unauthenticatedFetch(`${base}/api/configuration`)).status,401);
  const headers={Authorization:'Bearer test-token'},current=await (await fetch(`${base}/api/configuration`,{headers})).json();assert.equal(current.providers[0].credentialEnv,'EXTERNAL_API_KEY');assert.doesNotMatch(JSON.stringify(current),/sk-live-secret/);
  const saved=await fetch(`${base}/api/configuration/systems`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({revision:current.revision,kind:'resource',item:{id:'remote-host',name:'Remote host',platform:'linux',transport:{type:'ssh',host:'remote-host',user:'operator'},capabilities:[]}})});assert.equal(saved.status,200);assert.equal((await saved.json()).restartRequired,true);assert.equal(JSON.parse(fs.readFileSync(configFile,'utf8')).resources[0].id,'remote-host');
  const latest=await (await fetch(`${base}/api/configuration`,{headers})).json(),unsafe=await fetch(`${base}/api/configuration/systems`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({revision:latest.revision,kind:'provider',item:{id:'unsafe',kind:'responses',apiKey:'sk-live-secret'}})});assert.equal(unsafe.status,400);assert.equal(JSON.parse(fs.readFileSync(configFile,'utf8')).providers.length,1);
  const spark=await fetch(`${base}/api/configuration/spark`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({revision:latest.revision,spark:{enabled:false,model:'gpt-5.3-codex-spark',modelRole:'fast-execution',maximumFiles:1,maximumChangedLines:80,maximumAttempts:1,maximumSubagents:0,maximumContextTokens:2048,verificationRequired:true}})});assert.equal(spark.status,200);assert.equal((await spark.json()).spark.enabled,false);assert.equal(JSON.parse(fs.readFileSync(configFile,'utf8')).spark.maximumAttempts,1);
  const afterSpark=await (await fetch(`${base}/api/configuration`,{headers})).json(),adaptive=await fetch(`${base}/api/configuration/adaptive-orchestration`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({revision:afterSpark.revision,adaptiveOrchestration:{enabled:true,minimumSamplesForPreference:3,minimumQualityScore:.7,maxEvidenceAgeDays:90,policyQualityFloor:.6,maxRouteCost:null,maxRouteLatencyMs:null,qualityWeight:.5,reliabilityWeight:.2,costWeight:.15,latencyWeight:.1,confidenceWeight:.05,explorationRate:.1}})});assert.equal(adaptive.status,200);assert.equal((await adaptive.json()).adaptiveOrchestration.maxRouteCost,null);assert.equal(JSON.parse(fs.readFileSync(configFile,'utf8')).adaptiveOrchestration.enabled,true);
  const afterAdaptive=await (await fetch(`${base}/api/configuration`,{headers})).json(),cache=await fetch(`${base}/api/configuration/cache-aware-experts`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({revision:afterAdaptive.revision,cacheAwareExperts:{enabled:true,hotMinutes:10,warmMinutes:60,expiryMinutes:240,hotReuseRatio:.7,minimumReuseRatio:.25,highCompatibilityMaximumDelta:.25,partialCompatibilityMaximumDelta:.6,maximumScoreBonus:.15,allowDerivedPreference:false}})});assert.equal(cache.status,200);assert.equal((await cache.json()).cacheAwareExperts.allowDerivedPreference,false);assert.equal(JSON.parse(fs.readFileSync(configFile,'utf8')).cacheAwareExperts.maximumScoreBonus,.15);
});
test('model registry APIs expose safe identity and governed deterministic routes', async t => {
  const control=service(),registry=new ModelRegistry([{id:'external',name:'External',kind:'openai-compatible',baseUrl:'https://models.example/v1',wireApi:'responses',auth:{type:'bearer-env',env:'SECRET_ENV_NAME'}}],[{id:'fast',provider:'external',providerModel:'vendor/fast',capabilities:['coding'],qualification:{state:'QUALIFIED',version:'q1',qualifiedAt:'2026-09-01T00:00:00Z',capabilities:['coding'],nodes:['worker']}}],{roles:{'coding.fast':{primary:'fast'}}});control.configureProjection({modelRegistry:registry});
  const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const providers=await (await fetch(`${base}/api/models/providers`)).json();assert.equal(providers[0].auth.type,'bearer-env');assert.equal('env' in providers[0].auth,false);assert.equal(JSON.stringify(providers).includes('SECRET_ENV_NAME'),false);
  const models=await (await fetch(`${base}/api/models`)).json();assert.equal(models[0].providerModel,'vendor/fast');assert.equal(models[0].qualification.state,'QUALIFIED');
  const routed=await fetch(`${base}/api/models/fast/route`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer test-token'},body:JSON.stringify({nodeId:'worker',requiredCapabilities:['coding']})});assert.equal(routed.status,200);assert.equal((await routed.json()).qualificationVersion,'q1');
});

test('cost routing API is authenticated and explain performs no inference',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-cost-routing-web-')),configFile=path.join(root,'config.json');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.writeFileSync(configFile,JSON.stringify({schemaVersion:1,resources:[],providers:[{id:'openrouter',kind:'openai-compatible',baseUrl:'https://openrouter.ai/api/v1',wireApi:'chat-completions',capabilities:[]}],models:[{id:'model',provider:'openrouter',providerModel:'vendor/model',capabilities:[],pricing:{currency:'USD',inputPerMillionTokens:.2,outputPerMillionTokens:.4,effectiveFrom:'2026-09-20',source:'fixture'}}],modelRouting:{roles:{}},services:[],lanes:[]}));const control=service(),server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard'),configFile});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;assert.equal((await unauthenticatedFetch(base+'/api/routing/cost-performance')).status,401);const headers={'Content-Type':'application/json',Authorization:'Bearer test-token'},projection=await(await fetch(base+'/api/routing/cost-performance',{headers})).json();assert.equal(projection.controls.rateCeilings,'USD_PER_MILLION_TOKENS');const explained=await fetch(base+'/api/routing/cost-performance/explain',{method:'POST',headers,body:JSON.stringify({strategy:'fast-capped',providerId:'openrouter',modelId:'model',inputTokensEstimated:1000,outputTokensRequested:100})});assert.equal(explained.status,200);const body=await explained.json();assert.equal(body.externalRequestMade,false);assert.equal(body.decision,'PROCEED');assert.deepEqual(body.translation.request.provider.max_price,{prompt:1,completion:2});});

test('dashboard cost policy save uses exact preview and retains raised-authority approval',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-cost-policy-save-')),configFile=path.join(root,'config.json'),ledger=new CostRoutingLedger(path.join(root,'routing.jsonl'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const policy=(input:number,output:number)=>({schema:'agent-control.cost-performance-routing-policy/v1',id:'estate-policy',strategy:'custom',optimization:'price',rateCeilingUsdPerMillionTokens:{input,output},budget:{invocationUsd:.1,jobUsd:2},tokenCeiling:{output:500},fallback:{enabled:true,onNoEligibleRoute:'block',crossModel:false}});fs.writeFileSync(configFile,JSON.stringify({schemaVersion:1,resources:[],providers:[],models:[],modelRouting:{roles:{}},services:[],lanes:[],costPerformanceRouting:{estate:policy(1,2)}}));const control=service(),server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard'),configFile,costRoutingLedger:ledger});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`,headers={'Content-Type':'application/json',Authorization:'Bearer test-token'},configuration=await(await fetch(base+'/api/configuration',{headers})).json(),proposed=policy(2,4),previewResponse=await fetch(base+'/api/configuration/cost-performance-routing/preview',{method:'POST',headers,body:JSON.stringify({revision:configuration.revision,policy:proposed})}),preview=await previewResponse.json();assert.equal(previewResponse.status,200);assert.equal(preview.requiresApproval,true);const denied=await fetch(base+'/api/configuration/cost-performance-routing',{method:'POST',headers,body:JSON.stringify({revision:preview.revision,policy:proposed,proposalSha256:preview.proposalSha256})});assert.equal(denied.status,403);const applied=await fetch(base+'/api/configuration/cost-performance-routing',{method:'POST',headers,body:JSON.stringify({revision:preview.revision,policy:proposed,proposalSha256:preview.proposalSha256,approvalReason:'Approved exact higher ceilings for a bounded workload'})}),result=await applied.json();assert.equal(applied.status,200);assert.equal(result.approval.approver,'web-operator');assert.equal(JSON.parse(fs.readFileSync(configFile,'utf8')).costPerformanceRouting.estate.rateCeilingUsdPerMillionTokens.output,4);assert.equal(ledger.list().length,1);assert.equal(ledger.list()[0]?.kind,'OVERRIDE');assert.equal(JSON.stringify(ledger.list()).includes('Approved exact higher ceilings'),true);});

test('provider catalogue API, dashboard and SSE expose governed state without credential material', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-control-web-provider-catalog-')), credential = ['nvapi', 'fixture', 'L'.repeat(24)].join('-'), environment: NodeJS.ProcessEnv = {AGENT_CONTROL_STATE_DIR: root};
  t.after(() => fs.rmSync(root, {recursive: true, force: true}));
  const provider = {id: 'nvidia-hosted', name: 'NVIDIA hosted models', kind: 'openai-compatible' as const, adapter: 'nvidia-hosted-v1', baseUrl: 'https://integrate.api.nvidia.com/v1', wireApi: 'chat-completions' as const, enabled: true, auth: {type: 'provider-secure-store' as const, reference: 'provider:nvidia-hosted'}, discovery: {enabled: true, path: 'models'}, requiresAuth: true};
  new SecureProviderCredentialStore(path.join(root, 'credentials', 'providers')).set('provider:nvidia-hosted', credential);
  const intelligence = new ModelIntelligenceLedger(path.join(root, 'intelligence.json')), registry = new ModelRegistry([provider], [], {roles: {}}, undefined, undefined, environment, undefined, intelligence);
  const catalogue = new ProviderCatalogRuntime([provider], new ProviderCatalogStore(path.join(root, 'catalogue.json')), registry, intelligence, undefined, environment, async (_input, init) => {
    assert.equal(new Headers(init?.headers).get('authorization'), `Bearer ${credential}`);
    if ((init?.method ?? 'GET') === 'POST') return new Response(['data: {"choices":[{"delta":{"content":"AC_CALLABILITY_OK"},"finish_reason":null}]}','data: {"choices":[{"delta":{},"finish_reason":"stop"}]}','data: [DONE]'].join('\n\n'), {status: 200, headers: {'content-type':'text/event-stream'}});
    return new Response(JSON.stringify({data: [{id: 'vendor/model-a', owned_by: credential}]}), {status: 200, headers: {'x-ratelimit-limit-requests': '40', 'x-ratelimit-remaining-requests': '39', 'x-ratelimit-limit-tokens': '10000', 'x-ratelimit-remaining-tokens': '9900', 'x-quota-remaining': '12'}});
  });
  const control = service(); control.configureProjection({modelRegistry: registry, modelIntelligence: intelligence, providerCatalog: catalogue});
  const server = startWebDashboard(control, {host: '127.0.0.1', port: 0, operatorToken: 'test-token', assetsDir: path.resolve('assets/dashboard')});
  await once(server, 'listening'); t.after(() => server.close()); const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;

  const before = await (await fetch(`${base}/api/provider-catalog`)).json();
  assert.equal(before.providers[0].credentialStatus, 'CONFIGURED');
  assert.equal(before.providers[0].credentialReference, 'secure-store');
  assert.equal(JSON.stringify(before).includes(credential), false);
  const denied = await fetch(`${base}/api/provider-catalog/providers/nvidia-hosted/discover`, {method: 'POST', headers: {'content-type': 'application/json'}, body: '{}'});
  assert.equal(denied.status, 401);
  const discovered = await fetch(`${base}/api/provider-catalog/providers/nvidia-hosted/discover`, {method: 'POST', headers: {'content-type': 'application/json', authorization: 'Bearer test-token'}, body: '{}'});
  assert.equal(discovered.status, 200);
  const discovery = await discovered.json(); assert.equal(discovery.discovered, 1); assert.equal(JSON.stringify(discovery).includes(credential), false);
  const callability = await fetch(`${base}/api/provider-catalog/providers/nvidia-hosted/models/${encodeURIComponent('vendor/model-a')}/callability`, {method: 'POST', headers: {'content-type':'application/json', authorization:'Bearer test-token'}, body:'{}'}); assert.equal(callability.status,200); assert.equal((await callability.json()).inferenceEndpointStatus,'CONFIRMED');
  const invalidAdjudication = await fetch(`${base}/api/provider-catalog/providers/nvidia-hosted/models/${encodeURIComponent('vendor/model-a')}/adjudications`, {method:'POST',headers:{'content-type':'application/json',authorization:'Bearer test-token'},body:JSON.stringify({evidenceKind:'CAPABILITY_SMOKE',evidenceReference:'legacy:v2',attribution:'UNSUPPORTED_CLASS',scoreDisposition:'EXCLUDE',reason:'invalid taxonomy'})}); assert.equal(invalidAdjudication.status,400);
  const adjudicated = await fetch(`${base}/api/provider-catalog/providers/nvidia-hosted/models/${encodeURIComponent('vendor/model-a')}/adjudications`, {method:'POST',headers:{'content-type':'application/json',authorization:'Bearer test-token'},body:JSON.stringify({evidenceKind:'CAPABILITY_SMOKE',evidenceReference:'legacy:v2',attribution:'HARNESS_FAILURE',scoreDisposition:'EXCLUDE',reason:'The old output cap invalidated the test.',supersededBy:'smoke:v3',supportingEvidence:['diagnostic:v3']})}); assert.equal(adjudicated.status,201); assert.equal((await adjudicated.json()).attribution,'HARNESS_FAILURE');
  const catalogueEvents=control.events.history().filter(event => event.type === 'provider.catalog_changed');
  assert.deepEqual(catalogueEvents.map(event => (event.payload as {action?: string}).action), ['discovering', 'discovered', 'callability-testing', 'callability-tested', 'evidence-adjudicated']);
  assert.ok(catalogueEvents.every(event => typeof event.payload.narrative === 'string'));
  assert.equal(catalogueEvents.find(event => event.payload.action === 'callability-tested')?.payload.stage,'CONFIRMED');
  assert.match(String(catalogueEvents.at(-1)?.payload.narrative),/HARNESS_FAILURE/);

  const projection = await (await fetch(`${base}/api/provider-catalog`)).json();
  assert.equal(projection.providers[0].enabled, true);
  assert.equal(projection.providers[0].availableModels, 1);
  assert.equal(projection.providers[0].inferenceConfirmedModels, 1);
  assert.equal(projection.models[0].reviewState, 'UNQUALIFIED');
  assert.equal(projection.models[0].inferenceEndpointStatus, 'CONFIRMED');
  assert.equal(projection.models[0].qualificationStage, 'CONFIRMED');
  assert.equal(projection.models[0].routingEligible, false);
  assert.equal(projection.models[0].evidenceAdjudications[0].scoreDisposition,'EXCLUDE');
  assert.match(projection.models[0].latestNarrative,/responded successfully/);
  assert.ok(Array.isArray(projection.tournament.narrative));
  assert.deepEqual({callability:projection.tournament.requestAccounting.callabilityRequests,capability:projection.tournament.requestAccounting.capabilityRequests,benchmark:projection.tournament.requestAccounting.benchmarkRequests,total:projection.tournament.requestAccounting.totalRequests},{callability:1,capability:0,benchmark:0,total:1});
  assert.deepEqual(projection.tournament.requestAccounting.providerReportedTokens,{inputKnown:0,outputKnown:0,totalKnown:0,requestsWithCompleteUsage:0,requestCoverage:1,complete:false,total:null});
  assert.deepEqual(projection.providers[0].rateLimit, {requestsLimit: 40, requestsRemaining: 39, tokensLimit: 10000, tokensRemaining: 9900, reset: null, retryAfter: null, authority: 'PROVIDER_HEADER'});
  assert.deepEqual(projection.providers[0].quota, {value: 12, unit: 'provider-defined', authority: 'PROVIDER_REPORTED'});
  assert.equal(JSON.stringify(projection).includes(credential), false);
  const abort = new AbortController(), response = await fetch(`${base}/api/events`, {headers: {'last-event-id': '0'}, signal: abort.signal}), reader = response.body!.getReader(), chunk = await reader.read(), events = new TextDecoder().decode(chunk.value); abort.abort();
  assert.match(events, /event: provider\.catalog_changed/);
  assert.equal(events.includes(credential), false);
  const dashboard = await (await fetch(`${base}/dashboard-models.js`)).text();
  assert.match(dashboard, /Discover Models/);
  assert.match(dashboard, /Check Callability/);
  assert.match(dashboard, /requestsRemaining/);
  assert.match(dashboard, /available\/observed · inference confirmed/);
  assert.match(dashboard, /UNAVAILABLE/);
  assert.match(dashboard, /Measured tournament leadership/);
  assert.match(dashboard, /Deterministic tournament narrative/);
  assert.match(dashboard, /Benchmark efficiency telemetry/);
  assert.equal(dashboard.includes(credential), false);
  for (const file of [path.join(root, 'catalogue.json'), path.join(root, 'intelligence.json')]) if (fs.existsSync(file)) assert.equal(fs.readFileSync(file, 'utf8').includes(credential), false);
});
test('account-aware model APIs expose labels, plan and qualification without credential locations', async t => {
  const account={id:'lawrence-pro',label:'Lawrence Pro',plan:'ChatGPT Pro',planAuthority:'operator-configured' as const,credentialStore:{type:'codex-home-env' as const,env:'CODEX_HOME_LAWRENCE_PRO'},qualification:{state:'QUALIFIED' as const,version:'account-q1',checkedAt:'2026-09-02T00:00:00Z',qualifiedAt:'2026-09-02T00:00:00Z',capabilities:['codex-chatgpt'],evidence:['interactive-login']}};
  const registry=new ModelRegistry([{id:'codex',name:'OpenAI Codex',kind:'cli',accountProfiles:[account]}],[{id:'sol-pro',provider:'codex',accountProfile:'lawrence-pro',providerModel:'sol',capabilities:['coding'],qualification:{state:'QUALIFIED',version:'model-q1',capabilities:['coding'],nodes:['controller']}}],{roles:{review:{primary:'sol-pro'}}},undefined,undefined,{CODEX_HOME_LAWRENCE_PRO:process.cwd()}),control=service();control.configureProjection({modelRegistry:registry});
  const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const accounts=await(await fetch(`${base}/api/models/accounts`)).json(),models=await(await fetch(`${base}/api/models`)).json(),providers=await(await fetch(`${base}/api/models/providers`)).json();
  assert.deepEqual({id:accounts[0].id,label:accounts[0].label,plan:accounts[0].plan,availability:accounts[0].availability},{id:'lawrence-pro',label:'Lawrence Pro',plan:'ChatGPT Pro',availability:'AVAILABLE'});
  assert.equal(models[0].account.id,'lawrence-pro');assert.equal(providers[0].accountProfiles[0].qualification.state,'QUALIFIED');
  const serialized=JSON.stringify({accounts,models,providers});assert.equal(serialized.includes('CODEX_HOME_LAWRENCE_PRO'),false);assert.equal(serialized.includes(process.cwd()),false);assert.equal(serialized.includes('@'),false);
  const dashboard=await(await fetch(`${base}/dashboard-models.js`)).text();assert.match(dashboard,/Account qualification/);assert.match(dashboard,/not reliably known/);assert.match(dashboard,/models\/accounts/);
});
test('unauthenticated natural-language submission creates no parcel', async t => { const {server,base,control}=await runningParcels('test-token'); t.after(()=>server.close()); const response=await fetch(`${base}/api/parcels`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:'run web-job without authority'})}); assert.equal(response.status,401); assert.equal((await response.json()).error,'operator_authentication_required'); assert.deepEqual(control.parcels(),[]); });
test('authenticated natural-language submission immediately returns an attributed auditable PLANNING parcel and preserves prompt verbatim', async t => { const {server,base}=await runningParcels('test-token'); t.after(()=>server.close()); const prompt='  run web-job and preserve these spaces  '; const response=await fetch(`${base}/api/parcels`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer test-token'},body:JSON.stringify({prompt,actor:'spoofed-actor'})}); assert.equal(response.status,201); const parcel=await response.json(); assert.equal(parcel.status,'PLANNING'); assert.equal(parcel.prompt,prompt); assert.equal(parcel.actor,'web-operator'); assert.equal(parcel.attribution.legacy,true); assert.equal(parcel.attribution.parcelId,parcel.id); assert.equal(parcel.audit.timeline[0].type,'task.received'); });
test('maximumOutputTokens schema survives API redaction and dashboard auth controls use validated state', async t => { const {server,base}=await runningJobs(); t.after(()=>server.close()); const jobs=await (await fetch(`${base}/api/jobs`)).json(); assert.deepEqual(jobs[0].spec.parameters.maximumOutputTokens,{type:'integer',default:32768}); const source=await (await fetch(`${base}/dashboard.js`)).text(), html=await (await fetch(base)).text(); assert.match(source,/operatorAuthentication/); assert.match(source,/Operator authentication required/); assert.match(html,/natural-task-submit[^>]+disabled/); assert.match(html,/Systems/); });
test('governed Check now updates canonical provider readiness', async t => { const upstream=http.createServer((_request,response)=>{response.writeHead(200);response.end('ok')}); upstream.listen(0,'127.0.0.1'); await once(upstream,'listening'); t.after(()=>upstream.close()); const upstreamPort=(upstream.address() as AddressInfo).port, baseControl=service(), providers=new ProviderRegistry(); providers.register({id:'provider-check',name:'Provider Check',kind:'responses',baseUrl:`http://127.0.0.1:${upstreamPort}/v1`,requiresAuth:false,credentialConfigured:true,parallelism:1,costClass:'included',capabilities:['model.execute'],qualification:{status:'qualified'}}); const control=new AgentControlService(baseControl.state,baseControl.ptys,providers,'3.3.1-test',()=>{}), server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')}); await once(server,'listening'); t.after(()=>server.close()); const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`; assert.equal((await (await fetch(`${base}/api/systems`)).json())[0].execution,'UNKNOWN'); const checked=await fetch(`${base}/api/systems/provider-check/check`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer test-token'},body:'{}'}); assert.equal(checked.status,200); const system=await checked.json(); assert.equal(system.execution,'AVAILABLE'); assert.equal(system.reachable,'yes'); assert.ok(system.lastSuccessfulProbeAt); });
test('approval is a typed control event and cannot approve a policy that is not waiting', async t => { const {server, base, control, runtime} = await runningJobs('test-token'); t.after(() => server.close()); const createdResponse = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: '{}'}), created = await createdResponse.json(); await runtime.tick(); assert.equal(runtime.ledger.get(created.id)?.steps[0].status, 'WAITING_FOR_APPROVAL'); const wrong = await fetch(`${base}/api/runs/${created.id}/approve`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({policy: 'different'})}); assert.equal(wrong.status, 409); assert.equal((await wrong.json()).error, 'approval_policy_not_waiting'); assert.equal(runtime.ledger.get(created.id)?.approvals.length, 0); const approved = await fetch(`${base}/api/runs/${created.id}/approve`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({policy: 'release', actor: 'reviewer'})}); assert.equal(approved.status, 200); assert.deepEqual(runtime.ledger.get(created.id)?.approvals, ['release']); assert.equal(control.events.history().at(-1)?.type, 'job.run_approved'); });

test('token-aware metrics are readable while expansion remains authenticated and scope-bound', async t => {
  const control = service(), output = new TokenAwareOutputService(new MemoryCommandResultStore(), {policy: {completeMaxLines: 0}, now: () => new Date('2026-08-27T10:00:00.000Z'), handleFactory: () => 'output:WEB'});
  const scope: OutputAuthorityScope = {taskId: 'web-task', laneId: '1', workerId: 'worker', leaseGeneration: 1, ownershipGeneration: 1};
  const captured = output.capture({schema: COMMAND_RESULT_SCHEMA, command: 'build', args: [], cwd: '/workspace', stdout: Array.from({length: 1000}, (_, index) => `line ${index} ${'x'.repeat(80)}`).join('\n'), stderr: '', exitCode: 0, startedAt: '2026-08-27T10:00:00.000Z', completedAt: '2026-08-27T10:00:01.000Z', backend: 'local'}, scope);
  control.configureProjection({tokenAwareOutput: output});
  const server = startWebDashboard(control, {host: '127.0.0.1', port: 0, operatorToken: 'test-token', assetsDir: path.resolve('assets/dashboard')});
  await once(server, 'listening'); t.after(() => server.close()); const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const metrics = await (await fetch(`${base}/api/command-output/metrics`)).json(); assert.equal(metrics.commandsCompacted, 1); assert.ok(metrics.contextTokensAvoided > 0);
  const records = await (await fetch(`${base}/api/command-output`)).json(); assert.equal(records[0].handle, captured.handle); assert.equal('storageRef' in records[0], false);
  const denied = await fetch(`${base}/api/command-output/${encodeURIComponent(captured.handle)}/expand`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: '{}'}); assert.equal(denied.status, 401);
  const allowed = await fetch(`${base}/api/command-output/${encodeURIComponent(captured.handle)}/expand`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({scope, expansion: {mode: 'all'}})}); assert.equal(allowed.status, 200); assert.equal((await allowed.json()).disposition, 'COMPLETE');
});

test('harness efficiency metrics and redacted invocation telemetry are projected read-only', async t => {
  const control = service(), ledger = new MemoryHarnessEfficiencyLedger();
  const item = createInvocationObservation({id: 'inv-web', jobId: 'job-web', runId: 'run-web', taskId: 'task-web', laneId: '1', model: 'model-a', provider: 'provider-a', harnessProfile: 'THIN', executionStrategy: 'fixture', startedAt: '2026-08-27T10:00:00.000Z', completedAt: '2026-08-27T10:00:01.000Z', rawUsage: {input_tokens: 100, input_tokens_details: {cached_tokens: 75}, output_tokens: 20, total_tokens: 120}, cacheEvidence: {reusedTokens: 75, processedPromptTokens: 25, cacheWriteTokens: null, promptProcessingMs: 12, generationMs: 34, authority: 'authoritative', source: 'llama.cpp.timings', requestPrefixSha256: 'abc123'}, recipeFingerprint: 'recipe-web'});
  ledger.record(item); ledger.markVerification([item.id], 'PASS', 'SUCCEEDED'); control.configureProjection({harnessEfficiency: ledger});
  const server = startWebDashboard(control, {host: '127.0.0.1', port: 0, operatorToken: 'test-token', assetsDir: path.resolve('assets/dashboard')}); await once(server, 'listening'); t.after(() => server.close()); const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const metrics = await (await fetch(`${base}/api/efficiency`)).json(); assert.equal(metrics.overall.verifiedSuccesses, 1); assert.equal(metrics.overall.cachedInputTokens, 75);
  const invocations = await (await fetch(`${base}/api/efficiency/invocations`)).json(); assert.equal(invocations[0].usage.freshInputTokens, 25); assert.equal(invocations[0].harnessProfile, 'THIN'); assert.equal(typeof invocations[0].startup.components[0].estimatedTokens, 'number'); assert.equal(invocations[0].cacheEvidence.reusedTokens, 75); assert.equal(invocations[0].cacheEvidence.processedPromptTokens, 25);
  assert.equal((await (await fetch(`${base}/api/efficiency/invocations?limit=1&runId=run-web`)).json()).length, 1);
  const html = await (await fetch(base)).text(); assert.match(html, /Harness Efficiency/);
});

test('governed run cards route from Lanes to the authoritative Jobs detail', () => {
  const source=fs.readFileSync(path.resolve('assets/dashboard/dashboard-enhancements.js'),'utf8');
  assert.match(source,/data-view="jobs"/);
  assert.match(source,/Last provider \/ control signal/);
  assert.match(source,/phaseUpdatedAt/);
  assert.match(source,/Unavailable \(mixed currencies\)/);
  assert.match(source,/response received/);
  assert.match(source,/Runtime budget/);assert.match(source,/Job \/ model \/ tool deadlines/);assert.match(source,/Progress \/ reserves \/ terminal/);
});

test('dashboard exposes an operator configuration view with API-key references and restart semantics', () => {
  const html=fs.readFileSync(path.resolve('assets/dashboard/index.html'),'utf8'),source=fs.readFileSync(path.resolve('assets/dashboard/dashboard-enhancements.js'),'utf8');
  assert.match(html,/data-view="configuration">Configuration/);assert.match(html,/Add machine/);assert.match(html,/Fast execution/);assert.match(html,/credentialEnv/);assert.match(source,/\/api\/configuration\/systems/);assert.match(source,/\/api\/configuration\/spark/);assert.match(source,/RESTART REQUIRED/);
});

test('dashboard renders workload provider-execution and credential-residency locality separately', () => {
  const models=fs.readFileSync(path.resolve('assets/dashboard/dashboard-models.js'),'utf8'),runs=fs.readFileSync(path.resolve('assets/dashboard/dashboard-parameterized-jobs.js'),'utf8'),tokens=fs.readFileSync(path.resolve('assets/dashboard/dashboard-enhancements.js'),'utf8');
  for (const source of [models,runs,tokens]) assert.match(source,/providerExecutionNodeId/);
  for (const source of [models,runs,tokens]) assert.match(source,/credentialNodeId/);
  assert.match(runs,/workloadNodeId/); assert.match(tokens,/workloadNodeId/);
});

test('Sessions dashboard reads authoritative identity execution and 3.6 runtime provenance', async t => {
  const control=service(),identity=new IdentityControlPlane();identity.registerActor({id:'web-operator',type:'human',displayName:'Web operator',principalId:'operator:web',authenticationSource:'dashboard-bearer',roles:['operator'],capabilities:[],metadata:{}});identity.createSession({id:'session:web',creatorActorId:'web-operator',mode:'operator-controlled',permissions:{capabilities:['session.observe','session.manage','parcel.create'],filesystem:'none',network:'none'},contextPolicy:'compiled'});control.configureProjection({identity,defaultSessionId:'session:web'});
  const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const sessions=await(await fetch(`${base}/api/sessions`)).json();assert.equal(sessions[0].creatorActorId,'web-operator');assert.deepEqual(await(await fetch(`${base}/api/context-transfers`)).json(),[]);assert.deepEqual(await(await fetch(`${base}/api/delegations`)).json(),[]);assert.deepEqual(await(await fetch(`${base}/api/executions`)).json(),[]);assert.deepEqual(await(await fetch(`${base}/api/fast-execution-attempts`)).json(),[]);assert.equal((await(await fetch(`${base}/api/runtime`)).json()).schema,'agent-control.runtime-observability/v1');const html=await(await fetch(base)).text(),source=await(await fetch(`${base}/dashboard-sessions.js`)).text();assert.match(html,/data-view="sessions">Sessions/);assert.match(source,/Actor → Session → Work Parcel → Agent → Model → Provider → Runtime → Node\/Resource → Evidence/);assert.match(source,/Context transfers/);assert.match(source,/Active parcels/);assert.match(source,/Execution class \/ actual model \/ verification \/ escalation/);assert.match(source,/Contract-owned execution/);assert.match(source,/Transport \/ connection \/ authentication/);
});

test('parcel context APIs expose asynchronous questions, steering, retrieval and first-class criteria through authenticated controls', async t => {
  const {server,base,workParcels,control}=await runningParcels('test-token');t.after(()=>server.close());const parcel=await workParcels.submit('preserve this exact goal','operator'),headers={'Content-Type':'application/json',Authorization:'Bearer test-token'};
  const asked=await fetch(`${base}/api/parcels/${parcel.id}/questions`,{method:'POST',headers,body:JSON.stringify({text:'Which format?',dependentStageIds:['inspect'],priority:'HIGH',consequence:'MEDIUM'})});assert.equal(asked.status,201);const waiting=await asked.json(),question=waiting.context.questions[0];assert.equal(waiting.status,'WAITING');assert.equal(waiting.context.active.originalGoal,'preserve this exact goal');assert.match(waiting.context.active.currentInterpretation,/interpreted:/);
  const answered=await fetch(`${base}/api/parcels/${parcel.id}/questions/${question.id}/answer`,{method:'POST',headers,body:JSON.stringify({answer:'JSON'})});assert.equal(answered.status,200);assert.equal((await answered.json()).context.questions[0].status,'ANSWERED');
  assert.equal((await fetch(`${base}/api/parcels/${parcel.id}/steering`,{method:'POST',headers,body:JSON.stringify({instruction:'Do not deploy',constraints:['read only']})})).status,200);
  const added=await fetch(`${base}/api/parcels/${parcel.id}/criteria`,{method:'POST',headers,body:JSON.stringify({kind:'CUSTOM',description:'Operator checks semantic result'})});assert.equal(added.status,201);const criterion=(await added.json()).criterion;
  const evaluated=await fetch(`${base}/api/parcels/${parcel.id}/criteria/${criterion.id}/evaluate`,{method:'POST',headers,body:JSON.stringify({status:'PASS',evidence:['operator:checked']})});assert.equal(evaluated.status,200);
  const retrieved=await fetch(`${base}/api/parcels/${parcel.id}/context/retrieve`,{method:'POST',headers,body:JSON.stringify({query:'Which format JSON'})});assert.equal(retrieved.status,200);assert.ok((await retrieved.json()).some((item:{type:string})=>item.type==='question.answered'));
  const invalid=await fetch(`${base}/api/parcels/${parcel.id}/criteria`,{method:'POST',headers,body:JSON.stringify({kind:'NOT_A_KIND',description:'invalid'})});assert.equal(invalid.status,400);assert.equal((await invalid.json()).error,'parcel_success_criterion_invalid');
  assert.ok(control.events.history().filter(event=>event.type==='work.parcel_changed').length>=5);
  const source=await(await fetch(`${base}/dashboard-enhancements.js`)).text();for(const marker of ['data-answer-question','data-steer-parcel','data-retrieve-parcel','data-add-criterion','data-evaluate-criterion'])assert.match(source,new RegExp(marker));
});

test('capability and model-intelligence APIs expose durable queue state and emit typed SSE-compatible events', async t => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-web-intelligence-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const capabilities=new CapabilityIntelligenceStore(path.join(root,'capabilities.json'));registerAgentControlCoreCapabilities(capabilities,'2026-09-05T00:00:00Z');const intelligence=new ModelIntelligenceLedger(path.join(root,'models.json')),suite=loadFrozenQualificationSuite(path.resolve('config/qualification-suite-v1.json'));
  const registry=new ModelRegistry([{id:'provider',kind:'openai-compatible',baseUrl:'https://provider.example/v1',auth:{type:'none'}}],[{id:'candidate',provider:'provider',providerModel:'vendor/candidate',capabilities:['code.modify'],nodes:['controller'],qualification:{state:'UNTESTED'}}],{roles:{}},undefined,undefined,{},capabilities,intelligence),control=service();control.configureProjection({modelRegistry:registry,capabilityIntelligence:capabilities,modelIntelligence:intelligence,qualificationSuite:suite});const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`,headers={'Content-Type':'application/json',Authorization:'Bearer test-token'};
  assert.equal((await(await fetch(`${base}/api/capability-intelligence`)).json()).totals.observations>0,true);assert.deepEqual((await(await fetch(`${base}/api/model-intelligence`)).json()).queue,[]);
  const discovered=await fetch(`${base}/api/capability-candidates`,{method:'POST',headers,body:JSON.stringify({id:'candidate-capability',title:'Provider continuation',source:'release notes',providerRuntime:'provider@1',claimedCapability:'context.lifecycle',whyItMatters:'less repetition',agentControlEquivalent:'context lifecycle',evidence:['Bearer abcdefghijklmnopqrstuvwxyz']})});assert.equal(discovered.status,201);assert.doesNotMatch(JSON.stringify(await discovered.json()),/abcdefghijklmnopqrstuvwxyz/);
  const invalidTransition=await fetch(`${base}/api/capability-candidates/candidate-capability/transition`,{method:'POST',headers,body:JSON.stringify({to:'ADOPTED',reason:'skip',finalDecision:'adopt'})});assert.equal(invalidTransition.status,409);assert.equal((await invalidTransition.json()).error,'capability_candidate_transition_invalid:DISCOVERED:ADOPTED');
  const queued=await fetch(`${base}/api/model-evaluations`,{method:'POST',headers,body:JSON.stringify({modelIds:['candidate'],reason:'operator qualification'})});assert.equal(queued.status,201);const batch=await queued.json();assert.equal(batch.status,'QUEUED');assert.equal(batch.suiteSha256,suite.sha256);assert.equal((await(await fetch(`${base}/api/model-intelligence`)).json()).queue[0].id,batch.id);
  assert.ok(control.events.history().some(event=>event.type==='capability.intelligence_changed'));assert.ok(control.events.history().some(event=>event.type==='model.intelligence_changed'));
  const html=await(await fetch(base)).text(),models=await(await fetch(`${base}/dashboard-models.js`)).text();assert.match(html,/Model intelligence/);assert.match(html,/Capability Watch/);assert.match(html,/Runtime Safety/);assert.match(models,/Frozen evaluation queue/);assert.match(models,/Regression warnings/);assert.match(models,/Best current coding model/);assert.match(models,/data-route-transition/);assert.match(models,/model-intelligence\/routes/);
});

test('unconfigured intelligence endpoints fail explicitly instead of returning internal errors',async t=>{const{server,base}=await running();t.after(()=>server.close());for(const endpoint of ['capability-intelligence','model-intelligence','runtime-safety']){const response=await fetch(`${base}/api/${endpoint}`);assert.equal(response.status,503,endpoint);assert.match((await response.json()).error,/unconfigured/);}});

test('Social and Voice history and approval routes require authentication and same origin',async t=>{
 const {server,base}=await running('test-token');t.after(()=>server.close());
 for(const route of ['/api/social-voice','/api/social-voice/transcript']){
  assert.equal((await unauthenticatedFetch(base+route)).status,401);
  assert.equal((await fetch(base+route,{headers:{Authorization:'Bearer test-token'}})).status,200);
 }
 for(const route of ['/api/social-voice/summary','/api/social-voice/approval','/api/social-voice/approval-grant']){
  assert.equal((await fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,401);
  assert.equal((await fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer test-token',Origin:'https://evil.invalid'},body:'{}'})).status,403);
 }
 assert.equal((await fetch(base+'/social-voice.html')).status,200);
 assert.equal((await fetch(base+'/dashboard-social-voice.js')).status,200);
});

test('usage HTTP projection preserves token metric shape and serves real dashboard assets',async t=>{const control=service(),ledger=new MemoryHarnessEfficiencyLedger();const at=new Date().toISOString();ledger.record(createInvocationObservation({id:'http-usage',jobId:'job',taskId:'task',laneId:'lane',model:'model',provider:'provider',harnessProfile:'STANDARD',executionStrategy:'test',startedAt:at,completedAt:at,recipeFingerprint:'test',rawUsage:{input_tokens:10,output_tokens:2,total_tokens:12}}));control.configureProjection({harnessEfficiency:ledger});const operatorToken='isolated-usage-http-test';const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken,assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;const headers={Authorization:`Bearer ${operatorToken}`};t.after(()=>server.close());const p=await(await fetch(base+'/api/usage?period=all',{headers})).json();assert.equal(p.totals.tokens.knownTotal,12);assert.equal((await fetch(base+'/dashboard-usage.js')).status,200);assert.equal((await fetch(base+'/dashboard-usage.css')).status,200);assert.equal((await fetch(base+'/api/usage?filter.secret=x',{headers})).status,400);});

test('PWA serves a static offline shell and protects deployment observations',async()=>{
 const {server,base}=await running('pwa-test-operator');
 try{
  const manifest=await fetch(base+'/manifest.webmanifest');assert.equal(manifest.status,200);assert.match(manifest.headers.get('content-type')??'',/application\/manifest\+json/);const body=await manifest.json() as any;assert.equal(body.display,'standalone');assert.equal(body.start_url,'/');
  const offline=await fetch(base+'/offline.html');assert.match(await offline.text(),/cannot execute jobs or report live status/);
  assert.equal((await unauthenticatedFetch(base+'/api/deployment')).status,401);
  const deployment=await fetch(base+'/api/deployment',{headers:{Authorization:'Bearer pwa-test-operator'}});assert.equal(deployment.status,200);assert.equal((await deployment.json() as any).profile,'STANDARD');
  assert.equal((await fetch(base+'/android-operator-token')).status,404);
 }finally{server.close();}
});

test('saved-job input budgets remain numeric without exposing credential tokens',async t=>{
  const control=service();(control as unknown as {jobDefinitions:()=>unknown[]}).jobDefinitions=()=>[{budgets:{maximumInputTokens:120000,maximumOutputTokens:8192},credentialToken:'must-not-leak'}];
  const{server,base}=await runningWithControl(control);t.after(()=>server.close());
  const[value]=await(await fetch(`${base}/api/job-definitions`)).json();
  assert.equal(value.budgets.maximumInputTokens,120000);assert.equal(value.budgets.maximumOutputTokens,8192);assert.equal(value.credentialToken,'[REDACTED]');
});

test('same-run resume API requires mutation authority and preserves protected step approval',async()=>{
 const {control,runtime}=serviceWithJobs();runtime.registerResumePolicy('test.run@1.0.0',()=>({complete:false,checkpoint:{synthetic:true}}));
 const run=runtime.createRun('web-job@1.0.0',{}, {type:'manual',actor:'operator'});run.status='SUCCEEDED';run.steps[0].status='SUCCEEDED';run.approvals=['release'];runtime.ledger.update(run);
 const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`,url=base+'/api/runs/'+run.id+'/resume';
 try{
  const data={requestKey:'api-resume',expiresAt:new Date(Date.now()+60000).toISOString()};
  assert.equal((await unauthenticatedFetch(url)).status,401);
  assert.equal((await unauthenticatedFetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})).status,401);
  assert.equal((await fetch(url)).status,200);
  const r=await fetch(url,{method:'POST',headers:{Authorization:'Bearer test-token','Content-Type':'application/json'},body:JSON.stringify(data)});assert.equal(r.status,200);assert.equal((await r.json()).id,run.id);
  await runtime.tick();assert.equal(runtime.ledger.get(run.id)!.steps[0].status,'WAITING_FOR_APPROVAL');assert.equal(runtime.ledger.list().length,1);
 }finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}
});

test('cleanup verification requires authenticated mutation and never creates a run or dispatch',async()=>{
 const {control,runtime}=serviceWithJobs();let checks=0;runtime.registerCleanupVerifier('test.run@1.0.0',async()=>{checks++;return false;});const run=runtime.createRun('web-job@1.0.0',{}, {type:'manual',actor:'operator'});run.status='CLEANUP_UNCERTAIN';run.steps[0].status='CLEANUP_UNCERTAIN';runtime.ledger.update(run);
 const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');const url=`http://127.0.0.1:${(server.address() as AddressInfo).port}/api/runs/${run.id}/verify-cleanup`;
 try{assert.equal((await unauthenticatedFetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,401);assert.equal(checks,0);const result=await fetch(url,{method:'POST',headers:{Authorization:'Bearer test-token','Content-Type':'application/json'},body:'{}'});assert.equal(result.status,200);assert.equal((await result.json()).status,'CLEANUP_UNCERTAIN');assert.equal(checks,1);assert.equal(runtime.ledger.list().length,1);assert.equal(runtime.ledger.get(run.id)!.steps[0].attempts.length,0);}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}
});

test('target reset endpoint requires authentication and explicit reset authority without creating jobs',async()=>{const {control,runtime}=serviceWithJobs();let calls=0;runtime.registerTargetReset('fixture',{state:()=>undefined,reset:async(a:any)=>{if(!a.approveReset)throw Error('target_reset_authority_required');calls++;return {status:'COMPLETE'};}} as any);const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');const url=`http://127.0.0.1:${(server.address() as AddressInfo).port}/api/targets/fixture/reset-recovery`;try{assert.equal((await unauthenticatedFetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,401);assert.equal((await unauthenticatedFetch(url)).status,401);assert.equal(calls,0);const result=await fetch(url,{method:'POST',headers:{Authorization:'Bearer test-token','Content-Type':'application/json'},body:JSON.stringify({approveReset:true,reason:'test',requestKey:'one',expiresAt:new Date(Date.now()+60000).toISOString()})});assert.equal(result.status,200);assert.equal(calls,1);assert.equal(runtime.ledger.list().length,0);}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}});

test('target environment diagnostic requires authentication and creates no jobs',async()=>{const {control,runtime}=serviceWithJobs();let calls=0;runtime.registerTargetReset('fixture',{state:()=>undefined,diagnose:async()=>{calls++;return {status:'PASS'};}} as any);const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');const url=`http://127.0.0.1:${(server.address() as AddressInfo).port}/api/targets/fixture/environment-diagnostic`;try{assert.equal((await unauthenticatedFetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,401);assert.equal((await unauthenticatedFetch(url)).status,401);assert.equal(calls,0);const result=await fetch(url,{method:'POST',headers:{Authorization:'Bearer test-token','Content-Type':'application/json'},body:JSON.stringify({approveReset:true,reason:'test',requestKey:'one',expiresAt:new Date(Date.now()+60000).toISOString()})});assert.equal(result.status,200);assert.equal(calls,1);assert.equal(runtime.ledger.list().length,0);}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}});

test('target continuation preparation is authenticated and cannot dispatch or create jobs',async()=>{const {control,runtime}=serviceWithJobs();let calls=0;runtime.registerTargetReset('fixture',{state:()=>undefined,prepareContinuation:async()=>{calls++;return {status:'PASS'};}} as any);const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');const url=`http://127.0.0.1:${(server.address() as AddressInfo).port}/api/targets/fixture/reset-continuations`;try{assert.equal((await unauthenticatedFetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,401);assert.equal((await unauthenticatedFetch(url)).status,401);assert.equal(calls,0);const result=await fetch(url,{method:'POST',headers:{Authorization:'Bearer test-token','Content-Type':'application/json'},body:JSON.stringify({approveReset:true,reason:'test',requestKey:'one',expiresAt:new Date(Date.now()+60000).toISOString()})});assert.equal(result.status,200);assert.equal(calls,1);assert.equal(runtime.ledger.list().length,0);}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}});

test('Shared Speech stream preserves operator authentication and origin boundary',async t=>{const {control,server,base}=await running();t.after(()=>server.close());let invoked=0;(control as any).poeConversation=()=>({actorId:'web-operator'});(control as any).sharedSpeakPoe=async function*(){invoked++;yield{type:'speech.finished',turnId:'t',provider:'fixture'};};const url=base+'/api/poe/conversations/c/speech-stream';const body=JSON.stringify({turnId:'t'});assert.equal((await unauthenticatedFetch(url,{method:'POST',headers:{'content-type':'application/json'},body})).status,401);assert.equal((await unauthenticatedFetch(url,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer test-token',origin:'https://evil.invalid'},body})).status,403);assert.equal(invoked,0);const response=await unauthenticatedFetch(url,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer test-token'},body});assert.equal(response.status,200);assert.match(response.headers.get('content-type')??'',/text\/event-stream/);assert.match(await response.text(),/speech.finished/);assert.equal(invoked,1);});
