import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {schedulerContainmentScopes,WorkBoardRuntime,type BoardOperation,type CreateWorkItemInput,type SchedulerResource} from './work-board.js';
import {ContainmentSupervisor} from './containment.js';

const at='2026-09-19T12:00:00.000Z';
function setup(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-board-')),file=path.join(root,'boards.json'),runtime=new WorkBoardRuntime(file,()=>at),board=runtime.create({id:'release',title:'4.9 release',workspace:'agent-control',project:'agent-control',actor:'operator',lanes:[{id:'code',label:'Code',parallelism:1},{id:'test',label:'Testing',parallelism:2},{id:'security',label:'Security',parallelism:1},{id:'docs',label:'Documentation',parallelism:1}]});return{root,file,runtime,board};}
function create(runtime:WorkBoardRuntime,version:number,title:string,extra:Partial<CreateWorkItemInput>={}){return runtime.apply('release',version,{type:'CREATE_ITEM',input:{title,sourceInstruction:`Add ${title}`,creator:'operator',...extra}},'operator',`Add ${title}`);}
const item=(board:ReturnType<WorkBoardRuntime['get']>,title:string)=>board.items.find(value=>value.title===title)!;

test('board persists rich work, order, priority, lane, history and optimistic concurrency',t=>{const s=setup();t.after(()=>fs.rmSync(s.root,{recursive:true,force:true}));let board=create(s.runtime,s.board.version,'Implementation',{laneId:'code',acceptanceCriteria:['tests pass'],requirements:{writableScopes:['/repo/src']}});board=create(s.runtime,board.version,'Documentation',{laneId:'docs',priority:'LOW'});const docs=item(board,'Documentation'),impl=item(board,'Implementation');board=s.runtime.apply(board.id,board.version,{type:'MOVE_ITEM',itemId:docs.id,position:'TOP'},'operator','Put documentation at top');board=s.runtime.apply(board.id,board.version,{type:'SET_PRIORITY',itemId:docs.id,priority:'HIGH'},'operator');assert.equal(item(board,'Documentation').manualOrder,0);assert.equal(item(board,'Documentation').priority,'HIGH');assert.throws(()=>s.runtime.apply(board.id,board.version-1,{type:'ASSIGN_LANE',itemId:impl.id,laneId:'test'},'stale-agent'),/work_board_version_conflict/);const restored=new WorkBoardRuntime(s.file);assert.equal(restored.get('release').items.length,2);assert.ok(restored.get('release').history.some(event=>event.type==='item.move_item'));});

test('dependencies reject cycles and scheduler skips blocked work while selecting safe parallel lanes',t=>{const s=setup();t.after(()=>fs.rmSync(s.root,{recursive:true,force:true}));let board=create(s.runtime,s.board.version,'Implementation',{laneId:'code',priority:'CRITICAL',requirements:{writableScopes:['/repo']}});board=create(s.runtime,board.version,'Tests',{laneId:'test',priority:'HIGH',requirements:{writableScopes:['/repo']}});board=create(s.runtime,board.version,'Security',{laneId:'security',priority:'HIGH',requirements:{capabilities:['security.scan']}});board=create(s.runtime,board.version,'Documentation',{laneId:'docs',priority:'NORMAL',requirements:{writableScopes:['/docs']}});const implementation=item(board,'Implementation'),tests=item(board,'Tests'),security=item(board,'Security'),docs=item(board,'Documentation');for(const value of board.items)board=s.runtime.apply(board.id,board.version,{type:'SET_STATE',itemId:value.id,state:'QUEUED',reason:'triaged'},'operator');board=s.runtime.apply(board.id,board.version,{type:'ADD_DEPENDENCY',itemId:tests.id,dependency:{itemId:implementation.id,kind:'FINISH_TO_START'}},'operator');assert.throws(()=>s.runtime.apply(board.id,board.version,{type:'ADD_DEPENDENCY',itemId:implementation.id,dependency:{itemId:tests.id,kind:'FINISH_TO_START'}},'operator'),/work_board_dependency_cycle/);const result=s.runtime.reconcile(board.id,board.version,[{id:'controller',available:true,capabilities:['security.scan'],runtimes:[]}]);assert.ok(result.selected.includes(implementation.id));assert.ok(result.selected.includes(security.id));assert.ok(result.selected.includes(docs.id));assert.ok(!result.selected.includes(tests.id));assert.match(result.decisions.find(value=>value.itemId===tests.id)!.reason,/Dependency/);});

test('resource conflicts, approval and unavailable resource are explicit and missing metrics are not invented',t=>{const s=setup();t.after(()=>fs.rmSync(s.root,{recursive:true,force:true}));let board=create(s.runtime,s.board.version,'GPU benchmark',{priority:'CRITICAL',laneId:'test',requiredApprovals:['benchmark'],requirements:{nodes:['pixel'],runtimes:['llama.cpp'],exclusiveKeys:['device:pixel','gpu:pixel'],minimumRamBytes:8_000_000_000}});board=create(s.runtime,board.version,'Pixel installer',{laneId:'code',requirements:{nodes:['pixel'],exclusiveKeys:['device:pixel']}});for(const value of board.items)board=s.runtime.apply(board.id,board.version,{type:'SET_STATE',itemId:value.id,state:'QUEUED',reason:'ready'},'operator');let result=s.runtime.reconcile(board.id,board.version,[{id:'pixel',available:false,capabilities:[],runtimes:[]}]);assert.ok(result.decisions.every(value=>value.outcome==='BLOCKED'));const benchmark=item(s.runtime.get('release'),'GPU benchmark');board=s.runtime.approve('release',s.runtime.get('release').version,benchmark.id,'benchmark','operator');result=s.runtime.reconcile('release',board.version,[{id:'pixel',available:true,capabilities:[],runtimes:['llama.cpp'],ramBytes:12_000_000_000}]);assert.equal(result.selected.length,1);assert.equal(result.decisions.filter(value=>value.outcome==='DEFERRED').length,1);});

test('interruption policy, supersession, run evidence and restart retain truthful history',t=>{const s=setup();t.after(()=>fs.rmSync(s.root,{recursive:true,force:true}));let board=create(s.runtime,s.board.version,'Atomic install',{interruptionPolicy:'NON_INTERRUPTIBLE_ATOMIC_STEP'});board=create(s.runtime,board.version,'Replacement');const atomic=item(board,'Atomic install'),replacement=item(board,'Replacement');board=s.runtime.apply(board.id,board.version,{type:'SET_STATE',itemId:atomic.id,state:'QUEUED',reason:'ready'},'operator');board=s.runtime.linkRun(board.id,board.version,atomic.id,{runId:'run-1',attempt:1,state:'RUNNING',startedAt:at,evidence:[]});board=s.runtime.apply(board.id,board.version,{type:'SET_STATE',itemId:atomic.id,state:'CANCELLED',reason:'urgent'},'operator');assert.equal(item(board,'Atomic install').state,'PAUSING');board=s.runtime.apply(board.id,board.version,{type:'SUPERSEDE',itemId:replacement.id,replacementId:atomic.id},'operator');assert.equal(item(board,'Replacement').state,'SUPERSEDED');board=s.runtime.completeRun(board.id,board.version,atomic.id,{runId:'run-1',state:'COMPLETED',result:'installed',evidence:['artifact:receipt']});assert.deepEqual(item(board,'Atomic install').evidence,['artifact:receipt']);assert.match(s.runtime.humanReadable(board.id),/Atomic install/);assert.equal(new WorkBoardRuntime(s.file).get(board.id).items.length,2);});

test('natural-language control creates explicit proposals and refuses ambiguous destructive reinterpretation',t=>{const s=setup();t.after(()=>fs.rmSync(s.root,{recursive:true,force:true}));let board=create(s.runtime,s.board.version,'Security review');const security=item(board,'Security review');let proposed=s.runtime.proposal(board.id,'Put that at the top',{actor:'operator',itemId:security.id});assert.equal(proposed.classification,'REPRIORITISATION');assert.equal(proposed.requiresClarification,false);board=s.runtime.applyProposal(board.id,board.version,proposed,'operator');proposed=s.runtime.proposal(board.id,'Pause the benchmark',{actor:'operator'});assert.equal(proposed.requiresClarification,true);assert.equal(proposed.operations.length,0);proposed=s.runtime.proposal(board.id,'What is blocking the release?',{actor:'operator'});assert.equal(proposed.classification,'CONTEXT_ONLY');});

test('machine-readable operation covers dependencies, lane assignment, acceptance criteria, pause resume and cancellation',t=>{const s=setup();t.after(()=>fs.rmSync(s.root,{recursive:true,force:true}));let board=create(s.runtime,s.board.version,'A'),a=item(board,'A');const operations:BoardOperation[]=[{type:'UPDATE_ITEM',itemId:a.id,changes:{acceptanceCriteria:['proof retained']}},{type:'ASSIGN_LANE',itemId:a.id,laneId:'security'},{type:'SET_STATE',itemId:a.id,state:'PAUSED',reason:'operator pause'},{type:'SET_STATE',itemId:a.id,state:'QUEUED',reason:'operator resume'},{type:'REQUEST_APPROVAL',itemId:a.id,approval:'release'}];for(const operation of operations)board=s.runtime.apply(board.id,board.version,operation,'operator');assert.equal(item(board,'A').laneId,'security');assert.deepEqual(item(board,'A').acceptanceCriteria,['proof retained']);assert.equal(item(board,'A').state,'WAITING_FOR_HUMAN');assert.ok(board.history.length>=operations.length+2);});

async function quarantinedBoard(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-board-quarantine-')),containmentFile=path.join(root,'containment.json'),boardFile=path.join(root,'boards.json'),containment=new ContainmentSupervisor(containmentFile,()=>at);containment.register({id:'owner-a',scopes:[{kind:'WORKER',id:'worker-a'}],execution:{activePids:()=>[101],runProcess:async()=>({pid:101,exitCode:0,signal:null,stdout:'',stderr:''}),terminateAll:async reason=>({outcome:'uncertain',reason:reason??'',requestedAt:at,completedAt:at,processes:[]})},exclusive:true});const kill=await containment.kill({kind:'WORKER',id:'worker-a'},'watchdog','qualification quarantine');let current=containment;const authority={evaluate:(resource:SchedulerResource)=>current.schedulingEligibility(schedulerContainmentScopes(resource))},runtime=new WorkBoardRuntime(boardFile,()=>at,authority);let board=runtime.create({id:'release',title:'Quarantine scheduling',workspace:'agent-control',project:'agent-control',actor:'operator',lanes:[{id:'work',label:'Work',parallelism:2}]});return{root,containmentFile,boardFile,containment,current:()=>current,setContainment:(value:ContainmentSupervisor)=>{current=value;},runtime,board,kill};}

test('quarantine beats health priority and route order while an alternative worker is selected',async t=>{const s=await quarantinedBoard();t.after(()=>fs.rmSync(s.root,{recursive:true,force:true}));let board=create(s.runtime,s.board.version,'Priority one',{laneId:'work',priority:'CRITICAL',requirements:{capabilities:['execute']}});board=create(s.runtime,board.version,'Unrelated lower priority',{laneId:'work',priority:'LOW',requirements:{capabilities:['inspect']}});for(const value of board.items)board=s.runtime.apply(board.id,board.version,{type:'SET_STATE',itemId:value.id,state:'QUEUED',reason:'ready'},'operator');const resources:SchedulerResource[]=[{id:'preferred-a',workerId:'worker-a',sessionGeneration:2,available:true,capabilities:['execute'],runtimes:[]},{id:'alternative-b',workerId:'worker-b',available:true,capabilities:['execute'],runtimes:[]},{id:'worker-c',workerId:'worker-c',available:true,capabilities:['inspect'],runtimes:[]}];let result=s.runtime.reconcile(board.id,board.version,resources),decision=result.decisions.find(value=>value.itemId===item(s.runtime.get(board.id),'Priority one').id)!;assert.deepEqual(decision.resources,['alternative-b']);assert.deepEqual(decision.excludedResources?.map(value=>value.id),['preferred-a']);assert.match(decision.reason,/Excluded by containment/);result=s.runtime.reconcile(board.id,result.boardVersion,resources.map(value=>value.id==='alternative-b'?{...value,available:false}:value));decision=result.decisions.find(value=>value.itemId===item(s.runtime.get(board.id),'Priority one').id)!;assert.equal(decision.outcome,'BLOCKED');assert.match(decision.reason,/QUALIFIED WORKER QUARANTINED/);assert.ok(result.selected.includes(item(s.runtime.get(board.id),'Unrelated lower priority').id));assert.equal(item(s.runtime.get(board.id),'Priority one').priority,'CRITICAL');});

test('quarantine survives controller restart and reconnect generation until requalification completes',async t=>{const s=await quarantinedBoard();t.after(()=>fs.rmSync(s.root,{recursive:true,force:true}));let board=create(s.runtime,s.board.version,'Reconnect work',{laneId:'work',priority:'CRITICAL',requirements:{nodes:['node-a'],capabilities:['execute']}}),target=item(board,'Reconnect work');board=s.runtime.apply(board.id,board.version,{type:'SET_STATE',itemId:target.id,state:'QUEUED',reason:'ready'},'operator');const resource:SchedulerResource={id:'route-a',workerId:'worker-a',nodeId:'node-a',sessionGeneration:1,available:true,capabilities:['execute'],runtimes:[]};let result=s.runtime.reconcile(board.id,board.version,[resource]);assert.match(result.decisions[0]!.reason,/QUARANTINED/);const restartedContainment=new ContainmentSupervisor(s.containmentFile,()=>at);s.setContainment(restartedContainment);const restartedBoard=new WorkBoardRuntime(s.boardFile,()=>at,{evaluate:value=>restartedContainment.schedulingEligibility(schedulerContainmentScopes(value))});result=restartedBoard.reconcile(board.id,restartedBoard.get(board.id).version,[{...resource,sessionGeneration:99,available:true}]);assert.match(result.decisions[0]!.reason,/QUARANTINED/);for(const state of ['INSPECTED','RESET','REQUALIFIED'] as const)restartedContainment.recovery(s.kill.id,state,`evidence:${state}`,'qualification-operator');result=restartedBoard.reconcile(board.id,result.boardVersion,[{...resource,sessionGeneration:100,available:true}]);assert.match(result.decisions[0]!.reason,/QUARANTINED/);restartedContainment.recovery(s.kill.id,'AVAILABLE','qualification passed','qualification-operator');result=restartedBoard.reconcile(board.id,result.boardVersion,[{...resource,sessionGeneration:101,available:true}]);assert.ok(result.selected.includes(target.id));});

test('scheduler reconciliation never resurrects terminal contained work',async t=>{const s=await quarantinedBoard();t.after(()=>fs.rmSync(s.root,{recursive:true,force:true}));let board=create(s.runtime,s.board.version,'Killed work',{laneId:'work',requirements:{capabilities:['execute']}}),target=item(board,'Killed work');board=s.runtime.apply(board.id,board.version,{type:'SET_STATE',itemId:target.id,state:'QUEUED',reason:'ready'},'operator');board=s.runtime.linkRun(board.id,board.version,target.id,{runId:'run-killed',attempt:1,state:'RUNNING',startedAt:at,evidence:['containment:test']});board=s.runtime.apply(board.id,board.version,{type:'SET_STATE',itemId:target.id,state:'CANCELLED',reason:'containment confirmed'},'watchdog');const result=s.runtime.reconcile(board.id,board.version,[{id:'other',workerId:'other',available:true,capabilities:['execute'],runtimes:[]}]);assert.equal(result.decisions.some(value=>value.itemId===target.id),false);assert.equal(item(s.runtime.get(board.id),'Killed work').state,'CANCELLED');});
