import assert from 'node:assert/strict'; import fs from 'node:fs'; import test from 'node:test';
const source=fs.readFileSync(new URL('../assets/dashboard/dashboard-enhancements.js',import.meta.url),'utf8');
const dashboard=fs.readFileSync(new URL('../assets/dashboard/dashboard.js',import.meta.url),'utf8');
const parameterized=fs.readFileSync(new URL('../assets/dashboard/dashboard-parameterized-jobs.js',import.meta.url),'utf8');
test('running dashboard exposes browser capability node transport engine and reason',()=>{for(const label of['Capability / route','Node / transport','Engine','Routing reason','Chromium/Playwright','chatgpt.web','chatgpt.android'])assert.match(source,new RegExp(label.replace('/','\\/')));});
test('live token dashboard preserves fresh, cache-read and cache-write accounting and resolves next route by thread id',()=>{for(const label of['fresh +','cache read +','cache write','point.cumulative?.freshInputTokens','point.cumulative?.cachedInputTokens','point.cumulative?.cacheWriteTokens','item.threadId === thread.id'])assert.ok(source.includes(label),label);assert.equal(source.includes('item.threadId === thread.threadId'),false);});
test('live event stream starts independently of optional projection refreshes',()=>{assert.ok(dashboard.includes('connectEvents();refresh().catch(showError)'));assert.equal(dashboard.includes('refresh().then(connectEvents)'),false);});
test('unconfigured parameterised Job projection degrades locally without poisoning dashboard refresh',()=>{assert.ok(parameterized.includes('try{await loadParameterizedJobs()}catch(error){renderParameterizedUnavailable(error)}'));assert.match(parameterized,/Core Job, Work Parcel and live event-stream controls remain active/);});
test('parameterised Work Parcels appear as authoritative lanes and navigate to the genuine Job Run',()=>{for(const label of['Parameterized Work Parcel lanes · authoritative','data-parameterized-lane-run','run.workParcelIds','run.modelRoute','run.executionMode'])assert.ok(parameterized.includes(label),label);assert.ok(parameterized.includes('setJobPlatformTab(\'runs\')'));assert.ok(parameterized.includes('data-view="jobs"'));});
