import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {personalResultSchema} from '../src/control/personal-benchmark-league.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),structure=process.argv.includes('--structure'),failures:string[]=[],pending:string[]=[];
const resolve=(relative:string)=>{const target=path.resolve(root,relative);if(!target.startsWith(root+path.sep))throw Error('showcase_path_outside_repository');return target;};
const read=(relative:string)=>fs.readFileSync(resolve(relative),'utf8');
const manifest=JSON.parse(read('examples/showcase-4.6/showcase-manifest.json')),pkg=JSON.parse(read('package.json'));
if(manifest.version!==pkg.version)failures.push('Candidate version differs from package');
for(const file of ['README.md','docs/installation-first-run.md','docs/showcase-4.6-status.md','examples/showcase-4.6/README.md']){
  const text=read(file);
  for(const match of text.matchAll(/!?\[[^\]]*\]\(([^)]+)\)/g)){const link=match[1]!.split('#')[0]!;if(!link||/^[a-z]+:/i.test(link))continue;const target=path.resolve(path.dirname(resolve(file)),decodeURIComponent(link));if(!target.startsWith(root+path.sep)||!fs.existsSync(target))failures.push(`Unresolved link in ${file}: ${link}`);}
  if(/(?:sk-[A-Za-z0-9]{20,}|-----BEGIN [A-Z ]*PRIVATE KEY-----|Bearer [A-Za-z0-9_-]{24,}|\/fast\/(?:work|repos)\/|C:\\Users\\)/.test(text))failures.push(`Private material pattern in ${file}`);
}
for(const shot of manifest.screenshots){const file=resolve(shot.file);if(!fs.existsSync(file)){failures.push(`Missing screenshot ${shot.file}`);continue;}const hash=createHash('sha256').update(fs.readFileSync(file)).digest('hex');if(hash!==shot.sha256)failures.push(`Screenshot checksum changed ${shot.file}`);if(shot.privacyReviewed!==true||shot.synthetic!==false)failures.push(`Screenshot review missing ${shot.file}`);if(!/^[a-f0-9]{40}$/.test(shot.sourceCommit))failures.push(`Capture source commit missing ${shot.file}`);else try{const captured=JSON.parse(execFileSync('git',['show',`${shot.sourceCommit}:package.json`],{cwd:root,encoding:'utf8',stdio:['ignore','pipe','ignore']}));if(captured.version!==manifest.version)pending.push(`Capture predates current candidate version: ${shot.file}`);}catch{failures.push(`Unknown capture source commit ${shot.file}`);}}
const example=JSON.parse(read(manifest.intelligence.file));if(example.changesDetected!==manifest.intelligence.changesDetected||example.relevantCandidates!==manifest.intelligence.relevantCandidates||example.benchmarked!==manifest.intelligence.benchmarked)failures.push('Displayed intelligence counts differ from source example');
const report=read('examples/showcase-4.6/README.md');for(const [label,value]of [['Initial model/artifact/runtime changes',example.changesDetected],['Relevant and provisionable reviewed candidates',example.relevantCandidates],['Models benchmarked',example.benchmarked]])if(!report.includes(`| ${label} | ${value} |`))failures.push(`Example table differs: ${label}`);
for(const benchmark of manifest.benchmarks){try{const result=personalResultSchema.parse(JSON.parse(read(benchmark.result)));if(result.status!=='COMPLETE'||result.provenance!=='NATIVE_EXECUTION')failures.push('Showcase winner lacks complete native evidence');const evidence=[...benchmark.validators,...benchmark.resources];if(!evidence.length)failures.push('Benchmark evidence drill-down missing');for(const file of evidence)if(!fs.existsSync(resolve(file)))failures.push(`Benchmark evidence missing: ${file}`);}catch{failures.push('Benchmark result schema or evidence invalid');}}
if(!manifest.benchmarks.length)pending.push('No approved, measured target-model benchmark result');
for(const kind of ['dashboard','estate','process-active','discovery-start','discovery-running','discovery-completed','resource-inspector','personal-league','model-intelligence','morning-brief','mallow-proposal'])if(!manifest.screenshots.some((shot:any)=>shot.kind===kind))pending.push(`Required real screenshot missing: ${kind}`);
if(manifest.acceptance.cleanInstall!=='PASS_REVIEWED_README')pending.push('Published README clean-machine acceptance not complete');
const limitations:string[]=[];
if(!['PASS','PASS_WITH_LIMITATIONS','BASE_PASS_WITH_LIMITATIONS_BENCHMARK_BLOCKED'].includes(manifest.acceptance.androidStandalone))failures.push('Android standalone base deployment lacks physical acceptance');
else if(manifest.acceptance.androidStandalone!=='PASS')limitations.push('Android optional inference, telemetry and benchmark league are not qualified');
if(manifest.acceptance.overnight!=='PASS')limitations.push('Real overnight-duration qualification not complete; manual watch evidence only');
const state=failures.length?'FAIL':pending.length?'INCOMPLETE':limitations.length?'PASS_WITH_LIMITATIONS':'PASS';console.log(JSON.stringify({gate:'SHOWCASE',mode:structure?'DRAFT_STRUCTURE':'RELEASE',state,failures,pending,limitations},null,2));if(failures.length||(!structure&&pending.length))process.exitCode=1;
