import fs from 'node:fs';
import path from 'node:path';
import {ActionRegistry,createJobRuntime,WorkerRegistry} from '../src/control/job-runtime.js';
import {JobCatalog} from '../src/control/job-catalog.js';
import {registerSecurityAudit,registerSecurityAuditContinuation,SECURITY_AUDIT_VERIFIER_WORKER} from '../src/control/security-audit-job.js';
import {SecurityAuditRuntime,SecurityAuditStore} from '../src/control/security-audit.js';

const [auditId,stateArgument,sourceArgument,evidenceArgument]=process.argv.slice(2);
if(!auditId||!stateArgument||!sourceArgument||!evidenceArgument)throw Error('Usage: continue-security-audit-v4.9.ts AUDIT_ID STATE_ROOT EXACT_SOURCE_ROOT EVIDENCE_ROOT');
const stateRoot=path.resolve(stateArgument),sourceRoot=path.resolve(sourceArgument),evidenceRoot=path.resolve(evidenceArgument),controllerRoot=path.resolve('.');
const actions=new ActionRegistry(),catalog=new JobCatalog(actions.ids()),workers=new WorkerRegistry(),runtime=createJobRuntime(stateRoot,catalog,actions,workers),audits=new SecurityAuditRuntime(new SecurityAuditStore(path.join(stateRoot,'security-audits')),[controllerRoot,sourceRoot]);
registerSecurityAudit(runtime,audits);registerSecurityAuditContinuation(runtime,audits);
const before=audits.get(auditId),frozenFindings=structuredClone(before.findings),startedAt=new Date().toISOString();audits.resume(auditId,'qualification-operator');const run=runtime.createRun('security-audit-continuation@1.0.0',{auditId,sourceRoot},{type:'manual',actor:'qualification-operator'});audits.linkRun(auditId,run.id,'qualification-operator');
for(let tick=0;tick<12&&!['SUCCEEDED','FAILED','CANCELLED','DEGRADED'].includes(runtime.ledger.get(run.id)?.status??'');tick++)await runtime.tick();
const terminal=runtime.ledger.get(run.id);if(terminal?.status!=='SUCCEEDED')throw Error(`security_audit_continuation_${terminal?.status??'missing'}`);const audit=audits.get(auditId);fs.mkdirSync(evidenceRoot,{recursive:true});for(const [name,item] of Object.entries(audit.artifacts))fs.copyFileSync(item.path,path.join(evidenceRoot,path.basename(item.path)));
const processed=new Set((audit.findingHistory??[]).map(item=>item.candidateId)),latest=new Map(audit.verifications.map(item=>[item.candidateId,item])),activityFile=path.join(stateRoot,'logs','activity.jsonl'),activity=fs.existsSync(activityFile)?fs.readFileSync(activityFile,'utf8').trim().split('\n').filter(Boolean).map(line=>JSON.parse(line)).filter(row=>row.runId===run.id):[];
const receipt={schema:'agent-control.security-audit-continuation-qualification/v1',auditId,runId:run.id,sourceRevision:audit.sourceRevision,sourceRoot,startedAt,endedAt:new Date().toISOString(),runStatus:terminal.status,steps:terminal.steps.map(step=>({id:step.id,status:step.status,workerId:step.attempts.at(-1)?.workerId,attempts:step.attempts.length})),sandbox:audit.sandbox,processed:processed.size,previousFindingsPreserved:(audit.findingHistory??[]).every(item=>frozenFindings.some(old=>JSON.stringify(old)===JSON.stringify(item))),findings:{confirmed:audit.findings.filter(item=>item.verdict==='confirmed').length,needsValidation:audit.findings.filter(item=>item.verdict==='needs_validation').length,rejected:audit.findings.filter(item=>item.verdict==='rejected').length},independence:{verifierWorker:SECURITY_AUDIT_VERIFIER_WORKER,full:[...processed].filter(id=>latest.get(id)?.independence==='FULL'&&latest.get(id)?.verifier.workerId===SECURITY_AUDIT_VERIFIER_WORKER).length,separateInvocationIdentities:[...processed].filter(id=>{const candidate=audit.candidates.find(item=>item.id===id),verification=latest.get(id);return candidate&&verification&&candidate.finder.invocationId!==verification.verifier.invocationId;}).length},activity:{events:activity.length,sensitiveFixtureDataLeaked:activity.some(row=>JSON.stringify(row).includes('this-must-not-enter-evidence'))},artifacts:audit.artifacts};fs.writeFileSync(path.join(evidenceRoot,'continuation-qualification.json'),`${JSON.stringify(receipt,null,2)}\n`,{mode:0o600});console.log(JSON.stringify(receipt));
