import test from 'node:test';
import assert from 'node:assert/strict';
import {FactoryConnection,FactoryHistory} from '../assets/dashboard/factory-client.js';
import {positionFactory,displayMetric} from '../assets/dashboard/factory-layout.js';
const frame=(sequence=1,state='RUNNING')=>({schema:'agent-control.factory-frame/v1',id:`epoch:${sequence}`,sequence,epoch:'epoch',at:'2026-09-21T10:00:00Z',projection:{schema:'agent-control.factory/v1',entities:[{id:'job:a',kind:'job',sourceId:'a',label:'A',state,laneId:null,metrics:{},detail:{},links:[]}],relations:[],events:[],coverage:{omittedEntities:0}}});
test('Factory client keeps byte/count bounds, duplicate IDs and sequence gaps explicit',()=>{const h=new FactoryHistory(2,20000);h.add(frame());h.add(frame());assert.equal(h.frames.length,1);h.add(frame(3));h.add(frame(4));assert.equal(h.frames.length,2);assert.equal(h.gaps,1);assert.equal(h.dropped,1);assert.equal(h.export().coverage.sequenceGaps,1);const tiny=new FactoryHistory(10,1);tiny.add(frame());assert.equal(tiny.frames.length,0);assert.equal(tiny.dropped,1);});
test('Factory client replays recorded replacement state without touching runtime APIs',()=>{const h=new FactoryHistory();h.import({schema:'agent-control.factory-replay/v1',frames:[frame(1,'QUEUED'),frame(2,'VERIFYING'),frame(3,'SUCCEEDED')]});assert.deepEqual(h.frames.map(f=>f.projection.entities[0].state),['QUEUED','VERIFYING','SUCCEEDED']);});
test('Factory imported captures reject unsupported, malformed and oversized payloads atomically',()=>{const h=new FactoryHistory();h.add(frame());assert.throws(()=>h.import({schema:'other',frames:[]}));assert.throws(()=>h.import({schema:'agent-control.factory-replay/v1',frames:[{...frame(),projection:{...frame().projection,entities:[{}]}}]}));assert.equal(h.frames.length,1);assert.throws(()=>h.import({schema:'agent-control.factory-replay/v1',frames:Array(241).fill(frame())}));});
test('Factory layout derives dynamic lanes and isolates quarantined workers',()=>{const entities=[{id:'lane:one',kind:'lane',label:'CUSTOM'},{id:'job:a',kind:'job',laneId:'lane:one',state:'VERIFYING'},{id:'worker:a',kind:'worker',state:'QUARANTINED'}];const p=positionFactory(entities);assert.equal(p.lanes[0].label,'CUSTOM');assert.equal(p.positions.get('job:a').x,13);assert.equal(p.positions.get('worker:a').x,42);});
test('Factory layout follows state changes and never creates imaginary jobs or lanes',()=>{const empty=positionFactory([]);assert.equal(empty.positions.size,0);assert.equal(empty.lanes.length,0);const job={id:'j',kind:'job',state:'RUNNING'};assert.equal(positionFactory([job]).positions.get('j').x,-6);job.state='SUCCEEDED';assert.equal(positionFactory([job]).positions.get('j').x,31);});
test('Factory metrics distinguish unavailable values, zero and reported percentages',()=>{assert.equal(displayMetric({value:null,unit:'tokens'}),'UNAVAILABLE');assert.equal(displayMetric({value:0,unit:'tokens'}),'0 tokens');assert.equal(displayMetric({value:81,unit:'%'}),'81 %');});

test('Factory active routing physically follows the real provider/model column',()=>{const models=[{id:'model:a',kind:'model',modelId:'same',providerId:'a'},{id:'model:b',kind:'model',modelId:'same',providerId:'b'}],job={id:'job:a',kind:'job',state:'RUNNING',modelId:'same',providerId:'a',detail:{modelAssignment:'CURRENT_INVOCATION'}};const first=positionFactory([...models,job]);assert.equal(first.positions.get(job.id).x,first.positions.get('model:a').x);job.providerId='b';const next=positionFactory([...models,job]);assert.equal(next.positions.get(job.id).x,next.positions.get('model:b').x);assert.notEqual(first.positions.get(job.id).x,next.positions.get(job.id).x);});
test('Factory SSE parser accepts chunked UTF-8/CRLF and reconnect retains last observed cursor',async()=>{const original=globalThis.fetch;const seen=[],statuses=[],requests=[];let connection;globalThis.fetch=async(url,options)=>{requests.push(options.headers);const body=`event: factory.coverage\r\ndata: {"gap":false}\r\n\r\nid: epoch:1\r\nevent: factory.frame\r\ndata: ${JSON.stringify(frame())}\r\n\r\n`;const bytes=new TextEncoder().encode(body);return new Response(new ReadableStream({start(c){for(const b of bytes)c.enqueue(new Uint8Array([b]));c.close();}}),{status:200});};try{connection=new FactoryConnection({token:()=> 'test',onStatus:s=>statuses.push(s),onCoverage:()=>{},onFrame:f=>{seen.push(f);connection.stop();}});connection.running=true;await connection.connect();assert.equal(seen.length,1);assert.equal(connection.lastId,'epoch:1');connection.running=true;await connection.connect();assert.equal(requests[1]['Last-Event-ID'],'epoch:1');assert.ok(statuses.includes('CONNECTED'));}finally{connection?.stop();globalThis.fetch=original;}});
test('Factory disabled stream stops retries and never fabricates state',async()=>{const original=globalThis.fetch;let state;globalThis.fetch=async()=>new Response('{}',{status:404});const c=new FactoryConnection({token:()=>'',onStatus:s=>state=s,onFrame:()=>assert.fail('No frame expected'),onCoverage:()=>{}});try{c.running=true;await c.connect();assert.equal(state,'DISABLED');assert.equal(c.running,false);assert.equal(c.retry,null);}finally{c.stop();globalThis.fetch=original;}});

test('Factory rapid stop/start cannot let an old aborted stream overwrite or reconnect the new session',async()=>{const original=globalThis.fetch,statuses=[];let rejectOld,requests=0;globalThis.fetch=async()=>{if(++requests===1)return new Promise((_,reject)=>rejectOld=reject);return new Response('{}',{status:404});};const c=new FactoryConnection({token:()=>'',onStatus:s=>statuses.push(s),onFrame:()=>assert.fail('No frame expected'),onCoverage:()=>{}});try{c.running=true;const old=c.connect();c.stop();c.running=true;await c.connect();rejectOld(Error('Aborted old transport'));await old;assert.equal(statuses.at(-1),'DISABLED');assert.equal(c.retry,null);assert.equal(requests,2);}finally{c.stop();globalThis.fetch=original;}});
