import fs from 'node:fs';
import path from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {WorkQueueStore} from '../src/control/work-queue-store.ts';
import {ensureAndroidProvisioningMission, runAndroidProvisioning, provisioningSummary} from '../src/control/android-provisioning-runtime.ts';
import {expandUserPath, loadConfig} from './config.mjs';
const exec = promisify(execFile), stateDir = process.env.AGENT_CONTROL_STATE_DIR || path.resolve('.agent-control'), artifactDir = path.join(stateDir, 'android-artifacts'), timeout = Number(process.env.AGENT_CONTROL_COMMAND_TIMEOUT_MS || 30000), packageTimeout = Number(process.env.AGENT_CONTROL_PACKAGE_TIMEOUT_MS || 300000), apkInstallTimeout = Number(process.env.AGENT_CONTROL_APK_INSTALL_TIMEOUT_MS || 300000);
const {config, configured, file: configFile} = loadConfig();
const androidResource = config.resources.find(resource => resource.platform === 'android' && resource.android);
if (!configured || !androidResource) {
  console.log(`UNCONFIGURED: add an Android resource to ${configFile}`);
  process.exit(0);
}
async function command(file, args, options = {}) { const r = await exec(file, args, {timeout, maxBuffer: 4 * 1024 * 1024, ...options}); return r.stdout.trim(); }
async function adb(args, options = {}) { return command('adb', args, options); }
const PRIVILEGED_HELPER = process.env.AGENT_CONTROL_PRIVILEGED_HELPER || '/usr/local/libexec/agent-control-privileged';
const TERMUX_HOME='/data/data/com.termux/files/home', TERMUX_PREFIX='/data/data/com.termux/files/usr', TERMUX_REPO=androidResource.android.remoteDirectory.replace(/^~(?=\/|$)/,TERMUX_HOME), TERMUX_BOOT_FILE=`${TERMUX_HOME}/.termux/boot/agent-control.sh`, TERMUX_HOOK_SOURCE=path.resolve('android/termux-boot-agent-control.sh');
const approveInstall=process.argv.includes('--approve-install'),approvePairing=process.argv.includes('--approve-pairing'),approveRebootTest=process.argv.includes('--approve-reboot-test'),wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
if (androidResource.transport.type !== 'ssh') throw new Error(`android_provisioning_requires_ssh_transport:${androidResource.id}`);
const androidHost=androidResource.transport.host,androidUser=androidResource.transport.user||'',androidPort=androidResource.transport.port,androidIdentity=expandUserPath(androidResource.transport.identityFile||'');
const ops = {
  async detectAdb() { try { await command('adb', ['version']); return true; } catch { return false; } },
  async installPackage(spec) { if (spec.manager !== 'apt' || spec.packageName !== 'adb') return {installed: false}; if (process.env.AGENT_CONTROL_ALLOW_ADB_INSTALL !== '1') throw new Error('PRIVILEGE_UNAVAILABLE: explicit AGENT_CONTROL_ALLOW_ADB_INSTALL=1 is required'); let helperError; try { await command('sudo', ['-n', PRIVILEGED_HELPER, 'install-adb'], {timeout: packageTimeout}); } catch (error) { helperError=error; } const installed=await this.detectAdb(); if(installed)return{installed:true}; if(helperError)throw new Error(`PRIVILEGE_UNAVAILABLE: fixed helper failed and adb remains absent (${helperError instanceof Error ? helperError.message : String(helperError)})`); return {installed:false}; },
  async qualifyAdb() { try { const out = await adb(['devices']); return {qualified: out.split(/\r?\n/).slice(1).some(line => /^\S+\s+device\s*$/.test(line))}; } catch { return {qualified: false}; } },
  async obtainTermuxBoot() { fs.mkdirSync(artifactDir, {recursive: true}); const api = JSON.parse(await command('curl', ['-fsSL', '--max-time', '20', 'https://api.github.com/repos/termux/termux-boot/releases/latest'])); const asset = api.assets?.find(a => String(a.name).endsWith('.apk')); if (!asset?.browser_download_url) throw new Error('termux_boot_github_apk_asset_missing'); const file = path.join(artifactDir, 'termux-boot.apk'); await command('curl', ['-fsSL', '--max-time', '60', '-o', file, asset.browser_download_url]); const sha256 = (await command('sha256sum', [file])).split(/\s+/)[0]; this.artifact = {artifactRef: file, sha256}; return this.artifact; },
  async verifyTermuxBoot(spec, artifact) { if (spec.host !== 'github.com' || spec.repository !== 'termux/termux-boot' || !artifact.artifactRef.startsWith(artifactDir)) return {verified: false, sha256: artifact.sha256}; const sha256 = (await command('sha256sum', [artifact.artifactRef])).split(/\s+/)[0]; return {verified: sha256 === artifact.sha256, sha256}; },
  async installTermuxBoot(packageName) { if (!this.artifact?.artifactRef || !fs.existsSync(this.artifact.artifactRef)) throw new Error('termux_boot_artifact_not_obtained'); const sha256=(await command('sha256sum',[this.artifact.artifactRef])).split(/\s+/)[0]; if(sha256!==this.artifact.sha256)throw new Error('termux_boot_artifact_hash_changed_after_verification'); let installError; try { await adb(['install', '-r', this.artifact.artifactRef], {timeout: apkInstallTimeout}); } catch (error) { installError=error; } const observed=await this.verifyTermuxBootPackage(packageName); if(observed.installed)return{installed:true}; if(installError)throw new Error(`DEVICE INSTALL INCOMPLETE: adb install ended before ${packageName} was observed (${installError instanceof Error ? installError.message : String(installError)})`); return {installed:false}; },
  async verifyTermuxBootPackage(packageName) { try { return {installed: /package:/.test(await adb(['shell', 'pm', 'path', packageName])), signingSource: 'github'}; } catch { return {installed: false, signingSource: 'other'}; } },
  async installBootHook() { await adb(['shell','run-as','com.termux','/system/bin/env',`HOME=${TERMUX_HOME}`,`PREFIX=${TERMUX_PREFIX}`,`PATH=${TERMUX_PREFIX}/bin:/system/bin`,`${TERMUX_PREFIX}/bin/bash`,`${TERMUX_REPO}/android/install-boot.sh`],{timeout:packageTimeout}); return {installed:(await this.verifyBootHook()).verified}; }, async verifyBootHook() { try { await adb(['shell','run-as','com.termux','test','-x',TERMUX_BOOT_FILE]); const expected=(await command('sha256sum',[TERMUX_HOOK_SOURCE])).split(/\s+/)[0],observed=(await adb(['shell','run-as','com.termux',`${TERMUX_PREFIX}/bin/sha256sum`,TERMUX_BOOT_FILE])).split(/\s+/)[0]; return {verified:observed===expected}; } catch { return {verified:false}; } }, async qualifyRebootRecovery() { if(!approveRebootTest)throw new Error('REBOOT_APPROVAL_REQUIRED'); if(!androidUser||!androidPort||!androidIdentity)throw new Error(`android_ssh_transport_incomplete:${androidResource.id}`); await adb(['reboot'],{timeout:30000}); for(let attempt=1;attempt<=36;attempt++){await wait(5000);try{const out=await command('ssh',['-i',androidIdentity,'-o','PasswordAuthentication=no','-o','BatchMode=yes','-o','ConnectTimeout=5','-p',String(androidPort),`${androidUser}@${androidHost}`,'echo SSH-READY'],{timeout:10000});if(out==='SSH-READY')return{qualified:true};}catch{}}return{qualified:false}; }
};
const store = new WorkQueueStore(path.join(stateDir, 'work-queue.json')), queue = store.load(); const artifactResult=queue.get('android.provision.obtain-termux-boot')?.resultRef; if(artifactResult){try{const restoredArtifact=JSON.parse(artifactResult); if(restoredArtifact.artifactRef?.startsWith(artifactDir)&&restoredArtifact.sha256)ops.artifact=restoredArtifact;}catch{}} const added = ensureAndroidProvisioningMission(queue); store.save(queue); const missionItems = queue.all().filter(item => item.id.startsWith('android.provision.')); console.log(`Android provisioning mission for ${androidResource.id} ${added ? 'created' : 'restored'} (${missionItems.length} items)`); const result = await runAndroidProvisioning({queue, store, ops, approveInstall, approvePairing, approveRebootTest, onEvent: e => console.log(`[${e.kind}] ${e.workId || ''} ${e.detail}`)}); console.log(provisioningSummary(result.queue)); const install = result.queue.get('android.provision.install-adb'); if (install?.status === 'human-review') console.log('\nNEEDS PRIVILEGE\nA one-time root-owned helper must be installed and narrowly sudo-authorized for exactly apt install adb. No password is captured or stored. Resume with:\n  AGENT_CONTROL_ALLOW_ADB_INSTALL=1 npm run provision:android -- --approve-install'); const apkInstall = result.queue.get('android.provision.install-termux-boot'); if (apkInstall?.status === 'human-review') console.log('\nNEEDS DEVICE INSTALL\nTermux:Boot has not yet been observed on the Android device. Check the configured device for a confirmation, then resume with:\n  npm run provision:android'); const review = result.queue.get('android.provision.pairing-approval'); if (review?.status === 'human-review') console.log('\nHUMAN REVIEW\nAndroid Wireless Debugging pairing required\n\nApprove pairing on the Android device, then resume with:\n  npm run provision:android -- --approve-pairing'); const reboot=result.queue.get('android.provision.qualify-reboot-recovery'); if(reboot?.status==='human-review')console.log('\nNEEDS REBOOT APPROVAL\nThe Android device has not been rebooted. This test will deliberately reboot it and wait up to three minutes for configured SSH transport to return. Run only when ready:\n  npm run provision:android -- --approve-reboot-test'); if (result.events.some(e => e.kind === 'failed')) process.exitCode = 1;
