import {spawn,execFileSync} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {EnergyTelemetryRuntime,FileEnergyTelemetryStore,type PowerSample} from '../src/control/energy-telemetry.js';

type Route = 'general-batch' | 'specialist-batch';
type Power = {watts:number|null;util:number|null;used:number|null;total:number|null};
type BatchOutput = {mode:string;elapsedMs:number;rows:Array<{id:string;output:{lane?:string};inputTokens:number|null;outputTokens:number|null;elapsedMs:number}>};

const root=path.resolve(process.env.AGENT_CONTROL_SPECIALIST_BATCH_ENERGY_OUTPUT??'qualification/agent-control-4.5-specialist-batch-energy-20260912');
const python=process.env.AGENT_CONTROL_SKILL_PYTHON??path.resolve('../agent-control-4.5-training-env/.venv/bin/python');
const basePath=process.env.AGENT_CONTROL_SKILL_BASE_PATH??path.join(os.homedir(),'.cache/huggingface/hub/models--HuggingFaceTB--SmolLM2-135M-Instruct/snapshots/12fd25f77366fa6b3b4b768ec3050bf629380bac');
const adapterPath=process.env.AGENT_CONTROL_SKILL_ADAPTER_PATH;
if(!adapterPath)throw new Error('specialist_adapter_path_required');
const endpoint=process.env.AGENT_CONTROL_LOCAL_MODEL_URL??'http://127.0.0.1:8080/v1/chat/completions';
const model=process.env.AGENT_CONTROL_LOCAL_MODEL_ID??'qwen2.5-3b-instruct-q4_k_m.gguf';
const repeats=5,threads=Number(process.env.AGENT_CONTROL_SKILL_THREADS??6),mergeAdapter=process.env.AGENT_CONTROL_SKILL_MERGE_ADAPTER==='1';
const tasks=[
  {id:'release-review',input:'Please review the repository release notes using read-only evidence.',lane:'LANE_REVIEW'},
  {id:'provider-verification',input:'Please verify the provider route against frozen criteria.',lane:'LANE_VERIFY'},
  {id:'telemetry-research',input:'Please research the dashboard telemetry without changing systems.',lane:'LANE_RESEARCH'},
];
const runtime=new EnergyTelemetryRuntime(new FileEnergyTelemetryStore(path.join(root,'energy-state.json')));
fs.mkdirSync(root,{recursive:true,mode:0o700});

function gpu():Power{try{const row=execFileSync('nvidia-smi',['--query-gpu=power.draw,utilization.gpu,memory.used,memory.total','--format=csv,noheader,nounits'],{encoding:'utf8',timeout:2000}).trim().split('\n')[0]!.split(',').map(value=>Number(value.trim()));return{watts:row[0]!,util:row[1]!,used:row[2]!,total:row[3]!};}catch{return{watts:null,util:null,used:null,total:null};}}
function perfValues(file:string){const text=fs.readFileSync(file,'utf8'),read=(name:string)=>{const match=text.match(new RegExp(`(?:^|\\n)([0-9.]+);Joules;power/${name}/`));return match?Number(match[1]):null};return{cpuJ:read('energy-pkg'),ramJ:read('energy-ram')};}
async function measured(command:string,args:string[],stdin:string){const perf=path.join(root,`.perf-${process.pid}-${Date.now()}`),samples:Array<{at:string;gpu:Power}>=[],started=Date.now(),child=spawn('sudo',['-n','perf','stat','-x',';','-o',perf,'-e','power/energy-pkg/','-e','power/energy-ram/','--',command,...args],{stdio:['pipe','pipe','pipe']}),out:string[]=[],err:string[]=[];child.stdout.on('data',value=>out.push(String(value)));child.stderr.on('data',value=>err.push(String(value)));const timer=setInterval(()=>samples.push({at:new Date().toISOString(),gpu:gpu()}),100);samples.push({at:new Date().toISOString(),gpu:gpu()});child.stdin.end(stdin);const exit=await new Promise<number|null>(resolve=>child.on('close',resolve));clearInterval(timer);samples.push({at:new Date().toISOString(),gpu:gpu()});const completed=Date.now(),duration=(completed-started)/1000,{cpuJ,ramJ}=perfValues(perf);fs.rmSync(perf,{force:true});if(exit!==0)throw new Error(`measured_command_failed:${exit}:${err.join('').slice(0,240)}`);const cpuRamW=cpuJ!==null&&ramJ!==null?(cpuJ+ramJ)/duration:0,powerSamples:PowerSample[]=samples.map(sample=>({at:sample.at,nodeId:'controller',scope:'MEASURED_COMPONENTS',watts:sample.gpu.watts===null?null:sample.gpu.watts+cpuRamW,cpuWatts:cpuRamW,gpuWatts:sample.gpu.watts,gpuUtilizationPercent:sample.gpu.util,vramUsedBytes:sample.gpu.used===null?null:sample.gpu.used*1024**2,vramTotalBytes:sample.gpu.total===null?null:sample.gpu.total*1024**2,authority:'MEASURED',source:'intel-rapl-package+dram+nvidia-smi-board-power',limitations:['excludes_motherboard_storage_psu_and_peripherals','cpu_power_is_interval_average','shared_gpu_processes_present']}));return{stdout:out.join(''),durationMs:completed-started,powerSamples};}
async function execute(route:Route,repeat:number){const baselineRun=await measured('sleep',['2'],''),baseline=runtime.establishBaseline(baselineRun.powerSamples),payload=JSON.stringify({mode:'batch',threads,mergeAdapter,endpoint,model,basePath,adapterPath,items:tasks}),run=route==='specialist-batch'?await measured(python,[path.resolve('scripts/skill-learning/infer-route-intent-batch.py')],payload):await measured(process.execPath,[path.resolve('scripts/skill-learning/infer-general-route-batch.mjs')],payload),output=JSON.parse(run.stdout) as BatchOutput,failures=tasks.flatMap(task=>{const row=output.rows.find(item=>item.id===task.id);return row?.output.lane===task.lane?[]:[`${task.id}:${row?.output.lane??'missing'}!=${task.lane}`]}),tokens=output.rows.reduce((sum,row)=>sum+(row.inputTokens??0)+(row.outputTokens??0),0),record=runtime.recordExecution({parcelId:`specialist-batch-energy-${repeat}`,stageId:route,route:{providerId:route==='specialist-batch'?'learned-specialist':'local-openai-compatible',modelId:route==='specialist-batch'?'SmolLM2-135M+route-intent-lora':model,nodeId:'controller'},samples:run.powerSamples,idleBaseline:baseline,tokens,verified:true,successful:failures.length===0,evidence:[`batch:${repeat}`,`verifier:${failures.length?'FAIL':'PASS'}`]});return{route,repeat,output,failures,verified:tasks.length-failures.length,energy:record};}

const results=[];
for(let repeat=1;repeat<=repeats;repeat++){const order:Route[]=repeat%2?['specialist-batch','general-batch']:['general-batch','specialist-batch'];for(const route of order)results.push(await execute(route,repeat));}
const summary=(['general-batch','specialist-batch'] as Route[]).map(route=>{const rows=results.filter(result=>result.route===route),joules=rows.reduce((sum,row)=>sum+(row.energy.joules??0),0),verified=rows.reduce((sum,row)=>sum+row.verified,0);return{route,batches:rows.length,verified,total:rows.length*tasks.length,joules,measuredJoulesPerVerifiedResult:verified?joules/verified:null,meanBatchMs:rows.reduce((sum,row)=>sum+row.output.elapsedMs,0)/rows.length};});
const general=summary.find(item=>item.route==='general-batch')!,specialist=summary.find(item=>item.route==='specialist-batch')!,pairedWins=Array.from({length:repeats},(_,index)=>{const repeat=index+1,g=results.find(result=>result.route==='general-batch'&&result.repeat===repeat)!,s=results.find(result=>result.route==='specialist-batch'&&result.repeat===repeat)!;return{sRepeatJoules:s.energy.joules,gRepeatJoules:g.energy.joules,specialistLower:s.energy.joules!==null&&g.energy.joules!==null&&s.energy.joules<g.energy.joules};}),saving=(general.measuredJoulesPerVerifiedResult??0)-(specialist.measuredJoulesPerVerifiedResult??0),trainingJoules=Number(process.env.AGENT_CONTROL_SPECIALIST_TRAINING_JOULES??'5232.819580132289'),breakEven=saving>0?Math.ceil(trainingJoules/saving):null,verdict=general.verified===15&&specialist.verified===15&&pairedWins.every(item=>item.specialistLower)&&saving>0?'PASS_PHYSICAL_SPECIALIST_BATCH_ENERGY':'FAIL_SPECIALIST_BATCH_ENERGY';
const report={schema:'agent-control.specialist-batch-energy-qualification/v1',observedAt:new Date().toISOString(),checkpoint:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),workflow:'homogeneous batch of three governed route-intent classifications, repeated five times',boundary:'Intel package + DRAM + NVIDIA GPU board; excludes motherboard, storage, PSU losses and peripherals',modelIdentity:{general:{model,endpoint:'controller-local configured OpenAI-compatible endpoint'},specialist:{baseModel:'HuggingFaceTB/SmolLM2-135M-Instruct',adapterReference:'operator-supplied local qualified artifact',threads,mergeAdapter}},results,summary,pairedWins,training:{joules:trainingJoules,authority:'PRIOR_PHYSICAL_EVIDENCE',breakEvenVerifiedResults:breakEven},conclusion:saving>0?`The trained specialist saved ${saving.toFixed(3)} measured-component joules per verified classification in the qualified homogeneous-batch workflow.`:'No specialist energy saving was measured for this workflow.',verdict};
fs.writeFileSync(path.join(root,'qualification.json'),JSON.stringify(report,null,2)+'\n',{mode:0o600});
process.stdout.write(JSON.stringify({root,verdict,summary,pairedWins,breakEven},null,2)+'\n');
if(verdict!=='PASS_PHYSICAL_SPECIALIST_BATCH_ENERGY')process.exitCode=2;
