import {LocalBenchmarkController} from '../src/control/local-llm-benchmark-controller.js';
import {registerLlamaCppBenchmarkJobs} from '../src/control/llama-cpp-benchmark-adapter.js';
import {LocalWatchBenchmarkPort} from '../src/control/local-watch-benchmark-port.js';
import {PoeRuntime} from '../src/control/poe.js';
import fs from 'node:fs';import path from 'node:path';import {once} from 'node:events';import {randomBytes} from 'node:crypto';
import {IntelligenceJournal,ModelLandscape,intelligenceHash,type IntelligenceSource,type ModelWatch} from '../src/control/model-landscape.js';
import {HuggingFaceMetadataAdapter,GitHubRuntimeReleasesAdapter} from '../src/control/model-intelligence-adapters.js';
import {ModelWatchRuntime,registerModelWatchJobs,modelWatchPlan} from '../src/control/model-watch-runtime.js';
import {PYTHON_REPAIR_CASES} from '../src/control/local-llm-benchmark.js';
import {ActionRegistry,ArtifactStore,JobRuntime,ResourceLockManager,RunLedger,WorkerRegistry} from '../src/control/job-runtime.js';
import {JobCatalog} from '../src/control/job-catalog.js';import {WorkParcelCoordinator,WorkParcelStore} from '../src/control/work-parcels.js';
import {EnvironmentDiscoveryRuntime,LocalMachineDiscoveryAdapter} from '../src/control/environment-discovery.js';
import {AgentControlService} from '../src/control/application-service.js';import {PtyRegistry} from '../src/control/pty.js';import {startWebDashboard} from '../src/control/web-server.js';
import {chromium} from 'playwright-core';
const root=path.resolve(process.argv[2]??'work/showcase-intelligence-observation');fs.mkdirSync(root,{recursive:true,mode:0o700});
const configuration=process.argv[3]?JSON.parse(fs.readFileSync(path.resolve(process.argv[3]),'utf8')):null;let controller:LocalBenchmarkController|undefined;
const sources:IntelligenceSource[]=[{id:'qwen-small-official',adapter:'huggingface-metadata',trust:'OFFICIAL',approved:true,endpoint:'https://huggingface.co/api/models/Qwen/Qwen2.5-Coder-0.5B-Instruct-GGUF?blobs=true',allowedOrigins:['https://huggingface.co'],settings:{}},{id:'qwen-medium-official',adapter:'huggingface-metadata',trust:'OFFICIAL',approved:true,endpoint:'https://huggingface.co/api/models/Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF?blobs=true',allowedOrigins:['https://huggingface.co'],settings:{}},{id:'runtime-official-releases',adapter:'github-runtime-releases',trust:'OFFICIAL',approved:true,endpoint:'https://api.github.com/repos/ggml-org/llama.cpp/releases?per_page=3',allowedOrigins:['https://api.github.com','https://github.com'],settings:{runtimeId:'llama.cpp'}}];
const journal=new IntelligenceJournal(path.join(root,'journal.jsonl')),landscape=new ModelLandscape(journal).register(new HuggingFaceMetadataAdapter(fetch,()=>configuration?.template.candidates??[])).register(new GitHubRuntimeReleasesAdapter());
const discovery=new EnvironmentDiscoveryRuntime({file:path.join(root,'discovery.json'),configurationRevision:()=> 'isolated-showcase-observation/v1',config:()=>({resources:[],models:[],providers:[],services:[],lanes:[]} as any),adapters:[new LocalMachineDiscoveryAdapter()]});
const scan=await discovery.discover({mode:'QUICK_RESCAN',testing:'QUICK_TEST',includeRemote:false,includeMemory:false}),machine=scan.items.find(i=>i.kind==='MACHINE')!;
const watches=new ModelWatchRuntime({journal,landscape,sources:()=>sources,estate:()=>[{id:machine.id,fresh:Date.now()-Date.parse(scan.completedAt)<120000,authenticated:true,controlQualified:Boolean(controller),ramAvailable:Number(machine.attributes.availableMemoryBytes),vramAvailable:0,diskAvailable:Number(machine.attributes.diskAvailableBytes),busy:false,gpuUtilisation:null,architectures:configuration?.template.execution.architectures??[],runtimes:configuration?['llama.cpp']:[],existingArtifactHashes:[],provisioners:[]}]});
const benchmark=watches.league.define({schema:'agent-control.personal-benchmark/v1',id:'python-function-repair',version:'1.0.0',objective:'Repair Python functions using independent tests',cases:PYTHON_REPAIR_CASES,attempts:2,settings:{context:2048,temperature:0,seed:7,maxOutputTokens:256,timeoutMs:90000,tools:[]},weights:{quality:.95,speed:.05,cost:0,memory:0},judge:null});
const definition:ModelWatch={schema:'agent-control.model-watch/v1',id:'read-only-physical-intelligence',name:configuration?'Physical readiness and benchmark proposal — approval required':'Physical intelligence observation — no downloads',sourceIds:sources.map(s=>s.id),benchmarkSha256:benchmark.digest,incumbentResultSha256:null,filters:{mode:'LOCAL',capability:'coding',allowedLicences:['apache-2.0','mit'],minimumContext:2048,maximumArtifactBytes:2e9,minimumTrust:'PRIMARY'},policy:{machines:[machine.id],maxDownloadBytesPerRun:configuration?1608720832:0,maxDownloadBytesPerDay:configuration?1608720832:0,maxApiSpendPerRun:0,maxApiSpendPerDay:0,currency:'USD',maxDurationMs:3600000,allowRuntimeInstall:false,onlyWhenIdle:true,pauseOnPriorityWork:true,maxGpuUtilisation:0,maxDiskBytes:configuration?4e9:0,automaticBenchmark:false},schedule:{kind:'MANUAL',utcHour:0,utcWeekday:0},notifications:[],routing:'NEVER_AUTOMATIC',retention:'KEEP_ALL',expiresAt:new Date(Date.now()+3600000).toISOString()};
const proposed=watches.policies.propose(definition);watches.policies.approve(proposed.digest,'operator-requested-read-only-physical-qualification');
const actions=new ActionRegistry(),catalog=new JobCatalog(actions.ids());registerModelWatchJobs(catalog,actions,watches);const workers=new WorkerRegistry().register({id:'metadata-controller',capabilities:['model.intelligence.control'],health:'healthy',capacity:1,active:0,observedAt:new Date().toISOString()}),runtime=new JobRuntime(catalog,actions,workers,new RunLedger(path.join(root,'runs.json')),new ArtifactStore(path.join(root,'artifacts')),new ResourceLockManager(path.join(root,'locks.json')),{approval:()=>false});
if(configuration){controller=new LocalBenchmarkController({root:configuration.root,template:configuration.template,scan:()=>scan,catalog,actions,registerExecution:registerLlamaCppBenchmarkJobs});controller.admit(configuration.template);}
const parcels=new WorkParcelCoordinator(runtime,new WorkParcelStore(path.join(root,'parcels.json')),{plan:()=>{throw Error('explicit_plan_required');}});if(controller){watches.options.benchmark=new LocalWatchBenchmarkPort({controller,league:watches.league,journal,parcels,resolve:item=>configuration.template.candidates.find((c:any)=>c.id===item.identity.model&&c.revision===item.identity.revision&&c.sha256===item.artifactSha256&&c.filename===item.identity.artifact)??null});}const runKey=intelligenceHash({watch:proposed.digest,at:new Date().toISOString()}),parcel=parcels.submitApprovedPlan('Observe official model metadata without acquiring targets','operator-requested-read-only-qualification',runKey,modelWatchPlan(proposed.digest,runKey));
for(let i=0;i<8;i++){await parcels.tick();await runtime.tick();await parcels.tick();if(parcels.get(parcel.id).endedAt)break;}
const outcome=parcels.get(parcel.id),projection=watches.projection();const browserRoot=path.join(root,'browser',parcel.id);fs.mkdirSync(browserRoot,{recursive:true});if(outcome.status!=='SUCCEEDED')throw Error('native_intelligence_workflow_'+outcome.status);
const control=new AgentControlService({version:1,paused:false,lastRestorePoint:null,lanes:[]},new PtyRegistry(),undefined,'4.6-showcase-candidate',()=>{}).configureProjection({modelWatches:watches,jobRuntime:runtime,workParcels:parcels,environmentDiscovery:discovery});
control.configureProjection({poe:new PoeRuntime({evidence:{overview:()=>({title:'Native intelligence',summary:'Read-only physical source observations',facts:[],related:[]}),resolve:()=>({title:'Native intelligence',summary:'See recorded native runs',facts:[],related:[]})},modelWatches:{draft:()=>({state:'REVIEW_REQUIRED'}),brief:()=>watches.projection().briefs.at(-1)}})});
const allowedOrigins:string[]=[];const token=randomBytes(32).toString('hex'),server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:token,allowedOrigins,assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');const base=`http://127.0.0.1:${(server.address() as any).port}`;allowedOrigins.push(base);
let browser;try{browser=await chromium.launch({executablePath:'/snap/bin/chromium',headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1050}});await page.goto(base);await page.locator('#operator-button').click();await page.locator('#operator-token').fill(token);await page.locator('#operator-token').press('Enter');await page.locator('#operator-dialog').waitFor({state:'hidden'});await page.locator('[data-view="model-watches"]').click();await page.locator('#watch-morning details').waitFor();await page.waitForFunction(()=>!document.getElementById('estate-dashboard-heartbeat')?.textContent?.includes('authentication required'),{},{timeout:8000});await page.locator('#watch-morning').screenshot({path:path.join(browserRoot,'morning-brief.png')});await page.locator('#watch-league').screenshot({path:path.join(browserRoot,'personal-league.png')});await page.locator('#model-watches-workspace').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(browserRoot,'model-watches-desktop.png')});await page.setViewportSize({width:390,height:844});await page.locator('#watch-morning').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(browserRoot,'model-watches-mobile.png')});const body=await page.locator('#model-watches-workspace').innerText();fs.writeFileSync(path.join(browserRoot,'browser-evidence.json'),JSON.stringify({modelWatchVisible:await page.locator('#model-watches-workspace').isVisible(),noPhysicalModelResults:body.includes('No physical benchmark results recorded.'),body}));}finally{await browser?.close();await new Promise<void>(resolve=>server.close(()=>resolve()));}
fs.writeFileSync(path.join(root,`summary-${parcel.id}.json`),JSON.stringify({scope:'Real read-only model metadata and native Work Parcel; not a model benchmark or overnight-duration proof',parcelId:parcel.id,status:outcome.status,nativeRuns:runtime.ledger.list().map(r=>({id:r.id,job:r.jobId,status:r.status})),sourceSnapshots:journal.records('source-snapshot').map(r=>({sourceId:r.value.sourceId,items:r.value.items.length,changes:r.value.changes.length,complete:r.value.complete})),brief:projection.briefs.at(-1),preparedBenchmark:journal.records('watch-benchmark-proposed').at(-1)?.value,downloadedModelBytes:0,modelResults:0,householdActions:0,productionRoutingChanged:false},null,2));
console.log(JSON.stringify({root,parcelId:parcel.id,status:outcome.status,sources:projection.sources.length,brief:projection.briefs.at(-1),modelResults:0}));
