import {spawn,execFileSync} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const output=path.resolve(process.env.AGENT_CONTROL_RESIDENCY_OUTPUT??'qualification/agent-control-4.5-residency-20260912');
const python=process.env.AGENT_CONTROL_SKILL_PYTHON??path.resolve('../agent-control-4.5-training-env/.venv/bin/python');
const basePath=process.env.AGENT_CONTROL_SKILL_BASE_PATH??path.join(os.homedir(),'.cache/huggingface/hub/models--HuggingFaceTB--SmolLM2-135M-Instruct/snapshots/12fd25f77366fa6b3b4b768ec3050bf629380bac');
const adapterPath=path.resolve('qualification/agent-control-4.5-skill-learning-20260911/training/adapter');
const holder=path.resolve('scripts/skill-learning/hold-specialist-resident.py');
const intervalSeconds=5,repetitions=5,loadPenaltyJoules=62.999;
fs.mkdirSync(output,{recursive:true,mode:0o700});

type Sample={phase:'BASELINE'|'WARM_RESIDENT';index:number;seconds:number;packageJoules:number|null;dramJoules:number|null;gpuJoules:number|null;measuredComponentJoules:number|null;measuredComponentWatts:number|null};
function gpuWatts(){try{const value=Number(execFileSync('nvidia-smi',['--query-gpu=power.draw','--format=csv,noheader,nounits'],{encoding:'utf8',timeout:2000}).trim().split('\n')[0]);return Number.isFinite(value)?value:null;}catch{return null;}}
async function interval(phase:Sample['phase'],index:number):Promise<Sample>{const perf=path.join(output,`.perf-${phase}-${index}`),gpu:Array<{at:number;watts:number|null}>=[],timer=setInterval(()=>gpu.push({at:Date.now(),watts:gpuWatts()}),250),started=Date.now();gpu.push({at:started,watts:gpuWatts()});const child=spawn('sudo',['-n','perf','stat','-x',';','-o',perf,'-e','power/energy-pkg/','-e','power/energy-ram/','--','sleep',String(intervalSeconds)],{stdio:['ignore','ignore','pipe']}),stderr:string[]=[];child.stderr.on('data',data=>stderr.push(String(data)));const status=await new Promise<number|null>(resolve=>child.on('close',resolve));clearInterval(timer);gpu.push({at:Date.now(),watts:gpuWatts()});if(status!==0)throw new Error(`residency_perf_failed:${status}:${stderr.join('').slice(0,160)}`);const text=fs.readFileSync(perf,'utf8'),read=(name:string)=>{const match=text.match(new RegExp(`(?:^|\\n)([0-9.]+);Joules;power/${name}/`));return match?Number(match[1]):null},packageJoules=read('energy-pkg'),dramJoules=read('energy-ram'),duration=(Date.now()-started)/1000,validGpu=gpu.map(item=>item.watts).filter((value):value is number=>value!==null),averageGpu=validGpu.length?validGpu.reduce((a,b)=>a+b,0)/validGpu.length:null,gpuJoules=averageGpu===null?null:averageGpu*duration,measuredComponentJoules=packageJoules!==null&&dramJoules!==null&&gpuJoules!==null?packageJoules+dramJoules+gpuJoules:null;fs.rmSync(perf,{force:true});return{phase,index,seconds:duration,packageJoules,dramJoules,gpuJoules,measuredComponentJoules,measuredComponentWatts:measuredComponentJoules===null?null:measuredComponentJoules/duration};}
function stats(values:Array<number|null>){const available=values.filter((value):value is number=>value!==null);if(!available.length)return{mean:null,standardDeviation:null,standardError:null};const mean=available.reduce((a,b)=>a+b,0)/available.length,variance=available.length>1?available.reduce((sum,value)=>sum+(value-mean)**2,0)/(available.length-1):0,standardDeviation=Math.sqrt(variance);return{mean,standardDeviation,standardError:standardDeviation/Math.sqrt(available.length)};}
async function main(){const samples:Sample[]=[];for(let index=1;index<=repetitions;index++)samples.push(await interval('BASELINE',index));const resident=spawn(python,['-u',holder],{stdio:['pipe','pipe','pipe']}),errors:string[]=[];resident.stderr.on('data',data=>errors.push(String(data)));resident.stdin.write(`${JSON.stringify({basePath,adapterPath})}\n`);const ready=await new Promise<{state:string;loadMs:number}>((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('resident_load_timeout')),180_000);resident.stdout.once('data',data=>{clearTimeout(timeout);try{resolve(JSON.parse(String(data).trim()));}catch{reject(new Error('resident_ready_invalid'));}});resident.once('exit',code=>reject(new Error(`resident_exited:${code}:${errors.join('').slice(0,160)}`)));});if(ready.state!=='READY')throw new Error('resident_not_ready');for(let index=1;index<=repetitions;index++)samples.push(await interval('WARM_RESIDENT',index));resident.stdin.end('STOP\n');await new Promise(resolve=>resident.once('exit',resolve));const baseline=stats(samples.filter(item=>item.phase==='BASELINE').map(item=>item.measuredComponentWatts)),warm=stats(samples.filter(item=>item.phase==='WARM_RESIDENT').map(item=>item.measuredComponentWatts)),delta=baseline.mean!==null&&warm.mean!==null?warm.mean-baseline.mean:null,uncertainty=baseline.standardError!==null&&warm.standardError!==null?2*Math.sqrt(baseline.standardError**2+warm.standardError**2):null,supported=delta!==null&&uncertainty!==null&&delta>uncertainty,breakEvenSeconds=supported?loadPenaltyJoules/delta!:null,report={schema:'agent-control.model-residency-qualification/v1',observedAt:new Date().toISOString(),boundary:'Intel package + DRAM + NVIDIA GPU board; excludes motherboard, storage, PSU losses and peripherals',repetitions,intervalSeconds,model:{base:'SmolLM2-135M-Instruct',adaptation:'qualified route-intent LoRA',device:'CPU'},residentLoadMs:ready.loadMs,samples,baseline,warm,deltaWatts:delta,uncertaintyWatts95Approx:uncertainty,loadPenaltyJoules,breakEvenSeconds,verdict:supported?'PARTIAL_COMPONENT_RESIDENCY_EFFECT_MEASURED':'PARTIAL_RESIDENCY_EFFECT_UNRESOLVED',routingAdmission:supported?'OBSERVATIONAL_ONLY':'NOT_ADMITTED',limitations:['not_whole_node','shared_gpu_processes_present','sequential_intervals_not_lab_isolated','five_interval_approximate_uncertainty','no_automatic_shutdown_or_route_policy_change']};fs.writeFileSync(path.join(output,'residency.json'),`${JSON.stringify(report,null,2)}\n`,{mode:0o600});process.stdout.write(`${JSON.stringify({report:path.join(output,'residency.json'),verdict:report.verdict,baseline,warm,deltaWatts:delta,uncertaintyWatts95Approx:uncertainty,breakEvenSeconds},null,2)}\n`);}
main().catch(error=>{process.stderr.write(`${error instanceof Error?error.stack:String(error)}\n`);process.exitCode=1;});
