/** Real, isolated host qualification. No synthetic entities or timed discovery staging. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {once} from 'node:events';import {execFileSync} from 'node:child_process';import {randomBytes} from 'node:crypto';import type {AddressInfo} from 'node:net';import {chromium} from 'playwright-core';
import {EstateDiscovery,registerEstateDiscovery} from '../src/control/estate-discovery.js';import {estateHash} from '../src/control/estate-model.js';import {emptyConfig} from '../src/control/config.js';import {ActionRegistry,WorkerRegistry,createJobRuntime} from '../src/control/job-runtime.js';import {JobCatalog} from '../src/control/job-catalog.js';import {AgentControlService} from '../src/control/application-service.js';import {PtyRegistry} from '../src/control/pty.js';import {startWebDashboard} from '../src/control/web-server.js';
const out=path.resolve(process.env.ESTATE_EVIDENCE_DIR??'../estate-view-qualification'),root=path.join(out,'private-runtime');fs.mkdirSync(out,{recursive:true,mode:0o700});process.env.AGENT_CONTROL_ACTIVITY_LOG=path.join(root,'activity.jsonl');
const candidateCommit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),candidateDirty=Boolean(execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim());const write=(name:string,v:unknown)=>fs.writeFileSync(path.join(out,name),JSON.stringify(v,null,2)+'\n');
const runtime=createJobRuntime(path.join(root,'jobs'),new JobCatalog(),new ActionRegistry(),new WorkerRegistry()),service=new AgentControlService({version:1,paused:false,lastRestorePoint:null,lanes:[]},new PtyRegistry(),undefined,'4.12.1-estate-candidate').configureProjection({jobRuntime:runtime});
const estate=new EstateDiscovery({root:path.join(root,'estate'),config:emptyConfig,targets:[{id:'local-model-api',kind:'ENDPOINT',label:'Selected local model API',locator:'http://127.0.0.1:8080'},{id:'candidate-repository',kind:'REPOSITORY',label:'Isolated candidate repository',locator:process.cwd()},{id:'candidate-storage',kind:'STORAGE',label:'Candidate filesystem',locator:process.cwd()}],onEvent:(type,payload)=>service.events.emit('environment.discovery_changed',{eventType:type,...payload},undefined,'estate-discovery')});registerEstateDiscovery(runtime,estate);runtime.ledger.subscribe((runId,type,status)=>service.events.emit('job.run_changed',{runId,type,status},undefined,'run-ledger'));
const allowedOrigins:string[]=[],token=randomBytes(32).toString('hex'),server=startWebDashboard(service,{host:'127.0.0.1',port:0,operatorToken:token,estate,allowedOrigins});await once(server,'listening');const url=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;allowedOrigins.push(url);
const browser=await chromium.launch({headless:true,executablePath:'/snap/bin/chromium',args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:1680,height:1160},colorScheme:'dark'});await context.addInitScript(t=>sessionStorage.setItem('agent-control-operator-token',t),token);const page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));let tick:NodeJS.Timeout|undefined,busy=false,monitor:NodeJS.Timeout|undefined;const shots=new Set<string>();
const shot=async(name:string)=>{await page.evaluate(()=>window.scrollTo(0,0));await page.locator('#estate-workspace').screenshot({path:path.join(out,name)});};
try{
 await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForFunction("typeof state!=='undefined'&&state.operatorAuth==='authenticated'");await page.locator('[data-view="estate"]').click();await page.waitForFunction(()=>(window as any).AgentControlEstate.state().projection?.estate?.status==='EMPTY');assert.equal(estate.latest(),null);await shot('01-empty-estate.png');
 for(const category of ['PASSIVE_INVENTORY','CONFIGURATION_READ','SERVICE_ENUMERATION','CAPABILITY_PROBES','REPOSITORY_INSPECTION','STORAGE_INSPECTION'])await page.locator(`[name="estate-category"][value="${category}"]`).check();for(const id of ['local-model-api','candidate-repository','candidate-storage'])await page.locator(`[name="estate-target"][value="${id}"]`).check();await page.locator('#estate-grant').click();await page.waitForFunction(()=>Boolean((window as any).AgentControlEstate.state().permissionId));await page.locator('.estate-scope summary').click();await shot('02-explicit-scope.png');
 tick=setInterval(async()=>{if(busy)return;busy=true;try{await runtime.tick();}catch(e){errors.push((e as Error).message);}finally{busy=false;}},100);
 let shooting=false;monitor=setInterval(async()=>{if(shooting)return;try{const s=estate.latest();if(!s)return;let name=s.entities.some(e=>e.kind==='model')?'05-model-observed.png':s.entities.some(e=>e.kind==='gpu')?'04-hardware-observed.png':s.entities.some(e=>e.kind==='host')?'03-host-discovered.png':null;if(name&&!shots.has(name)){shooting=true;shots.add(name);await shot(name);}}catch{}finally{shooting=false;}},150);
 const wall=performance.now(),cpu=process.cpuUsage(),memoryBefore=process.memoryUsage().rss;await page.locator('#estate-run').click();await page.waitForFunction(()=>['COMPLETED','PARTIAL'].includes((window as any).AgentControlEstate.state().projection?.estate?.status),{},{timeout:150000});if(monitor)clearInterval(monitor);while(shooting)await new Promise(r=>setTimeout(r,50));const durationMs=performance.now()-wall,cpuUsed=process.cpuUsage(cpu),snapshot=estate.latest()!;write('snapshot.json',snapshot);write('replay.json',estate.replay(snapshot.id));assert.ok(snapshot.entities.some(e=>e.id==='host:controller-local'&&e.state==='VERIFIED'));assert.ok(snapshot.entities.some(e=>e.kind==='worker'&&e.capabilities['local-system-observation']==='PASS'));assert.ok(snapshot.events.some(e=>e.type==='DISCOVERY_STARTED'));assert.ok(snapshot.events.some(e=>e.type==='PERMISSION_BLOCKED'));await shot('06-completed-estate.png');
 await page.evaluate(()=>{(window as any).AgentControlEstate.select('host:controller-local');});await shot('07-how-do-we-know.png');await page.waitForTimeout(1300);
 const model=snapshot.entities.find(e=>e.kind==='model');if(model){await page.evaluate(id=>(window as any).AgentControlEstate.select(id),model.id);await shot('08-model-capability.png');await page.waitForTimeout(1300);}
 const stats=await page.evaluate(()=>(window as any).AgentControlEstate.state().statistics);await page.locator('#estate-use').click();await page.waitForFunction(()=>document.querySelectorAll('#factory-entities button').length>0);await page.waitForFunction(()=>document.querySelector('#factory-entities')?.textContent?.includes('SUCCEEDED'),{},{timeout:30000});await page.waitForTimeout(1000);const useRun=runtime.ledger.list().find(r=>r.jobId==='estate-system-observation')!;assert.equal(useRun.status,'SUCCEEDED',JSON.stringify(useRun));await page.evaluate(id=>(window as any).AgentControlFactory.inspect(`job:${id}`),useRun.id);await page.locator('#factory-workspace').screenshot({path:path.join(out,'09-factory-native-job.png')});await page.waitForTimeout(1500);
 const evidenceId=useRun.artifacts.at(-1)!;await page.evaluate(id=>(window as any).AgentControlFactory.inspect(`evidence:${id}`),evidenceId);await page.locator('#factory-workspace').screenshot({path:path.join(out,'10-native-evidence.png')});await page.waitForTimeout(1000);await page.evaluate(()=>(window as any).AgentControlEstate.stopRecording());await page.waitForFunction(()=>!(window as any).AgentControlEstate.state().recording);const bytes=await page.evaluate(()=>(window as any).AgentControlEstate.captureBytes());assert.ok(bytes.length>10000);fs.writeFileSync(path.join(out,'estate-discovery.webm'),Buffer.from(bytes));write('video-manifest.json',await page.evaluate(()=>(window as any).AgentControlEstate.captureManifest()));write('factory-replay.json',await page.evaluate(()=>(window as any).AgentControlFactory.replay()));
 await page.locator('[data-view="estate"]').click();await page.waitForFunction(()=>(window as any).AgentControlEstate.state().active&&Boolean(document.querySelector('#estate-stage canvas')));await page.locator('#estate-load-replay').click();await page.waitForFunction(()=>(window as any).AgentControlEstate.state().mode==='REPLAY');const replayEmpty=await page.evaluate(()=>(window as any).AgentControlEstate.state().projection.entities.length);assert.equal(replayEmpty,0);await page.locator('#estate-replay').fill(String(snapshot.events.length-1));await page.locator('#estate-replay').dispatchEvent('input');await shot('11-recorded-replay.png');assert.equal(runtime.ledger.list().length,2);
 for(const [name,predicate] of [['replay-01-host-observed.png',(e:any)=>e.type==='HOST_OBSERVED'],['replay-02-host-verified.png',(e:any)=>e.type==='HOST_VERIFIED'],['replay-03-gpu-identified.png',(e:any)=>e.type==='GPU_IDENTIFIED'],['replay-04-runtime-identified.png',(e:any)=>e.type==='RUNTIME_IDENTIFIED'],['replay-05-model-probed.png',(e:any)=>e.type==='MODEL_CAPABILITY_VERIFIED']] as const){const index=snapshot.events.findIndex(predicate);if(index>=0){await page.locator('#estate-replay').fill(String(index));await page.locator('#estate-replay').dispatchEvent('input');await page.waitForTimeout(120);await shot(name);}}
 await page.locator('#estate-live').click();await page.locator('#estate-collapse').uncheck();await shot('13-services-expanded.png');await page.locator('#estate-search').fill('Quadro');await page.waitForTimeout(400);await shot('14-search-focus.png');await page.locator('#estate-search').fill('');await page.waitForTimeout(250);await page.locator('#estate-collapse').check();
 await page.setViewportSize({width:390,height:844});await shot('12-mobile.png');write('native-runs.json',runtime.ledger.list());write('native-artifacts.json',useRun.artifacts.map(id=>({id,record:runtime.artifacts.get(id),value:runtime.artifacts.read(id)})));assert.deepEqual(errors,[]);
 write('qualification.json',{candidateCommit,candidateDirty,mode:'REAL_AUTHORISED_LOCAL_HOST',scope:'Controller OS/GPU/worker/service metadata, selected loopback model endpoint, isolated repository revision and filesystem capacity; literal text and local observation probes. No logs, remote hosts, process arguments, credentials, LAN scan or inference admission.',startedAt:snapshot.startedAt,completedAt:snapshot.completedAt,durationMs,resources:{cpuMicroseconds:cpuUsed.user+cpuUsed.system,rssBefore:memoryBefore,rssAfter:process.memoryUsage().rss},renderer:stats,entities:snapshot.entities.length,relationships:snapshot.relationships.length,events:snapshot.events.length,states:Object.fromEntries([...new Set(snapshot.entities.map(e=>e.state))].map(state=>[state,snapshot.entities.filter(e=>e.state===state).length])),nativeDiscovery:runtime.ledger.list().find(r=>r.jobId==='discover-estate')?.status,nativeConsumption:useRun.status,discoveredWorkerId:'worker:agent-control:estate-observer',assignedWorkers:useRun.selectedWorkers,videoBytes:bytes.length,video:'estate-discovery.webm',eventChainHead:snapshot.events.at(-1)?.sha256,snapshotSha256:estateHash(snapshot),checks:{emptyInitial:true,progressiveEvents:true,realMetadata:true,independentHostIdentity:true,separateCapabilityProbe:true,recordedReplayNoWorkload:true,browserErrors:errors},limits:snapshot.coverage});process.stdout.write(JSON.stringify({out,entities:snapshot.entities.length,events:snapshot.events.length,run:useRun.status})+'\n');
}catch(e){write('failure.json',{message:(e as Error).message,errors,runs:runtime.ledger.list(),estate:estate.projection()});await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e;}finally{if(tick)clearInterval(tick);if(monitor)clearInterval(monitor);await browser.close();server.close();}
