import {createHash} from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {GovernedRetrievalRuntime,RepositoryTextRetrievalProvider,SpawnZgSearchExecutor,ZgRetrievalProvider,type RetrievalAttempt,type RetrievalIntent} from '../src/control/governed-retrieval.js';
import {decideRetrievalResource} from '../src/control/retrieval-resource-policy.js';

const zg=required('ZG_EXECUTABLE'),sourceFixture=path.resolve(process.env.AGENT_CONTROL_PHASE2_FIXTURE??'benchmarks/harness-mutation-fixture'),indexedFixture=path.resolve(required('AGENT_CONTROL_PHASE2_INDEXED_FIXTURE')),output=path.resolve(process.env.AGENT_CONTROL_PHASE2_FAILURE_RESULT??'qualification-results/3.8-phase2/failures.json'),root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-3.8-failures-'));
try{
  const absent=path.join(root,'absent'),stale=path.join(root,'stale');fs.cpSync(sourceFixture,absent,{recursive:true});fs.cpSync(indexedFixture,stale,{recursive:true});
  const cases=[];
  cases.push(await qualify('zg-unavailable',absent,'/definitely/missing/zg'));
  const beforeAbsent=fs.existsSync(path.join(absent,'.zvec-grep'));cases.push(await qualify('index-absent',absent,zg));const afterAbsent=fs.existsSync(path.join(absent,'.zvec-grep'));
  cases.push(await qualify('process-failure',absent,'/bin/false'));
  cases.push(await qualify('malformed-no-result',absent,'/bin/echo'));
  const staleFile=path.join(stale,'src','constants.js'),staleBefore=hash(fs.readFileSync(staleFile));fs.writeFileSync(staleFile,fs.readFileSync(staleFile,'utf8').replace('30_000','31_000'));const staleAfter=hash(fs.readFileSync(staleFile));cases.push(await qualify('stale-index',stale,zg));
  const memoryKb=Number(fs.readFileSync('/proc/meminfo','utf8').match(/^MemAvailable:\s+(\d+)/m)?.[1]??0),storage=fs.statfsSync(root),availableStorageMb=storage.bavail*storage.bsize/1024/1024,provider=new ZgRetrievalProvider().descriptor();
  const resourcePolicy={observed:{availableMemoryMb:Math.floor(memoryKb/1024),availableStorageMb:Math.floor(availableStorageMb),repositoryBytes:directoryBytes(sourceFixture),expectedTaskDurationMs:20_000,coldIndexMemoryMb:954,coldIndexDurationMs:21_410,indexManageAuthorized:true,builtinAvailable:true},shortTask:decideRetrievalResource({provider,indexState:'MISSING',availableMemoryMb:Math.floor(memoryKb/1024),availableStorageMb:Math.floor(availableStorageMb),repositoryBytes:directoryBytes(sourceFixture),expectedTaskDurationMs:20_000,coldIndexMemoryMb:954,coldIndexDurationMs:21_410,indexManageAuthorized:true,builtinAvailable:true}),insufficientMemory:decideRetrievalResource({provider,indexState:'MISSING',availableMemoryMb:512,availableStorageMb:Math.floor(availableStorageMb),repositoryBytes:directoryBytes(sourceFixture),expectedTaskDurationMs:120_000,coldIndexMemoryMb:954,coldIndexDurationMs:21_410,indexManageAuthorized:true,builtinAvailable:true}),noAuthority:decideRetrievalResource({provider,indexState:'MISSING',availableMemoryMb:Math.floor(memoryKb/1024),availableStorageMb:Math.floor(availableStorageMb),repositoryBytes:directoryBytes(sourceFixture),expectedTaskDurationMs:120_000,coldIndexMemoryMb:954,coldIndexDurationMs:21_410,indexManageAuthorized:false,builtinAvailable:true})};
  const report={schema:'agent-control.3.8-retrieval-failure-qualification/v1',generatedAt:new Date().toISOString(),cases,indexAbsence:{before:beforeAbsent,after:afterAbsent,searchOnlyDidNotCreateIndex:!beforeAbsent&&!afterAbsent},staleMutation:{path:'src/constants.js',beforeHash:staleBefore,afterHash:staleAfter},resourcePolicy,note:'Insufficient-memory policy is safely reproduced by a deterministic capacity observation; no OOM was induced.'};
  fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,`${JSON.stringify(report,null,2)}\n`,{mode:0o600});console.log(JSON.stringify({output,sha256:hash(fs.readFileSync(output)),cases:cases.map(item=>({id:item.id,fallback:item.fallback,attempts:item.attempts.map(attempt=>({providerId:attempt.providerId,outcome:attempt.outcome,freshness:attempt.freshness,reason:attempt.reason}))})),indexAbsence:report.indexAbsence,resourcePolicy},null,2));
  if(cases.some(item=>!item.fallback)||!report.indexAbsence.searchOnlyDidNotCreateIndex)process.exitCode=1;
}finally{fs.rmSync(root,{recursive:true,force:true});}

async function qualify(id:string,repositoryRoot:string,executable:string){const runtime=new GovernedRetrievalRuntime([new ZgRetrievalProvider(new SpawnZgSearchExecutor(executable)),new RepositoryTextRetrievalProvider('exact')],{enabled:true,progression:['HYBRID','EXACT'],maximumCalls:2,minimumConfidence:0,requiredCoverage:0,maximumEvidenceTokens:1024});const intent:RetrievalIntent={id:`failure:${id}`,parcelId:`parcel:${id}`,taskType:'qualification',query:'Assigned repository path src/constants.js Code identifier DEFAULT_JOB_TIMEOUT_MS',exactTerms:['src/constants.js','DEFAULT_JOB_TIMEOUT_MS'],scopes:['src/constants.js'],repository:{repositoryId:`failure-fixture:${id}`,root:repositoryRoot,gitSha:'phase2-failure-fixture',dirty:false},maximumEvidenceTokens:1024,requiredCoverage:0,minimumConfidence:0};const packet=await runtime.retrieve(intent),attempts=runtime.projection().attempts;return{id,fallback:packet.items[0]?.providerId==='builtin-ripgrep',packetProvider:packet.items[0]?.providerId,packetHash:packet.sha256,attempts:safeAttempts(attempts)};}
function safeAttempts(attempts:RetrievalAttempt[]){return attempts.map(({id:_id,...attempt})=>attempt);}
function directoryBytes(directory:string):number{return fs.readdirSync(directory,{withFileTypes:true}).reduce((sum,entry)=>{if(['.git','.zvec-grep','node_modules'].includes(entry.name)||entry.isSymbolicLink())return sum;const file=path.join(directory,entry.name);return sum+(entry.isDirectory()?directoryBytes(file):entry.isFile()?fs.statSync(file).size:0);},0);}
function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`${name.toLowerCase()}_required`);return value;}
function hash(value:string|Buffer){return createHash('sha256').update(value).digest('hex');}
