import assert from 'node:assert/strict';
import {createHash,randomBytes} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {once} from 'node:events';
import type {AddressInfo} from 'node:net';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {startWebDashboard} from '../src/control/web-server.js';
import {projectUxSession,sealUxSession,UxSessionAnnotationStore,UxSessionShareStore,UxSessionStore,type UxSessionArtifact,type UxSessionEvent,type UxSessionLane,type UxSessionRecord} from '../src/control/ux-session.js';

const require=createRequire(import.meta.url),root=process.cwd(),sourceCommit='fcb4127d049408af2177c1e5104b638160933e7e',memoryCommit='e449cd4d40fb570bacbd79ce64a2e5892f4372fa';
const sourceEvidencePath='docs/evidence/agent-control-4.3-parallel-lanes-qualification.json',sourceTranscriptPath='docs/evidence/agent-control-4.3-parallel-lanes-complete-transcript.md',sourceVideoPath='docs/evidence/agent-control-4.3-parallel-lanes-qualification.mp4';
const output=path.resolve('qualification/agent-control-4.4-ux-session-replay-20260911'),state=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-ux-replay-')),rawVideoDir=path.join(state,'video');fs.mkdirSync(output,{recursive:true});fs.mkdirSync(rawVideoDir,{recursive:true});
const sourceEvidence=gitObject(sourceCommit,sourceEvidencePath),sourceTranscript=gitObject(sourceCommit,sourceTranscriptPath),sourceVideo=gitObject(sourceCommit,sourceVideoPath),evidence=JSON.parse(sourceEvidence.toString('utf8'));
const memoryFile=path.resolve('docs/evidence/agent-control-4.4-marm-memory-qualification-20260911.json'),memoryBytes=fs.readFileSync(memoryFile),memory=JSON.parse(memoryBytes.toString('utf8'));
const sourceArtifacts:UxSessionArtifact[]=[artifact('transcript',`${sourceCommit}:${sourceTranscriptPath}`,sourceTranscript),artifact('screen-capture',`${sourceCommit}:${sourceVideoPath}`,sourceVideo),artifact('manifest',`${sourceCommit}:${sourceEvidencePath}`,sourceEvidence)];
const lanes:UxSessionLane[]=[...evidence.firstWave.map((lane:any)=>({id:lane.laneId,name:lane.laneName,provider:lane.providerId,model:lane.modelId,outcome:lane.outcome==='PASSED'?'PASSED':'FAILED',inputTokens:lane.usage?.inputTokens??null,outputTokens:lane.usage?.outputTokens??null,totalTokens:lane.usage?.totalTokens??null,cost:lane.usage?.cost??null,currency:lane.usage?.currency??null})),{id:'sol',name:'Sol Escalation Lane',provider:'codex-chatgpt',model:'sol',outcome:'SKIPPED',inputTokens:0,outputTokens:0,totalTokens:0,cost:0,currency:null}];
const turns=evidence.poe?.conversations?.[0]?.turns??[],operatorTurn=turns.find((turn:any)=>turn.actor==='operator'),poeGreeting=turns.find((turn:any)=>turn.purpose==='GREETING'),submitted=turns.at(-1),events:UxSessionEvent[]=[];
const push=(event:Omit<UxSessionEvent,'parentIds'|'evidenceRefs'>&{parentIds?:string[];evidenceRefs?:string[]})=>events.push({...event,parentIds:event.parentIds??[],evidenceRefs:event.evidenceRefs??[]});
if(poeGreeting)push({id:poeGreeting.id,at:poeGreeting.at,layer:'UX',kind:'POE',title:'POE welcomed the operator',summary:poeGreeting.text,outcome:'INFO',interaction:{actor:'poe',action:'greeting'}});
if(operatorTurn)push({id:operatorTurn.id,at:operatorTurn.at,layer:'UX',kind:'USER_INTERACTION',title:'Operator requested a parallel governed review',summary:operatorTurn.text,outcome:'INFO',interaction:{actor:'operator',action:'submit request'},parentIds:poeGreeting?[poeGreeting.id]:[]});
push({id:'proposal-approved',at:submitted?.at??evidence.startedAt,layer:'AGENT_CONTROL',kind:'JOB',title:'POE proposal explicitly approved',summary:'The bounded crew-wopr-review Job was approved and submitted to the Work Parcel runtime.',outcome:'PASSED',parentIds:operatorTurn?[operatorTurn.id]:[],evidenceRefs:[evidence.parentWorkParcel?.id??'parcel-social-39a33c88d6fca15e6664ae50c21a6644382353569a15be5e844234d4e2aa274b']});
push({id:'parallel-fan-out',at:evidence.startedAt,layer:'AGENT_CONTROL',kind:'ROUTING',title:'One immutable repository bundle fanned out to three lanes',summary:'Luna, Qwen and GLM received the same frozen bundle and the same independent acceptance gate.',outcome:'RUNNING',parentIds:['proposal-approved'],evidenceRefs:[evidence.repository?.immutableBundleSha256??evidence.gateDecision.immutableBundleSha256]});
for(const lane of evidence.firstWave){
  push({id:`${lane.runId}:started`,at:evidence.startedAt,layer:'AGENT_CONTROL',kind:'LANE',title:`${lane.laneName} invoked`,summary:`${lane.providerId} / ${lane.modelId} began independent review of the immutable bundle.`,outcome:'RUNNING',laneId:lane.laneId,provider:lane.providerId,model:lane.modelId,parentIds:['parallel-fan-out'],evidenceRefs:[lane.immutableBundleSha256]});
  push({id:`${lane.runId}:model`,at:lane.completedAt,layer:'TELEMETRY',kind:'MODEL',title:`${lane.laneName} provider execution completed`,summary:`Provider returned a structured repository review. Token use is provider reported where available; monetary cost remains unavailable unless the provider reported it.`,outcome:'PASSED',laneId:lane.laneId,provider:lane.providerId,model:lane.modelId,parentIds:[`${lane.runId}:started`],evidenceRefs:lane.evidence,telemetry:{inputTokens:lane.usage?.inputTokens??null,outputTokens:lane.usage?.outputTokens??null,totalTokens:lane.usage?.totalTokens??null,cachedTokens:null,cost:lane.usage?.cost??null,currency:lane.usage?.currency??null,authority:'AUTHORITATIVE'},diagnostic:{sanitisedInput:'Same immutable repository bundle and acceptance criteria.',sanitisedOutput:lane.result?.executiveSummary??'Structured result retained in source evidence.',durationMs:null},authorised:{content:JSON.stringify(lane.result),sourcePaths:lane.result?.areasReviewed??[]}});
  push({id:`${lane.runId}:gate`,at:lane.completedAt,layer:'AGENT_CONTROL',kind:'GATE',title:`${lane.laneName}: ${lane.outcome==='PASSED'?'PASS':'FAIL'}`,summary:lane.outcome==='PASSED'?'Independent gate accepted every required criterion.':`Independent gate rejected the result with ${lane.unresolvedCriteria.length} unresolved criterion/criteria.`,outcome:lane.outcome==='PASSED'?'PASSED':'FAILED',laneId:lane.laneId,provider:lane.providerId,model:lane.modelId,parentIds:[`${lane.runId}:model`],evidenceRefs:lane.evidence,diagnostic:{sanitisedOutput:lane.unresolvedCriteria.join('\n')||'All criteria resolved.'}});
}
push({id:'aggregate-decision',at:evidence.completedAt,layer:'AGENT_CONTROL',kind:'GATE',title:'Aggregate decision: accept GLM',summary:'One of three first-wave lanes passed. GLM was accepted as the independently verified result; Luna and Qwen remained truthful failures.',outcome:'PASSED',laneId:evidence.gateDecision.selectedLaneId,parentIds:evidence.firstWave.map((lane:any)=>`${lane.runId}:gate`),evidenceRefs:evidence.gateDecision.evidence});
push({id:'sol-not-invoked',at:evidence.completedAt,layer:'AGENT_CONTROL',kind:'ROUTING',title:'Sol was deliberately not invoked',summary:evidence.sol.reason,outcome:'SKIPPED',laneId:'sol',parentIds:['aggregate-decision'],evidenceRefs:[]});
push({id:'accounting',at:evidence.completedAt,layer:'TELEMETRY',kind:'TELEMETRY',title:'Work Parcel token accounting reconciled',summary:'The three lane totals reconcile with the aggregate Work Parcel total. Current-context occupancy was not reported and is therefore unavailable.',outcome:'PASSED',parentIds:['aggregate-decision'],evidenceRefs:evidence.gateDecision.evidence,telemetry:{inputTokens:evidence.gateDecision.usage.inputTokens,outputTokens:evidence.gateDecision.usage.outputTokens,totalTokens:evidence.gateDecision.usage.totalTokens,cachedTokens:null,cost:null,currency:null,authority:'AUTHORITATIVE'}});
push({id:'verification',at:evidence.completedAt,layer:'AGENT_CONTROL',kind:'OUTCOME',title:'Physical qualification verified',summary:'All three real lanes executed against the same immutable bundle, independent gates were applied, the correct result was selected, and conditional Sol admission was correct.',outcome:evidence.verification.passed?'PASSED':'FAILED',parentIds:['accounting','sol-not-invoked'],evidenceRefs:[sha(sourceEvidence),sha(sourceTranscript),sha(sourceVideo)]});
const parallel=sealUxSession({id:'ux-parallel-lanes-20260910',title:'Parallel Review — Two Failures, One Verified Result',startedAt:evidence.startedAt,completedAt:evidence.completedAt,sources:[{kind:'qualification-evidence',reference:`git:${sourceCommit}:${sourceEvidencePath}`,sha256:sha(sourceEvidence),authority:'Agent Control 4.3 physical qualification evidence'},{kind:'qualification-evidence',reference:`git:${sourceCommit}:${sourceTranscriptPath}`,sha256:sha(sourceTranscript),authority:'Agent Control product-generated complete transcript'}],events,lanes,outcome:{verdict:evidence.verdict??'PASS',summary:'Luna FAIL · Qwen FAIL · GLM PASS → accept GLM; Sol not invoked.',selectedLaneId:evidence.gateDecision.selectedLaneId,escalationInvoked:evidence.sol.invoked},totals:{inputTokens:evidence.gateDecision.usage.inputTokens,outputTokens:evidence.gateDecision.usage.outputTokens,totalTokens:evidence.gateDecision.usage.totalTokens,cost:null,currency:null,authority:'PARTIAL'},artifacts:sourceArtifacts});
const memoryEvents:UxSessionEvent[]=[
  memoryEvent('memory-requested',memory.startedAt,'REQUESTED','Your Memories checked for relevant context','Agent Control looked for relevant memories for eight real historical questions.',[]),
  memoryEvent('memory-validated',memory.startedAt,'VALIDATED','Your Memories passed governance and provenance checks','Current evidence, project and session boundaries were checked before any memory could enter context.',['memory-requested']),
  memoryEvent('memory-accepted',memory.startedAt,'ACCEPTED','Relevant memories were accepted','Eligible, current memories were accepted; their contents remain hidden in this replay.',['memory-validated']),
  memoryEvent('memory-rejected',memory.startedAt,'REJECTED','Unsafe or irrelevant memories were rejected','Stale, superseded, unrelated, unverified, incomplete and incorrect memories were rejected.',['memory-validated']),
  memoryEvent('memory-supplied',memory.completedAt,'SUPPLIED','Your Memories supplied bounded context','Supplied context fell from 6,022 to 550 estimated tokens while correctness remained 8/8.',['memory-accepted','memory-rejected']),
  {id:'memory-outcome',at:memory.completedAt,layer:'TELEMETRY',kind:'OUTCOME',title:'Your Memories comparison independently passed',summary:'Provider input fell from 7,844 to 1,608 tokens; correctness remained unchanged; memories remained advisory.',outcome:'PASSED',parentIds:['memory-supplied'],evidenceRefs:[sha(memoryBytes)],telemetry:{inputTokens:memory.comparison.memory.providerInputTokens,outputTokens:memory.comparison.memory.outputTokens,totalTokens:memory.comparison.memory.totalTokens,cachedTokens:memory.comparison.memory.cachedInputTokens,cost:null,currency:null,authority:'AUTHORITATIVE'}},
];
const memorySession=sealUxSession({id:'ux-memory-qualification-20260911',title:'Your Memories — Relevant Context, Safely Governed',startedAt:memory.startedAt,completedAt:memory.completedAt,sources:[{kind:'qualification-evidence',reference:`git:${memoryCommit}:docs/evidence/agent-control-4.4-marm-memory-qualification-20260911.json`,sha256:sha(memoryBytes),authority:'Agent Control 4.4 physical memory qualification'}],events:memoryEvents,lanes:[{id:'memory',name:'Your Memories',provider:'Agent Control',model:'Your Memories',outcome:'PASSED',inputTokens:1608,outputTokens:277,totalTokens:1885,cost:null,currency:null}],outcome:{verdict:memory.verdict,summary:'8/8 correct with bounded, provenance-checked memories.',selectedLaneId:'memory',escalationInvoked:false},totals:{inputTokens:1608,outputTokens:277,totalTokens:1885,cost:null,currency:null,authority:'PARTIAL'},artifacts:[artifact('manifest','governed-memory-evidence.json',memoryBytes)]});

const stores={sessions:new UxSessionStore(path.join(state,'sessions')),shares:new UxSessionShareStore(path.join(state,'shares.json')),annotations:new UxSessionAnnotationStore(path.join(state,'annotations.json'))};stores.sessions.write(parallel);stores.sessions.write(memorySession);
const external=stores.shares.create(parallel,'EXECUTION_OVERVIEW',{expiresAt:'2026-10-11T00:00:00.000Z'}),diagnostic=stores.shares.create(parallel,'SANITISED_DIAGNOSTIC',{expiresAt:'2026-10-11T00:00:00.000Z'}),memoryShare=stores.shares.create(memorySession,'EXECUTION_OVERVIEW',{expiresAt:'2026-10-11T00:00:00.000Z'});
const operatorToken=randomBytes(32).toString('hex'),server=startWebDashboard({} as never,{host:'127.0.0.1',port:0,operatorToken,assetsDir:path.resolve('assets/dashboard'),uxSessions:stores.sessions,uxSessionShares:stores.shares,uxSessionAnnotations:stores.annotations,uxSessionPlayerDir:path.resolve('assets/session-player')});await once(server,'listening');const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
let browser:any,context:any,video:any;const browserErrors:string[]=[];try{
  const {chromium}=require('playwright-core');browser=await chromium.launch({headless:true,executablePath:process.env.AGENT_CONTROL_CHROMIUM??'/snap/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});context=await browser.newContext({viewport:{width:1920,height:1080},recordVideo:{dir:rawVideoDir,size:{width:1920,height:1080}},colorScheme:'dark'});const page=await context.newPage();video=page.video();page.on('pageerror',(error:any)=>browserErrors.push(error.message));page.on('console',(message:any)=>{if(message.type()==='error')browserErrors.push(message.text())});await page.goto(`${base}${diagnostic.url}`,{waitUntil:'networkidle'});await page.waitForSelector('.lane');assert.equal(await page.locator('.lane').count(),4);assert.match(await page.locator('#decision').innerText(),/Accepted glm; escalation not invoked/);assert.match(await page.locator('#totals').innerText(),/14,897/);await page.screenshot({path:path.join(output,'interactive-replay.png'),fullPage:true});await page.click('#play');await page.waitForTimeout(Math.max(18_000,events.length*1450));await page.selectOption('#layer','TELEMETRY');await page.waitForTimeout(2500);await page.selectOption('#layer','ALL');await page.locator('button[data-index]').last().click();await page.waitForTimeout(2500);
  await page.goto(`${base}${memoryShare.url}`,{waitUntil:'networkidle'});await page.waitForSelector('.lane');assert.match(await page.locator('#title').innerText(),/Your Memories/);const memoryPageText=await page.locator('body').innerText();assert.match(memoryPageText,/Your Memories/);assert.doesNotMatch(memoryPageText,/MARM|generic memory abstraction|memory optimi[sz]ation/i);await page.screenshot({path:path.join(output,'your-memories-replay.png'),fullPage:true});await page.click('#play');await page.waitForTimeout(Math.max(9_000,memoryEvents.length*1450));
  const externalResponse=await fetch(`${base}/api/share/ux/${external.share.id}`,{headers:{Authorization:`Bearer ${external.token}`}}),externalText=await externalResponse.text();assert.equal(externalResponse.status,200);for(const forbidden of ['reservation-ledger.mjs','access-policy.mjs','test/acceptance.test.mjs','PRIVATE KEY','Bearer ','nvapi-','sk-proj-','operationalAccess":true','rerun":true'])assert.doesNotMatch(externalText,new RegExp(escape(forbidden),'i'));assert.equal((JSON.parse(externalText).events as any[]).some(event=>event.diagnostic),false);
  const diagnosticResponse=await fetch(`${base}/api/share/ux/${diagnostic.share.id}`,{headers:{Authorization:`Bearer ${diagnostic.token}`}});assert.equal(diagnosticResponse.status,200);assert.equal((await diagnosticResponse.json()).events.some((event:any)=>event.diagnostic),true);
  const memoryResponse=await fetch(`${base}/api/share/ux/${memoryShare.share.id}`,{headers:{Authorization:`Bearer ${memoryShare.token}`}}),memoryView=await memoryResponse.json(),memoryText=JSON.stringify(memoryView);assert.equal(memoryResponse.status,200);assert.equal(memoryView.events.filter((event:any)=>event.kind==='MEMORY').length,5);assert.equal(memoryView.events.every((event:any)=>!event.memory||event.memory.contentExposed===false),true);assert.match(memoryText,/Your Memories/);assert.doesNotMatch(memoryText,/MARM|generic memory abstraction|memory optimi[sz]ation/i);
  const annotationResponse=await fetch(`${base}/api/ux-sessions/${parallel.id}/annotations`,{method:'POST',headers:{Authorization:`Bearer ${operatorToken}`,'Content-Type':'application/json'},body:JSON.stringify({eventId:'aggregate-decision',comment:'01:23 — clarify why Sol was not invoked',audience:'SANITISED_DIAGNOSTIC'})});assert.equal(annotationResponse.status,201);assert.equal(stores.annotations.list(parallel.id).length,1);assert.equal(stores.annotations.list(parallel.id,'EXECUTION_OVERVIEW').length,0);assert.equal(stores.annotations.list(parallel.id,'SANITISED_DIAGNOSTIC').length,1);
  await context.close();context=undefined;const raw=await video.path();await browser.close();browser=undefined;execFileSync('ffmpeg',['-nostdin','-y','-loglevel','error','-i',raw,'-an','-c:v','libx264','-preset','medium','-crf','20','-pix_fmt','yuv420p','-movflags','+faststart',path.join(output,'agent-control-4.4-ux-session-replay.mp4')]);
}finally{if(context)await context.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});server.close();fs.rmSync(state,{recursive:true,force:true});}
assert.deepEqual(browserErrors,[]);
const transcript=renderTranscript(parallel),digestText=renderDigest(parallel);fs.writeFileSync(path.join(output,'complete-transcript.md'),transcript);fs.writeFileSync(path.join(output,'human-readable-digest.md'),digestText);fs.writeFileSync(path.join(output,'canonical-session.json'),`${JSON.stringify(parallel,null,2)}\n`);fs.writeFileSync(path.join(output,'memory-session.json'),`${JSON.stringify(memorySession,null,2)}\n`);fs.writeFileSync(path.join(output,'sanitised-external-view.json'),`${JSON.stringify(projectUxSession(parallel,'EXECUTION_OVERVIEW'),null,2)}\n`);fs.writeFileSync(path.join(output,'authorised-diagnostic-view.json'),`${JSON.stringify(projectUxSession(parallel,'SANITISED_DIAGNOSTIC'),null,2)}\n`);
const generated=['canonical-session.json','memory-session.json','sanitised-external-view.json','authorised-diagnostic-view.json','interactive-replay.png','your-memories-replay.png','agent-control-4.4-ux-session-replay.mp4','complete-transcript.md','human-readable-digest.md'].map(file=>{const bytes=fs.readFileSync(path.join(output,file));return{file,sha256:sha(bytes),bytes:bytes.length}}),videoInfo=JSON.parse(execFileSync('ffprobe',['-v','error','-show_entries','format=duration,size:stream=codec_name,width,height,r_frame_rate','-of','json',path.join(output,'agent-control-4.4-ux-session-replay.mp4')],{encoding:'utf8'}));
const manifest={schema:'agent-control.ux-session-qualification/v1',verdict:'PASS_PHYSICAL_UX_SESSION_REPLAY',qualifiedAt:new Date().toISOString(),implementationCommit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),sources:{parallel:{commit:sourceCommit,evidenceSha256:sha(sourceEvidence),transcriptSha256:sha(sourceTranscript),videoSha256:sha(sourceVideo),transcriptLines:sourceTranscript.toString('utf8').split('\n').length-1},memory:{commit:memoryCommit,evidenceSha256:sha(memoryBytes)}},sessions:[{id:parallel.id,sha256:parallel.sha256},{id:memorySession.id,sha256:memorySession.sha256}],representations:generated,videoInfo,checks:{immutableSession:true,sameSessionProvenance:true,parallelLaneOutcomes:Object.fromEntries(lanes.map(lane=>[lane.id,lane.outcome])),aggregateSelected:'glm',solInvoked:false,totalTokens:14897,readOnlyShare:true,expiryAndRevocationCoveredByFocusedTests:true,externalSourceRecovery:false,externalCredentialRecovery:false,diagnosticDrilldown:true,memoryProvenanceFlow:true,memoryContentsExposed:false,userFacingMemoryName:'Your Memories',implementationTerminologyAbsentFromNormalMemoryView:true,annotationOverlaySeparate:true,browserErrors}};fs.writeFileSync(path.join(output,'evidence-manifest.json'),`${JSON.stringify(manifest,null,2)}\n`);process.stdout.write(`${JSON.stringify({verdict:manifest.verdict,output,sessionSha256:parallel.sha256,video:generated.find(item=>item.file.endsWith('.mp4')),sourceTranscriptLines:manifest.sources.parallel.transcriptLines})}\n`);

function memoryEvent(id:string,at:string,operation:'REQUESTED'|'VALIDATED'|'ACCEPTED'|'REJECTED'|'SUPPLIED',title:string,summary:string,parentIds:string[]):UxSessionEvent{return{id,at,layer:'AGENT_CONTROL',kind:'MEMORY',title,summary,outcome:operation==='REJECTED'?'FAILED':'PASSED',parentIds,evidenceRefs:[sha(memoryBytes)],memory:{operation,contentExposed:false,provenance:[`git:${memoryCommit}`,sha(memoryBytes)]}}}
function artifact(kind:UxSessionArtifact['kind'],file:string,bytes:Buffer):UxSessionArtifact{return{kind,file,sha256:sha(bytes),bytes:bytes.length}}
function gitObject(commit:string,file:string){return execFileSync('git',['show',`${commit}:${file}`],{maxBuffer:64*1024*1024})}
function sha(value:Buffer|string){return createHash('sha256').update(value).digest('hex')}
function escape(value:string){return value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function renderTranscript(record:UxSessionRecord){return `# Agent Control UX Session Complete Transcript\n\n- Session: \`${record.id}\`\n- Session SHA-256: \`${record.sha256}\`\n- Started: \`${record.startedAt}\`\n- Completed: \`${record.completedAt}\`\n- Verdict: **${record.outcome.verdict}**\n\n${record.events.map((event,index)=>`## ${String(index+1).padStart(3,'0')} · ${event.at} · ${event.title}\n\n- Layer: \`${event.layer}\`\n- Kind: \`${event.kind}\`\n- Outcome: \`${event.outcome??'UNAVAILABLE'}\`\n- Lane: ${event.laneId??'none'}\n- Provider/model: ${event.provider??'unavailable'} / ${event.model??'unavailable'}\n- Parents: ${event.parentIds.join(', ')||'none'}\n- Evidence: ${event.evidenceRefs.join(', ')||'none'}\n\n${event.summary}\n`).join('\n')}\n## Integrity\n\nThis transcript is rendered from canonical session \`${record.sha256}\`; it excludes private model reasoning and credentials.\n`}
function renderDigest(record:UxSessionRecord){return `# ${record.title}\n\nThe operator asked POE for a governed parallel repository review. Agent Control sent one immutable bundle to three independent lanes.\n\n- Luna: **FAIL** — two required criteria remained unresolved.\n- Qwen: **FAIL** — eight required criteria remained unresolved.\n- GLM: **PASS** — every required criterion was satisfied.\n- Aggregate: **ACCEPT GLM**.\n- Sol: **NOT INVOKED**, because one first-wave lane passed.\n- Tokens: **10,119 input + 4,778 output = 14,897 total**.\n- Monetary total: **unavailable**; Agent Control does not manufacture unreported provider costs.\n\nCanonical session: \`${record.id}\` / \`${record.sha256}\`. The interactive replay, transcript, digest, screenshot and video are linked in the evidence manifest.\n`}
