/** Browser driver only: the ordinary Estate API, native Jobs and adapter own discovery. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {once} from 'node:events';import {execFileSync} from 'node:child_process';import {randomBytes,createHash} from 'node:crypto';import type {AddressInfo} from 'node:net';import {chromium} from 'playwright-core';
import {EstateDiscovery,registerEstateDiscovery} from '../src/control/estate-discovery.js';import {estateHash} from '../src/control/estate-model.js';import {estateResourceAlias} from '../src/control/estate-remote.js';import {emptyConfig,type ResourceConfig} from '../src/control/config.js';import {ActionRegistry,WorkerRegistry,createJobRuntime} from '../src/control/job-runtime.js';import {JobCatalog} from '../src/control/job-catalog.js';import {AgentControlService} from '../src/control/application-service.js';import {PtyRegistry} from '../src/control/pty.js';import {startWebDashboard} from '../src/control/web-server.js';

const configPath=process.env.ESTATE_APPROVED_RESOURCE_CONFIG,alias=process.env.ESTATE_APPROVED_RESOURCE_ALIAS,authorisation=process.env.ESTATE_SCOPE_AUTHORISATION_SHA256;
assert.ok(configPath&&alias&&authorisation&&/^[a-f0-9]{64}$/.test(authorisation),'Explicit approved configuration, alias and authorisation digest required');
const original=fs.readFileSync(configPath),external=JSON.parse(original.toString()),matches=(external.resources as ResourceConfig[]).filter(r=>estateResourceAlias(r.id)===alias);
assert.equal(matches.length,1,'Exactly one existing resource required');assert.equal(matches[0].managedNode?.enabled,true,'Existing managed-node authority required');assert.equal(matches[0].transport.type,'ssh');
const resource=structuredClone(matches[0]);resource.estateDiscovery={enabled:true,scope:'metadata-only',authorisationDigest:authorisation,expectedIdentitySha256:resource.estateDiscovery?.expectedIdentitySha256};
const config=emptyConfig();config.resources=[resource];
const out=path.resolve(process.env.ESTATE_EVIDENCE_DIR??'../estate-native-qualification'),root=path.join(out,'private-runtime');fs.mkdirSync(root,{recursive:true,mode:0o700});process.env.AGENT_CONTROL_ACTIVITY_LOG=path.join(root,'activity.jsonl');
const candidateCommit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),candidateDirty=Boolean(execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim());const write=(name:string,v:unknown)=>fs.writeFileSync(path.join(out,name),JSON.stringify(v,null,2)+'\n',{mode:0o600});
const runtime=createJobRuntime(path.join(root,'jobs'),new JobCatalog(),new ActionRegistry(),new WorkerRegistry()),service=new AgentControlService({version:1,paused:false,lastRestorePoint:null,lanes:[]},new PtyRegistry(),undefined,'4.12.1-estate-native-candidate').configureProjection({jobRuntime:runtime});
const estate=new EstateDiscovery({root:path.join(root,'estate'),config:()=>config,onEvent:(type,payload)=>service.events.emit('environment.discovery_changed',{eventType:type,...payload},undefined,'estate-discovery')});registerEstateDiscovery(runtime,estate);runtime.ledger.subscribe((runId,type,status)=>service.events.emit('job.run_changed',{runId,type,status},undefined,'run-ledger'));
const allowedOrigins:string[]=[],token=randomBytes(32).toString('hex'),server=startWebDashboard(service,{host:'127.0.0.1',port:0,operatorToken:token,estate,allowedOrigins});await once(server,'listening');const url=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;allowedOrigins.push(url);
const browser=await chromium.launch({headless:true,executablePath:'/snap/bin/chromium',args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:1680,height:1160},colorScheme:'dark'});await context.addInitScript(t=>sessionStorage.setItem('agent-control-operator-token',t),token);const page=await context.newPage(),errors:string[]=[];page.on('pageerror',()=>errors.push('BROWSER_PAGE_ERROR'));let busy=false;
const tick=setInterval(async()=>{if(busy)return;busy=true;try{await runtime.tick();}catch{errors.push('NATIVE_TICK_ERROR');}finally{busy=false;}},100);
const shot=async(name:string)=>{await page.evaluate(()=>window.scrollTo(0,0));await page.locator('#estate-workspace').screenshot({path:path.join(out,name)});};
try{
 await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForFunction("typeof state!=='undefined'&&state.operatorAuth==='authenticated'");await page.locator('[data-view="estate"]').click();await page.waitForFunction(()=>(window as any).AgentControlEstate.state().projection?.estate?.status==='EMPTY');
 for(const category of ['PASSIVE_INVENTORY','CAPABILITY_PROBES','REMOTE_HOST_DISCOVERY'])await page.locator(`[name="estate-category"][value="${category}"]`).check();await page.locator(`[name="estate-target"][value="${alias}"]`).check();await page.locator('#estate-video').check();await page.locator('#estate-grant').click();await page.waitForFunction(()=>Boolean((window as any).AgentControlEstate.state().permissionId));await shot('01-selected-scope.png');await page.locator('.estate-scope summary').click();
 const snapshots=[];const startedAt=new Date().toISOString();
 for(let pass=1;pass<=3;pass++){
  const before=estate.latest()?.id??null;await page.locator('#estate-run').click();await page.waitForFunction(old=>{const s=(window as any).AgentControlEstate.state().projection?.estate;return s?.snapshotId!==old&&['COMPLETED','PARTIAL'].includes(s?.status);},before,{timeout:150000});
  const snapshot=estate.latest()!;snapshots.push(snapshot);write(`snapshot-${pass}.json`,snapshot);write(`replay-${pass}.json`,estate.replay(snapshot.id));
  assert.ok(snapshot.entities.some(e=>e.id==='host:controller-local'&&e.state==='VERIFIED'));await shot(`0${pass+1}-native-pass-${pass}.png`);await page.waitForTimeout(3500);
  await page.evaluate(id=>(window as any).AgentControlEstate.select(id),`host:${alias}`);await page.waitForTimeout(3500);
 }
 const final=snapshots.at(-1)!,remote=final.entities.find(e=>e.id===`host:${alias}`)!;
 const pins=snapshots.map(s=>s.entities.find(e=>e.id==='host:controller-local')?.attributes.physicalIdentityDigest);
 const localContinuity=pins.every(p=>typeof p==='string'&&p===pins[0]);
 const remoteAccepted=remote?.state==='AVAILABLE';
 await shot('05-remote-binding-verdict.png');await page.waitForTimeout(4000);
 await page.locator('[data-view="factory"]').click();await page.waitForFunction(()=>(window as any).AgentControlFactory.state().transport==='CONNECTED');
 const lastRun=runtime.ledger.list().find(r=>r.id===final.runId)!;assert.equal(lastRun.status,'SUCCEEDED');await page.evaluate(id=>(window as any).AgentControlFactory.inspect(`job:${id}`),lastRun.id);await page.locator('#factory-workspace').screenshot({path:path.join(out,'06-native-job.png')});await page.waitForTimeout(5000);
 await page.evaluate(id=>(window as any).AgentControlFactory.inspect(`evidence:${id}`),lastRun.artifacts[0]);await page.locator('#factory-workspace').screenshot({path:path.join(out,'07-native-receipt.png')});await page.waitForTimeout(5000);
 await page.locator('[data-view="estate"]').click();await page.waitForFunction(()=>(window as any).AgentControlEstate.state().active);await page.evaluate(id=>(window as any).AgentControlEstate.select(id),`host:${alias}`);await shot('08-final-verdict.png');await page.waitForTimeout(7000);
 await page.evaluate(()=>(window as any).AgentControlEstate.stopRecording());await page.waitForFunction(()=>!(window as any).AgentControlEstate.state().recording);const bytes=await page.evaluate(()=>(window as any).AgentControlEstate.captureBytes());assert.ok(bytes.length>10000);fs.writeFileSync(path.join(out,'estate-native-blocker.webm'),Buffer.from(bytes),{mode:0o600});write('video-manifest.json',await page.evaluate(()=>(window as any).AgentControlEstate.captureManifest()));write('factory-replay.json',await page.evaluate(()=>(window as any).AgentControlFactory.replay()));
 const permission=estate.assertPermission(final.permissionId);write('permission.json',permission);write('native-runs.json',runtime.ledger.list());write('native-artifacts.json',runtime.ledger.list().flatMap(r=>r.artifacts.map(id=>{const {storageRef,...record}=runtime.artifacts.get(id)!;return{id,record,value:runtime.artifacts.read(id)};})));
 await page.setViewportSize({width:390,height:844});await shot('09-mobile.png');assert.deepEqual(errors,[]);
 const verdict={candidateCommit,candidateDirty,resourceAlias:alias,sourceConfigurationSha256:createHash('sha256').update(original).digest('hex'),authorisationDigest:authorisation,startedAt,completedAt:new Date().toISOString(),nativeJobs:runtime.ledger.list().map(r=>({id:r.id,status:r.status,selectedWorkers:r.selectedWorkers})),physicalHostsVerified:1+(remoteAccepted?1:0),configuredRemoteState:remote.state,remoteAccepted,localContinuity,remoteContinuity:remoteAccepted?'NOT_YET_PHYSICALLY_QUALIFIED':'BLOCKED',physicalUnreachableRecovery:'NOT_PHYSICALLY_QUALIFIED',entities:final.entities.length,relationships:final.relationships.length,remoteObservedEntities:final.entities.filter(e=>e.attributes.execution==='REMOTE'&&['AVAILABLE','VERIFIED','DEGRADED'].includes(e.state)).length,comparison:final.comparison,snapshotSha256:estateHash(final),eventChainHead:final.events.at(-1)?.sha256,browserErrors:errors,overall:'BLOCKED',limits:['Transport fault/recovery tests are synthetic, not physical qualification.','No production logs, arbitrary file contents, credentials, route changes, service mutation or deployment.','Full two-host qualification requires a reachable approved resource and independently established identity pin.']};
 write('qualification.json',verdict);console.log(JSON.stringify({candidateCommit,candidateDirty,nativeJobs:verdict.nativeJobs.length,physicalHostsVerified:verdict.physicalHostsVerified,remoteState:remote.state,localContinuity,entities:verdict.entities,relationships:verdict.relationships,overall:verdict.overall}));
}catch{write('failure.json',{classification:'QUALIFICATION_DRIVER_FAILED',browserErrors:errors});await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw Error('estate_native_qualification_failed');}finally{clearInterval(tick);while(busy)await new Promise(r=>setTimeout(r,50));await browser.close();server.close();}
