import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';import {randomBytes,createHash} from 'node:crypto';import {once} from 'node:events';import assert from 'node:assert/strict';
import {ActionRegistry,ArtifactStore,JobRuntime,ResourceLockManager,RunLedger,WorkerRegistry} from '../src/control/job-runtime.js';
import {JobCatalog} from '../src/control/job-catalog.js';import {WorkParcelCoordinator,WorkParcelStore} from '../src/control/work-parcels.js';
import {FileHarnessEfficiencyLedger,createInvocationObservation} from '../src/control/harness-efficiency.js';
import {EnergyTelemetryRuntime,FileEnergyTelemetryStore,type PowerSample} from '../src/control/energy-telemetry.js';
import {PoeKnowledgeService} from '../src/control/poe-knowledge.js';
import {usageQuestionQuery} from '../src/control/usage-projection.js';
import {accountingSchema} from '../src/control/usage-accounting.js';import {usageProjection,usageAnswer} from '../src/control/usage-projection.js';
import {AgentControlService} from '../src/control/application-service.js';import {PtyRegistry} from '../src/control/pty.js';import {PoeRuntime} from '../src/control/poe.js';import {startWebDashboard} from '../src/control/web-server.js';
import {EnvironmentDiscoveryRuntime,LocalMachineDiscoveryAdapter} from '../src/control/environment-discovery.js';import {chromium} from 'playwright-core';

// Physical closure uses existing resident services and canonical stores only.
const jsonMode=false,representative=false;
const workload={id:'ordered-integer-list-1-to-100',prompt:'Return the integers 1 through 100 inclusive in ascending order, one integer per line. No title, no punctuation, no markdown, and no commentary.',maxTokens:512};
const replay=process.argv.includes('--capture-existing');const root=path.resolve(process.argv[2]??'');if(!process.argv[2]||!replay&&fs.existsSync(root))throw Error('new_evidence_directory_required');fs.mkdirSync(root,{recursive:true,mode:0o700});
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const ledger=new FileHarnessEfficiencyLedger(path.join(root,'model-invocations.json')),energy=new EnergyTelemetryRuntime(new FileEnergyTelemetryStore(path.join(root,'energy.json')));
const discovery=new EnvironmentDiscoveryRuntime({file:path.join(root,'discovery.json'),configurationRevision:()=> 'usage-qualification/v1',config:()=>({resources:[],models:[],providers:[],services:[],lanes:[]} as any),adapters:[new LocalMachineDiscoveryAdapter()]});
const scan=replay?discovery.projection().latest!:await discovery.discover({mode:'QUICK_RESCAN',testing:'QUICK_TEST',includeRemote:false,includeMemory:false}),machine=scan.items.find(i=>i.kind==='MACHINE')!;
function residentIdentity(port:number){for(const pid of fs.readdirSync('/proc').filter(v=>/^\d+$/.test(v))){try{const args=fs.readFileSync('/proc/'+pid+'/cmdline','utf8').split('\0');if(!args[0]?.includes('llama-server'))continue;const portIndex=args.indexOf('--port');if(portIndex<0||args[portIndex+1]!==String(port))continue;const modelIndex=args.indexOf('--model')>=0?args.indexOf('--model'):args.indexOf('-m');const modelFile=args[modelIndex+1];if(modelIndex<0||!modelFile)continue;const digest=(file:string)=>execFileSync('sha256sum',[file],{encoding:'utf8',timeout:30000}).split(' ')[0]!;return {modelSha256:digest(modelFile),runtimeSha256:digest('/proc/'+pid+'/exe')};}catch{}}return {modelSha256:null,runtimeSha256:null};}
function power():PowerSample {const raw=execFileSync('nvidia-smi',['--query-gpu=power.draw,utilization.gpu','--format=csv,noheader,nounits'],{encoding:'utf8',timeout:3000}).trim().split('\n')[0]!.split(',').map(Number);return {at:new Date().toISOString(),nodeId:machine.id,scope:'GPU_ONLY',watts:Number.isFinite(raw[0])?raw[0]!:null,gpuUtilizationPercent:raw[1],authority:Number.isFinite(raw[0])?'MEASURED':'UNAVAILABLE',source:'nvidia-smi:gpu0',limitations:['GPU board telemetry; other resident services exist; exclusive workload attribution unproven']};}
const initial=replay?null:power();if(initial&&(initial.gpuUtilizationPercent??100)>10)throw Error('physical_qualification_deferred_gpu_busy');
const actions=new ActionRegistry();let parcelId='';
for(const [i,port]of [8081,8080,8081].entries())actions.registerReadOnly(`usage.local-${i}@1.0.0`,async context=>{
  const base=`http://127.0.0.1:${port}`,inventory=await(await fetch(base+'/v1/models',{signal:AbortSignal.timeout(3000)})).json() as any,model=inventory.data?.[0]?.id;if(typeof model!=='string')throw Error('resident_model_unavailable');
  let pre=power();for(let retry=0;retry<12&&(pre.gpuUtilizationPercent??100)>10;retry++){await new Promise(r=>setTimeout(r,1000));pre=power();}if((pre.gpuUtilizationPercent??100)>10)throw Error('physical_qualification_deferred_gpu_busy');
  const baselineSamples:PowerSample[]=[];for(let n=0;n<12;n++){baselineSamples.push(power());await new Promise(r=>setTimeout(r,250));}
  if(baselineSamples.some(s=>(s.gpuUtilizationPercent??100)>10))throw Error('physical_qualification_deferred_baseline_busy');
  const gpuProcesses=execFileSync('nvidia-smi',['--query-compute-apps=pid,process_name,used_gpu_memory','--format=csv,noheader'],{encoding:'utf8'}).trim().split('\n').map(line=>{const [pid,name,memory]=line.split(',').map(s=>s.trim());return {pid:Number(pid),executable:path.basename(name!),memory};});
  const id=`usage-closure-${context.run.id}`,startedAt=new Date().toISOString(),samples:PowerSample[]=[power()],sampleStart=Date.now();let sampling=false,expectedSamples=1,skippedSamples=0;const skippedAt:string[]=[];
  const timer=setInterval(()=>{expectedSamples++;if(sampling)return;const elapsed=Date.now()-sampleStart;if(i===2&&elapsed>=1500&&elapsed<3100){skippedSamples++;skippedAt.push(new Date().toISOString());return;}sampling=true;try{samples.push(power());}finally{sampling=false;}},200);
  let body:any=null,passed=false,failure:string|null=null;
  try{const response=await fetch(base+'/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'user',content:workload.prompt}],max_tokens:workload.maxTokens,temperature:0,cache_prompt:false,...(jsonMode?{response_format:{type:'json_object'}}:{})}),signal:AbortSignal.any([context.signal,AbortSignal.timeout(30000)])});if(!response.ok)throw Error('provider_http_'+response.status);body=await response.json();const content=String(body.choices?.[0]?.message?.content??'').trim();if(representative){try{const v=JSON.parse(content);passed=Object.keys(v).sort().join(',')==='A,B,C'&&v.A===1050&&v.B===1050&&v.C===1000;}catch{passed=false;}}else passed=content===Array.from({length:100},(_,i)=>String(i+1)).join('\n');}catch(e){failure=e instanceof Error?e.message:'inference_failed';}finally{clearInterval(timer);expectedSamples++;samples.push(power());}
  const completedAt=new Date().toISOString(),identity=residentIdentity(port),u=body?.usage??{},number=(v:unknown)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0?v:null;
  const accounting=accountingSchema.parse({schema:'agent-control.usage-accounting/v1',revision:0,parentInvocationId:null,retryOfInvocationId:null,parcelId,batonId:null,providerRequestId:typeof body?.id==='string'?body.id:null,modelRevision:identity.modelSha256,runtime:'llama.cpp',runtimeVersion:identity.runtimeSha256,machine:machine.id,hardware:'NVIDIA Quadro P5000',jobType:workload.id+(i===2?'-observer-gap':''),executionKind:'LOCAL',provenance:{kind:'NATIVE',source:'loopback-llama-chat-adapter',sourceVersion:jsonMode?'2/json-mode':'1',migrationVersion:null,at:startedAt},semantics:{id:'llama-chat-completions/v1',input:'INCLUDES_CACHE',reasoning:'UNKNOWN',total:'INPUT_PLUS_OUTPUT',billing:'UNKNOWN'},evidence:{input:number(u.prompt_tokens),cached:number(u.prompt_tokens_details?.cached_tokens),cacheWrite:null,output:number(u.completion_tokens),reasoning:null,total:number(u.total_tokens)},pricing:null,reportedCost:null,localApiChargeKnownZero:true});
  const observation=createInvocationObservation({id,jobId:context.run.jobId,runId:context.run.id,stepId:'execute',taskId:'usage-physical',laneId:'usage-controller',model,provider:'local-llama-'+(port===8081?0:1),harnessProfile:'STANDARD',executionStrategy:'bounded-existing-local-model',startedAt,completedAt,accounting,outcome:failure?'FAILED':'COMPLETE',recipeFingerprint:hash({task:workload.id,maxTokens:workload.maxTokens,temperature:0,responseFormat:jsonMode?'json_object':'text'}),evidenceIds:[`response-sha256:${hash(body)}`]});
  ledger.record(observation);ledger.markVerification([id],passed?'PASS':'FAIL',passed?'SUCCEEDED':'FAILED');
  const measured=energy.recordMeasurement({invocationId:id,parcelId,stageId:'local-'+i,providerId:observation.provider,modelId:model,modelRevision:identity.modelSha256,runtime:'llama.cpp',runtimeVersion:identity.runtimeSha256,nodeId:machine.id,sensorId:'nvidia-gpu0',scope:'GPU_ONLY',samples,maxGapMs:700,attribution:'NOT_ATTRIBUTABLE',concurrentInvocationIds:[],concurrencyEvidence:['GPU process inventory sha256:'+hash(gpuProcesses),'Other resident inference and speech services exist; their request streams cannot be locked or attributed by this observer.'],methodology:'GPU board power at 200 ms and boundaries; maximum accepted interval 700 ms; controlled 1600 ms observer pause in third run only' ,conditions:'existing resident services',baselineMaxAgeMs:60000,tariffs:[],tokens:observation.usage.totalProcessedTokens,verified:passed,successful:passed});
  fs.writeFileSync(path.join(root,id+'-provider-response.json'),JSON.stringify({usage:body?.usage??null,response:body,responseFormat:jsonMode?'json_object':'text'}),{mode:0o600});
  fs.writeFileSync(path.join(root,id+'.json'),JSON.stringify({id,providerModel:model,usage:u,responseSha256:hash(body),validator:{workload:workload.id,expectedSha256:hash(Array.from({length:100},(_,i)=>String(i+1)).join('\n')),passed},failure,samples,baselineSamples,gpuProcesses,expectedSamples,observedSamples:samples.length,skippedSamples,skippedAt,sampleIntervalMs:200,gapExperiment:i===2,providerTimings:body?.timings??null,measurementId:measured.id,ledgerId:id},null,2),{mode:0o600});
  return {artifacts:[],evidence:[`accounting:${id}`,`energy:${measured.id}`],verification:passed?['exact-integer']:[],efficiencyInvocationIds:[id],detail:passed?'All 100 ordered integers verified':'Response did not pass exact ordered-list verifier'};
});
const catalog=new JobCatalog(actions.ids());for(let i=0;i<3;i++)catalog.addJob({apiVersion:'agent-control/v1',kind:'Job',metadata:{id:`usage-local-${i}`,name:'Qualify resident local accounting '+i,version:'1.0.0'},spec:{priority:'normal',concurrency:'allow',steps:[{id:'execute',action:`usage.local-${i}@1.0.0`,requires:['usage.qualification'],outputs:[],verification:['exact-integer']}]}});
const workers=new WorkerRegistry().register({id:'usage-controller',capabilities:['usage.qualification'],health:'healthy',capacity:1,active:0,observedAt:new Date().toISOString()}),runtime=new JobRuntime(catalog,actions,workers,new RunLedger(path.join(root,'runs.json')),new ArtifactStore(path.join(root,'artifacts')),new ResourceLockManager(path.join(root,'locks.json')),{approval:()=>false,efficiency:ledger});
const parcels=new WorkParcelCoordinator(runtime,new WorkParcelStore(path.join(root,'parcels.json')),{plan:()=>{throw Error('explicit_plan_required');}},ledger);
const parcel=replay?JSON.parse(fs.readFileSync(path.join(root,'execution-status.json'),'utf8')):parcels.submitApprovedPlan('Verify usage and GPU observation for two already resident local models','operator-authorised-bounded-usage-qualification',hash({root}),{objective:'Trace two local invocations into canonical usage reporting',planner:{kind:'deterministic',reason:'Explicit bounded qualification, no downloads or service changes'},stages:[{id:'local-0',name:'Resident coder controlled workload',job:'usage-local-0@1.0.0'},{id:'local-1',name:'Resident general same workload',job:'usage-local-1@1.0.0'},{id:'local-2',name:'Separate controlled observer gap',job:'usage-local-2@1.0.0'}]});parcelId=replay?parcel.parcelId:parcel.id;
for(let i=0;!replay&&i<8;i++){await parcels.tick();await runtime.tick();await parcels.tick();if(parcels.get(parcelId).endedAt)break;}
if(!replay)fs.writeFileSync(path.join(root,'execution-status.json'),JSON.stringify({parcelId,status:parcels.get(parcelId).status,invocations:ledger.list().length}));
const measuredRecords=energy.projection().executions;
if(!replay){const gap=measuredRecords.find(r=>r.stageId==='local-2');if(gap){assert.ok(gap.accounting!.excludedIntervals.some(g=>g.reason==='SAMPLE_GAP'));assert.ok(gap.accounting!.coverage<1);}}
const projection=usageProjection(ledger,energy.projection().executions,{period:'all'}),answer=usageAnswer(projection);assert.equal(projection.totals.calls,ledger.list().length);assert.equal(projection.totals.tokens.knownTotal,ledger.list().reduce((n,r)=>n+(r.usage.totalProcessedTokens??0),0));assert.deepEqual(answer.evidence.apiCost,projection.totals.apiCost);
const control=new AgentControlService({version:1,paused:false,lastRestorePoint:null,lanes:[]},new PtyRegistry(),undefined,'4.6.0-rc.1',()=>{}).configureProjection({jobRuntime:runtime,workParcels:parcels,harnessEfficiency:ledger,energyTelemetry:energy,environmentDiscovery:discovery});
const knowledge=new PoeKnowledgeService({root:process.cwd(),version:'4.6.0-rc.1',sources:[],configuration:()=>({scope:'physical-usage-closure'}),live:(category,question)=>{if(category!=='usage')throw Error('category_not_in_qualification_scope');return control.usageAnswer(usageQuestionQuery(question??''));}});
const poeProof=[];
for(const question of ['What did that API call cost?','How many tokens did it use?','How much energy did that local run use?','What was the measurement coverage?','Was the local run cheaper than the API?']){
 const evidence=knowledge.enrich(question);assert.ok(evidence.facts.some(f=>f.label==='Live usage'));
 control.configureProjection({poe:new PoeRuntime({evidence:{overview:()=>evidence,resolve:()=>evidence}})});
 const conversation=control.createPoeConversation('dashboard','web-operator'),poe=await control.askPoe(conversation.id,question,'web-operator');
 const live=JSON.parse(String(poe.evidence.facts.find(f=>f.label==='Live usage')!.value));assert.equal(live.accountedUsage.tokens.knownTotal,projection.totals.tokens.knownTotal);assert.ok(live.comparisonLimitation.includes('attributable electricity'));
 poeProof.push({question,responseMode:poe.turn.responseMode,groundingPath:'PoeKnowledgeService -> AgentControlService.usageAnswer -> canonical stores -> PoeRuntime',text:poe.turn.text,evidence:poe.evidence});
}
fs.writeFileSync(path.join(root,'mallow-accounting-proof.json'),JSON.stringify(poeProof,null,2));
const allowedOrigins:string[]=[],token=randomBytes(32).toString('hex'),server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:token,allowedOrigins,assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');const base=`http://127.0.0.1:${(server.address() as any).port}`;allowedOrigins.push(base);const browserErrors:string[]=[];let browser;
try{browser=await chromium.launch({executablePath:'/snap/bin/chromium',headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1050}});page.on('pageerror',e=>browserErrors.push(e.message));await page.goto(base);await page.evaluate(token=>(globalThis as any).eval('state.token = '+JSON.stringify(token)+'; operatorAuthentication(state.token).then(value => {state.operatorAuth=value})'),token);await page.locator('[data-view="usage"]').click();await page.waitForFunction(()=>document.getElementById('usage-status')?.textContent?.includes('matching calls'));
  await page.waitForFunction(()=>!document.getElementById('estate-dashboard-heartbeat')?.textContent?.includes('authentication required'),{},{timeout:8000});
  const tabs=['Overview','Trend','Breakdown','Cache & retries','Energy','Local vs API','Model history','Invocations'];for(const [i,tab]of tabs.entries()){await page.getByRole('button',{name:tab,exact:true}).click();await page.screenshot({path:path.join(root,`${String(i+1).padStart(2,'0')}-${tab.replace(/[^a-zA-Z]+/g,'-').toLowerCase()}.png`),fullPage:true});}
  await page.getByRole('button',{name:'Inspect',exact:true}).first().click();await page.screenshot({path:path.join(root,'09-invocation-detail.png'),fullPage:true});
  await page.getByRole('button',{name:'Show Process',exact:true}).click();await page.locator('#runtime-map-workspace').waitFor();
  const mapped=await(await fetch(base+'/api/runtime-map?parcelId='+encodeURIComponent(projection.rows[0]!.parcel!),{headers:{Authorization:'Bearer '+token}})).json();assert.equal(mapped.parcelId,projection.rows[0]!.parcel);
  const traced=projection.rows[0]!,runNode=mapped.nodes.find((n:any)=>n.detail?.runId===traced.jobRun);assert.ok(runNode,'native_process_run_required');
  const estate=await(await fetch(base+'/api/estate-map',{headers:{Authorization:'Bearer '+token}})).json();assert.ok(estate.nodes.some((n:any)=>n.id===traced.machine),'discovered_machine_required');
  fs.writeFileSync(path.join(root,'process-estate-trace.json'),JSON.stringify({invocationId:traced.id,runId:traced.jobRun,parcelId:traced.parcel,processNodeId:runNode.id,machineId:traced.machine,processEvidence:runNode.evidence,usageLinks:traced.links,nativeExecution:true},null,2));
  await page.screenshot({path:path.join(root,'11-process-trace.png'),fullPage:true});
  await page.locator('[data-view="usage"]').click();await page.waitForFunction(()=>document.getElementById('usage-status')?.textContent?.includes('matching calls'));await page.getByRole('button',{name:'Invocations',exact:true}).click();await page.getByRole('button',{name:'Inspect',exact:true}).first().click();
  await page.getByRole('button',{name:'Show in Estate',exact:true}).click();await page.locator('#runtime-map-workspace').waitFor();await page.getByRole('button',{name:'Show usage',exact:true}).waitFor();await page.screenshot({path:path.join(root,'12-estate-trace.png'),fullPage:true});await page.getByRole('button',{name:'Show usage',exact:true}).click();await page.waitForFunction(()=>document.getElementById('usage-status')?.textContent?.includes('matching calls'));assert.ok((await page.locator('#usage-status').textContent())?.includes('3 matching calls'),'estate_usage_round_trip_count');await page.getByRole('button',{name:'Overview',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'10-mobile.png'),fullPage:true});
  const payload=await(await fetch(base+'/api/usage?period=all',{headers:{Authorization:'Bearer '+token}})).json();assert.equal(payload.totals.tokens.knownTotal,projection.totals.tokens.knownTotal);fs.writeFileSync(path.join(root,'projection.json'),JSON.stringify(payload,null,2));
}finally{await browser?.close();await new Promise<void>(resolve=>server.close(()=>resolve()));}
fs.writeFileSync(path.join(root,replay?'qualification-recapture.json':'qualification.json'),JSON.stringify({sourceCommit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),sourceDirty:!!execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim(),parcelId,status:parcels.get(parcelId).status,invocations:ledger.list().length,tokens:projection.totals.tokens,verifiedSuccessfulJobs:projection.totals.successfulJobs,measurements:energy.projection().executions.map(e=>({id:e.id,scope:e.scope,grossWh:e.grossWh,coverage:e.accounting!.coverage,attribution:e.accounting!.attribution})),browserErrors,privacyReview:'PENDING_VISUAL_REVIEW',wholeNodeEnergy:'BLOCKED_EXTERNAL',cpuPackageEnergy:'UNAVAILABLE_PERMISSION',apiSpend:'No paid API used; existing local services only',electricityCost:'UNAVAILABLE: no attributable whole-node meter or operator tariff',limitations:['Bounded controlled workload on two resident models; not a general qualification or statistically meaningful efficiency ranking','Existing shared GPU observation cannot establish energy per job','Model/runtime file hashes describe resident process references, not a new model-load attestation'],poeAnswer:answer},null,2));console.log(JSON.stringify({root,parcelId,calls:projection.totals.calls,status:parcels.get(parcelId).status,browserErrors}));
