/** Matched local metadata scopes; no model requests and no synthetic topology. */
import fs from 'node:fs';import path from 'node:path';import {once} from 'node:events';import type {AddressInfo} from 'node:net';import {EstateDiscovery,registerEstateDiscovery} from '../src/control/estate-discovery.js';import {emptyConfig} from '../src/control/config.js';import {ActionRegistry,WorkerRegistry,createJobRuntime} from '../src/control/job-runtime.js';import {JobCatalog} from '../src/control/job-catalog.js';import {AgentControlService} from '../src/control/application-service.js';import {PtyRegistry} from '../src/control/pty.js';import {startWebDashboard} from '../src/control/web-server.js';
const root=path.resolve(process.env.ESTATE_PERFORMANCE_DIR??'../estate-performance'),rows:any[]=[];fs.mkdirSync(root,{recursive:true});process.env.AGENT_CONTROL_ACTIVITY_LOG=path.join(root,'activity.jsonl');
for(const [index,enabled] of [false,true,false,true,false,true,false,true].entries()){
 const isolated=path.join(root,String(index)),runtime=createJobRuntime(path.join(isolated,'jobs'),new JobCatalog(),new ActionRegistry(),new WorkerRegistry()),estate=new EstateDiscovery({root:path.join(isolated,'estate'),config:emptyConfig});registerEstateDiscovery(runtime,estate);const service=new AgentControlService({lanes:[]} as never,new PtyRegistry()).configureProjection({jobRuntime:runtime}),server=startWebDashboard(service,{host:'127.0.0.1',port:0,operatorToken:'isolated-performance',estate,estateEnabled:enabled,factoryEnabled:false});await once(server,'listening');const address=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;let bytes=0,frames=0;const abort=new AbortController();let consume:Promise<void>|null=null;
 if(enabled){const response=await fetch(address+'/api/estate/events',{headers:{Authorization:'Bearer isolated-performance'},signal:abort.signal});consume=(async()=>{const reader=response.body!.getReader();try{while(true){const {value,done}=await reader.read();if(done)break;bytes+=value.length;frames+=new TextDecoder().decode(value).split('event: factory.frame').length-1;}}catch{/* Explicitly disconnected after measured run. */}})();}
 const permission=estate.grant({categories:['PASSIVE_INVENTORY','SERVICE_ENUMERATION'],targetIds:[]},'performance');global.gc?.();const rssBefore=process.memoryUsage().rss,cpu=process.cpuUsage(),start=performance.now();const run=runtime.createRun('discover-estate@1.0.0',{permissionId:permission.id},{type:'manual',actor:'performance'});await runtime.tick();await new Promise<void>(resolve=>setImmediate(resolve));const cpuUsed=process.cpuUsage(cpu),durationMs=performance.now()-start;rows.push({index,warmup:index<2,visualisation:enabled?'STREAM_CONNECTED':'DISABLED',durationMs,cpuMicroseconds:cpuUsed.user+cpuUsed.system,rssBefore,rssAfter:process.memoryUsage().rss,streamBytes:bytes,frames,status:runtime.ledger.get(run.id)?.status,entities:estate.latest()?.entities.length,events:estate.latest()?.events.length});abort.abort();await consume;server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));
}
const mean=(enabled:string)=>{const r=rows.filter(r=>!r.warmup&&r.visualisation===enabled);return{runs:r.length,wallMs:r.reduce((n,r)=>n+r.durationMs,0)/r.length,cpuMs:r.reduce((n,r)=>n+r.cpuMicroseconds,0)/r.length/1000};};const result={mode:'REAL_LOCAL_METADATA_MATCHED_SCOPE',scope:'OS, GPU, registered local worker, running service names; no logs, network scanning or inference',rows,means:{disabled:mean('DISABLED'),connected:mean('STREAM_CONNECTED')},limitations:['Three measured observations per mode after warmup; descriptive, not a statistical performance guarantee.','Same process and shared host; RSS high-water values are not allocation or leak measurements.','SSE overhead measured here; browser rendering and video costs are measured separately in physical qualification.']};fs.writeFileSync(path.join(root,'performance.json'),JSON.stringify(result,null,2)+'\n');process.stdout.write(JSON.stringify(result.means)+'\n');
