import assert from 'node:assert/strict';
import {createHash,randomBytes} from 'node:crypto';
import {spawn,execFileSync} from 'node:child_process';
import {createServer} from 'node:http';
import {createRequire} from 'node:module';
import {once} from 'node:events';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const require=createRequire(import.meta.url),{chromium}=require('playwright-core');
const root=path.resolve(process.env.AGENT_CONTROL_45_LIVE_EVIDENCE_ROOT??'qualification/agent-control-4.5-release-gate-20260912/live-poe-run');
const stateRoot=path.join(root,'runtime'),rawDir=fs.mkdtempSync(path.join(os.tmpdir(),'ac45-live-video-')),videoDir=path.join(rawDir,'video');
const pair=process.env.AGENT_CONTROL_45_LIVE_PAIR??'qwen-to-codex';
const qualificationFile=process.env.AGENT_CONTROL_MEMORY_ROUTE_QUALIFICATIONS;
const enforceRouteQualifications=process.env.AGENT_CONTROL_MEMORY_ENFORCE_ROUTE_QUALIFICATION==='1';
if(enforceRouteQualifications&&!qualificationFile)throw new Error('memory_route_qualification_file_required');
const prompt=`POE, run the Agent Control 4.5 physical cross-model Your Memories pair ${pair}. Have the writer persist governed project memory, start the different reader cold without its transcript, reconstruct the work, execute the exact next action, and independently verify it.`;
fs.mkdirSync(videoDir,{recursive:true});fs.mkdirSync(root,{recursive:true,mode:0o700});
const snapshots=[],startedAt=new Date().toISOString(),token=randomBytes(18).toString('hex');

function readState(name,fallback){try{return JSON.parse(fs.readFileSync(path.join(stateRoot,name),'utf8'));}catch{return fallback;}}
function readRoot(name,fallback){try{return JSON.parse(fs.readFileSync(path.join(root,name),'utf8'));}catch{return fallback;}}
function state(){
  const parcels=readState('work-parcels.json',{parcels:[]}).parcels??[],runs=readState('runs.json',{runs:[]}).runs??[],poe=readState('poe.json',{conversations:[]});
  const report=readRoot('cross-model-memory-qualification.json',null),parcel=parcels.at(-1)??null;
  return{at:new Date().toISOString(),prompt,parcel,runs:runs.map(run=>({id:run.id,jobId:run.jobId,status:run.status,startedAt:run.startedAt,completedAt:run.completedAt,error:run.error??null,route:run.trigger?.modelRoute?{provider:run.trigger.modelRoute.providerId,model:run.trigger.modelRoute.modelId,node:run.trigger.modelRoute.nodeId}:null})),poe,report};
}
const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Agent Control 4.5 — Live Qualification</title><style>
*{box-sizing:border-box}body{margin:0;background:#07111d;color:#e8f4ff;font:16px system-ui,sans-serif}.top{height:70px;display:flex;align-items:center;justify-content:space-between;padding:0 28px;border-bottom:1px solid #20364b;background:#091521}.brand{font-size:24px;font-weight:800}.live{color:#63f6ad;border:1px solid #2b9862;border-radius:18px;padding:7px 13px}.wrap{padding:24px 28px}.grid{display:grid;grid-template-columns:1.55fr .8fr;gap:18px}.card{background:#0d1b29;border:1px solid #294258;border-radius:14px;padding:18px;margin-bottom:18px}.card h2{margin:0 0 12px;font-size:19px}.prompt{background:#091521;border-left:4px solid #59e6ff;padding:14px;line-height:1.5}.stages{display:grid;gap:11px}.stage{display:grid;grid-template-columns:1fr 120px;gap:12px;padding:14px;border:1px solid #31485c;border-radius:10px;background:#101f2d}.stage.RUNNING{border-color:#48bfff;box-shadow:0 0 18px #2186ae33}.stage.SUCCEEDED{border-color:#37c878;background:#0d2a24}.stage.FAILED,.stage.BLOCKED{border-color:#ef6175;background:#301824}.badge{justify-self:end;font-weight:800}.route{color:#9bc2df;font-size:14px;margin-top:6px}.hash{font:12px ui-monospace,monospace;color:#6ee7c5;word-break:break-all}.run{padding:10px 0;border-bottom:1px solid #23384b}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.metric{background:#102536;padding:13px;border-radius:10px}.big{font-size:26px;font-weight:800;color:#70f0b0}.muted{color:#8faec7}.footer{font-size:13px;color:#7396af}.pulse{width:10px;height:10px;background:#5af1a4;border-radius:50%;display:inline-block;animation:p 1.3s infinite}@keyframes p{50%{opacity:.25;transform:scale(.7)}}
</style></head><body><div class="top"><div class="brand">🤖 Agent Control <span class="muted">4.5 EXPERIMENTAL</span></div><div class="live"><span class="pulse"></span> LIVE GOVERNED RUNTIME</div></div><div class="wrap"><div class="grid"><main><div class="card"><h2>POE operator request</h2><div id="prompt" class="prompt"></div></div><div class="card"><h2>Job → Work Parcel → verified continuation</h2><div id="parcel" class="muted">Waiting for POE to create the Work Parcel…</div></div></main><aside><div class="card"><h2>Live accounting</h2><div id="metrics" class="metrics"></div></div><div class="card"><h2>Provider runs</h2><div id="runs" class="muted">No model run yet.</div></div><div class="card"><h2>Evidence integrity</h2><div id="integrity" class="muted">Durable state is observed read-only every second.</div></div></aside></div><div class="footer">Qualification observer driven only by live Agent Control durable stores. This is not a replay. No private reasoning or credentials are displayed.</div></div><script>
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function tick(){const s=await fetch('/state?token=${token}').then(r=>r.json());document.querySelector('#prompt').textContent=s.prompt;const p=s.parcel;if(p){document.querySelector('#parcel').innerHTML='<div class="route"><b>'+esc(p.id)+'</b> · '+esc(p.status)+' · '+esc(p.objective)+'</div><div class="stages">'+p.stages.map(x=>'<div class="stage '+esc(x.status)+'"><div><b>'+esc(x.id)+'</b><div class="route">'+esc(x.actualRoute?.provider??'Agent Control')+' / '+esc(x.actualRoute?.model??x.job?.id??'control')+' @ '+esc(x.actualRoute?.providerExecutionNodeId??x.actualRoute?.workloadNodeId??'controller')+'</div>'+(x.baton?.sha256?'<div class="hash">sealed baton '+esc(x.baton.sha256)+'</div>':'')+'</div><div class="badge">'+esc(x.status)+'</div></div>').join('')+'</div>';}document.querySelector('#runs').innerHTML=s.runs.length?s.runs.map(r=>'<div class="run"><b>'+esc(r.jobId)+'</b><div>'+esc(r.status)+' · '+esc(r.route?.provider??'control')+' / '+esc(r.route?.model??'deterministic')+'</div><div class="hash">'+esc(r.id)+'</div></div>').join(''):'No model run yet.';const row=s.report?.matrix?.[0],u=row?.usage??{},qa=row?.routeQualification;document.querySelector('#metrics').innerHTML='<div class="metric"><div class="muted">Input</div><div class="big">'+esc(u.inputTokens??'—')+'</div></div><div class="metric"><div class="muted">Output</div><div class="big">'+esc(u.outputTokens??'—')+'</div></div><div class="metric"><div class="muted">Total</div><div class="big">'+esc(u.totalTokens??'—')+'</div></div>';document.querySelector('#integrity').innerHTML=row?'<b>Independent verification: '+esc(row.result)+'</b>'+(qa?'<div><b>Route gate: '+esc(qa.decision)+'</b></div><div>'+esc(qa.reasons.join('; ')||'requested route qualified')+'</div><div class="hash">selected '+esc(qa.selected?.writer?.modelId)+' → '+esc(qa.selected?.reader?.modelId)+'</div>':'')+'<div>Cold reconstruction '+esc(row.reconstructionAccuracy)+'%</div><div>Continuation '+(row.continuationSuccess?'PASS':'FAIL')+'</div><div class="hash">memory '+esc(row.memorySha256)+'</div>':'Durable state is observed read-only every second.';}tick();setInterval(tick,1000);
</script></body></html>`;
const server=createServer((req,res)=>{const url=new URL(req.url,'http://127.0.0.1');if(url.pathname==='/state'&&url.searchParams.get('token')===token){const value=state();snapshots.push(value);res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(value));return;}res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(html);});server.listen(0,'127.0.0.1');await once(server,'listening');
const address=server.address(),browser=await chromium.launch({headless:true,executablePath:process.env.AGENT_CONTROL_CHROMIUM??'/snap/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']}),context=await browser.newContext({viewport:{width:1920,height:1080},recordVideo:{dir:videoDir,size:{width:1920,height:1080}},colorScheme:'dark'}),page=await context.newPage(),video=page.video(),browserErrors=[];
page.on('pageerror',error=>browserErrors.push(error.message));page.on('console',message=>{if(message.type()==='error')browserErrors.push(message.text());});await page.goto(`http://127.0.0.1:${address.port}`,{waitUntil:'networkidle'});await page.waitForTimeout(2500);
const child=spawn(process.execPath,['--import','tsx','scripts/qualify-cross-model-memory-4.5.ts'],{cwd:process.cwd(),env:{...process.env,AGENT_CONTROL_CROSS_MODEL_MEMORY_ROOT:root,AGENT_CONTROL_MEMORY_PAIR_FILTER:pair,AGENT_CONTROL_MEMORY_POE_FLOW:'1',...(qualificationFile?{AGENT_CONTROL_MEMORY_ROUTE_QUALIFICATIONS:qualificationFile}:{}),...(enforceRouteQualifications?{AGENT_CONTROL_MEMORY_ENFORCE_ROUTE_QUALIFICATION:'1'}:{})},stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',chunk=>stdout+=chunk);child.stderr.on('data',chunk=>stderr+=chunk);const [code]=await once(child,'exit');await page.waitForTimeout(6500);await page.screenshot({path:path.join(root,'live-runtime-final.png'),fullPage:true});await context.close();const raw=await video.path();await browser.close();server.close();
const output=path.join(root,'agent-control-4.5-live-poe-memory-qualification.mp4');execFileSync('ffmpeg',['-nostdin','-y','-loglevel','error','-i',raw,'-an','-c:v','libx264','-preset','medium','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart',output]);fs.rmSync(rawDir,{recursive:true,force:true});
fs.writeFileSync(path.join(root,'live-runtime-snapshots.json'),JSON.stringify({schema:'agent-control.live-memory-observer/v1',startedAt,completedAt:new Date().toISOString(),prompt,snapshots},null,2)+'\n',{mode:0o600});
const report=readRoot('cross-model-memory-qualification.json',null);assert.equal(code,0,`qualification_failed:${redact(stderr).slice(-500)}`);assert.equal(report?.verdict,'PASS_PHYSICAL_CROSS_MODEL_MEMORY');assert.ok(snapshots.some(s=>s.parcel?.status==='RUNNING'),'live_running_state_not_observed');assert.ok(snapshots.some(s=>s.parcel?.stages?.some(x=>x.status==='RUNNING')),'live_stage_transition_not_observed');if(enforceRouteQualifications)assert.equal(report?.matrix?.[0]?.routeQualification?.decision,pair==='local-to-gemma-e4b'?'ESCALATE':'ALLOW');assert.equal(browserErrors.length,0);
const files=['cross-model-memory-qualification.json','cross-model-memory-transcript.md','live-runtime-final.png','live-runtime-snapshots.json','agent-control-4.5-live-poe-memory-qualification.mp4'].map(file=>{const bytes=fs.readFileSync(path.join(root,file));return{file,bytes:bytes.length,sha256:sha(bytes)};}),probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_entries','format=duration,size:stream=codec_name,width,height,r_frame_rate','-of','json',output],{encoding:'utf8'}));
fs.writeFileSync(path.join(root,'live-evidence-manifest.json'),JSON.stringify({schema:'agent-control.live-memory-evidence/v1',verdict:'PASS_GENUINE_RUNTIME_ACTIVITY_RECORDED',implementationCommit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),qualificationExitCode:code,browserErrors,providerOutputPersistedOnlyThroughSanitizedQualificationEvidence:true,files,video:probe},null,2)+'\n',{mode:0o600});
process.stdout.write(JSON.stringify({root,verdict:'PASS_GENUINE_RUNTIME_ACTIVITY_RECORDED',files,stdout:redact(stdout).slice(-1200)},null,2)+'\n');
function sha(value){return createHash('sha256').update(value).digest('hex');}
function redact(value){return String(value).replace(/(?:sk|nvapi)-[A-Za-z0-9._-]+/g,'[REDACTED]').replace(/Bearer\s+\S+/gi,'Bearer [REDACTED]');}
