import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../assets/dashboard/dashboard-poe.js',import.meta.url),'utf8');
const code=source.slice(source.indexOf('  function sharedSpeechAudioBlob('),source.indexOf('  async function speakShared('));
const create=vm.runInNewContext(code+';createSharedPlayback',{Blob,ArrayBuffer,DataView,Uint8Array});
const mime='audio/pcm;rate=24000;channels=1;format=s16le';
function fixture(){const nodes=[],states=[],controller=new AbortController();const context={currentTime:0,destination:{},decodeAudioData:async bytes=>({duration:(bytes.byteLength-44)/48000}),createBufferSource(){const n={connect(){},disconnect(){this.disconnected=true;},start(at){this.at=at;},stop(){this.stopped=true;}};nodes.push(n);return n;}};return {context,nodes,states,controller,player:create(context,controller.signal,s=>states.push(s),6)};}
const second=()=>new Uint8Array(48000);
test('six seconds buffer then continuous clock scheduling without waiting for playback',async()=>{const f=fixture();for(let i=0;i<5;i++)await f.player.add(second(),mime);assert.equal(f.nodes.length,0);await f.player.add(second(),mime);assert.equal(f.nodes.length,6);await f.player.add(second(),mime);assert.equal(f.nodes.length,7);for(let i=1;i<7;i++)assert.equal(f.nodes[i].at,f.nodes[i-1].at+1);let done=false;const finished=f.player.finish().then(()=>{done=true;});await Promise.resolve();assert.equal(done,false);f.nodes.forEach(n=>n.onended());await finished;assert.equal(done,true);});
test('short reply flushes on completion without six-second audio requirement',async()=>{const f=fixture();await f.player.add(second(),mime);const done=f.player.finish();assert.equal(f.nodes.length,1);f.nodes[0].onended();await done;});
test('abort stops current and queued sources and prevents later scheduling',async()=>{const f=fixture();for(let i=0;i<6;i++)await f.player.add(second(),mime);f.controller.abort();assert.ok(f.nodes.every(n=>n.stopped&&n.disconnected));await f.player.add(second(),mime);assert.equal(f.nodes.length,6);await f.player.finish();});
test('abort during decoding cannot resurrect speech',async()=>{const f=fixture();let release;f.context.decodeAudioData=()=>new Promise(r=>{release=r;});const pending=f.player.add(second(),mime);await new Promise(r=>setImmediate(r));f.controller.abort();release({duration:1});await pending;await f.player.finish();assert.equal(f.nodes.length,0);});
test('starvation re-buffers rather than playing isolated one-second pieces',async()=>{const f=fixture();for(let i=0;i<6;i++)await f.player.add(second(),mime);f.context.currentTime=7;f.nodes.slice().forEach(n=>n.onended());await f.player.add(second(),mime);assert.equal(f.nodes.length,6);assert.equal(f.states.at(-1),'buffering');const done=f.player.finish();assert.equal(f.nodes.length,7);assert.ok(f.nodes[6].at>7);f.nodes[6].onended();await done;});
test('buffered abort and malformed payload fail safely',async()=>{const f=fixture();await assert.rejects(f.player.add(new Uint8Array(3),mime));await f.player.add(second(),mime);f.controller.abort();await f.player.finish();assert.equal(f.nodes.length,0);});
test('observed 1.27 generation ratio fits the buffer for a thirty-second reply',async()=>{const f=fixture();f.player=create(f.context,f.controller.signal,s=>f.states.push(s),8);for(let i=0;i<30;i++){f.context.currentTime=(i+1)*1.27;await f.player.add(second(),mime);}assert.equal(f.nodes.length,30);for(let i=1;i<30;i++)assert.equal(f.nodes[i].at,f.nodes[i-1].at+1);f.controller.abort();});
